### ISSUE TITLE
Keyframe graph not shown in Windows 10

### ISSUE THREAD

**Issue by alpody** [mltframework/shotcut#1000]
I use Shotcut version 20.11.28 on Windows  10 Home (1909 build: 18363.1256).

On some tutorial I see graph line  in keyframe tab. 

![firefox_NciqcvaDLS-2](https://user-images.githubusercontent.com/13846803/103549254-1e0c3e80-4eb8-11eb-92f9-6a22aa45f47b.png)

[yotube tutorial](https://www.youtube.com/watch?v=xA9BMDoBeFA&t=761sl)

In my project I can't change speed of block movement.

![yXK7V4M3wo-2](https://user-images.githubusercontent.com/13846803/103548498-f072c580-4eb6-11eb-9aa3-24d7010e8c8a.gif)

MyProject file:
[keyframe.zip](https://github.com/mltframework/shotcut/files/5765346/keyframe.zip)

Thank u 4 great work! 
It's really amazing tool

**Comment by ddennedy** [comment]
Not a bug, not all parameters support a line graph aka curve.
