### ISSUE TITLE
Timeline rendering incorrectly

### ISSUE THREAD

**Issue by LCBHSStudent** [mltframework/shotcut#1001]
shotcut version: v20.11.28
os: windows 10 20190.1000

when i click menu action in **m_externalGroup** to make video output full screen on one of my monitor,
and then clicked 'None' to cancel this operation,
timeline rendering become strange at this time:

![](https://img-blog.csdnimg.cn/2021010717493766.png)

seems only QQuickWidget components are affected...

could you plz give me some information about this problem? thanks!

**Comment by LCBHSStudent** [comment]
![2021010717493766](https://user-images.githubusercontent.com/52310370/103878447-5ab18300-50ce-11eb-9ce1-31be2f1e289e.png)

**Comment by bmatherly** [comment]
I am not able to reproduce this problem using your instructions.

Have you tried changing Settings->Display Method?

Why are you using programming terms? Did you compile Shotcut yourself?

**Comment by ddennedy** [comment]
I think this is a duplicate of  #757
The reason this reporter is speaking in terms of code is because he is making a fork of Shotcut. The workaround is to restart Shotcut.

**Comment by LCBHSStudent** [comment]
> I think this is a duplicate of #757
> The reason this reporter is speaking in terms of code is because he is making a fork of Shotcut. The workaround is to restart Shotcut.

> I am not able to reproduce this problem using your instructions.
> 
> Have you tried changing Settings->Display Method?
> 
> Why are you using programming terms? Did you compile Shotcut yourself?

I really appreciate both of your helpful reply，and i thnik I’d better try another way to implement the function i need...
