### ISSUE TITLE
Slide controls do not have decimals.

### ISSUE THREAD

**Issue by TheHackingDekuTre** [mltframework/shotcut#1003]
Windows 10, using version 21.01.12 (nightly) 

(21.10.12)
![image](https://user-images.githubusercontent.com/77210709/104400307-e769a000-5517-11eb-8b4b-ea4a8f832c4f.png) 

(20.11.28)
![image](https://user-images.githubusercontent.com/77210709/104400453-1ed84c80-5518-11eb-87e3-4fe37f3d11bb.png)

**Comment by bmatherly** [comment]
Occurs on Windows only, apparently since it works for me on Linux. I will look into it.

**Comment by ddennedy** [comment]
It is also a problem on macOS.

**Comment by ddennedy** [comment]
This seems to have fixed it for me:
```
--- src/qml/modules/Shotcut/Controls/SliderSpinner.qml
+++ src/qml/modules/Shotcut/Controls/SliderSpinner.qml
@@ -118,4 +118,5 @@ RowLayout {
         from: slider.from / ratio
         to: slider.to / ratio
+        decimals: parent.decimals
         stepSize: 1 / Math.pow(10, decimals)
         onValueChanged: slider.value = value * ratio
```

**Comment by bmatherly** [comment]
> This seems to have fixed it for me:

Yes. That fixed it: https://github.com/mltframework/shotcut/commit/eb5be4128c9fab3721356564186a8d27a285a761
