### ISSUE TITLE
Toolbar buttons are different sizes.

### ISSUE THREAD

**Issue by TheHackingDekuTre** [mltframework/shotcut#1004]
using windows 10, version 21.01.12 (nightly)

(21.01.12)
![image](https://user-images.githubusercontent.com/77210709/104400803-9a39fe00-5518-11eb-9bd4-be6607d625f5.png)

(20.11.28)
![image](https://user-images.githubusercontent.com/77210709/104400747-8b534b80-5518-11eb-8704-2bc7b2060705.png)

**Comment by bmatherly** [comment]
@ddennedy We can change the icon size by setting the button padding and icon size. Let me know which size you prefer (or maybe something in between)

**Comment by ddennedy** [comment]
I know about this, and initially I did not know about padding and how to control it until I saw something you did @bmatherly.

I am fine with the new size, but I expect some people will complain about it. The new approach does not try to manage size at all and leaves it up to Qt. This does make them more automatically adaptive to High DPI settings. In 20.11 on 200% HiDPI, the normal icon size is slightly too big and aliased, while View > Show Small Icons is nicer but possibly a tad too small and cramped. The new version seems to be just right on my 13" MacBook Retina, and the code is simpler. However, I can definitely understand complaints that it is too small for many screens, and more difficult to see for even the mildly visually impaired. 

One thing is for certain: if we are going to start managing the size, we should return to reading View > Show Small Icons (`settings.smallIcons`). I played around with this some tonight, but I did not come up with anything that I like. I could not seem to affect the icon size - only the button size and padding. @bmatherly if you want to propose something on one toolbar, for example, Keyframes is shorter, I will consider it.

**Comment by bmatherly** [comment]
In order to control the icon size precisely, it requires a combination of setting the padding, and the icon.width and icon.height
https://doc.qt.io/qt-5/qtquickcontrols2-icons.html
We can make our own button control derived from the ToolButton so that we can put all the logic in one place.

I tend to agree with your comments about letting Qt control the size. I propose that we leave this open as a low priority task and wait until we have some testing on different screen sizes and resolutions before deciding on a final path.

**Comment by ddennedy** [comment]
I did try that
```
            padding: 4
            implicitWidth: settings.smallIcons? 24 : 32
            implicitHeight: implicitWidth
            icon.width: settings.smallIcons? 16 : 24
            icon.height: icon.width
```
but it does not affect the icon size, only the padding. This is very clear by toggling Show Small Icons.
