### ISSUE TITLE
Sometimes there is no shotuct in task manager.

### ISSUE THREAD

**Issue by tasty0tomato** [mltframework/shotcut#1006]
Windows10 20H2
Shotcut 20.11.28
When I export vedio and my Cpu is 100%, there is no shotcu in the task manager

**Comment by bmatherly** [comment]
The Shotcut export process is called "melt.exe". Look for that in the task manager when you export.

**Comment by ddennedy** [comment]
I have seen where Shotcut does not show in Task Manager, but when I switch to another tab and back to Processes then it appears. I do not think we can do anything about that; we do not do anything to hide. Seems like a bug in Task Manager Processes view to me. The Details view never seems to have this problem.
