### ISSUE TITLE
Cannot start while using RDC on windows

### ISSUE THREAD

**Issue by heil-stalin** [mltframework/shotcut#101]
When using remote desktop connection, I cannot start the program.

I understand RDC acts like a video output, but I also have an AMD HD 7950 in my system. Is there any way to force the program to use my graphics card for the video card, but display over RDC?

**Comment by ddennedy** [comment]
This is fixed in v15.09, just tested to confirm it. You must have GPU processing disabled in Settings, and the new Settings option Display Method must be Automatic or DirectX.

**Comment by heil-stalin** [comment]
ily Dan <3
