### ISSUE TITLE
Filter menu shows wrong entries and scrolls by itself

### ISSUE THREAD

**Issue by bmatherly** [mltframework/shotcut#1014]
11) Select a new clip in the timeline. Open the Filters menu either by pressing the + icon or by pressing F on the keyboard. Now don’t move the mouse or press any keys. After about a second, for no reason the scroll bar on the Filters menu will start scrolling all the way down by itself. In this demo 4 I first do it by pressing the + icon and the second time I do it by pressing F.

In @DRM demo 11 the “Favorite” tab is selected and it looks like all filters are in the list, not just the favorite ones.

I have reproduced both of these and will look into them.

**Comment by ddennedy** [comment]
I reproduced the automatic scrolling too, but it is minor, and we should be conservative on changes in beta. If you find the filter state bug and the fix is simple, I am all for it.

**Comment by bmatherly** [comment]
I submitted a pull request and will let you judge the risk.
