### ISSUE TITLE
Email has incorrect new release?

### ISSUE THREAD

**Issue by DanaMW** [mltframework/shotcut#1024]
The email states v21.10.29  
The web page says v21.01.29

**Comment by ddennedy** [comment]
What email? Something automated through GitHub. This was an incorrect tag that was changed.

**Comment by DanaMW** [comment]
Yes the email from github. And the link was not found. I went to releases and found it myself.
![Screenshot_2021-01-30  mltframework shotcut  Release v21 10 29 - v21 10 29 - danamw gmail com - Gmail](https://user-images.githubusercontent.com/12940577/106369301-2021bb80-6305-11eb-90af-7878ad4a715b.png)

**Comment by ddennedy** [comment]
Thanks. Shit happens especially when you combine humans and automation.
