### ISSUE TITLE
I need your help very much

### ISSUE THREAD

**Issue by wanweiyang** [mltframework/shotcut#1026]
Hello, I'm sorry to disturb you. I have a problem. The UOS (Linux) system I use needs to compile shotcut and type it into DEB package. It can be compiled normally. After executing the program, I can't open the. MP4 file
I will compile this software on ARM platform MIPS platform and upload it to Debian. I need your help very much

When I compile on arm, I can't open the. MP4 file 

The project of shotcut DEB package is as follows: https://gitee.com/deepin-opensource/shotcut/tree/uos20.09

**Comment by ddennedy** [comment]
Stop spamming us.

**Comment by thiru31** [comment]
> Hello, I'm sorry to disturb you. I have a problem. The UOS (Linux) system I use needs to compile shotcut and type it into DEB package. It can be compiled normally. After executing the program, I can't open the. MP4 file I will compile this software on ARM platform MIPS platform and upload it to Debian. I need your help very much
> 
> When I compile on arm, I can't open the. MP4 file
> 
> The project of shotcut DEB package is as follows: https://gitee.com/deepin-opensource/shotcut/tree/uos20.09

Hey @wanweiyang @eszlari @bmatherly @ddennedy 
I'm curious if you've made any progress compiling and building Shotcut on clangARM64. Have you experimented with any specific steps to achieve this? Particularly, I'm interested in how you dealt with porting of dependencies that aren't supported on ARM, such as gopro2gpx and glaxnimate.

Looking forward to hearing about your experience!

Thanks in advance for sharing.

**Comment by ddennedy** [comment]
@thiru31 What are you planning to do with your arm64 build of Shotcut for Windows? Sell it in the Microsoft Store? I will make an official build myself when I buy one of the coming systems with the new Qualcomm Snapdragon X Elite chip. The current ARM Windows systems are not interesting enough to motivate me.

**Comment by magician31** [comment]
@ddennedy  Haha, if I had the ability to do that, I wouldn't keep seeking help from you! I'm just trying to get started with making some open-source contributions. 

I don't have much experience, but I'm learning things to make a good impact! 

I'm working on a **Single script to build Shotcut on Windows** for people who, like me, struggled at the beginning.

Soon I'll develop my skills and raise a PR to your repo. Good luck!
