### ISSUE TITLE
Keyframes lost when entering new value

### ISSUE THREAD

**Issue by Gizemquea** [mltframework/shotcut#1029]
observed in Shotcut 21.01.29 Windows 10 64bit - does not happen in previous versions!

Steps to reproduce in [this project](https://drive.google.com/file/d/1XcJpM0yhzQiPFxDiB5crVAIT6DbzthmB/view?usp=sharing)
1.) go to the Gain/Volume filter of the first clip in the first audio track
2.) note that the keyframes button is NOT marked, although keyframes are displayed and regarded in playback
3.) position playhead anywhere in that clip
4.) try to create another keyframe by arbitrary means of entering a new value for "Level"
Result:
keyframes are gone and cannot be restored by undo

While this seems version-specific, it is not related to that particular project. The same happened to me on various occasions in another project. I ended up in the "keyframes are displayed but the keyframes button in the filter says otherwise" after sucessfully adding a few keyframes and deleted all of them without even noticing at first. I originally questioned myself (considering the option of having accidentally delted the keyframes myself) and investigeted this very thoroughly since it kept happening again and again.

**Comment by ddennedy** [comment]
Already reported and fixed

**Comment by Gizemquea** [comment]
> Already reported and fixed

Great, thanks! ^.^
