### ISSUE TITLE
Filters popup too small to show anything when no filters are marked as "favorite"

### ISSUE THREAD

**Issue by silvahwuff** [mltframework/shotcut#103]
This problem occurs when you remove all filters from your favorites list. Next time you open the list, no filters will appear, and the popup window is too small to show any filters in the video or audio categories. Additionally, the window cannot be resized. Uninstalling and reinstalling Shotcut does not fix this issue.

OS: Windows 10 64-bit
Shotcut Version: 15.07.02

**Comment by silvahwuff** [comment]
Workaround:

1. Open Registry Editor as administrator (for Windows 10, just hit the Windows key, type "regedit", right click the result and click "Run as administrator")
2. Navigate to "Computer\HKEY_USERS\S-1-5-21-864796840-2417554276-3120481895-1001\SOFTWARE\Meltytech\Shotcut\filter\favorite"
3. Set all of the key values to "yes"
4. Close Registry Editor.

If "Computer\HKEY_USERS\S-1-5-21-864796840-2417554276-3120481895-1001\" does not exist on your system (as that may be system specific), simply look for the first entry in "HKEY_USERS" that has a long list of keys under "SOFTWARE". Most likely, it will be the first entry with a longer name under "HKEY_USERS".

I will keep this issue open until the software itself prevents this issue from occurring.

**Comment by ddennedy** [comment]
Github automatically closes issues when they are referenced in a git commit message, and we just roll with that instead of waiting until next release to mark issues as closed.

Another workaround is to switch to the video or audio filter list, close the filter menu, and then click + to re-open the filter menu.
