### ISSUE TITLE
Creating an image sequence breaks video playback and frame preview for whole project

### ISSUE THREAD

**Issue by Gizemquea** [mltframework/shotcut#1030]
Shotcut 21.01.29 - Windows 10 64bit - also happens in older versions

I frequently use timelapse clips created from image sequences - usually several hundred to a few thousend frames in resolutions up to 4k. Creating a new image sequence ALWAYS breaks video playback and frame preview i.e. i get the last displayed image "frozen" and that's it..

In this state I can still drag the image sequence into the project and save, but shotcut will become unresponsive on close.

A new instance of shotcut will successfully open the project and the image sequence works - this is the workaround I have been using in the last year or so...

**Comment by ddennedy** [comment]
Not reproduced on Linux using one image sequence of 1716 4K JPEGs and another 26331 1280x720 PNGs. I tested both existing project and empty project. For empty project, I tested Automatic Video Mode and 4K24. I tested both changing Properties of image in Source and Timeline.
See all these combinations I tested? That is why steps are helpful. Otherwise, I have to keep trying many different ways and relay them only to receive feedback about yet another way I never even thought about. I will test on Windows 10 and macOS next.

**Comment by Gizemquea** [comment]
> Not reproduced on Linux using one image sequence of 1716 4K JPEGs and another 26331 1280x720 PNGs. I tested both existing project and empty project. For empty project, I tested Automatic Video Mode and 4K24. I tested changing Properties of image in both Source and Timeline.
> See all these combinations I tested? That is why steps are helpful. Otherwise, I have to keep trying many different ways and relay them only to receive feedback about yet another way I never even thought about. I will test on Windows 10 and macOS next.

I understand your frustration, and I'm well aware that you do all this for free and hardly ever get anythng in return.

Plesase accept my apologies for wasting your time. Image sequences have actually NEVER worked for me in the last 18 months or so - and yes, I did the same thing on various machines, with images from different sources and so on. The circumstances really weren't suggesting that this would be hard to reproduce at all - at least not with Windows 10, 64bit as I mentioned in my original report.

I now tested a little bit more, still on Windows 10, 64bit and I actually managed to get this working for 2 images, for around 30 images, and once even for a _few hundred_ images - but **never** for much more than that (I tried about 10 times).

The images for this particular test are 4000x3000 pixel JPGs from a GoPro Hero 7, about 2-3MB each, the whole set would consist of ~1730 images and taking up close to 4 GB of disk space total - still nowhere near the available RAM on my machine (32GB). Image size, resolution, number and total amount of data is typical for my use case - but **it seems to be a lot more than in your own test scenarios!**

I am using 60 FPS in my projects - obviously I'll never have less than at least several hundred images in my sequences. That must be why this has never worked for me.

**Comment by ddennedy** [comment]
I reproduce it with higher frame rate video modes. Definitely on 50 or 60 fps. Only once on 30 and never below that. And this is on Linux where it is easiest to debug; so that's good.

**Comment by ddennedy** [comment]
I tested the fix on Linux with a GoPro Hero 9 photo timelapse at 5184x3888, 1902 images, in a video mode of 4K60. Will test it soon on Windows 10.

**Comment by Gizemquea** [comment]
If there is a nightly build with this fx, I can test it on Windows 10 if you want.

**Comment by ddennedy** [comment]
What I fixed was a deadlock I experienced immediately after clicking the check box. However, I still see some other problem testing on Windows where playback is stuck as you originally described while using a high frame rate video mode. Sometimes, I can get it to resume after clicking around the scrub bar, play button, and waiting.

**Comment by Gizemquea** [comment]
Interesting... I remember having seen this behavior where it somehow "recovered" and started playing eventually, but it was only once and I wasn't completely sure if I just mis-clicked or something.

I'm willing to test any additional fix you come up with, as soon as there is a build available.

**Comment by ddennedy** [comment]
Keep an eye out for the 21.02 beta coming very soon.

**Comment by ddennedy** [comment]
https://github.com/mltframework/shotcut/releases/tag/v21.02.15

**Comment by Gizemquea** [comment]
Tested with v21.02.15 and various large image sequences@60FPS - seems to work just fine. Thanks!
