### ISSUE TITLE
Switching external monitors resets playhead to 00:00:00,00

### ISSUE THREAD

**Issue by Gizemquea** [mltframework/shotcut#1032]
Shotcut Windows 10 64bit - all versions (presumably)

Switching to (or between) external monitor(s) doesn't retain the position of the playhead.

Yes, it is a minor inconvenience, but if this is by choice then I respectfully disagree.
Any UI action should do just what it says - no more, no less.

**Comment by ddennedy** [comment]
System external monitor option no longer included.
