### ISSUE TITLE
External monitor should never retain the focus

### ISSUE THREAD

**Issue by Gizemquea** [mltframework/shotcut#1033]
Shotcut Windows 10 64bit - all versions (presumably)

Working with external monitors completely breaks the workflow with keyboard shortcuts.

E.g. if I trim down a clip displayed on the external monitor and then drag it to some video track, the external display retains the focus and I cannot use keyboard controls unless I click somewhere in the main window. 

It would be really nice if the main window could at least get the focus automatically in such a case - even nicer: the external monitor never gets the focus in the first place. :)

**Comment by ddennedy** [comment]
System external monitor no longer offered, only Blackmagic Design SDI/HDMI
