### ISSUE TITLE
Directly typing into non-integer number fields doesn't work as expected

### ISSUE THREAD

**Issue by Gizemquea** [mltframework/shotcut#1036]
Shotcut UNSTABLE-21.02.09 - Windows 10 64bit

Steps to reproduce:
1.) Click into any non-integer number input field e.c. Gain/Volume filter's "Level" field
2.) It is not possible to enter a number or sign in the usual way e.g. you cannot put a "1" or a "-" in front of the existing number, instead the cursor is set to the end of the existing content upon input, subsequent typing does nothing
3.) Deleting part of the existing content does not work, doesn't matter whether BS or Del, - cursor and subsequent typing same as above
4.) Selecting part of the existing content and replacing that by something else does not work - cursor and subsequent typing same as above
5.) Selecting the whole existing content and replacing that by something else only works partially - I cannot enter the decimal separator that is displayed as determined my local Windows settings, I have to enter a decimal point instead, but even if I do that, the decimal value is discarded and I end up with the integer value+",0" only.

**Comment by ddennedy** [comment]
@Gizemquea please take a look at the code change:
https://github.com/mltframework/shotcut/commit/7606a915fb3d44dc49a8b6964830fd104ae57db2

You can try to manually replace that line in your installed version of Shotcut to confirm since this file is not compiled but loaded at run time.

**Comment by Gizemquea** [comment]
> @Gizemquea please take a look at the code change:
> [7606a91](https://github.com/mltframework/shotcut/commit/7606a915fb3d44dc49a8b6964830fd104ae57db2)
> 
> You can try to manually replace that line in your installed version of Shotcut to confirm since this file is not compiled but loaded at run time.

Confirmed working with this patch. Thanks.
