### ISSUE TITLE
By export the File, the source and export-file going corrupt

### ISSUE THREAD

**Issue by uxadax** [mltframework/shotcut#1039]
I want to replace the Source-file trough the exportfile. It loaded a little bit and stops. The source was completely corrupt. The export file was only a blank Video without audio and with a blackscreen. Without replacing it works perfect.

[ I don't know if this really a bug or a layer 8 problem ;) ]

- Windows 10 pro
- Shotcut: 21.01.29

**Comment by ddennedy** [comment]
You are not permitted to replace the Source with Export. Sorry but your description is very poor English to the point of making this an invalid report.

**Comment by ddennedy** [comment]
Export does not ever try to write the Source. It is not responsible for any corruption to your source.
