### ISSUE TITLE
text html not showing

### ISSUE THREAD

**Issue by strexgth** [mltframework/shotcut#1044]
I am using Linux mint 20.1, and I downloaded Shotcut from Flathub through the terminal. I noticed that I do not have the following filters, text HTML or 3d text. I want to use the text HTML filter to set up the end rolling credits scene, but it is not available. Please help.

**Comment by ddennedy** [comment]
These were removed a few versions ago and will never come back. You can read more about it in our website.

**Comment by strexgth** [comment]
> These were removed a few versions ago and will never come back. You can read more about it in our website.

Oh I didn't know. Thank you.
