### ISSUE TITLE
Default font color on Rich Text elements is white

### ISSUE THREAD

**Issue by floschl** [mltframework/shotcut#1045]
I stumbled exactly over this problem
https://forum.shotcut.org/t/rich-text-not-appearing-after-render/21576/4

and I indeed got it solved by setting the font color explicitely to white (on a black background).

My suggestion is to set the default color to a different than the background color. Otherwise, definitely other people will fall into this pitfall and it takes quite some time (and export jobs) to figure out the problem.

Thumbs up and thank you very much for your great work on the development of Shotcut!

**Comment by ddennedy** [comment]
The default is white already, and I will not change the background to black.
