### ISSUE TITLE
RTL (right to left) text look wrong after rendering

### ISSUE THREAD

**Issue by brigazvi** [mltframework/shotcut#1047]
![תמונה](https://user-images.githubusercontent.com/37640970/109439570-8e0def80-7a37-11eb-931f-74ca29512498.png)

**shotcut 21.01.29
windows 10  20h2**

**Comment by ddennedy** [comment]
I was not able to reproduce it.

See https://forum.shotcut.org/t/rtl-for-arabic-font/27373

**Comment by luzpaz** [comment]
@brigazvi can you still reproduce ?
