### ISSUE TITLE
libmlt++.so error with shotcut-linux-x86_64-210227.txz package

### ISSUE THREAD

**Issue by jeffdgr8** [mltframework/shotcut#1052]
Upgrading to [v21.02.27](https://github.com/mltframework/shotcut/releases/tag/v21.02.27), using the [shotcut-linux-x86_64-210227.txz](https://github.com/mltframework/shotcut/releases/download/v21.02.27/shotcut-linux-x86_64-210227.txz) package, Shotcut fails to run with the error `bin/shotcut: error while loading shared libraries: libmlt++.so.3: cannot open shared object file: No such file or directory`. This is running from the `Shotcut.app/shotcut` launcher. I had to `chmod +x` the launcher as well as the binaries in the `bin` folder after extracting the archive. `lib/libmlt++.xo.6.25.0` is the version packaged in the archive.

**Comment by ddennedy** [comment]
I think you are extracting it incorrectly. It works for me on Ubuntu 20.04. Also, the launch scripts and binaries are already set executable. This is a sign that something is different about your setup, archive extraction, or the volume. Also, there is no `libmlt++.xo.6.25.0 ` in archive but there is `libmlt++.*so.6.25.0` as well as there should be `libmlt++.so.3` that is symbolically linked. Again, another sign of an incorrect extraction.
![image](https://user-images.githubusercontent.com/1146683/110529526-38d47c80-80ce-11eb-9e88-dfd8d9906971.png)

**Comment by jeffdgr8** [comment]
I just noticed extracting the archive with `tar xvf`, there are a bunch of `Permission denied` errors creating symlinks. I think it may have to do with the archive being on a Chrome OS volume, shared with the Linux container/VM. If I move it to the Linux volume before extracting, then it works.
