### ISSUE TITLE
Timeline incorrect

### ISSUE THREAD

**Issue by piiskop** [mltframework/shotcut#1054]
Please see the [detailed description](https://forum.shotcut.org/t/timeline-incorrect/23030) in the main forum.

**Comment by ddennedy** [comment]
A terse description that simply links elsewhere is invalid.

**Comment by piiskop** [comment]
What's wrong with you, @ddennedy? You never told me anything about this place for bug reporting and accepted many of my reports. Yet, you marked another report of me invalid without a non-terse explanation until somebody else explained the problem of a terse description in details. He wrote that if somebody searches for a certain issue description they won't land in the forum. So I started to follow the template. There's no template here and no reason for anybody to land here as it's reported in the forum already. Do you want every reporter to duplicate every single report both in the forum and here? After many reports, you locked me out without an explanation. After I could access the forum again, you mentioned that the forum wasn't a bug tracker. Again, someone else had to tell me where the bug tracker was. You want my respect, you need to show your respect, too. A good start would be reasoning why it's not enough to link to the detailed discussion and not duplicate everything here. Or you can lock me out again as you seem used to do regarding me.

A terse description that simply links elsewhere although it links to a detailed discussion by _Shotcut_ people doesn't render the issue obsolete or invalid.

**Comment by ddennedy** [comment]
I will block if you continue to be contentious and nagging, and cross-posting is a form of nagging.

**Comment by piiskop** [comment]
Of course you will because you just can't respect and tolerate me and my energy that I put into reporting at all so that you can maintain your creation. Can't you see that you're the one who's nagging as you accuse me in cross-posting although you never didn't tell me where to post at first place, you just let another guy act for you in this matter. You've been harrassing me several times already. My intention is to help fixing the software but you don't let me do it. Would I have known that this place here is the bug tracker, I wouldn't have posted a single thing into the forum and no cross-posting wouldn't have happened by me. What I demand from you now is a public apology for the actions you've taken against me on an open source software. Instead of fighting me embrace my reports and fix the software as some issues wouldn't appear without me discovering them as I tend to use things differently from conservative people.
