### ISSUE TITLE
Detecting hardware encoders does not appear to work with appimage/portable-build/snap on ubuntu 20.04 with intel hardware

### ISSUE THREAD

**Issue by callegar** [mltframework/shotcut#1056]
Detection fails and you get:

```
checking for "h264_vaapi" 
[Debug  ] <EncodeDock::detectHardwareEncoders> "/tmp/.mount_shotcuUXWOKF/usr/bin/bin/ffmpeg" ("-hide_banner", "-f", "lavfi", "-i", "color=s=640x360", "-frames", "1", "-an", "-init_hw_device", "vaapi=vaapi0:,connection_type=x11", "-filter_hw_device", "vaapi0", "-vf", "format=nv12,hwupload", "-c:v", "h264_vaapi", "-f", "rawvideo", "pipe:") 
[Debug  ] <EncodeDock::detectHardwareEncoders> "[AVHWDeviceContext @ 0x55751da21b00] Failed to initialise VAAPI connection: -1 (unknown libva error)." 
[Debug  ] <EncodeDock::detectHardwareEncoders> "Device creation failed: -5." 
[Debug  ] <EncodeDock::detectHardwareEncoders> "Failed to set value 'vaapi=vaapi0:,connection_type=x11' for option 'init_hw_device': Input/output error" 
[Debug  ] <EncodeDock::detectHardwareEncoders> "Error parsing global options: Input/output error"
```

Yet, vainfo seems to say that everything is OK:
```
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.7 (libva 2.6.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
```
Any clue?

**Comment by ddennedy** [comment]
This is very much related to #892
VA-API in Shotcut's AppImage and portable works on Ubuntu 18.04 and other distros based on that such as Mint. An AppImage by design does not use the same version of things as running `vainfo` installed by your distribution. I do not know why VA-API breaks so easily when any one of its three different pieces (library, user space driver, and kernel module) does not match versions, or maybe that project frequently breaks API compatibility. What I do not know is that NVENC does not suffer from this problem, and neither does equivalent hardware encoding solutions on Windows and macOS. But also, and more interesting, is that the Flatpak package of Shotcut does not appear to have this problem - at least not on Ubuntu 20.04. It probably works on a far wider range of Linux versions, but there is very little data about that.

**Comment by callegar** [comment]
I see. I have also tried the snap and the portable tar and as expected I am getting the same result.

It is my understanding that the encoding is done via ffmpeg, though. Would it be possible, sensible to provide a way to tell shotcut to use the system provided ffmpeg rather than the bundled one?

**Comment by ddennedy** [comment]
Ffmpeg is used as a library. So no, not unless you use a distributor package of Shotcut, which we do not provide or support. Snap, AppImage, and portable are all the same build with most dependencies bundled. Flatpak is also bundled but different.

**Comment by callegar** [comment]
Made another check: in the flatpack build vaapi is indeed detected. Unfortunately, that build is a pain to me, since it cannot open files in the partitions that I dedicate to videos and I don't like very much the idea of playing mount tricks to make it happy.

**Comment by callegar** [comment]
More progress. If you take the *portable build* that has the advantage of letting you play around with files and you:

- get rid of `libva-drm.so.2`; `libva.so.2`; `libva-x11.so.2`
- symbolic link into the `lib/va` directory the system iHD_drv_video.so that is missing

then the hardware detection works, at least partially, and the `h264_vaapi` detection is successful.  What remains unsuccessful is the `hvec_vaapi` detection, though for some different issue than before:

```
checking for "hevc_vaapi" 
[Debug  ] <EncodeDock::detectHardwareEncoders> "/opt/Shotcut/Shotcut.app/bin/ffmpeg" ("-hide_banner", "-f", "lavfi", "-i", "color=s=640x360", "-frames", "1", "-an", "-init_hw_device", "vaapi=vaapi0:,connection_type=x11", "-filter_hw_device", "vaapi0", "-vf", "format=nv12,hwupload", "-c:v", "hevc_vaapi", "-f", "rawvideo", "pipe:") 
[Debug  ] <EncodeDock::detectHardwareEncoders> "Input #0, lavfi, from 'color=s=640x360':" 
[Debug  ] <EncodeDock::detectHardwareEncoders> "  Duration: N/A, start: 0.000000, bitrate: N/A" 
[Debug  ] <EncodeDock::detectHardwareEncoders> "    Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 25 tbr, 25 tbn, 25 tbc" 
[Debug  ] <EncodeDock::detectHardwareEncoders> "Stream mapping:" 
[Debug  ] <EncodeDock::detectHardwareEncoders> "  Stream #0:0 -> #0:0 (rawvideo (native) -> hevc (hevc_vaapi))" 
[Debug  ] <EncodeDock::detectHardwareEncoders> "Press [q] to stop, [?] for help" 
[Debug  ] <EncodeDock::detectHardwareEncoders> "[hevc_vaapi @ 0x564e9be8bf00] No usable encoding entrypoint found for profile VAProfileHEVCMain (17)." 
[Debug  ] <EncodeDock::detectHardwareEncoders> "Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height" 
[Debug  ] <EncodeDock::detectHardwareEncoders> "Conversion failed!"
```
This while `vainfo` reports entry points for
```
 VAProfileHEVCMain               : VAEntrypointVLD
 VAProfileHEVCMain10             : VAEntrypointVLD
```
With the above the h264 encoding with hardware support seems to work, at least it delivers a playable video. The time needed for the encoding does not seem to change significantly, though, but possibly the CPU stays a little cooler.

Altogether my guess is that the main issue is that the libs for vaapi that are currently embedded in the shotcut builds know nothing of the newer iHD driver. Would it be possible to rebuild with libs that are aware of that?

**Comment by callegar** [comment]
On the other hand, the flatpak package does the detection fine, but hangs on file dialogs (see bug #1058 and https://github.com/flatpak/flatpak/issues/4186).

**Comment by callegar** [comment]
... and more progress again. Made a deb package for ubuntu 20.04 using the libs that are available in the distro. Was a bit messy, since the melt version that is provided with ubuntu 20.04 does not

**Comment by callegar** [comment]
... and more progress again. Made a deb package of the latest shotcut using debian's as a base, for ubuntu 20.04 using the libs that are available in the distro. Was a bit messy, since the melt version that is provided with ubuntu 20.04 does not have `mlt_properties_exists()` and `Mlt::Properties::property_exists()`. I really don't know if my quick patches to allow compilation are actually correct, even if I understand that property_exist is a shortcut for something that should have been done differently in previous versions of the mlt lib.

Not asking about the deb. I understand that I am on my own on this.

What I would like to report is that with this, I get the hardware encoder detection working *only* for h264 not the hvec. It is totally equivalent to the results that I have previously obtained playing with the portable build.  So this is probably the best that can be obtained with the libs available in the distro.

I don't think that there are other tests that I can make to provide useful info. I now wonder if it could be possible on your side to update the portable/appimage build to be aware of the iHD driver.

**Comment by ddennedy** [comment]
We can only and do bundle all VA drivers that are a part of 18.04. I am sorry, but I am not going to change our build to download additional drivers from an additional location for a mismatching version of VAAPI.  The Intel and AMD H.264 hardware encoders are almost useless since x264 is better and just as fast.

**Comment by callegar** [comment]
I understand. Hoped it was possible to use the 20.04 versions also on 18.04 because when I swapped them in the portable build it went without an hiccup. But unfortunately it is hard to say without trying and I haven't a 18.04 machine at hand...
Sad that flatpak is so fragile out of fedora/gnome land.
And yes, speed wise x264 is certainly as good as hardware encoding on intel. The adavantage that I was expecting with the latter is more fan wise and with doing other things while encoding without thermal throttling.

**Comment by catscarlet** [comment]
I got an issue about VA-API two months ago, not with shotcut, but with obs. The vainfo output you mentioned in the first remind me of it.

It maybe an **Intel-media-va-driver** issue I guess.
The obs issue link here: [How to use QSV/VAAPI on Linux Mint?](https://obsproject.com/forum/threads/how-to-use-qsv-vaapi-on-linux-mint.137329/)

Originally Ubuntu and Mint use the `Intel-media-va-driver` and you got the vainfo output like that. Some people say the `VAEntrypointEncSliceLP`, the "LP" things didn't work well.

I installed the package called `Intel-media-va-driver-non-free`, and the vainfo changed a lot, like this: 

<details>
  <summary>vainfo output</summary>


```
$ sudo vainfo 

libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.7 (libva 2.6.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
```

See there are a lot of `VAEntrypointEncSlice` showed up.

</details>

The VA-API worked with OBS after I installed `Intel-media-va-driver-non-free`. 
Also test in Shotcut, with shotcut-linux-x86_64-210321.AppImage, on Linux mint 20.1, and **failed**.
End up with

<details>
  <summary>shotcut output</summary>

```
[Info   ] <EncodeDock::detectHardwareEncoders> checking for "h264_vaapi" 
[Debug  ] <EncodeDock::detectHardwareEncoders> "/tmp/.mount_shotcuShsYNt/usr/bin/bin/ffmpeg" ("-hide_banner", "-f", "lavfi", "-i", "color=s=640x360", "-frames", "1", "-an", "-init_hw_device", "vaapi=vaapi0:,connection_type=x11", "-filter_hw_device", "vaapi0", "-vf", "format=nv12,hwupload", "-c:v", "h264_vaapi", "-f", "rawvideo", "pipe:") 
[Debug  ] <EncodeDock::detectHardwareEncoders> "[AVHWDeviceContext @ 0x561cbd425b00] Failed to initialise VAAPI connection: -1 (unknown libva error)." 
[Debug  ] <EncodeDock::detectHardwareEncoders> "Device creation failed: -5." 
[Debug  ] <EncodeDock::detectHardwareEncoders> "Failed to set value 'vaapi=vaapi0:,connection_type=x11' for option 'init_hw_device': Input/output error" 
[Debug  ] <EncodeDock::detectHardwareEncoders> "Error parsing global options: Input/output error" 
[Info   ] <EncodeDock::detectHardwareEncoders> checking for "hevc_vaapi" 
[Debug  ] <EncodeDock::detectHardwareEncoders> "/tmp/.mount_shotcuShsYNt/usr/bin/bin/ffmpeg" ("-hide_banner", "-f", "lavfi", "-i", "color=s=640x360", "-frames", "1", "-an", "-init_hw_device", "vaapi=vaapi0:,connection_type=x11", "-filter_hw_device", "vaapi0", "-vf", "format=nv12,hwupload", "-c:v", "hevc_vaapi", "-f", "rawvideo", "pipe:") 
[Debug  ] <EncodeDock::detectHardwareEncoders> "[AVHWDeviceContext @ 0x556e5a94eb00] Failed to initialise VAAPI connection: -1 (unknown libva error)." 
[Debug  ] <EncodeDock::detectHardwareEncoders> "Device creation failed: -5." 
[Debug  ] <EncodeDock::detectHardwareEncoders> "Failed to set value 'vaapi=vaapi0:,connection_type=x11' for option 'init_hw_device': Input/output error" 
[Debug  ] <EncodeDock::detectHardwareEncoders> "Error parsing global options: Input/output error" 

```

</details>

As same as above.

Wish this could help.

**Comment by callegar** [comment]
Thanks for your info. Currently, I am happy with the flatpak version of Shotcut:

- After I have upgraded flatpak using the dedicated PPA on ubuntu and got rid of its kde pieces it works just fine on my ubuntu system and does hardware detection right;
- Contrarily to my initial expectations, it can read and write stuff out of my home (snap packages generally cannot) which is great!

Having the hardware encoding, even if it is not faster than the software one, is a *huge advantage*. On my laptop it keeps cpu usage and fan spinning to a minimum while encoding.

**Comment by babam86** [comment]
I followed @callegar's suggestion to get rid of libva-drm.so.2, libva.so.2 and libva-x11.so.2

And now Shotcut can detect h264_vaapi and hevc_vaapi (iHD/Intel media driver), but only h264_vaapi works while hevc_vaapi produces broken videos/glitches.

Using HW acceleration has at least 2 advantages, less CPU and RAM usage.

Thanks.

**Comment by babam86** [comment]
Regarding hevc_vaapi not working properly (glitches) it's not a Shotcut issue, it's an Intel driver (iHD) issue https://github.com/intel/media-driver/issues/1343

Thanks.

**Comment by LiGoldragon** [comment]
>  x264 is better and just as fast.

Hardware encoders are an order of magnitude faster at the same cycle rate. Hence an order of magnitude less CPU destructive and efficient.
