### ISSUE TITLE
Dragging from the playlist to the timeline sometimes impossible

### ISSUE THREAD

**Issue by piiskop** [mltframework/shotcut#1057]
What is your operating system?
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 20.10
Release: 20.10
Codename: groovy

What is your Shotcut version (see Help > About Shotcut)? Is it 32-bit?
21.02.27
No.

Can you repeat the problem? If so, what are the steps?
I have encountered this problem many times. Suddenly, I can’t drag anything from the playlist to the timeline. An icon appears that shows that dropping an item there is impossible. Giving instructions to repeat the problem is hardly possible. Maybe the application log can be useful. Please also see my corresponding [video](https://youtu.be/avqonwlXQN0)
[log.txt](https://github.com/mltframework/shotcut/files/6175441/log.txt)

As of 20210320, it happened again. I wanted to close the application and it asked from me whether I want to save the changes. I wanted. After a restart, I can't drag and drop a video from the playlist into the timeline. Dragging and dropping to timeline doesn't work at all anymore. I've created three porjects already and can't even start editing. This doesn't even work after a reinstall.

I had to do _Edit_->_Paste_ and after that, I could drag and drop again. _Shotcut_ seems to store the timeline information somewhere outside, so that even a clean reinstall didn't help.

**Comment by bkauler** [comment]
Same problem. I have just compiled 21.12.24 on EasyOS 64-bit with all deps present. The app starts up and the timeline is just black, no menubar/icons. Cannot drag clips to it. Photo:

![shotcut-timeline-broken](https://user-images.githubusercontent.com/4200448/149975683-1675cc2e-83f1-416a-910f-e725a97bbd10.jpg)

I am running shotcut from a terminal, cannot see any error message.

**Comment by AlexanderZhirov** [comment]
> [Same problem](https://www.youtube.com/watch?v=FgnUEWi_Mag). There is no time scale, or rather, its display. There are not even any icons.
@bkauler 

I solved this problem by [installing](https://discuss.getsol.us/d/7499-shotcut-does-not-add-video-to-the-timeline/52) the **qt5-quickcontrols** package

**Comment by ddennedy** [comment]
@bkauler You must install the build for the binary to locate the QML files it loads at run-time per the [README.md](https://github.com/mltframework/shotcut/#from-command-line).

**Comment by bkauler** [comment]
Thanks very much for the feedback. 

I do have qtquickcontrols2 installed, version 5.14.2 (as well as dev pkg), and I did do "make install" -- and have /usr/share/shotcut/qml

I am unfamiliar with qml -- is there any way that I can do a quick test that qml works? Like, some test qml?

**Comment by don570** [comment]
I'm using fatdog64 linux  and dragging video  from  playlist to timeline works fine
in version  21.12.24
