### ISSUE TITLE
Shotcut flatpak broken on kubuntu 20.04, file dialogs hang

### ISSUE THREAD

**Issue by callegar** [mltframework/shotcut#1058]
Seen on ubuntu 20.04, in fact kubuntu, with the latest shotcut (21.02.27) in its flatpak package from flathub.

It is enough to start the application and press the "Projects Folder" button in the "New Project" panel to make the application hang.

Nothing significant gets printed on stderr.

**Comment by ddennedy** [comment]
Did you check if the dialog opened behind the application window?

**Comment by callegar** [comment]
Opens well above. And when it opens, nothing works anymore.

**Comment by callegar** [comment]
Using a more recent flatpak from the ubuntu PPA ppa:alexlarsson/flatpak, that is 1.10.2 with its companion xdg-desktop-portal gives a different behavior. Now pressing the "Projects Folder" button, the application does not hang. However the "open" button at the bottom of the dialog does not work (i.e., dialog does not close pressing it). Furthermore, video is totally broken with this setup.

**Comment by ddennedy** [comment]
I have not experienced those problems, but I am not using KDE, rather GNOME.

**Comment by callegar** [comment]
Maybe the problem is xdg-desktop-portal-kde that appears to be DE specific /and/ related to filesystem access... no idea. Googling gives many results about flatpak issues with file dialogs (including hangs and crashes) but none seems to point to a solution.
In any case, thanks for your help and let's hope that having a report of these issues here can at least save some work and time to others that might experience my same issue.

**Comment by callegar** [comment]
Great! Finally managed making the flatpak version of shotcut work!
Definitely not an issue with shotcut itself - so I'm closing the bug.

However, I'm taking the time to document the process here for those who might encounter my same problem.

The issue seems to be that flatpak in ubuntu is in a bit of a miserable state with packages that are old and broken.

On kubuntu 20.04 you need to get rid of the xdg-desktop-portal-kde and to install the gtk counterpart. That will have the unfortunate side effect of also removing the flatpak support in the discover software center, but that does not seem a big loss.
After that you need a reboot (or at least restarting the desktop portal service).
If that is not enough (I suspect it is not), you'll also need to install flatpak via the flatpak official PPA (sudo add-apt-repository ppa:alexlarsson/flatpak). Reboot after this, because this is renewing the portal service again.

With the flatpak, you finally get the hardware encoding working in (k)ubuntu 20.04. While this seems a negligible gain because the software coder works very well and is in fact even slightly faster on some intel laptops like mine, the hardware encoder has the huge pro of leaving the laptop cold (<65°) during all the encoding process with the fan at minimum speed in contrast to the high temperature and fan rotation characterizing the CPU encoding.
