### ISSUE TITLE
.DNG file(s) - sequence not detected, adding to timeline impossible

### ISSUE THREAD

**Issue by newillusion** [mltframework/shotcut#1059]
.DNG (cdng) file is correctly recognized and showed in Source panel, but:

1. Detected duration .dng-image is very huge (see attached picture)
![Clipboard02](https://user-images.githubusercontent.com/13040758/112413796-628ad600-8d53-11eb-93e4-1e9d933207fe.png)

2. Attemp to drag .dng fro Source panel to Timeline is not succefull. Message "You cannot drag non-seekable source".
![Clipboard93](https://user-images.githubusercontent.com/13040758/112413830-759da600-8d53-11eb-96f8-e72467774840.png)

I using .dng files recored by SIGMA fp camera.

**Comment by ddennedy** [comment]
DNG is not supported

**Comment by newillusion** [comment]
.DNG reading, displayng, and placed on timeline - that is 95% of "supporting".
And .dng is very important, becouse a lot of new cameras can write video to .dng sequences.
It MUST be supported. And on 95% supported now.

**Comment by ddennedy** [comment]
You cannot dictate what must be done, but you can can submit a pull request with the code changes to make it work for you. 
See this comment for a workaround to read this as an image sequence: https://github.com/mltframework/shotcut/issues/37#issuecomment-55200346
Is the color correct in that image above? I have seen before where bayer-based images do not have correct color from FFmpeg.
