### ISSUE TITLE
BUG: 15.07 serious redraw issues

### ISSUE THREAD

**Issue by COLABORATI** [mltframework/shotcut#106]
I have serious redraw issues with shotcut to the point that makes the software unusable. No other software has these problems, I also tried other video software like Flowblade or Lightworks.

This is on Ubuntu 14.04, Hardware is with an NVIDIA 4200, however I am assuming that shotcut is using the internal Intel card. Here are the relevant parts of lspci:

00:00.0 Host bridge: Intel Corporation 2nd Generation Core Processor Family DRAM Controller (rev 09)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port (rev 09)
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
00:16.0 Communication controller: Intel Corporation 6 Series/C200 Series Chipset Family MEI Controller #1 (rev 04)
01:00.0 VGA compatible controller: NVIDIA Corporation GF119M [NVS 4200M] (rev ff)
01:00.1 Audio device: NVIDIA Corporation GF119 HDMI Audio Controller (rev ff)

![shotcut-serious-redraw-issues_2015-08-08](https://cloud.githubusercontent.com/assets/6514273/9147023/0c8cad74-3d62-11e5-9139-f8964f9ecefe.png)

**Comment by ddennedy** [comment]
This is probably a compatibility issue with your video driver and Qt 5.2, possibly our use of their Quick views. We hope to upgrade to Qt 5.5 for the 15.09 release early September, and we'll have you try again then. Otherwise, I don't reproduce this problem, and I don't have a similarly equipped system to test and verify if 5.5 resolves it.

**Comment by firew4lker** [comment]
Sory for hijacking the thread. Will you release 15.08 or directly15.09?

**Comment by metellius** [comment]
15.09 will be the next release due to work on the transition to qt 5.5.

**Comment by ddennedy** [comment]
Needs to be re-tested on 15.09.

**Comment by ddennedy** [comment]
To be clear, I want the bug reporter to re-test on 15.09 since I am not able to reproduce it.

**Comment by mxa** [comment]
I have this issue when using Shotcut with the integrated graphics. When I run it as `optirun shotcut` (NVIDIA) there is no problem.  Screenshot from intel card:
![screenshot from 2015-09-26 13 32 01](https://cloud.githubusercontent.com/assets/1220707/10127985/80423458-65e6-11e5-882f-9b8878c27d0c.png)

**Comment by ddennedy** [comment]
@mxa Please confirm you are using Shotcut 15.09 for Linux.

**Comment by mxa** [comment]
Using 15.09.11 on Linux Mint 17.2 cinnamon

**Comment by mxa** [comment]
made a quick [screencast](http://sendvid.com/er8gui4l) for you.

**Comment by ddennedy** [comment]
Sorry but there is nothing I can do about this. It is a limitation of that integrated GPU's OpenGL , and this part of Qt requires OpenGL. If you can provide more information about that GPU, then at least we have that information to deal with future duplicate reports.

**Comment by mxa** [comment]
lspci -vnn | grep VGA -A 12
 00:02.0 VGA compatible controller [0300]: Intel Corporation 4th Gen Core Processor Integrated  Graphics Controller [8086:0416] (rev 06) (prog-if 00 [VGA controller])
	Subsystem: Lenovo Device [17aa:502a]
	Flags: bus master, fast devsel, latency 0, IRQ 29
	Memory at f1000000 (64-bit, non-prefetchable) [size=4M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 6000 [size=64]
	Expansion ROM at <unassigned> [disabled]
	Capabilities: <access denied>
	Kernel driver in use: i915
 
 glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.1.3
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.1.3
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:

sudo lshw -numeric -C display
  *-display               
       description: VGA compatible controller
       product: 4th Gen Core Processor Integrated Graphics Controller [8086:416]
       vendor: Intel Corporation [8086]
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 06
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:29 memory:f1000000-f13fffff memory:e0000000-efffffff ioport:6000(size=64)
