### ISSUE TITLE
GIF export doesn't work

### ISSUE THREAD

**Issue by eoopx** [mltframework/shotcut#1060]
I added .gif image and then selected export video -> format .gif -> export file. Result: failed (jobs)

```
 [libx264 @ 0x7f0448001ec0] using SAR=1/1
[libx264 @ 0x7f0448001ec0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7f0448001ec0] profile High, level 2.1, 4:2:0, 8-bit
[AVIOContext @ 0x7f043800b380] Statistics: 2528796 bytes read, 3 seeks
[producer avformat-novalidate] /home/disk/Downloads/New Folder/teno.gif
    missing hwaccel parameters. skipping hardware initialization
[producer avformat-novalidate] /home/disk/Downloads/New Folder/teno.gif
    checking VFR: pkt.duration 10
[swscaler @ 0x7f04380881c0] Warning: data is not aligned! This can lead to a speed loss
[gif @ 0x7f0448000f40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[gif @ 0x7f0448000f40] GIF muxer supports only a single video GIF stream.
[consumer avformat] Could not write header '/home/disk/Documents/outputgif'
[AVIOContext @ 0x7f044815cbc0] Statistics: 0 seeks, 0 writeouts

[AVIOContext @ 0x7f043800b180] Statistics: 4125392 bytes read, 4 seeks
Failed with exit code 1
```
Below default settings
![image](https://user-images.githubusercontent.com/61364121/112630664-7ecc6700-8e68-11eb-9a58-f9df91ae76d1.png)
![image](https://user-images.githubusercontent.com/61364121/112630585-5cd2e480-8e68-11eb-98dd-2ba7960ed2f5.png)

But if i selected to export as mp4 then it works properly even original file is a .gif
```
[libx264 @ 0x7fee84001f80] using SAR=1/1
[libx264 @ 0x7fee84001f80] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x7fee84001f80] profile High, level 2.1, 4:2:0, 8-bit
[libx264 @ 0x7fee84001f80] 264 - core 161 r3039 544c61f - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=50 keyint_min=5 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[AVIOContext @ 0x7fee7800b380] Statistics: 2528796 bytes read, 3 seeks
[producer avformat-novalidate] /home/disk/Downloads/New Folder/teno.gif
    missing hwaccel parameters. skipping hardware initialization
[producer avformat-novalidate] /home/disk/Downloads/New Folder/teno.gif
    checking VFR: pkt.duration 10
[swscaler @ 0x7fee780881c0] Warning: data is not aligned! This can lead to a speed loss
[mp4 @ 0x7fee84000f40] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mp4 @ 0x7fee84000f40] Starting second pass: moving the moov atom to the beginning of the file
[AVIOContext @ 0x7fee8416a140] Statistics: 64919 bytes read, 0 seeks
[libx264 @ 0x7fee84001f80] frame I:1     Avg QP:18.20  size: 10506
[libx264 @ 0x7fee84001f80] frame P:9     Avg QP:21.39  size:  3628
[libx264 @ 0x7fee84001f80] frame B:10    Avg QP:22.83  size:  2103
[libx264 @ 0x7fee84001f80] consecutive B-frames: 15.0% 50.0% 15.0% 20.0%
[libx264 @ 0x7fee84001f80] mb I  I16..4: 26.5% 38.4% 35.1%
[libx264 @ 0x7fee84001f80] mb P  I16..4:  1.7%  8.5%  2.9%  P16..4: 14.7% 11.8%  9.4%  0.0%  0.0%    skip:51.0%
[libx264 @ 0x7fee84001f80] mb B  I16..4:  6.9%  5.0%  1.6%  B16..8: 14.3% 12.9%  4.5%  direct: 2.2%  skip:52.6%  L0:50.9% L1:41.7% BI: 7.5%
[libx264 @ 0x7fee84001f80] 8x8 transform intra:46.8% inter:22.3%
[libx264 @ 0x7fee84001f80] coded y,uvDC,uvAC intra: 45.5% 51.2% 20.0% inter: 10.8% 9.7% 1.9%
[libx264 @ 0x7fee84001f80] i16 v,h,dc,p: 63% 13% 23%  1%
[libx264 @ 0x7fee84001f80] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 14%  7% 69%  2%  2%  1%  2%  1%  2%
[libx264 @ 0x7fee84001f80] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 26% 14% 23%  7%  5%  6%  5%  6%  8%
[libx264 @ 0x7fee84001f80] i8c dc,h,v,p: 65% 14% 19%  1%
[libx264 @ 0x7fee84001f80] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x7fee84001f80] ref P L0: 69.4% 30.6%
[libx264 @ 0x7fee84001f80] ref B L0: 77.5% 22.5%
[libx264 @ 0x7fee84001f80] ref B L1: 98.4%  1.6%
[libx264 @ 0x7fee84001f80] kb/s:256.73
[AVIOContext @ 0x7fee8415dd00] Statistics: 4 seeks, 5 writeouts

[AVIOContext @ 0x7fee7800b180] Statistics: 4607876 bytes read, 4 seeks
Completed successfully in 00:00:00
```

Ubuntu 20.04.02 Gnome X11
Shotcut 21.03.24 (snap store)

**Comment by ddennedy** [comment]
You need to use the GIF export preset. It is not enough to change Format within Advanced. If you are in Advanced you are expected to understand everything you need to change to make something work. libx264 video codec in GIF is an invalid combination. Obviously, you are not advanced.

**Comment by eoopx** [comment]
@ddennedy sorry, i didn't notice it as advanced export window. i still have another problem but it seems i should ask this on forum however i have other request below then you may able to answer for both,

Shotcut auto detect gif resolution etc but it doesn't provide original quality output (export). i can see tiny shaking dots then what's the best config suitable to set for get very smooth and high quality gif?
I don't have more knowledge related graphic to work with advanced settings, basically increase frames/sec, quality, GOP don't help to make different.

(Default settings)
![image](https://user-images.githubusercontent.com/61364121/112688495-8b25e380-8eab-11eb-98da-b5bbe5ed6c94.png)
![image](https://user-images.githubusercontent.com/61364121/112688517-9416b500-8eab-11eb-99e1-f8e04df6de79.png)


Yesterday i requested to add sinhala (si) language through transifex then can you approve it?

**Comment by ddennedy** [comment]
Good GIF export requires pre-processing to generate a palette that is rather old and unique in a video format and not available in Shotcut. Most GIF-like things on the web now are actually MP4 or WebM videos, and GIF is very low priority for us. 
I will look for your translation request.

**Comment by eoopx** [comment]
>Good GIF export requires pre-processing to generate a palette that is rather old and unique in a video format and not available in Shotcut. Most GIF-like things on the web now are actually MP4 or WebM videos, and GIF is very low priority for us.

There're many video editors available for windows that provide source quality gif output but it's hard to find for linux, so far i only found gimp as solution to quality problem but it is hard to use due this issue 
https://gitlab.gnome.org/GNOME/gimp/-/issues/6133 (feature request)
You're video editor software developer so there's higher chance you may have noticed something for linux, Do you know good software for this?  kdenlive also has this problem

>I will look for your translation request.

I already started to translate shotcut to sinhala language :)

**Comment by eoopx** [comment]
@ddennedy 
>Good GIF export requires pre-processing to generate a palette that is rather old and unique in a video format and not available in Shotcut., and GIF is very low priority for us.

Should i open feature request for avoid forget or is there any existing request for it?, as i mentioned above i couldn't find any tool for linux and platforms similar mastodon etc ask .gif format file if need to add animated page cover 
e.g. page https://mastodon.social/@protonmail

**Comment by ddennedy** [comment]
We do not take feature requests. You can search the web for how to use ffmpeg. For example,
https://engineering.giphy.com/how-to-make-gifs-with-ffmpeg/
Our Shotcut builds include ffmpeg.
