### ISSUE TITLE
Filter details (options) not showing up

### ISSUE THREAD

**Issue by OliverLew** [mltframework/shotcut#1064]
System: Arch Linux
CPU: AMD 4800H
Shotcut version: 21.03.21
Qt version: 5.15.2

Issue:
After I add a filter to a clip by clicking the "+" button in "filter" tab, the filter name shows in the filters list, but there is no filter details (or, options) shown below the filter list. The only exceptions are fade in/out video/audio (I only tried the filters from default "favorite" list).

However, on another Arch Linux machine (Intel CPU) with the same software and version (but the other packages installed are different, I don't know if any are related), I got everything displayed correctly.

Output:
Not sure how to get proper debug info, here is the output if I open shotcut in a terminal, add a "brightness" filter and close shotcut at last:
Terminal output for shotcut with the issue: [shotcut.log](https://github.com/mltframework/shotcut/files/6234377/shotcut.log)
Terminal output for shotcut with correct behavior (on another machine): [shotcut.good.log](https://github.com/mltframework/shotcut/files/6234254/shotcut.good.log)

Screenshot:
![Screenshot_2021-03-31_14-52-06](https://user-images.githubusercontent.com/12032219/113102503-b5233100-9230-11eb-94e6-644dbeb31b66.png)
exception:
![Screenshot_2021-03-31_14-53-00](https://user-images.githubusercontent.com/12032219/113102595-d552f000-9230-11eb-9c7e-561ec3bf99b5.png)

**Comment by ddennedy** [comment]
This is usually a sign that your computer's OpenGL is incompatible, but also it can depend on how you received and installed Shotcut. We only support the builds we [provide](https://shotcut.org/download/), and I see from your log that you are running `/usr/bin/shotcut` which is not our build. You can also try changing the option in Settings > Display Method.

**Comment by OliverLew** [comment]
Yes, the portable version is working fine. It must be Arch's packages being not compatible with shotcut.

**Comment by OliverLew** [comment]
Just want to say, the current Arch Linux's package works fine now. Something must be fixed (also probably in other packages, not shotcut itself), although I don't know what.
