### ISSUE TITLE
Keyframe zoom gets automatically set to 1.000,0%

### ISSUE THREAD

**Issue by Moouncat** [mltframework/shotcut#1065]
When I want to change the position of a keyframe in Size, Position & Rotate (used the shake preset) the scale immediatly gets set to 1.000,0% and that crashes my Shotcut (found out changing the Zoom in general just freezes the programm and crashes)

I'm running v21.03.21 on Windows

**Comment by ddennedy** [comment]
This is the same as the following in the forum
https://forum.shotcut.org/t/shotcut-freezes-trying-to-apply-shake-to-transparent-png/26188

I have only reproduce this when using a shake preset. There are probably other ways, but likely fixing it for that case covers it.
