### ISSUE TITLE
Rich text filter glitch

### ISSUE THREAD

**Issue by alpody** [mltframework/shotcut#1066]
I use Openshot 21.03.21 on Windows 10 (20H2 ) Build: 19042.868

In project good-color.mlt  i had moved transparent fragment. That is screencast

https://user-images.githubusercontent.com/13846803/113451683-30d8d580-940b-11eb-9aab-560b3b8d295c.mp4

After that i save project to bad-color3.mlt 

Rendered video from good-color.mlt has static text and it's ok.    

that is it 

https://user-images.githubusercontent.com/13846803/113452530-d80a3c80-940c-11eb-8364-6ed22a6d751f.mp4

Rendered video  from bad-color3.mlt start glitch from beginning to 10 seconds 
 
that is it 

https://user-images.githubusercontent.com/13846803/113452290-629e6c00-940c-11eb-8894-fd5d31d9c41d.mp4

Project files in this archive 
[text-glitch.zip](https://github.com/mltframework/shotcut/files/6251148/text-glitch.zip)

Difference between bad-color3.mlt (left) and  good-color.mlt(right)   is very small 

![WinMergeU_TCYc0r88Im](https://user-images.githubusercontent.com/13846803/113453214-2ff57300-940e-11eb-8f91-b929de457411.png)

**Comment by ddennedy** [comment]
This is Shotcut, not OpenShot.
I did not reproduce it yet from bad-color3.mlt
Do you have **Export > Advanced > Video > Parallel processing** turned on? If so, try without it.

**Comment by alpody** [comment]
You are right, this is Shotcut and it better for me. 
When  Export > Advanced > Video > Parallel processing  is off it works

Thank u.

**Comment by ddennedy** [comment]
I reproduced it, and fixed it for the next version.
