### ISSUE TITLE
CMake & MLT as a subdir

### ISSUE THREAD

**Issue by eszlari** [mltframework/shotcut#1067]
Just a heads-up, in case you were not aware:

Now that MLT is being converted to CMake, a move of Shotcut to CMake would make it possible to add MLT as subdir. This way, MLT would be compiled as part of the regular build process, so you could use Qt Creator's graphical debugger for MLT too.

**Comment by ddennedy** [comment]
Please add this to your PR #967. I have releases due for MLT and Shotcut April 10 and 11, and I will not get around to it before then. I will try to merge it soon thereafter (pending integration with build scripts including our SDKs and their usage). FYI, I already use Qt Creator's debugger with MLT simultaneously with Shotcut ;-)
