### ISSUE TITLE
I can't edit any filter, the box below it simply won't appear.

### ISSUE THREAD

**Issue by hrqmonteiro** [mltframework/shotcut#1069]
I was using it normally, but since before yesterday, i simply can't edit any filter. Like a text, for example.

![2021-04-08_10-07](https://user-images.githubusercontent.com/17055027/114213949-125a6900-993a-11eb-9e1f-da2935660ac7.png)

The box below it (like this, i got this screenshot in the forum when i made a thread)

![test](https://forum.shotcut.org/uploads/default/original/3X/2/8/28858ba997d5625a560a019316133fd8853f9cad.png)

Simply won't appear. I opened shotchut on a terminal, and no errors are accused.

I removed it, removed all my config files, cache, and everything (in `~/.config`, `~/.local/share` ), installed it again and it simply won't work.

**Comment by ddennedy** [comment]
Where did you get Shotcut and how did you install it and run it? (Linux is complicated to support.)

**Comment by hrqmonteiro** [comment]
> Where did you get Shotcut and how did you install it and run it? (Linux is complicated to support.)
> 
> Related forum thread: https://forum.shotcut.org/t/how-do-i-edit-an-active-text-filter/26687

The forum thread is myself. I am on Void Linux, downloaded it through the package manager.

And as i said, it was totally normal before, i was using it for more than 8 months. Not it happened to be like this.

**Comment by ddennedy** [comment]
We do not support and debug builds we do not provide through or listed on our download page.

**Comment by hrqmonteiro** [comment]
> We do not support and debug builds we do not provide through or listed on our download page.

I just removed it completely, erased all the folders again, and downloaded your .AppImage, which is "officially supported", and it is behaving the same way.

**Comment by ddennedy** [comment]
OK, then you probably have an OpenGL compatibility problem. The Qt QML UI APIs we are using uses OpenGL, and this can happen. It may have worked before but we had to upgrade Qt and change APIs to something no longer deprecated. You can start Shotcut and choose View > Application Log, and post it to see if it shows anything interesting. You can also try option **Settings > Display Method > Software (Mesa)** but this does not work with all OpenGL drivers.

**Comment by ddennedy** [comment]
Does the timeline work? It uses the same technology. Does Filters work correctly in a new/untitled project?

**Comment by MarcoDiFrancesco** [comment]
Same problem in ArchLinux with Qt packages updated. Tested on both OpenGL and Mesa, the result is exactly the same.

With *Text: simple* the result is the same as the screenshot above, and another example where the options don't show up is *Size, Position & Rotate*

![](https://i.imgur.com/KHmmAcx.png)

But for some reasons the *Fade In Audio* filter works

![](https://i.imgur.com/CJhY73o.png)

**Comment by bmatherly** [comment]
> mlt_repository_init: failed to dlopen /usr/lib/mlt/libmltsox.so

That package is not from the Shotcut download page

>> We do not support and debug builds we do not provide through or listed on our download page.

Please download, extract and run the build from here:
https://www.fosshub.com/Shotcut.html?dwl=shotcut-linux-x86_64-210321.txz

Does the problem persist?

**Comment by MarcoDiFrancesco** [comment]
Works completely fine! The problem looks related to pacman dependecies. Sorry for the wasted time.

**Comment by newedgex** [comment]
Ciao @MarcoDiFrancesco ,
I have the same problem on Arch with Shotcut version ARCH-21.03.21 and Qt version 5.15.2. 
How did you fix this issue exactly?

**Comment by newedgex** [comment]
Ok, understood now, didn't think it was that easy... Downloaded, extracted and clicked the shotcut icon, it works.
How can we fix this with the default arch package tho?

**Comment by MarcoDiFrancesco** [comment]
I reported the bug in the archlinux website ([link](https://bugs.archlinux.org/task/70407)). Hopefully it get fixed soon!
