### ISSUE TITLE
crash when dragging to timeline if no write permissions 

### ISSUE THREAD

**Issue by unhammer** [mltframework/shotcut#107]
I tried opening a file in another users dir, where I only had read, not write permissions. Opening and playing the clip worked fine, but when I tried pulling it to the timeline shotcut just crashed – a warning would probably be friendlier :-)

(Dragging as the file owner worked fine however)

**Comment by ddennedy** [comment]
Please indicate which OS, its version, and version of Shotcut.

**Comment by unhammer** [comment]
xubuntu 15.04
shotcut-debian7-x86_64-150702.tar.bz2

**Comment by ddennedy** [comment]
Unable to reproduce.

**Comment by unhammer** [comment]
After logging out and in again I can't reproduce either :-( 

It happened the first time I tried Shotcut, but rm -rf  ~/.config/Meltytech ~/.locals/share/Meltytech didn't help me reproduce, so presumably there's something other/more than permissions that caused the crash. I'll be back with more details if I can get them.
