### ISSUE TITLE
shotcut needs qmelt for video export

### ISSUE THREAD

**Issue by plater** [mltframework/shotcut#1070]
Does shotcut still need qmelt or is there some way I can remove the depreciated webvfx package from openSUSE?

**Comment by plater** [comment]
https://github.com/mltframework/shotcut/issues/284

**Comment by plater** [comment]
I couldn't find any mention in the logs, webvfx doesn't appear in build-shotcut.sh  and shotcut appears to export videos properly so I've removed webvfx. Please confirm that shotcut doesn't require qmelt from webvfx anymore.

**Comment by bmatherly** [comment]
Confirmed. WebVfx is no longer a depencency. Shotcut no longer uses qmelt. It uses melt instead.
