### ISSUE TITLE
Seems like a memory leak when gradually zooming a video.

### ISSUE THREAD

**Issue by AlexKotik** [mltframework/shotcut#1073]
Shotcut version: 21.03.21

Steps to reproduce:
1) Add HD video to the timeline (something like 3 min long).
2) Add Size, Position and Rotate effect to the video.
3) Add keyframes at the beginning and at the ending of a video.
4) At the begining keyframe set Zoom to 100%.
5) At the ending keyframe set Zoom to 200%.
6) Export the video using builtin YouTube preset.
7) Shotcut will eat up all of your memory (on my side memory consumption starts at 2GB and gradually increase up to my maximum memory of 8GB during the export procedure, looks like a memory leak or something).

PS: I can easily preview the video in the editor, the bug happens only when exporting the video for some reason.
PPS: I on Manjaro Linux KDE edition if it matters.

**Comment by ddennedy** [comment]
> I on Manjaro Linux KDE edition if it matters.

Where did you get Shotcut and how did you install it?
Prior to seeing your version and OS, I tested with version 21.03.21 on macOS, and I did not experience the problem with a 4K clip. The memory usage depends on the number of logical CPUs, parallel processing export option, and hardware encoder. Parallel processing, more CPUs, and software encoder all increase memory. I was on a machine with 16 logical CPUs, and the melt process for export only used up to 3.7 GB resident memory with parallel processing and software encoder. Notice, that I wrote "melt" (not Shotcut + melt) and "resident" (not virtual, you did not say how you are measuring memory usage and it is not simple and obvious). Please try without parallel processing, monitor the `melt` process, and watch the RSS (resident set size) memory. 
Finally, memory intensive is not to be confused with a leak.

**Comment by AlexKotik** [comment]
> Where did you get Shotcut and how did you install it?
I installed it from official Manjaro's repositories (community) using official package manager (Pamac).

> The memory usage depends on the number of logical CPUs, parallel processing export option, and hardware encoder.
Well, I don't have the best computer suited for video editing, but I've done quite a few somewhat effects heavy videos lately and exporting them usually eats up around 3-5GB on my computer. I have 4 CPU cores and 8GB of RAM. I tried both with "Use hardware encoder" checkbox checked and unchecked. I get quite similar results.

> Please try without parallel processing, monitor the melt process, and watch the RSS (resident set size) memory.
I don't quite understand, how do I do that exactly?

> Finally, memory intensive is not to be confused with a leak.
Well, I started the export procedure. On 1% the memory usage is around 3.2GB and it started gradually increasing until all memory was eaten up at around 8-10% of export procedure (after around 15 minutes of export procedure). I don't know, but it looks like a memory leak to me. There are no effects being constantly added to the timeline or something, just the zoom parameter of the effect is changing. Why should the memory consumption be gradually increasing?

PS I can upload the project, so you could try it yourself, but I think the paths in the MLT XML file would be broken.

**Comment by bmatherly** [comment]
> I installed it from official Manjaro's repositories (community) using official package manager (Pamac).

We prefer to support our own builds. Please try again using the latest portable version.
Latest stable:
https://github.com/mltframework/shotcut/releases/tag/v21.03.21
Latest unstable:
https://github.com/mltframework/shotcut/releases/tag/v21.05.18
There is no need to install the portable version. Just extract and run.

> I don't quite understand, how do I do that exactly?
Uncheck "Parallel Processing" in the export tab

> PS I can upload the project, so you could try it yourself, but I think the paths in the MLT XML file would be broken.

The best scenario is if you can create the simplest project possible that recreates the problem. If you save the media and the mlt file in the same directory, then the paths in the mlt file can be relative. You could take that whole project and zip it up with the media and it can work for anyone who unzips it.
