### ISSUE TITLE
qscale changes when storing user defined export presets

### ISSUE THREAD

**Issue by zauberer777** [mltframework/shotcut#1074]
Win 10 Pro 19042.867 - Shotcut 21.03.21
When storing a user defined export preset, two errors happen:
1) The qscale in the user dialog changes to qscale=24
2) The stored qscale setting is higher by one, i.e. if I store qscale=10, then the stored preset is qscale=11 (increased by one)

**Comment by zauberer777** [comment]
As there was no response to my issue, I started digging myself.

> 1. The qscale in the user dialog changes to qscale=24
It looks like if the newly written preset file is not closed before shotcut tries to read it again. As I'm new to the project, I wanted to share the diff of the fix for review.
[Shotcut_01.zip](https://github.com/mltframework/shotcut/files/6470785/Shotcut_01.zip)

**Comment by ddennedy** [comment]
Thanks for the diff. Next time, please submit a pull request or just paste it. I confirmed your change fixes 1. but I do not reproduce 2.
