### ISSUE TITLE
Adding jpeg

### ISSUE THREAD

**Issue by Potatof** [mltframework/shotcut#1075]
Version 21.04
When adding jpeg file to the playlist, the thumbnail is white, the duration is 00:00:00:02, then if the picture is added in the timeline, the video is also white..

**Comment by ddennedy** [comment]
It works for me with pre-release versions 21.01.14 on Windows and 21.01.13 on Linux. Version 21.01.13 for Windows is known to be bad, and the beta release page was updated to 21.01.14 a day later. What is your full version and operating system?

**Comment by Potatof** [comment]
Hi ddennedy, the offending version was : 

https://github.com/mltframework/shotcut/releases/download/v21.04.13/shotcut-win64-210413.exe

Config:
Windows 10 64 - 32Go ram - 
Processor:"Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz , GenuineIntel
NVIDIA GeForce RTX 2070 SUPER

Back to version 21.03.21: everything is fine

**Comment by Potatof** [comment]
Ok, sorry for wasting your time

**Comment by ddennedy** [comment]
Not a problem; thanks for testing the beta and reporting it.
