### ISSUE TITLE
Text box disappears.

### ISSUE THREAD

**Issue by Yamiji** [mltframework/shotcut#1078]
Windows 8.1
Shotcut version 21.03.21

When trying to add text to a video it worked for a while, but now the text window disappears whenever 
 I try adding one to a video segment - 
![image](https://user-images.githubusercontent.com/10524661/115989379-526a4e80-a5be-11eb-89fa-03ebae5e088b.png)
 When it happens all text boxes across entire video disappear, showing up only for a split second when I select the segment. I tried restarting Shotcut, restarting PC, reinstalling Shotcut and changing display method to no avail. If I will keep adding text boxes to other segments, it might pop up again after many tries and then all the boxes show up allowing me to edit them, but if I add more they disappear again.

**Comment by ddennedy** [comment]
They play head must be over the clip you selected for the editor to appear. It is not a bug that it goes away otherwise. The easiest way to ensure the play head is over the clip when selecting to double click. That selects and seeks to the start of the clip.

**Comment by Yamiji** [comment]
Thank you, I had the feeling I was doing something to make it appear, but I wasn't able to pinpoint it down. I feel quite stupid now, since I actually tested a bunch of stuff today...
