### ISSUE TITLE
shotcut fails to export

### ISSUE THREAD

**Issue by T3cube** [mltframework/shotcut#1079]
when exporting a project (in my case i have a video, image and another video with chroma key filter), if you change the of the project and try to export shotcut exports nothing in zero seconds

i am using arch linux :Shotcut version ARCH-21.03.21
attatched are logs. nothing is changed exept for the resolution. changing encoders from h264 vaapi to amf has the export complete successfully. changing the resolution causes the export to fail
[fail.txt](https://github.com/mltframework/shotcut/files/6372107/fail.txt)
[success.txt](https://github.com/mltframework/shotcut/files/6372108/success.txt)

**Comment by ddennedy** [comment]
It works for me in version 21.03.21 but not in the current development version or recent beta. That is a sign that your distribution does not know how to properly manage the build of this package by using the incorrect version of MLT. In any case, I will accept in the context of the current beta.
