### ISSUE TITLE
big memory leak using Add All To Timeline with still images

### ISSUE THREAD

**Issue by AGOGUE** [mltframework/shotcut#108]
Configuration:
Shotcut 64 bits (up to date: 15.07.02 
Windows 7 integral 64 bits (up to date: SP1 ...)
P6T CPU card + Pentium i7 920
24 GB RAM

1 video full HD MP4 (45 seconds - 112MB) and  pictures (4Kx3K jpg  about 3MB each).
Pictures duration : 3 seconds each.
==> See file attached for pictures and video

Description:
When imported pictures or video in play list, source viewer is automaticaly playing the first picture for 10 mn. If I import to time-line pictures and video when source viewer is playing, the memory management is not good.  ===> See video attached for process and result.
If I stop source viewer playing before importation, memory management is OK.

Here is all tests I've made to have this conclusion
Between each test, shotcut is closed and launch again. 
I've used Windows monitor to see memory occupation

I import in play-list in one time 3 pictures + 1 video + 29 pictures and then import all play list in one time in time-line.
Video mode 1080p 25fps  (Source viewer stopped) ==> OK  2.77GB used 
Video mode 1080p 25fps  (Source viewer playing) ==> More than 20GB used (memory full) 
Video mode 1080p 25fps  (Source viewer stopped) ==> OK  2.67GB used 
Video mode 1080p 25fps  (Source viewer playing) ==> More than 20GB used (memory full) 
Video mode Automatic (Source viewer stopped) ==> OK  2.77GB used 
Video mode Automatic  (Source viewer playing) ==> More than 20GB used (memory full) 

All next tests have been made in Automatic video mode:
3 pictures (not more) are imported in time-line
Source viewer playing :  4.5 GB used
Source viewer stopped: 2.72 GB used

1 picture (not more) is imported in time-line
Source viewer playing :  3.32 GB used
Source viewer stopped: 2.72 GB used

1 video is imported in time-line
Source viewer playing :  2.81 GB used
Source viewer stopped: 2.70 GB used

8 videos are imported in time-line
Source viewer playing :  3.48 GB used  ==> Pb seems same for pictures and videos
Source viewer stopped: 2.73 GB used

This file is including:
1 Video showing how I process and result
1 Directory with pictures and video used
(Please download quickly, this link is not available for a long time)

**Comment by AGOGUE** [comment]
Sorry...
Here is link for pictures an video (same above)
http://dl.free.fr/qY5uyVGL0

And here is link for process and result:
http://dl.free.fr/bt7YL8b99

Thierry

**Comment by ddennedy** [comment]
I reproduced this only on Windows and when using still images.

**Comment by AGOGUE** [comment]
That's a great news so that now you can investigate.
Thanks for this information.

If you need help to test, just ask me.

Thierry



Le 09/08/2015 21:22, Dan Dennedy a écrit :
>
> I reproduced this only on Windows and when using still images.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mltframework/shotcut/issues/108#issuecomment-129227386>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by ddennedy** [comment]
I removed your free.fr links because the behavior of that web site is offensive.

**Comment by AGOGUE** [comment]
OK thanks.
Thierry


Le 10/08/2015 01:00, Dan Dennedy a écrit :
>
> I removed your free.fr links because the behavior of that web site is 
> offensive.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mltframework/shotcut/issues/108#issuecomment-129259157>.
>



---
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus
