### ISSUE TITLE
On reopen a project mlt the proxy files are no longer found - new issue in 21.04.14 Win10

### ISSUE THREAD

**Issue by pauweh** [mltframework/shotcut#1083]
Up to 21.03.21 proxy file handling was no problem. 
With new version proxy files are generated and shown as available in playlist and timeline with the (PROXY)-comment below the filename. When reopening the saved mlt-file again the proxy files are not found agaion and the (PROXY)-comments are gone. Removing files from playlist and adding them again will show (PROXY)-comment again without creating them again. Looking on the proxy folder settings shows no problem.

**Comment by ddennedy** [comment]
This was already fixed. See the thread about this beta version:
https://forum.shotcut.org/t/test-the-version-21-04-pre-release/26818/14
