### ISSUE TITLE
Proxy file creation is not using hardware encoding - v21.04.14 Win10

### ISSUE THREAD

**Issue by pauweh** [mltframework/shotcut#1084]
When adding files to the playlist a proxy file is generated. This jobs are shown. The CPU is 100% used, the GPU is near 0%. All settings in proxy generation are set similar to the export file settings. Proxy HW encoding is enabled and configured.
When sending the playlist files to FFmpeg with similar settings as used by Shotcut proxy generation, then encoding is using 100% GPU and is 10-20 times faster. Even when Shotcut uses HW-encoding this is only 5% GPU.

**Comment by ddennedy** [comment]
This is working fine as expected. For example, on my Windows system with NVENC:
```
[hevc_nvenc @ 000001479ebfa040] Loaded Nvenc version 11.0
[hevc_nvenc @ 000001479ebfa040] Nvenc initialized successfully
[hevc_nvenc @ 000001479ebfa040] 1 CUDA capable devices found
[hevc_nvenc @ 000001479ebfa040] [ GPU #0 - < NVIDIA GeForce GTX 980 Ti > has Compute SM 5.2 ]
[hevc_nvenc @ 000001479ebfa040] supports NVENC
[hevc_nvenc @ 000001479ebfa040] Using global_quality with nvenc is deprecated. Use qp instead.
```
The CPU is still used for decoding and scaling. You assume too much about what "hardware encoder" means. It mentions only one aspect of digital video handling. It does not say full end-to-end GPU processing. If you want that please suggest the ffmpeg command lines that includes scaling on the GPU for every combination of GPU vendor and operating system without ever copying the uncompressed video between CPU and GPU memory.

**Comment by pauweh** [comment]
Proxy file creation indeed could and should use full end-to-end GPU processing. Keep in mind, that GPU-HW-Usage is not the same as GBU-HW-Video-Encoding. FFmpeg seems to use different commands for these different things. See my screenshots with https://github.com/mltframework/shotcut/issues/1038 where you can see CPU, GPU and GPU Video-encoding usage of FFMpeg.
There you can find the FFmpeg command lines for end-to-end file to file video-encoding, too:
"ffmpeg -vsync 0 -hwaccel cuvid -hwaccel_output_format cuda -i 4k.mp4 -c:a copy -c:v hevc_nvenc -gpu all 4k-hevc_nvenc.mp4"
As Shotcut already knows on which system and hardware it is running and FFmpeg is already running too, it should not be a real problem to change the needed settings for the known system and the known hardware ;-))
