### ISSUE TITLE
Video Export file creation is not really using hardware encoding - v21.04.14 Win10

### ISSUE THREAD

**Issue by pauweh** [mltframework/shotcut#1085]
As in all versions yet, Shotcut is still not using Hardware encoding properly in Win 10. I guess it would speed up video export file creation, when in a first step Shotcut would generate a file which is not as time consuming as H.264 or HEVC H.265 but output speed optimized. Computing a time friendly first temp-file could be a first export step. Then sending this large first temp-file to FFmpeg using real GPU encoding in a second step would be more than ten times faster then creating only one file in one step. FFmpeg is able to encode 100 to 200 frames per second into compressed MPEGs. Shotcut is slow with only 1 - 10 fps - this takes 10 to 12 hours for a 15 minutes UHD 2160p 30 fps file. FFmpeg is able doing the same job within 1 hour on same hardware.

**Comment by ddennedy** [comment]
You are wrong. It is really using hardware encoding. It is improper to compare simple transcoding with video editing for reasons as explained in our [FAQ](https://shotcut.org/FAQ/). Try to use ffmpeg command line to edit your video. And no, I am not going to a huge lossless intermediate file to the process; you can do that yourself already.
