### ISSUE TITLE
Unable to export from source in v21.05.01

### ISSUE THREAD

**Issue by BlivetWidget** [mltframework/shotcut#1088]
Using shotcut-win64-210501 I am unable to export from source (Timeline | Other | Copy Timeline to Source ; then export).  The log claims a successful export, but the resultant file is very small and just displays INVALID.

Entirely of export log (attempting to export 2 second GIF):

```
plugin_mgr_get_object_file_plugins: error opening shared object file 'C:\Program Files\Shotcut\lib\ladspa/AUTHORS': "C:\Program Files\Shotcut\lib\ladspa\AUTHORS": The specified module could not be found.
plugin_mgr_get_object_file_plugins: error opening shared object file 'C:\Program Files\Shotcut\lib\ladspa/COPYING': "C:\Program Files\Shotcut\lib\ladspa\COPYING": The specified module could not be found.
plugin_mgr_get_object_file_plugins: error opening shared object file 'C:\Program Files\Shotcut\lib\ladspa/readme.txt': "C:\Program Files\Shotcut\lib\ladspa\readme.txt": 
[producer_xml] failed to load producer "(null)"
[gif @ 000001e684c8ebc0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[AVIOContext @ 000001e68646a000] Statistics: 0 seeks, 1 writeouts

Completed successfully in 00:00:02
```

I am, however, able to complete this operation successfully with valid output in shotcut-win64-210321.  This makes me pretty confident the issue is not on my end.  Please let me know if you need anything else from me, but it seems to me this is pretty straightforward to reproduce (not necessarily to solve, though, of course!).

**Comment by ddennedy** [comment]
This is related to [this bug report](https://forum.shotcut.org/t/bug-with-version-21-05-01-open-mlt-xml-as-clip/27307) in the forum. Copy Timeline to Source does the same thing as Open MLT XML as Clip. Fixed in ba5ad83
