### ISSUE TITLE
Window resizing issue

### ISSUE THREAD

**Issue by alexsourcerer** [mltframework/shotcut#109]
Shotcut starts with a small window size, so I need to resize it.
But even if I resize it manually (dragging the mouse from a corner), of by clicking on the adequate button, it freezes totally. Under Ubuntu, it turns grey, so that I need to kill it manually.

**Comment by ddennedy** [comment]
I do not reproduce this. It sounds like a compatibility problem with the video/gpu driver. Please provide the following information:
1.) What is the version of OS? 32- or 64-bit?
2.) What is the version of Shotcut? 32- or 64-bit?
3.) Where did you get Shotcut?
4.) Paste the output of the following terminal window command: glxinfo | grep OpenGL

**Comment by alexsourcerer** [comment]
OS : Ubuntu, 64 bits.
Shotcut 15.0.10, donwnloaded I don't remember
no problem anymore since I updated some drivers, mainly graphics drivers.
Thanks for your answer.
