### ISSUE TITLE
View | Enter Full Screen has no effect

### ISSUE THREAD

**Issue by BlivetWidget** [mltframework/shotcut#1090]
On Windows 10, shotcut-win64-210321 the option View | Enter Full Screen (F11) has no effect, or at least not the desired effect.  It seems to flip whether the program is maximized or not, but not in a way that makes sense.  That is, it flips the maximized / not maximized state depending on the current state.  Entering Full Screen when maximized sets it to not maximized (and changes the setting to Exit Full Screen, so the program thinks it is full screen).  Entering Full Screen when not maximized just sets it to maximized.

My assumption is that this setting is intended to do away with the window bar and taskbar (that is, to be _full_ screen).

Let me know if you need any further details, but this one seems pretty straightforward to reproduce.

**Comment by bmatherly** [comment]
This has been a limitation for some time:
https://forum.shotcut.org/t/fullscreen-mode-ctrl-shift-f-not-working-on-windows/3900

The underlying GUI framework that we use (Qt) seems to have some stability trouble on Windows in fullscreen mode. I just tested again on Windows using Qt 5.12.10. In my testing, there were no crashes, and the pop-up windows all seem to appear on top, but I would see screen flashes when opening/closing popups. So I do not think it is ready to enable full-screen on Windows yet.

**Comment by BlivetWidget** [comment]
It seems strange to me this would be a Qt limitation, as Open Broadcaster Software (OBS) also uses Qt and has a similar interface of arrangeable panels.  OBS fullscreen mode works as intended.  Thoughts?

**Comment by ddennedy** [comment]
Shotcut uses more and different Qt APIs than most Qt apps including OBS. In particular, it combines the Widget and Quick APIs. The Quick API is heavily dependent upon OpenGL (or a translation of it to Direct3D by ANGLE on Windows). I just retested it with our latest release version of Qt on Windows: 5.15.2, and it is still problematic. We will revisit this when we upgrade to Qt. In the meantime, toggling maximize is not a big sacrifice. 
You are correct, however, that the initial state of the menu item is incorrect if Shotcut starts maximized! I will fix that.
