### ISSUE TITLE
App Crashed when editing Textboxes or viewing them

### ISSUE THREAD

**Issue by wagnbeu0** [mltframework/shotcut#1091]
When adding a Textfilter to my movie, and just playing around with the Texteffects the app often crashes.

![grafik](https://user-images.githubusercontent.com/28983373/117689261-daa14400-b1b9-11eb-8022-cfe438e9e81c.png)

My Sytem: Win10 Pro 20H2, NVIDIA GTX 1050 Ti, 1 GB RAM, Shortcut 21.05.01

![grafik](https://user-images.githubusercontent.com/28983373/117688740-5b137500-b1b9-11eb-85d3-aeb27abb8b88.png)

**Comment by bmatherly** [comment]
> 1 GB RAM

If this is true, then it is almost certainly the problem. See minimum system requirements:
https://shotcut.org/FAQ/#what-are-the-minimum-system-requirements

**Comment by wagnbeu0** [comment]
@bmaherly Sorry was an typo, I changed it - 16 GB RAM is correct

**Comment by ddennedy** [comment]
Sorry but I have not reproduced this. You can try changing Settings > [Display Method](https://forum.shotcut.org/t/display-method/12705/2) to see if it makes a difference.

**Comment by ddennedy** [comment]
I am fairly certain this bug was fixed in 1f33ca6824a835d666ba5e1856a70c345c15f823
Please test newer version and reopen if needed.
