### ISSUE TITLE
"Drag from preview into track" makes shotcut frozen.

### ISSUE THREAD

**Issue by catscarlet** [mltframework/shotcut#1095]
This may not be a 100% reproducible glitch. I am not very sure.

OS: Linux Mint 20.1 Cinnamon
Graphic: Intel Corporation UHD Graphics 620 (Whiskey Lake) (prog-if 00 [VGA controller])
Shotcut version: shotcut-linux-x86_64-210501.AppImage

Reproducing step.

1. Open shotcut with a video(like using right click in file-explorer and open with shotcut, or just drag a new video into a blank shotcut window)
2. Drag the into timeline, it will automatically create a new track(V1)
3. Add one more track(V2)
4. (**Important**) Click **Open File** on the top left and select a new element (an image is prefered)(assuming select an image). The image now is showing on the preview.
5. (**Important**) Drag the image from preview to track(V2)

Click on timeline and the play function should be broken. The image always shows still on preview window.

![screenshot_by_flameshot_at_20210514215531](https://user-images.githubusercontent.com/10594035/118281566-f0876f80-b4ff-11eb-8925-1e5b9d55daf9.png)

The image should be showed on the video(V1) but now it shows still and the video refused to play.
If now click the Source tap of preview window(or do some other actions), shotcut freezes and dies.

Can't reproduce on the last two version: shotcut-linux-x86_64-210321.AppImage. I think only shotcut-linux-x86_64-210501.AppImage is affected.

**Comment by catscarlet** [comment]
OK I got more information
In step-4. The key action is open an element in preview window, and then **drag the element from preview window into track**.
If directly drag the element from file explorer into track, it does not get this issue.

And I'm sure in shotcut-linux-x86_64-210321.AppImage this function works. Only shotcut-linux-x86_64-210501.AppImage has this issue.

**Comment by catscarlet** [comment]
Also, this causes "Open Other" broken, which is confusing me. I used this function two days ago  and it works fine then.

**Comment by ddennedy** [comment]
I am not able to reproduce this. I am using Ubuntu 20.04 with Intel UHD Graphics 630 (close enough to yours). I tried a few times.

> Also, this causes "Open Other" broken,

How so? This only opens a menu (when used from toolbar) or a dialog (when using File menu). Or, do you mean something specific in Open Other?

**Comment by catscarlet** [comment]
> I am not able to reproduce this. I am using Ubuntu 20.04 with Intel UHD Graphics 630 (close enough to yours). I tried a few times. Thank you for the clear and detailed steps
> 
> > Also, this causes "Open Other" broken,
> 
> How so? This only opens a menu (when used from toolbar) or a dialog (when using File menu). Or, do you mean something specific in Open Other?

Open Other always open stuff in preview and you have to use **drag into track** to use the stuff. The **drag** is broken on my computer.

As I said, it's not a 100% reproducible issue. I tried today and it didn't reproduce well.
I tried short video in track(V1) and it can't be reproduced.
I think long video in track(V1) may be helpful(I used a 30mins video in V1)

**Comment by catscarlet** [comment]
Here. I recorded a screenshot video. [ytb_video_link](https://www.youtube.com/watch?v=CshCA6APdUI)

**Comment by catscarlet** [comment]
Test in shotcut-linux-x86_64-210518.AppImage and it still has this issue.
More info: My video file is stored on a external disk with usb3.0. When I drag video into track, it starts to build waveform very slow. After the waveform is built, and wait more time, this issue would disappear and shotcut will become functional again. Not very sure if this would helpful or not.

**Comment by ddennedy** [comment]
possibly related to #1114

**Comment by ddennedy** [comment]
Need retest on version 21.06.28

**Comment by catscarlet** [comment]
> Need retest on version 21.06.28

Test with shotcut-linux-x86_64-210629.AppImage. Not reproduced.

I think it's fixed.
