### ISSUE TITLE
qscale changes when storing user defined export presets - 2nd part

### ISSUE THREAD

**Issue by zauberer777** [mltframework/shotcut#1098]
Win 10 Pro 19042.867 - Shotcut 21.05.01

Thanks @ddennedy for fixing the first part of the issue #1074. Here's the 2nd part:

Configure preset:
- Codec = h264_qsv
- Bitrate mode = quality based
- qscale = 17

Save this setting as user defined preset. The saved preset will have qscale = 18

There is an inconsistency in the code regarding the range of qscale for _qsv codecs (1..51 or 0..51). By experiment, qscale=0 results in small files with poor quality, so 0..51 seems not to be correct.
 
```
src/docks/encodedock.cpp:369
        if (vcodec == "libx264" || vcodec == "libx265" || vcodec.contains("nvenc") || vcodec.endsWith("_amf")
                || vcodec.endsWith("_qsv") || vcodec.endsWith("_videotoolbox") || vcodec.endsWith("_vaapi")) {
            // 0 (best, 100%) - 51 (worst)
            ui->videoQualitySpinner->setValue(TO_RELATIVE(51, 0, videoQuality));
			
src/docks/encodedock.cpp:742
                    } else if (vcodec.endsWith("_qsv")) {
                        setIfNotSet(p, "qscale", TO_ABSOLUTE(51, 0, vq));

src/docks/encodedock.cpp:2002
    } else if (vcodec.endsWith("_qsv")) {
        s = QString("qscale=%1").arg(TO_ABSOLUTE(51, 1, vq));
```

**Comment by ddennedy** [comment]
Some codec, definitely x264, which is the default and most popular, support a qscale of 0.
