### ISSUE TITLE
spacing in text is missing after export

### ISSUE THREAD

**Issue by Photocreator** [mltframework/shotcut#1099]
Hello, after having exported my project (4k files with added text and effects) in some cases the added text is missing spacing. In this case the title for example is missing spaces after having exported my project at the default setting, MP4. Project settings are on automatic, which in this case is 4K 25 frames, which are my files. My computer has 16GB of ram, fast AMD processor, fast graphic card and runs on Debian 10, the latest version. Strange is that not all added text is missing spacing, no clue as to why only in some added text spacing is missing. I would like to send the project, but don't know how, can't get it to convert to a smaller MP4 file unfortunately or to any other supported file.  And 1,2 GB is a bit much. Shotcut version is the latest: version 21.05.01

**Comment by ddennedy** [comment]
Please indicate which filter you are using but its name and provide some example text or screenshots. To attach the project, locate the .mlt file and rename it as .txt or zip it.

**Comment by Photocreator** [comment]
hello, thanks for your quick response!I started to use the "color' option from "open other" to make a black clip, then added text from the filters "simple text". This I used as a title at the beginning of my project.This looked good as a project, but came out without spacing after rendering.I renamed the project file to a .txt file and attach it to this mail.Hopefully this will provide you with more information!

Kind regards, Arnoud

    On Sunday, May 16, 2021, 6:53:52 PM GMT+2, Dan Dennedy ***@***.***> wrote:  
 
 


Please indicate which filter you are using but its name and provide some example text or screenshots. To attach the project, locate the .mlt file and rename it as .txt or zip it.

**Comment by ddennedy** [comment]
Unable to reproduce
