### ISSUE TITLE
Changing Theme Maintoolbar bug

### ISSUE THREAD

**Issue by hbtalha** [mltframework/shotcut#1100]
Shotcut version: 21.05.01
OS Version: Windows 10 Home Edition version 21H1, OS Build 19043.985

When switching among the three themes(System, Fusion Dark, Fusion Light), the maintoolbar theme will not change along.

Fusion Dark -> Fusion Light

![Screenshot_3](https://user-images.githubusercontent.com/49079799/118499515-28640200-b70e-11eb-93e2-a2cd96d3c375.png)

 Fusion Light -> Fusion Dark

![Screenshot_4](https://user-images.githubusercontent.com/49079799/118499591-3a45a500-b70e-11eb-9b47-5ab7cc82ce7e.png)

Fusion Dark -> System

![Screenshot_1](https://user-images.githubusercontent.com/49079799/118499690-53e6ec80-b70e-11eb-8a91-a0de43a10d15.png)

The maintoolbar will not be the same as the rest of the program. However, if I set the theme again it will will fix it.

From System to the other two works fine.

**Comment by ddennedy** [comment]
Unfortunately, this is not the only thing affected. Toolbars and menus in Timeline and Keyframes do not update, and reselection does not resolve those. This is something that degraded when we upgraded our GUI library several versions ahead, and I do not know the fix for this. Basically, now, the immediate switch simply gives you an idea of the change, and you need to restart to see it completely. I can fix this by requiring a restart.

**Comment by hbtalha** [comment]
I just fixed the the problem when switching between dark and light. I would like to make a pull request and have that code fully reviewed and tested.
I am currently working on the fix to when I switch to System theme, it is proving to be difficult as it basically a one-line code. A suggestion would be to remove the 'System' theme option as I think it doesn't add any significant advantage as a feature.

**Comment by ddennedy** [comment]
Feel free to submit a PR but do not remove the System theme as that must stay.

**Comment by hbtalha** [comment]
@ddennedy 
Since you already fixed the issue by requiring a restart I don't think it is necessary to submit a PR as the code I changed only fixes part of the issue. Even so I tried submitting a PR but I can't figure out the coding style used and QT editor changes the entire file making it impossible to see where the real code change was made.
For reference here is the code that I changed that fixed the problem when switching between dark and light theme for the toolbar.

```
void MainWindow::changeTheme(const QString &theme) {
    
    LOG_DEBUG() << "begin";
    LOG_DEBUG() << "begin";
    if (theme == "dark") {
        QPalette palette;
        palette.setColor(QPalette::Window, QColor(50,50,50));
        palette.setColor(QPalette::WindowText, QColor(220,220,220));
        palette.setColor(QPalette::Base, QColor(30,30,30));
        palette.setColor(QPalette::AlternateBase, QColor(40,40,40));
        palette.setColor(QPalette::Highlight, QColor(23,92,118));
        palette.setColor(QPalette::HighlightedText, Qt::white);
        palette.setColor(QPalette::ToolTipBase, palette.color(QPalette::Highlight));
        palette.setColor(QPalette::ToolTipText, palette.color(QPalette::WindowText));
        palette.setColor(QPalette::Text, palette.color(QPalette::WindowText));
        palette.setColor(QPalette::BrightText, Qt::red);
        palette.setColor(QPalette::Button, palette.color(QPalette::Window));
        palette.setColor(QPalette::ButtonText, palette.color(QPalette::WindowText));
        palette.setColor(QPalette::Link, palette.color(QPalette::Highlight).lighter());
        palette.setColor(QPalette::LinkVisited, palette.color(QPalette::Highlight));
        palette.setColor(QPalette::Disabled, QPalette::Text, Qt::darkGray);
        palette.setColor(QPalette::Disabled, QPalette::ButtonText, Qt::darkGray);
        QApplication::setPalette(palette);
        QApplication::setStyle("Fusion");
        QIcon::setThemeName("dark");
        QMetaObject::invokeMethod(&MAIN, "on_actionShowTextUnderIcons_toggled", Qt::QueuedConnection, Q_ARG(bool, Settings.textUnderIcons()));
    } else if (theme == "light") {
        QApplication::setPalette(QApplication::style()->standardPalette());
        QApplication::setStyle(QStyleFactory::create("Fusion"));
        QIcon::setThemeName("light");
        QMetaObject::invokeMethod(&MAIN, "on_actionShowTextUnderIcons_toggled", Qt::QueuedConnection, Q_ARG(bool, Settings.textUnderIcons()));
    } else {
        QApplication::setStyle(qApp->property("system-style").toString());
        QIcon::setThemeName("oxygen");
    }
    emit QmlApplication::singleton().paletteChanged();
    LOG_DEBUG() << "end";
}
```

What I did was just `setStyle ` after I `setPalette`. Also in this manner if `MainWindow::changeTheme(const QString &theme)` is called twice for the dark fusion theme, the whole program will update the theme fine from what I saw.
