### ISSUE TITLE
Incorrect duration metadata makes it impossible to import to timeline

### ISSUE THREAD

**Issue by OoLunar** [mltframework/shotcut#1101]
OS: Windows 10, x64
Shotcut Version: 21.05.01

When importing a video with no duration metadata, it is impossible to import it to the timeline. While you can still watch the video, it is impossible to edit it. It'll appear as such:
![image](https://user-images.githubusercontent.com/46751150/118545597-6a944000-b71c-11eb-8e88-1dd1da1c8b11.png)
Note how the duration is set to 9942 days, 3 hours, 14 minutes and 7 seconds. When opening the video up in VLC, the proper duration/video length is shown: 1 hour, 47 minutes and 38 seconds.

Workarounds: None found other than fixing the duration metadata.
Potential Fixes:
- Having a tool to manually edit metadata
- Doing whatever VLC does to calculate the correct duration length

**Comment by ddennedy** [comment]
We cannot fix this. We get the duration from FFmpeg's libraries, and the version depends on what is most compatible. Not all videos will be read exactly the same by all tools. You can override this in Properties > Duration.

**Comment by OoLunar** [comment]
> and we will not add a dependency on VLC

Oh that wasn't what I was implying at all. I was thinking that y'all could reference VLC's code to see how they got the duration.
Regardless, thank you for the quick response. I'm a bit sad that it got shutdown so quickly, but I understand. Have a wonderful day

**Comment by OoLunar** [comment]
> You can override this in Properties > Duration.

Oh, I see what you mean now! I hadn't realized that the properties allowed you to edit the metadata already. Thank you!
