### ISSUE TITLE
Including a subfolder in a new project's name creates the folder, but can't create the MLT file.

### ISSUE THREAD

**Issue by ClairelyClaire** [mltframework/shotcut#1106]
OS is Windows 10 Enterprise build 21382. Shotcut version is 21.05.01.

I'm trying to create a new project in a subfolder created by the project:

![image](https://user-images.githubusercontent.com/3516276/119033251-dc110000-b961-11eb-8416-05c4e2574b72.png)

This does create the subfolder, but fails to create the file:
![image](https://user-images.githubusercontent.com/3516276/119033311-ecc17600-b961-11eb-8b57-a4e86d8544ae.png)

I can create a new project in the folder Shotcut creates without any problems, so it's not really a perms issue, near as I can tell.

I don't know if what I'm doing is supposed to be possible, but it appears to be trying.

**Comment by ddennedy** [comment]
This is unexpected, and I have no plan to permit this. You should not be doing this or not using a slash in the project name. We can add an error message if there is a slash.

**Comment by ClairelyClaire** [comment]
Yeah, that probably makes the most sense. As it stands, it's just getting confused. :)
