### ISSUE TITLE
export with alpha is not working in version 21.05

### ISSUE THREAD

**Issue by ddennedy** [mltframework/shotcut#1107]
Shotcut versions 21.05.01 and 21.05.18

As reported on Twitter and reproduced, export with alpha is broken:

> BulldogGamingTTV
> I'm having trouble with the exporting a video to have a transparent background. I use the webm VP9 with alpha like before, but it no longer works. I use this way to make my Twitch overlays. How do I fix this?

@bmatherly  Can you take a look at this one?

**Comment by bmatherly** [comment]
I am happy to look at this. Can you remind me the steps to make a video with transparent background?

**Comment by ddennedy** [comment]
Open Other > Text
Export > alpha preset
Export File

**Comment by bmatherly** [comment]
https://github.com/mltframework/mlt/pull/712

**Comment by ddennedy** [comment]
A workaround until the next release is to change a line in Export > Other after choosing the preset:
`mlt_image_format=rgba`

**Comment by ddennedy** [comment]
Fixed in https://github.com/mltframework/mlt/commit/3b65dfd1077310077ac7c04bc8d9cdc24d949be5
