### ISSUE TITLE
Black frames in slideshow when using multiple videos

### ISSUE THREAD

**Issue by mihaela1111** [mltframework/shotcut#1112]
OS Windows 10 Home Version 21H1 OS Build 19043.985
Shotcut Version 21.05.18 

I uninstalled Shotcut Version 21.05.18 and installed older Shotcut Version 21.02.27. When I opened the project in Version 21.02.27, the app told me it detected some issues and asked if I want to repair them. I repaired them and checked the project again, the issue was gone. Checked it after export as well, the issue was gone. Please repair this issue! Thank you!

**Comment by ddennedy** [comment]
I did not reproduce it.

**Comment by mihaela1111** [comment]
I had 20 mini videos, 11 seconds each. There is a black frame between them. Resolution 2560x1440, 60 frames per sec.

**Comment by ddennedy** [comment]
I tried doing it in a 1440p6 project, and I still did not reproduce it. I do not have 60 fps "mini" videos rather only longer ones - most several minutes and the shortest 42 seconds. You did not specify your slideshow settings here is what I used with a transition duration of 2.0 s and another test with 0. For each, I exported and played the export to look for black frames.
![image](https://user-images.githubusercontent.com/1146683/119930885-2b909680-bf35-11eb-9542-594da15d944b.png)

**Comment by mihaela1111** [comment]
Hi! 
I don't know where the Slideshow Settings are, did not find them. This is how I arranged my videos on the timeline. I do not use any transition. 
Initially, there were black frames between each video, and then after sliding them right-left some of them disappeared. However, I could not "fix" the black frames between the last 4 videos.  

![image](https://user-images.githubusercontent.com/84684300/119998015-fc336580-bfd8-11eb-9642-8aaa913c5111.png)

**Comment by ddennedy** [comment]
Why are you calling this a slideshow, and why are you using a separate track for each? You are making it difficult for yourself. If they are on the same track you can zoom in to more clearly see a gap, right click it, and close remove.

**Comment by mihaela1111** [comment]
I am using a separate track for each because they are different videos. If I want to replace them/change the order, it’s easier for me to identify them. Plus, there is no transition between them so I don’t need them to be on the same track. I know how to remove the gaps, if any. The issue exists in this version. Why the problem disappeared with an older version? For the moment, this is the only way I can make use of the app. This has not happened before, I am using Shotcut for more than 6 months now and my way of working with it has not changed.

**Comment by ddennedy** [comment]
I tried to create a project like yours, and I used snapping to line things up between tracks:
![image](https://user-images.githubusercontent.com/1146683/120037789-08a6c680-bfb7-11eb-8462-aa30c8175fb9.png)

But I still did not reproduce it. Thus, I will be unable to fix it. Maybe someone else will be able to.
