### ISSUE TITLE
Adding text applies only to entire clip

### ISSUE THREAD

**Issue by freebrowser1** [mltframework/shotcut#1113]
I tried Shotcut on and think it is an awesome editor, but there is a big BUT:

Adding texts to videos only applies to the entire clip, so I cannot add an intro text on the first few seconds and another explanatory text e.g. a minute later.
Other video editors, like Openshot, iMovie, Wondershare Filmora allow putting a text in just a small section of the video by putting a text timeline over the video.
I tried this in Shotcut, but to no avail.

Can this feature be added ?

Shotcut version 21.5.1
macOS 10.16.3 BigSur.

**Comment by catscarlet** [comment]
Add an extra track and use "Open Other -> Text" to make a text only video clip, then drag it into the new track. You will get what you want.

![screenshot_by_flameshot_at_20210529151953](https://user-images.githubusercontent.com/10594035/120061811-7d4e3380-c091-11eb-9d9f-27f1e70dfc67.png)
![screenshot_by_flameshot_at_20210529152047](https://user-images.githubusercontent.com/10594035/120061819-83dcab00-c091-11eb-9ee6-7368c0703cad.png)
