### ISSUE TITLE
On the problem of MLT library header file not found in compiling shotcut project with QT5.14.2

### ISSUE THREAD

**Issue by liquanguo** [mltframework/shotcut#1115]
Hello，when I tried to build shotcut with QT5.14.2,it indicated that MLT.H and MLTPROPERTIES.H files could not be found.
But I can find the MLT.H file int the \shotcut\src\mlt\src\framework\mlt.h directory.

Thanks

**Comment by bmatherly** [comment]
Building Shotcut works for me using this script in Linux:
https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut.sh
And this script in Windows:
https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut-msys2.sh

A lot more information will be needed to debug your specific problem.
What is your operating system?
How are you trying to build it?

**Comment by ddennedy** [comment]
You should use our [SDK](https://shotcut.org/notes/windowsdev/) and then you will need to figure it out yourself. The Windows build of Shotcut does not use pkg-config, for example, and you need to read `src.pro` to understand how MLT is located. It uses a qmake variable named `MLT_PATH`, which has a sensible defailt when using the SDK. (Our nightly build script bmatherly mentions overrides this for its folder organization.)
