### ISSUE TITLE
segfault when adding new video track

### ISSUE THREAD

**Issue by noahsmindfuck** [mltframework/shotcut#1116]
I am running shotcut for the first time on 
Kubuntu 20.04 
Kernel 5.4.0-73-generic
Qt 5.12.8 and 
Shotcut apt package shotcut/focal,now 20.02.17-2 amd64

When I want to add a new video track I the program just collapses. Logs are attached in file. Is there a way to get debug symbols to run it in gdb?

[shotcut_log.txt](https://github.com/mltframework/shotcut/files/6603788/shotcut_log.txt)

**Comment by ddennedy** [comment]
We do not support this build. Use one of ours.
