### ISSUE TITLE
You have macOS 10.14.6. The application requires macOS 10.10 or later.

### ISSUE THREAD

**Issue by tarilabs** [mltframework/shotcut#1117]
Mac OSX version 10.14.6 (18G9028)
Shotcut version shotcut-macos-ARM64-210518

result:
![image](https://user-images.githubusercontent.com/1699252/121153021-027dd900-c846-11eb-9cbc-329b6052c7ce.png)

🤔

**Comment by ddennedy** [comment]
I believe you downloaded the wrong build, and you should get Intel and not ARM unless you are using a Mac with an M1 chip.

**Comment by tarilabs** [comment]
Cool, but this is what the website proposed me:

![image](https://user-images.githubusercontent.com/1699252/121216966-ad5fb880-c881-11eb-81cb-b477f4366154.png)

as you can see, the table header says Intel, but allegedly the download was Arm and I basically didn't notice.

Thank you for the feedback and indeed using instead `shotcut-macos-signed-210518` found on this github repo worked.

Do you want to maybe reconsider the issue for the website?

**Comment by tarilabs** [comment]
ah, LOL, sorry I get it now, it was _not_ a table header, but a link with bold face 😅

**Comment by ddennedy** [comment]
The Intel build is emphasized with bold because that is what most people need. I think if the table did not already have column headings it would be absolutely confusing. I’m sorry, but nothing is going to prevent some people from choosing the wrong thing except a universal build.

**Comment by tarilabs** [comment]
Absolutely, sorry it was totally me not connecting today. Thank you for your patience and highlighting it to me.
