### ISSUE TITLE
UI scaling wrong with 4K Monitor - 200% DPI

### ISSUE THREAD

**Issue by AmonBune** [mltframework/shotcut#1119]
When using a 4K monitor (3840x2160) with 200% DPI, the UI looks horrible and is barely readable because some elements are too small.

Screenshot of the issue:
![image](https://user-images.githubusercontent.com/15927695/121683199-53e3cd80-cabd-11eb-8958-e568dc18af1e.png)

I pointed out the main issues (there are many more elements throughout the app which are too small):
![image](https://user-images.githubusercontent.com/15927695/121683336-85f52f80-cabd-11eb-812f-90d07a844076.png)

OS: **Windows 10 - 21H1 19043.1023**
Shotcut: **21.05.18**

**Comment by ddennedy** [comment]
I have not reproduced this, but others have reported similar issues. Here is mine where screen 1 is a 4K at 100% scaling, and screen 2 is 4K at 200%, and this was taken from screen 2

![image](https://user-images.githubusercontent.com/1146683/121786287-c31bf900-cb73-11eb-8a4c-6df42731c19b.png)

Are you using more than one screen? Did you change the Windows Shotcut shortcut properties? In particular, Compatibility > mode or high DPI settings?

**Comment by AmonBune** [comment]
@ddennedy I use two monitors: the main monitor is 4K @ 200% DPI, the secondary is a Full-HD 1080p monitor with 100% DPI.
the 4K monitor is 40" and my secondary one is 42". But this SHOULD not be an issue, since windows doesn't know how large the monitor is.
I still have to test if it looks better with the scaling factor set.

I'm not sure if it helps, but I recently fixed a scaling issue in my WPF app by enabling "per-monitor DPI support" in my app manifest. Perhaps there is something like that in Qt as well?

**Comment by LedAlex** [comment]
Have same issue. In my new setup primary 4K 150%, secondary FullHD 100%.
Shotcut takes font's size from primary monitor and becomes eye painful small on FullHD monitor.
<img width="960" alt="Безымянный" src="https://user-images.githubusercontent.com/27248144/123619018-6e35df00-d811-11eb-9024-80f6d601fb95.png">

**Comment by ddennedy** [comment]
Qt since upgraded to new major version 6, which fixes a lot of display scaling issues.
