### ISSUE TITLE
ARM64 Linux cannot save ?

### ISSUE THREAD

**Issue by freebrowser1** [mltframework/shotcut#1123]
Maybe stupid question, but I ran Shotcut under Ubuntu 18.04 in a prooted envrironment under Android (Andronix) which works rather well for other apps, like Gimp or Firefox.
Shotcut loads, editing works well, but when I click onto 'Save' I get a message 'Error saving file'. Same applies to 'Export'.
It does create an .mlt, resp. .mp4 file, but with zero bytes.
I then started it from a terminal see the output below.
It is run as a root user as I don't have another user on Andronix. Maybe this is a proot issue, but other apps save files normally.
OS: Ubuntu 18.04 arm64 prooted under Android 10.
Shotcut version: 20.05.24 (the 21 version was not available under arm64 ?).

Furthermore, Shotcut is awesome, I use it now frequently on my Mac where these probles do not occur at all. It does much more than iMovie supplied with macOS and is even better than the commercial app Wondershare Filmora 10.

On x86 Linux (Ubuntu 20.04) it also runs well.
Is arm64 Linux not well supported (as it does not appear in the list of releases) ?

<img width="509" alt="Screenshot 2021-06-23 at 19 48 47" src="https://user-images.githubusercontent.com/26625141/123145262-f0628400-d45c-11eb-9291-fdb3b6d664d4.png">

````  <producer id="producer0" title="Shotcut version 20.05.24" in="00:00:00.000" out="00:01:05.100">
    <property name="length">00:01:05:04</property>
    <property name="eof">pause</property>
    <property name="resource">/root/Videos/Blackbird-singing-20210620.mp4</property>
    <property name="seekable">1</property>
    <property name="aspect_ratio">1</property>
    <property name="audio_index">1</property>
    <property name="video_index">0</property>
    <property name="mute_on_pause">0</property>
    <property name="mlt_service">avformat-novalidate</property>
    <property name="creation_time">2021-06-20T16:33:20</property>
    <property name="shotcut:hash">169f0719faa6e5ab38076fef4207c8bd</property>
    <property name="ignore_points">0</property>
    <property name="shotcut:caption">Blackbird-singing-20210620.mp4</property>
    <property name="shotcut:skipConvert">1</property>
    <property name="shotcut:projectAudioChannels">2</property>
    <property name="shotcut:projectFolder">0</property>
    <property name="global_feed">1</property>
  </producer>
</mlt>
[Warning] <> QIODevice::read (QTemporaryFile, ""): device not open
[Debug  ] <MainWindow::closeEvent> begin 
[Warning] <> QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
[Warning] <> QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
[Debug  ] <Database::shutdown> database closed 
[Debug  ] <MainWindow::closeEvent> end 
root@localhost:~# 
````

**Comment by ddennedy** [comment]
We do not provide Linux ARM builds, and we only support the builds we provide. Also, "prooted envrironment under Android (Andronix)" is not something we know or really care about. You will need to debug this yourself.
