### ISSUE TITLE
Wrong conversion while fps change

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#1124]
All latest Shotcut versions.

Original project was made for FullHD 30 fps. Now I'm going to use 60 fps.
The problem is that some video files length is stored in number of frames. In our case 20 seconds 30 fps video has 600 frames.
If I'll try to change output video format, project becomes broken.  All video with length in frames will be twice shorter.
If same video file will be added after change to 60 fps it stores differently in project.
I've tried different versions of Shotcut, tried re-saves and other tweaks. Now the only way to edit xml manually, but project is big and that will take a lot of time...

<img width="1437" alt="1" src="https://user-images.githubusercontent.com/27248144/123727625-99184580-d89a-11eb-94c9-442aac0d88f5.png">
<img width="410" alt="2" src="https://user-images.githubusercontent.com/27248144/123727629-9a497280-d89a-11eb-9318-77c60436cfcf.png">

[Test.zip](https://github.com/mltframework/shotcut/files/6730185/Test.zip)

**Comment by ddennedy** [comment]
Your project file says version 21.03.21. I checked around 16 of my recent projects from the past half a year, and I found one instance of this, but I do not know how to reproduce it. I guess you did not learn the steps.

**Comment by bmatherly** [comment]
I was able to reproduce this issue using latest master. When dragging multiple clips from the window manager into the playlist, the first playlist item would have the correct time format, but the rest would have frame format.

I do not know the root cause, but this patch works around the issue: https://github.com/mltframework/shotcut/pull/1125

**Comment by ddennedy** [comment]
Note this is included in the next/21.07 release and not the version 21.06.29 that was released today.

**Comment by LedAlex** [comment]
Do you have nightly builds on some СICD server?

**Comment by ddennedy** [comment]
You can get last night's build in GitHub Actions: https://github.com/mltframework/shotcut/actions/runs/985554072

Please be aware that this fix currently does not correct existing projects.

**Comment by ddennedy** [comment]
There were major problems introduced in the first attempt to fix this rendering build 21.06.30 bad. These have been fixed; please wait until at least 21.07.01.

**Comment by LedAlex** [comment]
Ok. Thanks. Maybe I'll try nightly build a little bit later.

I'm fixing project manually in XML second day in row, blood already flows from the eyes... I have fixed it for new 21.06.29, but as it turned out all versions after 21.03.21 counts length in frames, even images. So now I'm going to to downgrade project to 21.03.21.
Honestly 21.03.21 is the only stable version for last half of year...
