### ISSUE TITLE
Cutting too much of a selected video clip and being moved to playlist completely crashes Shotcut

### ISSUE THREAD

**Issue by rockmetal58342** [mltframework/shotcut#1134]
Whenever I tried to clip a video file and then drag it to my playlist, it would completely crash Shotcut. It was stable for smaller cuts though, when I would cut 3 seconds of or something near that, it would be perfectly fine. But, when I cut off 20 or more seconds of a selected video clip, and when I would drag it to my playlist, Shotcut would completely stop responding. This happened on all video formats I tested.

Windows 10 Shotcut 21.05.18

**Comment by ddennedy** [comment]
You need to upgrade or downgrade below 21.05.01 and test. We are not accepting bug reports for any 21.05 versions.

**Comment by rockmetal58342** [comment]
My bad, should've checked for a new version. Ill report back in a few minutes

**Comment by rockmetal58342** [comment]
In conclusion, I just had to update my version. Updated my Version to 21.06.29, everything is working just fine.
