### ISSUE TITLE
Segmentation Fault when editing .avi file

### ISSUE THREAD

**Issue by dougkdev** [mltframework/shotcut#1136]
Shotcut version 21.03.21 (also happens on 21.06.29) Ubuntu 18.04

Steps to reproduce:
1) create a new project (Video mode: HD 1080p 30 fps) but it also happens with automatic video mode
2) drag the problem-causing video file to the timeline - video can be downloaded (1.2 GB) from https://drive.google.com/file/d/1nWEKJKU9XjanYlj9_kpjDfZU2k9seVM1/view?usp=sharing

Shotcut crashes - Segmentation fault (core dumped)

Strangely, I think I was successfully using this same avi video earlier in the day without problems and then at some point shotcut crashed. Ever since the first crash, every time this video gets used, the crash happens, even in a new project. Same shotcut version before and after the issues (21.03.21), and I don't remember any other system updates happening before vs after, either.

No problem watching the avi video in VLC, and if I use ffmpeg to convert the avi to mp4 first, shotcut doesn't crash with the mp4 file.

**Comment by ddennedy** [comment]
Shotcut has a built in Convert function in Properties that we recommend over using ffmpeg command line, which is easy to do wrong. You can hopefully get to it before crash but first opening in Source player.

What package/build are you using?

**Comment by dougkdev** [comment]
I was using the Linux portable tar for 21.03.21 and then also tried shotcut-linux-x86_64-210629.AppImage to see if the problem persisted (which it did). It was crashing when I used the Source player, too, but reduced the number of repro steps by dragging directly to the timeline.

**Comment by bmatherly** [comment]
I had the same experience as you: the first time I opened the file in Shotcut it played fine. All subsequent attempts to open it result in a crash. I was able to catch the crash in GDB and it is crashing in the swscale library that Shotcut uses for color space conversion and scaling.

**Comment by ddennedy** [comment]
mediainfo output
```
ddennedy@Gamerbox-9400:~/src/mlt/build$ mediainfo '/home/ddennedy/Downloads/ship_waves_on_deck_1_island_of_hope_theater_splice_prelinger_archive.org_PD__00_09_50.avi' 
General
Complete name                            : /home/ddennedy/Downloads/ship_waves_on_deck_1_island_of_hope_theater_splice_prelinger_archive.org_PD__00_09_50.avi
Format                                   : AVI
Format/Info                              : Audio Video Interleave
Format profile                           : OpenDML
File size                                : 1.12 GiB
Duration                                 : 12 s 0 ms
Overall bit rate                         : 799 Mb/s
Writing application                      : Lavf57.83.100

Video
ID                                       : 0
Format                                   : YUV
Codec ID                                 : YUY2
Codec ID/Info                            : YUV 4:2:2 as for UYVY but with different component ordering within the u_int32 macropixel
Duration                                 : 12 s 0 ms
Bit rate                                 : 796 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:2
Compression mode                         : Lossless
Bits/(Pixel*Frame)                       : 16.000
Stream size                              : 1.11 GiB (100%)

Audio
ID                                       : 1
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 00000001-0000-0010-8000-00AA00389B71
Duration                                 : 12 s 0 ms
Bit rate mode                            : Constant
Bit rate                                 : 2 304 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Bit depth                                : 24 bits
Stream size                              : 3.30 MiB (0%)
Alignment                                : Aligned on interleaves
Interleave, duration                     : 21  ms (0.50 video frame)
```
