### ISSUE TITLE
Shotcut core dumps when moving clips as first in timeline with ripple trim and drop

### ISSUE THREAD

**Issue by Barro** [mltframework/shotcut#1139]
Shotcut core dumps whenever moving multiple clips to be the first on the timeline with "ripple trim and drop" and "ripple edits across all tracks" timeline editing options enabled. This happens with Shotcut versions 21.03.21 (shotcut-linux-x86_64-210321.txz), 21.06.29 (shotcut-linux-x86_64-210629.txz), and Shotcut version 21.01.31 (the one that comes with current Debian testing).

I have attached an example project with 3 transparent clips [move-me.mlt.gz](https://github.com/mltframework/shotcut/files/6896367/move-me.mlt.gz) that you can use to try it yourself. Attached video simplescreenrecorder-2021-07-28_23.51.28.mkv.gz](https://github.com/mltframework/shotcut/files/6896400/simplescreenrecorder-2021-07-28_23.51.28.mkv.gz) demonstrates the core dump happening when moving the 2 clips from end of the timeline to the beginning.

I'm using x86-64 version of Debian testing as the base system.

**Comment by ddennedy** [comment]
Thanks for the excellent bug report.
