### ISSUE TITLE
linux opengl - 15.09

### ISSUE THREAD

**Issue by myswiat** [mltframework/shotcut#114]
bug:
[Warning] <> libpng warning: iCCP: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG
[Warning] <> QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
[Fatal  ] <> Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior 2, swapInterval 1, profile  0) 
Aborted (core dumped)

System: Ubuntu 15.10 beta1 64 bit.
intel: 2.99.917+git20150808-0ubuntu2
mesa: 10.5.2-0ubuntu1
drm: 2.4.63+git...
libqt5...: 5.4.2+dfsg-4

**Comment by ddennedy** [comment]
Does your download file name include "150911"?
Shotcut requires OpenGL on Linux. Please provide the output of "glxinfo | grep OpenGL".

**Comment by ddennedy** [comment]
Also, in a console window, please:
```
cd path/to/Shotcut/Shotcut.app
source source-me
ldd lib/qt5/platforms/libqxcb.so
```

**Comment by ddennedy** [comment]
reproduced by /dev/harald, who is looking into this.

**Comment by metellius** [comment]
myswiat, what does glxinfo give you?

**Comment by emdete** [comment]
hi, have the same problem, here the requested infos:

glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.6.5
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.6.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 10.6.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

ldd lib/qt5/platforms/libqxcb.so
	linux-vdso.so.1 (0x00007fffab1fc000)
	libQt5XcbQpa.so.5 => /home/mdt/Downloads/Shotcut/Shotcut.app/lib/libQt5XcbQpa.so.5 (0x00007f13a1c65000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f13a1a38000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f13a1836000)
	libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f13a1626000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007f13a141d000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007f13a1200000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f13a0fde000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f13a0da0000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f13a0af5000)
	libQt5DBus.so.5 => /home/mdt/Downloads/Shotcut/Shotcut.app/lib/libQt5DBus.so.5 (0x00007f13a0879000)
	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007f13a0676000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f13a046e000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f13a015f000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f139ff54000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f139fd42000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f139f9ff000)
	libQt5Gui.so.5 => /home/mdt/Downloads/Shotcut/Shotcut.app/lib/libQt5Gui.so.5 (0x00007f139f1eb000)
	libQt5Core.so.5 => /home/mdt/Downloads/Shotcut/Shotcut.app/lib/libQt5Core.so.5 (0x00007f139eaa6000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f139e80e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f139e5f0000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f139e275000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f139df74000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f139dd5d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f139d9b4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f13a21cf000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f139d7ae000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f139d5aa000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f139d3a4000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f139d17a000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f139cf5f000)
	libpng12.so.0 => /home/mdt/Downloads/Shotcut/Shotcut.app/lib/libpng12.so.0 (0x00007f139cd38000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f139cac9000)
	libicui18n.so.54 => /home/mdt/Downloads/Shotcut/Shotcut.app/lib/libicui18n.so.54 (0x00007f139c65b000)
	libicuuc.so.54 => /home/mdt/Downloads/Shotcut/Shotcut.app/lib/libicuuc.so.54 (0x00007f139c2ac000)
	libicudata.so.54 => /home/mdt/Downloads/Shotcut/Shotcut.app/lib/libicudata.so.54 (0x00007f139a882000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f139a654000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f139a450000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f139a24a000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f139a031000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f1399e2b000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f1399c28000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f1399a25000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f139981d000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f139961a000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f1399414000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f1399205000)

i use an unstable debian.

**Comment by metellius** [comment]
does everyone use nvidia proprietary drivers?
try running just qmlscene (might have to install it from package repos), and run it to see if you like me get:
```
$ qmlscene
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
```
pretty sure this is a configuration issue and not shotcut specific. I haven't resolved the issue yet on my end though, trying to understand the complicated ld.so workings on ubuntu is aggravating.

this report here was useful in figuring out more about what's happening: https://bugs.launchpad.net/ubuntu/+source/nvidia-prime/+bug/1307466

**Comment by ddennedy** [comment]
On my machine at home I use NVIDIA proprietary driver with no problem. I am now reproducing this in a Fedora 21 VirtualBox VM that uses Mesa+llvmpipe. What is interesting is that other VMs running Manjaro and Ubuntu 12.04 also using mesa+llvmpipe are not reproducing it.

**Comment by ddennedy** [comment]
A new build is running now; should be ready in less than an hour.

**Comment by ddennedy** [comment]
The new download is ready. Please retry.

**Comment by metellius** [comment]
works for me.

**Comment by myswiat** [comment]
Thx, now works :)
Close.

**Comment by emdete** [comment]
the download file has the exact same name - is that intended? anyway it starts now. thanks!
