### ISSUE TITLE
High CPU, no GPU

### ISSUE THREAD

**Issue by igavronski** [mltframework/shotcut#1152]
Not sure if it is a defect or else...

OS and Shotcut versions: `Windows 10 .0.19043; Shotcut 21.05.18`

When converting to an "edit-friendly format," Shotcut (in fact, FFmpeg) jumps to close to 100% CPU while GPU usage is negligible. Why is that?

See task manager output:
![Screenshot 2021-09-02 194632](https://user-images.githubusercontent.com/14096908/131926715-d59af167-deea-46c7-a215-c1c151d9c509.png)

**Comment by ddennedy** [comment]
Not a bug. Convert does not use hardware encoder because it was not programmed to do that.
