### ISSUE TITLE
Transition invalid after gap removing

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#1154]
Shotcut All Versions.

Make sample project with three video tracks.
Make transition by D&D to left of third on second.
Transition works fine.
Make transition by D&D to left of second on first.
Both transitions works fine.
Remove gap between second video and second transition.
Second transition works fine.
Undo.
Second transition stopped working. Only third video is used in it.
Save project and reopen it.
We got "Invalid" in second transition.

<img width="960" alt="1" src="https://user-images.githubusercontent.com/27248144/131930182-8a9e3776-8126-404d-8a55-eb05e72b9bd6.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/27248144/131930184-39dd6cd3-99a0-4a95-9051-062bda22974f.png">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/27248144/131930185-111a143f-40fd-488f-9317-f68ebab78497.png">
<img width="960" alt="4" src="https://user-images.githubusercontent.com/27248144/131930186-7134e641-6ad1-4fa7-97ba-a61d4bc8517e.png">
<img width="960" alt="5" src="https://user-images.githubusercontent.com/27248144/131930189-63ca5725-575a-472f-b9c8-af506f238da5.png">
<img width="960" alt="6" src="https://user-images.githubusercontent.com/27248144/131930190-878e123f-46a4-4ebb-be18-b28cb3971db3.png">
<img width="960" alt="7" src="https://user-images.githubusercontent.com/27248144/131930192-78e3b2b1-29ea-4138-aa57-2ae8590a0555.png">
<img width="960" alt="8" src="https://user-images.githubusercontent.com/27248144/131930194-111de9ea-37d4-4b3b-bf0b-aa44b636d6e2.png">
<img width="960" alt="9" src="https://user-images.githubusercontent.com/27248144/131930196-a01386e4-873a-4e98-8d98-4c706191fe8d.png">
<img width="960" alt="10" src="https://user-images.githubusercontent.com/27248144/131930199-1bb06991-ef77-45f5-bb9e-6ead9d9b15ec.png">

[Test.zip](https://github.com/mltframework/shotcut/files/7102383/Test.zip)

**Comment by ddennedy** [comment]
No longer reproduces, not sure when was fixed.
