### ISSUE TITLE
Version shotcut-macos-210913 immediately crashes on MacOS Mojave

### ISSUE THREAD

**Issue by aapple1944** [mltframework/shotcut#1158]
I get an immediate crash using 2109 and 2108 works fine. I am on 10.14.6 up-to-date on a MacPro 2010. I am attaching the latest crash log.

Thanks. Hope this helps. Sorry if this is a repeat. I did not see it in my search and am new to github.

[Shotcut_2021-09-20-122349_kea.crash.txt](https://github.com/mltframework/shotcut/files/7198346/Shotcut_2021-09-20-122349_kea.crash.txt)
!

**Comment by ddennedy** [comment]
I have a machine with macOS 10.14.6 where it is working fine, but there is a strong correlation with the problem described on Linux [in our forum](https://forum.shotcut.org/t/shotcut-does-not-work-on-ubuntu-20-04-3-lts-anymore/29857) considering your crash log shows it happening in the 360 video plugin.

**Comment by aapple1944** [comment]
Yes, I just launched 2109 on my Mojave laptop (MacBookPro14,3) and it does not crash. Perhaps GPU related?
Removing the plugins you suggested works and 2109 now works. Don't know what those plugins do.
Thank-you for your quick response.

**Comment by aapple1944** [comment]
Meant to say that the removal of plugs fixed the problem on the machine on which it crashed. Did not apply to laptop.

**Comment by ddennedy** [comment]
Please test an updated build that I believe fixes this: 
http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-macos-210920.dmg

**Comment by aapple1944** [comment]
It did fix it on my MacPro. Looks like you found it. I will let you close this if you think appropriate... not sure of the protocol.

**Comment by ddennedy** [comment]
Great! Fixed in 77521f4c9e28b34cf52aa200295595b9c1d3b298
I am doing some more testing and getting more feedback on the updated Linux build before releasing this as v21.09.20
