### ISSUE TITLE
Audio peak meter does not display correctly

### ISSUE THREAD

**Issue by callegar** [mltframework/shotcut#1159]
Probably most of a cosmetic issue.

The dB scale of the audio peak meter does not display correctly (seen on kubuntu linux using the shotcut flatpack, all recent versions, now at 21.09.20).

Specifically, the horizontal space allowed for the numeric scale is too small. Hence when you should see "0" you see only the left half of the "0", when you should see "-25" you see "-2" and then only the left half of the "5".

**Comment by ddennedy** [comment]
Looks OK to me
![image](https://user-images.githubusercontent.com/1146683/135303318-87324091-52da-4127-afe4-ee53fd77d1bf.png)

I changed the display scale to 150% and still looks OK
![image](https://user-images.githubusercontent.com/1146683/135303648-98594afa-0a3e-4898-a417-eb902e060281.png)

Reverted display scale to 100% and increased text size and still OK
![image](https://user-images.githubusercontent.com/1146683/135304051-59e43c64-aaf2-40ce-80af-6f98d0672511.png)

I was using Shotcut Flatpak on Gnome Shell on Ubuntu 20.04. I would not be surprised if it does not look perfect on every possible system configuration, but I am not going to chase all of them. Patch is welcome.

**Comment by callegar** [comment]
Sorry, I have not been clear in my initial reporting because I missed a word: the audio peak meter does not display correctly *initially*, when you start the application:
![Screenshot_20210929_175512](https://user-images.githubusercontent.com/1041166/135305332-3acb86d5-ea5c-41e0-904d-6ab0cf2389e9.png)
Weird enough, when the application needs to actually draw the meters, because you open and play a track including some audio channels, the scale gets fixed as in your illustrations. So it looks like the application changes the space allocation for the scale depending on the meters being shown or not.

**Comment by ddennedy** [comment]
Ah, yes, that I do see, but I have not given much time and priority to fix that. :-)

**Comment by callegar** [comment]
Very understandable. This is why I said "cosmetic issue" (I said "probably", just because I did not know for sure if there were other implications, but from what I read I believe there are not).  May be worth a fix because it is in the first "face" of shotcut that a new user sees.
