### ISSUE TITLE
Unused transitions cause enormous performance loss and memory leak

### ISSUE THREAD

**Issue by AgStarRay** [mltframework/shotcut#1160]
I had a long editing session that involved splitting 3 hours of footage into 4 videos. This resulted in me deleting lots of clips and tracks to prepare each next video, and thus it broke a lot of links concerning the transitions I accidentally made. On the last video, I took a break and closed the editor. When I opened the project again, the editor was unresponsive. I decided to close the editor and shut the computer off.

On the following day, I tried opening the project again, and it had very poor playback performance, and Shotcut was consuming 120 MB/s of RAM, a giant memory leak. I checked the logs and stuff like this was appearing.

[Debug  ] <MLT> [consumer sdl2_audio] dropped video frame 1
[Debug  ] <MLT> [consumer sdl2_audio] dropped video frame 2
[Debug  ] <MLT> [consumer sdl2_audio] dropped video frame 3
...
[Debug  ] <MLT> [consumer sdl2_audio] dropped video frame 14
[Debug  ] <MLT> [consumer sdl2_audio] dropped video frame 15
[Debug  ] <MLT> [consumer sdl2_audio] too many frames dropped - forcing next frame
[Debug  ] <MLT> [consumer sdl2_audio] dropped video frame 16
[Debug  ] <MLT> [consumer sdl2_audio] dropped video frame 17
...

I decided to open the project in a text editor and I noticed the transitions had invalid b_track indexes. There was only one video track and one audio track, but the b_track index went up to 5. When I changed them all to 1, the editor was singing again and no more memory leak occurred. After that, I found out these transitions don't even exist, so I deleted them. I attached the broken project for reference.

Tractor properties
![tractor](https://user-images.githubusercontent.com/22349545/135650879-1f5ea597-d22c-46e5-9598-687c5dab85d4.png)
Before
![before](https://user-images.githubusercontent.com/22349545/135650705-67d11ad9-c5d0-459e-9a13-3a9e7966889b.png)
After
![after](https://user-images.githubusercontent.com/22349545/135650785-30753cb8-8771-4bb9-b800-932826194f87.png)

Microsoft Windows [Version 10.0.19043.1237], Shotcut version 21.09.20

[Project with Invalid b_track indexes.zip](https://github.com/mltframework/shotcut/files/7268520/Project.with.Invalid.b_track.indexes.zip)

**Comment by ddennedy** [comment]
Closing as expired, and I recall us having fixed some track operations causing incorrect track indexes in the XML.
