### ISSUE TITLE
Could Set In and Set Out  create a render range instead of deleting extra clips?

### ISSUE THREAD

**Issue by jackrgilmore** [mltframework/shotcut#1161]
This is super irritating. I don't know if it's possible or if you have the resources. The program is absolutely fantastic already. But if you could design a range select feature rather than a "clip everything" feature that would be awesome. Thanks!

**Comment by ddennedy** [comment]
This is unintelligible and nonsensical. Please provide full steps using the terms in the UI. What are you trying to achieve? Export a range of the timeline? We do not have anything we call “clip everything.” Ultimately if this is a feature request that is not accepted here; only hard defects.

**Comment by jackrgilmore** [comment]
Sorry. I'll try to be more clear. This isn't at all a high priority fix or a bug in the software. I was comparing Shotcut's features to Adobe premiere pro and Davinci Resolve. The feature I'm talking about is in the keyboard shortcut reference listed as "Set Out" and/or "Set In". When you use these functions, they appear to permanently delete all footage beyond or before the cursor respectively. I was thinking that it might be more effective if these shortcuts set up a highlighted range of footage that could then be rendered without deleting extra clips you want to use later in the editing process. Please let me know if that was a more helpful description.

**Comment by ddennedy** [comment]
The way to do this today is
1. Timeline > menu > Copy Timeline to Source
2. mark in and out points in the Source player
3. Export

When we add the timeline markers/region feature (in development) then we plan to offer export from a range directly.

The shortcuts you mentioned are for trimming and will not be extended for another purpose, but there will be shortcuts for this new marker feature.

**Comment by jackrgilmore** [comment]
Thank you
