### ISSUE TITLE
The waveform length of the sound is not displayed correctly

### ISSUE THREAD

**Issue by PangZhenHai-1973** [mltframework/shotcut#1162]
![just smaple is not same](https://user-images.githubusercontent.com/49462433/136303470-7c2f8779-9774-45bf-848d-b00b8d9e331b.png)
just sample is not same, The waveform length of the sound is not displayed correctly

**Comment by ddennedy** [comment]
I do not reproduce it, and you did not provide steps, operating system, or version.
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/1146683/136304311-c0691f09-61db-473a-9242-19ec318d8208.png">
