### ISSUE TITLE
Low pass (audio)

### ISSUE THREAD

**Issue by ghost** [mltframework/shotcut#1165]
why there is no low pass filter in Linux?

**Comment by bmatherly** [comment]
There is a low pass audio filter. It works for me using this build on Ubuntu 20.04
https://github.com/mltframework/shotcut/releases/download/v21.09.20/shotcut-linux-x86_64-210920.txz

**Comment by ddennedy** [comment]
If not using our build you need to install or build the SWH LADSPA plugins.
