### ISSUE TITLE
Shotcut 21.09.20 crashs a few handured times a day, reported by Windows “Reliability Monitor”

### ISSUE THREAD

**Issue by chenx77** [mltframework/shotcut#1169]
Shotcut 21.09.20 crashs a few handured times a day, reported by Windows “Reliability Monitor”, although you can use Shotcut without noticing it.

Windows 10 Pro
Processor: Intel(R) Pentium(R) Gold G5500 CPU @ 3.80GHz   3.79 GHz
RAM: 8.00 GB (7.79 GB usable)
System Type: 64-bit operating system, x64-based processor
Shotcut version Win 64, 21.09.20

When you use it, e.g., to export any mp4 video, it will generate a lot of 'Stopped working' error log, can be read-out by Windows “Reliability Monitor”, while the programm acturally still WORKING. The 'Stopped working' process usually pointed to '**shotcut.exe**' or '**melt.exe**' as following.

Some one suggested to WhiteList the entire Shotcut project folder and the appdata directory, as discussed in Community: 'https://forum.shotcut.org/t/shotcut-v21-05-18-crashing-frequently/27754/29, but it won't work either.

========================================
Description
Faulting Application Path:	C:\Program Files\Shotcut\shotcut.exe

Problem signature
Problem Event Name:	APPCRASH
**Application Name:	shotcut.exe**
Application Version:	0.0.0.0
Application Timestamp:	614908a8
Fault Module Name:	bigsh0t_eq_mask.dll
Fault Module Version:	0.0.0.0
Fault Module Timestamp:	614906a6
Exception Code:	c000001d
Exception Offset:	000000000000a07c
OS Version:	10.0.19043.2.0.0.256.48
Locale ID:	2057
Additional Information 1:	bd02
Additional Information 2:	bd02b367c4ddb63acd1be1118321261c
Additional Information 3:	1ad5
Additional Information 4:	1ad5f60f002a1383badf57f6d7e0b36d

Extra information about the problem
Bucket ID:	94a328638212d0ae9ed7b4273269833d (2222443021573129021)

Description
Faulting Application Path:	C:\Program Files\Shotcut\melt.exe

Problem signature
Problem Event Name:	APPCRASH
**Application Name:	melt.exe**
Application Version:	0.0.0.0
Application Timestamp:	614906c2
Fault Module Name:	bigsh0t_rect_to_eq.dll
Fault Module Version:	0.0.0.0
Fault Module Timestamp:	614906ad
Exception Code:	c000001d
Exception Offset:	000000000000a499
OS Version:	10.0.19043.2.0.0.256.48
Locale ID:	2057
Additional Information 1:	f618
Additional Information 2:	f618df8784840304de286c86e090b761
Additional Information 3:	b022
Additional Information 4:	b02293b9aa8b42ad6d0d6d29a7ca14dc

Extra information about the problem
Bucket ID:	39eca36acfb78230421b1e8e812db2c5 (1304670114455335621
![Screenshot (672)](https://user-images.githubusercontent.com/15191607/138140356-cd65e8a5-18e5-4e23-9439-94758af7f876.png)
![Screenshot (674)](https://user-images.githubusercontent.com/15191607/138140381-fde424ac-0c73-4476-b82a-ff5e43cfffc7.png)
)

**Comment by chenx77** [comment]
> That is a weird combination. It must be crashing in a way that you can observe it directly and not only through some reporting tool? I checked the Reliability Monitor on my system, and I do not see this. I do see a few over a few weeks, and these are expected because it is my development system, and bugs naturally occur temporarily during development.

> There is a known bug in the 21.09.13 version that affects CPU compatibility that I thought only affected Linux and macOS builds. See https://github.com/mltframework/shotcut/releases/tag/v21.09.20
> 
> > Fixed x86-64 CPU compatibility in Linux and macOS releases (broke in v21.09.13).
> 
> This was a bug in the dependency for the 360 video plugins that I had to [fix in that project](https://bitbucket.org/leo_sutic/bigsh0t/commits/8fe56f6d4e0deb93ac0eb0bc73fdbe35bd7614cb). However, checking the history of the build scripts and the bigsh0t change history, I see this bug is affecting Windows as well. I can definitely see this in the Microsoft Store report:
> 
> ![image](https://user-images.githubusercontent.com/1146683/138148199-7531f6d4-cfa1-4047-ab3c-bcdf808a211d.png)
> 
> We have a[ 21.10 beta version](https://github.com/mltframework/shotcut/releases/tag/v21.10.17) that contains the fix. Please try it. It definitely helps if you are able to _see_ the crash and verify you no longer _see_ it. Also, I will upload the 21.09.22 build that contains only this fix to the downloads page and MS Store.

**Comment by chenx77** [comment]
> > That is a weird combination. It must be crashing in a way that you can observe it directly and not only through some reporting tool? I checked the Reliability Monitor on my system, and I do not see this. I do see a few over a few weeks, and these are expected because it is my development system, and bugs naturally occur temporarily during development.

Just to proof this is real with a screen record that Reliability
 
> > There is a known bug in the 21.09.13 version that affects CPU compatibility that I thought only affected Linux and macOS builds. See https://github.com/mltframework/shotcut/releases/tag/v21.09.20
> > > Fixed x86-64 CPU compatibility in Linux and macOS releases (broke in v21.09.13).
> > 
> > 
> > This was a bug in the dependency for the 360 video plugins that I had to [fix in that project](https://bitbucket.org/leo_sutic/bigsh0t/commits/8fe56f6d4e0deb93ac0eb0bc73fdbe35bd7614cb). However, checking the history of the build scripts and the bigsh0t change history, I see this bug is affecting Windows as well. I can definitely see this in the Microsoft Store report:
> > ![image](https://user-images.githubusercontent.com/1146683/138148199-7531f6d4-cfa1-4047-ab3c-bcdf808a211d.png)
> > We have a[ 21.10 beta version](https://github.com/mltframework/shotcut/releases/tag/v21.10.17) that contains the fix. Please try it. It definitely helps if you are able to _see_ the crash and verify you no longer _see_ it. Also, I will upload the 21.09.22 build that contains only this fix to the downloads page and MS Store.

**Comment by chenx77** [comment]
>> That is a weird combination. It must be crashing in a way that you can observe it directly and not only through some reporting tool? I checked the Reliability Monitor on my system, and I do not see this. I do see a few over a few weeks, and these are expected because it is my development system, and bugs naturally occur temporarily during development.

With a screen record, try to proof this is happenning: “Reliability Monitor” reports a lot error, while Shotcut still working. I refreshed the RM during Shotcut's launch, load project file Study.mlt, and export video. Each time new error added to RM. And finally the generated video file Study7.mp4 replayed very well.

Du to the size limitation, I have to share the screen video over GD: https://drive.google.com/drive/folders/125ISObeCWjaUv-WngfEcgcJCn0I73YlD?usp=sharing

> > Fixed x86-64 CPU compatibility in Linux and macOS releases (broke in v21.09.13). 

This was my mistake, that I involved a piece of Demo How to Report, but forgot to remove it. There is nothing to do with Linux and macOS releases. Sorry for that.

**Comment by ddennedy** [comment]
Thank you so much for helping!
