### ISSUE TITLE
Crashes when trying to open (version 15.09.11 Kubuntu 15.04 x64)

### ISSUE THREAD

**Issue by jessedubord** [mltframework/shotcut#117]
When I try to run the program via konsole, Shotcut briefly flashes the logo and interface, then crashes. Konsole returns this:

[Warning] <> libpng warning: iCCP: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG
[Warning] <> QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
[Fatal  ] <> Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior 2, swapInterval 1, profile  0) 
Aborted (core dumped)

Running Shotcut 15.09.11 on Kubuntu 15.04 x64 w/ KDE Plasma 5.3.2.

**Comment by ddennedy** [comment]
Does your install have a Shotcut.app/lib/qt5/xcbglintegrations/libqxcb-glx-integration.so file?
If not, then you need to re-download and re-install. There was a short-term packaging error.

**Comment by jessedubord** [comment]
That worked! Thank you, Dan.
