### ISSUE TITLE
If i open filters and then click on something in the timeline it crashes

### ISSUE THREAD

**Issue by Abelkrijgtalles** [mltframework/shotcut#1174]
I have downloaded shotcut today cuz I need a video edited for today 17:00 CEST. (It doesn't need to be fixed before that)
First my shotcut crashed, and then I had restored it.
Then I opened the filters tab/window that was not in my main window.
It was black.
Then I click on a clip and it crashed.

In the terminal, it says: Segmentation fault (core dumped)

(Sorry for the bad English, I'm Dutch)

OS: Ubuntu 20.04.3 LTS
Shotcut: Shotcut 21.09.20 (Downloaded from the snap store)

**Comment by ddennedy** [comment]
Did you use Shotcut successfully before? This sounds like your system is not compatible because basic things are not working. Shotcut depends heavily upon a *compatible* OpenGL implementation. What "compatible" is is rather difficult to define, unfortunately. Obviously, I do not experience this problem as well as thousands of others. If you are not using the `nvidia` display driver, you can try using Settings > Display Method > Software in Shotcut's menu.

**Comment by bmatherly** [comment]
Can you share a screenshot of the UI and filters tab before a crash?

After a crash, locate the file at:
/home/username/.local/share/Meltytech/Shotcut/shotcut-log.txt
Upload that log file here for people to view

**Comment by Abelkrijgtalles** [comment]
> Did you use Shotcut successfully before? This sounds like your system is not compatible because basic things are not working. Shotcut depends heavily upon a _compatible_ OpenGL implementation. What "compatible" is is rather difficult to define, unfortunately. Obviously, I do not experience this problem as well as thousands of others. If you are not using the `nvidia` display driver, you can try using Settings > Display Method > Software in Shotcut's menu.

Sorry for the long response, i had fixed it but then also not. But if i switch to `software display method` and then i open filters, it is gonna crash

**Comment by Abelkrijgtalles** [comment]
> Did you use Shotcut successfully before? This sounds like your system is not compatible because basic things are not working. Shotcut depends heavily upon a _compatible_ OpenGL implementation. What "compatible" is is rather difficult to define, unfortunately. Obviously, I do not experience this problem as well as thousands of others. If you are not using the `nvidia` display driver, you can try using Settings > Display Method > Software in Shotcut's menu.

Sorry for the long response, i had fixed it but then also not. But if i switch to `software display method` and then i open filters, it is gonna crash
