### ISSUE TITLE
can not build 21.10.31 on debian linux

### ISSUE THREAD

**Issue by alexmyczko** [mltframework/shotcut#1175]
i can't build the latest release on debian sid, here's a build log:

http://sid.ethz.ch/debian/shotcut/2021b/shotcut_21.10.31%2Bds-1_amd64.build

**Comment by bmatherly** [comment]
> models/markersmodel.cpp:328:64: error: ‘class Mlt::Properties’ has no member named ‘get_props’

Shotcut 21.10.31 only builds with MLT master at this time.

**Comment by ddennedy** [comment]
A new MLT version is releasing today or tomorrow.

**Comment by alexmyczko** [comment]
when advertising snap and appimage, why not also https://repology.org/project/shotcut/versions

**Comment by ddennedy** [comment]
We do not make, support, or recommend any packages except the ones on our download page. PERIOD!
