### ISSUE TITLE
A white box flashs on top-left corner of display, shortly after Shotcut launched

### ISSUE THREAD

**Issue by chenx77** [mltframework/shotcut#1178]
### How to reproduce
Launch Shotcut **version Win 64, 21.11.04**, no need from a MLT project, shortly after the shotcut logo splashing on the screen, there is a white box (almost the same size as shotcut splashing logo) flashes on top-left of display. This "feature" happened on earlier releases and builds as well.

A screen video attached here, it shows 3 successive launch and each caused a white box flashing.

https://user-images.githubusercontent.com/15191607/140316030-cc96d103-72c8-471a-87e7-8384f2e8ca9b.mp4

Noticed that, there was a similar categary of defect #1168 had been fixed and built into the test build **21.11.04**. So this is a different error other than #1168.

### Windows 10 Pro
Processor: Intel(R) Pentium(R) Gold G5500 CPU @ 3.80GHz 3.79 GHz
RAM: 8.00 GB (7.79 GB usable)
System Type: 64-bit operating system, x64-based processor

**Comment by ddennedy** [comment]
I found this happens because of View > Scopes > Video Zoom. It does not need to be turned on and visible. Simply its presence in the build. For example, excluding it makes the problem go away:
```
--- src/controllers/scopecontroller.cpp
+++ src/controllers/scopecontroller.cpp
@@ -47,7 +47,7 @@ ScopeController::ScopeController(QMainWindow* mainWindow, QMenu* menu)
         createScopeDock<VideoRgbWaveformScopeWidget>(mainWindow, scopeMenu);
         createScopeDock<VideoVectorScopeWidget>(mainWindow, scopeMenu);
         createScopeDock<VideoWaveformScopeWidget>(mainWindow, scopeMenu);
-        createScopeDock<VideoZoomScopeWidget>(mainWindow, scopeMenu);
+//        createScopeDock<VideoZoomScopeWidget>(mainWindow, scopeMenu);
     }
     LOG_DEBUG() << "end";
 }
```

**Comment by chenx77** [comment]
Great finding! I tried myself to fix it, but it is harder than I thought. And I tested your fix, it works perfectly. Thank you for your excellent effort!
