### ISSUE TITLE
rotate filter creates offset

### ISSUE THREAD

**Issue by mxa** [mltframework/shotcut#118]
The rotate filter set to 180 degrees produces a one pixel offset towards the right and downwards axis resulting in a black row of pixels on the left and top border.

**Comment by vilhok** [comment]
This issue is still present, at least in Windows version

Shotcut version: 19.06.15
Qt-version 5.9.7

**Comment by ddennedy** [comment]
Use Properties > Rotation now for multiples of 90 degrees.
