### ISSUE TITLE
Crash on dragging items from playlist to timeline

### ISSUE THREAD

**Issue by jamesb93** [mltframework/shotcut#1184]
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

os: 12.0.1 with M1 chip
version: 21.10.31

I am getting a crash occasionally when I drag items from the playlist to the timeline. It seems indiscriminate to the item itself.

[shotcut crashes.zip](https://github.com/mltframework/shotcut/files/7556607/shotcut.crashes.zip)

here are the crash logs.

**Comment by ddennedy** [comment]
Thanks. I took a look at your logs, and they all crash in the same manner within the main app/UI library we use called Qt. I have not reproduced, but neither do I have macOS 12; I am using 11.6. Are you dragging multiple items at once? (I tested both.) In any case, in the meantime, I suggest to use another of many ways to add to the timeline.

**Comment by jamesb93** [comment]
It doesn't seem to be limited to one or two items. If I can help debug it in anyway let me know.

**Comment by nobiado** [comment]
This seems to be exactly the same issue as #1218.
