### ISSUE TITLE
Desktop integration (Linux)

### ISSUE THREAD

**Issue by mxa** [mltframework/shotcut#119]
The current binary distribution format makes desktop integration difficult. A proper PPA or .deb file that adds repositories to the package manager would be greatly appreciated. That way Shotcut could be accessed through the menu and added to the app list that automatically uses the dedicated gfx card.
I have tried to follow [this instruction](https://askubuntu.com/questions/396857/how-can-i-add-processing-to-the-unity-launcher) (for processing) to integrate Shotcut manually in the desktop, but did not succeed.

**Comment by metellius** [comment]
I'm maintaining a ppa that just wraps the monthly here: https://launchpad.net/~haraldhv/+archive/ubuntu/shotcut

As for the discussion of 'correct' packaging, it has been done several times already, the most recent that comes to mind being #26.

**Comment by mxa** [comment]
Thanks, I wasn't aware of the PPA.
