### ISSUE TITLE
Can't export markers as chapters without manually editing .mlt file

### ISSUE THREAD

**Issue by Skeletonek** [mltframework/shotcut#1209]
Shotcut _(Windows version at least)_ can't export markers as chapters without me removing some data from .mlt file. If I try exporting markers as chapters after adding them, shotcut exports file with only "Intro" set to 00:00 and that's it. No other timestamp added. 

![1](https://user-images.githubusercontent.com/41450243/147987616-6bfce2cc-9943-4519-bce2-3c1d10cc4fe0.png)

If I manually edit .mlt and delete all \<track producer> and \<transition> in "tractor" where markers are stored, the project file corrupts itself but Shotcut successfully exports markers to .txt file

![remove](https://user-images.githubusercontent.com/41450243/147987323-8b38877a-7b71-4dd8-b7fb-9537e5d14cdf.png)
![2](https://user-images.githubusercontent.com/41450243/147987641-270ca74d-c159-469c-928c-a9e04931c741.png)

I'm sending .mlt files in link below. Obviously you will have problem opening them in Shotcut without source videos, but you can still open it as a text file.

[https://drive.google.com/drive/folders/1e-aRLS1d4GI4p1ZogvnkJKVrdNhVKUQl?usp=sharing](https://drive.google.com/drive/folders/1e-aRLS1d4GI4p1ZogvnkJKVrdNhVKUQl?usp=sharing)

**Comment by ddennedy** [comment]
This was already fixed for the next release. The latest nightly build exports chapters from your `Original.mlt` as
```
00:00 09.14 20.46
00:10 09.14 20.52
00:52 09.14 21.01
01:07 09.14 22.47
01:24 09.14 22.51
01:40 09.15 23.33
02:05 09.15 23.38
02:20 09.16 00.06
02:45 09.16 00.33
02:58 09.16 00.42
03:10 09.16 00.43
03:23 09.16 00.46
03:34 09.16 01.02
04:00 09.16 23.59
04:21 09.24 01.22
04:39 09.24 02.21
04:56 10.29 20.54
05:11 10.29 21.05
05:35 10.29 21.07
05:45 10.29 21.08
06:07 10.29 21.14
06:15 10.29 21.19
06:25 10.29 22.18
06:45 10.29 22.22
07:04 10.29 23.10
07:31 10.29 23.12
07:43 10.29 23.19
07:57 10.29 23.29
08:23 10.31 22.53
08:36 10.31 23.04
```
