### ISSUE TITLE
How do I make some video parts play faster or slower?

### ISSUE THREAD

**Issue by vi** [mltframework/shotcut#121]
With Shotcut I can easily make a skip or duplicate some part of video.

But how do I do a video like so: in the source video there is some frame where something strange is briefly shown. I want the video to slow down before that frame, show this frame paused for a few seconds (maybe with "hand-drawn" circle overlayed), then resume to normal speed?

Is it possible to do with current's Shotcut? Is it a planned feature?

**Comment by ddennedy** [comment]
This is not implemented, this is not a bug, and we do not take feature requests.

**Comment by vi** [comment]
Where do feature requests to Shotcut tracked and voted for then?

Is "subtitles should be preserved" a bug (so open an issue here) or a feature request?

**Comment by ddennedy** [comment]
Read the web site. I don't need a policy, and I do not work for you. The only "feature requests" I accept are patches or pull requests.
