### ISSUE TITLE
custom mask from file not saved with relative path

### ISSUE THREAD

**Issue by grahamjamesaddis** [mltframework/shotcut#1211]
Steps to reproduce:

Create a mask file in a subdirectory to the project directory
Add the Mask: From File filter, choose custom and select the mask file from the subdirectory.
Save the project.

Problem: the filter.resource property contains the full path to the file.

To workaround this behaviour, close shotcut, edit the mlt file and remove the prefix from the filter.resource. Shotcut will then work with the relative path correctly, until a new mask file is selected.

Windows:
Shotcut version 21.12.24
Edition	Windows 10 Home
Version	21H1
Installed on	‎20/‎04/‎2021
OS build	19043.1415
Experience	Windows Feature Experience Pack 120.2212.3920.0

Note: This is not a problem on my Mac running Shotcut 21.12.21

**Comment by ddennedy** [comment]
Windows has the complication that slashes can be forward or backward and drive letters are case-insensitive. Fixed for the next version, but it will fix most past projects without editing the XML to make drive letters upper case.
