### ISSUE TITLE
Image is exported as white (but is correctly displayed during shotcut editing)

### ISSUE THREAD

**Issue by NicolasMICAUX** [mltframework/shotcut#1213]
I created a custom png mask for my video (black and transparent), used as an overlay in a second video track.
I splitted it multiple times, but only the first segment exports correctly ! (others are exported as white)

**I solved it by replacing all segments (R) with the only mask that is working.**

The material encoder did not solved the problem, nor changing the codec etc.
I can't understand why there was a problem in the first place, this seems like a bug to me.
<hr>
I just had the same problem with 4 other images (all jpg images not splitted in any way. I solved the problem by replacing by the same image converted in PNG).

NB : this is the first time I get this bug, however I use shotcut for a long time, I never had this bug before.

CONFIG : Ubuntu 20.04.3 LTS - Shotcut 21.12.24

PJ : the files that made the bug appear
[bug.zip](https://github.com/mltframework/shotcut/files/7833377/bug.zip)

**Comment by NicolasMICAUX** [comment]
Should I close the issue if my problem is solved, but I still think it is a bug ?

**Comment by ddennedy** [comment]
I do not understand the steps. You might want to add the smallest project file that shows the problem if you have trouble communicating steps.

> I created a custom png mask for my video (black and transparent), used as an overlay in a second video track.

I assume you are using the Mask: From File filter. You should say that if so.

> I splitted it multiple times

What exactly is being split? I tried splitting the clip on V2 that has the Mask: From File filter with `mask.png` and Channel = Alpha.

> only the first segment exports correctly 

It worked for me.

**Comment by NicolasMICAUX** [comment]
I think I can't because it's a project for work.
But my problem is solved (converting everything from jpg to png and replacing all images in the project timeline), so I colse the issue.
Thx for the help.

**Comment by catscarlet** [comment]
Got same bug recently. 

LinuxMint 20.3(based on Ubuntu 20.04)- Shotcut 22.10.25

Sometimes after I changed the filename, this bug disappeared.
