### ISSUE TITLE
CuteLogger Makefile broken

### ISSUE THREAD

**Issue by bkauler** [mltframework/shotcut#1217]
shotcut 21.12.24, EasyOS 3.2.1, all required deps installed.

```
# export PKG_CONFIG=/usr/bin/pkg-config
# qmake PREFIX=/usr DEFINES+=SHOTCUT_NOUPGRADE DEFINES+=NDEBUG
# make
....
cqs libCuteLogger.a Logger.o AbstractAppender.o AbstractStringAppender.o ConsoleAppender.o FileAppender.o RollingFileAppender.o
make[1]: cqs: No such file or directory
```

It created CuteLogger/Makefile with this line:

`AR            = cqs`

I edited it:

`AR            = ar cqs`

And that fixed it. /usr/bin/ar exists, why isn't it found?
Never had this problem before.

**Comment by ddennedy** [comment]
With no change on my Ubuntu 20.04 system 
```
ddennedy@Gamerbox-9400:~/src/build-shotcut-Desktop_Qt_5_15_2_GCC_64bit-Debug$ grep -r cqs
translations/Makefile:AR            = ar cqs
src/Makefile:AR            = ar cqs
CuteLogger/Makefile:AR            = ar cqs
```
This is a problem on your system. People including many distributions are building on multiple OS without reporting this problem.
