### ISSUE TITLE
Video Player

### ISSUE THREAD

**Issue by Technosteve942** [mltframework/shotcut#1219]
Windows 10 pro; shortcut 21.12.24(all versions i am using this from the beginning of release) 
Video player is very bad during playing effects or transition or filters it lags out and even sometime crashes the software on best to best pc please make the player better it's a good video editor but i dont like the player if u fix it it will be one of the best video editor

**Comment by ddennedy** [comment]
Player speed is a function of your project complexity and computer. We do not accept this type of report as an actionable bug. Of course we want to make things better, but it is what is is. And that is not what causes a crash.

**Comment by ddennedy** [comment]
Also, you can learn to use Preview Scaling and Proxy. These are documented in our forum as well as a video on our [Tutorials](https://shotcut.org/tutorials/) page.

**Comment by Technosteve942** [comment]
Thx
