### ISSUE TITLE
Too much percents

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#1221]
Shotcut 22.01.17

When generating proxies, jobs shows a lot of percents, too much percents.
![2022-01-23 0000+](https://user-images.githubusercontent.com/27248144/150686941-2b35de11-228d-4037-934d-75f51004759f.png)

**Comment by ddennedy** [comment]
This is a known problem with GoPro clips that I also have. This is fixed for the release.

P.S. Shotcut since a couple versions now directly supports GoPro LRV files as proxies.
