### ISSUE TITLE
Crash on creating a project in Windows 10

### ISSUE THREAD

**Issue by dakshy** [mltframework/shotcut#1229]
Whenever I am creating a project in ShotCut, it is closing the window without an error. It is being repeated again and again.

OS: WIN 10
ShotCut Version: v22.01.30

**Comment by ddennedy** [comment]
Please explain **exactly** "creating a project"

**Comment by dakshy** [comment]
@ddennedy yeah, that is what I meant.
A video showing the defect: https://files.catbox.moe/7q5hy0.webm

**Comment by ddennedy** [comment]
Remove the emoji in the folder name or choose a different folder that does not have an emoji. With that said, I was not able to reproduce the problem with an emoji or the other problem with adding a file. Maybe a Windows security setting is blocking Shotcut such as Windows Settings > Privacy > File System or [Controlled Folder Access](https://support.microsoft.com/en-us/windows/allow-an-app-to-access-controlled-folders-b5b6627a-b008-2ca2-7931-7e51e912b034.).

**Comment by dakshy** [comment]
@ddennedy Thanks for replying.
 I tried with other folder with no emoji as well. But, ShotCut only creates a folder with the Project Name in that folder and the window gets closed. No change in the process.

**Comment by dakshy** [comment]
Sorry, I cannot wait much, so I have shifted to Filmora.

**Comment by dakshy** [comment]
The issue got fixed in new version. Thanks!
