### ISSUE TITLE
Secondary Colour Correction & L*a*b Adjustments

### ISSUE THREAD

**Issue by Arkoprovo1996** [mltframework/shotcut#1231]
Hello,
I'm a noob, who uses & loves Shotcut. So, I've found that practically the only & only thing missing from FOSS video editing on Linux is secondary colour correction tools, L*a*b adjustment curves (HH, HC, HL, etc.), a kind of mask as a scope to make colour corrections easier by focusing on the region of interest. I found the tools already existing in [RawTherapee](https://rawpedia.rawtherapee.com/Lab_Adjustments) & [Darktable](https://docs.darktable.org/usermanual/3.8/en/module-reference/processing-modules/color-zones/), as well as in [Natron](https://natron.readthedocs.io/en/rb-2.5/guide/compositing-color.html) & the blue banana tool in [Cinelerra GG Infinity](https://www.cinelerra-gg.org/wp-content/uploads/2018/11/Blue-Banana-cc-02.jpg). The former ones are better though in my opinion, nevertheless, I wanted to port them into Shotcut, Flowblade & Kdenlive, starting with shotcut. I know basic programming, but haven't worked on any full GUI app, save in web development. The colour bits I can do, but for the rest, I'm in need of guidance, even suggestions on reading material and like would do, like what to read and where to start things. So, just posting it here, if anyone can help me.
Thanks.

I hope this is a good place to post this.

**Comment by ddennedy** [comment]
Cross posted to forum and not a bug which is all we accept here.

**Comment by Arkoprovo1996** [comment]
Thank You
