### ISSUE TITLE
Filters: crop - rectangle

### ISSUE THREAD

**Issue by BX2ABT** [mltframework/shotcut#1234]
When applying the crop - rectangle filter it is possible to drag the rectangle to size in the source screen. It is not possible to change the numerical figures in the filter settings. Entering digits via a keyboard is possible, but after hitting enter they revert back to the previous digits. The up/down arrows also don't change the digits at all.

(Manjaro latest release, Shotcut 22.01.30)

**Comment by ddennedy** [comment]
This was already found and fixed for the next release. Thanks for reporting it.

**Comment by ddennedy** [comment]
fixed in 9e98df0
