### ISSUE TITLE
scale M, L boxes when changing  tracks height

### ISSUE THREAD

**Issue by petrica-celrau** [mltframework/shotcut#124]
not exactly a bug, more of an aesthetic issue, when making tracks shorter part of the audio track controls becomes hidden (M and L boxes). I'm wondering if scaling the font would help..

**Comment by ddennedy** [comment]
Specifically, this affects audio tracks. Since there is a border, scaling them will them tiny and illegible. Also, we might be moving these to icons.

**Comment by ddennedy** [comment]
The minimum height of audio tracks was increased by 10 pixels.
