### ISSUE TITLE
[Linux] HEVC (hevc_vaapi) encoding on Tiger Lake

### ISSUE THREAD

**Issue by babam86** [mltframework/shotcut#1240]
Can you patch FFmpeg with this to fix HEVC (hevc_vaapi) hardware encoding on Tiger Lake+

https://github.com/intel-media-ci/cartwheel-ffmpeg/blob/master/patches/0025-lavc-vaapi_encode_h265-fix-max_transform_hierarchy_d.patch

https://github.com/intel/media-driver/issues/1190

Thanks.

**Comment by ddennedy** [comment]
No it must go through upstream. I will not patch our FFmpeg source.
