### ISSUE TITLE
Shotcut crashes when you open filters and sometimes when you close filters

### ISSUE THREAD

**Issue by Abelkrijgtalles** [mltframework/shotcut#1242]
Hi, I had opened an issue a few months ago about Shotcut crashing when you close filters. Then I got asked if I could send some screenshots of the filters tab and somehow then I could close it, and it did not crash. And like a dumb idiot, I closed the issue. And if there was a new update, you could just open it normally.
But now there is an update (22.01.30 and 22.03.30) where it crashes if you open it, and sometimes you can open it, but if you close it, it crashes. Seeing the logs, I think it has something to do with the rendering and the CPU, because this was the error message:
`Segmentation fault (core dumped)`

Specs:
Ubuntu 20.04.1
Tested on: Shotcut 22.03.30 (Snap store and AppImage) and Shotcut 22.01.30 (Snap store)
Laptop: HP EliteBook Folio 9470m (B7S87AV)
CPU: Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz

**Comment by Abelkrijgtalles** [comment]
![Schermafdruk van 2022-03-31 17-41-27](https://user-images.githubusercontent.com/56084910/161095374-1301cb2e-f193-4353-ba0a-2634c5735fcd.png)
An image of the filters tab

**Comment by NumanIjaz** [comment]
faced the same issue, did you find any solution?

**Comment by Abelkrijgtalles** [comment]
nope

**Comment by ddennedy** [comment]
On some systems, due to OpenGL compatibility, you cannot let the Filters panel be floating and you need to dock it back into the main window.  Double-click the panel title bar (where it says "Filters") to dock it.

**Comment by Abelkrijgtalles** [comment]
Thanks, I will try it tomorrow

**Comment by Abelkrijgtalles** [comment]
Sorry for latte response, I have tested it today. If I can get a loose window to appear and not shotcut to crash, I can put it in the main window. That it crashes.

**Comment by Abelkrijgtalles** [comment]
I have tested it in OpenGL and software mode. And if I have placed it, and then it crashed, I open it up, and it's not placed.

**Comment by ddennedy** [comment]
- I have not reproduced the problem with Display Method = Software.
- Software Display Method does not work on systems with the `nvidia` binary display driver.
- Try redocking with no project loaded if you have not.
- You might need to reset your configuration to the default to make it return to docked upon restart. See https://shotcut.org/notes/configuration/ for the location of the config file. You can simply remove the `geometry` and `windowState` keys to reset the UI layout only, but if you are not confident to edit your config file you can also remove the file or rename or move it.

**Comment by luzpaz** [comment]
@Abelkrijgtalles can you still reproduce this on latest Release Candidate ?

**Comment by Abelkrijgtalles** [comment]
Switched OSes, so felt it to be good to close this issue
