### ISSUE TITLE
Shotcut 22.03.30 does not support Hardware acceleration

### ISSUE THREAD

**Issue by babam86** [mltframework/shotcut#1243]
OS: Slackware 15.0 x64
Graphic: Intel Iris Xe (iHD/intel-media-driver)
Shotcut version: 22.03.30 (Portable)

Shotcut 22.03.30 does not support hardware acceleration (h264_vaapi, hevc_vaapi)

Thanks.

**Comment by sergiomb2** [comment]
maybe is about ffmpeg 5 see https://code.videolan.org/videolan/vlc/-/issues/26772

**Comment by ddennedy** [comment]
It works for me on AMD Radeon on Ubuntu 20.04. VAAPI in portable binaries is always at risk of incompatibility.

**Comment by babam86** [comment]
Shotcut v22.01.30 can use hardware acceleration if libva* is removed and creates an iHD_drv_video.so link to the "va" directory, but in v22.03.30 it doesn't.

**Comment by babam86** [comment]
Yes it also works on v22.03.30, I had to remove libva* and create an iHD_drv_video.so link to the 'va' directory.

Thanks.
