### ISSUE TITLE
Changing from 50 FPS to 60 on existing project messes clips (includes solution)

### ISSUE THREAD

**Issue by sausagejohnson** [mltframework/shotcut#1244]
When making the mistake of editing a video in 50 FPS, and then trying to switch video mode to 60 FPS will cause audio and video clips (especially long video sources, cut up) to misalign, dissapear or grow very long on the timeline,

I am aware (I am now) of the following warning:

```it is important to set this as you desire at the beginning of your project. If you try to change it later Shotcut will try to retain the timing of edits, but some users have reported problems, and it is risky.``

I made the mistake of not checking my video and after days of editing found myself facing starting over.

When converting from 50 to 60 I resorted to hand editing the MLT file to try and restore the clips to their expected values.

I notice that shotcut is correct in its attempt to correct the timecode milliseconds for the clips, but the lengths of each "producer" node is not converted and it should be. Therefore to fix a project, the following needs to happen:

1. Timecodes must retain their values but the millisecond value should be converted. eg:

  <producer id="producer13" title="Anonymous Submission" in="00:00:00.000" out="00:03:12.420"> (50 fps)
  to
  <producer id="producer13" title="Anonymous Submission" in="00:00:00.000" out="00:03:12.350"> (60 fps)
  
2. Producer properties are not converted by shotcut, but they should be. This is the key to a better video mode change, eg:

  <property name="length">9622</property> (50 fps)
  to
  <property name="length">11542</property> (60 fps)
  
Those two things pretty much brought my project back from the dead, and only minor adjustments were needed. I have a demo project available if this if useful.
  
OS: Windows 10
Shotcut: 22.01.30

**Comment by bmatherly** [comment]
There may be multiple, unrelated things that do not handle video mode framerate change. This report is too vague to be actionable. If you can provide very specific steps to create a single problem, we can focus on that. We might need multiple bug reports for each problem.

As an example, here is a test I performed:

1) Create a blank project with video mode 720p 50
2) Put a clip on the timeline
3) Split the clip at exactly 00:03:00 and 00:06:00
4) Delete everything after 00:06:00
5) Save and close the project
6) Open the project and set the video mode to 720p 60
Observe that the split is at exactly 00:03:00 and the end is at exactly 00:06:00

Can you provide similar, succinct steps to demonstrate a bare minimum example to cause a problem?

**Comment by sausagejohnson** [comment]
I'll come up with a set of reproducable steps. Smaller clips are probably unlikely to show a significant result. I'll test small and large clips and make it very clear to reproduce and repair.
