### ISSUE TITLE
Missing Files Found but Repair Project Fails 

### ISSUE THREAD

**Issue by rvernica** [mltframework/shotcut#1245]
I moved around the project and the source files. When opening the project, Shotcut reports the missing files. I proceed with _Search in Folder_ and all the files are found:
![Screenshot from 2022-04-08 11-28-09](https://user-images.githubusercontent.com/241185/162500828-843b3a96-07ed-44a7-baa2-766b4b31ce70.png)
Once I click OK an error is reported and I see a 0 bytes `.mlt` file with _Rapaired_ append to it:
![image](https://user-images.githubusercontent.com/241185/162501446-cddedcf0-bfe8-4a13-85a6-831c06f7e3d0.png)
If I restore the files to the old location the project is opened successfully.
Version info
* Shotcut `21.08.03`
* Fedora `35`

**Comment by ddennedy** [comment]
This version is old and not supported (not one of our releases or builds).

**Comment by ddennedy** [comment]
Please try the latest Flatpak https://shotcut.org/download/
