### ISSUE TITLE
about reverse

### ISSUE THREAD

**Issue by mixneko** [mltframework/shotcut#1251]
for windows 22.03.30
your reverse is so weird
the video after reverse will be poor video quality for any set
maybe you can try the ffmpeg for reverse code follow this
`ffmpeg -i source.mp4 -vf reverse -y destination.mp4`

**Comment by bmatherly** [comment]
The quality is good when I test it. Can you clarify what poor video quality you see? Please provide:
* before/after screenshots
* The Video Mode for your project
* The export settings you are using

**Comment by mixneko** [comment]
hi the source video are [here](https://mixneko.org:2096/share.cgi?ssid=7f6adedb7f1f457db37526a5bb9039ad)
and [this](https://i.imgur.com/lKIbrrd.png) is shotcut setting
use shotcut [before](https://i.imgur.com/b6zNZT8.png) reverse and [after](https://i.imgur.com/00I6Hcr.png) reverse
this is I generate [gif](https://i.imgur.com/Tm6JSL5.gifv) to make the difference between the pictures more obvious
and I use ffmpeg [before](https://i.imgur.com/SnaFw3N.png) reverse and [after](https://i.imgur.com/cfb4D7b.png) reverse
it look normal

**Comment by ddennedy** [comment]
The way that you write it so weird.
You do not use any capitalization or punctuation. 
We cannot use the FFmpeg video filter because it requires [reading the entire media into memory](https://ffmpeg.org/ffmpeg-filters.html#reverse), which is not acceptable. People will try to reverse an entire large 4K60 video on a system with 4 GB RAM and complain that it fails.
Your command line loses quality too.

**Comment by bmatherly** [comment]
When I compare your before and after images, it looks like the brightness is increased. Is that what you mean by "poor quality"?

Before:
![image](https://user-images.githubusercontent.com/821968/163730668-0e283f4e-c070-4f4b-974d-1156dfb547af.png)

After:
![image](https://user-images.githubusercontent.com/821968/163730674-73531429-da99-4f12-9496-acbc4db37afc.png)

If the brightness is the issue, maybe Shotcut is not detecting the color range of your source clip for some reason.

**Comment by mixneko** [comment]
can I ask what think about to use 4GB memory to cut 4K60 video 
btw
if let ffmpeg to do cut first then to do reverse
maybe can fix the bug?

**Comment by bmatherly** [comment]
> can I ask what think about to use 4GB memory to cut 4K60 video
I would expect 4k60 video to require much more than 4Gb memory

That would be a good question for the [forum](https://forum.shotcut.org/)
This tracker is for bugs only

You maybe have found a bug in the color preservation of the reverse feature. But I am unsure.
Can you provide a screenshot of the "Properties" panel for your source clip? I would like to see the values for "Format", "Color Space" and "Color Transfer"
