### ISSUE TITLE
Commit of Sat Apr 30 12:14:09 2022 can't be built dueto missing fftw3.h

### ISSUE THREAD

**Issue by chenx77** [mltframework/shotcut#1255]
The following commit can't be compiled, due to missing header file fftw3.h etc.
 
commit e853e13a241c60d9d39ef171894da8ca44eae4ba (HEAD -> master, origin/master, origin/HEAD)
Date:   Sat Apr 30 12:14:09 2022 -0500

![Screenshot (983)](https://user-images.githubusercontent.com/15191607/166145500-36a06045-f9cb-4bb0-aa9a-63b74979f662.png)

OS: Windows 10
Shotcut SDK: 22.01.30

**Comment by bmatherly** [comment]
fftw3.h will need to be added to the SDK after the next release. In the meantime, you can download it yourself and add it into your environment.

FYI: after the next SDK release, you will probably have to make some changes in your QtCreator configuration as we are moving away from .pro and toward cmake:
https://github.com/mltframework/shotcut/commit/0ccd65dda61aa46d59c1694098c287d3de4f85ba

If you would be willing to help us write new instructions, we would be grateful.
