### ISSUE TITLE
Time Remap filter blend image mode does not work

### ISSUE THREAD

**Issue by tve** [mltframework/shotcut#1261]
The time remap filter with blend image mode does not work and renders white frames.
Per https://forum.shotcut.org/t/no-preview-in-time-remap-with-blend/33628/3 this broke after version 21.06.29

Shotcut 22.03.30
Linux x64 Manjaro

**Comment by bmatherly** [comment]
Fixed by https://github.com/mltframework/mlt/commit/12381397b68c1bf1eb222c82f0e3a41310dad6fd
