### ISSUE TITLE
Can't build due to missing ui_glaxnimateproducerwidget.h

### ISSUE THREAD

**Issue by chenx77** [mltframework/shotcut#1262]
The commit 3319e40432cb and earlier can't be built due to missing file ui_glaxnimateproducerwidget.h.

OS Windows 10
Shotcut SDK Windows 22.03.30
Shotcut commit 3319e40432cb9c0ab6f81bbcc87d9f8223db970c
Date:   Wed May 4 18:07:42 2022 -0700

![Screenshot (990)](https://user-images.githubusercontent.com/15191607/166938742-325ae3b4-7707-41b9-9abb-dcd9478a7ca2.png)

**Comment by ddennedy** [comment]
It builds fine using cmake. See our GitHub Actions. Qmake is no longer supported, and I will remove that today to make it clear.

**Comment by ddennedy** [comment]
Actually I altar removed qmake. Build support is not provided.
