### ISSUE TITLE
Audio crackling/popping in preview and exported video

### ISSUE THREAD

**Issue by lackovic** [mltframework/shotcut#1265]
Using **Shotcut 22.04.25** on **Windows 10 21H1**, the audio of an imported video sounds corrupted - i.e. contains cracks/pops - when playing the video, both in Shotcut preview and in an external player playing the exported video.

The crackling doesn’t appear in the source video when I play it in MPC-HC 1.9.20.30.

Codecs
Audio: mp4a, MPEG-4 AAC LC, 48000Hz, mono (1/0)
Video: avc1, H.264/MPEG-4 AVC
[Link to the source video file](https://mega.nz/file/Vg8lnaZD#gcq0TmnZ5uA0EtsoSbBFPo47NMfPB4Jogp1PKMyukZs)

**Comment by bmatherly** [comment]
> Codecs
Audio: mp4a, MPEG-4 AAC LC, 48000Hz, mono (1/0)
Video: avc1, H.264/MPEG-4 AVC
[Link to the source video file](https://mega.nz/file/Vg8lnaZD#gcq0TmnZ5uA0EtsoSbBFPo47NMfPB4Jogp1PKMyukZs)

Thanks for sharing your source file. I notice the odd frame rate of your clip - it is probably variable frame rate. Variable frame rate clips suffer from difficulty seeking - which is not good for video editors (even though media players play through them just fine).

I recommend clicking the "Convert" button. I tried that with your clip and the audio problem cleared up.

![image](https://user-images.githubusercontent.com/821968/169664187-6b0a6ea3-29e5-41c4-81d7-1ff40262d07c.png)

**Comment by ddennedy** [comment]
Variable frame rate is not supported and use that at your own risk such as this problem. We try to detect variable frame rate, but it not perfect or diligent because doing so would cause a performance problem when opening a video file (xN files when multiple are opened/dropped).
