### ISSUE TITLE
Build failure on FreeBSD 12.3 with shotcut 22.04.25

### ISSUE THREAD

**Issue by hhartzer** [mltframework/shotcut#1268]
Hi awesome Shotcut developers,

I'm trying to update the FreeBSD port for shotcut. This is what I have so far.

```
diff --git a/multimedia/shotcut/Makefile b/multimedia/shotcut/Makefile
index beae7d75f977..f692321912cd 100644
--- a/multimedia/shotcut/Makefile
+++ b/multimedia/shotcut/Makefile
@@ -1,7 +1,7 @@
 PORTNAME=	shotcut
 DISTVERSIONPREFIX=	v
 DISTVERSION=	${FULLVERSION}
-PORTREVISION=	3
+PORTREVISION=	1
 CATEGORIES=	multimedia
 
 MAINTAINER=	vishwin@FreeBSD.org
@@ -12,7 +12,7 @@ LICENSE=	GPLv3
 RUN_DEPENDS=	ffmpeg:multimedia/ffmpeg \
 		${LOCALBASE}/lib/libjack.so:audio/jack
 
-USES=		compiler:c++11-lang cpe desktop-file-utils gl mlt:6 pkgconfig \
+USES=		compiler:c++11-lang cpe desktop-file-utils gl mlt:7 pkgconfig \
 		qmake qt:5 sdl shared-mime-info \
 		xorg
 CPE_VENDOR=	meltytech
@@ -21,7 +21,7 @@ USE_GITHUB=	yes
 GH_ACCOUNT=	mltframework
 
 # Needed to be able to correctly check for updates in-app.
-FULLVERSION=	21.03.21
+FULLVERSION=	22.04.25
 
 USE_GL+=	gl
 USE_QT=		buildtools_build concurrent_build core declarative \
diff --git a/multimedia/shotcut/distinfo b/multimedia/shotcut/distinfo
index acc51bc72c3b..98ffe93960e2 100644
--- a/multimedia/shotcut/distinfo
+++ b/multimedia/shotcut/distinfo
@@ -1,3 +1,3 @@
-TIMESTAMP = 1616401712
-SHA256 (mltframework-shotcut-v21.03.21_GH0.tar.gz) = be668454896c540746a3d27c42c858d7652399722c7ec073c7cd3e52d7578ccd
-SIZE (mltframework-shotcut-v21.03.21_GH0.tar.gz) = 4101401
+TIMESTAMP = 1652462072
+SHA256 (mltframework-shotcut-v22.04.25_GH0.tar.gz) = 5531d513afcb807a25a1659c2ec013a42600a2a53a00f4aec0e631bd1baa3398
+SIZE (mltframework-shotcut-v22.04.25_GH0.tar.gz) = 4600941
```

When I run `make`, it eventually errors with this:

```
--- proxymanager.o ---
c++ -c -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -Wall -Wextra -pthread -fPIC -DSHOTCUT_VERSION=\"22.04.25\" -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_QUICKWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -I../CuteLogger/include -I/usr/local/include/mlt-7/mlt++ -I/usr/local/include/mlt-7 -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtOpenGL -I/usr/local/include/qt5/QtQuickWidgets -I/usr/local/include/qt5/QtWidgets -I/usr/local/include/qt5/QtQuickControls2 -I/usr/local/include/qt5/QtQuick -I/usr/local/include/qt5/QtMultimedia -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtXml -I/usr/local/include/qt5/QtQmlModels -I/usr/local/include/qt5/QtQml -I/usr/local/include/qt5/QtWebSockets -I/usr/local/include/qt5/QtNetwork -I/usr/local/include/qt5/QtSql -I/usr/local/include/qt5/QtCore -I. -I/usr/local/include -I. -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/freebsd-clang -o proxymanager.o proxymanager.cpp
--- mltcontroller.o ---
mltcontroller.cpp:1154:47: error: too many arguments to function call, expected single argument 'position', have 2 arguments
                animation.previous_key(delta, previous);
                ~~~~~~~~~~~~~~~~~~~~~~        ^~~~~~~~
/usr/local/include/mlt-7/mlt++/MltAnimation.h:48:4: note: 'previous_key' declared here
                        int previous_key( int position );
                        ^
1 error generated.
*** [mltcontroller.o] Error code 1

make[3]: stopped in /usr/ports/multimedia/shotcut/work/shotcut-22.04.25/src
1 error
```

My mlt7 package is version 7.4.0.

Could you point me in the right direction?

Thank you!

**Comment by ddennedy** [comment]
You need to upgrade MLT to the latest version.

**Comment by hhartzer** [comment]
That worked, thank you!

Shotcut compiles and launches. However, the timeline view just says "timeline" and there's no actual timeline.

Do you have any ideas of what that might be from?

**Comment by ddennedy** [comment]
It is normal that it is empty initially, but it should show a toolbar. This is normal
![image](https://user-images.githubusercontent.com/1146683/168376291-cc876b2d-3d83-4708-b9be-f2ddeb7dc517.png)

**Comment by hhartzer** [comment]
Unfortunately, mine doesn't look like that.

![shotcut](https://user-images.githubusercontent.com/100533792/168385296-2409fc03-585f-44ae-9f65-f4499c862a94.png)

Keyframes is the same.

![shotcut-keyframes](https://user-images.githubusercontent.com/100533792/168385344-af82fa39-bb8d-48d9-8ca9-d3d9aaef4f63.png)

**Comment by ddennedy** [comment]
These depend on OpenGL, which is probably not working on your system. This is stated in the system requirements in the FAQ.

**Comment by hhartzer** [comment]
Thanks for writing back!

OpenGL is working for me. I can run `glxgears` and other OpenGL applications.

I selected software (Mesa) rendering, and the timeline did not come back.

21.03.21's timeline works really well for me.

**Comment by vishwin** [comment]
(pinged through not-public email)
The actual cause is quickcontrols and quickcontrols2 not present on the user's system. There is otherwise nothing wrong here.

**Comment by hhartzer** [comment]
> (pinged through not-public email) The actual cause is quickcontrols and quickcontrols2 not present on the user's system. There is otherwise nothing wrong here.

Ah, thank you! That makes sense.

Appreciate the help!

**Comment by ddennedy** [comment]
Hi guys, glad you got that working. For your port please be aware the next version switches exclusively to cmake as the build tool.

It will also have a new feature to integrate with Glaxnimate that you might want to consider to port if not already. The MLT part of that is not yet released yet, but it uses git submodule and a custom CMakeLists.txt to integrate into MLT since the project does not have a separate library. This does not directly add a build dependency to Shotcut. But Shotcut gracefully hides the Glaxnimate feature if MLT does not include it.
