### ISSUE TITLE
Keyboard focus gets stuck sometimes

### ISSUE THREAD

**Issue by metellius** [mltframework/shotcut#127]
One way to reproduce:

* Create a video or audio track
* Type something into trackhead text field
* Click once on toolbar (or any other qwidget-based component)
* Click in the text field again

The text field will not show the caret, and you cannot type anything into the field. Clicking on another qml-based embedded component (for example the filter menu) then clicking back is a workaround for restoring the focus.

I have reproduced this behavior outside shotcut in a minimal example with a qwidget and qquickview, using createWindowContainer. I then wrote it into a QTest testcase:

```
#include <QWidget>
#include <QDebug>
#include <QTest>

class Bug : public QObject
{
    Q_OBJECT
private slots:
    void testDoubleWindowActivation();
};

void Bug::testDoubleWindowActivation()
{
    QWindow * view = new QWindow;

    QWidget w;
    QWidget * container = QWidget::createWindowContainer(view, &w);
    w.show();

    QTest::qWait(100);
    qDebug() << qApp->focusObject();
    QCOMPARE(qApp->focusObject(), &w);

    view->requestActivate();
    QTest::qWait(100);
    qDebug() << qApp->focusObject();
    QCOMPARE(qApp->focusObject(), view);

    w.setFocus();
    QTest::qWait(100);
    qDebug() << qApp->focusObject();
    QCOMPARE(qApp->focusObject(), &w);

    view->requestActivate();
    QTest::qWait(100);
    qDebug() << qApp->focusObject();
    //the following check fails because focusObject was never set back to the qquickview
    QCOMPARE(qApp->focusObject(), view);
}

QTEST_MAIN(Bug)
#include "main.moc"
```

Observing focus events inside qt, I see that at least all the way up to the QWindow+wm-event layer there is no trace of focus events coming in when clicking on the qml component, so I don't see myself fixing this easily without help. Reading bug reports and googling around, I get the feeling that QQuickWidget is regarded as a more robust way of embedding qquickviews. I modified my testcase to use QQuickWidget, and now the focus actually behaved as expected.

I'm looking into having shotcut using qquickwidgets instead of createWindowContainer for embedded qml components.

**Comment by ddennedy** [comment]
I too have made attempts at converting to qquickwidgets but have run into problems. I do not recall specifics, but I have a branch I could push.

**Comment by metellius** [comment]
I just made it work on the timelinedock here after doing  QCoreApplication::setAttribute(Qt::AA_DontCreateNativeWidgetSiblings); in order to resolve some rendering bugs, and that actually fixed the focus bug. Please do push your branch somewhere, I'd like to see what you tried.

**Comment by metellius** [comment]
Also, here's my wip commit: https://github.com/metellius/shotcut/commit/991ddc4e790fd4ce6d5fad402ad014d7a2c36dc8

**Comment by ddennedy** [comment]
Yours and mine (https://github.com/mltframework/shotcut/commit/53f5aaf0514be9a83ba2739f9907faa8572d65c4) are very similar, except I started with filter dock, and it is very broken.

**Comment by ddennedy** [comment]
I added your suggestion; that helped. And, I unbroke some things. See the tip of the branch if it helps: https://github.com/mltframework/shotcut/commits/quickWidgets

Now, the filter panel displays but clicking + does nothing.

**Comment by metellius** [comment]
Making the filtersdock StrongFocus fixed not being able to type in it:
```
    m_qview.setFocusPolicy(Qt::StrongFocus);
```

**Comment by metellius** [comment]
This makes it show up:
```
diff --git a/src/qml/views/filter/FilterMenu.qml b/src/qml/views/filter/FilterMenu.qml
index 19d2f48..7559392 100644
--- a/src/qml/views/filter/FilterMenu.qml
+++ b/src/qml/views/filter/FilterMenu.qml
@@ -37,6 +37,7 @@ Window {
         filterWindow.y = menuRect.y
         filterWindow.height = menuRect.height
         filterWindow.visible = true
+        filterWindow.show()
         filterWindow.requestActivate()
 
     }

```

**Comment by metellius** [comment]
https://github.com/metellius/shotcut/tree/danQuickWidget is my quickwidget commit cherry-picked and cleaned up on top of your branch. Focus works fine for both filters and timeline now! I'm excited to see the caret blink in just one place at a time :p
Still some quirks with key propagation (mainwindow isn't getting the key events that it should with timelinedock focused), but I think we're heading in the right direction.

**Comment by metellius** [comment]
Branch tip now includes a fix for the keyevent propagation - evidently qquickwidget has not yet fixed the bug that caused us to make ForwardingQuickViewWorkaround in the first place.

**Comment by ddennedy** [comment]
In my working copy of danQuickWidget branch, I made some fixes to vertical position of timeline menu and auto-closing the filter menu. However, there are problems with GLWidget. I did rather straight-forward conversion of it to QQuickWidget, but currently it deadlocks.

**Comment by metellius** [comment]
My key last keyevent commit was not enough - the mechanism that propagates ignore keyevents to the items ancestors is actually completely broken in 5.5.x due to this: https://bugreports.qt.io/browse/QTBUG-48343
Now that I understand what's going on I can see that it's workaroundable, but it sucks that we have to.
I got the same deadlock, and it's one I've seen many times before: consumer->stop() at the real_time property check. Is there something I can do to assist in debugging it? I feel a bit lost seeing all the mlt consumer/producer threads in gdb...

**Comment by metellius** [comment]
Understanding more now: the glwidget never got a call to initializeGL for two reasons: one being the sceneGraphInitialized signal being incorrectly connected (this is also printed to stderr), and the other is that the signal is never emitted at all since the glwidget is never shown, in turn because it is incorrectly attempted added with createWindowContainer in player.cpp. With these fixed, it is now crashing in

   [Debug  ] <void uploadTextures(QOpenGLContext*, SharedFrame&, GLuint*)>     Mlt::FrameRenderer(0x2a6f700, name = "FrameRenderer")
   [Fatal  ] <void qt_assert(const char*, const char*, int)> ASSERT:    "QOpenGLFunctions::isInitialized(d_ptr)" in file /mnt/stor/qt5/qt5/qtbase/include/QtGui/../../src/gui/opengl/qopenglfunctions.h, line 803

**Comment by metellius** [comment]
Much of the trouble here is related to the direct connections done to sceneGraphInitialized and beforeRendering - previously this would be on a different thread, but with qquickwidget this is now called from the GUI thread, causing locking and context switching trouble. I see how the beforeRendering signal is being used for painting gl behind the qml, and I have some suggestions for how this can be simplified later.

**Comment by metellius** [comment]
My branch is updated now - https://github.com/metellius/shotcut/commit/55f674eb3d6f40a6c78917dbab4e6a493a502a3f is a fix for the deadlock.

**Comment by ddennedy** [comment]
Great, now with all of these changes, I just need to test it good across all 3 platforms. All this just to fix a little text entry issue. Sigh. Did I mention yet how Movit HEAD changed a lot recently causing breakage on OS X and potentially how GL is used in Shotcut? So, yeah, it feels a lot like wheels spinning in mud lately.

**Comment by metellius** [comment]
Let me look at the missing event-propagation workaround first before you start testing - that was after all the reason for doing this.

**Comment by metellius** [comment]
Workaround in https://github.com/metellius/shotcut/commit/93d45193322a8c89379714293c3ee6489da53961. Seems to work fine, but obviously needs testing.

**Comment by metellius** [comment]
...and of course I discover another scenario minutes after posting; I'll have to look more at it tomorrow.

**Comment by metellius** [comment]
Allright, I found a better workaround in https://github.com/metellius/shotcut/commit/0049c09b08f9b739c7c4bc167a09c49714fbf0d0 . Instead of reimplementing the event propagation, I just rerouted the event through QQuickWindow::sendEvent where it is originally done. This is where it will pass through again once QTBUG-48343 is fixed...

**Comment by ddennedy** [comment]
This ready for testing on all OSes now?

**Comment by metellius** [comment]
Yes.

**Comment by ddennedy** [comment]
merged your quickWidgets branch
