### ISSUE TITLE
The folder contents could not be displayed. Operation was cancelled.

### ISSUE THREAD

**Issue by rockmetal58342** [mltframework/shotcut#1271]
Shotcut version 22.04.25

Pop!_OS 22.04

When I try to export a video, an error message pops up saying "The folder contents could not be displayed. Operation was cancelled." No matter what format or video clips I chose to edit. 

![image](https://user-images.githubusercontent.com/84007057/168978578-d5ad20a0-bf7f-4159-81bb-6c238591159d.png)

**Comment by bmatherly** [comment]
> When I try to export a video, an error message pops up 

Can you provide more detail? Does that message come from Shotcut? It does not look like a Shotcut UI. Or does the export succeed and the message comes from your operating system when you try to play the file?

**Comment by ddennedy** [comment]
I think this comes from the desktop environment's file dialog upon clicking **Export File** in Shotcut. It is weird and first I ever hear of it in 10 years. We need to know what the package format is such as appimage, deb, snap, or flatpak.

**Comment by rockmetal58342** [comment]
1. The message doesn't come from Shotcut itself I don't think, as it is the OS UI, but everything on my actual system seems fine. The export does not succeed, as it just quits immediately.

2. I downloaded the flatpak version from the Pop!_Shop

**Comment by ddennedy** [comment]
> The export does not succeed, as it just quits immediately.

Please explain that better. Does the file dialog to choose the output file appear? Does the export job appear in the Jobs panel in Shotcut.

**Comment by rockmetal58342** [comment]
The file dialogue to choose the output file does show up, and it shows the same time as the error message. I just checked again, no it does not show up on jobs panel.

**Comment by ddennedy** [comment]
This is an unknown problem with Flatpak. I do not yet know if this is specific to your system, your OS, or something wrong in our flatpak. Please use our portable or AppImage in the meantime.

**Comment by rockmetal58342** [comment]
Got it.
