### ISSUE TITLE
Not starting after installation on mac m1 with macOS 11.6.1 Big Sur

### ISSUE THREAD

**Issue by malmostafa8** [mltframework/shotcut#1273]
It seems like the app does not start on mac m1? Or am I missing sth?

macOS 11.6.1 Big Sur
Chip Apple M1
ShotCut 22.04.25 "ARM64 macOS"

**Comment by malmostafa8** [comment]
Just installed ShotCut v22.03.30 it launches without issues.

**Comment by ddennedy** [comment]
It requires Monterey now for ARM64. I mistakenly upgraded the build machine - the only Apple Silicon machine I have. Then,I thought surely everyone who has this machine surely wants to upgrade from the very first version of the OS to support ARM64!
