### ISSUE TITLE
Disabling new version check is not working with cmake

### ISSUE THREAD

**Issue by inglor** [mltframework/shotcut#1275]
Previously with `qmake` we would disable version checks when using a custom version (see #627) but with `cmake` this is not possible. Can you please advice on how to do this?

Cheers,
Leonidas

**Comment by ddennedy** [comment]
You need to `-DSHOTCUT_NOUPGRADE`. You can do that with the `CXXFLAGS` environment variable before running cmake the first time. CMake only reads environment variables on the first run within a build directory. Remove the build directory if you already ran cmake.
