### ISSUE TITLE
preview window not visible

### ISSUE THREAD

**Issue by mwilck** [mltframework/shotcut#1277]
It happens with shotcut 22.04.25. Environment is openSUSE Leap 15.3.

The preview window (more precisely, the media being previewed) is not displayed. Everything else seems to work fine. I suppose it's a permission / sandboxing problem. But I'm unsure what to look out for.

Already reported on [the Forum](https://forum.shotcut.org/t/preview-window-not-visible-in-22-04/33986/4), but it seems to be flatpak-specific (doesn't occur with the AppImage from flathub.org).

The following screenshot illustrates the issue: ![Screenshot from 2022-05-29 20-01-24](https://user-images.githubusercontent.com/15961354/170884810-d1da9405-da6f-40c9-8c52-2d510fb56e7c.png). You can see that the grid is displayed, but the video image (actually, a still photo in this case but that doesn't matter) is not.

I have enabled all available permissions in FlatSeal, but that didn't help. Running with `flatpak run --devel` didn't help, either. 

Hints for further debugging would be appreciated.

The only error I could see in the [Shotcut output](https://github.com/mltframework/shotcut/files/8793968/shotcut-debug.zip) is related to pulseaudio (but the pulseaudio socket is enabled; this was a log from a run with all permissions enabled).

**Comment by mwilck** [comment]
I've played around with older versions and found the same issue all the way down to flathub commit eef8db5cab7a. I am absolutely positive this used to work until recently. But with these findings, it looks more like a regression on the OS side, most likely some security "hardening". I'll continue investigating.

Forgot to mention: The openSUSE native package doesn't show this issue. But that's no surprise as the AppImage doesn't, either.

**Comment by mwilck** [comment]
It'd help if I had some slight idea what specific functionality (openGL?) is required for displaying the preview / player content.

**Comment by ddennedy** [comment]
It uses OpenGL for displaying the video but also many other parts of the UI including timeline, keyframes, filters, and video overlays like the player grid you are showing. 

From your log
> [Error  ] <MLT> [consumer sdl2_audio] Failed to initialize SDL: Audio target 'pulse' not available

That is a major problem and the cause of the issue. We do not hardcode or default "pulse" here. It comes from the SDL2 library as reported by its `SDL_GetError()` API. Do a web search on "SDL Audio target 'pulse' not available" and find related results like:

https://www.reddit.com/r/openSUSE/comments/pbcdmo/sdl_audio_audio_target_pulse_not_available/

https://forums.opensuse.org/showthread.php/558461-Kdenlive-crashing-sdl2_audio-Failed-to-initialize-SDL-Audio-target-pulse-not-available-quot

Apparently a common problem on openSUSE.

**Comment by ddennedy** [comment]
Please confirm the workaround to set environment variable `SDL_AUDIODRIVER=pulseaudio`

**Comment by mwilck** [comment]
Confirmed, thanks a lot. :+1: 

`SDL_AUDIODRIVER=pulse` used to be set on openSUSE by default because some old SDL 1.x required it (see [bug 1189778](https://bugzilla.suse.com/show_bug.cgi?id=1189778#c6)). It's removed in the latest version, but still set in 15.3. 

Given that this environment variable has been set in openSUSE for ages, it's strange that we never saw issues with the shotcut flatpak since very recently, and that the AppImage didn't exhibit the issue (it would see the same environment variable).

Anyway, thanks for the great support!
