### ISSUE TITLE
Video reading error in Linux

### ISSUE THREAD

**Issue by HPW-dev** [mltframework/shotcut#1279]
Hi, if i use this video in my linux (Linux 5.17.1-arch1-1 x64) i get crush:
Assertion ((src_linesize) >= 0 ? (src_linesize) : (-(src_linesize))) >= bytewidth failed at libavutil/imgutils.c:350
[video.zip](https://github.com/mltframework/shotcut/files/8805812/video.zip)

**Comment by ddennedy** [comment]
This was already fixed for the next version for which there is a beta:
https://github.com/mltframework/shotcut/releases/tag/v22.05.23
