### ISSUE TITLE
Text alignment with multiline text issues

### ISSUE THREAD

**Issue by CraftedCart** [mltframework/shotcut#128]
I added a text filter and gave it two lines. The text was centred in ShotCut, but when I exported to .mp4, the second line was on the left

Using Shotcut 15.10.06 on OS X 10.10.5﻿

**Comment by metellius** [comment]
I have experienced similar things before when rendering a preview with different aspect ratio thae the project settings. What resolution is the project set to? can you reproduce this if you create a blank project, add single videoclip, add text filter then render immediately with default settings?

**Comment by CraftedCart** [comment]
I used the same resolution. I also could reproduce with an empty project. (Well, one with a transparent colour clip attached)
![screen shot 2015-10-18 at 1 01 42 pm](https://cloud.githubusercontent.com/assets/5341220/10563973/91156694-7598-11e5-8391-00914d796f0f.png)
![screen shot 2015-10-18 at 1 01 25 pm](https://cloud.githubusercontent.com/assets/5341220/10563974/9133d368-7598-11e5-81cd-6f1a7f4419d1.png)

**Comment by ddennedy** [comment]
I have intermittently reproduced the problem, and I think it is related to multi-threaded rendering.
@CraftedCart and @metellius Please make this test to see if it removes the problem for you. In Encode > Other, add on a line by itself "real_time=-1" (that is a negative one).

**Comment by ddennedy** [comment]
When I do not add real_time=-1 and do not exactly reproduce the problem, usually the text flickers between left and center.

**Comment by CraftedCart** [comment]
@ddennedy Yup, adding `real_time=-1` worked

**Comment by ddennedy** [comment]
Fixed in MLT for next release. https://github.com/mltframework/mlt/commit/3797206319324e34b4211d7212b4089efa5c12dd
