### ISSUE TITLE
Export Markers as Chapters creates a empty file

### ISSUE THREAD

**Issue by abakum** [mltframework/shotcut#1281]
On Windows 10 portable Shotcut v22.04.25 export Markers as Chapters creates a empty file
On Windows 10 portable Shotcut v22.04.25 export EDL creates a not empty file
In log no records.
![2022-06-02_16-15-04](https://user-images.githubusercontent.com/18271863/171644571-4666368f-9109-4e47-9db6-51bdb959561b.png)
![2022-06-02_16-17-18](https://user-images.githubusercontent.com/18271863/171644580-34a9c57e-2d8e-46dc-b579-9fb15058afbb.png)
![2022-06-02_16-21-32](https://user-images.githubusercontent.com/18271863/171644585-22c6d59e-f8cf-46c1-b82a-c3391f7db22e.png)
![2022-06-02_16-23-03](https://user-images.githubusercontent.com/18271863/171644590-cdde3bf1-685b-40c1-b29f-260ff953f871.png)
![2022-06-02_16-22-17](https://user-images.githubusercontent.com/18271863/171644589-d39e2ff3-ae25-422a-ba83-20f1b3cd08ff.png)
![2022-06-02_16-25-13](https://user-images.githubusercontent.com/18271863/171644592-fa3fa2f1-b438-49a1-8e84-c46907c2b66e.png)
![2022-06-02_16-53-17](https://user-images.githubusercontent.com/18271863/171645261-e655a34a-cacf-4d83-8a3a-a8b5206b6160.png)

**Comment by abakum** [comment]
Source project and results for export Markers as Chapters and export EDL
[export-chapters.zip](https://github.com/mltframework/shotcut/files/8824597/export-chapters.zip)

**Comment by abakum** [comment]
![2022-06-02_17-06-50](https://user-images.githubusercontent.com/18271863/171648156-ebbc79cc-a0d0-4461-aa5e-641fd9105ce0.png)

**Comment by ddennedy** [comment]
It only exports markers with a duration of one frame by design (because the format does not support a duration).

**Comment by abakum** [comment]
![image](https://user-images.githubusercontent.com/18271863/171855368-1f1b348e-20c7-4202-9f0d-ce8cadfb92ee.png)
Thanks! It works great!
```
00:00 Marker 1
00:04 Marker 2

```

Is it possible to hope that in the future the program will not pay attention to property name="end" recognizing
```
    <properties name="shotcut:markers">
      <properties name="0">
        <property name="text">Marker 1</property>
        <property name="start">00:00:00.000</property>
        <property name="end">00:00:04.000</property>
        <property name="color">#008000</property>
      </properties>
      <properties name="1">
        <property name="text">Marker 2</property>
        <property name="start">00:00:04.000</property>
        <property name="end">00:00:08.000</property>
        <property name="color">#008000</property>
      </properties>
    </properties>
```
as 
```
    <properties name="shotcut:markers">
      <properties name="0">
        <property name="text">Marker 1</property>
        <property name="start">00:00:00.000</property>
        <property name="end">00:00:00.000</property>
        <property name="color">#008000</property>
      </properties>
      <properties name="1">
        <property name="text">Marker 2</property>
        <property name="start">00:00:04.000</property>
        <property name="end">00:00:04.000</property>
        <property name="color">#008000</property>
      </properties>
    </properties>
```
?

**Comment by ddennedy** [comment]
You are not the first person to report this confusion, and these are markers (we do not literally call them something else such as "Range" in the UI). So, it is reasonable to assume they will be exported, and one can easily edit the result to remove markers they do not want.

**Comment by abakum** [comment]
Thanks, I tested you patch locally it work well
![image](https://user-images.githubusercontent.com/18271863/171923991-757bc524-d37f-4bf8-bcf6-bb9155c53792.png)
![image](https://user-images.githubusercontent.com/18271863/171924197-25cf9f6f-d51c-44f2-b354-d48788c67831.png)
