### ISSUE TITLE
timeline context menu does not dismiss if clicking on other parts of the UI

### ISSUE THREAD

**Issue by Pomax** [mltframework/shotcut#1286]
This is on Windows 10 x64, Shotcut version 22.04.25:

When right-clicking on the playlist panel, which triggers a context menu, and then clicking anywhere else on the UI, the context menu gets dismissed. However, when right-clicking on the timeline (either background or a track), and then clicking elsewhere on the UI, the context menu stays open rather than getting dismissed.

**Comment by ddennedy** [comment]
This is a technology limitation with our usage of Qt Quick in some panels such as timeline. And this is why a Cancel menu item was added. There might be some workaround or fix, but I have not figured it out.

**Comment by Pomax** [comment]
I see, that sounds inconvenient. Hopefully someone knows how to send a global Qt signal to close any outstanding context menus and can help getting that put in.

**Comment by ddennedy** [comment]
This was fixed in version 22.09 when we added action search and editable keyboard shortcuts.
