### ISSUE TITLE
Every interaction becomes unbearably slow after creating a slideshow

### ISSUE THREAD

**Issue by glenneroo** [mltframework/shotcut#1287]
First time user. Just installed 22.04.25 on Win10 Pro with latest updates. AMD 3900X, 64GB RAM. 2080 Ti and 3060 Ti. 3 monitors, running full-screen on the middle 4K (# 3). CPU usage never goes above 10%.

Created a new project - added 61 images in 2048x1365 (77MB total) as a slideshow using this guide: https://forum.shotcut.org/t/slideshow-generator/19162

After doing this (and clicking on Firefox on another monitor), 2 out of 3 projects every actions (scrolling playlist, clicking on clip in timeline, etc - literally everything) becomes horribly slow. For the 1st project, dragged an mp3 into playlist from Explorer, then dragged it below the video layer which put it on top of the V1 video layer, so I hit Ctrl-Z to undo, and suddenly things started to get quite a bit slower... but getting to be unbearable (1-3 seconds per interaction). Created an audio channel, added audio clip again, checked out transitions, discovering UI a bit, clicked on Firefox to double-check I didn't mess up, clicked back into Shotcut and even slower (IIRC). Basically it feels like every subsequent action (especially context switching) takes between 3-20 seconds before anything happens. It's really hard to say if it's related to clicking on my browser or undoing or what exactly.

I tried creating multiple new projects with various slideshow values to see if that was somehow related. If I just manually add all the images w/o transitions, things seem to remain fairly quick, although definitely not as fast as the UI is in the tutorial videos.

I should also note that before even opening a project, just scrolling through menu options at the top with the mouse is rather sluggish in showing the menu items.

Restarting and re-opening project doesn't help, in fact opening the project takes about 15 seconds. Once a project is slow, it stays slow i.e. clicks take anywhere between 5-30 seconds before anything happens e.g. selecting 4 images > add to slideshow > 30 seconds before the slideshow generator dialog opens up.

Saving (ctrl+s) seems to always be pretty fast (< 2 seconds).

Attached log from the latest super-slowdown session after creating the 3rd project which became slow immediately after adding all images to a slideshow (clip duration=10, zoom=30, transition duration=4, dissolve).
[shotcut-log.txt](https://github.com/mltframework/shotcut/files/8875228/shotcut-log.txt)

p.s. I checked FAQ, searched forums, watched tutorials and couldn't find any mention of slowness.

**Comment by ddennedy** [comment]
Do you have grammerly installed?

**Comment by glenneroo** [comment]
Never heard of it :)
