### ISSUE TITLE
Server Deployment

### ISSUE THREAD

**Issue by sheafferusa** [mltframework/shotcut#129]
Can it be deployed on a remote server to be used as perhaps a web application?

**Comment by metellius** [comment]
The google plus community is a better place for this kind of questions: https://plus.google.com/communities/111984976401772983232

**Comment by sheafferusa** [comment]
hello @metellius 
Well, The reason I put it here is becoz I don't use Google Plus (and I am not the exception), moreover, there didn't seem to be any other choice except that, which was available from the official website or the github pages etc. and you know, as the query was regarding software deployment, I thought, the developers might be able to guide me better rather than some random dude on the internet who's used it once or twice if ever. anyways, whatever,  thank you for your suggestion.
**One more thing was, Since the question's already been asked,   would you (or anyone else here) mind helping me out on the issue?**

**Comment by ddennedy** [comment]
Yes. See MLT and its companion utility melt on http://www.mltframework.org
Shotcut comes with a melt utility. This tracker is for defect tracking only related to Shotcut. Questions about MLT are done through StackExchange.
