### ISSUE TITLE
Glaxnimate not launching when clicked edit(even if i set the correct location) 

### ISSUE THREAD

**Issue by Technosteve942** [mltframework/shotcut#1292]

**Comment by ddennedy** [comment]
Not enough information

**Comment by ddennedy** [comment]
My guess is that you are not using a build we made, and your version of glaxnimate is too old. This only works with a git master branch version of glaxnimate or wait for its next release.

**Comment by Technosteve942** [comment]
sorry for being late

https://user-images.githubusercontent.com/69840732/179551536-b0027581-260b-4577-9dc9-5b4fec95268c.mp4
