### ISSUE TITLE
Segfault with Timeframe

### ISSUE THREAD

**Issue by Pran-Ker** [mltframework/shotcut#1297]
**Describe the bug**
Segmentation fault (core dumped) which crashes the whole application with all progress made. When the Timeframe window is closed and reopened. The reopened timeframe window does not work and shows a black screen, if re positioned the entire Shotcut application crashes.

**To Reproduce**
My machine's OS is Pop.OS with KDE.
1. Open shotcut (through the terminal).
2. Close the timeframe with the button X.
3. Reopen timeframe using 'Crtl + 5' or using the menu.
4. Opens black timeframe screen which does not respond.
5.  Move the timeframe window to the bottom of the screen, where it auto reposition. The application will crash. 
6. If the application is reopened from the terminal and the timeframe is still missing. Attempting to reopen cause the problem to repeat.

**Additional context**
I removed lock files and cleaning my cache. This helps as the timeframe is back. But if the issue still persists.

**Screenshots**
![alt text](https://i.imgur.com/dh5Hp3u.png)

**Log messages**
"....
  - vp8_v4l2m2m
  - vp8_vaapi
  - vp9_vaapi
...
Segmentation fault (core dumped)
"

```

**Comment by bmatherly** [comment]
Please report your Shotcut version and where you downloaded it from.

If you have not already, please try the Linux portable build from here: https://shotcut.org/download/

Possibly related to these two reports:
https://forum.shotcut.org/t/timeline/16573/
https://forum.shotcut.org/t/filters-not-showing/10161

Try changing Settings > Display Method

**Comment by Pran-Ker** [comment]
Shotcut 22.06.23
Installed via 'apt'.

Yes, I think it is related to the reports mentioned. Only difference is when the timeframe window is realigned the entire thing crashes.

Issue persists in both display types, OpenGL and software(Mesa).

**Comment by bmatherly** [comment]
> Shotcut 22.06.23
> Installed via 'apt'.

Please try the portable package from the download page and report back. This will help narrow the problem.
https://shotcut.org/download/

**Comment by Pran-Ker** [comment]
Installed it from the .tar file, and the issue still persists. The same thing happens.
Tried purging and reinstalling, shotcut works perfectly, but the issue can be recreated.

**Comment by bmatherly** [comment]
I notice the Timeline dock is floating (undocked) in your screenshot. Are you able to drag it to re-dock it? If that crashes, try clicking on the "FX" layout by clicking "FX" in the upper right. I wonder if the problem only occurs when the timeline is undocked.

**Comment by Pran-Ker** [comment]
Dragging to re-dock will cause it crash.
Yes it works, "FX" layout button re-docks the timeline. And then works like perfectly.

**Comment by bmatherly** [comment]
> Dragging to re-dock will cause it crash.

You can restore the default (docked) layout by deleting the Shotcut.conf file. It will  be recreated when you start Shotcut with default settings.

On my Ubuntu system, the file is in /home/user/.config/Meltytech/Shotcut.conf

We have seen a couple of reports from people that the timeline does not work when undocked on their system. Unfortunately, we do not experience this problem on any of our develpment systems. We believe it is a combination of video card or graphics driver. But we can not debug it without reproducing the problem on our development system.

The work-around is to always leave the timeline docked.

If you want to find a better work-around, you could try a different graphics card, or try changing/upgrading your graphics driver on your system. If you find a way to make it work, we would be interested to know the solution.
