### ISSUE TITLE
Pixel values no longer adjustable with arrow keys

### ISSUE THREAD

**Issue by John-Johns0n** [mltframework/shotcut#1300]
Hello, I've been using Shotcut for a while, and up until today I was using an older version (not sure which one unfortunately)
Today I ran the update (so I'm on 22.06.23, Windows 10), and not much seems to have changed so far, except for one detail:
When using the `Crop: Source` filter, I used to be able to adjust pixel values one pixel at a time by highlighting them and pressing the up/down arrow keys. However, this no longer works. Is there any reason why the feature was removed?
I assume this counts as an issue, but if it does not, please redirect me to the proper place.
![crop](https://user-images.githubusercontent.com/84598043/178580604-61d9d6e9-e697-4ffb-9c72-5e314b6922c5.png)
Before you ask, the issue persists after rebooting my computer and re-installing Shotcut.

**Comment by John-Johns0n** [comment]
I have just tried it by "disconnecting" the `Filters` window from the main one, and oddly enough, the feature still works when in this windowed mode, but it stops working again when I merge it back into the main Shotcut window.

**Comment by bmatherly** [comment]
This is a change that occurred a while back when we updated our underlying GUI framework (QT). I guess you can call it an issue, but we do not try to fix/change the QT framework. I hope that you can adjust to a workaround and use the mouse scroll wheel to increment/decrement the fields by one.

**Comment by John-Johns0n** [comment]
Thank you for your reply. I actually had no idea you could use the scroll wheel as well, so that's definitely good to know. Given the nature of the problem I'll go ahead and close this issue

**Comment by andrewk8** [comment]
FYI, using the keyboard to adjust filter parameters was working through 22.04.25 Windows x64.  The issue can be narrowed down to a change in 22.06.23

**Comment by ddennedy** [comment]
git bisect reveals the commit that broke this is a0c1d8942a6f6356f8bc14751e9e9cb3949ba9fc
