### ISSUE TITLE
Portable version saves settings on the local system

### ISSUE THREAD

**Issue by AdKiller** [mltframework/shotcut#1304]
I used portable Shotcut on Windows 10 a while ago, and deleted the folder. Later I downloaded the portable version again and was surprised to see that my recent project names where still there.

**Comment by ddennedy** [comment]
There is no specification or standard for "portable." For us, it simply means you can extract the archive to any location and run it, and move the program folder to a different location and run it. The portable build is the exact same build as the installer and MS Store app. If you want to change the location of the app data, you need to use Settings > App Data Directory > Set... or a [command line option](https://shotcut.org/notes/command-line-options/).
