### ISSUE TITLE
Does not open Shotcut on Debian-11.4.0-i386

### ISSUE THREAD

**Issue by X-DE1** [mltframework/shotcut#1305]
Does not open shotcut-linux-x86_64-220623.AppImage on debian-11.4.0-i386-DVD-1.iso
this was where i downloaded a version of debian https://www.debian.org/CD/http-ftp/#stable

**Comment by ddennedy** [comment]
It runs on Intel/AMD 64-bit only.

**Comment by X-DE1** [comment]
Intel

**Comment by ddennedy** [comment]
And you’re Debian ISO is 32-bit not 64

**Comment by X-DE1** [comment]
Ok ty

**Comment by X-DE1** [comment]
I opened shotcut-linux-x86_64-220623.AppImage in debian-live-11.4.0-amd64-lxde.iso with an intel 32 bit processor and it worked.
I think it works on 32 bit processors but with 64 bit operating systems.
