### ISSUE TITLE
Chromakey leavers border around image and fuzzes around objects even when there is no closeness in color between color being chroma keyed out and the other elements

### ISSUE THREAD

**Issue by Klawdek** [mltframework/shotcut#1307]
Shotcut 22.06.23
Windows 10 OS Build: 19043.1826

I made some scrolling text in Windows Movie Maker. (nothing else does scrolling text like WMM) It had yellow text with a black border on a solid white background. The background image was made in gimp and is solid white. So this should have been a real simple chroma key operation given the background has every pixel the EXACT same color and that color is not even close to any other color in the image.
First I did the chroma key and all I did was select the color from the screen. That results in a white border on the image. (see screenshots)
Then I tried setting the distance to 50% that is as far as I could go without messing up the scrolling text too much.
This results in a fainter white border and the text being degraded a bit.

Here is a screenshot of just using color picker to pick the white background and everything else at defaults.  The white border is more noticeable if you full screen the screenshot and is very noticeable in the video.
![Screenshot (15789)](https://user-images.githubusercontent.com/45950944/180888167-a52d2c1d-1cbc-4c55-947a-a0a1a8ee0cd0.png)

Here is a shot of what it looks like when I set distance to 50% the white border is fainter yet the text is now degraded.
![Screenshot (15790)](https://user-images.githubusercontent.com/45950944/180888476-837b7585-dd69-4a3d-8d7b-6f163f249227.png)

I really would have thought that this would be the easiest chroma key ever.  The background is pure white every single pixel the same exact color no variation at all.  The text is yellow with a black border.  The contrast between black and white is as far as is possible.

I therefore was expecting it to work right off the bat with just the selection of color to key out.

**Comment by ddennedy** [comment]
Which chroma key filter?! There are 2. Please also attach a sample image.

**Comment by Klawdek** [comment]
Sorry about that. I am using Chroma Key Simple
![Screenshot (15791)](https://user-images.githubusercontent.com/45950944/180896559-e5d481d0-3106-4b7f-84d5-6cc2e1126a74.png)

**Comment by ddennedy** [comment]
Can you please extract and save a frame of `Frequency_Scroll.mp4` that contains a fair amount of text? I want to work with the same image as you. I just made a quick test using a Text: Simple filter on a white color clip in Shotcut and Chroma Key: Simple on that, and it seems OK:
![image](https://user-images.githubusercontent.com/1146683/180898578-89998c2b-c1b0-4e70-89a7-0564ecd19eeb.png)

No white border.

![image](https://user-images.githubusercontent.com/1146683/180898677-bc064330-d5f2-4f32-bf4f-ee0043efed83.png)

Not too bad fuzzing, but I suspect the anti-aliasing in your source is a part of the problem. I highly doubt I can improve it, but let me know if you want to work on the code yourself, and I will show you where it is. You really should improve your process by using alpha channels and avoiding chroma key. Or better, learn Shotcut's text and keyframes features.

**Comment by Klawdek** [comment]
Here is a shot from Frequency_Scroll.mp4:
![vlcsnap-2022-07-25-20h26m38s258](https://user-images.githubusercontent.com/45950944/180902931-83707663-a24d-4ae4-90af-ab1b60d4da43.png)
If you are talking about making the video clip with a transparent background.  That is the first thing I tried.  I made a transparent image in GIMP dropped it into WMM and it did not make a video with a transparent background. The background ends up being black. There are no settings for such in WMM.

Using Shotcuts text features is not an option.  With WMM I can paste my text into a text box.  Click on one thing to set it as scrolling text.  Click on one thing to select the outline size and another thing to select outline color.  I can select text color and then duration of text captions sets how fast it scrolls.  It can be done in seconds.
There is no other product anywhere that can do that as easy and simple.  With every other video editor you have to jump through a lot of hoops and no outline feature for text.
The outline feature is important for me as I often have text over fractal art with many colors in it.  It can be impossible sometimes to find a text color that does not blend into some part of the image.  The outline feature that only WMM has, takes care of that problem. 
Thank you for helping out.  I hope there is a way to get this to work.

**Comment by ddennedy** [comment]
The bad border comes from your image. Taking a look at in Shotcut's Video Zoom scope:

![image](https://user-images.githubusercontent.com/1146683/180905716-1ded1e8c-bbaa-458f-b21a-1d3c9310191e.png)

The antialiasing of the text with the background in your image is causing the fuzzing around the text:

![image](https://user-images.githubusercontent.com/1146683/180905839-116165b9-ea6d-405e-b97f-889a40fb1b52.png)

I will not be able to make this work better for you.

**Comment by Klawdek** [comment]
OK thank you for showing me what the problem is.  I guess I will just make the clip in WMM complete with the background image.  I thought this would be a good thing to do to learn chroma key and it would be more versatile this way.

**Comment by Klawdek** [comment]
This may have been closed a bit quick.  We forgot to address the issue of the white border.  I don't think that was from the antialiasing.

**Comment by ddennedy** [comment]
It was addressed. Re-read my last reply.

**Comment by ddennedy** [comment]
Try using Crop: Rectangle before the Chroma Key filter to address the border, and then maybe you can tune the Distance to give the best text result. Maybe also a Key Spill filter can help with the light gray edges of the text.
