### ISSUE TITLE
.tga files failed to import on latest version

### ISSUE THREAD

**Issue by Morphlng** [mltframework/shotcut#1308]
## Description

Imported .tga file appears to be all white in the latest version of Shotcut (after further testing, all version after 20.10 have this bug).

## Pictures

This is how it looks like in the latest version:

<img width="640" alt="shotcut_2206" src="https://user-images.githubusercontent.com/50166287/181864158-67e05b13-42ec-4fa5-b005-843d6821e943.png">

And this is how it should work in 20.09 version

<img width="640" alt="shotcut_2009" src="https://user-images.githubusercontent.com/50166287/181864181-9cb0dc75-b241-4d41-a0aa-144467ed0d90.png">

## Platform

Windows 11 21H2

**Comment by bmatherly** [comment]
Observations:

- Shotcut tries to open .tga files with avformat after QImage producer fails
- QImage producer fails to open .tga file in the ImageReader.read() call with error: Error 4 "Unable to read image data" - "The image data was invalid, and [QImageReader](https://doc.qt.io/qt-6/qimagereader.html) was unable to read an image from it. The can happen if the image file is damaged."
- qtga.dll is present in Windows builds. libqtga.so is present in Linux builds

**Comment by ddennedy** [comment]
I had already made the same observations. But also reports that Qt does not support RLE compression. I tried with and without and both fail. I don’t know why the Qt plug-in is failing. I suspect previous build that worked included the MLT gtk/gdk module, which is also an image reader. That is no longer included to save space and simplify dependencies. I think the fact no one else reported this for nearly two years indicates the priority.

**Comment by bmatherly** [comment]
In my testing, the content based detection was not detecting TGA files at all (did not even try to load the TGA plugin).

This change improves the detection: https://github.com/mltframework/mlt/commit/520acf93c4225eaae62d2f2bfd1b7ac7ba8d4f09
With that change, I am able to load some of my tga files. Other tga files fail with a "not supported" message from the  TGA plugin.

**Comment by Morphlng** [comment]
> But also reports that Qt does not support RLE compression.

> the content based detection was not detecting TGA files at all

I've tried myself with Qt 5.15.2, and found that:
1. `QImageReader` could support tga files and could auto detect it with `setDecideFormatFromContent(true)`.
2. `QImageReader` does not support RLE compressed tga image.

While I could use QImageReader to load some tga files ([earth.tga](https://people.math.sc.edu/Burkardt/data/tga/earth.tga) for example), most of them doesn't work. I've found a discussion on Qt Forum, and their solution works fine for all my images. You could check it with [Qimage from tga with Alpha](https://forum.qt.io/topic/74712/qimage-from-tga-with-alpha/11)

As for Shotcut, I'll stick with 20.09 for the moment.

**Comment by ddennedy** [comment]
I do not like the idea of making it work occasionally, and adding a completely custom targa image reader is out of scope for a bug. This is effectively a feature request, and I don’t accept feature requests with a pull request.
