### ISSUE TITLE
Transition leftovers

### ISSUE THREAD

**Issue by Lex-DRL** [mltframework/shotcut#1324]
Steps to reproduce:

- Overlap two clips to create transition
- Move one clip away to split them apart
- The transition will stay on another clip, not linked to the first clip in any way and yet fading to/from it.

Shotcut **v22.06.23** portable, Windows 10 21H2 19044.1889

**Comment by ddennedy** [comment]
This is a feature I actually utilize. Delete the transition if you don’t want it anymore.
