### ISSUE TITLE
Shotcut crashes with Windows XP

### ISSUE THREAD

**Issue by Petrouchka** [mltframework/shotcut#133]
All versions of Shotcut newer than 15.04.01 version are crashing at start, with Windows XP Pro SP3 french version. Only shotcut-win32-150401.exe is starting without crashing.

**Comment by ddennedy** [comment]
Windows XP is not supported.

**Comment by Petrouchka** [comment]
![capture](https://cloud.githubusercontent.com/assets/3955499/10766026/d0e597a0-7cd5-11e5-925b-b1dd2d2bf346.png)

**Comment by Petrouchka** [comment]
I will propose version 15.04.01 in my next compilation : http://www.numopen.fr/compilibre-en
