### ISSUE TITLE
Using hevc_vaapi and the result is a broken video

### ISSUE THREAD

**Issue by babam86** [mltframework/shotcut#1332]
Shotcut version: shotcut-linux-x86_64-220901.txz
Distro: Slackware 15.0
Intel i5-1135G7, Iris Xe Graphics, intel-media-driver (iHD)

Hardware acceleration is work

Using hevc_vaapi and the result is a broken video
![Screenshot_2022-09-03_21-48-07](https://user-images.githubusercontent.com/7625165/188280344-ebbc076f-b99b-49a3-9bda-f61087fe34e9.png)

How to reproduce it:
Use Intel 12th Gen Graphics with `intel-media-driver` https://github.com/intel/media-driver
Export with `hevc_vaapi` codec

Notes:
`h264_vaapi` works great
`vp9_vaapi` works great

Thanks.

**Comment by ddennedy** [comment]
Does a previous version work? It with VAAPI works on my AMD system on Ubuntu 20.04. VAAPI is always a big gamble with a portable binary on {insert name of your distro} due to version alignment issues through multiple layers.

**Comment by babam86** [comment]
The previous version also doesn't work.

h264_vaapi always works fine

**Comment by babam86** [comment]
Even to the latest version of Shotcut the problem is still there.

How to reproduce it:
Use Intel graphics Gen 12 with `intel-media-driver`
Export with `hevc_vaapi` codec

**Comment by ddennedy** [comment]
I do not think this is in our control and comes from the lower levels of VA-API and driver. Retest on latest Flatpak to get best VA-API environment outside of distro packages.
