### ISSUE TITLE
Ubuntu - shotcut don't work

### ISSUE THREAD

**Issue by myswiat** [mltframework/shotcut#134]
The point is simple: Ubuntu (at the moment) based on qt5.4. Debian based on 5.5.
Only to info you that on Ubuntu until the Canonical will update qt to 5.5 shotcut not start.

[Fatal  ] <> Cannot mix incompatible Qt library (version 0x50402) with this library (version 0x50500)
Aborted (core dumped)

:)

**Comment by ddennedy** [comment]
What is the Shotcut version, where did you get it, and how did you start it? Shotcut does not use your system Qt libraries; it supplies its own. Except, version 15.11.01 was shipped with a missing library, and that is being fixed now.

**Comment by metellius** [comment]
I'm also getting this. kubuntu 15.10 here

**Comment by myswiat** [comment]
v: 15.11.01

No problem :) I downloaded an earlier version and look forward to working version.
:)

**Comment by ddennedy** [comment]
I did a quick test of this new release candidate. It would be great if someone else can check it:
http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-debian7-x86_64-151102.tar.bz2

**Comment by metellius** [comment]
works!

**Comment by ddennedy** [comment]
new version uploaded and link changed on download page.

**Comment by myswiat** [comment]
Works :)
