### ISSUE TITLE
Shotcut editor exported mp4 Problem

### ISSUE THREAD

**Issue by Shehan52** [mltframework/shotcut#1341]
Exported video file doesn't play, but I don't understand why the file size is too small, Size must be at least 20 MB. please guide me to fix this problem. This isn't my first time with Shotcut. I have been using it for years but yesterday I reinstalled the new version after that the problem began.

OS Windows 11; Installed physical ram 8GB

![Screenshot 2022-09-23 075652](https://user-images.githubusercontent.com/114202718/191881697-4bcdb68a-63d9-4a88-9300-898e893eb1d4.png)
![Screenshot (76)](https://user-images.githubusercontent.com/114202718/191881731-33760b76-bd69-4d57-9a8e-a84ae8702bdb.png)

**Comment by ddennedy** [comment]
You did not state the version.
The file size is 0. You need to check it after it is done.
It works for me. Unable to reproduce. I don’t know what the problem is. You should reboot, uninstall, and reinstall.

**Comment by Shehan52** [comment]
Shotcut version - 22.06.23

**Comment by ddennedy** [comment]
I do basic testing of the build before release specifically especially around export. Hundreds of thousands of people have downloaded this version and not reported this problem.

Is this problem specific to this one project? Make a simple test. This is not a support channel. There is a lot of export troubleshooting info in the forum that you should search and read.
