### ISSUE TITLE
[22.09.23] VP9 default settings are too high

### ISSUE THREAD

**Issue by gutko** [mltframework/shotcut#1342]
When selecting VP9 as export format in export menu, the default settings are too high. Now its crf=4, in previous version it was 23 or even 28 i think. Not sure about other settings like gop and bframes

![Screenshot 2022-09-25 162321](https://user-images.githubusercontent.com/1101181/192148789-ef467092-8891-4f92-86cd-d5af40fd3cd4.jpg)
win10 21h2 up to date

**Comment by ddennedy** [comment]
Thanks, the default is supposed to be average 2 Mbps - the same as VP8, but there is something slightly different in the order of the lines in the presets that triggered this regression bug on VP9 but not VP8 in this version. The problem also affected the D10 and XDCAM presets.
