### ISSUE TITLE
Video layer order conflict with picture if multiple video is showned at the same time

### ISSUE THREAD

**Issue by ss1h2a3tw** [mltframework/shotcut#1346]
## Environment
Windows 11 21H2 22000.978
Shotcut 22.06.23

## Sympton
When two videos playing at same time (one covering another). Another video track with only picture in front of those two track will also be affected. This not only affect the preview but also the rendered output.

## Step to reproduce
1. Create Video Track 1
2. Add video to Video Track 1
3. Create Video Track 2
4. Add picture to Video Track 2
5. Create Video Track 3
6. Move Video Track 3 under Video Track 2
7. Add Video to the current Video Track 2

https://user-images.githubusercontent.com/5120934/193402820-42c42ee9-d25d-40c6-bd32-c5fe1660c710.mp4

**Comment by ddennedy** [comment]
This was already fixed in the most recent version 22.09
