### ISSUE TITLE
Help - Suggest 

### ISSUE THREAD

**Issue by Joh45456464** [mltframework/shotcut#1348]
I love your program and have been following it for a while, but I am not a professional

And I hope that the program (and other free and open source programs) will also be the easiest and most used, and this requires ease for all users, especially non-professionals (because professionals can buy the program they want)

Therefore, I hope and suggest (the ease, simplicity and flexibility of the program)

suggested:

1- Add selection with the mouse to an area that I want to cut easily Example:

https://user-images.githubusercontent.com/108882090/193619589-18309855-b639-4601-9b5b-849979073a80.mp4

https://user-images.githubusercontent.com/108882090/193619597-de87c7c5-4593-40f4-95db-dfa862768d24.mp4

2- CAN CUSTOMIZE  GUI TO SIMPLE:
Add features flexibly   **"Especially if you have more than 2000 small videos"** like (Some videos need simple editing such as crop / speed / moving one place to another

Therefore (for example) I want to show in my interface (these additions only) possible to do a checkbox next to (crop) or any way to add the tool to the interface only.  

3- Adding multiple parts to the edit “especially if you want to produce and divide this amount of videos.... for example, I will find (personal / sports / funny / dramatic / educational parts (and their words are embedded in other videos and so on)).”
**LIKE VIDEOpad video 2 Multi sequence and can rename   and cut from any sequence  and past in any other **

    3- 1-   any sequence has a specific folder and save in (bookmark folders)  like   (if sequence = sports    SO  sport time line            export in "like" c:.......\sports\   .

**Comment by bmatherly** [comment]
Thanks for sharing your comments. Unfortunately, this is only a defect tracker and there is nobody here to discuss your suggestions with you. I suggest you post your suggestions in the Shotcut [forum ](https://forum.shotcut.org/)in the [Suggestion](https://forum.shotcut.org/c/suggestion/7) category. I think there are many people there who would be interested in your ideas.
