### ISSUE TITLE
Export Bug?

### ISSUE THREAD

**Issue by GhostPumpkin1** [mltframework/shotcut#1350]
Exported video output freezes on a video frame around 30 minute mark with the remaining audio continuing as normal until end of clip, however the video frame does not change.
On a 58m24s video, this happens at 35m exactly 

Tried with a few different default preset settings with same results at exactly same time stamp.

Have gone back to my previous version (190615) and exactly the same settings work with no issues. Have not had chance to check back every version in between to isolate where issue started as there are too many!!

Have also tried with a different video source file (also around an hour original length) and same thing happens, albeit at a slightly earlier time of just after 31 minutes.

Exporting from timeline, using hardware encoder and a custom preset with following settings:
VIDEO
1280 x 720
Aspect 16:9
25 Fps
Broadcast Ltd
Scan: Progresive
YADIF - Temporal + Spatial (best)
Interpolation: (good)

CODEC
h264-qsv
Average bitrate
1Mb/s
GOP 125 frames
B frames = 2
Codec threads = 0

AUDIO
2 channel stereo
sample 44.1kHz
mp2
average bitrate
128k b/s

Shotcut Version: 22.09.23
Sytem: Intel i7-7500 2.7GHz 8gb
OS: Windows home 10 version 21H2

**Comment by bmatherly** [comment]
Can you provide the properties of your source clip? Screenshot of the properties panel would be great.

Also, can you try to export using lix264 instead of qsv to see if the hardware encoder is causing the problem?

**Comment by ddennedy** [comment]
I was not able to reproduce this. I used a 1 hour 5 min 1080p24 clip with similar rate control and GOP settings. GPU memory usage remained flat at 0.4 GB the whole time.
My CPU is Intel(R) Core(TM) i7-8559U so 8th generation whereas 13th just came out. Same version of Shotcut and Windows.

**Comment by ddennedy** [comment]
I also just successfully tested same 1+ hour 1920x1080p24 project exported as 1280x720p25 1 Mbps. Plays back fine to the end. Maybe you are running low on memory. Maybe the newer version uses more memory. Export > Video > Parallel processing requires more memory if you want to try turning that off.

**Comment by GhostPumpkin1** [comment]
Hi 

Thanks for looking into this. 

I have tried everything suggested and still same issue in all cases, but I do have some more info that might help.

- Parallel processing has never been used in any tests, so that's not the issue

- Conversions have been tried with and without hardware encode selected and also with differing codec as suggested, same issue persists in all cases

- I have watched my task manager during export and overall system memory never goes above 45%, Disk never above 12%, overall CPU is around 80%. 

**Crucially CPU changes at around 60% conversion and drops to nothing. 60% of source clip time correlates exactly to the 35 minute mark where the video conversion in the output file freezes**

I have attached images of all of the settings and the source clip properties and maybe this will help replicate

If you need anything else, let me know. As mentioned, I have what I need by rolling back the version, but this issue really puzzles me, so I am happy to help where I can!


![Export settings 2](https://user-images.githubusercontent.com/115377393/194756766-4abe3563-f81f-4316-9d2a-b1e871cb9c47.png)
![Export settings 3](https://user-images.githubusercontent.com/115377393/194756767-0ba0dbd7-51fd-4651-a734-fb018bf03d48.png)
![Export settings](https://user-images.githubusercontent.com/115377393/194756768-0365bccf-9941-481b-93bf-5294eb861eb5.png)
![Source Audio Properties](https://user-images.githubusercontent.com/115377393/194756770-b8e0e5e4-e7d6-4bef-ab8b-0407b61a0ac9.png)
![Source Video Properties](https://user-images.githubusercontent.com/115377393/194756771-bca2c753-3e6d-4fa6-8750-1105164e8212.png)

**Comment by bmatherly** [comment]
Nothing jumps out at m in those pictures.

Some other ideas/comments:
Do you have any filters or transitions at the 35 minute mark that you could try to disable?
Can you attach the export log (right click on the job after it completes)?
Would you be willing to PM your entire project with a developer so we can try to reproduce the problem in our environment?
