### ISSUE TITLE
Apple ARM Beta 22-10 - File is Damaged, Cannot Be Opened, Move to Trash.

### ISSUE THREAD

**Issue by cruudesign** [mltframework/shotcut#1356]
Apple said the App is Damaged and can't be opened.  OS suggested I move it to the trash.  I'll try again, report back.

Monterey 12.6
Shotcut Beta 22-10 ARM
M1 14" MBP, 16GB RAM

**Comment by ddennedy** [comment]
Does the release version work for you?

**Comment by cruudesign** [comment]
I've had issues since moving to the M1.  Any time I touch Timeline or Keyframes windows, the app crashes.  I've sent reports to Apple since 21-06-23.  21-09-23 crashes immediately upon the same, touch Timeline or Keyframes windows.  Existing projects might be the issue?  I moved from my 2015 MBP to the new M1.  I just created a new project and can't get it to repeat.  Digging back in.

**Comment by cruudesign** [comment]
Repeated.  Re-downloaded.  Changed file name to ...-Beta-22-10, open, popup says file damaged, move to trash. Thanks.  I'll watch for an update.  LMK if it keeps the same version and is re-uploaded.

**Comment by ddennedy** [comment]
I reproduced it and just uploaded a resigned build. I think I missed a manual step. I verified the new upload. I do not reproduce your crash issues.
