### ISSUE TITLE
Apple ARM M1 22-06-23, 22-09-23 Crashes when touching Timeline or Keyframes window.. sometimes?

### ISSUE THREAD

**Issue by cruudesign** [mltframework/shotcut#1357]
I've had issues since moving to the M1. I've produced a few videos successfully. Many times when I touch Timeline or Keyframes windows, the app crashes.  I've sent reports to Apple since 21-06-23.  21-09-23 crashed immediately upon the same, touch Timeline or Keyframes windows.  I just re-opened the trouble file and it seems stable now.  Just moving the Keyframes or Timeline windows would cause the crash, as well as X close window button.  Continuing to test today.  This video is long overdue, had to move on in life.  Thanks for the continued development.

**Comment by ddennedy** [comment]
I do not reproduce it. Sending crash reports to Apple is useless unless it is a problem they identify in their code.

**Comment by cruudesign** [comment]
Copy that, I'd be glad to produce system reports for the issue.  It has happened tens of times.  The video was also incredibly glitchy like the ol 2015 MBP with dedicated graphics card.  I was crushed, this being an M1.  The video now plays smooth on the 22-10 BETA. (In the future, can I get a chance to test before the issue is closed / close the issue myself once tested?)
I likely have system reports on here from all the crashes.  I am good now it seems, I'll continue on BETA and keep u posted.  Thanks for everything u do.  (your website linked in bio didn't load, Safari, maybe has DuckDuckGo plugin, no NoScript here).  Also no SSL on your (lastname).org site.  You can reach me at (user) at gmail if you want.  Appreciate.

**Comment by cruudesign** [comment]
Dan, I have repeated crashes in one of my projects when trying to keyframe the text box.  Now any attempt to re-open Keyframes window crashes Shotcut.  I've repeated it over and over, restarted, and the same immediate crash is happening.  Thanks for the dedicatoin.  Clint
(aside, https://github.com/mltframework/shotcut has your website listed mid-page as your contact info still.)

**Comment by ddennedy** [comment]
Still unable to reproduce. Is your Keyframes window floating/not docked into the main window? If so, does it make a difference if you re-dock it? 
I don't care about my website and contact. I don't want people to contact me.

**Comment by cruudesign** [comment]
Keyframes was undocked, think I did so today successfully.  When I closed the undocked Keyframes window it began to act up. Unsure if it began when I clicked the Keyframes icon in Rich Text, but both cause the crash. I am exporting the file now with audio added, just stopped trying to mess with it.  I could take a video of the crashing and post it on YT in a bit if that helps.  System report? Let me know what you need to diagnose.  Thanks.

**Comment by cruudesign** [comment]
I still have the same issue.  I was able to open the Keyframes undocked window today in a new project, but as soon as I grabbed the top bar to move the window it crashed the program.

**Comment by ddennedy** [comment]
Find another way to redock the panel. Double click its title bar or reset the layout in the View menu.

**Comment by cruudesign** [comment]
I just installed the latest 22-10-25 build and the Keyframes window seems stable.  No glitches so far.  Stabilizer seems to have done a good job with a shaky video.  Thanks for the incredible work!
