### ISSUE TITLE
Bug : the software crashes as soon as there is a rich text

### ISSUE THREAD

**Issue by davi-domo** [mltframework/shotcut#1358]
As soon as I use rich text the software stops responding
On version 22.09.23 I had noticed it on the previous version but it was less marked just a lag but since the update, almost impossible to use rich text
CPU: i7-8700
GPU: Intel® UHD 630
ram: 32 GB

**Comment by bmatherly** [comment]
I do not reproduce this. Can you give specific steps to reproduce? Also, what operating system are you on?

**Comment by ddennedy** [comment]
What does "47 / 5 000" mean?

I have not experienced this either, and I tested it across all supported operating systems on multiple machines.

**Comment by davi-domo** [comment]
hello
I will try to reproduce it and take screenshots
for 47/5000 error on my part when copying and pasting the translator🤭

**Comment by davi-domo** [comment]
Hello,

Sorry I was overwhelmed at work I didn't have time to watch instead

The problem is solved I finally uninstalled then installed and everything came back in order

**Comment by davi-domo** [comment]
Hello
I found how the bug occurs
It appears when I’m in double screen with the windows detached

**Comment by davi-domo** [comment]
Hello
I found how the bug occurs
It appears when I’m in double screen with the windows detached

**Comment by ddennedy** [comment]
Closing as expired since this is related to the GUI library Qt, which was updated to a major new version 6 in Shotcut 23.05. Reopen if reproduced in latest version.
