### ISSUE TITLE
Crash on trying to delete

### ISSUE THREAD

**Issue by Charleswj39** [mltframework/shotcut#136]
Using 15.11 on a Mac running 10.10.5. I mark up a section of a file to Ripple Delete and press X on my keyboard - no result. I click on the '-' in the Timeline and Shotcut crashes. This is reproducible and an image of the first part of a typical crash report is attached.
![shotcut crash1](https://cloud.githubusercontent.com/assets/15653920/10943244/e50a8f8a-8313-11e5-8281-b4b4ac056aab.jpg)

**Comment by ddennedy** [comment]
I reproduced it, but I can also tell you that Shotcut does not work that way. There is no function to select part of a clip and remove that part. You can only select part of a clip and add it to the timeline (or playlist).    Buttons on the timeline toolbar only affect the timeline. The '-' button removes the a selected clip on the timline, but you had an empty timeline.
