### ISSUE TITLE
fftw3配置失败

### ISSUE THREAD

**Issue by leijiuhu** [mltframework/shotcut#1360]
按照这个方法https://shotcut.org/notes/windowsdev/
编译，使用该页面提供的SDK，编译失败。
run cmake成功了。但是运行就会出现图片中那些错误：
undefined reference to `__imp_fftw_free'。
请问应该怎么解决这个问题，有人帮帮我吗。
![5372bcf51fb5e59fa0742d90003ee4f](https://user-images.githubusercontent.com/97873285/197169606-47025425-7fdd-45fb-a47b-25db03a7b785.png)

**Comment by ddennedy** [comment]
You need to install fftw from msys2. You need to figure out how to build yourself. The SDK is simply an aid and not a product for support.

**Comment by leijiuhu** [comment]
谢谢你的帮助我编译成功了。
我想知道怎么通过SDK和源码编译的工程有什么区别。
还有，我在github以及readme中并没有找到编译源码的详细步骤

**Comment by leijiuhu** [comment]
谢谢你的帮助我编译成功了。
我想知道通过SDK和源码编译的工程有什么区别。
还有，我在github以及readme中并没有找到编译源码的详细步骤
