### ISSUE TITLE
Shotcut crashes Cmd-N while playing video in 22-10-25 on M1 Monterey 12.6

### ISSUE THREAD

**Issue by cruudesign** [mltframework/shotcut#1364]
I was playing a video with the stabilization filter active and hit Command-N by instinct for what I hoped was a new track; Cmd-N is a new project.  Shotcut crashed.  When the player is paused, Cmd-N will bring me back to the opening screen where I can name a new project.  I repeated this with the Editing and Player windows while the video is playing; when paused, both take you to the opening screen.
There is an update available to Monterey 12.6.1 that I will install now and test.
Shotcut 22-10-25
Macbook Pro M1 14" 16gb 
Monterey 12.6

**Comment by cruudesign** [comment]
Issue repeats after update to Monterey 12.6.1.  TIA.

**Comment by cruudesign** [comment]
I'll add all crashes here... Timeline broken out, just completed analysis for a new stabilization over the wee hours with zoom 5%, some increased values and a higher quality.  Saved file on waking, moved the main window with the top bar, crashed.  System resources are flat and stable at 6 of 16gb RAM.

**Comment by cruudesign** [comment]
Dragging or adjusting Timeline size crashes Shotcut.  2nd monitor plugged in.  It was working fine for a few projects.  Just created this one and added files.  Fine if I leave it alone and deal with one video track for editing.

**Comment by ddennedy** [comment]
> I'll add all crashes here

That is not acceptable, only the original bug. I believe I fixed it in a19c36914c5ebabc3ecffcb61699811ec1c877b3 included in the latest version 24.11
