### ISSUE TITLE
Linux Wayland Export Issues

### ISSUE THREAD

**Issue by S7venLights** [mltframework/shotcut#1369]
Hi I'm Using the 22.10.25 Flatpak in Fedora Silverblue in this case with wayland user windowing system.
Although looking at the app Flatseal, Shotcut is by default set not to use Wayland.

When exporting a video with libx264 it sometimes crashes.
This is the export log output of a successful export:

> Failed to create wl_display (No such file or directory)
> qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
> Gtk-Message: 14:04:51.601: Failed to load module "canberra-gtk-module"
> Gtk-Message: 14:04:51.601: Failed to load module "canberra-gtk-module"
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fefb8009700] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1001
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fefb8009700] st: 0 edit list 1 Cannot find an index entry before timestamp: 1001.
> [libx264 @ 0x7fefc0202040] using SAR=1/1
> [libx264 @ 0x7fefc0202040] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
> [h264 @ 0x7fefb800b780] Reinit context to 1920x1088, pix_fmt: yuvj420p
> [libx264 @ 0x7fefc0202040] profile High, level 4.0, 4:2:0, 8-bit
> [libx264 @ 0x7fefc0202040] 264 - core 164 - H.264/MPEG-4 AVC codec - Copyleft 2003-2022 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=6 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=90 keyint_min=9 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=20.0 qcomp=0.60 qpmin=23 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fefb815c980] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1001
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fefb815c980] st: 0 edit list 1 Cannot find an index entry before timestamp: 1001.
> [h264 @ 0x7fefb815b280] Reinit context to 1920x1088, pix_fmt: yuvj420p
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fefb8125000] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1001
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fefb8125000] st: 0 edit list 1 Cannot find an index entry before timestamp: 1001.
> [h264 @ 0x7fefb8150dc0] Reinit context to 1920x1088, pix_fmt: yuvj420p
> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
> [AVIOContext @ 0x7fefb8012240] Statistics: 479660 bytes read, 5 seeks
> [mp3 @ 0x7fefb899dac0] Skipping 0 bytes of junk at 0.
> [mp3 @ 0x7fefb899dac0] Estimating duration from bitrate, this may be inaccurate
> [mp3 @ 0x7fefb899e600] Skipping 0 bytes of junk at 0.
> [mp3 @ 0x7fefb899e600] Estimating duration from bitrate, this may be inaccurate
> [producer avformat] audio: total_streams 1 max_stream 0 total_channels 2 max_channels 2
> [AVIOContext @ 0x7fefb8144a00] Statistics: 131200 bytes read, 3 seeks
> [filter swresample] 2(stereo) f32le 44100Hz -> 2(stereo) f32le 48000Hz
> 
> [h264 @ 0x7fefb81327c0] Reinit context to 1920x1088, pix_fmt: yuvj420p

When I use Flatseal to turn on Wayland support for Shotcut:
The app loads fine and interestingly has a smaller ui and font scaling (better use of screen space) External factors: I have Large Text enabled in Fedoras accessibility settings..
The export doesn't error and opening logs look like this:

> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7feb58009700] st: 0 edit list: 1 Missing key frame while searching for timestamp: 1001
> [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7feb58009700] st: 0 edit list 1 Cannot find an index entry before timestamp: 1001.
> [libx264 @ 0x7feb60202040] using SAR=1/1

**Separate Issue:**
The rich text filter text position changes slightly in export. (Turns out turning on wayland in Flatseal fixes this, the preview window then shows accurate positions of text)

**Separate Issue:** 1920 video was put on the timeline and the 'video mode' was automatically set to 2160p.
When changing it back to 1080p after the whole edit, text and items in the timeline with 'size and position' filters on them come out too large! It doesn't correct.

PS: The app also sometimes crashes when moving things around the timeline. Usually if I grab a clip and try move it to a different track too quickly.

**Comment by S7venLights** [comment]
Wayland being on does break one thing:
The export and save windows in Gnome don't appear on top of shotcut but rather behind. I've seen that same behavior in other apps though.

**Comment by S7venLights** [comment]
Separate Export issue:

When trying to export images to video (With same export settings mentioned above) in a wayland session with wayland turned on in Flatseal, export fails:

> [mlt_producer 0x55718399ffe0] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [mlt_producer 0x5571839a3b80] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [AVIOContext @ 0x5571839d5b00] Statistics: 29304 bytes read, 0 seeks
> [mlt_producer 0x55718399e610] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [mlt_producer 0x5571839e27f0] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [AVIOContext @ 0x5571839e4200] Statistics: 286168 bytes read, 1 seeks
> [AVIOContext @ 0x5571839d3100] Statistics: 29304 bytes read, 0 seeks
> [AVIOContext @ 0x5571839fec80] Statistics: 143084 bytes read, 0 seeks
> [mlt_producer 0x557183c13a10] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [mlt_producer 0x557183c13a10] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [AVIOContext @ 0x557183c1f180] Statistics: 286168 bytes read, 1 seeks
> [filter 0x557183c21f80] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [mlt_producer 0x55718399e610] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [mlt_producer 0x55718399e610] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [AVIOContext @ 0x557183c49600] Statistics: 286168 bytes read, 1 seeks
> [filter 0x557183c4cd70] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [filter 0x557183c940b0] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [mlt_producer 0x557183c47470] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [mlt_producer 0x557183c47470] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [AVIOContext @ 0x557183c97600] Statistics: 286168 bytes read, 1 seeks
> [filter 0x557183c96080] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [filter 0x557183ce0b20] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [filter 0x557183cdd140] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [mlt_producer 0x557183ce0bb0] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [mlt_producer 0x557183ce0bb0] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [AVIOContext @ 0x557183c954c0] Statistics: 286168 bytes read, 1 seeks
> [filter 0x557183ce5300] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [filter 0x557183d252a0] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [filter 0x557183d25230] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [filter 0x557183ce5300] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [mlt_producer 0x557183d25560] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [mlt_producer 0x557183d25560] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [AVIOContext @ 0x557183d26440] Statistics: 286168 bytes read, 1 seeks
> [AVIOContext @ 0x557183c221c0] Statistics: 143084 bytes read, 0 seeks
> [AVIOContext @ 0x557183c63300] Statistics: 143084 bytes read, 0 seeks
> [AVIOContext @ 0x557183cb5480] Statistics: 143084 bytes read, 0 seeks
> [AVIOContext @ 0x557183ce4700] Statistics: 143084 bytes read, 0 seeks
> [AVIOContext @ 0x557183d2dcc0] Statistics: 143084 bytes read, 0 seeks
> [h264_nvenc @ 0x7f66a4202040] Loaded Nvenc version 12.0
> [h264_nvenc @ 0x7f66a4202040] Nvenc initialized successfully
> [h264_nvenc @ 0x7f66a4202040] 1 CUDA capable devices found
> [h264_nvenc @ 0x7f66a4202040] [ GPU #0 - < NVIDIA GeForce GTX 1060 > has Compute SM 6.1 ]
> [AVIOContext @ 0x7f669c011d00] Statistics: 286168 bytes read, 1 seeks
> [mp3 @ 0x7f669c03fbc0] Skipping 0 bytes of junk at 0.
> [mp3 @ 0x7f669c03fbc0] Estimating duration from bitrate, this may be inaccurate
> [mp3 @ 0x7f669c049800] Skipping 0 bytes of junk at 0.
> [mp3 @ 0x7f669c049800] Estimating duration from bitrate, this may be inaccurate
> [producer avformat] audio: total_streams 1 max_stream 0 total_channels 2 max_channels 2
> [AVIOContext @ 0x7f669c048480] Statistics: 131200 bytes read, 3 seeks
> [filter swresample] 2(stereo) f32le 44100Hz -> 2(stereo) f32le 48000Hz
> [h264_nvenc @ 0x7f66a4202040] Max B-frames 6 exceed 4
> [h264_nvenc @ 0x7f66a4202040] No capable devices found
> [h264_nvenc @ 0x7f66a4202040] Nvenc unloaded
> Failed with exit code 11
> Export job failed; trying again without Parallel processing.
> [mlt_producer 0x564b99cd1fe0] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [mlt_producer 0x564b99cd5b80] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [AVIOContext @ 0x564b99d07b00] Statistics: 29304 bytes read, 0 seeks
> [mlt_producer 0x564b99cd0610] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [mlt_producer 0x564b99d147f0] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [AVIOContext @ 0x564b99d16200] Statistics: 286168 bytes read, 1 seeks
> [AVIOContext @ 0x564b99d05100] Statistics: 29304 bytes read, 0 seeks
> [AVIOContext @ 0x564b99d30c80] Statistics: 143084 bytes read, 0 seeks
> [mlt_producer 0x564b99f45a10] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [mlt_producer 0x564b99f45a10] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [AVIOContext @ 0x564b99f51180] Statistics: 286168 bytes read, 1 seeks
> [filter 0x564b99f53f80] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [mlt_producer 0x564b99cd0610] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [mlt_producer 0x564b99cd0610] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [AVIOContext @ 0x564b99f7b600] Statistics: 286168 bytes read, 1 seeks
> [filter 0x564b99f7ed70] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [filter 0x564b99fc60b0] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [mlt_producer 0x564b99f79470] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [mlt_producer 0x564b99f79470] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [AVIOContext @ 0x564b99fc9600] Statistics: 286168 bytes read, 1 seeks
> [filter 0x564b99fc8080] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [filter 0x564b9a012b20] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [filter 0x564b9a00f140] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [mlt_producer 0x564b9a012bb0] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [mlt_producer 0x564b9a012bb0] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [AVIOContext @ 0x564b99fc74c0] Statistics: 286168 bytes read, 1 seeks
> [filter 0x564b9a017300] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [filter 0x564b9a0572a0] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [filter 0x564b9a057230] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [filter 0x564b9a017300] The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [producer_xml] failed to load filter "qtext"
> [mlt_producer 0x564b9a057560] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [mlt_producer 0x564b9a057560] <producer>
>     The MLT Qt module requires a X11 environment.
> Please either run melt from an X session or use a fake X server like xvfb:
> xvfb-run -a melt (...)
> [AVIOContext @ 0x564b9a058440] Statistics: 286168 bytes read, 1 seeks
> [AVIOContext @ 0x564b99f541c0] Statistics: 143084 bytes read, 0 seeks
> [AVIOContext @ 0x564b99f95300] Statistics: 143084 bytes read, 0 seeks
> [AVIOContext @ 0x564b99fe7480] Statistics: 143084 bytes read, 0 seeks
> [AVIOContext @ 0x564b9a016700] Statistics: 143084 bytes read, 0 seeks
> [AVIOContext @ 0x564b9a05fcc0] Statistics: 143084 bytes read, 0 seeks
> [h264_nvenc @ 0x7f1e88202040] Loaded Nvenc version 12.0
> [h264_nvenc @ 0x7f1e88202040] Nvenc initialized successfully
> [h264_nvenc @ 0x7f1e88202040] 1 CUDA capable devices found
> [h264_nvenc @ 0x7f1e88202040] [ GPU #0 - < NVIDIA GeForce GTX 1060 > has Compute SM 6.1 ]
> [AVIOContext @ 0x7f1e84011380] Statistics: 286168 bytes read, 1 seeks
> [mp3 @ 0x7f1e8403f440] Skipping 0 bytes of junk at 0.
> [mp3 @ 0x7f1e8403f440] Estimating duration from bitrate, this may be inaccurate
> [mp3 @ 0x7f1e84049d40] Skipping 0 bytes of junk at 0.
> [mp3 @ 0x7f1e84049d40] Estimating duration from bitrate, this may be inaccurate
> [producer avformat] audio: total_streams 1 max_stream 0 total_channels 2 max_channels 2
> [AVIOContext @ 0x7f1e84047cc0] Statistics: 131200 bytes read, 3 seeks
> [filter swresample] 2(stereo) f32le 44100Hz -> 2(stereo) f32le 48000Hz
> [h264_nvenc @ 0x7f1e88202040] Max B-frames 6 exceed 4
> [h264_nvenc @ 0x7f1e88202040] No capable devices found
> [h264_nvenc @ 0x7f1e88202040] Nvenc unloaded
> Failed with exit code 11
> Failed with exit code 11

**Comment by NyllRE** [comment]
same issue here with fedora 37 wayland

**Comment by ddennedy** [comment]
Expired due to many Qt upgrades since this.
