### ISSUE TITLE
Help - Actions and Shortcuts crashes when the --appdata command line switch is used on Windows

### ISSUE THREAD

**Issue by JohnTHaller** [mltframework/shotcut#1370]
When launching shotcut.exe with the --appdata switch, clicking on Help and then Actions and Shortcuts will cause Shotcut to crash. This happens with both relative and absolute paths. Removing the --appdata switch causes it to work without issue.

Shotcut 22.10.25 64-bit
Windows 10 Pro 22H2 64-bit Build 19045.2130

The last few lines in the log file are as follows:
```
[Debug  ] <MltXmlChecker::check> begin 
[Debug  ] <MltXmlChecker::check> "" 
[Debug  ] <MltXmlChecker::check> end "" 
[Info   ] <MainWindow::open> decimal point '.' 
```

**Comment by bmatherly** [comment]
I also recreate this on Linux.

Interestingly... I use the --appdata switch to set the appdata to the default location and it still crashes. But maybe that is invalid because when I do this, none of my saved settings are applied.
