### ISSUE TITLE
Windows sound settings are ignored / impossible to select audio output device.

### ISSUE THREAD

**Issue by ghost** [mltframework/shotcut#1371]
Shotcut has no method to select an audio output device. Windows has built-in facilities to direct application audio to a specific device, but shotcut bypasses this and forces the audio into the default device.

Here's a screenshot of windows' settings with shotcut assigned to a specific device and the audio playing through the default anyway:
![image](https://user-images.githubusercontent.com/58130821/199931333-6082da01-76f5-4722-b9e7-25cf39e3a724.png)

**Comment by ddennedy** [comment]
You need to restart Shotcut after you change the output device.

**Comment by xcasxcursex** [comment]
> You need to restart Shotcut after you change the output device.

I'm afraid that doesn't work either. The above screenshot was taken after a restart of the app.

**Comment by ddennedy** [comment]
No longer need to restart after default output device changes since version 23.07,  not adding audio device selection inside Shotcut.
