### ISSUE TITLE
Menu on Right click not the same as pervious versions

### ISSUE THREAD

**Issue by detectdigsmile** [mltframework/shotcut#1372]
I upgrade to the latest version 22.10.25.  I noticed the right click menu was not the same.  I installed the pervious version and it was back that version is 22.06.23.  Is there a way to get the new version to have this menu?

I have attached a screenshot of the old menu and what was in it.

![2022-11-06_20-16-21](https://user-images.githubusercontent.com/117610691/200208539-39d7cb3a-381b-4f88-afa3-15c447820bb1.jpg)

**Comment by bmatherly** [comment]
> I upgrade to the latest version 22.10.25. I noticed the right click menu was not the same.

The menu design was re-written to support the "Actions and Shortcuts" dialog and to fix the label tuncation problem that is visible in your screenshot ("M...").

You  can read about it here:
https://github.com/mltframework/shotcut/releases/tag/v22.09.23

This change is not a bug. We change it on purpose.

> Is there a way to get the new version to have this menu?

no
