### ISSUE TITLE
[22.10.25] Pitch compensation distorts audio when increasing playback speed in expotred material

### ISSUE THREAD

**Issue by gutko** [mltframework/shotcut#1373]
Im talking about speed bump of around 1.5x-2x
It does not happen when playing videos on youtube and for example vlc with playback speed bumped by 1.5x-2x so yt and vlc must use another better method(?). 
Win10 x64 22h2 build 19045.2251
Shotcut version 22.10.25

Sample video https://www.youtube.com/watch?v=jWbKqa6Y0W0
Downloaded sample using `yt-dlp https://youtu.be/jWbKqa6Y0W0`
Youtube online version at 1.5 as well as downloaded sample in vlc at 1.5x sounds ok
Shotcut reencoded at 1.5 sounds little robotic with mechanical echo https://files.catbox.moe/3p7f9i.mp4

Test steps:
1.  Drag+drop sample on track 1
2.  Click on properties
3.  Set the speed to 1.5
4.  Check the "Pitch Compensation" check box, 
5.  Hit apply
6.  Play the clip in the player and observe that the audio sounds little robotic with some kind of mechanical echo
7.  Export using default presets h264 high profile
8.  Play the exported file in VLC and observe that the audio sounds little robotic with some kind of mechanical echo

**Comment by bmatherly** [comment]
I do not reproduce this on Windows 11 with Shotcut version 22.10.25

Test steps:
1) Open a file
2) Click on properties
3) Set the speed to 1.5
4) Check the "Pitch Compensation" check box
5) Play the clip in the player and observe that the audio is good
6) Export using default presets
7) Play the exported file in VLC and observe that the audio is good.

**Comment by ddennedy** [comment]
You did not provide operating system, version info, or steps as requested in the template rendering this invalid.

**Comment by gutko** [comment]
I will edit this post with required info later today

**Comment by gutko** [comment]
updated

**Comment by bmatherly** [comment]
> observe that the audio sounds little robotic with some kind of mechanical echo

I agree that for human voice the pitch compensation adds some echo effect. This is as good as we can do with the underlying [pitch library](https://rubberbandaudio.com/) that we use. The compensation works better other kinds of audio like music.

You can read other discussion on this topic:
https://forum.shotcut.org/t/problems-with-pitch-compensation/26788
https://forum.shotcut.org/t/pitch-changes-lower-the-audio-quality/30697

The library we use is called “Rubberband”. There is a demo application here that you can use to see how the library works for your specific audio:
https://rubberbandaudio.com/

**Comment by ddennedy** [comment]
There is an upgrade to the library we can look into.

**Comment by bmatherly** [comment]
> There is an upgrade to the library we can look into.

Looks promising. I will try it out.

**Comment by gutko** [comment]
thank you, couldnt find version info of rubberband in shotcut files but advertising on their version 3.x.x looks promising

**Comment by bmatherly** [comment]
I made this commit to MLT: https://github.com/mltframework/mlt/commit/45f3737116034ae94ebd4a4473cc042e30a3c20b
It uses the new "finer" engine when compiled with version 3.x
In my listening tests, the finer engine does have better audio quality. I also tested at the extreme pitch changes and I do not notice any problems.

**Comment by ddennedy** [comment]
What about memory and performance of “finer” especially at higher change values?

**Comment by bmatherly** [comment]
I tested the min/max values allowed by Shotcut and it works very well. I do not notice a change in performance/memory utilization. I plan to do some extreme testing tonight before I update the build scripts.

**Comment by bmatherly** [comment]
My final test results were positive. The "finer" engine seems to hold up well even with extreme pitch changes. I've updated the build script to use the latest rubberband library for the next release.
