### ISSUE TITLE
Shotcut [22.10.25] crashes on start up on arch.

### ISSUE THREAD

**Issue by MadoScientist97** [mltframework/shotcut#1374]
Hardware Specs: Intel i5 7300HQ, RAM; 16GB, GPU1: Intel HD, GPU2: 1050 Ti
Running Arch with latest updates.
DE: No DE using only i3wm
Login: tui-greet + systemd

Wanted to try shotcut for the first time. I installed it from the pacman repo as it had the latest version. However starting the app always causes a crash and creates a core dump. Analyzing the core dump and having a bt gives this:

`warning: Can't open file /memfd:/.glXXXXXX (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:unknown-usage:QtQml (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:JITCode:QtQml (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:JSGCHeap:QtQml (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:JSVMStack:QtQml (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:/.nvidia_drv.XXXXXX (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:xorg (deleted) during file-backed mapping note processing
[New LWP 547847]
[New LWP 547849]
[New LWP 547853]
[New LWP 547848]
[New LWP 547854]
[New LWP 547851]
[New LWP 547850]
[New LWP 547852]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `shotcut --gpu'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f3390ea164c in ?? () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f338f40b840 (LWP 547847))]
(gdb) bt
#0  0x00007f3390ea164c in  () at /usr/lib/libc.so.6
#1  0x00007f3390e51958 in raise () at /usr/lib/libc.so.6
#2  0x00007f3390e3b53d in abort () at /usr/lib/libc.so.6
#3  0x00007f3392b1b29e in  () at /usr/lib/libCuteLogger.so
#4  0x00007f3392b23858 in Logger::write(QDateTime const&, Logger::LogLevel, char const*, int, char const*, char const*, QString const&) () at /usr/lib/libCuteLogger.so
#5  0x00007f3392b238cf in Logger::write(Logger::LogLevel, char const*, int, char const*, char const*, QString const&) ()
    at /usr/lib/libCuteLogger.so
#6  0x00007f3392b23b8c in  () at /usr/lib/libCuteLogger.so
#7  0x00007f33904e0a88 in  () at /usr/lib/libQt5Core.so.5
#8  0x00007f33904d9b99 in  () at /usr/lib/libQt5Core.so.5
#9  0x00007f339049fec4 in QMessageLogger::fatal(char const*, ...) const () at /usr/lib/libQt5Core.so.5
#10 0x00007f33904bdb77 in  () at /usr/lib/libQt5Core.so.5
#11 0x00007f339291692c in QWebSocket::QWebSocket(QString const&, QWebSocketProtocol::Version, QObject*) ()
    at /usr/lib/libQt5WebSockets.so.5
#12 0x00005645967ace0e in  ()
#13 0x00005645967afaa4 in  ()
#14 0x00005645967b5cce in  ()
#15 0x00005645966a4e15 in main ()`

Getting a strace for this it seems to crash at this:
`newfstatat(AT_FDCWD, "/etc/localtime", {st_mode=S_IFREG|0644, st_size=285, ...}, 0) = 0
write(8, "[Fatal  ] <> Cannot mix incompat"..., 84) = 84
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
gettid()                                = 557584
getpid()                                = 557584
tgkill(557584, 557584, SIGABRT)         = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=557584, si_uid=1000} ---
+++ killed by SIGABRT (core dumped) +++
Aborted (core dumped)`

I am most likely missing a dependency. Although I seem to have all. Any help would be appreciated.

**Comment by ddennedy** [comment]
1. We do not support this build; only our own. Might be better to get support from the person or party who built this. And we do not like to track other parties’ builds as bugs in our own system.
2. The build provided through our download page work for me on Ubuntu 20.04 and Pop!_OS 22.04. I do not have Arch and not going to set that up.
3. The gpu command line option is experimental and unsupported. Did you try without it?
4. This application requires a working OpenGL.

**Comment by MadoScientist97** [comment]
Yes I tried without it, have a similar backtrace. I have openGL working fine with both the gpus through PRIME. I got this from the official Arch Repo, not sure whom to approach but let me try one from the release page.

**Comment by MadoScientist97** [comment]
Alright the appimage version is working. Gotta raise it to the arch team then. Closing this ticket as it doesn't seem to be an app issue really.
