### ISSUE TITLE
The encoder 'opus' is experimental but experimental codecs are not enabled

### ISSUE THREAD

**Issue by kparal** [mltframework/shotcut#1378]
I wanted to export a video using the `opus` audio codec, so I selected `opus` in the `Audio -> Codec` menu in `Export` (while using `matroska` container), and... the resulting video had no audio at all! It took me a while, but eventually, I found the error in the Job Log:
```
...
[opus @ 0x7f22f0005cc0] The encoder 'opus' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
[opus @ 0x7f22f0005cc0] Alternatively use the non experimental encoder 'libopus'.
/run/build/mlt/src/modules/avformat/consumer_avformat.c: Unable to encode audio - disabling audio output.
...
```
And when I followed the advice and used `libopus` instead of `opus` as the audio codec, everything worked, the exported video had an opus audio track.

But this is very confusing for the general user. The obviously named codec `opus` doesn't work, you'll only find it out if you try to listen to the produced video file, and the error message is extremely well hidden.

I think either `opus` audio codec should be hidden (and possibly `libopus` be renamed to `opus` instead, so that people can find it easier), or experimental codecs should be enabled (not sure what the disadvantages are). In the current state, it's just confusing and seems broken.

Thanks!

Fedora 37  
Shotcut 22.11.25 installed from Flathub

**Comment by ddennedy** [comment]
We list the codecs provided by FFmpeg libavcodec and will not adjust them. Also, You are in the Advanced section of the Export panel. The AV1 and WebM presets include a working opus configuration.
