### ISSUE TITLE
Video goes to 0x0 and 0,0 if I click keyframes button

### ISSUE THREAD

**Issue by ChutacoackoPlayz** [mltframework/shotcut#1379]
Shotcut version: 22.11.25
OS: Windows 11 22H2

Title basically says it all. If I click keyframes, the whole video becomes resolution of 0x0 and goes to 0,0 place
A sample of this glitch (before and after, replicated):
![Screenshot (49)](https://user-images.githubusercontent.com/62620653/205411818-ab7efbf2-1084-4ffe-997e-8c66ea740038.png)
![Screenshot (50)](https://user-images.githubusercontent.com/62620653/205411820-467f26b9-4965-4467-9409-a6f64d21f00d.png)
I wonder why I experience many glitches and issues when using Shotcut (each newer version there's always an annoying glitch/crash).

**Comment by ddennedy** [comment]
Already reported and fixed for the next version. Feel free to get a nightly build from the Actions tab here on GitHub.

**Comment by ddennedy** [comment]
Fix for this in new beta https://github.com/mltframework/shotcut/releases/tag/v22.12.04
