### ISSUE TITLE
HEVC movies taken with Canon R6 DSLR show pale colors

### ISSUE THREAD

**Issue by freebrowser1** [mltframework/shotcut#1381]
Shotcut is an excellent video editor, better that iMovie and even better than the commercial Filmora.

But when processing video clips recorded by the Canon EOS R6 (original version) I see a strong difference between H.265 (HDR PQ setting to ON) and H.264 (HDR PQ OFF).
The latter has the original vibrat colors, while the HDR PQ recordings contain pale colors and sometimes a bit darker.

Different export settings (even H.264 or HEVC) does not make any difference.

The weird thing about this is that when I process the H.265 / HDR PQ video in iMovie I don't see pale coloration.
See an example video of a wood fire.

Am I doing anything wrong ?

macOS 10.18.0 (13.0: Ventura) on M1
Shotcut 22.11.25 M1 version

https://user-images.githubusercontent.com/26625141/206565955-486713d1-3c3b-4016-bc4d-2b69a8525375.mp4

**Comment by ddennedy** [comment]
Shotcut does not support HDR directly and for output. You must convert them to SDR. In Shotcut you can use Properties > Convert > Advanced > Convert to BT.709 colorspace.
