### ISSUE TITLE
Time remap disables Crop: Source

### ISSUE THREAD

**Issue by kkibria** [mltframework/shotcut#1382]
I have windows 10 and my shotcut version is 22.11.25. I see ~~two~~ a problem ~~s~~,

1. Time remap and crop does not work together. If I crop (center weighted) and no Time remap then crop works just fine, but as soon as I add Time remap cropping goes away from the project window. Then when I remove Time remap plug in then crop starts working fine again.
2.  ~~The property editor for the clip provides a button for pitch compensation to enable rubberband for audio. However Time remap does not have any such option to use audio rubberband library.~~

**Comment by ddennedy** [comment]
1. It might not be addressed due to how Crop: Source works and the architecture. The workaround is to use Size, Position & Rotate filter and zoom in.
2. Yes, it is integrated into Time Remap. There is a checkbox for pitch compensation!

**Comment by kkibria** [comment]
I see the pitch compensation option in Time remap now, I was looking for it in the wrong place. I will edit the ticket to remove the 2nd item.

**Comment by kkibria** [comment]
I'll use the workaround suggested.

**Comment by ddennedy** [comment]
Fixed in MLT for next version.
