### ISSUE TITLE
Exported video file can't be read correctly

### ISSUE THREAD

**Issue by benwiley4000** [mltframework/shotcut#1393]
I'm running Shotcut 22.12.1 on macOS Mojave 10.14 (Intel).

I haven't yet found an export setting that actually works. I've tried several variations on settings. I would appreciate some help finding settings that will work, but also, I think this is pretty clearly a bug.

## What happens if I try to read the file in quicktime

My video is one minute long, but the full video plays at ultra-high framerate - finishing in less than a second. If I manually scrub through the whole video with Quicktime's progress bar, I can see that all the exported frames are present, but Quicktime doesn't understand to only play 30 of those frames per second. No audio is played.

## What happens if I try to open the file in Google Chrome or Firefox

The audio plays perfectly, but the video hangs on the first frame. The video progress bar doesn't advance. I can scrub manually to get to a different frame, and then the progress will hang there again. The audio will pick up and play at the correct place I scrubbed to, though.

Clearly the video export almost worked... there's just something broken that seems to make the file non-standard. If anyone could help me find a workaround while I'm waiting on a fix, I'd really appreciate it.

## My settings

![Screen Shot 2022-12-31 at 3 32 09 PM](https://user-images.githubusercontent.com/13558253/210155326-3823f7c3-80dc-4901-9ab6-61783af79c0f.png)
![Screen Shot 2022-12-31 at 3 32 18 PM](https://user-images.githubusercontent.com/13558253/210155328-ddcbac7b-15e5-4257-b372-0d59a649debf.png)
![Screen Shot 2022-12-31 at 3 32 26 PM](https://user-images.githubusercontent.com/13558253/210155330-c88eec72-1a23-484f-9f06-496ae43b5140.png)
![Screen Shot 2022-12-31 at 3 32 31 PM](https://user-images.githubusercontent.com/13558253/210155332-52253831-b485-4b3a-82f6-2bb5819ee998.png)

**Comment by ddennedy** [comment]
> Shotcut 22.12.1 on macOS Mojave 10.14 (Intel)

I just retested that combination, and it works fine for me. Hundreds of thousands of people use Shotcut on a monthly basis, and we would certainly hear about it if there is a general problem with export.

Did you change anything in Export > Video? Try without changing anything. You should use Settings > Video Mode instead.

Try without hardware encoder; maybe it is doing something bad on your system. If so, *maybe* a reboot will help.
Try playing the result in Shotcut.

Here is an example I exported at 2 Mb/s for GitHub to accept it so you can try it on your players.

https://user-images.githubusercontent.com/1146683/210156161-77ac746d-0493-401c-846a-b18f1ea3c3b9.mp4

**Comment by benwiley4000** [comment]
Thanks for checking it out. I don't have a great explanation but since I came back to this, everything works now. I did quit and restart the program, but other than that I don't see how anything changed (didn't even restart my computer). The only setting I had originally changed in the advanced settings was the audio sample rate, but I checked with that setting configured as I had before, and it still works. You can close this if you don't see what could have caused the issue. Hopefully it doesn't come back.

**Comment by ddennedy** [comment]
Also make sure export is completely done before trying to play. And next time you can right click the job to get a menu item to view a log that might reveal something.

**Comment by benwiley4000** [comment]
I definitely waited for the jobs to finish each time, although I didn't
read the logs once they were successful.

Le sam. 31 déc. 2022, 6 h 28 p.m., Dan Dennedy ***@***.***> a
écrit :
