### ISSUE TITLE
Incorrect video clip framing for transitions and segmentation fault

### ISSUE THREAD

**Issue by benwiley4000** [mltframework/shotcut#1394]
I'm running Shotcut 22.12.1 on macOS Mojave 10.14 (Intel).

My project was previously working fine and I somehow triggered an error with transitions that I am having a hard time fixing. I think it might have happened after I tried to apply a filter to the whole output or track, and then removed it.

What's now happening is that when I transition between two clips with the Size, Position and Rotate filter active, the Size, Position and Rotate filter appears not to be applied correctly during the transition between the clips - the frame around the clip is reduced although the content is still zoomed in.

I've confirmed that this will also happen for new transitions I create between newly added clips - not just for the transitions I'd already saved in my project.

Here is a screenshot. Note that the rectangular overlay in the middle of the screen is supposed to take up the full area of the white frame, as it does before and after transition. Until my mystery action which broke everything a few minutes ago, this was working fine. Now it's adjusting during the transition to fit in the viewport according to its original aspect ratio.

![Screen Shot 2023-01-01 at 8 50 28 PM](https://user-images.githubusercontent.com/13558253/210190310-487d0e35-e3e1-497c-924e-d2c037495aa3.png)

I figured I could try to fix this by deleting the transition and recreating it. However dragging the edge of the second clip produced a segmentation fault:

```
[h264 @ 0x7fec9fcab740] mmco: unref short failure
Segmentation fault: 11
```

I've tried restarting my computer but the issue persists.

This is pretty bad for me because I basically can't edit this project anymore without it crashing. I'd appreciate any workaround available.

**Comment by benwiley4000** [comment]
I just realized this was all due to the Audio Dance Visualization filter. Very strange!!

**Comment by bmatherly** [comment]
I am glad you were able to find a work-around. If you can provide a simple project file that demonstrates the problem, I would be happy to take a look.
