### ISSUE TITLE
a user reports a problem with starting on linux

### ISSUE THREAD

**Issue by alexmyczko** [mltframework/shotcut#1399]
Please see the details at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1019445

I was not able to reproduce the problem, and it's maybe a local user problem, reporting it anyways to maybe find out if there are others with this issue.

**Comment by ddennedy** [comment]
A web search on "File already exists in database: opencv-caffe.proto" shows this is a not uncommon problem. There is a suggestion to statically link to libprotobuf from upstream caffe project in
https://github.com/BVLC/caffe/issues/1917
