### ISSUE TITLE
3D Text plugin issue

### ISSUE THREAD

**Issue by itspec-ru** [mltframework/shotcut#140]
Extended characters appear as "?" when using the plugin 3D Text

**Comment by ddennedy** [comment]
I reproduce it. Even if I hard code a string like "Téléchargements" in the JavaScript of the HTML file, it fails. It also affects the Overlay HTML filter.

**Comment by itspec-ru** [comment]
O. K. Waiting for bug fix.
Thank you for great program!

**Comment by itspec-ru** [comment]
When I use the filter "Overlay HTML", I in the "View Source" add 
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
to the tag "head". Then everything works correctly.

**Comment by ddennedy** [comment]
Hey, that's a great find! I have tested it here, and it works. I am using the form presented here:
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Introduction_to_HTML5

**Comment by ddennedy** [comment]
As you can see in the meantime, you can simply edit your file at Shotcut.app/share/shotcut/qml/filters/webvfx_threejs_text/threejs_text.html

**Comment by itspec-ru** [comment]
Thank you! Now filter works perfect. I'm build shotcut from sources in gentoo linux using portage.
I just reinstalled shotcut using sources from github.
