### ISSUE TITLE
ffmpeg command

### ISSUE THREAD

**Issue by rufan321** [mltframework/shotcut#1403]
This software is wonderful, but I just like the cut function, as I want to cut some video clip. so I usually use ffmpeg,
ffmpeg -ss 00:31:00  -to 00:55:09 -i 123.mp4 -threads 2 -c:v copy -c:a copy outputVideo.mp4
this command is fast but will loss the video quality, can someone help me to use ffmpeg to lossless cut the video clip? thanks

**Comment by ddennedy** [comment]
This is an invalid bug report, and this is not a discussion forum. You can use in Shotcut Properties > menu > Extract Sub-clip to run a similar ffmpeg command line interactively.

**Comment by rufan321** [comment]
thanks! Ddennedy
