### ISSUE TITLE
std::pmr requires C++17

### ISSUE THREAD

**Issue by Tjoppen** [mltframework/shotcut#1404]
On building with `g++ (GCC) 6.3.1 20170510 (for GNAT GPL 2017 20170515)`:

```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.2: undefined reference to `std::pmr::monotonic_buffer_resource::~monotonic_buffer_resource()@GLIBCXX_3.4.28'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.2: undefined reference to `vtable for std::pmr::monotonic_buffer_resource@GLIBCXX_3.4.28'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.2: undefined reference to `std::pmr::get_default_resource()@GLIBCXX_3.4.26'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.2: undefined reference to `std::pmr::monotonic_buffer_resource::_M_new_buffer(unsigned long, unsigned long)@GLIBCXX_3.4.26'
```

For some reason qt5widgets uses C++17 features. Curiously linking libstdc++ statically fixes the issue whereas upgrading CMAKE_CXX_STANDARD to 17 does not:

```cmake
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static-libstdc++")
```

**Comment by ddennedy** [comment]
I do not think this is a Shotcut bug. Qt 5.15 only requires C++11:
https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/global/qcompilerdetection.h?h=5.15#n588
Qt 6 does require C++17, but we have a qt6 branch that is building fine across different OS with no change to increase `CMAKE_CXX_STANDARD` in `CMakeLists.txt`. It might inherit something from the Qt cmake files. I might increment it on that branch. I only directly support our own nightly builds. Others can submit a PR to make something better for their needs, and I will consider it.

**Comment by Tjoppen** [comment]
Yeah I suspect it's just something borked on my end or Debian messed something up. Perhaps someone will run across this ticket and find my solution until the next Debian release probably fixes things. Maybe.
