### ISSUE TITLE
"Failed to read version.json when checking" on AppImage build

### ISSUE THREAD

**Issue by metalfoxdev** [mltframework/shotcut#1406]
Specs:

Shotcut 22.12.21 (AppImage Edition)
Manjaro Linux

When launching, Shotcut puts a message next to the video player saying "Failed to read version.json when checking", I am connected to the Internet.
![Screenshot_20230217_170851](https://user-images.githubusercontent.com/92944520/219718523-9cfcdb75-b898-4aad-a539-beff822c6036.png)

**Comment by ddennedy** [comment]
This is a known problem due to OpenSSL 3 API breakage, and we intentionally do not bundle OpenSSL libs on Linux. This is already fixed for the next version by a) Qt 6 is built against OpenSSL3 b) falling back to HTTP.
