### ISSUE TITLE
Track Overlaying Causes Undesired Removal

### ISSUE THREAD

**Issue by MrTeeXD** [mltframework/shotcut#1409]
Metadata:
- OS: Windows 11 Pro 64bit
- ShotCut Version: 22.12.21

### What is the issue?
I am not sure if this is intentional, but if I attempt to overlay one video over the over, the bottom video gets removed and replaced by the one I want to overlay. I am not sure this is the operation I wanted.

### Screenshot or Video Recording of the issue
https://user-images.githubusercontent.com/37266538/221791909-5492b3c6-cc3d-443c-bcdc-948ffee93f58.mp4

**Comment by ddennedy** [comment]
You have Ripple and Ripple All Tracks turned on (see the Timeline toolbar).
