### ISSUE TITLE
Suggested file extension does not match encode format.

### ISSUE THREAD

**Issue by bmatherly** [mltframework/shotcut#141]
Steps to reproduce:
1. Open a file
2. Choose "avi" from the format list in the encode dock
3. Click "Encode File"
4. Observe that the suggested file name extension in the "Encode to File" dialog is ".mp4". It should be ".avi".

**Comment by ddennedy** [comment]
Brian, there is no easy way to do this. This list of suggested extensions is in libavformat, and I do not want to add this to the MLT avformat consumer or Shotcut. All I can suggest is that choosing a format explicitly (not using a preset), would clear the extension recommended by Shotcut.

**Comment by bmatherly** [comment]
I agree that, minimally, we could clear the extension suggestion if they change the format. 

I volunteer to do some research to see if I come up with an amicable solution. If I don't, we can clear the suggestion on format change and call it good.
