### ISSUE TITLE
Chroma Key Issues

### ISSUE THREAD

**Issue by MrTeeXD** [mltframework/shotcut#1412]
### Technical Information:
ShotCut Version: 22.12.21
OS: Windows 11 Pro 64bit

#### Issue Description
Either I am completely stupid or ChromaKey does not work the way I want it to work. I am trying to key out a specific colour but for some reason, it is not doing so. Here is a GIF of what I am doing.

![shotcut_Bs7u2bHMZJ](https://user-images.githubusercontent.com/37266538/225755580-ecdbeed6-fc67-408f-87b3-ab0357125344.gif)

**Comment by MrTeeXD** [comment]
I did re-enable it but still no effect

**Comment by ddennedy** [comment]
Not a bug. You do not have anything under the video you are keying. You need to add a video track below it to see something else.

**Comment by ddennedy** [comment]
If you want to "see" the transparency without putting anything underneath it, then add the **Alpha Channel: View** filter. Shotcut does not automatically blend V1 with anything like black or a checkerboard to optimize performance.

**Comment by MrTeeXD** [comment]
Would that filter be applied on the same channel as the video or the track below the video?
