### ISSUE TITLE
Build failure on Ubuntu 22.10 

### ISSUE THREAD

**Issue by ashinpan** [mltframework/shotcut#1416]
I tried to build shotcut (master branch) on Ubuntu 22.10. 

I used cmake-gui and accepted all defaults except the INSTALL_PREFIX, which I changed to the home folder.  What follows is the error message:

---------------------
[ 31%] Building CXX object src/CMakeFiles/shotcut.dir/mltcontroller.cpp.o
/home/pan/Develop/shotcut/src/mltcontroller.cpp: In member function ‘Mlt::Producer* Mlt::Controller::setupNewProducer(Mlt::Producer*) const’:
/home/pan/Develop/shotcut/src/mltcontroller.cpp:975:20: error: ‘class Mlt::Chain’ has no member named ‘attach_normalizers’
  975 |             chain->attach_normalizers();
      |                    ^~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/shotcut.dir/build.make:1071: src/CMakeFiles/shotcut.dir/mltcontroller.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:272: src/CMakeFiles/shotcut.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by bmatherly** [comment]
you need to use MLT master with Shotcut master

**Comment by ddennedy** [comment]
Every release of Shotcut requires the latest release of MLT. Take the version of MLT you are using, get its release date, and find the previous release of Shotcut. That is the combination that will work (but not with Qt 6 as that only works with our master branch).
