### ISSUE TITLE
Consistent crash when adding new video track

### ISSUE THREAD

**Issue by phr00t** [mltframework/shotcut#142]
Windows 10, x64, Shotcut v15.11.03, Qt 5.5, NVIDIA 760M / Intel Optimus laptop. GPU rendering on & off doesn't matter.

1) Open Shot Cut (playlist & filter panes visible)
2) Drag mp4 video taken from Galaxy S4 to playlist
3) Drag video from platlist to video track area.... CRASH

Full log below. Program is overwhelmingly unstable, and almost anything I do within a minute or two will cause crashes. This is just one consistent one I can create. Rarely when this crash doesn't happen, If I try to create a new video track, the application crashes.

Version=1
EventType=APPCRASH
EventTime=130924355883463698
ReportType=2
Consent=1
UploadTime=130924355884054441
ReportIdentifier=4a853395-8ef5-11e5-8373-240a64bcd317
IntegratorReportIdentifier=dc468769-c556-45b0-a03f-b01a7abbef61
NsAppName=shotcut.exe
Response.BucketId=d82060bd68ba7cf02f6136908956c29c
Response.BucketTable=4
Response.LegacyBucketId=120349837411
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=shotcut.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=5638f0d2
Sig[3].Name=Fault Module Name
Sig[3].Value=shotcut.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5638f0d2
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000094b37
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.10240.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=92d0
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=92d0d867e4b59143ef3a3e7d38676aad
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=041d
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=041dbc482efe0b4d5a6b4daedcbf6432
UI[2]=C:\Program Files\Shotcut\shotcut.exe
UI[3]=shotcut.exe has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files\Shotcut\shotcut.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\system32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\system32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\system32\apphelp.dll
LoadedModule[5]=C:\WINDOWS\AppPatch\AppPatch64\AcLayers.DLL
LoadedModule[6]=C:\WINDOWS\system32\msvcrt.dll
LoadedModule[7]=C:\WINDOWS\system32\USER32.dll
LoadedModule[8]=C:\WINDOWS\system32\GDI32.dll
LoadedModule[9]=C:\WINDOWS\system32\SHLWAPI.dll
LoadedModule[10]=C:\WINDOWS\system32\combase.dll
LoadedModule[11]=C:\WINDOWS\system32\RPCRT4.dll
LoadedModule[12]=C:\WINDOWS\SYSTEM32\sfc.dll
LoadedModule[13]=C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
LoadedModule[14]=C:\WINDOWS\SYSTEM32\bcrypt.dll
LoadedModule[15]=C:\WINDOWS\SYSTEM32\sfc_os.DLL
LoadedModule[16]=C:\WINDOWS\system32\IMM32.DLL
LoadedModule[17]=C:\WINDOWS\system32\MSCTF.dll
LoadedModule[18]=C:\WINDOWS\system32\SHELL32.dll
LoadedModule[19]=C:\WINDOWS\system32\windows.storage.dll
LoadedModule[20]=C:\WINDOWS\system32\advapi32.dll
LoadedModule[21]=C:\WINDOWS\system32\sechost.dll
LoadedModule[22]=C:\WINDOWS\system32\kernel.appcore.dll
LoadedModule[23]=C:\WINDOWS\system32\shcore.dll
LoadedModule[24]=C:\WINDOWS\system32\powrprof.dll
LoadedModule[25]=C:\WINDOWS\system32\profapi.dll
LoadedModule[26]=C:\Program Files\Shotcut\Qt5Core.dll
LoadedModule[27]=C:\Program Files\Shotcut\Qt5Gui.dll
LoadedModule[28]=C:\WINDOWS\system32\ole32.dll
LoadedModule[29]=C:\Program Files\Shotcut\Qt5Multimedia.dll
LoadedModule[30]=C:\Program Files\Shotcut\Qt5Network.dll
LoadedModule[31]=C:\WINDOWS\system32\WS2_32.dll
LoadedModule[32]=C:\Program Files\Shotcut\Qt5OpenGL.dll
LoadedModule[33]=C:\Program Files\Shotcut\Qt5Qml.dll
LoadedModule[34]=C:\WINDOWS\system32\CRYPT32.dll
LoadedModule[35]=C:\WINDOWS\system32\NSI.dll
LoadedModule[36]=C:\Program Files\Shotcut\Qt5Quick.dll
LoadedModule[37]=C:\Program Files\Shotcut\Qt5QuickWidgets.dll
LoadedModule[38]=C:\WINDOWS\system32\MSASN1.dll
LoadedModule[39]=C:\Program Files\Shotcut\Qt5Sql.dll
LoadedModule[40]=C:\Program Files\Shotcut\Qt5WebKitWidgets.dll
LoadedModule[41]=C:\Program Files\Shotcut\Qt5WebSockets.dll
LoadedModule[42]=C:\Program Files\Shotcut\Qt5Widgets.dll
LoadedModule[43]=C:\Program Files\Shotcut\Qt5Xml.dll
LoadedModule[44]=C:\Program Files\Shotcut\libmlt-6.dll
LoadedModule[45]=C:\Program Files\Shotcut\libmlt++-3.dll
LoadedModule[46]=C:\Program Files\Shotcut\libgcc_s_seh-1.dll
LoadedModule[47]=C:\Program Files\Shotcut\libstdc++-6.dll
LoadedModule[48]=C:\WINDOWS\SYSTEM32\MPR.dll
LoadedModule[49]=C:\WINDOWS\SYSTEM32\DNSAPI.dll
LoadedModule[50]=C:\Program Files\Shotcut\Qt5MultimediaWidgets.dll
LoadedModule[51]=C:\Program Files\Shotcut\Qt5PrintSupport.dll
LoadedModule[52]=C:\Program Files\Shotcut\Qt5Sensors.dll
LoadedModule[53]=C:\WINDOWS\system32\comdlg32.dll
LoadedModule[54]=C:\Program Files\Shotcut\Qt5WebKit.dll
LoadedModule[55]=C:\Program Files\Shotcut\libdl.dll
LoadedModule[56]=C:\Program Files\Shotcut\libiconv-2.dll
LoadedModule[57]=C:\Program Files\Shotcut\libwinpthread-1.dll
LoadedModule[58]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.10240.16384_none_0212ec7eba871e86\COMCTL32.dll
LoadedModule[59]=C:\Program Files\Shotcut\Qt5Positioning.dll
LoadedModule[60]=C:\Program Files\Shotcut\Qt5WebChannel.dll
LoadedModule[61]=C:\Program Files\Shotcut\icuin55.dll
LoadedModule[62]=C:\Program Files\Shotcut\icuuc55.dll
LoadedModule[63]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[64]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[65]=C:\Program Files\Shotcut\icudt55.dll
LoadedModule[66]=C:\WINDOWS\SYSTEM32\WINMMBASE.dll
LoadedModule[67]=C:\WINDOWS\system32\cfgmgr32.dll
LoadedModule[68]=C:\WINDOWS\SYSTEM32\DEVOBJ.dll
LoadedModule[69]=C:\Program Files\Shotcut\lib\qt5\platforms\qwindows.dll
LoadedModule[70]=C:\WINDOWS\system32\OLEAUT32.dll
LoadedModule[71]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[72]=C:\WINDOWS\SYSTEM32\bcryptPrimitives.dll
LoadedModule[73]=C:\WINDOWS\system32\dwmapi.dll
LoadedModule[74]=C:\Program Files\Shotcut\lib\qt5\imageformats\qdds.dll
LoadedModule[75]=C:\Program Files\Shotcut\lib\qt5\imageformats\qgif.dll
LoadedModule[76]=C:\Program Files\Shotcut\lib\qt5\imageformats\qicns.dll
LoadedModule[77]=C:\Program Files\Shotcut\lib\qt5\imageformats\qico.dll
LoadedModule[78]=C:\Program Files\Shotcut\lib\qt5\imageformats\qjp2.dll
LoadedModule[79]=C:\Program Files\Shotcut\lib\qt5\imageformats\qjpeg.dll
LoadedModule[80]=C:\Program Files\Shotcut\lib\qt5\imageformats\qmng.dll
LoadedModule[81]=C:\Program Files\Shotcut\lib\qt5\imageformats\qsvg.dll
LoadedModule[82]=C:\Program Files\Shotcut\Qt5Svg.dll
LoadedModule[83]=C:\Program Files\Shotcut\lib\qt5\imageformats\qtga.dll
LoadedModule[84]=C:\Program Files\Shotcut\lib\qt5\imageformats\qtiff.dll
LoadedModule[85]=C:\Program Files\Shotcut\lib\qt5\imageformats\qwbmp.dll
LoadedModule[86]=C:\Program Files\Shotcut\lib\qt5\imageformats\qwebp.dll
LoadedModule[87]=C:\Program Files\Shotcut\lib\mlt\libmltavformat.dll
LoadedModule[88]=C:\Program Files\Shotcut\avcodec-56.dll
LoadedModule[89]=C:\Program Files\Shotcut\avutil-54.dll
LoadedModule[90]=C:\Program Files\Shotcut\avformat-56.dll
LoadedModule[91]=C:\Program Files\Shotcut\avdevice-56.dll
LoadedModule[92]=C:\Program Files\Shotcut\swscale-3.dll
LoadedModule[93]=C:\Program Files\Shotcut\libmp3lame-0.dll
LoadedModule[94]=C:\Program Files\Shotcut\libopus-0.dll
LoadedModule[95]=C:\Program Files\Shotcut\libx264-148.dll
LoadedModule[96]=C:\Program Files\Shotcut\libx265.dll
LoadedModule[97]=C:\Program Files\Shotcut\zlib1.dll
LoadedModule[98]=C:\Program Files\Shotcut\swresample-1.dll
LoadedModule[99]=C:\WINDOWS\SYSTEM32\AVICAP32.dll
LoadedModule[100]=C:\Program Files\Shotcut\avfilter-5.dll
LoadedModule[101]=C:\Program Files\Shotcut\SDL.dll
LoadedModule[102]=C:\WINDOWS\SYSTEM32\MSVFW32.dll
LoadedModule[103]=C:\Program Files\Shotcut\postproc-53.dll
LoadedModule[104]=C:\Program Files\Shotcut\lib\mlt\libmltcore.dll
LoadedModule[105]=C:\Program Files\Shotcut\lib\mlt\libmltdecklink.dll
LoadedModule[106]=C:\Program Files\Shotcut\lib\mlt\libmltfrei0r.dll
LoadedModule[107]=C:\Program Files\Shotcut\lib\mlt\libmltgtk2.dll
LoadedModule[108]=C:\Program Files\Shotcut\libgdk-win32-2.0-0.dll
LoadedModule[109]=C:\Program Files\Shotcut\libgdk_pixbuf-2.0-0.dll
LoadedModule[110]=C:\Program Files\Shotcut\libexif-12.dll
LoadedModule[111]=C:\Program Files\Shotcut\libglib-2.0-0.dll
LoadedModule[112]=C:\Program Files\Shotcut\libgobject-2.0-0.dll
LoadedModule[113]=C:\Program Files\Shotcut\libpango-1.0-0.dll
LoadedModule[114]=C:\Program Files\Shotcut\libpangoft2-1.0-0.dll
LoadedModule[115]=C:\Program Files\Shotcut\libcairo-2.dll
LoadedModule[116]=C:\Program Files\Shotcut\libintl-8.dll
LoadedModule[117]=C:\Program Files\Shotcut\libgio-2.0-0.dll
LoadedModule[118]=C:\Program Files\Shotcut\libpangocairo-1.0-0.dll
LoadedModule[119]=C:\Program Files\Shotcut\libgmodule-2.0-0.dll
LoadedModule[120]=C:\Program Files\Shotcut\libpng14-14.dll
LoadedModule[121]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.10240.16384_none_89a94c179af51f83\gdiplus.dll
LoadedModule[122]=C:\Program Files\Shotcut\libgthread-2.0-0.dll
LoadedModule[123]=C:\WINDOWS\SYSTEM32\MSIMG32.dll
LoadedModule[124]=C:\Program Files\Shotcut\libfreetype-6.dll
LoadedModule[125]=C:\Program Files\Shotcut\libfontconfig-1.dll
LoadedModule[126]=C:\Program Files\Shotcut\libpangowin32-1.0-0.dll
LoadedModule[127]=C:\Program Files\Shotcut\libexpat-1.dll
LoadedModule[128]=C:\WINDOWS\SYSTEM32\USP10.dll
LoadedModule[129]=C:\Program Files\Shotcut\lib\mlt\libmltjackrack.dll
LoadedModule[130]=C:\Program Files\Shotcut\libxml2-2.dll
LoadedModule[131]=C:\Program Files\Shotcut\libjackserver64.dll
LoadedModule[132]=C:\WINDOWS\system32\PSAPI.DLL
LoadedModule[133]=C:\Program Files\Shotcut\lib\mlt\libmltkdenlive.dll
LoadedModule[134]=C:\Program Files\Shotcut\lib\mlt\libmltmotion_est.dll
LoadedModule[135]=C:\Program Files\Shotcut\lib\mlt\libmltnormalize.dll
LoadedModule[136]=C:\Program Files\Shotcut\lib\mlt\libmltoldfilm.dll
LoadedModule[137]=C:\Program Files\Shotcut\lib\mlt\libmltopengl.dll
LoadedModule[138]=C:\Program Files\Shotcut\libepoxy-0.dll
LoadedModule[139]=C:\Program Files\Shotcut\lib\mlt\libmltplus.dll
LoadedModule[140]=C:\Program Files\Shotcut\libfftw3-3.dll
LoadedModule[141]=C:\Program Files\Shotcut\lib\mlt\libmltplusgpl.dll
LoadedModule[142]=C:\Program Files\Shotcut\lib\mlt\libmltqt.dll
LoadedModule[143]=C:\Program Files\Shotcut\lib\mlt\libmltresample.dll
LoadedModule[144]=C:\Program Files\Shotcut\libsamplerate-0.dll
LoadedModule[145]=C:\Program Files\Shotcut\lib\mlt\libmltrtaudio.dll
LoadedModule[146]=C:\WINDOWS\SYSTEM32\DSOUND.dll
LoadedModule[147]=C:\Program Files\Shotcut\lib\mlt\libmltsdl.dll
LoadedModule[148]=C:\Program Files\Shotcut\lib\mlt\libmltsox.dll
LoadedModule[149]=C:\Program Files\Shotcut\libsox-2.dll
LoadedModule[150]=C:\Program Files\Shotcut\lib\mlt\libmltvideostab.dll
LoadedModule[151]=C:\Program Files\Shotcut\lib\mlt\libmltvidstab.dll
LoadedModule[152]=C:\Program Files\Shotcut\libvidstab.dll
LoadedModule[153]=C:\Program Files\Shotcut\lib\mlt\libmltvmfx.dll
LoadedModule[154]=C:\Program Files\Shotcut\lib\mlt\libmltxine.dll
LoadedModule[155]=C:\Program Files\Shotcut\lib\mlt\libmltxml.dll
LoadedModule[156]=C:\Program Files\Shotcut\lib\mlt\mltwebvfx.dll
LoadedModule[157]=C:\WINDOWS\SYSTEM32\OPENGL32.dll
LoadedModule[158]=C:\Program Files\Shotcut\Qt5Declarative.dll
LoadedModule[159]=C:\WINDOWS\SYSTEM32\GLU32.dll
LoadedModule[160]=C:\WINDOWS\SYSTEM32\DDRAW.dll
LoadedModule[161]=C:\WINDOWS\SYSTEM32\DCIMAN32.dll
LoadedModule[162]=C:\Program Files\Shotcut\Qt5Script.dll
LoadedModule[163]=C:\Program Files\Shotcut\Qt5XmlPatterns.dll
LoadedModule[164]=C:\WINDOWS\SYSTEM32\cryptsp.dll
LoadedModule[165]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[166]=C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
LoadedModule[167]=C:\WINDOWS\system32\clbcatq.dll
LoadedModule[168]=C:\WINDOWS\system32\dataexchange.dll
LoadedModule[169]=C:\WINDOWS\system32\d2d1.dll
LoadedModule[170]=C:\WINDOWS\system32\d3d11.dll
LoadedModule[171]=C:\WINDOWS\system32\dcomp.dll
LoadedModule[172]=C:\WINDOWS\system32\dxgi.dll
LoadedModule[173]=C:\WINDOWS\system32\twinapi.appcore.dll
LoadedModule[174]=C:\WINDOWS\system32\USERENV.dll
LoadedModule[175]=C:\Program Files\Shotcut\lib\qml\QtQuick.2\qtquick2plugin.dll
LoadedModule[176]=C:\Program Files\Shotcut\lib\qml\QtQml\Models.2\modelsplugin.dll
LoadedModule[177]=C:\Program Files\Shotcut\lib\qml\QtQuick\Controls\qtquickcontrolsplugin.dll
LoadedModule[178]=C:\Program Files\Shotcut\lib\qml\QtQuick\Layouts\qquicklayoutsplugin.dll
LoadedModule[179]=C:\Program Files\Shotcut\lib\qml\QtQuick\Window.2\windowplugin.dll
LoadedModule[180]=C:\WINDOWS\system32\mswsock.dll
LoadedModule[181]=C:\Windows\System32\rasadhlp.dll
LoadedModule[182]=C:\Program Files\Shotcut\lib\qt5\sqldrivers\qsqlite.dll
LoadedModule[183]=C:\WINDOWS\System32\fwpuclnt.dll
LoadedModule[184]=C:\WINDOWS\system32\d3d9.dll
LoadedModule[185]=C:\WINDOWS\SYSTEM32\nvoglv64.DLL
LoadedModule[186]=C:\WINDOWS\system32\SETUPAPI.dll
LoadedModule[187]=C:\WINDOWS\SYSTEM32\WTSAPI32.dll
LoadedModule[188]=C:\WINDOWS\system32\WINTRUST.dll
LoadedModule[189]=C:\WINDOWS\SYSTEM32\ntmarta.dll
LoadedModule[190]=C:\WINDOWS\SYSTEM32\WINSTA.dll
LoadedModule[191]=C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.10240.16384_none_f41f7b285750ef43\comctl32.dll
LoadedModule[192]=C:\WINDOWS\SYSTEM32\WindowsCodecs.dll
LoadedModule[193]=C:\WINDOWS\SYSTEM32\edputil.dll
LoadedModule[194]=C:\WINDOWS\SYSTEM32\iertutil.dll
LoadedModule[195]=C:\WINDOWS\SYSTEM32\wintypes.dll
LoadedModule[196]=C:\WINDOWS\SYSTEM32\policymanager.dll
LoadedModule[197]=C:\WINDOWS\SYSTEM32\msvcp110_win.dll
LoadedModule[198]=C:\WINDOWS\SYSTEM32\XmlLite.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=shotcut.exe
AppPath=C:\Program Files\Shotcut\shotcut.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=0A025B65F8A90D5EA3E1D172985FAB63

**Comment by ddennedy** [comment]
I do not reproduce your problems. It seems like Shotcut is incompatible with your computer and drivers. That is the way it goes sometimes. I am not going to do anything about it.

**Comment by phr00t** [comment]
Switching from "Display Mode" from Automatic to "Direct X" seems to have improved initial stability, but haven't used it extensively to see if crashing has generally been resolved.

From one developer to another, offering a simple suggestion like updating drivers or trying a different display mode can go a long way over "I couldn't reproduce it; I'm not doing anything about it". I really enjoyed kdenlive on Linux, and I'm happy to see an MLT video editor coming to Windows.

**Comment by jmcgvr** [comment]
I get this same bug when I double-click a .mlt file after having associated them with shotcut. The workaround is to open shotcut first and open the file from inside. Double-click opening appears to end up giving mlt_service_connect_producer a null pointer when you try to add a video track:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	shotcut.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5613d68d
  Fault Module Name:	libmlt-6.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5613d176
  Exception Code:	c0000005
  Exception Offset:	000000000000d52c
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	66c4
  Additional Information 2:	66c41392c1e39816faa00c395f123ac3
  Additional Information 3:	a8c6
  Additional Information 4:	a8c60045a9bf3880d561b22fa7cd3f05

**Comment by ddennedy** [comment]
@jmcgvr That is not the same bug. You can open a new issue to track your problem, but be prepared to share a short project that reproduces it or the steps to reproduce it from scratch (empty project). I already tried to reproduce it on Windows 7 with no success so far.

**Comment by maloner** [comment]
I see the same issue when I use the attached mlt.

Also attached is the app Report.wer
[Report.zip](https://github.com/mltframework/shotcut/files/819741/Report.zip)

Faulting application name: shotcut.exe, version: 0.0.0.0, time stamp: 0x58b83c11
Faulting module name: ntdll.dll, version: 10.0.14393.479, time stamp: 0x5825887f
Exception code: 0xc00000fd
Fault offset: 0x00000000000379bf
Faulting process ID: 0x804
Faulting application start time: 0x01d295eb11a28564
Faulting application path: C:\Program Files\Shotcut\shotcut.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: a805d1fa-581f-4fdb-ae2a-3f4cb708b0b2
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket 120711407631, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: shotcut.exe
P2: 0.0.0.0
P3: 58b83c11
P4: ntdll.dll
P5: 10.0.14393.479
P6: 5825887f
P7: c00000fd
P8: 00000000000379bf
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1D10.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_shotcut.exe_eb7fb8f85b2349846fb9175f4a1d95f63f2177_cb799db7_082a3b95

Analysis symbol: 
Rechecking for solution: 0
Report ID: a805d1fa-581f-4fdb-ae2a-3f4cb708b0b2
Report Status: 0
Hashed bucket: ac7b6fbb40aecd93745c94ee2e5897bd


[goal_and_risk.zip](https://github.com/mltframework/shotcut/files/819738/goal_and_risk.zip)

**Comment by Klaus-Nomi** [comment]
Ddennedy wrote in November 2015 that he could not reproduce the problem.
Regrettably I can reproduce it.

I run Linux Mint 20.3

If I add a new audio-track in shotcut it is fine.
If I add a new video-track in shotcut it CRASHES immediately without warning.

I have been working with Shotcut under Windows for over a year and never
experienced such thing there. 

I cleaned all remains of Shotcut, then installed anew. And again, same mess as before.

I wonder if I am the only person who experiences this.

Bye, Klaus.
