### ISSUE TITLE
Motion Tracker not available in flatpak (Beta 23.04)

### ISSUE THREAD

**Issue by timlau** [mltframework/shotcut#1420]
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

The motion tracker filter is not availble in 23.904 Beta in the flatpak version, installed by
```
flatpak install --user https://dl.flathub.org/build-repo/15229/org.shotcut.Shotcut.flatpakref
```

![Screenshot from 2023-04-05 11-52-30](https://user-images.githubusercontent.com/283985/230086848-e1c220cd-2921-4f67-8073-6685902cb364.png)

**Comment by timlau** [comment]
I have compared the opencv files in the AppImage  and the flatpak

```
find .  -name *opencv*
./usr/bin/bin/opencv_version
./usr/bin/bin/setup_vars_opencv4.sh
./usr/bin/lib/cmake/opencv4
./usr/bin/lib/libopencv_core.so
./usr/bin/lib/libopencv_core.so.4.7.0
./usr/bin/lib/libopencv_core.so.407
./usr/bin/lib/libopencv_imgproc.so
./usr/bin/lib/libopencv_imgproc.so.4.7.0
./usr/bin/lib/libopencv_imgproc.so.407
./usr/bin/lib/libopencv_plot.so
./usr/bin/lib/libopencv_plot.so.4.7.0
./usr/bin/lib/libopencv_plot.so.407
./usr/bin/lib/libopencv_tracking.so
./usr/bin/lib/libopencv_tracking.so.4.7.0
./usr/bin/lib/libopencv_tracking.so.407
./usr/bin/lib/libopencv_video.so
./usr/bin/lib/libopencv_video.so.4.7.0
./usr/bin/lib/libopencv_video.so.407
./usr/bin/lib/mlt-7/libmltopencv.so
./usr/bin/share/licenses/opencv4
./usr/bin/share/mlt-7/opencv
./usr/bin/share/mlt-7/opencv/filter_opencv_tracker.yml
./usr/bin/share/opencv4

```
 none of these files is found in the flatpak

**Comment by ddennedy** [comment]
This is fixed now.
