### ISSUE TITLE
crash on start in flatpak beta : 23.04.05

### ISSUE THREAD

**Issue by timlau** [mltframework/shotcut#1421]
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).
Flatpak Linux 23.04.05.

Shotcut crash on start after the window layout has been changed and saved, check debug.md for details.
I have attached a good and a bad .conf file.
the diff is show in the picture bellow

[debug.md](https://github.com/mltframework/shotcut/files/11168910/debug.md)
[Shotcut.conf.zip](https://github.com/mltframework/shotcut/files/11168928/Shotcut.conf.zip)
![Screenshot from 2023-04-06 11-54-15](https://user-images.githubusercontent.com/283985/230342994-6c6a289f-d8b0-4f45-b36b-bd505a3a73d1.png)

**Comment by ddennedy** [comment]
Please provide more information about the layout change you made. Those conf values are generated by Qt, not us, and I don’t know how to read them. Also you wrote “saved. ” it normally just saves on exit. Did you do something special to “save?”

**Comment by ddennedy** [comment]
I copied the `windowState2` line from your `Shotcut.conf.broken` file into my config file and ran in the debugger, but it did not crash.

**Comment by timlau** [comment]
I can reproduce it in shotcut-linux-x86_64-230403.AppImage also

* download shotcut-linux-x86_64-230403.AppImage from github
* chmod +x shotcut-linux-x86_64-230403.AppImage
* rm $HOME/.config/Meltytech/Shotcut.conf
* ./shotcut-linux-x86_64-230403.AppImage
*  Maximize the window på double click on the titlebar
* close recent & histrory
* drag to audio peek meter to be as small as possible
* close shotcut to save config
* start shotcut again and it segfault

```
/tmp/.mount_shotcu2TD3BI/usr/bin//shotcut: line 21: 48892 Segmentation fault      (core dumped) bin/shotcut "$@"
```


![Screenshot from 2023-02-24 18-27-43](https://user-images.githubusercontent.com/283985/230551737-adfe71a2-f357-4b01-974d-65e065b51ee2.png)

**Comment by timlau** [comment]
Look like it is related to the maximized state.

* rm $HOME/.config/Meltytech/Shotcut.conf
* ./shotcut-linux-x86_64-230403.AppImage
* Maximize the window på double click on the titlebar
* close recent & histrory
* close shotcut to save config
* start shotcut again and it segfault

If i don't maximize it don't crash

I have attached a diif between the windowState2= lines in the maximized version (crash) and the un-maximized version (no crash)
[diff.txt](https://github.com/mltframework/shotcut/files/11176711/diff.txt)




[diff.txt](https://github.com/mltframework/shotcut/files/11176693/diff.txt)

**Comment by timlau** [comment]
My system
![image](https://user-images.githubusercontent.com/283985/230558191-fbd2526b-f8a8-4fb5-a5e4-548ffe059c6e.png)

**Comment by ddennedy** [comment]
Thanks for the detailed steps. For a while I was not able to find a workaround. I think this might be a bug in Qt. Switching the order of the two lines (layout vs. window size+pos) fixed it for some reason.
