### ISSUE TITLE
Deinterlacing changed framerate unexpected

### ISSUE THREAD

**Issue by DarkiStar** [mltframework/shotcut#1425]
System used:
Windows 10 - 16 GByte RAM - GTX 1060 6 GByte
Shotcut version 22.12.21

When I open an interlaced video file from my old Sanyo camera it shows a framerate of 59.940060 fps.

![Screenshot1](https://user-images.githubusercontent.com/23613040/231507107-144f68a9-e878-4fa0-90cb-29bcec9abcb8.png)

After converting with following settings:

![Screenshot2](https://user-images.githubusercontent.com/23613040/231507457-bca6e726-b65b-416e-9cae-144b3574f652.png)

and opening the new file, it shows a framerate of 119.880165 fps.

![Screenshot3](https://user-images.githubusercontent.com/23613040/231507616-1e3e6bd6-78da-4570-afd9-e33292f7a93a.png)

The deinterlacing worked perfectly (its progressive and looks good), but the framerate change was unexpected for me.
When I set the framerate in the convert dialog to the 59 fps (like the source) than the deinterlaced video has the 59 fps setting and everything is ok. The question is, why does it double the framerate without interaction?

Another problem (maybe specific to the sanyo cam files ... if I select the option "Convert to BT.709 colorspace"

![Screenshot4](https://user-images.githubusercontent.com/23613040/231508013-4433d15d-36d1-4194-8524-c08ff963d965.png)

Then there is no output but an error message that the convertion failed.

[Debug  ] <FfmpegJob::start> "D:/Downloads/PortableSoftware/Shotcut/ffmpeg -loglevel verbose -i E:/Videos/Klingenberg/Klingenberg/100SANYO/SANY0014.MP4 -max_muxing_queue_size 9999 -map 0:V? -map 0:a? -map_metadata 0 -ignore_unknown -vf bwdif,zscale=t=linear:npl=100,format=gbrpf32le,zscale=p=bt709,tonemap=tonemap=hable:desat=0,zscale=t=bt709:m=bt709:r=tv,format=yuv422p,scale=flags=accurate_rnd+full_chroma_inp+full_chroma_int:in_range=full:out_range=full -color_range jpeg -f matroska -codec:a pcm_f32le -codec:v utvideo -pix_fmt yuv422p -colorspace bt709 -color_primaries bt709 -color_trc bt709 -y C:/Users/Worker/Pictures/Shotcut_Interlace/SANY0014 - Konvertiert2.mkv" 
[Info   ] <AbstractJob::onFinished> job failed with 1

In the first picture it is shown, that the source file has the ITU-R BT.709 colorspace already.

Another problem is, that is seems to be impossible to batch convert files. And the convert dialog looses its settings after each conversation. It would be best that the last settings are persisted somehow.

regards

**Comment by ddennedy** [comment]
>  you could use FFProbe to see what the FFMpeg library reports for that file

Shotcut comes with this, and when you use Properties > menu > More Information.. it runs it for you. You can copy and paste its output here.

**Comment by ddennedy** [comment]
Here is the reason why the double the expected frame rate:
`avg_frame_rate=60000/1001`

Sanyo probably set something incorrectly. All of my interlace sources that work correctly (vast majority), it reports
`avg_frame_rate=30000/1001`

There are always going to be some interoperability problems like this that require manual correction.

**Comment by DarkiStar** [comment]
> Here is the reason why the double the expected frame rate: `avg_frame_rate=60000/1001`
> 
> Sanyo probably set something incorrectly. All of my interlace sources that work correctly (vast majority), it reports `avg_frame_rate=30000/1001`
> 
> There are always going to be some interoperability problems like this that require manual correction.

But as I remember, I set the framerate in the camera to 60 fps. So I think the metadata is correct. I was not complaining about the 59 fps of the source file but the (to me) unexpected 120 fps after deinterlacing which is the expected behaviour regarding to the comment from @bmatherly 

So I think this issue can be closed ... the batch conversation is more a feature request and the failed color space conversion (because it is not nessecary) is only a small issure.

Thank you for taking time to look into this ....

regards

**Comment by ddennedy** [comment]
I see. That is odd: I have never run across a 60 interlaced video like yours. :-) Shotcut can do deinterlace in realtime if you do not need to increase the frame rate. 60 fps interlace is actually 120 Hz since the field (half the lines of a frame) rate is 120 fields/second. The convert dialog is how Shotcut provides a deinterlace that retains the full frequency by doubling frame rate. But you can override that behavior in case you want to pre-convert to something optimal for your project. In that case, the 601 to 709 conversion should be working too.

**Comment by DarkiStar** [comment]
> I see. That is odd: I have never run across a 60 fps interlaced video like yours. :-) Shotcut can do deinterlace in realtime if you do not need to increase the frame rate. 60 fps interlace is actually 120 Hz since the field (half the lines of a frame) rate is 120 fields/second. The convert dialog is how Shotcut provides a deinterlace that retains the full frequency by doubling frame rate. But you can override that behavior in case you want to pre-convert to something optimal for your project. In that case, the 601 to 709 conversion should be working too.

But according to my first screenshot the source had the 709 colorspace already (not 601). Or do I miss something?

I have a lot of videos taken with that camera. Now I deinterlace them one by one (have to repeat all settings every time :-) ) and try to save them lossless. But the resulting files are huge!!! .... Not sure if there is a better way ...

**Comment by bmatherly** [comment]
> But as I remember, I set the framerate in the camera to 60 fps. 

Can you also set the mode to "progressive"? I would question whether these files are really interlaced. If you do not deinterlace, do you see an interlaced combing effect?

**Comment by DarkiStar** [comment]
> > But as I remember, I set the framerate in the camera to 60 fps.
> 
> Can you also set the mode to "progressive"? I would question whether these files are really interlaced. If you do not deinterlace, do you see an interlaced combing effect?

The files are really interlaced. I can clearly see an interlaced combing effect in the source files (especially in camera pans). And deinterlacing in shortcut does a very good job to eliminate that effect!

I am not sure if the cam has an progressive mode, but I doubt it. I do not have it laying around to do a quick test.

regards
