### ISSUE TITLE
Chroma bug for interlaced 4:2:0

### ISSUE THREAD

**Issue by Sharc99** [mltframework/shotcut#1428]
Shotcut Beta 23.04.03, Windows 11.
Source is 4:2:0 interlaced video.
Exporting to x264 YV12 4:2:0 works correctly _when no (color) filters are enabled_. Chroma motion is in line with the field motion, i.e. when stepping through the fields the chroma moves in line with the fields.
However, when enabling the color grading filter (or the white balance filter ) the chroma temporal movement is halved. Means the chroma advances temporally only with every 2nd field i.e. at the framrate rather than at the field rate. It is visible as chroma tearing. And there is also chroma bleeding between fields when color filters are enabled (without doing any adjustments).
I think this is a bug.

Edit:
Maybe it's because the color filters make a YUV to RGB conversion without accounting for interlaced video? Just my speculation though.

**Comment by Sharc99** [comment]
Thank you for the new Release Candidate. Doing some more tests with 23.04.20 RC:
For interlaced 4:2:0 sources, some filters like white balance, color grading, contrast, HQ3N3D, sharpen .... still cause chroma bleeding between fields and chroma motion flaws in x264 interlaced YV12 (4:2:0) exports.
The remedy is to avoid 4:2:0 interlaced sources or convert these to RGB, 4:4:4 or 4:2:2 beforehand, or deinterlace them. It's ok, but one has to be aware of the issue, or otherwise one may get bad surprises when viewing the results carefully.

**Comment by bmatherly** [comment]
Thanks for your report. Can you please help me reproduce the issue by providing the following:
1) An example file (4:2:0 interlaced)
2) A simple example project that uses the clip
3) A screenshot that shows the before and after chroma (so I know what to look for specifically).

It would also be helpful for me to know what tool you are using to inspect the pixels.

Thanks

**Comment by Sharc99** [comment]
Thank you for taking a look.
Attached a .zip with 5 clips which should demonstrate the issue. Explanations are found in the Readme.txt. I hope it helps.
In case you have some doubts or need more info please let me know.
Thanks
[Shotcut Chroma Bug.zip](https://github.com/mltframework/shotcut/files/11303363/Shotcut.Chroma.Bug.zip)

**Comment by bmatherly** [comment]
I have a proposed fix in this MLT pull request: https://github.com/mltframework/mlt/pull/909

**Comment by Sharc99** [comment]
Thank you.
Glad you could verify my issue.
