### ISSUE TITLE
Move track with mouse, make all video black 

### ISSUE THREAD

**Issue by timlau** [mltframework/shotcut#1429]
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).
Fedora Linux 38, Flatpak Shotcut 23.04.07

When I move a track with the mouse all video turns black, when i save and reload the project, it is back to normal
![Screenshot from 2023-04-20 15-18-26](https://user-images.githubusercontent.com/283985/233379948-1bb754ba-af39-4fef-8912-7200493e0af6.png)

![Screenshot from 2023-04-20 15-19-06](https://user-images.githubusercontent.com/283985/233379982-dd6cda83-feb8-43b8-a845-348c370c5d3e.png)

**Comment by timlau** [comment]
Also happen when i use the keyboard shortcuts to move track

**Comment by timlau** [comment]
Added simple projects with 3 color clips with SPR filters on 3 tracks to reproduce the issue
[Bug_Track_move.zip](https://github.com/mltframework/shotcut/files/11286893/Bug_Track_move.zip)

**Comment by bmatherly** [comment]
Thanks for your report and test case. I recreate this and will look into it.

**Comment by bmatherly** [comment]
This is fixed for the next release.
