### ISSUE TITLE
Re-arranging the order of filters getting locked up

### ISSUE THREAD

**Issue by Sharc99** [mltframework/shotcut#1431]
RC 23.04.20, Windows 10
The filter order of the selected video filters sometimes becomes locked. Selecting and shifting the filters up/down doesn't work. I did not find a systematic condition as to when and why this may happen.

**Comment by ddennedy** [comment]
As a workaround click the X icon below the list of filters to deselect and try again.
This bug report needs the detail of steps to reproduce it.

**Comment by Sharc99** [comment]
Thanks . I will come back when I find a reproducible condition or workflow as to when this happens.
