### ISSUE TITLE
Buzzing sound is added to some of my clips

### ISSUE THREAD

**Issue by Mutusen** [mltframework/shotcut#1433]
Hi, I'm using version 22.12.21 on Linux Mint 21.1. Shotcut adds an awful buzzing sound to some of my video clips, both in preview and when exporting the video, even though I am pretty sure the buzzing sound does not exist in my video clip (no buzzing sound when I open it with a video player, and there is no problem with Shotcut 22.06.23). 

All the problematic clips were shot with an Akaso V50 camera. I'm attaching an example of such a clip, if someone with a similar configuration wants to try to open it with Shotcut.

https://user-images.githubusercontent.com/47037331/235310838-e61ad2ca-14e6-42be-a948-670eaafbb6e7.MP4

**Comment by bmatherly** [comment]
Thanks for providing the test clip. I recreated the buzzing sound in 22.12.21. When I play it with debug messages turned on, I see this repeated message:
```
[aac @ 0x55555c2facc0] ChannelElement 1.0 missing 
[aac @ 0x55555c2facc0] ChannelElement 0.1 missing 
[aac @ 0x55555c2facc0] ChannelElement 1.0 missing 
```
I wonder if there is an error in the stream or an unsupported codec feature being used. 

I was not able to recreate the buzzing in our latest nightly build. Would you be willing to try your test with this nightly build?
https://github.com/mltframework/shotcut/actions/runs/4837711852

Also, I notice in my testing that sound only appears in the left channel. If you are making a stereo project and want sound in both channels, you can use the Channel Copy filter.

![image](https://user-images.githubusercontent.com/821968/235327873-834f9f95-bec5-4499-ae37-630725dc4d45.png)

**Comment by Mutusen** [comment]
Thank you for your answer. Unfortunately it doesn't change anything when I try with this build (but with the added bug that I see nothing in the timeline when I open an old project). How can you turn on debug messages? I didn't find this option.

**Comment by ddennedy** [comment]
As a workaround, use Properties > Convert. We cannot make Shotcut work with every media file in existence. Some things are not going to work good, and the convert process helps take care of many but still not all.

> nothing in the timeline when I open an old project

I have not seen this, and none of our other testers reported it.

There is no option to turn on debug messages. You only get that when you make a custom debug build as a developer would.

**Comment by bmatherly** [comment]
> As a workaround, use Properties > Convert.

When I tried this with 22.12.21, the buzzing became encoded in the converted file. But I was not able to recreate the buzzing with the beta build. So maybe there is some other factor (project setting, etc) that I have not figured out.

**Comment by docent27** [comment]
I'm using Linux Mint 21.1 and can't hear any buzzing sounds. Shotcut 12.22.21 flathub version.

**Comment by ddennedy** [comment]
Bug is specific to FFmpeg version and this clips' encoding. We have since upgraded to new major version of Shotcut so this is expired.
