### ISSUE TITLE
23.04.20 RC crashing when Windows puts the monitor to sleep

### ISSUE THREAD

**Issue by andrewk8** [mltframework/shotcut#1435]
23.04.20 RC on Window 10 22H2.  AMD 3700X. B550, 32 GB, NVidia GTX 1660. Dual monitor.  Up-to-date on all updates and drivers.

I've been queuing up several encodes.  SC has crashed on me several times while running queued jobs.  It's repeatable, but I am not able to pinpoint the conditions where you can trigger it on demand.

Steps:
- Run SC in a different virtual desktop (not required?  SC seems to crash even when you don't switch away from the desktop where it was launched)
- Add several (5?) encodes to the job queue
- Let the computer run unattended

The computer is a desktop.  I have sleep / hibernate disabled. It turns off the screens after 15 minutes.

The last time this happened, I moved the mouse to wake the screens up.  Shotcut was gone.  The previous melt.exe encode process was still running and finished to completion.  The Windows Event Viewer captured the crash.

Not sure whether the screens turning off or not is necessary.  The issue seems to happen when there are more than 3 encodes in the job queue and you leave the computer unattended.

[Report.txt](https://github.com/mltframework/shotcut/files/11365732/Report.txt)

![image](https://user-images.githubusercontent.com/16465258/235459746-5128499c-82b5-482b-829c-63b1d16efea5.png)

![image](https://user-images.githubusercontent.com/16465258/235459784-c4ac9260-a7e7-4bbd-84a0-a7393891979a.png)

**Comment by andrewk8** [comment]
Update:  I set my monitor to go to sleep after 2 minutes.  I queued up 3 jobs and stopped using the computer.  After it turned off the monitor, I let it run for a minute or two before checking.  When I moved the mouse to wake up the monitor, SC was gone.  The melt.exe process was still running the first encode, and it ran to completion.

the issue seems less about how many jobs are in the queue than the interaction between the GUI and Windows power management.

![image](https://user-images.githubusercontent.com/16465258/235465686-180ea358-06fc-4b52-b50e-c3bf0a074559.png)

**Comment by ddennedy** [comment]
I reproduced it just by having a project loaded without doing any exports and single monitor.

**Comment by ddennedy** [comment]
I am no longer reproducing this on today's daily build at https://github.com/mltframework/shotcut/actions/runs/4869622007

Can you please retest this to confirm?

**Comment by andrewk8** [comment]
Seems to be working fine.

**Comment by ddennedy** [comment]
Thank you
