### ISSUE TITLE
Track names always have ellipsis regardless of length

### ISSUE THREAD

**Issue by AhNesh** [mltframework/shotcut#1437]
Windows 10.0.19045
Shotcut version 22.12.21

Track names always have ellipsis. Here are two tracks, one named 'abc' and the other named 'abcdefghjklmnop'; both have more space, but both have ellipsis.

![image](https://user-images.githubusercontent.com/33862238/236528522-79b3960f-e0e2-4c42-b402-e5400aab3798.png)

**Comment by ddennedy** [comment]
This is already fixed for the next version which improves support for fractional display scale on Windows. You can read about this [here](https://shotcut.org/blog/beta/), but you might just want to wait for the release, which is probably within a week.
