### ISSUE TITLE
Fix g+/forum link

### ISSUE THREAD

**Issue by qubodup** [mltframework/shotcut#144]
Hi,

http://www.shotcut.org/bin/view/Shotcut/DiscussionForum

links to 

https://plus.google.com/u/0/b/116966741191547003590/communities/111984976401772983232

which is a 403

**Comment by ddennedy** [comment]
works for me

**Comment by bmatherly** [comment]
Doesn't work for me, either:

"403. That’s an error.
We're sorry, but you do not have access to this page. That’s all we know."

**Comment by bmatherly** [comment]
This link does work for me:

https://plus.google.com/communities/111984976401772983232

**Comment by ddennedy** [comment]
Thanks, Brian. I updated the page. Takes up to 48 hours to update cache.
