### ISSUE TITLE
Bug on export with new Shotcut v23.05.07

### ISSUE THREAD

**Issue by Ticrob** [mltframework/shotcut#1442]
Hi,

My OS : Kubuntu 22.04.2 LTS / Kernel : 5.19.0-41 / KDE Plasma 5.24.7
Bug with Shotcut v23.05.07 (there is no the same bug with Shotcut v22.12.21 for exactly the same event)

I have made a cut with two MP4 videos (Timeline V1). For some parts of the two videos, I have used "Ripple deleted". The only effect I have used was  to merge the end of the first video with the begining of the second one (sorry I don't know the english word for this effect).
A the end of my cut, I have exported to MP4 format. The export was "succeed" but when I watch the video, only the first video was exported. I have tried the same process with MP4 converted video (as recommanded by shotcut). The result was the same.
Before upgraded shotcut from v22.12.21 to v23.05.07 I never had this issue. Then I decided to save my project and to downgrade Shotcut to v22.12.21. I opened my project and proceed to the export. This time the video contains all my final cuts.
Don't hesitate if you need more informations.
Regards,
Krzyzstof

**Comment by ddennedy** [comment]
I do not reproduce this. What build/package are you using?

**Comment by Ticrob** [comment]
https://github.com/mltframework/shotcut/releases/download/v23.05.07/shotcut-linux-x86_64-230507.txz
Is it what you ask ?

**Comment by Ticrob** [comment]
If you want I can upload on my Mega space the 2 videos and the "mlt" project ?

**Comment by ddennedy** [comment]
Yes ok

**Comment by Ticrob** [comment]
https://mega.nz/file/ftkDATTI#An632Dxo_vSYTQ8aBumznj-eGMHq8-sy_HeQiASCAe4

**Comment by ddennedy** [comment]
FYI Your project does not refer to the included, converted videos. It refers to the originals before conversion. 

After I export, it looks exactly like the project, which is nearly 2 minutes long.

https://github.com/mltframework/shotcut/assets/1146683/2e72201a-f782-4ff2-9d54-459c10f8451e

Here you can see I put the exported video on the timeline on a track above the normal timeline:

![image](https://github.com/mltframework/shotcut/assets/1146683/3a9d7959-65fd-4547-9a5f-fc137fb2510c)

**Comment by ddennedy** [comment]
To further test, I re-converted each of the timeline videos to the "better" level .mov files. Then, I exported that, and it worked exactly as before.

**Comment by ddennedy** [comment]
To start Shotcut, are you running `Shotcut.app/bin/shotcut`?

**Comment by Ticrob** [comment]
Ok for the mlt files, I have made a mistake when I sent it to you. But if I started again to fresh (converted or not), I have always the same issue on my laptop. Shotcut application is located there :
/home/christophe/Applications/Shotcut/
and launched with :
/home/christophe/Applications/Shotcut/Shotcut.app/shotcut
I have completly erased the shotcut folder, and I have tried again with unzipping v23.05.07 : the bug appears. 
Then, I have erased the folder again, unzip v22.12.21 : it works ! I can't explain why ?

**Comment by ddennedy** [comment]
Are you exporting with hardware encoder? Try without and using default export options.

**Comment by Ticrob** [comment]
Ok, I will try...but tomorrow cause it's quiet late and I have to wake up early. I keep you in touch. Thank you for your help ;)

**Comment by Ticrob** [comment]
The first time I was faced with this problem I had only the two only original videos. Face to this issue I have tried next to convert the videos. Then for me the issue is not related to my mlt file. Nevertheless, could you sent me your mlt repaired file in order I try on my PC ? I will try to restart from scratch this cut too.

**Comment by Ticrob** [comment]
Right. If I disable audio it works now.
If I sum up on V.23.05.07 I have to disable audio to export a video not including audio track ; on v22.12.21 no need to do it.
Is it a bug or it will be now the process to apply in the future ?

**Comment by ddennedy** [comment]
It is a bug.

**Comment by bmatherly** [comment]
Fixed here: https://github.com/mltframework/mlt/commit/77be3ee97453c194006df9080504492a67c8915b
