### ISSUE TITLE
Importing MLT as Clip crashes when GPU Effects enabled

### ISSUE THREAD

**Issue by oatycreates** [mltframework/shotcut#1443]
Hi, I've encountered this crash when trying to use another MLT project as a clip in a project that has GPU Effects enabled. Originally observed in **Shotcut v23.05.07** and again in **v23.05.14**. Tested on Windows and Mac.

**Workaround (General):** Render the clip MLT to a video file and embed that instead for now. Slight quality hit from the extra encode and likely has issues with transparency for doing overlays (chroma key instead?).

**Workaround (Windows):** Drag a CPU Effects MLT onto Timeline. Seems stable and persists through save/reload. Also seems to export and playback correctly (Codec: h264_nvenc .mp4)
**Update 2023-05-23:** This workaround seems patchy sadly, the same test imported CPU Effects clip was just crashing on a ~20 min long GPU Effects project with plenty of cuts/filters/transitions.

**Project setup:** The crash seems to happen for fresh project files saved with the respective GPU Effects setting on or off. In my case I was testing with a simple project with a PNG with simple GPU *Size & Position* filter. Importing simple 20s duration GPU or CPU Effects projects as clip that both contain the same image, proxied video, and audio with respective CPU/GPU filters.

The crashes seem to be silent, Shotcut either closes immediately or manages to put the clip onto the Timeline or Playlist then stops accepting input and closes shortly after. When adding to Timeline it seems to at least get up to starting the process of generating an audio waveform according to the log.

---

-**Windows 10 22H2**-

GPU: Nvidia RTX 2060.

**In GPU Effects mode:**

* Drag GPU MLT onto Playlist -> Crash
  * Adding via Playlist - Add Files menu -> Crash
* Drag GPU MLT onto Timeline -> Crash
* File - Open XML MLT as Clip (GPU project) -> Loads and plays as Source
  * Append that Clip to Timeline -> Crash
  * Append that Clip to Playlist -> Crash

**Importing CPU Effects MLT into GPU Effects Project:**

* Drag CPU MLT onto Playlist -> Crash
* Drag CPU MLT onto Timeline -> Seems to work and allow playback? Survives saving and loading project
* File - Open XML MLT as Clip (CPU project) -> Shows 'Disable GPU Effects?' dialog

-**MacOS Ventura v13.3.1**-

GPU: Intel Iris Plus 650 integrated graphics. Macbook Pro 2017.

**In GPU Effects mode:**

* Same behaviour as Windows above, though workaround of dragging a CPU MLT onto Timeline crashes instead

---

Outside of this crash the GPU Effects feature seems to improve performance a bunch for my Windows machine especially with filters across multiple layers. Big thanks to everyone who has contributed to it!

**Comment by ddennedy** [comment]
This is fixed for the next version, but in doing so I added a requirement that the video mode of the inner and outer projects must match. The only exception to that is when you are using automatic video mode in the outer project and the first thing you add is another MLT XML with GPU Effects (either using File > Open MLT XML as Clip or drag-n-drop to playlist).

**Comment by oatycreates** [comment]
Thanks for looking into this issue, much appreciated! Those project CPU/GPU Effect mode requirements makes sense as well. I'll keep an eye out for any other issues with this new GPU workflow. Thanks again, it's been a big improvement so far!
