### ISSUE TITLE
Chroma bug for 4:2:0 interlaced UTVideo sources

### ISSUE THREAD

**Issue by Sharc99** [mltframework/shotcut#1444]
Shotcut 23.05.14, Windows 11.

Attached 2 files, both 4:2:0 interlaced sources.
- For the ffv1_420i.mkv the chroma is handled correctly (resolved issue #1428) when exporting to x264 YV12 interlaced. All OK.
- For the utvideo_420i.mkv there is still chroma blending between fields when exporting to x264 YV12 interlaced, although the source properties are recognized correctly by Shotcut, and I can't see a problem with the utvideo source. So probably a bug?
[420i.zip](https://github.com/mltframework/shotcut/files/11496294/420i.zip)

Edit: 
I suspect the culprit is the UTVideo codec ULY0 which does not support _interlaced_ 4:2:0 correctly? The stream is flagged progressive (although being reported as interlaced by MediaInfo and Shotcut properties.) So maybe it is beyond the influence of Shotcut  although ffmpeg commandline can encode and flag it correctly as interlaced 4:2:0 YV12 (x264) without chroma blending.

**Comment by bmatherly** [comment]
Thanks you for the report and the example files. I am able to reproduce the problem.

As a workaround, you can set "mlt_image_format=yuv420p" in the Other tab of the advanced export settings. This can be a generally good thing to do since it can save a conversion step.

![image](https://github.com/mltframework/shotcut/assets/821968/fdc7be1d-abec-40c2-ae5d-55ecf5c0dd12)

**Comment by Sharc99** [comment]
Glad you could reproduce the case. I was afraid that I may have missed something. Thanks for the workaround. I think this will solve the same issue with other codecs. 
Specifying the pixel format was the solution I found for the ffmpeg commandline as well.

**Comment by bmatherly** [comment]
This should be fixed now. See here: https://github.com/mltframework/mlt/commit/dcd7e617a452939dfdaa9acd58222eeddda6bc29

**Comment by Sharc99** [comment]
Great. Thank you.

**Comment by Sharc99** [comment]
The workaround solves the problem for utvideo source. However when I keep that "mlt_image_format=yuv420p" the chroma bleeding reappears for the ffv1 codec. So the issue is flipped it seems.
Should I therefore insert the "mlt_image_format=yuv420p" for the utvideo (and similar) only but remove it for ffv1?
Will the fix for the next release solve the issue for both formats?
I am currently on Shotcut 23.05.14, Windows 11.

**Comment by Sharc99** [comment]
All solved with version 23.06.14. Thank you.
