### ISSUE TITLE
Key framing causes an instant crash

### ISSUE THREAD

**Issue by Delocop** [mltframework/shotcut#1446]
Haven't used Shotcut in a long while so I can't tell if this is caused by the latest version or ones that precede it however making a key frame out of any filter property seems to crash the program instantly.

https://github.com/mltframework/shotcut/assets/127618333/0bc360c9-dcd5-4a91-9ca3-5d58d47e66fa

**Comment by ddennedy** [comment]
You did not specify your version as requested.   Your description is something so basic (and not reproducible) that it means you probably made a bad install. Reboot and reinstall that order.

**Comment by Delocop** [comment]
I apologize for that, I was using the latest release v23.05.14 however rebooting and reinstalling as you instructed worked.
Thanks for the help and once again I apologize for making this post!

**Comment by ddennedy** [comment]
I’m glad that worked. A number of people have had various problems solved by a clean reinstall. The installer is supposed to warn you when it is unable to update a file.
