### ISSUE TITLE
Installer Not Working

### ISSUE THREAD

**Issue by Czdam0** [mltframework/shotcut#1449]
Description:
I am experiencing issues with the installer for Shotcut. The installation process is not working as expected, and I would like to report this defect.

Operating System: windows 11Release Preview

Shotcut Version: all

Steps to Reproduce:

Download the Shotcut installer on windows 11 Release Preview.
Run the installer executable.

Expected Behavior:
Install window opens

Actual Behavior:
no window opens

Please let me know if you need any further information. Thank you for your attention to this matter.

**Comment by ddennedy** [comment]
Maybe this is the same as #1230

**Comment by ddennedy** [comment]
Was Mandatory ASLR enabled for you?
