### ISSUE TITLE
Link to github issues

### ISSUE THREAD

**Issue by qubodup** [mltframework/shotcut#145]
Assuming you want bug reports to be filled by non-developers, it should be easier for people to find this issues list.

You could add a link to http://www.shotcut.org/bin/view/Shotcut/DiscussionForum saying bugs should be reported here.
You could add 'bugs' sidebar link.

**Comment by ddennedy** [comment]
This was added to the forum page. You can see it on un-cached version of the page here: http://shotcut.org/bin/view/Shotcut/DiscussionForum
Accessing it through www. accesses a cache that will take up to 48 hours to update.

**Comment by qubodup** [comment]
Thanks! What's your policy on feature requests? Is there a place for them or not?

**Comment by ddennedy** [comment]
No features requests.
