### ISSUE TITLE
Segfault with GPS-Filter in Version 23.05.14

### ISSUE THREAD

**Issue by TheRaven500** [mltframework/shotcut#1450]
There is a Segfault in v23.05.14, it works with v22.12.21.
How to reproduce:
Open a video and add GPS filter (graphic or text, both are affected). Now click the "Open file" button. Before selecting a file, shotcut crashes with a segfault.
OS: Linux Mint 21.1
Shotcut-Version: 23.05.14 AppImage
If more informations or logs are needed, just let me know.

**Comment by ddennedy** [comment]
This is a known problem in the AppImage only that was already fixed in 1a141b3. The portable and Flatpak do not have this problem.

**Comment by ddennedy** [comment]
Actually, all you need to do is download the AppImage that was re-upload on May 26 with this fix. The version did not change since it was simply a packaging change.

**Comment by TheRaven500** [comment]
Thank you very much for the fast answer and solution! I will try it ASAP.
