### ISSUE TITLE
Missing libSDL

### ISSUE THREAD

**Issue by allesan** [mltframework/shotcut#1453]
I tried upgrading to 23.06.14 and I'm having problem starting Shotcut because I get error that libSDL is missing. I'm using portable version.
The same thing is happening with every QT 6 package, but not with older QT 5 releases.
I'm executing shotcut from terminal, bash script, not the binary.

What could be wrong?

**Comment by ddennedy** [comment]
What is your Linux distro and version?

**Comment by allesan** [comment]
Gentoo Linux, fully up to date.

**Comment by ddennedy** [comment]
`libSDL2-2.0.so.0` is included. Maybe it does not work properly on your system for whatever reason. I do not use Gentoo and do not want to learn it. Maybe you want to delete the bundled copy and use the one installed by Gentoo. Or, you can 
```
cd Shotcut.app
source source-me
ldd lib/mlt-7/libmltsdl2.so
```
and see what is missing. It is normal and expected that some libs are provided by the distro.

**Comment by allesan** [comment]
It lists wayland libs as missing.

	libwayland-egl.so.1 => not found
	libwayland-client.so.0 => not found
	libwayland-cursor.so.0 => not found

**Comment by allesan** [comment]
Hm, it works with wayland libs installed.

**Comment by ddennedy** [comment]
The libs are intentionally not bundled. I added them to the following page linked from our download page: https://shotcut.org/notes/linux-dependencies/
