### ISSUE TITLE
after v22.12.21, there is a new bug

### ISSUE THREAD

**Issue by kli2013** [mltframework/shotcut#1454]
when i use v23.06.14, 'source'→  'crop source'  → automatic,  the video can't fill the new video mode

v22.12.21 is ok

**Comment by ddennedy** [comment]
FYI that is not really a feature.

**Comment by ddennedy** [comment]
If you are looking to crop video, and export to the cropped dimensions it does not work in v22.12 either. It does something different but not correct. This unexpected sequence of actions (i.e. the non-feature) broke much earlier when Crop: Source changed to be  compatible with preview scaling. A supported way to export to cropped dimensions is on the road map.

**Comment by kli2013** [comment]
I just want to quickly get a new video mode, and I don't want to manually calculate and customize it, which would waste too much time

In the new video mode, I will click on the project → size, position&otate filter'

It works very well

You don't understand my question

Look at my example
https://www.youtube.com/watch?v=GavEy3Q_5pE

**Comment by kli2013** [comment]
> FYI that is not really a feature.

open my issues

**Comment by ddennedy** [comment]
A weird sequence of actions that yields a useful result is not a feature that is supported and will always work as the software changes to improve. You are not entitled to have the software changed by us to meet your needs, and you can cannot tell me what to do. You can submit a pull request with the code changes to make this work again. Do not continue to bother and make demands, or I will simply block you.
