### ISSUE TITLE
Hardware encoder for AV1 not used even if enabled

### ISSUE THREAD

**Issue by blacktowel** [mltframework/shotcut#1460]
When ticking the "Use hardware encoder" checkbox with an AV1 export preset selected nothing happens. It still uses a CPU encoder even if a hardware encoder would be available.

Clicking on the "Configure" button
![](https://github.com/mltframework/shotcut/assets/124326167/fb6de331-6760-44d3-92c7-c2ca322a7740)
brings up a window showing hardware encoders for h264 and hevc, but av1 is falsely missing.
![](https://github.com/mltframework/shotcut/assets/124326167/86c180cd-b905-4eec-8d40-82607303ed1e)
Even tho it is supported (by ffmpeg and the GPU).

When manually selecting the encoder it is available:
![](https://github.com/mltframework/shotcut/assets/124326167/ee8b57cb-742e-4bac-ac9f-e5575983ddbb)
But does not get automatically selected even if "Use hardware encoder" is on.

Shotcut version: 23.06.14

**Comment by ddennedy** [comment]
> showing hardware encoders for h264 and hevc, but av1 is falsely missing

It is only supported on Windows at the moment.

**Comment by ddennedy** [comment]
I do not integrate a hardware codec until I have the supporting hardware to make settings tweaks where required and be able to verify it works and continue to do so. (I only have RTX 3060).

**Comment by ddennedy** [comment]
This is added in 274ccf09f41c5db9c3df839d75c16f857748632c for the next version.

**Comment by ddennedy** [comment]
@blacktowel I received an e-mail where you wrote

> AV1 quality levels go down to 63. But the av1 nvenc encoder bottoms out at 51:
[image.png (view on web)](https://github.com/mltframework/shotcut/assets/124326167/77fa66e1-4369-488a-b86d-4f5501a1f43d)

But I am unable to locate that comment! If you believe you are correct, where is your evidence other than libaom or SVT? The [FFmpeg source code](https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/nvenc.c#L798) shows [0, 255] is the range for av1_nvenc!
```
static av_cold void set_constqp(AVCodecContext *avctx)
{
    NvencContext *ctx = avctx->priv_data;
    NV_ENC_RC_PARAMS *rc = &ctx->encode_config.rcParams;
#if CONFIG_AV1_NVENC_ENCODER
    int qmax = avctx->codec->id == AV_CODEC_ID_AV1 ? 255 : 51;
#else
    int qmax = 51;
#endif
```

**Comment by ddennedy** [comment]
Ok well it still caused me to fix a bug in this area for next version.

**Comment by ddennedy** [comment]
Shotcut was a fairly early adopter of NVENC, and there was a time when hardware or driver did not support CQ. I think that time has largely passed now especially with our updated minimum driver version.

**Comment by ddennedy** [comment]
>  what is the range of CQ for AV1?

from `ffmpeg -h`
```
-cq                <float>      E..V....... Set target quality level (0 to 51, 0 means automatic) for constant quality mode in VBR rate control (from 0 to 51) (default 0)
```
It is the same for hevc_nvenc and h264_nvenc.

**Comment by ddennedy** [comment]
I am using `-cq` now. The fact that 100% in our UI gives you cq=0, which is automatic and not lossless is a quirk feature of NVENC that I will not address. 100% does not mean lossless in Shotcut, and many codecs do not have lossless. Other parameters are required for lossless, which is why there is a category for lossless presets.

**Comment by ddennedy** [comment]
We hide this parameter in a section labeled "Advanced" for a reason. I am not doing anything about it, but you can submit a pull request with your code change for this.
