### ISSUE TITLE
Font Size Error

### ISSUE THREAD

**Issue by devtonic-net** [mltframework/shotcut#1463]
So I'm trying to create a text title by doing "Menu - > Open other -> Text". All is well until I select a huge font size, like 400px. Because the preview box is trying to show me "live" how the 400 px letters will look like, the OK/Cancel buttons are getting pushed "under" the monitor, so that there is no way to actually use the feature whenever I am trying to use a large font.

Also, whenever I try to edit the font (let's say, editing the text from a lower third created with the method as described above, I have to choose the font all over again, Shotcut does not seem to have any "memories" for that. Am I wrong, maybe?)

That's it, so far.

**Comment by bmatherly** [comment]
Which OK/Cancel buttons are you referring to? Can you provide a screenshot to show our problem?

**Comment by devtonic-net** [comment]
Hi there,
Please see this screenshot, it's the "normal" view, with the "Select font" window open, font size 60 -> https://snipboard.io/yTo1WP.jpg
And then this screenshot, with the distorted view and the buttons pushed beneath the visible part after selecting font size 400 -> https://snipboard.io/6v70sP.jpg
Now, the only option is to hit escape and start all over with the title creation.
Hope this helps.

**Comment by bmatherly** [comment]
Thank you for the screenshot. That is helpful. Unfortunately, in this case, Shotcut is using the font dialog provided by your desktop environment (Ubuntu). We do not have any control over how it is displayed. You would need to report this bug to Ubuntu and see if they can fix it.

**Comment by devtonic-net** [comment]
Thank you for the explanation. Glad to know where the problem is, actually :)

În 10 august 2023 06:17:53 EEST, Brian Matherly ***@***.***> a scris:
