### ISSUE TITLE
Can't download SDKs for Linux

### ISSUE THREAD

**Issue by MarriotZ** [mltframework/shotcut#1468]
Hi, the author of this project
  When I downloaded shotcut SDK for Linux, the page prompted me with 'access denied' and refused my request.
  Could you tell me how to solve this issue?
![2023-08-31_00-22](https://github.com/mltframework/shotcut/assets/114582524/2fcabb3c-9e6d-4f44-9537-3301f2ff6666)

**Comment by MarriotZ** [comment]
> No longer available, obviously. The page showing this link says clearly "DISCONTINUED"

Sorry, I may not have rested well and ignored the text above. Thank you for reply.

**Comment by ddennedy** [comment]
"SDKs" are not the typical way to do development on Linux. Rather, you install dependencies from distribution packages, except in the case of Shotcut you need to pick a distro that aggressively updates MLT, maybe a so-called rolling release distro:
https://itsfoss.com/best-rolling-release-distros/
