### ISSUE TITLE
Segmentation fault (core dumped) -- how to collect more info?

### ISSUE THREAD

**Issue by facundobatista** [mltframework/shotcut#1469]
Hello! 

I'm using latest Shotcut (`23.07.29`), and both from the AppImage or the Snap installation I get a lot of segfaults. It's not in a predictable moment, but while editing or even opening the `.mlt` file.  Desktop is KDE on Ubuntu 22.04.3.

How can I collect more information so I can open a proper bug report and actually help you?

Thanks!

**Comment by ddennedy** [comment]
Using the snap
1. `cd /snap/shotcut/current/Shotcut.app`
2. `source source-me`
3. `gdb bin/shotcut`
4. at "(gdb)" enter "run" and press enter
5. wait for crash
6. at "(gdb)" enter "bt" and press enter
7. copy and paste the output here

**Comment by facundobatista** [comment]
Thanks @ddennedy for the information!

I cannot run `gdb` properly, though :(... I get

```
$ gdb bin/shotcut
gdb: /snap/shotcut/current/Shotcut.app/lib/libtinfo.so.6: version `NCURSES6_TINFO_6.2.20211010' not found (required by /lib/x86_64-linux-gnu/libncursesw.so.6)
```

The weird thing there is that it's taking `libtinfo.so.6` from inside the snap but `libncursesw.so.6` from the system. Maybe the ncurses library should also be put inside the snap?

Alternatively, can I get the debug information running shotcut *not* from the snap? 

Thanks again!

**Comment by neutrinus** [comment]
@facundobatista  maybe the logs will tell something?

`~/.local/share/Meltytech/Shotcut/shotcut-log.txt`

**Comment by facundobatista** [comment]
@neutrinus nothing that looks too evident.

For example, this is [what I found in the logs](https://pastebin.ubuntu.com/p/kC7FFv3v8k/) and this is [the output in the terminal](https://pastebin.ubuntu.com/p/h3PB2wYXGF/) until it crashed.

Maybe there is a way to increase the verbosity of logs or info produced?

Thanks!!

**Comment by alexmyczko** [comment]
does `strace shotcut` show something?

otherwise why not native packaging? apt install shotcut?
