### ISSUE TITLE
Playlist Section Plus Button Not Functioning as Expected

### ISSUE THREAD

**Issue by mycreativeusernameis** [mltframework/shotcut#1474]
In the playlist section, the plus button appears to have an issue or may not be functioning as intended. It is labeled as "Add the source to Playlist," but when clicked, it doesn't perform any action. Instead, the button simply duplicates the selected source in the playlist. This behavior seems counterproductive.

My shotcut version is: **23.09.29**
and I'm running it on: **Windows 11**

**Comment by ddennedy** [comment]
Do you have something different than the selected playlist item in the **Source** tab of the player?

**Comment by ddennedy** [comment]
I just tested it, and it is working as designed: it adds literally what it is in the UI element labeled "source" and nothing. Also, your wording is inconsistent. First you say it "doesn't perform any action" and then you say it "duplicates."

**Comment by mycreativeusernameis** [comment]
I'm trying to understand your perspective on the "Source" button. It seems like when you begin a new project and want to add files, you expect the plus button to perform this action. However, it appears that pressing the plus button doesn't do anything in this scenario.

Now, if you've already added some files to your playlist and you select one of them and press the plus button, it adds that file to the playlist again. This can be confusing because you're essentially adding an item that's already in the playlist.

So, could you clarify the actual purpose of the "Source" button and why there might be a need to add an item to the playlist if it's already there?
