### ISSUE TITLE
Old registry key not removed when installing latest version

### ISSUE THREAD

**Issue by BazirClem** [mltframework/shotcut#1476]
Updating Shotcut from Shotcut 23.07.29 to Shotcut 23.9.29 on Windows 10.

The old registry key before the transition to inno setup isn't removed. 
The latest registry key is "Shotcut_is1" and the old registry key is just "Shotcut".

When I tried to install the latest Shotcut version, I had an older version installed and it had the older registry key. So now i have in my registry both keys ( "Shotcut_is1" and "Shotcut") even though the older version have been uninstalled.

I think the newer installation should check wether or not there are an older installation already here

**Comment by ddennedy** [comment]
Thanks, fixed for a new build of installer coming soon.
