### ISSUE TITLE
Shotcut AppImage bundle is not able to open/process any content on Debian Trixie

### ISSUE THREAD

**Issue by vulcainman** [mltframework/shotcut#1482]
Dear mainteners,

First of all, thanks for working on this great project! I'm currently facing a bizarre issue with the latest shotcut AppImage flavor version (2023.09.29). Indeed, it is not able to open/preview/process any input anymore (video, image, etc...). If you open a new item, it display a failure message and, if try to load a project, it displays INVALID for all contents. Here are my observations :

- Everything was working fine when it suddenly happened (I'm almost 100% sure it is related to a system upgrade since I managed to reproduce this issue on another machine), if it can helps, I can provide the list of packages updated during system upgrade.
- Only the AppImage bundle is impacted, the Portable TAR is working fine
- Shotcut logs are 100% equivalent between the 2 flavors (AppImage vs Portable TAR)
- When started from CLI, the AppImage flavor don't display anymore supported codecs (actually, it doesn't print anything) whereas Portable TAR prints a lot of formats/codecs 

System information :

- Debian 13 (Trixie)
- Shotcut 2023.09.29 (AppImage)

Let me know if I can provide you any additional information!

Best

**Comment by ddennedy** [comment]
This was fixed in 28048db for the version 23.09.29 (re-download it):
https://forum.shotcut.org/t/shotcut-fails-to-load-any-video-file/40938/17
