### ISSUE TITLE
The installer's display is wrong

### ISSUE THREAD

**Issue by itagagaki** [mltframework/shotcut#1489]
I ran shotcut-win64-231129.exe but the wording in the dialogue is not correct.
Windows Pro 22H2 Japanese

![image](https://github.com/mltframework/shotcut/assets/71218184/f57d254c-6891-4177-97ea-4af2231a47fe)

**Comment by ddennedy** [comment]
Thank you for the notification. This should be fixed now. Can you please re-download it, and test it to confirm? You will need to uninstall first. Thanks

**Comment by itagagaki** [comment]
Perfect. Thank you!
