### ISSUE TITLE
Crash on Windows when adding video track

### ISSUE THREAD

**Issue by jmcgvr** [mltframework/shotcut#149]
I thought I could create files that don't cause the crash, but I no longer know. All my files now do it and I can't seem to create one that doesn't.

To reproduce:
- versions 15.11.03 and 15.10.06 (all others unknown).
- GPU processing must be UNchecked
- associate .mlt files with shotcut in explorer.
- double-click an .mlt file to open it (opening from shotcut's menu once it's running will not cause the crash)
- right-click in the timeline area and select Add Video Track (add audio track does not crash)
Windows says the following:
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	shotcut.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5638f0d2
  Fault Module Name:	libmlt-6.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5638eb08
  Exception Code:	c0000005
  Exception Offset:	000000000000d52c
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	007d
  Additional Information 2:	007d235e4ee9bf8666abe55bea4cadbc
  Additional Information 3:	64a0
  Additional Information 4:	64a02a01af7a3f64290ca6c0f5fcee48
```
That offset is the first instruction in mlt_service_connect_producer

The simplest .mlt file with the following contents will cause the crash (created by just drag-and-dropping an mp4 file from explorer to shotcut, then from the source viewer to the playlist, then deleting it from the playlist, then saving):
```
<?xml version="1.0" encoding="utf-8"?>
<mlt LC_NUMERIC="English_United States.1252" version="0.9.9" title="Shotcut version 15.11.03" producer="playlist0">
  <profile description="automatic" width="1280" height="720" progressive="1" sample_aspect_num="1" sample_aspect_den="1" display_aspect_num="1280" display_aspect_den="720" frame_rate_num="30000" frame_rate_den="1001" colorspace="709"/>
  <playlist id="playlist0" title="Shotcut version 15.11.03"/>
</mlt>
```
It is not caused by deleting a video from the playlist, as I once thought; the same crash will occur if I save without deleting the file from the playlist.

**Comment by ddennedy** [comment]
make separate issues, please

**Comment by ddennedy** [comment]
This is resolved (first issue), and I am going to make a new release tomorrow that includes it. Closing this because there should only be one issue per issue.

**Comment by jmcgvr** [comment]
I am still getting this in 15.12.03:
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	shotcut.exe
  Application Version:	0.0.0.0
  Application Timestamp:	565fbaaa
  Fault Module Name:	libmlt-6.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	565fb547
  Exception Code:	c0000005
  Exception Offset:	000000000000d52c
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	2483
  Additional Information 2:	24839b85d46335f8538f185414274b77
  Additional Information 3:	9429
  Additional Information 4:	94299d927beb8f96e76fe163462acde5
```

**Comment by ddennedy** [comment]
Hmm.. yes. Why is that? Because it works from my dev copy launching it from the IDE.

**Comment by ddennedy** [comment]
Testing a nightly build, and this is fixed now for me. You can try it:
http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-win64-151223.exe
