### ISSUE TITLE
Missing MLT XML Annotations Schema / Outdated Docs?

### ISSUE THREAD

**Issue by hendursaga** [mltframework/shotcut#1490]
I [posted on the forum](https://forum.shotcut.org/t/edl-to-mlt-xml-conversion/40527) some months ago, but received no answer. There does not appear to be any sort of DTD or other schema for the Shotcut-specific additions to the MLT XML specification. The MLT project has a [DTD schema](https://github.com/mltframework/mlt/blob/master/src/modules/xml/mlt-xml.dtd). What little documentation I have on these Shotcut additions, is either scattered throughout the code, or [available as a note](https://shotcut.org/notes/mltxml-annotations/) that may or may not be outdated.

As for OS and Shotcut version, I use Ubuntu Jammy and Shotcut v23.11.29.

**Comment by ddennedy** [comment]
Shotcut does not change the schema. It puts its data into MLT property elements. There is a page on the web site that documents these as you already know. I am not giving anything more to you in this regard. Figure it out yourself.
