### ISSUE TITLE
shotcut version 23.11.04  build with qt6-6.6.0 on NetBSD 10, abort with fatal: Cannot find stack base

### ISSUE THREAD

**Issue by extremelydangerous** [mltframework/shotcut#1491]
<pre>
The system is NetBSD 10.0 running on amd64...
built with qt-6.6.0 on start it flashes the inital blue screen than dumps core with a backtrace:

[lenzi@10dev ~]$ shotcut 
[Info   ] <main> Starting Shotcut version 23.11.30 
[Info   ] <main> Linux version "10.0_RC1" 
[Info   ] <main> number of logical cores = 8 
[Info   ] <main> locale = QLocale(Portuguese, Latin, Brazil) 
[Info   ] <main> install dir = "/usr/pkg/bin" 
[Info   ] <ShotcutSettings::log> language "pt_BR" 
[Info   ] <ShotcutSettings::log> deinterlacer "onefield" 
[Info   ] <ShotcutSettings::log> external monitor "" 
[Info   ] <ShotcutSettings::log> GPU processing false 
[Info   ] <ShotcutSettings::log> interpolation "bilinear" 
[Info   ] <ShotcutSettings::log> video mode "" 
[Info   ] <ShotcutSettings::log> realtime true 
[Info   ] <ShotcutSettings::log> audio channels 2 
[Debug  ] <MainWindow::changeTheme> begin 
[Debug  ] <MainWindow::changeTheme> end 
[Debug  ] <MainWindow::MainWindow> begin 
[Info   ] <MainWindow::MainWindow> device pixel ratio = 1 
[Fatal  ] <> Cannot find stack base
===========================
this is a QT error... any help?
please reply to my personal email:  nervoso@k1.com.br

**Comment by ddennedy** [comment]
Our developers do not run NetBSD to support this, and no one else has commented. So, closing as expired.
