### ISSUE TITLE
No indication of progress when exporting

### ISSUE THREAD

**Issue by php4fan** [mltframework/shotcut#1497]
0. Edit some videos in a project
1. Go to File->Export
2. Select a folder to save to, a file name, and go.

Expected:
Should show a progress bar indicating that it is exporting (ideally a percentage done and an estimated time remaining, but at the very least an indication that it's in process and it's not finished), and let me know when it's done.

Observed:
The window for exporting immediately closes, as if it had exported the video immediately in a fraction of a second.

I was very surprised by how quick it was, so I went and opened the folder in my file explorer and saw the file there, but it was growing. That's how I knew that it was actually still exporting, despite the fact that within ShotCut's UI there was no indication that the export was in process.

I had to guess when it was done exporting the video by when the file size stopped growing.

**Comment by ddennedy** [comment]
I have no idea what you are talking about. It already does that. I guess you are not viewing the Jobs panel somehow.

**Comment by bmatherly** [comment]
I just did a test to confirm: when you start an export job, the jobs panel is enabled and forced to the foreground. You can't miss it. However, maybe there is some condition where the jobs panel does not show. If you find such a case, please let us know.

**Comment by php4fan** [comment]
> I just did a test to confirm: when you start an export job, the jobs panel is enabled and forced to the foreground. You can't miss it.

This is where it shows up for me. I definitely did miss it and I would argue it's _very_ missable. 

![image](https://github.com/mltframework/shotcut/assets/13969584/6625ff86-fd10-46a7-ad86-252e89e10912)
