### ISSUE TITLE
Timer filter not working consistently (regression)

### ISSUE THREAD

**Issue by JustinTimeCuber** [mltframework/shotcut#1505]
OS: Linux Mint 21.2 Victoria
Shotcut: 23.12 Flatpak

The timer filter shows correctly in the preview, but is sometimes not visible after exporting a video, using either software or hardware encoding. In the September release (23.9) it seems to work correctly.

Reproduction steps:
1. Create a project
2. Add a Timer filter using the "bottom left" preset
3. Save the project file
4. Export the video
5. Observe that the filter is not applied
6. Downgrade to 23.9: `sudo flatpak update --commit=687df650cace86058925a39a116dff1dcb1aa63439645784358779340d1f609c org.shotcut.Shotcut`
7. Open the same project file
8. Export the video again
9. Observe that the filter is applied correctly

**Comment by bmatherly** [comment]
In a quick test, I recreated this with the 23.12 portable, but not with git master. The "Bottom Left" preset seems to be the key.

Would you be willing to test this daily build?
https://github.com/mltframework/shotcut/actions/runs/7485826967

**Comment by ddennedy** [comment]
The save step is no necessary. I see in the job XML
`<property name="opacity">#01000000</property>`
That's weird. It is in a color format.

**Comment by ddennedy** [comment]
I found an uninitialized class member was the culprit. This does not fix affected custom presets that have serialized this  floating value to a color string format.
