### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by louies0623** [mltframework/shotcut#1506]
The progress black text on the Splash screen will blend with the background color, making it difficult to read.
![image](https://github.com/mltframework/shotcut/assets/44593430/f812f17e-b05c-4f5d-b87f-6ec823a2dd45)
It should be changed to white, and I also hope that the splash screen will at least make users feel psychologically that this software will not be boring to use. (First impression) This is what I designed.
![未命名-2_工作區域 1](https://github.com/mltframework/shotcut/assets/44593430/88029d00-bfc7-4c49-9ede-df77e74665a0)
[logo background.svg](https://github.com/mltframework/shotcut/assets/44593430/0711835f-37ab-4124-9fa3-4af47e71173c)

**Comment by ddennedy** [comment]
No thank you
