### ISSUE TITLE
Changing the playback duration of pictures

### ISSUE THREAD

**Issue by Sharc99** [mltframework/shotcut#1507]
Version 23.12.15, Windows 11:
Changing the Duration of imported pictures (.jpg) in the 'Properties' is grayed out and can't be changed. It's fixed at 00:00:03:00.
Am I possibly missing something?

**Comment by bmatherly** [comment]
It is explained here https://forum.shotcut.org/t/how-to-change-the-default-duration-of-images-or-other-clips/24178/8
