### ISSUE TITLE
Shotcut shortcuts

### ISSUE THREAD

**Issue by alexmyczko** [mltframework/shotcut#1511]
You might want to ship or link this?

https://github.com/alexmyczko/autoexec.bat/blob/master/Documents/shotcut.md

**Comment by ddennedy** [comment]
why?

**Comment by ddennedy** [comment]
It looks like all you did was add <kbd> tags. That clutters the page both visually and for maintenance when it already very clear these are keys.

**Comment by alexmyczko** [comment]
I was looking for this. And another user as well. Maybe there are more? Of course you can just close the issue if you think it is not useful.

**Comment by ddennedy** [comment]
It is already here https://shotcut.org/howtos/keyboard-shortcuts/
Which you can get to from https://shotcut.org/howtos/
Which you can get to from Help > Topics (<kbd>F1</kbd>) in the application. Right above the more useful **Help > Actions and Shortcuts**
