### ISSUE TITLE
Automatic Proxy Creation Stopped Working

### ISSUE THREAD

**Issue by ssoher** [mltframework/shotcut#1512]
`Windows 10 22H2 Build 19045.3930; Shotcut 24.0.1.28`

I have manually deleted some proxy files through Windows explorer and now proxy creation doesn't fire automatically. It was working fine before that.

Upon clicking `Settings->Proxy->Use Proxy` I get the "Do you want to create missing proxies for every file in this project" dialog. Upon clicking yes nothing happens but the `Proxy is ON at 540p` label is shown on the UI. There are no proxies in the proxy path (Checked with `Proxy->Storage->Show` option).

shotcut-log.txt contains the following lines when I click yes on the missing proxy creation dialog:

```
[Debug  ] <ProxyManager::GoProProxyFilePath> "D:/art/breakout/trailer/source/GLOXY_TEST.LRV" 
[Debug  ] <ProxyManager::isValidVideo> pix_fmt = "yuv420p"  codec.frame_rate = ""  alpha_mode = false 
[Debug  ] <ProxyManager::generateIfNotExists> 640 x 1080 threshold 702 
[Debug  ] <ProxyManager::GoProProxyFilePath> "D:/art/breakout/trailer/source/GLOXY_TEST.LRV" 
[Debug  ] <ProxyManager::isValidVideo> pix_fmt = "yuv420p"  codec.frame_rate = ""  alpha_mode = false 
[Debug  ] <ProxyManager::generateIfNotExists> 640 x 1080 threshold 702 
```

I guess it thinks the proxies already exist and exit early from the proxy generation function?

Things I have tried:
- Create fresh project
- Completely remove (appdata and cache folders as well as the program itself) and reinstall Shotcut with delete registry settings option checked
- Try an older version of Shotcut

Proxies only get generated and applied if I manually create a proxy for each clip in their Properties panel. Otherwise like I said the label Proxy is ON at 540p is shown but there is no P tag on the clips, there is no (Proxy) in the timeline and judging by the quality of the clip it's clearly not 540p.

**Comment by ddennedy** [comment]
Proxies are only automatically generated under certain conditions. This log line
> [Debug  ] <ProxyManager::generateIfNotExists> 640 x 1080 threshold 702 

tells me the width and height of the source video is not high enough for automatic proxy generation. From the [documentation](https://forum.shotcut.org/t/proxy-editing/18517):

> Both the image width and image height are more than 1.3X the preview scaling resolution (or 540 if preview scaling is off).

You can still manually make a proxy for it in **Properties**.

**Comment by ssoher** [comment]
@ddennedy thank you, didn't know preview scaling affected proxy generation, that's a bit confusing tbh. Anyways my problem is solved 👍
