### ISSUE TITLE
Timeline milliseconds wrap at 60

### ISSUE THREAD

**Issue by ssoher** [mltframework/shotcut#1513]
If the timeline time format is hh:mm:ss:dd, the last part for the milliseconds should be 3 digits and should go up to 999. There are 1000ms in a second not 60. Am I reading this incorrectly?

Currently once it hits 60 it increases the minutes and resets the ms digits.

![image](https://github.com/mltframework/shotcut/assets/4283979/6b0fbd27-e60a-4239-9630-8443328f1c73)

**Comment by ddennedy** [comment]
What you are showing is proper SMPTE timecode where the last field is frames, and not milliseconds. I see that you did not follow the directions of our GitHub Issue template. This is not a general help area; use our forum for questions and general discussion.

**Comment by ddennedy** [comment]
See also "Entering Time Values" at the bottom of this page https://shotcut.org/howtos/keyboard-shortcuts/

**Comment by ssoher** [comment]
> See also "Entering Time Values" at the bottom of this page https://shotcut.org/howtos/keyboard-shortcuts/

Thank you @ddennedy, sorry for not following the issue template directions, I'll be sure to check the forums and documentation before opening a github issue in the future.
