### ISSUE TITLE
Pause - UnPause crashes the task

### ISSUE THREAD

**Issue by Brisou394** [mltframework/shotcut#1514]
Pausing an export makes the task unresponsive. Nothing can be done to resume the job or even delete the export line.
I render in HEVC_nvenc
latest Shotcut (v24.01)
Win11

**Comment by ddennedy** [comment]
What is your operating system?

**Comment by ddennedy** [comment]
I do not reproduce the problem. So, until I can you can avoid using this if it does not consistently work for you. You should also indicate if you can consistently reproduce it yourself. Maybe it was a single incident.

**Comment by Brisou394** [comment]
indeed, I test it again and it does work. It previously failed on me 3 times...

**Comment by Brisou394** [comment]
indeed, I test it again and it does work. It previously failed on me 3 times...

**Comment by ddennedy** [comment]
Please update this bug if you find the factor that causes the problem. For example, maybe if the computer goes to sleep. Thanks, I will run a couple of more tests myself.
