### ISSUE TITLE
crash on this..

### ISSUE THREAD

**Issue by CatMow** [mltframework/shotcut#1519]
https://github.com/mltframework/shotcut/assets/84914492/4f0efd30-7d5f-4732-af66-4b939acb8934

watch the video, double clicking on the "Text: Simple" will crash it. (in that specific setup)

shotcut version: 24.01.28
windows version: 22h2, 19045.3930

This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

**Comment by CatMow** [comment]
sorry i did have to pause to do something

**Comment by ddennedy** [comment]
The simple text filter UI is not appearing. Either you have a bad install, your system is a bad state and needs reboot, or your system is incompatible with Shotcut’s usage of Direct3D. This is not something we can reproduce and fix.
