### ISSUE TITLE
PLEASE correct the QT version on README

### ISSUE THREAD

**Issue by ohquait** [mltframework/shotcut#1523]
Only with Qt**6**  building can work,
but on Readme just see QT**5** 

or add a cmake.options or meson.options provide to switch between Qt5 - Qt6 builds,

**Comment by ddennedy** [comment]
Wrong, Qt 5 is supported.

**Comment by ddennedy** [comment]
You are correct. I was thinking of different project.

**Comment by ohquait** [comment]
Beautiful will be,
if a re-patch were possible
so that you can also build the current version under QT5,
possibly with restrictions - i.e. without the plugins or
functions that are really only possible with QT6.
