### ISSUE TITLE
melt.exe connecting to the internet

### ISSUE THREAD

**Issue by sdfdger** [mltframework/shotcut#1527]
**My question:** Why does `melt.exe` access the internet?
<br><br>

Shotcut Version: Windows 10 24.02.29 (Portable)

**CMD:**
```
    C:\shotcut-win64-240229>melt.exe
    [melt.exe immediately attempts to connect to the internet]
```
Exporting video in Shotcut also does this. Shotcut successfully exports regardless of failed `melt.exe` internet connection.

**Comment by ddennedy** [comment]
I don’t know. It is probably something in a library. What is trying to access and do?

**Comment by sdfdger** [comment]
The software I used isn't advanced enough to log connection details, only blocks and alerts internet connections.

**Comment by ddennedy** [comment]
"[melt.exe immediately attempts to connect to the internet]" is not specific. How do you know?
"The software I used" is not specific. What software?
Closing this soon as this is not identified as a hard defect, and we only use this space for tracking hard defects.

**Comment by ddennedy** [comment]
I started Windows Resource Monitor > Network and then started Shotcut 24.02.29 and ran `melt.exe` via Export. It did not show shotcut.exe or melt.exe:
![image](https://github.com/mltframework/shotcut/assets/1146683/2bdde40c-f2eb-4c2e-b9e3-21735acd67e6)

If I choose Help > Upgrade to run a new version check, then `shotcut.exe` does appear in the Resource Monitor as expected.
