### ISSUE TITLE
source compile

### ISSUE THREAD

**Issue by wangdongxxx** [mltframework/shotcut#1528]
Hello, the latest version of the source code is compiled using mingw under windows. There is no log output in cmd in debug mode, and the debugging breakpoints are invalid.

**Comment by thiru31** [comment]
I noticed that you recently **closed this issue after finding a solution**. I'm encountering similar difficulties while compiling Shotcut from source on Windows using Mingw. Could you please provide some guidance or a walkthrough on how you resolved the issue? Any assistance would be greatly appreciated.

Thanks in advance

**Comment by wangdongxxx** [comment]
> I noticed that you recently **closed this issue after finding a solution**. I'm encountering similar difficulties while compiling Shotcut from source on Windows using Mingw. Could you please provide some guidance or a walkthrough on how you resolved the issue? Any assistance would be greatly appreciated.
> 
> Thanks in advance

set environment about QSG_RHI_BACKEND
