### ISSUE TITLE
always Failed with exit code -1073741819 Failed with exit code -1073741819

### ISSUE THREAD

**Issue by hgftrdw45ud67is8o89** [mltframework/shotcut#1529]
win10,shotcut latest github release 24.02

The video is properly produced and written,but it always shows failed,not sure where it fails.

`[link swresample] 1(mono) f32le 44100Hz -> 2(stereo) f32le 48000Hz
[mp4 @ 000002bdc52ec940] Timestamps are unset in a packet for stream 1. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[mp4 @ 000002bdc52ec940] Encoder did not produce proper pts, making some up.
[mp4 @ 000002bdc52ec940] Starting second pass: moving the moov atom to the beginning of the file
[AVIOContext @ 000002bdc5305e00] Statistics: 898246766 bytes read, 0 seeks
[h264_nvenc @ 000002bdc5750c80] Nvenc unloaded
[aac @ 000002bdc574c480] Qavg: 33943.312
[AVIOContext @ 000002bdc5305880] Statistics: 1796738350 bytes written, 26 seeks, 6870 writeouts
[link swresample] 1(mono) f32le 44100Hz -> 2(stereo) f32le 48000Hz
Failed with exit code -1073741819
Failed with exit code -1073741819
`

**Comment by bmatherly** [comment]
This is a common error code that can be triggered by many things. The best place to look for help is on the forum. It could be many things... turn off hardware encoder, disable parallel processing, remove a corrupt filter.

Have a look at these recent posts and see what has worked for other people:
https://forum.shotcut.org/search?q=1073741819%20%20order%3Alatest

**Comment by ddennedy** [comment]
Not enough info to reproduce, diagnose, or be actionable.
