### ISSUE TITLE
Windows crash when splitting timeline at playhead and adding filters

### ISSUE THREAD

**Issue by OpusMcN** [mltframework/shotcut#153]
I have a shot with 10 2k by 1k 60Hz videos.  I want to fade to black between each shot.  I can't see a transition that does this, so I'm cutting each shot 1 second before the end, adding a fade out video filter, then cutting the next shot 1 second in and adding a fade in video filter.  After the first few filters were added I'm getting continuous crashes (app hangs for 10 seconds then vanishes with no error message) when either splitting at the playhead, clicking the '+' button to add a filter, or selecting the filter.   Crashes seems to happen fairly randomly, but I can't do more than 2 or 3 actions on this file before it crashes every time.  Everthing worked fine while editing until I started cutting the clips and adding filters.

Windows 7.1, Nvidia 980 GTX graphics (GPU processing disabled).

Log file and mlt project file attached.
[shotcut-log.txt](https://github.com/mltframework/shotcut/files/51453/shotcut-log.txt)
[shotcut.mlt.txt](https://github.com/mltframework/shotcut/files/51456/shotcut.mlt.txt)

**Comment by ddennedy** [comment]
You are using 15.12.01, which has a known crashing bug when splitting, which is why we now have 15.12.03 on the downloads page. Please upgrade and report back.

**Comment by OpusMcN** [comment]
Thanks, appears fixed in 15.12.03.    I only downloaded yesterday from the main shotcut page and got 15.12.01 then, so I must have just missed the upgrade.
