### ISSUE TITLE
org.kde.Platform branch 6.5 is end-of-life - Info: applications using this runtime: org.shotcut.Shotcut

### ISSUE THREAD

**Issue by LinuxOpa** [mltframework/shotcut#1530]
ubuntu 22.04 full updated
Meltytech, LLC  org.shotcut.Shotcut 24.02.29 stable flathub system

Info: runtime org.kde.Platform branch 6.5 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   org.shotcut.Shotcut

**Comment by ddennedy** [comment]
What is more important? Qt's so-called support for its open source version or the applications being ready and verified working for the latest version? What if every Qt 6-based project does not have the manpower resources to stay current? I am not saying that is the case here, but I think these are genuine issues. I will update the runtime in the current beta slated for the next release but only for Flatpak and not any other build that we provide as I do not volunteer to run on that hamster wheel.

**Comment by ddennedy** [comment]
Build currently fails on Qt 6.7; so, this is not a simple flatpak update for next release (already in beta), but maybe the one after that.

**Comment by sudopluto** [comment]
I don't think we have to go to 6.7 yet, I think qt 6.6 won't give the flatpak warning. Will try building with 6.6 later.

**Comment by ddennedy** [comment]
[Build fails](https://buildbot.flathub.org/#/builders/6/builds/116503) on 6.6 too.

**Comment by ddennedy** [comment]
OK, I was able to fix the build on KDE runtime 6.6 with a cmake tweak in the flatpak manifest. Brief testing is successful with no end-of-line warning. I applied the change to the flatpak beta for next release.
