### ISSUE TITLE
auto-saved file doesn't like my reletive path

### ISSUE THREAD

**Issue by CarlFK** [mltframework/shotcut#154]
clicked something, Shotcut crashed.  restarted, "autosave file exists, restore?" Yes.

all my assets are invalid.  I saved as a new file, diff shows:

<     <property name="resource">../dv/Collins_Auditorium/2015-11-15/Sunday Afternoon Camera/SC1ATK117.mov</property>
---
>     <property name="resource">/home/carl/.local/share/Meltytech/Shotcut/autosave/../dv/Collins_Auditorium/2015-11-15/Sunday Afternoon Camera/SC1ATK117.mov</property>

**Comment by ddennedy** [comment]
Shotcut does not support relative paths that are not in the same folder as the .mlt file or a sub-folder.
