### ISSUE TITLE
SVT-AV1 does not follow provided quality factor

### ISSUE THREAD

**Issue by NyanMaths** [mltframework/shotcut#1547]
Hello there,
I have been struggling to get libsvtav1 working on Arch Linux with shotcut 24.04-1 (latest release as I write). This is a fresh install, so nothing fishy in my packages for now and I installed svt-av1.
When I ask for quality based VBR (I assume this stands for CRF) in the export options, I can only get the same quality and the same file size, whatever I put as qscale.
Behold, the typical export log :

<details>
  <summary>Click to expand</summary>
  Plugin 1041 exists in both '/usr/lib/ladspa/filter.so' and '/usr/lib64/ladspa/filter.so'; using version in '/usr/lib/ladspa/filter.so'<br />
Plugin 1042 exists in both '/usr/lib/ladspa/filter.so' and '/usr/lib64/ladspa/filter.so'; using version in '/usr/lib/ladspa/filter.so'<br />
Plugin 1043 exists in both '/usr/lib/ladspa/delay.so' and '/usr/lib64/ladspa/delay.so'; using version in '/usr/lib/ladspa/delay.so'<br />
Plugin 1050 exists in both '/usr/lib/ladspa/noise.so' and '/usr/lib64/ladspa/noise.so'; using version in '/usr/lib/ladspa/noise.so'<br />
Plugin 1048 exists in both '/usr/lib/ladspa/amp.so' and '/usr/lib64/ladspa/amp.so'; using version in '/usr/lib/ladspa/amp.so'<br />
Plugin 1049 exists in both '/usr/lib/ladspa/amp.so' and '/usr/lib64/ladspa/amp.so'; using version in '/usr/lib/ladspa/amp.so'<br />
Plugin 1044 exists in both '/usr/lib/ladspa/sine.so' and '/usr/lib64/ladspa/sine.so'; using version in '/usr/lib/ladspa/sine.so'<br />
Plugin 1045 exists in both '/usr/lib/ladspa/sine.so' and '/usr/lib64/ladspa/sine.so'; using version in '/usr/lib/ladspa/sine.so'<br />
Plugin 1046 exists in both '/usr/lib/ladspa/sine.so' and '/usr/lib64/ladspa/sine.so'; using version in '/usr/lib/ladspa/sine.so'<br />
Plugin 1047 exists in both '/usr/lib/ladspa/sine.so' and '/usr/lib64/ladspa/sine.so'; using version in '/usr/lib/ladspa/sine.so'<br />
mlt_repository_init: skip plugin /usr/lib/mlt-7/libmltqt.so<br />
mlt_repository_init: skip plugin /usr/lib/mlt-7/libmltglaxnimate.so<br />
mlt_repository_init: failed to dlopen /usr/lib/mlt-7/libmltrtaudio.so
  (librtaudio.so.7: cannot open shared object file: No such file or directory)<br />
mlt_repository_init: failed to dlopen /usr/lib/mlt-7/libmltsox.so
  (libsox.so.3: cannot open shared object file: No such file or directory)<br />
[libsvtav1 @ 0x7fee94001e00] [Eval @ 0x7feebdfff190] Undefined constant or missing '(' in 'fast'<br />
[libsvtav1 @ 0x7fee94001e00] Unable to parse option value "fast"<br />
[libsvtav1 @ 0x7fee940021c0] [Eval @ 0x7feebdfff190] Undefined constant or missing '(' in 'fast'<br />
[libsvtav1 @ 0x7fee940021c0] Unable to parse option value "fast"<br />
Svt[info]: -------------------------------------------<br />
Svt[info]: SVT [version]:	SVT-AV1 Encoder Lib v2.1.0-dirty<br />
Svt[info]: SVT [build]  :	GCC 14.1.1 20240507	 64 bit<br />
Svt[info]: LIB Build date: May 20 2024 19:45:55<br />
Svt[info]: -------------------------------------------<br />
Svt[info]: Number of logical cores available: 12<br />
Svt[info]: Number of PPCS 76<br />
Svt[info]: [asm level on system : up to avx512]<br />
Svt[info]: [asm level selected : up to avx2]<br />
Svt[info]: -------------------------------------------<br />
Svt[info]: SVT [config]: main profile	tier (auto)	level (auto)<br />
Svt[info]: SVT [config]: width / height / fps numerator / fps denominator 		: 1920 / 1080 / 120000000 / 1000000<br />
Svt[info]: SVT [config]: bit-depth / color format 					: 8 / YUV420<br />
Svt[info]: SVT [config]: preset / tune / pred struct 					: 10 / PSNR / random access<br />
Svt[info]: SVT [config]: gop size / mini-gop size / key-frame type 			: 120 / 16 / key frame<br />
Svt[info]: SVT [config]: BRC mode / rate factor 					: CRF / 35 <br />
Svt[info]: SVT [config]: AQ mode / variance boost 					: 2 / 0<br />
Svt[info]: -------------------------------------------<br />
[producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2<br />
[AVIOContext @ 0x7fee54831480] Statistics: 66404 bytes read, 3 seeks<br />
[chain avformat-novalidate] /home/nyanmaths/Videos/captures/payload.mkv<br />
    checking VFR: pkt.duration 8<br />
[swscaler @ 0x7fee57443080] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fedb06c01c0] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fedb10f9100] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fedb1b46fc0] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fedb257fec0] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fedb2bbb440] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fedb31ee540] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fedb3829640] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fedb3e64340] deprecated pixel format used, make sure you did set range correctly<br />
SvtMalloc[info]: SVT Memory Usage:<br />
SvtMalloc[info]:     total allocated memory:       1.51 GB<br />
SvtMalloc[info]:         malloced memory:          492.61 MB<br />
SvtMalloc[info]:         callocated memory:        27.64 MB<br />
SvtMalloc[info]:         allocated aligned memory: 1.01 GB<br />
SvtMalloc[info]:     mutex count: 14867<br />
SvtMalloc[info]:     semaphore count: 1359<br />
SvtMalloc[info]:     thread count: 348<br />
SvtMalloc[info]:     hash table fulless: 0.124473, hash bucket is healthy<br />
[swscaler @ 0x7fedb3e97440] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fedb3ed1f40] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fedb3f0cc80] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fedb3f3f700] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fedb3f7a240] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fedb3facf40] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fedb3fe7c40] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fed50622800] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fed50c55280] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fed5128ff80] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fed518cae80] deprecated pixel format used, make sure you did set range correctly<br />
SvtMalloc[info]: top 10 malloced memory locations:<br />
SvtMalloc[info]: (135.47 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbCodingUnit.c:84<br />
SvtMalloc[info]: (91.58 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Common/Codec/EbBitstreamUnit.c:36<br />
SvtMalloc[info]: (87.66 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbPictureControlSet.c:1071
SvtMalloc[info]: (38.10 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbPictureControlSet.c:1524
SvtMalloc[info]: (21.17 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbPictureControlSet.c:1527
SvtMalloc[info]: (15.94 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbPictureControlSet.c:1043
SvtMalloc[info]: (13.89 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbPictureControlSet.c:114
SvtMalloc[info]: (13.01 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbPictureControlSet.c:567
SvtMalloc[info]: (9.96 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbPictureControlSet.c:1039
SvtMalloc[info]: (9.03 MB): /usr/src/debug/svt-av1/SVT-AV1/Source/Lib/Encoder/Codec/EbPictureControlSet.c:115
[swscaler @ 0x7fedb2bd0600] deprecated pixel format used, make sure you did set range correctly<br />
... same warning maybe 10000 times<br />
[swscaler @ 0x7fed52c95ac0] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fed52c9a1c0] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fed52c9a1c0] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fed52c9a1c0] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fed52c9a1c0] deprecated pixel format used, make sure you did set range correctly<br />
[swscaler @ 0x7fed52c9a1c0] deprecated pixel format used, make sure you did set range correctly<br />

[matroska @ 0x7fee94000f40] Timestamps are unset in a packet for stream 1. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly<br />
[matroska @ 0x7fee94000f40] Encoder did not produce proper pts, making some up.<br />
SvtMalloc[info]: you have no memory leak<br />
[aac @ 0x7fee94002e40] Qavg: 837.354<br />
[AVIOContext @ 0x7fed6ac79440] Statistics: 115696244 bytes written, 2 seeks, 443 writeouts<br />
[AVIOContext @ 0x7fee5482e100] Statistics: 410678172 bytes read, 3 seeks<br />
[AVIOContext @ 0x7fee54839880] Statistics: 410743708 bytes read, 3 seeks<br />
Completed successfully in 00:05:47<br />
</details>

Thanks in advance for any response.
Edit : made the log actually readable

**Comment by ddennedy** [comment]
This is not a bug. SVT-AV1 is not supported in Shotcut in that version. (Adding it yourself is not something you should report as  a bug when you don't know how to use it.) Use our [24.06 BETA](https://forum.shotcut.org/t/beta-version-24-06-now-available-to-test/44478) to use SVT-AV1. If you want to use your own build or package then take a look at the changes in Git here and in Shotcut related to SVT-AV1. Look through the recently closed Pull Requests.
