### ISSUE TITLE
(UI) Stabilise filter hard to use having long file paths

### ISSUE THREAD

**Issue by lightwisephoto** [mltframework/shotcut#1548]
Hi.

When using the _Stabilise_ filter it gets hard to control the inputs when the path to the _Stabilisation file_ is rather long.

See:

![Inputs and Buttons not accessible](https://github.com/mltframework/shotcut/assets/163399981/fcaf6a10-5144-46bf-92df-1cd033c3bb9d)

You're unable to see and reach input fields and reset buttons on the right since everything stretches out with the file path.

Here's how it should look like:

![Inputs and Buttons](https://github.com/mltframework/shotcut/assets/163399981/2050d708-cdbc-43b0-8be2-e2018f8db1f8)

I'd suggest a _disabled text field_ instead of a label for the path of the _Stabilisation file_ so that the whole path can be shown whilst the text field is never longer than the surrounding frame.

Shotcut version 24.04.28 on
Linux Mint

Thank you.

**Comment by ddennedy** [comment]
It now shows only the basename and the full path and name in a tooltip. Not using a disabled text field because that is ugly.
