### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by zukas97** [mltframework/shotcut#1549]
I am using void Linux and when I tried to open shotcut is crashed instantly. When I ran it through terminal, I got this error:
```
shotcut: symbol lookup error: /usr/lib/libCuteLogger.so: undefined symbol: _ZN14QReadWriteLock16destroyRecursiveEP21QReadWriteLockPrivate, version Qt_6_PRIVATE_API
```
This may already be fixed since void does not use the latest packages but idk.

**Comment by ddennedy** [comment]
From the template
> If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

Also, on Linux specify how you are getting, installing, and running Shotcut. If you are using a distro package, you need to report the problem to them. Our code does not contain a reference to [`QReadWriteLock::destroyRecursive`](https://github.com/search?q=repo%3Amltframework%2Fshotcut%20destroyRecursive&type=code).

I do not reproduce the issue on a few Debian/Ubuntu-based or Fedora distributions with our portable, Snap, AppImage, or Flatpak, which is all that we support here.
