### ISSUE TITLE
Timeline scaling will cause the program to lose its response

### ISSUE THREAD

**Issue by wenbingzhang** [mltframework/shotcut#1553]
MACOS: 12.6
SHOTCUT: v24.06

4 hours of video, dragging it to the timeline, and then setting the zoom of the timeline to the maximum will cause the program to lose its response.

**Comment by ddennedy** [comment]
You need to more patient especially if it is the first time importing as it will create a waveform in the background, which is going to take long for a 4 hour video. In my testing, it does not hang indefinitely. Turning off Settings > Timeline > Show Audio Waveforms makes it slightly better. I cannot make everything instantaneous.
