### ISSUE TITLE
 Crop:Rectangle filter  Outline box Not Visible on Debian

### ISSUE THREAD

**Issue by gl0wplatinum** [mltframework/shotcut#1554]
Hello,

I'm new to video editing and I use Linux (Debian 12) as my daily driver. I installed Shotcut to blur a video for YouTube, and while I managed to do that, I encountered an issue that made me switch to Windows temporarily.

I tried to use the Crop:Rectangle tool in Shotcut on Debian, but it didn't seem to load correctly. The outline box that allows you to select the area to crop was not visible. I tried using SHIFT + drag, but it was buggy. So, I quickly switched to a Windows VM, installed Shotcut, and the Crop
tool worked as intended.

Some things I want to mention:

I tried reinstalling Shotcut on Debian, but it didn't fix the issue.
I also tried running the Windows version of Shotcut with Wine, but that didn't work either.
i here's output of me add ing the filter but i doubt it will be helpfull but i will be glad to reproduce this bug and provide more technical details:
[h264 @ 0x562560576900] Reinit context to 1920x1088, pix_fmt: yuv420p
[Info   ] <AvformatProducerWidget::onFrameDecoded> color transfer 1 = "ITU-R BT.709" 
[Info   ] <MainWindow::showStatusMessage> "Click in rectangle + hold Shift to drag" 
[Info   ] <Util::isMemoryLow> available RAM =  2537148 KB 
[Debug  ] <autosaveTask> Function autosaveTask finished in 1 ms.

![Screenshot from 2024-07-14 19-00-04](https://github.com/user-attachments/assets/6c87db3e-cb30-4029-a214-0ca85804daf7)

**Comment by gl0wplatinum** [comment]
![Screenshot from 2024-07-14 19-02-32](https://github.com/user-attachments/assets/a42583b3-8e08-42a6-ac06-b14549cca5b9)

**Comment by ddennedy** [comment]
How did you get and install Shotcut for Debian?

**Comment by gl0wplatinum** [comment]
> How did you get and install Shotcut for Debian? If you are using the [package](https://packages.debian.org/bookworm/shotcut), that is old and we only support our builds. In our builds, this has always worked on the Ubuntu 20.04 and 22.04 versions I use and test. You can try changing Settings > Display Method to see if that makes a difference as this part of the UI uses OpenGL, which makes behavior depend on compatibility with its implementation (driver).

i used the apt package manager(bookworm repository)  and the version is Shotcut 22.12.22 and i switched to mesa(software) but no luck , i'havent got the chance to test using this filter  on other linux distros yet but i will comeback to you on that a bit later.

**Comment by ddennedy** [comment]
You are using an old, unsupported version. You can use one of the builds we provide on our download page.

**Comment by gl0wplatinum** [comment]
Thank you sir for your help , it feels smoother and snappier after installing it from the official website and evreything now works as intended.
