### ISSUE TITLE
1080p HEVC Main Profile GPU export adds extra pixels

### ISSUE THREAD

**Issue by Medi223** [mltframework/shotcut#1557]
> OS: Fedora Linux 40 (Workstation Edition)
> KERNEL: 6.9.9-200.fc40.x86_64
> CPU: AMD Ryzen 7 5700X 8-Core
> GPU: AMD Radeon RX 7800 XT (radeonsi, navi32, LLVM 18.1.6, DRM 3.57,)
> GPU DRIVER: 4.6 Mesa 24.1
> RAM: 32 GB                     
> 
> SHOTCUT VERSION: 24.06.26 from Flathub

**Issue:** Exporting a 1920x1080 video using the HEVC Main Profile preset, with Hardware Encoding enabled, renders a 1920x1088 video with an empty line at the bottom.

H.264, VP9, AV1 have no issues. Rendering via CPU is fine. HEVC+GPU at 720, 1440, and 2160 is fine. Only 1080+GPU+HEVC renders with 8 extra pixels, even if I switch to MKV, or disable parallel processing. Rendering at 1072 does not add the 8 extra pixels to make 1080. No issue using Handbrake.

**Export Job Log:**
```
[hevc @ 0x7f706c00a9c0] VPS 0 does not exist
[hevc @ 0x7f706c00a9c0] SPS 0 does not exist.
[AVHWDeviceContext @ 0x7f7074002180] Trying to use DRM render node for device 0.
[AVHWDeviceContext @ 0x7f7074002180] libva: VA-API version 1.19.0
[AVHWDeviceContext @ 0x7f7074002180] libva: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
[AVHWDeviceContext @ 0x7f7074002180] libva: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/radeonsi_drv_video.so
[AVHWDeviceContext @ 0x7f7074002180] libva: Trying to open /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeonsi_drv_video.so
[AVHWDeviceContext @ 0x7f7074002180] libva: Found init function __vaDriverInit_1_19
[AVHWDeviceContext @ 0x7f7074002180] libva: va_openDriver() returns 0
[AVHWDeviceContext @ 0x7f7074002180] Initialised VAAPI connection: version 1.19
[AVHWDeviceContext @ 0x7f7074002180] VAAPI driver: Mesa Gallium driver 24.1.3 for AMD Radeon RX 7800 XT (radeonsi, navi32, LLVM 17.0.6, DRM 3.57, 6.9.9-200.fc40.x86_64).
[AVHWDeviceContext @ 0x7f7074002180] Driver not found in known nonstandard list, using standard behaviour.
[mlt_buffer @ 0x7f70742720c0] w:1920 h:1080 pixfmt:nv12 tb:1048603/30960000 fr:30960000/1048603 sar:88889/50000 csp:unknown range:unknown
[hevc_vaapi @ 0x7f70740019c0] Input surface format is nv12.
[hevc_vaapi @ 0x7f70740019c0] Using VAAPI profile VAProfileHEVCMain (17).
[hevc_vaapi @ 0x7f70740019c0] Using VAAPI entrypoint VAEntrypointEncSlice (6).
[hevc_vaapi @ 0x7f70740019c0] Using VAAPI render target format YUV420 (0x1).
[hevc_vaapi @ 0x7f70740019c0] Using CTU size 64x64, min CB size 8x8.
[hevc_vaapi @ 0x7f70740019c0] RC mode: CQP.
[hevc_vaapi @ 0x7f70740019c0] Block Level bitrate control: OFF.
[hevc_vaapi @ 0x7f70740019c0] RC quality: 28.
[hevc_vaapi @ 0x7f70740019c0] RC framerate: 1181/40 (29.52 fps).
[hevc_vaapi @ 0x7f70740019c0] Driver does not report any additional prediction constraints.
[hevc_vaapi @ 0x7f70740019c0] Using intra and P-frames (supported references: 1 / 0).
[hevc_vaapi @ 0x7f70740019c0] Driver does not support some wanted packed headers (wanted 0xd, found 0x1).
[hevc_vaapi @ 0x7f70740019c0] Using level 4.
[hevc @ 0x7f706c00bd00] VPS 0 does not exist
[hevc @ 0x7f706c00bd00] SPS 0 does not exist.
[hevc @ 0x7f706c04dac0] VPS 0 does not exist
[hevc @ 0x7f706c04dac0] SPS 0 does not exist.
[producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[AVIOContext @ 0x7f706c012300] Statistics: 67903 bytes read, 0 seeks
[hevc @ 0x7f706c177600] VPS 0 does not exist
[hevc @ 0x7f706c177600] SPS 0 does not exist.
[chain avformat-novalidate] /home/gavint/Videos/random videos/Possible M1A2 Abrams SEPv3.mp4
    checking VFR: pkt.duration 1048603
[mlt_buffer @ 0x7f70742720c0] video frame properties congruent with link at pts_time: NOPTS

[mp4 @ 0x7f7074000f40] Timestamps are unset in a packet for stream 1. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[mp4 @ 0x7f7074000f40] Encoder did not produce proper pts, making some up.
[mp4 @ 0x7f7074000f40] Starting second pass: moving the moov atom to the beginning of the file
[AVIOContext @ 0x7f707429c700] Statistics: 32354429 bytes read, 0 seeks
[aac @ 0x7f7074203500] Qavg: 25102.926
[AVIOContext @ 0x7f70741fbac0] Statistics: 64720562 bytes written, 4 seeks, 251 writeouts
[AVIOContext @ 0x7f706c00f600] Statistics: 59518195 bytes read, 0 seeks
[AVIOContext @ 0x7f706c049f00] Statistics: 63345729 bytes read, 1 seeks
Completed successfully in 00:00:04
```

Export settings
![shotcutbug](https://github.com/user-attachments/assets/20f00cdc-a544-4bfd-98cb-aa963aa2ed85)

Video comparison (extra pixels on right side):
![Screenshot from 2024-07-21 20-27-17](https://github.com/user-attachments/assets/042b8b09-be72-47ed-adab-e5bdac157a35)

**Comment by bmatherly** [comment]
The 1920x1088 issue is a common bug dating back to the early days of MPEG2. The encoder encodes in blocks of 16x16. But 1080 is not divisible by 16. So 1088 pixels are encoded and the sequence header is used to signal that only 1080 pixels are active. If the encoder does not put the proper signaling in the sequence header, the decoder will assume all 1088 pixels are active. This problem is so pervasive, that most decoders will assume 1080 active pixels if they see 1088. Unfortunately, this is a bug in your VAAPI encoder and I don't think there will be anything Shotcut can do about it. You can try a different video card, or or a different driver.

**Comment by Medi223** [comment]
Oh wow, thanks for the info. It was such a specific bug I didn't think to search for it online, but it instantly comes up.

I've been using Shotcut for years, and this bug only appeared recently. I figure it might resolve itself after a few updates, or not.

I'll try using the .rpm of Shotcut, but I'll close the issue for now.

**Comment by Medi223** [comment]
Just adding that the issue persists with the .rpm version from rpmfusion.
