### ISSUE TITLE
how can i save the audio language 

### ISSUE THREAD

**Issue by damingchuanqi** [mltframework/shotcut#1561]
how can i save the audio language 

i use this filter

    <filter id="filter11">
      <property name="mlt_service">avfilter.ametadata</property>
      <property name="av.key">language</property>
      <property name="av.value">eng</property>
    </filter>

But it didn't take effect

**Comment by damingchuanqi** [comment]
I also tried metadata and avformat.alang, but they didn't take effect

**Comment by ddennedy** [comment]
https://forum.shotcut.org/t/embedding-metadata-into-exports/14806

**Comment by bmatherly** [comment]
I recreated alang is not working. It is fixed for the next release.

You will be able to set it in the "Other" tab:
![image](https://github.com/user-attachments/assets/6955b414-04e9-4d9d-839c-e444b1cdf885)
