### ISSUE TITLE
About window context is not translated (translation availble)

### ISSUE THREAD

**Issue by bovirus** [mltframework/shotcut#1563]
@ddennedy 

- About window 

The content of "About" window seems not translated also if the translation si availble in relative language

![image](https://github.com/user-attachments/assets/74ff9a37-f57b-4618-bfe0-d6765c1ea39d)

This the Italian language where Italian translation is available.
But relative window contains text in English.

- Qt library about bwindow

How can help you with "About Qt Library" window?

![image](https://github.com/user-attachments/assets/28f4b9fd-0a0e-4c24-9b10-5e84abb86e72)

The translation is not complete.

I developped the update for this language file.

**Comment by ddennedy** [comment]
Translation is turned off for the About Shotcut because most of the text should not be translated and some translators were breaking the HTML and links.
The About Qt dialog translation comes from the Qt Library.

**Comment by bovirus** [comment]
@ddennedy 

Please consider to enable the About window because the transltor spent time to translate relative strings.
If the relative strings are not used has no sense to have this in language file.

The QtLanguage library (for my language) has no update fofroms everal eyars.
I asked to somene of qt italian team to post my qt library translation updated but no one of qt Italian team answered me.
If you can accept I can provide the qt library updated to have About Qt library translated.

**Comment by ddennedy** [comment]
Maybe you see it in the language file because it was translatable at some point but is not longer. I have to check the English file and will remove it if it’s still there. But maybe transifex keeps it? I don’t want  to re-enable it.

**Comment by bovirus** [comment]
@ddennedy

Yes it's includee d as stringsin tarnsisflex.

I belieeve that to be a good choice instead to re-enable the translation aof "About" window to ahve less as possible part untranslated.

Please tell me what do you like about QT Libraryu about window.

I posted a PR with the changes to enable Italian language for the installer.

**Comment by ddennedy** [comment]
I checked that the About dialog is no longer in the text of the translation files in the source, and I have not changed my mind to re-enable it,

**Comment by bovirus** [comment]
And what's about QT Libarry?

changes with my Qt-base_it.qm

![image](https://github.com/user-attachments/assets/cd3f5c1b-c997-4a0f-95ee-29fa0d4871c0)

**Comment by ddennedy** [comment]
The Qt languages are included from a special location per its SDK or installation (distribution). It is not a manual process. I am not going to make an exception for one language. I cannot verify that your changes to  legal text is correct.

**Comment by bovirus** [comment]
@ddennedy 

I agree with you.
But on the other side is aneverneding story.
No one of of Italian qt offciial team follow the Italian translations that are quite old and with many strings untranslated.
After a lot of time spent asking to someone of official qt it team to check and load new translation I should made it myself.
