### ISSUE TITLE
filter suggest

### ISSUE THREAD

**Issue by ckappgit** [mltframework/shotcut#1565]
I suggest adding a partial mosaic filter to the Shotcut software. Currently, the process of applying partial mosaic to videos is quite cumbersome and can lead to unnecessary video tracks, and it's prone to repetitive work when performing batch operations. Introducing this filter would not only effectively simplify the existing workflow but also enhance the user experience without altering the current logic.

**Comment by ddennedy** [comment]
A) This is for bug reports only. 
B) You don't need multiple tracks; you are probably doing it the least efficient way.
C) There is a Filter Sets with "Obscure With Mosaic" and "Obscure With Blur".
D) There is also a **Spot Remove** filter that some people use.

Here is [documentation](https://forum.shotcut.org/t/table-of-contents/43285) for you to read.

**Comment by ckappgit** [comment]
Thank you for your reply. However, I've found an issue where the Obscure with Mosaic filter is not adding mosaic correctly at the edges, and this problem can be replicated on both Linux and Windows. I'm unsure if it's intentional or a bug.
@ddennedy 
![2024-08-09_10-07](https://github.com/user-attachments/assets/1a895201-4ad6-49b6-bf9c-6544c74e6fa5)

**Comment by ddennedy** [comment]
> Obscure with Mosaic filter is not adding mosaic correctly at the edges,

You need to change **Mask: Simple Shape > Softness**.

**Comment by ckappgit** [comment]
Again, thank you for your reply. I suggest setting the default configuration of "Softness" in "Obscure With Mosaic" and "Obscure With Blur" to 0,as people who generally use this feature are doing so to avoid legal risks, and without double checking like I did to find out that people with this feature will suffer the risks

**Comment by ddennedy** [comment]
OK, I will, but keep in mind that defaults, stock presets, and stock sets are all starting points and not legal tools.
