### ISSUE TITLE
Crop filters always get enabled when selected

### ISSUE THREAD

**Issue by Jowan-Spooner** [mltframework/shotcut#1566]
Windows 10, Shotcut 24.08.03 (also on 24.6.26)

Steps to reproduce:
- Add a crop filter (Crop Rectangle or Circle) to a track or clip. 
- Disable the filter.
- Add another Filter (any will do)
- Select the crop filter -> It get's enabled

This is most annoying when the first filter is a crop filter that you don't want to have enabled right now, because the first filter always get's auto-selected when clicking a clip or track, meaning the crop filter will get enabled every time.

This isn't a very big problem, because I could delete the filter, but I often like to keep filters disabled instead, so I can play around with them again later.

Thanks in advance ;)

**Comment by Jowan-Spooner** [comment]
@ddennedy Thanks for fixing this! 
Maybe this has already gotten fixed as well, but I just noticed that the same thing happens to the `Drop Shadow` filter. Should I report that as a separate bug? It seems very similar to this one.

**Comment by ddennedy** [comment]
The problem affected any filter with a color picker directly on its parameter UI, but I had not extended the fix to other filters until now.

**Comment by Jowan-Spooner** [comment]
I see! Thanks for the quick fix and all your work, looking forward to the next version 😄!
