### ISSUE TITLE
shotcut-linux-x86_64-240626.AppImage crashes on export

### ISSUE THREAD

**Issue by takesnodamage** [mltframework/shotcut#1568]
shotcut-linux-x86_64-240626.AppImage freezes and must be killed after hitting the Export button on Ubuntu 22.04.4 LTS. Rolling back to either 230729 or 240428 AppImages works as expected.

I had about a dozen clips that I wanted to apply a volume increase filter on, so I saved them as a file then opened the file as a clip so they appeared as a single segment. After adding the Gain filter I hit Export and the window freezes and cannot be interacted with. I have to Ctrl+C in the terminal to end the program.

**Comment by ddennedy** [comment]
Sorry but I do not reproduce that (using same IS and AppImage), and I will be unable to fix it for you. Maybe you can fix it.

**Comment by ddennedy** [comment]
Maybe you experienced an anomaly. Did you try more than once in that version and experience the same thing? Did the file save dialog appear?

**Comment by takesnodamage** [comment]
I tried several times with the same result. The video files were originally on an SD card so I tried moving them over to the HD and re-importing them all, same crash. The save box does not appear, the UI freezes as soon as I hit the Export button. If it makes a difference, I was using the Xubuntu release of Ubuntu.

**Comment by ddennedy** [comment]
I ran Xubuntu 22.04.4 in a virtual machine, and the Shotcut 24.06 AppImage Export works for me.
![image](https://github.com/user-attachments/assets/5d8de2a3-72a7-418b-b8fc-eec956ce5967)
![image](https://github.com/user-attachments/assets/bf3378c5-6097-4a05-b6da-4b67fcad65e4)

**Comment by ddennedy** [comment]
Does File > Save As... work?
