### ISSUE TITLE
Shotcut is reseting it's interface everytime it is minimized

### ISSUE THREAD

**Issue by raulgrangeiro** [mltframework/shotcut#1571]
Good evening, guys,

I'm starting to use Shotcut and I'm enjoying it very much, but I found an issue that's a bit annoying: everytime you minimize the software it resets the modifications on the sizes of windows inside it's interface.

Would it be possible to fix?

I'm running the Snap version 24.08.17 (beta, which is the only one which works #1569)  on Ubuntu 24.04 LTS above this hardware:

CPU: AMD Ryzen 7 5700U
GPU: AMD Radeon Vega 8
RAM: 20GB DDR4 3200MHz
SSD: WD SN530 512GB M.2

I've recorded a video to show you the issue:

[Video on YouTube](https://youtu.be/3yqryQNm3LY)

**Comment by ddennedy** [comment]
This is a bug specific to Wayland or whatever window manager is running on Wayland. It does not occur on X/Linux, macOS, or Windows. The problem occurs because the maximized window state is not restored properly by the window manager. The problem goes away if you take the app out of the maximized state. I do not think this is not something I can fix in our code.

**Comment by raulgrangeiro** [comment]
> This is a bug specific to Wayland or whatever window manager is running on Wayland. It does not occur on X/Linux, macOS, or Windows. The problem occurs because the maximized window state is not restored properly by the window manager. The problem goes away if you take the app out of the maximized state. I do not think this is not something I can fix in our code.

Friend, thanks again for answering my questions. As you told me this workaround I noticed I can tweak the interface withou maximizing it and it will maintain that state everytime I start it.

At least it is a liveable bug.

God bless you!

**Comment by raulgrangeiro** [comment]
I reported this issue to Ubuntu team take care. If you want, tell them you are getting the same error when using the software to encourage them to fix it.

Link of the report: https://bugs.launchpad.net/ubuntu/+source/xwayland/+bug/2077635

God bless you!
