### ISSUE TITLE
Chroma Hold filter holds the opposite color

### ISSUE THREAD

**Issue by allekov** [mltframework/shotcut#1572]
Shotcut 24.06.26 installed as a flatpak on Debian 12.
Chroma hold filter seems broken - for e.g. if I pick blue it holds red, if I pick red it holds yellow, if I pick green it holds magenta etc. It seems as if it holds the opposite (bitwise) color
![hold blue](https://github.com/user-attachments/assets/167455aa-cc94-410d-bc53-2552b8bac151)
![hold green](https://github.com/user-attachments/assets/df009feb-7ac9-4324-8bb9-e286b66fb25a)
![hold red](https://github.com/user-attachments/assets/ad0e7d63-1da0-4615-bb50-c206566d6a46)
![no filter](https://github.com/user-attachments/assets/c7bc9e07-ef88-4e6b-a5f6-5c9b8b435608)

**Comment by ddennedy** [comment]
Thank you for the good find and report.
