### ISSUE TITLE
Different interfaces for Snap and Flatpak

### ISSUE THREAD

**Issue by raulgrangeiro** [mltframework/shotcut#1573]
Good morning, friends,

I've noticed a difference between interfaces of Shotcut in different packages: Snap and Flatpak. I'm using Ubuntu 24.04 LTS with Gnome 46 above Wayland.

Here is the interface of Shotcut Snap 24.08.17 beta:

![Snap version](https://github.com/user-attachments/assets/eecce298-b3b3-4248-bcd4-fc5a53497fd4)

And here is the interface of Shotcut Flatpak 24.06.26:

![Flatpak version](https://github.com/user-attachments/assets/fe62c926-f95f-41da-b5e5-37d31b53c117)

Note that the Flatpak version has buttons on the top right corner that allows user to change the mode: Logging, Editing, FX, Color, Audio and Player, but the Snap version has none of these buttons.

Why does that happen to the Snap version? Also the Windows version has these buttons.

God bless you!

**Comment by ddennedy** [comment]
The newer version in snap added another icon on the toolbar (Subtitles), and now your window is not wide enough to show the workspace switcher. This is also compounded by showing text under icons and your translations, some of which are long. In the View menu you can turn off text under icons.

**Comment by raulgrangeiro** [comment]
> The newer version in snap added another icon on the toolbar (Subtitles), and now your window is not wide enough to show the workspace switcher. This is also compounded by showing text under icons and your translations, some of which are long. In the View menu you can turn off text under icons as well as access the workspaces under View > Layout.

Good afternoon, friend. I thought it was a bug. Thanks for answering me.

My screen is a default 1080p: 1920x1080, I didn't know this size was small. I'll try removing the text under the icons.

God bless you!

**Comment by ddennedy** [comment]
The problem does not happen in the English version with default settings. The problem with defaults is parly due to the translations not being mindful about the user experience. That happens a lot. The translator might be too literal, but also it could be the correct expected translation for this kind of application. I cannot make it all fit for any conceivable translation without making some sacrifice. The defaults are suitable for beginners, and for beginners this part of the UI is the best thing to sacrifice. So, it is working as expected.

**Comment by raulgrangeiro** [comment]
> The problem does not happen in the English version with default settings on 1920x1080. System level display scaling and text size are additional factors. This is with 100% and normal text size:
> 
> ![image](https://private-user-images.githubusercontent.com/1146683/360664201-ac43652b-7b55-45f8-a038-b4a5f1230065.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NzE2OTIsIm5iZiI6MTcyNDY3MTM5MiwicGF0aCI6Ii8xMTQ2NjgzLzM2MDY2NDIwMS1hYzQzNjUyYi03YjU1LTQ1ZjgtYTAzOC1iNGE1ZjEyMzAwNjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjZUMTEyMzEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2NiZGU4OWZkN2U0MGNiNjI0MWQ1MWViZGEwZThjZWU5YzU0ZDA4YjEzZTQxMDk5NjdmZWZhYmQ1NGI2MWEzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HEplpODGzKga-nfRKEwdfHS8HY4x32q8kIsCLWv_Bts)
> 
> The problem with defaults is partly due to the translations not being mindful about the user experience. That happens a lot. The translator might be too literal, but also it could be the correct expected translation for this kind of application. I cannot make it all fit for any conceivable translation without making some sacrifice. The defaults are suitable for beginners, and for beginners this part of the UI is the best thing to sacrifice. So, it is working as expected. If you have a better idea how to translate these icons use https://www.transifex.com/ddennedy/shotcut/ The icon label should be very short, single word if possible. Each one has a tooltip that can have a longer description.

Good morning, @ddennedy,

My sysem is 100% scale and in Shotcut I didn't change anything about scale from default, how did you manage to have your screen seeming so large with the icons? The default for me was those screenshots I sent you.

**Comment by raulgrangeiro** [comment]
@ddennedy , I would like to thank you for fixing the app. I just saw the new release and the snap now is running better than before, and even the selector of types of Logging, Editing, FX and others appear just fine now on Ubuntu 24.04 LTS. You are an awesome guy! God bless you!

![Captura de tela de 2024-08-30 11-29-57](https://github.com/user-attachments/assets/b5969f5c-00f1-414c-a14f-d6866e728fdb)
