### ISSUE TITLE
[Question] Are all aac files non-seekable or did I missed something?

### ISSUE THREAD

**Issue by catscarlet** [mltframework/shotcut#1576]
I was trying to import an AAC file which I detached from a MP4/M4A file by FFMPEG, but Shotcut 24.08.29 showed it is non-seekable and refused to import.

![screenshot_on_b85m_by_flameshot_at_2024-09-10_16-57-27](https://github.com/user-attachments/assets/a2dac2de-f9cf-49ea-ad23-021c1c18aeb2)

Then I tried the MP4/M4A file and it worked fine with Shotcut. (made sure the encoded-audio-file is fine)

(I would still prefer AAC files because some of my old hardware only recognizes AAC file, not mp4/m4a)

**Are all aac files non-seekable? Or did I missed something when detaching? I used command line like this to detach.**

`ffmpeg -i h264-video-with-aac-audio.mp4 -vn -acodec copy audio-only.aac`
`ffmpeg -i waterfront.m4a -vn -acodec copy waterfront.aac`

**Comment by bmatherly** [comment]
>Are all aac files non-seekable?

Yes. Raw AAC does not have any header information or index. And the frames are variable size. So Shotcut can not accurately seek to a specific position in the file.

**Comment by catscarlet** [comment]
> > Are all aac files non-seekable?
> 
> Yes. Raw AAC does not have any header information or index. And the frames are variable size. So Shotcut can not accurately seek to a specific position in the file.

Thanks.
