### ISSUE TITLE
Additional track will be added, when drop a single image/video-clip on timeline

### ISSUE THREAD

**Issue by chenx77** [mltframework/shotcut#1577]
Prosess to reproduce:
0. Launch Shotcut;
1. Drag and drop an image / a clip of video to the Playlist;
2. Drag and drop above item from Playlist to Timeline;
Expected result: a video track V1 created with the new item dropped to the Timeline.
Actual result:  video track created as V1, and another redundant video track V2 appears too without any image/video item.

This observation is found on following Windows Shotcut versions:

> commit 0739f1681b165ba01e8db55295da1ed525f2c5f8
> Date:   Mon Sep 9 21:33:35 2024 -0700

An attempted fix (following) didn't thoroughly fix it 

> commit bc4e62735ca34cc5e7c0bef31841947f509a8a25
> Date:   Sun Aug 25 12:51:14 2024 -0700
> 
>     fix drop single clip on empty timeline adds too many tracks

This 'feature' started to appear at least since the beginning of 2024

Screenshot:
![Screenshot (1910)](https://github.com/user-attachments/assets/24d24679-2537-4ce3-a59f-49c846a271b0)

**Comment by ddennedy** [comment]
Is Settings > Timeline > Automatically add tracks turned on?

**Comment by chenx77** [comment]
Oh, Yes! I didn't notice this feature.

After turning this off, the reported issue gone.

**Comment by chenx77** [comment]
> I am a little surprised since it is Off by default.

Indeed, it should be turned off by default. 

This feature is also saved by previous session. But I don't remember I have used this toggerable feature in the past. So it's default.

Anyway, do you think automatically adding a redundant track is necessary?
