### ISSUE TITLE
Please can you make a new release folder for MacOS emergency fix 24.09.19, or as new "unified" release number?

### ISSUE THREAD

**Issue by J-A-M-E-5** [mltframework/shotcut#1584]
You put the special MacOS release 24.09.19 in the old 24.09.13 folder which is causing downstream issues.

See: https://github.com/mltframework/shotcut/releases

As you have deleted MacOS 24.09.13 it now no longer installs even old version, this is causing downstream issues in homebrew: https://github.com/Homebrew/homebrew-cask/pull/186487#issuecomment-2372561628

Thanks

**Comment by ddennedy** [comment]
I don't want to make a full new release right now. Try this
https://github.com/mltframework/shotcut/releases/tag/v24.09.19

**Comment by ddennedy** [comment]
Supporting software distributions systems is not a priority for me.
