### ISSUE TITLE
Can 24.09.19 be marked as `prerelease` or perhaps not `latest`

### ISSUE THREAD

**Issue by aptalca** [mltframework/shotcut#1586]
Hi, I'm with [linuxserver](https://www.linuxserver.io) and we publish a docker image for Shotcut: https://github.com/linuxserver/docker-shotcut

We have a ci that checks the latest releases in the upstream repo hourly and builds a new docker image.

The latest release 24.09.19 is a platform specific release and is missing the assets for other platforms but it is marked as the latest stable release. Therefore it is causing our ci to attempt and fail a build every hour.

I would like to humbly request that the release in question be marked either as a `prerelease` on github or alternatively `not latest` so our ci can rest easy 😅

Thanks

**Comment by ddennedy** [comment]
No, Homenbrew needs it. Can't make everyone happy all the time.

**Comment by aptalca** [comment]
In that case, a full release with all assets might please everyone.

**Comment by ddennedy** [comment]
It does not please me who has to do some manual work to make it happen. Sounds like your system needs a change to limit the number of retries.

**Comment by ddennedy** [comment]
I switched it back.

**Comment by aptalca** [comment]
Thanks, much appreciated.
