### ISSUE TITLE
export markers bug

### ISSUE THREAD

**Issue by connma** [mltframework/shotcut#1588]
Hello,

Using Microsoft Windows 10 Pro and Shotcut 24.09.13

When exporting the markers, even if the "Include ranges (Duration > 1 frame)?" is checked, it only exports the Start point of each marker, not the End nor the Duration.
Did I understand wrongly this feature or is it a bug?
The duration of my markers are much more than a frame (although some are without durations)

Thanks in advance!

**Comment by ddennedy** [comment]
Working as intended. The chapters text is basically designed to work for YouTube. Since then, some other services and software support it too. There is no standard for it, but I don’t want to output something that does not work in YouTube.
