### ISSUE TITLE
Memory leaks caused by multitrack() and track() calls

### ISSUE THREAD

**Issue by bmatherly** [mltframework/shotcut#1592]
The following functions return "new" objects:

Mlt::Multitrack::Track()
https://github.com/mltframework/mlt/blob/c75721eaae09196cb523132d63f40efc3882eecd/src/mlt%2B%2B/MltMultitrack.cpp#L87

Mlt::Tractor::Multitrack()
https://github.com/mltframework/mlt/blob/c75721eaae09196cb523132d63f40efc3882eecd/src/mlt%2B%2B/MltTractor.cpp#L94

Mlt::Tractor::Track()
https://github.com/mltframework/mlt/blob/c75721eaae09196cb523132d63f40efc3882eecd/src/mlt%2B%2B/MltTractor.cpp#L124

There are multiple instances in Shotcut where we call these functions without deleting the returned objects.

As an example, this line calls both Multitrack() and Track() without freeing either returned object. So two objects are being leaked.
https://github.com/mltframework/shotcut/blob/f922f5b49c8996ee244d667c6283a068aa3cc8e9/src/commands/timelinecommands.cpp#L1496

The purpose of this issue is to remind us to do a search through the code to seek out these leaks and clean them up.
Any volunteers who want to work on this should assign this to themselves to let others know that they are working on it.

**Comment by ddennedy** [comment]
Qt Creator makes this task easy for me by searching for all references to a symbol. BTW it cannot find references using the old style `connect(SIGNAL() .. SLOT())` methods, which is one reason why I try to avoid introducing them.

During this, it surfaced some usage of bare pointers that I replaced. It is easier to locate these locates by looking for results without `QScopedPointer` or `std::unique_ptr`.

**Comment by bmatherly** [comment]
> BTW it cannot find references using the old style connect(SIGNAL() .. SLOT())

I agree - I always try to use the new style as well. Do we have any interest in a clean-up task to convert the remaining instance of old connect statements? Maybe the risk is not worth the reward.
