### ISSUE TITLE
Can shoutcut add transitions other than movit.luma_mix?

### ISSUE THREAD

**Issue by liubailin2017** [mltframework/shotcut#1598]
It seems shotcut only supports movit.luma_mix. I added the gltransition(https://gl-transitions.com/) in mlt. 
 eg. melt d.mp4 out=:4.0  -track e.mp4 out=:4.0 -transition movit.cube  in=:0.0 out=:4.0 a_track=0 b_track=1 -consumer sdl2 
 Can I integrate movit.cube into shotcut?

**Comment by ddennedy** [comment]
Not at this time. If you plan to make a pull request to MLT for that it should not be in the movit module or have the name prefix with “.movit” as that refers to a library dependency.

**Comment by liubailin2017** [comment]
I have tried adding gltransition to movit and tested the effect with melt. But I don’t know how to add shotcut
