### ISSUE TITLE
Shotcut 24.10.29 is not showing the controls on the corner like past version

### ISSUE THREAD

**Issue by raulgrangeiro** [mltframework/shotcut#1600]
Good morning, friend,

I received an update of Shotcut to version 24.10.29 Snap, and with it I lost the ability to use the controls on ther superior right corner. On the past version I had it. Could you please help me with that?

I'm sensind a video showing you the issue.

I'm using Ubuntu 24.04.1 LTS with Gnome 46 on Wayland on a 1920x1080p screen.

God bless you!

https://github.com/user-attachments/assets/a66b3cfe-36a2-4fa2-96a3-3ed2460fc3ad

**Comment by ddennedy** [comment]
Not a bug. Your translation makes the toolbar icons too wide and there is no more room. See what happens when you make the window as small as possible: you lose toolbar icons. Use the View menu for when things fall away on the main toolbar. In there you also turn off text under the icons.

**Comment by raulgrangeiro** [comment]
> Not a bug. Your translation makes the toolbar icons too wide and there is no more room. See what happens when you make the window as small as possible: you lose toolbar icons. Use the View menu for when things fall away on the main toolbar. In there you also turn off text under the icons. Why did it change? Because another icon was added or the translation changed.

Thank you for answering me!

May I ask you why the previous version supported all the icons on the screen?

**Comment by ddennedy** [comment]
I ALREADY TOLD YOU!

**Comment by ddennedy** [comment]
A remedy: in the View menu, turn off **Show Text Under Icons**

**Comment by raulgrangeiro** [comment]
> I ALREADY TOLD YOU!

Not my question but thank you again.

> A remedy: in the View menu, turn off **Show Text Under Icons**

I'll do that!
