### ISSUE TITLE
Problem with Fade Out Video

### ISSUE THREAD

**Issue by He-Zu** [mltframework/shotcut#1605]
Linux Shotcut version 24.10.29

fade out video does not work if a second video track exists
see example in the attached video
What am I doing wrong?

https://github.com/user-attachments/assets/bb3821d1-cd95-47ff-affd-88eb23894289

**Comment by ddennedy** [comment]
Fade on a video track that is not bottom fades **opacity**. In order to see an effect involving translucency, there needs to be something **below**. You can select the fade filter in Filters panel and click the checkbox to turn off fade opacity. I am not going to change this behavior.
