### ISSUE TITLE
Text flickering and buging after export

### ISSUE THREAD

**Issue by MoutonBinoclard** [mltframework/shotcut#1606]
Windows 10, Last version, Shotcut version 24.10.29

Hey, i'm making a short video, but somehow after exporting, some of my text are getting "glitchy" ?
I don't know what is causing this, I tried both exporting with integrated gpu, or x64 only, but nothing changes
Here's some frame 
![image](https://github.com/user-attachments/assets/8fc0da58-a04d-4403-a455-38cdd156bed0)
![image](https://github.com/user-attachments/assets/21fd4eee-6117-4673-b977-612a62020a13)
![image](https://github.com/user-attachments/assets/bc6fc83e-7e37-4b5f-af9e-a85b494812fa)

![image](https://github.com/user-attachments/assets/53146586-3398-4e8a-906a-3f53f027a4ff)
![image](https://github.com/user-attachments/assets/d9f4dec6-67b3-4aa6-8ad6-b55c0a396c44)

the first text only bug after the zoom position thing takes action, but in the preview nothing happens

**Comment by ddennedy** [comment]
Try turning off Export > Advanced > Video > Parallel processing.

You can try a different font. Some people have reported weird problems using certain stylized or amateur fonts.

I do not understand “zoom position thing.” You should use the exact words of things in the English version of the UI in bug reports.

You did not provide steps to reproduce. We need to know exactly what filters you are using, their parameters, and maybe the video mode and export settings.

**Comment by MoutonBinoclard** [comment]
Ok this works, thanks so much
