### ISSUE TITLE
Flatpak version doesn't launch on Linux Mint

### ISSUE THREAD

**Issue by SpeeQz1** [mltframework/shotcut#1612]
Flatpak Shotcut won't open when launching it on Linux Mint, surprisingly the `.deb` and `AppImage` version do work.

![image](https://github.com/user-attachments/assets/fe13c298-adea-42af-aa2e-4f05f4c8ae37)

When trying to run the flatpak in terminal:
```
Gtk-Message: 22:21:43.196: Failed to load module "xapp-gtk3-module"
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
---
formats:
  - a64
  - ac3
  - ac4

...
# Just prints out more formats and codecs
```

Shotcut Version: 24.11.17 Flatpak
OS: Linux Mint 22 (Cinnamon)

**Comment by ddennedy** [comment]
I installed Mint 22 Cinnamon in a virtual machine and the Shotcut flatpak, and it worked for me:
![image](https://github.com/user-attachments/assets/411a5437-a701-46ae-82c6-8f48024c006c)

I too get the warnings about `xapp-gtk3-module` and `libDeckLinkAPI.so`. The DeckLink message is well known and not an error. That is an optional user-space driver for specialized video production hardware. 

I guess something else installed on your system is causing a problem, but Flatpak is usually more isolated than the portable or AppImage. 
🤷

**Comment by SpeeQz1** [comment]
> I installed Mint 22 Cinnamon in a virtual machine and the Shotcut flatpak, and it worked for me: ![image](https://private-user-images.githubusercontent.com/1146683/394459766-411a5437-a701-46ae-82c6-8f48024c006c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4Njc0NjUsIm5iZiI6MTczMzg2NzE2NSwicGF0aCI6Ii8xMTQ2NjgzLzM5NDQ1OTc2Ni00MTFhNTQzNy1hNzAxLTQ2YWUtODJjNi04ZjQ4MDI0YzAwNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTBUMjE0NjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDFiM2NjNWE1ZWMzMzZiZWU1NGViZTEyNWIyNjk2ZTMzN2I3Y2NjNTVlNzQyMzU0ZTkwNGNmMTAzNDcwNDM5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.c52gSsQfLeIODp6psr2IhaO8y_kuCncViq0wDwCGsls)
> 
> I too get the warnings about `xapp-gtk3-module` and `libDeckLinkAPI.so`. The DeckLink message is well known and not an error. That is an optional user-space driver for specialized video production hardware.
> 
> I guess something else installed on your system is causing a problem, but Flatpak is usually more isolated than the portable or AppImage. 🤷

Anyways to debug this then?

**Comment by ddennedy** [comment]
Of course there is a way to debug it, but I do not know from memory. Ask AI or search the web for how to debug a flatpak with gdb because that is what I would have to do and copy and paste here it for you.

**Comment by SpeeQz1** [comment]
> Of course there is a way to debug it, but I do not know from memory. Ask AI or search the web for how to debug a flatpak with gdb because that is what I would have to do and copy and paste here it for you.

Followed this documentation: [Debugging](https://docs.flatpak.org/en/latest/debugging.html)

```
GNU gdb (GDB) 15.2
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /app/bin/shotcut...
Reading symbols from /usr/lib/debug//app/bin/shotcut.debug...
(gdb) run
Starting program: /app/bin/shotcut 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff0b756c0 (LWP 27)]
[New Thread 0x7fffebfff6c0 (LWP 28)]
Gtk-Message: 01:30:54.548: Failed to load module "xapp-gtk3-module"
[New Thread 0x7fffea86c6c0 (LWP 29)]
[New Thread 0x7fffe8b456c0 (LWP 30)]
[New Thread 0x7fffd49ff6c0 (LWP 31)]
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
[New Thread 0x7fffd41fe6c0 (LWP 32)]
---
formats:
  - a64
  - ac3

...
# Rest of codecs and formats

Thread 1 "shotcut" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, 
    no_tid=no_tid@entry=0) at pthread_kill.c:44
44	      return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
```

**Comment by ddennedy** [comment]
Thanks, but it is better to have all of the lines after gdb command `bt` because the output is not useful (Shotcut does not call `pthread_kill`).

**Comment by SpeeQz1** [comment]
> Thanks, but it is better to have all of the lines after gdb command `bt` because the output is not useful (Shotcut does not call `pthread_kill`).

[gdb.txt](https://github.com/user-attachments/files/18091351/gdb.txt)

**Comment by ddennedy** [comment]
From this line in the debug output it looks like this version of Qt does fails with the OpenGL on your computer

> #12 0x00007fffd5869db1 in QXcbGlxIntegration::createPlatformOpenGLContext (this=0x5555564c9b20, context=<optimized out>) at /run/build-runtime/qt6-qtbase/src/plugins/platforms/xcb/gl_integrations/xcb_glx/qxcbglxintegration.cpp:158

**Comment by SpeeQz1** [comment]
> From this line in the debug output it looks like this version of Qt fails with the OpenGL on your computer
> 
> > #12 0x00007fffd5869db1 in QXcbGlxIntegration::createPlatformOpenGLContext (this=0x5555564c9b20, context=) at /run/build-runtime/qt6-qtbase/src/plugins/platforms/xcb/gl_integrations/xcb_glx/qxcbglxintegration.cpp:158

Here's my version:
OpenGL version string: 4.6.0 NVIDIA 550.127.08

**Comment by SpeeQz1** [comment]
@ddennedy After some more application usage I noticed this is a global issue with my system when it comes to flatpaks. For some reason some flatpaks would not run on my system when they run perfectly fine on a VM with the same version of Mint.
Any idea what could be causing this?

**Comment by ddennedy** [comment]
No, sorry, I do not know. The nvidia driver does not use Mesa, and it is generally extremely reliable for OpenGL compatibility.

**Comment by SpeeQz1** [comment]
Alright, this got solved due to a new update I received changing my drivers from 550.127 to 550.135.
All my problems with flatpaks got fixed.
