### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by tieugene** [mltframework/shotcut#165]
Fedora 21 linux:

bash-4.3$ qmake-qt5 && LC_ALL=C make                                                                                                                                               
cd CuteLogger/ && ( test -e Makefile || /bin/qmake-qt5 /mnt/shares/home/eugene/rpmbuild/BUILD/shotcut-15.12/CuteLogger/CuteLogger.pro -o Makefile ) && make -f Makefile            
make[1]: Entering directory '/mnt/shares/home/eugene/rpmbuild/BUILD/shotcut-15.12/CuteLogger'                                                                                      
g++ -c -pipe -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -O2 -fPIC -Wall -W -D_REENTRANT -DCUTELOGGER_LIBRARY -DQT_NO_DEBUG -DQT_CORE_LIB -I. -Iinclude -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -I. -I/usr/lib/qt5/mkspecs/linux-g++ -o Logger.o src/Logger.cpp                                                                                                             
src/Logger.cpp: In function 'void qtLoggerMessageHandler(QtMsgType, const QMessageLogContext&, const QString&)':                                                                   
src/Logger.cpp:261:10: error: 'QtInfoMsg' was not declared in this scope                                                                                                           
     case QtInfoMsg:                                                                                                                                                               
          ^                                                                                                                                                                        
Makefile:271: recipe for target 'Logger.o' failed                                                                                                                                  
make[1]: *** [Logger.o] Error 1                                                                                                                                                    
make[1]: Leaving directory '/mnt/shares/home/eugene/rpmbuild/BUILD/shotcut-15.12/CuteLogger'                                                                                       
Makefile:44: recipe for target 'sub-CuteLogger-make_first' failed                                                                                                                  
make: *** [sub-CuteLogger-make_first] Error 2

**Comment by metellius** [comment]
Likely qt version incompatibility, you need to supply more context. Also, you'll likely need much more than just 'qmake-qt5' for it to compile correctly with all dependencies. Compiling outside build-shotcut.sh is not officially supported.

**Comment by tieugene** [comment]
> Likely qt version incompatibility, you need to supply more context. 
Qt 5.4.2

> Compiling outside build-shotcut.sh is not officially supported.
There is no 'build-shotcut.sh' in src: https://github.com/mltframework/shotcut/archive/v15.12.tar.gz

**Comment by metellius** [comment]
Shotcut requires minimum 5.5.0

**Comment by ddennedy** [comment]
Not going to fix. This project is too complicated to try to address multiple versions of dependencies.
