### ISSUE TITLE
Wrong size for audio thumb image cache

### ISSUE THREAD

**Issue by j-b-m** [mltframework/shotcut#170]
Hi,

While working on audio thumbnails in Kdenlive, I noticed a small error in the image caching, and since I borrowed some Shotcut code, here is what I found:

in audiolevestask.cpp, line 170 where you create the image for caching:

 QImage image((count + 3) / 4, channels, QImage::Format_ARGB32);

In fact, the image width should be divided by the channel count, since channels are stacked vertically.
So the following would be more correct:

 QImage image((count + 3) / 4 / channels, channels, QImage::Format_ARGB32);

Not a huge issue, but in case you want to spare a few bits in mem...

regards

**Comment by ddennedy** [comment]
Thanks, JB
