### ISSUE TITLE
Support for render farms?

### ISSUE THREAD

**Issue by mathwhiz1212** [mltframework/shotcut#171]
I would like to use a linux render farm, is this possible with shotcut?

**Comment by ddennedy** [comment]
This area is only for defect tracking, not general Q&A. To answer your question, see [MLT](http://www.mltframework.org/) and its melt command line utility, which Shotcut itself uses for encoding in a background process. Therefore, every copy of Shotcut comes with melt. Shotcut saves to MLT XML, which melt can read and process.

**Comment by mathwhiz1212** [comment]
Sorry. I didn't know, next time I will ask questions in the right places. Thanks!
