### ISSUE TITLE
Transition Resizing Windows7-64 v16.01.02

### ISSUE THREAD

**Issue by najoco** [mltframework/shotcut#176]
After watching the the tutorial at https://www.youtube.com/watch?v=NUDCcq6WcJU , I am not able to increase the size of a video transition.  I can decrease it, but not increase.

**Comment by ddennedy** [comment]
It does not permit you (by design) to stretch a transition beyond the beginning or end of a clip.

**Comment by najoco** [comment]
In watching the video at the 2:45 mark, https://youtu.be/NUDCcq6WcJU?t=165, the presenter shows the created transition being increased. After the initial creation, I can decrease the size of the transition, but not increase it.  The is the issue I am having.

**Comment by ddennedy** [comment]
I am the presenter and creator of Shotcut. It works fine for me within the constraints I previously explained; I just tested it. Do you understand those constraints? If you really do believe there is still a problem, explain the exact steps. No, referring to the video is not good enough. Or, get the source code and try to fix it yourself.
