### ISSUE TITLE
Persistent crashes @ app startup (Despite multiple reinstalls)

### ISSUE THREAD

**Issue by sciom1001** [mltframework/shotcut#178]
Windows 7 64bit (latest updates)
i5 4590
R9  290x (Latest drivers)
8GB RAM
1TB WD blue
No other programs running.
Reinstalling and deleting app data files before reinstall not fixing the problem.
[shotcut-log.txt](https://github.com/mltframework/shotcut/files/83658/shotcut-log.txt)

**Comment by ddennedy** [comment]
It works for me on multiple systems and for thousands of other people. What do you expect us to do about it on your system? I have no idea why it does not work. Try fixing it yourself and submitting the fix or maybe again in a year from now to see if it got fixed by someone else.

**Comment by md81544** [comment]
I get the same problem. Given the attitude of the developer I think I'll just resort to uninstalling.

**Comment by md81544** [comment]
If anyone gets here looking for a solution, see https://www.reddit.com/r/shotcut/comments/44thzk/need_help_cannot_get_shotcut_to_start/d0mh3jo

**Comment by ddennedy** [comment]
Thanks @md81544. I will add something to the FAQ about this. I have mentioned this before to people on the G+ forum when it was clear that it used to start OK but suddenly stopped. In this case, it is not clear that was what had happened. The next step toward a real fix will be to remove one Shotcut registry item at time and test startup after removing it to find the one causing the problem.
