### ISSUE TITLE
Windows: pressing Enter in image duration field does not apply new duration.

### ISSUE THREAD

**Issue by ddennedy** [mltframework/shotcut#18]
Just worked for me on Linux. Windows only?

**Comment by apolakipso** [comment]
This also happens on OS X (Yosemite) with Shotcut 15.07 when trying to set the duration of Video or Audio fade-ins/fade-outs. The up/down buttons work, but entering values into the input has no effect at all (value is selectable by mouse, but the cursor immediately disappers when trying to type in a value, moving around or deleting text).

**Comment by ddennedy** [comment]
No @apolakipso it (the reported bug) does not happen on OS X - at least not for me. There are troubles with the filter timecode fields on OS X, but that is a different bug.

**Comment by apolakipso** [comment]
Sorry, looked close enough. I haven't found the filter timecode fields issue, is it on here?

**Comment by ddennedy** [comment]
fixed in v15.09
