### ISSUE TITLE
Filters do not work if speed is changed from 1.0

### ISSUE THREAD

**Issue by ddennedy** [mltframework/shotcut#184]
This is a bug on new speed effect in v16.01 regardless of OS. Open a video with audio clip. Change the speed to something like 0.5. Add a video filter such as Sepia. The filter does not apply its effect to the video. Saving as XML and viewing the XML shows there is actually no filter. It got rejected somehow. `melt timewarp:0.5:some.mp4 -attach sepia` does work.

**Comment by bmatherly** [comment]
Fixed by 858a4af4e7dfe81936d91ec77d071dda4a3b78fd
