### ISSUE TITLE
Clip speed can't be set to decimal if locale uses comma as decimal point.

### ISSUE THREAD

**Issue by mrtnxii** [mltframework/shotcut#186]
Basically when I want to set clip speed to i.e. 1,5 or 0,5, it resets to 1. Setting it to a round number like 2, 3, 5... works fine.

Windows 7 Ultimate 64-bit, Shotcut 16.01.02.

My locale is using comma as a decimal point, I've asked about the issue on shotcut subreddit and it was confirmed by another user that it only works with dots as decimal point.
https://www.reddit.com/r/shotcut/comments/42crmh/i_can_only_set_clip_speed_to_a_round_number/

**Comment by metellius** [comment]
Closely related to #166 (but unrelated codewise as far as I can tell). I'm also seeing this on linux. My temporary workaround is to set LC_ALL=en_US.utf-8 (it is normally nb_NO.UTF-8)

**Comment by ddennedy** [comment]
This was already fixed for next release. I reproduced it on Linux with v16.01, and verified it was fixed with nightly builds 16.01.24 for both Linux and Windows.
