### ISSUE TITLE
pcm_s16be audio stream in dv file is detected as pcm_s16le in audio properties

### ISSUE THREAD

**Issue by ognjenzz** [mltframework/shotcut#187]
tested on v16.01 and Win7 x64

ffmbc detects 

Input #0, dv, from 'test.dv':
  Duration: 00:02:33.56, bitrate: 28800 kb/s
    Stream #0.0(und): Video: dvvideo, yuv411p, 720x576i bff [PAR 16:15 DAR 4:3],
 28800 kb/s, 25.00 fps
    Stream #0.1(und): Audio: pcm_s16be, 48000 Hz, 2 channels, s16, 1536 kb/s

**Comment by ddennedy** [comment]
We are simply reporting what libavcodec from FFmpeg 2.7 is reporting. Even a newer pre-2.9 version of FFmpeg ffprobe gives me the same results (s16le). ffmbc tends to be dated, and I am inclined to trust newer ffmpeg versions to be more correct. Ultimately, you need more concrete evidence (i.e. a specification) to support your claim and report it to the FFmpeg project as this is not from our code base.
