### ISSUE TITLE
Some filters settings are not applied/stored correctly

### ISSUE THREAD

**Issue by peossource** [mltframework/shotcut#189]
Hi,

there are some filters which are not "considered" during encoding.

I have a timeline with several clips. Each clip has its filters. The Fade In/Out Audio/Video filters are working well but not "White Balance", "Color Grading" or "Normalize(Audio)" for instance.

ShotCut 16.01.02 on KUbuntu 15.04
Project is 1080p50 with 1080p50 clips

Thanks,
Christian

**Comment by ddennedy** [comment]
I am not able to reproduce this with the White Balance or Color Grading filters with GPU processing enabled or disabled. Is GPU processing enabled?

Is the problem with a combination of filters in a certain order on the clip? First, I only tested 1 White Balance on first clip and 1 Color Grading on second clip. Then, I made another test with same arrangement but added fade in and out to each of them. Still not able to reproduce.

**Comment by peossource** [comment]
I have to rename this issue.
For testing today I reopened my project file again and noticed that the project is exactly the same what was encoded yesterday. In point of fact the filters are active but have totally different values as I had yesterday in ShotCut. It seems that there is a problem in ShotCut that sometimes filter setting are not applied/stored correctly in XML.

For further testing I saved I copy of my project and did all filter settings (colour grades, whitepoint) again. For your information - these clips are shots of my daughter during her skiing course and every clip has an different white point. I got a perfect result as expected. After reopening all remains good. Yesterday I have not tried this.

There must be a bug in the GUI. I can remember that I had different white points yesterday when I played clips from the Playlist and after putting it on a time line track. I checked if there is a track filter active... no, nothing!

I also can remember that I had trouble with a "Normalize" Filter assigned to a whole track several weeks ago which was not working too. After applying it to each clip directly all works fine.

I don't use GPU processing. For now I'm not able to give you an hint how to reproduce such an issue. I'll check this in the next days.

Maybe my approach is helping:

- Set up project file (video mode, progressive...)
- Drag/Drop Clips to Playlist
- Play one clip from Playlist, set in out points, update playlist, drag/drop snippet to timeline (append)
- ... repeat until finished
- apply filters to each clip on time line
- set cursor to clip border, step 10 frames back, move next clip to cursor to create a transition.
- ... repeat until finished. Before the next transition can be created you must delete the gap (another bug??)
- Insert a composite track for titles, do some titling (png's from Gimp)
- done

**Comment by ddennedy** [comment]
OK, I believe you. Likely, there is a bug somewhere, but the person trying to fix it needs to be able to reproduce it. I will hold this open a little while in case we figure out what is happening.

I do not know if Normalize can actually be used on a track. I think we need to remove some filters from the menu that do not work correctly on a track.

Your steps are very normal and similar to some of my workflows. The gap created when making a transition is not exactly a bug. You are moving a clip, and moving a clip in general does not affect other items on the timeline. However, in this particular use case, in can be argued that it should respect the setting of the ripple toggle on the timeline toolbar, and I will take it into consideration for the to-do list.

**Comment by peossource** [comment]
Yesterday I did some trials to reproduce with no success. One variance of my described workflow is to use two snippets from the same clip but this worked well too.

Let us continue if this issue reoccurs. I'll keep my eyes open. Thanks for helping!
