### ISSUE TITLE
XML job files get changed when adding multiple encode jobs

### ISSUE THREAD

**Issue by OpusMcN** [mltframework/shotcut#192]
It appears that the XML for an encode job in the jobs list can get changed when adding multiple jobs.   I'm unsure if it's random or exactly repeatable, but I've seen it multiple times with the following steps :

- Set up a project with multiple videos (all clipped down to a small region, lots of the videos appear more then once clipped to different regions) in the playlist 
- Drag one video from the playlist to the timeline
- Encode that video, set the filename, ok the save dialog.  The job gets added to the jobs list and starts encoding
- Delete the video from the timeline (either just the clip, or then entire track)
- Drag another video from the playlist to the timeline
- Encode that one in the same way, queuing it up on the jobs list
- Repeat the delete clip / drag new clip / encode for a few clips (I see it go wrong on about the 7th or 8th clip)
- View the XML file for each of the pending (and currently encoding).   I'm seeing the XML for previous jobs get changed after their submission.

See the attached image, this is the XML for the selected job (boat3.mp4).  This showed correctly when the job was first added, but after adding the additional jobs shown the XML has now changed, and has all the values for the Boat6 job (and the target is set to Boat6.mp4).    This happens on both completed and pending jobs.

![capture](https://cloud.githubusercontent.com/assets/7122800/12905528/cda5191c-cf3c-11e5-9524-ece7ba5aee65.JPG)

(the boat6 job XML file is still correct)

When adding lots of jobs this results in files both getting missed, and other files overwritten with the wrong video.

Thanks,

Craig.

**Comment by ddennedy** [comment]
I have not been able to reproduce this. The XML contains a <producer> for each clip in your playlist. The playlist is saved with the project, and the XML for encoding is the same as the project XML - it contains the playlist as well. I checked for "files both getting missed, and other files overwritten with the wrong video" but did not experience that. For the test, I ensured that I queued encodes that would take a good while by using HEVC and added new jobs while first couple were still running to create pending jobs as described. Still, your screenshot is convincing, and I will try again and review some of the code in this area.

**Comment by ddennedy** [comment]
Reviewing the code, I think the only way this can happen is if the temporary files containing MLT XML are not unique per job. I checked my debug log for my test session for lines like this:
`[Debug  ] <virtual void MeltJob::start()> "C:/Projects/Shotcut/qmelt.exe" ("-progress2", "-abort", "C:/Users/ddennedy/AppData/Local/Temp/shotcut-U35980.mlt")`
[Debug] messages are only available in developer builds - not release builds.
In my test session, these names were all unique. 
We use [QTemporaryFile](http://doc.qt.io/qt-5/qtemporaryfile.html) to generate the temp file name. However, I think the way we are using it does allow the temp name to be recycled as we discard the QTemporaryFile object immediately after the job is enqueued. We probably need to save the XML as a string on the job object and then make the temp file when the job is actively running so we can keep the QTemporaryFile object active for the active lifetime of the job.

**Comment by OpusMcN** [comment]
Hi Dan,

That definitely sounds plausible.  I've spent a while trying to 
reproduce it in a more systematic way without any luck,  it seems 
reasonably random, and in further testing it only seems to kick in once 
you've had Shotcut open for a while and have queued up lots of jobs 
(I've been running through 30 or 40 encode jobs in a single session of 
Shotcut and it's much more common under those circumstances).

Thanks for your efforts.

Cheers,

Craig.
On 10/02/2016 7:25 a.m., Dan Dennedy wrote:
>
> Reviewing the code, I think the only way this can happen is if the 
> temporary files containing MLT XML are not unique per job. I checked 
> my debug log for my test session for lines like this:
> |[Debug ] <virtual void MeltJob::start()> 
> "C:/Projects/Shotcut/qmelt.exe" ("-progress2", "-abort", 
> "C:/Users/ddennedy/AppData/Local/Temp/shotcut-U35980.mlt")|
> [Debug] messages are only available in developer builds - not release 
> builds.
> In my test session, these names were all unique.
> We use QTemporaryFile <http://doc.qt.io/qt-5/qtemporaryfile.html> to 
> generate the temp file name. However, I think the way we are using it 
> does allow the temp name to be recycled as we discard the 
> QTemporaryFile object immediately after the job is enqueued. We 
> probably need to save the XML as a string on the job object and then 
> make the temp file when the job is actively running so we can keep the 
> QTemporaryFile object active for the active lifetime of the job.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mltframework/shotcut/issues/192#issuecomment-181991961>.
>

-- 

*Craig McNaughton | Software Engineering*
Animation Research Ltd / Virtual Eye
8 Dowling Street, PO Box 5580, Dunedin, New Zealand
*Ph* +64 3 477 2995 *M* +64 21 115 2402 *Fx* +64 3 479 9751
*Skype* craig.mcnaughton

*http://*arl.co.nz <http://arl.co.nz>
*http://*virtualeye.tv <http://virtualeye.tv>

**Comment by ddennedy** [comment]
I reproduced this after adding a new feature to batch encode all of the playlist items. I have a fix pending testing.

**Comment by ddennedy** [comment]
You can download a nightly release from here to test and confirm this (and get new feature: From field added to top of Encode panel).

**Comment by OpusMcN** [comment]
Thanks Dan,  grabbing the nightly build now.

Thanks for the quick work!
