### ISSUE TITLE
Display broken if GPU enabled and OpenGL context not threaded

### ISSUE THREAD

**Issue by j-b-m** [mltframework/shotcut#194]
Hi,

I think there is a problem with current display code in glwidget.cpp

In august, a change was introduced to test if OpenGL supports updating from a thread != main GUI thread ( supportsThreadedOpenGL ) :
https://github.com/mltframework/shotcut/commit/04187163cbdbe99f97b720c4f40e5d53dfb56f08

Before this change, display was working fine for me (linux with integrated intel GPU).
With this new code, my system reports that it does not handle threaded OpenGL.
Enabling GPU processing, the monitor does not work anymore. Looking at the code, it seems like there is an error in the logic:

if you look at the ShowFrame code, handling processing of frames (glwidget.cpp, line 791), the code is like this:

void FrameRenderer::showFrame(Mlt::Frame frame)
{
if (!Settings.playerGPU()) { 
     (process display on non GPU)
}

if (m_context && m_context->isValid()) {
     (process display if m_context is valid)
}

emit frameDisplayed(m_displayFrame);
}

But m_context is defined in FrameRenderer constructor only if supportsThreadedOpenGL:

if (shareContext->supportsThreadedOpenGL()) {
        m_context = new QOpenGLContext;
}

So in my situation, where I enable GPU and OpenGL context does not support threading, showFrame does nothing but send blank frames, while it was working before the mentioned commit.

I did try to make some changes but I am not familiar enough with OpenGL stuff to find a solution, so any comments / ideas are welcome.

**Comment by ddennedy** [comment]
Honestly, I did not expect that to be a workable combination! Non-threaded GL was mainly added for ANGLE DirectX, which cannot support GPU processing. I will try to make a change you can test but no real way to test it myself.

**Comment by ddennedy** [comment]
Wait. Movit inherently requires threaded OpenGL. It runs in a separate thread and needs to be able to share GL resources with another thread. Perhaps the Qt supportsThreadedOpenGL() returns an incorrect value for your system. Otherwise, I do not know how to detect non-threaded GL that also supports Movit. I could stop using threadedOpenGL and just detect ANGLE instead.

**Comment by ddennedy** [comment]
What does `qDebug() << "OpenGL ES?" << quickWindow()->openglContext()->isOpenGLES();` report on your system?

**Comment by ddennedy** [comment]
One thing I can do is to allow Settings > GPU Processing to force usage of threaded rendering. Do you have an easy way to test this?
```
--- src/glwidget.cpp
+++ src/glwidget.cpp
@@ -165,7 +165,7 @@ void GLWidget::initializeGL()
     quickWindow()->openglContext()->makeCurrent(quickWindow());
 
     connect(m_frameRenderer, SIGNAL(frameDisplayed(const SharedFrame&)), this, SIGNAL(frameDisplayed(const SharedFrame&)), Qt::QueuedConnection);
-    if (quickWindow()->openglContext()->supportsThreadedOpenGL())
+    if (Settings.playerGPU() || quickWindow()->openglContext()->supportsThreadedOpenGL())
         connect(m_frameRenderer, SIGNAL(textureReady(GLuint,GLuint,GLuint)), SLOT(updateTexture(GLuint,GLuint,GLuint)), Qt::DirectConnection);
     else
         connect(m_frameRenderer, SIGNAL(frameDisplayed(const SharedFrame&)), SLOT(onFrameDisplayed(const SharedFrame&)), Qt::QueuedConnection);
@@ -347,7 +347,7 @@ void GLWidget::paintGL()
     glClear(GL_COLOR_BUFFER_BIT);
     check_error(f);
 
-    if (!quickWindow()->openglContext()->supportsThreadedOpenGL()) {
+    if (!(Settings.playerGPU() || quickWindow()->openglContext()->supportsThreadedOpenGL())) {
         m_mutex.lock();
         if (!m_sharedFrame.is_valid()) {
             m_mutex.unlock();
@@ -769,7 +769,7 @@ FrameRenderer::FrameRenderer(QOpenGLContext* shareContext, QSurface* surface)
     Q_ASSERT(shareContext);
     m_renderTexture[0] = m_renderTexture[1] = m_renderTexture[2] = 0;
     m_displayTexture[0] = m_displayTexture[1] = m_displayTexture[2] = 0;
-    if (shareContext->supportsThreadedOpenGL()) {
+    if (Settings.playerGPU() || shareContext->supportsThreadedOpenGL()) {
         m_context = new QOpenGLContext;
         m_context->setFormat(shareContext->format());
         m_context->setShareContext(shareContext);
```

**Comment by j-b-m** [comment]
On Monday, February 15, 2016 7:37:04 PM CET, Dan Dennedy wrote:
> One thing I can do is to allow Settings > GPU Processing to 
> force usage of threaded rendering. Do you have an easy way to 
> test this?

Hi Dan, thanks for looking into this.
I just double checked on my laptop (which also has an integrated intel GPU 
but more recent).
Result is the same for my 2 computers:

supportsThreadedOpenGL() is false
isOpenGLES() is false

OpenGL info:

Desktop PC
GL_Vendor: "Intel Open Source Technology Center"
GL_RENDERER: "Mesa DRI Intel(R) Ivybridge Desktop"

Laptop:
GL_VENDOR: "Intel Open Source Technology Center"
GL_RENDERER: "Mesa DRI Intel(R) Haswell Mobile"

I can confirm that your patch proposal (Force threaded processing when GPU 
enabled) fixes the issue 
and makes GPU work again.

So maybe supportsThreadedOpenGL() returns an incorrect value ?

Regards
jb

**Comment by ddennedy** [comment]
Maybe there is some context for multi-threaded that someone (including me) is misunderstanding. I will commit this. Thanks
