### ISSUE TITLE
Encoding fails if tmp folder full

### ISSUE THREAD

**Issue by zeroghost** [mltframework/shotcut#195]
When you try to encode a video, while your temp folder is full (my tmp folder is on a 2 GB ramdisk) Shotcut will quietly fail to encode. 
The Job will instantly jump to done, and the log only says: Failed to load ".mlt"
Maybe make some error handling to capture this error, and make the log a little bit more clear on what is going on. 

Forgot to add: Shotcut version 16.02.01
Windows 10.

**Comment by ddennedy** [comment]
A couple of versions ago, the temp file behavior was changed so that if it fails to open or unwritable in the system temp directory, then it uses the export destination directory for the temp file.
