### ISSUE TITLE
Some track content disapear

### ISSUE THREAD

**Issue by ydesgagn** [mltframework/shotcut#197]
In my project there are four video tracks where there are transparent PNG files. I could well see my PNG images in the timeline and in the source monitor. It was perfectly working. But, when I added more tracks to add videos below my PNG, PNG images were no longer visible in the video source. So, when I play the video, we dont see the PNG images in the source monitor, as if they are not in the timeline, but they still are.
<img width="833" alt="fine" src="https://cloud.githubusercontent.com/assets/9338353/13083827/ae5efd94-d4a4-11e5-925f-3060d2a98132.png">
<img width="833" alt="not fine" src="https://cloud.githubusercontent.com/assets/9338353/13083831/b25bc026-d4a4-11e5-8038-4633971ac041.png">

**Comment by ydesgagn** [comment]
Mlt file available here:

https://drive.google.com/file/d/0By_LKGPsGsIOZW84QXR1ZkdJZUU/view?usp=sharing

**Comment by ddennedy** [comment]
This was fixed in https://github.com/mltframework/mlt/commit/29dcea00506d4e8b95affb63537008c4a779db88
