### ISSUE TITLE
producer_xlr fails to load

### ISSUE THREAD

**Issue by Anon-Penguin** [mltframework/shotcut#198]
I was getting weird output in my video logs when encoding as `H.264 High Profile`:

```
[producer_xml] failed to load producer "C:/Users/matth/AppData/Local/Temp/nb.jpg"
[producer_xml] failed to load producer "C:/Users/matth/AppData/Local/Temp/si.jpg"
[producer_xml] failed to load producer "C:/Users/matth/AppData/Local/Temp/pi1.jpg"
[producer_xml] failed to load producer "C:/Users/matth/AppData/Local/Temp/pi5.jpg"
[producer_xml] failed to load producer "C:/Users/matth/AppData/Local/Temp/pi2.jpg"
[producer_xml] failed to load producer "C:/Users/matth/AppData/Local/Temp/pi3.jpg"
[producer_xml] failed to load producer "C:/Users/matth/AppData/Local/Temp/pi6.jpg"
[producer_xml] failed to load producer "C:/Users/matth/AppData/Local/Temp/ei1.jpg"

(qmelt.exe:9160): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderFc', script='latin'
Fontconfig error: Cannot load default config file
[swscaler @ 00000000482bb560] Warning: data is not aligned! This can lead to a speedloss
```

The output is black and silent except for a few random clips. Elements not listed above are also missing from the exported movie.

Ideas? What do I need to provide to make this a bug report/this is needed tomorrow, how can I fix it?

**Comment by ddennedy** [comment]
I am not sure. Some people said they had to run as admin on Windows to get encoding to work. You should try that first. Otherwise, why is your project trying to load images from your Temp directory? Those files might be gone now.

**Comment by ddennedy** [comment]
Also, read the text of your project file in a text editor and look at file names. See if those files actually exist at those locations.

**Comment by Anon-Penguin** [comment]
I never imported from a temporary directory; I presume that is from the encoder copying files

I will try admin

**Comment by Anon-Penguin** [comment]
Admin worked. Thanks!

**Comment by ddennedy** [comment]
OK, thank you for providing some hint about what might have happened "I never imported from a temporary directory." This tells me that some how the XML generated for the encode job, which is a temp file, got tricked into making relative path names to those files. I still do not know how, but it is a clue for why some people need to run as admin.
