### ISSUE TITLE
shotcut stop work when I try to move image in timeline

### ISSUE THREAD

**Issue by danieleduvolucion** [mltframework/shotcut#200]
when I use a chorma key and put a image in the back in timeline the shotcut stop work... I have a pc with windows 10 and last version of shotcut

**Comment by ddennedy** [comment]
Very poor description. Improve it or I close it.

**Comment by bmatherly** [comment]
Some things that might help us reproduce the problem:

* What filters (exactly) are you using?
* Are the filters applied to the track or to a clip?
* What steps are you taking when shotcut stops? Provide step-by-step instructions
* What exactly does "stop work" mean? Crash? Freeze?

Some people provide screenshots or videos to help us see the problem.
