### ISSUE TITLE
Relative paths breaks render

### ISSUE THREAD

**Issue by IBPX** [mltframework/shotcut#201]
If I add a clip to Shotcut, save the `.mlt`, then render it, I'll get an error saying it couldn't find the clip

    /tmp/.something/PATH/RELATIVE/TO/WHERE/I/SAVED/THE/MLT

If I open the file and manually change relative paths to absolute, it renders fine.

**Comment by ddennedy** [comment]
OK but how do I reproduce it?

**Comment by IBPX** [comment]
Try adding a clip to an empty project, and saving the `mlt` to the same folder. Open the file in a text editor and search for the name of the file. If it's not already a relative path, change it to just be the name of the clip.

For example, from

    /home/Dan/Videos/aproject/someclip.webm

to just `someclip.webm`.

Then, try to render.

**Comment by ddennedy** [comment]
OK, I did that with Shotcut 15.03 on OS X 10.11, and it works fine for me. Some people on Windows are reporting a similar problem, and when they start Shotcut as Administrator, they are then able to export with correct results. But, I have not been able to reproduce it and figure out what causes this.

**Comment by IBPX** [comment]
It seems MLT runs in a temporary directory, and interprets the relative location relative to _it,_ not where the .mlt is stored.

**Comment by ddennedy** [comment]
Can you please test this new version?
http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-debian7-x86_64-160308.tar.bz2

**Comment by IBPX** [comment]
I'm on Windows, so I can't test that version. I'll try to build it when I have a minute.

**Comment by ddennedy** [comment]
No, don't build it yourself. It is difficult and likely to produce
something broken and invalidate your test. See the related bug #199 for a
Windows version. Let me know if you want to help with Shotcut and need an
easier way to dev and test.

>

**Comment by IBPX** [comment]
Thanks, I'll see if that works.

**Comment by IBPX** [comment]
That fixes it.

Rendering _[this file](https://gist.github.com/IBPX/038b6abf707592d762f9)_ with an _img.jpg_ in the same folder, the old version fails. If you replace the `img.jpg` with an absolute path in the old version still, it renders correctly.

Rendering with the relative path in the new build works without error.

Thanks!
