### ISSUE TITLE
Video encoding results in black fragments

### ISSUE THREAD

**Issue by Crackle42** [mltframework/shotcut#206]
Hi, first of all, I really appreciate your program and its possibilities.

I am working on a short video of a recently published app and combined different clippings I have created before. As I don't know, which information you need, I recorded the problem. You can find the video here: https://www.dropbox.com/s/u80b2z8vdciggeo/shotcutbug.mp4?dl=0

Short description: In the video, you can see the shotcut preview showing no problems with the video in the timeline. However after encoding, some parts of the video are black (audio is still working). To fix the problem I have to drag and drop the video from the playlist to the timeline again.
Sometimes I get the same problem with pictures I added (png). They show seven white squares though

I have no idea why and when the problem occurs. Sometimes it's working and sometimes I save and quit the project and one hour later, when reopening the project, it's broken. This problem occured on Win7 with Version 16.02. I'm trying the new one now.

**Comment by bmatherly** [comment]
Thanks for your report.

Please do try the latest version as there have been some improvements.

Also, please try running Shotcut as administrator ("right click"->"run as Administrator").

Please report back what you find.

**Comment by ddennedy** [comment]
No, Brian, this is not fixed in version 16.03. It was, however, resolved and closed in 2 related bug reports. One of those, #199 has a link to an interim release that includes the fix.
