### ISSUE TITLE
the program stops (crash) when I drag an image over a video. 

### ISSUE THREAD

**Issue by danieleduvolucion** [mltframework/shotcut#210]
when I try to drag and drop an image over a video program does crash:
version of shotcut: Current Version: 16.03 – 64-bit Only

1 stp: add video with drag and drop in the playlist
2 stp: add video to the timeline on the track by default with drag and drop
3 stp: add image  with drag and drop in the playlist
4 stp: add on picture over the video with drag and drop (track in the timeline) and the program does crash.

please look at the gif attach you ![sin titulo](https://cloud.githubusercontent.com/assets/17646032/13784765/7bfde396-ea9e-11e5-84d0-bd8375af2e7a.gif)

**Comment by metellius** [comment]
In the gif you seem to drag the image, then alt+tab while dragging and then dropping. I'm curious: if you make shotcut smaller so that you can see the desktop and then make the drag without hitting any keyboard shortcuts, does it still happen?

**Comment by danieleduvolucion** [comment]
yes, the bug still going

**Comment by ddennedy** [comment]
A workaround is to drag the image to the player instead of the timeline.
