### ISSUE TITLE
5.1 audio is not downmixed to stereo when source is AAC

### ISSUE THREAD

**Issue by bmatherly** [mltframework/shotcut#212]
Play a 5.1 surround clip. Only the left and right front channels will be used. Shotcut should be down-mixing all channels to stereo so that center, surround and LFE are not lost.

Test file available here:
https://www2.iis.fraunhofer.de/AAC/ChID-BLITS-EBU.mp4

**Comment by ddennedy** [comment]
I seem to recall that avformat_producer used to do this, but I had to fix a libavcodec API change and lost it. See this:
https://github.com/mltframework/mlt/commit/6b79e7c79ae67b56284ccca16cde3cac9f2587b6
Normally, *channels = 2, and av_get_default_channel_layout(2) ought to return stereo. But, I do not know why; maybe downmixing is no longer implicit and requires explicit avfilters to achieve.

**Comment by bmatherly** [comment]
Thanks for the tip. I tried reverting that commit. It prints a deprecation warning, but it does still compile. 

Unfortunately, the channels are still not rematrixed properly.

I took a quick look in ffmpeg, and it seems that the proper method for dowmixing/rematrixing is to use libswresample. I haven't found a way to trick a codec contex into performing the downmix. if it exists, maybe it is hidden somewhere.

I'm going to keep looking to see if I can find a good path forward.

**Comment by bmatherly** [comment]
Additional Info:

from avcodec.h:
```
 /**
      * Request decoder to use this channel layout if it can (0 for default)
      * - encoding: unused
      * - decoding: Set by user.
      */
     uint64_t request_channel_layout;
```

Compliance with this request is dependent on the decoder. It turns out that the AC3 decoder supports it and the AAC decoder does not. I tested an AC3 file and it did return two channels with proper downmix. So I expect this is not a regression. Rather, it probably had not been tested with AAC previously.

Some paths forward:
* Add the downmix matrix to the audiochannels filter.
* Add channel count to the avresample filter (since ReSampleContext supports rematrix) and make it the preferred normalizer.
* Create a new normalize filter based on libswrescale.

**Comment by bmatherly** [comment]
Fixed with https://github.com/mltframework/mlt/commit/1f8ee7769e33b0aceb161ddaafa9eab7112ad7b0
I added support for 5.1->stereo. I think that will cover 99% use cases. We can add other obscure downmix modes as the need arises. However, to do so, we would probably have to add the concept of channel layout since some channel counts have multiple speakers configurations that apply to them.
