### ISSUE TITLE
Crashes when trimming video video more than 10 minutes long

### ISSUE THREAD

**Issue by dantesorgentini** [mltframework/shotcut#214]
Shotcut crashed when i try to trimm a video with more than 10 min duration. I maket it with a Cannon t3i in .mov format. Full HD 1910x1080 in 25fps. In Linux Xubuntu 15.10.  When i put the 3rd video into the timeline and try to trimm, the program crash. I try it several times and can't solve it. 
![captura de pantalla_2016-03-28_13-02-51](https://cloud.githubusercontent.com/assets/18115174/14076870/eb505bb0-f4e5-11e5-83fc-53dbcde7ff4c.png)

**Comment by ddennedy** [comment]
Unable to reproduce.
Where did you get Shotcut? What version is it?
As a workaround, trim it before adding it to the timeline.

**Comment by dantesorgentini** [comment]
hey thanks for the fast reply!
I ve downloaded the version of shotcut 16.03.01 from
https://www.shotcut.org/
the Linux one.
I sorry i only uploaded a photo, i'll upload a video nex time.
I try that and tell you. Thanks!

2016-03-28 18:26 GMT+02:00 Dan Dennedy <notifications@github.com>:

> Unable to reproduce.
> Where did you get Shotcut? What version is it?
> As a workaround, trim it before adding it to the timeline.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mltframework/shotcut/issues/214#issuecomment-202471835>
>



-- 
Dante Sorgentini
Realizador de Cine y Animación
Tel: +34 6112287821
canal de Vimeo <https://vimeo.com/channels/dantesorgentini>   Facebook
<https://www.facebook.com/sorgentinidante>   Linkedin
<https://www.linkedin.com/pub/dante-sorgentini/32/851/5b2>

**Comment by ddennedy** [comment]
OK, thanks. Another workaround for the Timeline (assuming this bug report is about drag-n-drop edge trimming) is to use the 'i' and 'o' keyboard shortcuts. Please correct that assumption if wrong.
Also, the screenshot shows that Ripple mode is Off, which is also good to know.

**Comment by dantesorgentini** [comment]
yes, the bug occurs when drah-n-drop the edge, with the ripple mode in Off.
I doesn't try with the ripple in On yet.

2016-03-28 19:54 GMT+02:00 Dan Dennedy <notifications@github.com>:

> OK, thanks. Another workaround for the Timeline (assuming this bug report
> is about drag-n-drop edge trimming) is to use the 'i' and 'o' keyboard
> shortcuts. Please correct that assumption if wrong.
> Also, the screenshot shows that Ripple mode is Off, which is also good to
> know.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mltframework/shotcut/issues/214#issuecomment-202507089>
>



-- 
Dante Sorgentini
Realizador de Cine y Animación
Tel: +34 6112287821
canal de Vimeo <https://vimeo.com/channels/dantesorgentini>   Facebook
<https://www.facebook.com/sorgentinidante>   Linkedin
<https://www.linkedin.com/pub/dante-sorgentini/32/851/5b2>
