### ISSUE TITLE
Frequent crashes when working with multuple audio tracks (16.04.01, Win64)

### ISSUE THREAD

**Issue by OpusMcN** [mltframework/shotcut#216]
I'm adding some additional audio tracks, currenty I've got two video tracks (one with audio) and two additional audio tracks.  I'm getting frequent crashes when dragging new audio files on these additional audio tracks, and when dragging around the clips on those tracks.  

Haven't reproduced an exact sequence to get the crash, but it's happening very frequently. 

Shotcut log attached.
[shotcut-log.txt](https://github.com/mltframework/shotcut/files/201681/shotcut-log.txt)

**Comment by OpusMcN** [comment]
I've found a way to reproduce a crash fairly reliably.    Dragging a new video clip onto the timeline (with the 2 video and two audio tracks as above), just drag the clip randomly around on the timeline over various tracks and clips without dropping it.   After a few seconds I invariably get a crash.

MLT file attached, I'm dragging the final (boat1.mp4) clip around the timeline.
[ClipDraggingCrash.mlt.txt](https://github.com/mltframework/shotcut/files/201699/ClipDraggingCrash.mlt.txt)

**Comment by Gaffy2** [comment]
I can repeat the error. If one item on the timeline has its properties changed (speed and audio mut in my case) then from then on any change causes it to crash. Windows10 64bit event data

Faulting application name: shotcut.exe, version: 0.0.0.0, time stamp: 0x56fe8a4b
Faulting module name: Qt5Core.dll, version: 5.5.0.0, time stamp: 0x559bedfb
Exception code: 0xc0000005
Fault offset: 0x000000000008b6ba
Faulting process ID: 0x5e74
Faulting application start time: 0x01d18f11811aacf0
Faulting application path: C:\Program Files\Shotcut\shotcut.exe
Faulting module path: C:\Program Files\Shotcut\Qt5Core.dll
Report ID: 8e5a633a-d274-4414-8687-27fa5cadd551
Faulting package full name: 
Faulting package-relative application ID: 

Hope this is helpful

**Comment by Gaffy2** [comment]
I can repeat the error. If one item on the timeline has its properties changed (speed and audio mut in my case) then from then on any change causes it to crash. Windows10 64bit event data

Faulting application name: shotcut.exe, version: 0.0.0.0, time stamp: 0x56fe8a4b
Faulting module name: Qt5Core.dll, version: 5.5.0.0, time stamp: 0x559bedfb
Exception code: 0xc0000005
Fault offset: 0x000000000008b6ba
Faulting process ID: 0x5e74
Faulting application start time: 0x01d18f11811aacf0
Faulting application path: C:\Program Files\Shotcut\shotcut.exe
Faulting module path: C:\Program Files\Shotcut\Qt5Core.dll
Report ID: 8e5a633a-d274-4414-8687-27fa5cadd551
Faulting package full name: 
Faulting package-relative application ID: 

Hope this is helpful

**Comment by ddennedy** [comment]
@Gaffy2 You say you can repeat this error "on any change," but the original reporter's steps say "without dropping it," which implies no change. Doesn't sound the same to me. Any change to what?

@OpusMcN You wrote "Dragging a new video clip." Dragging it from where - playlist or source player?

**Comment by Gaffy2** [comment]
Ok, I suppose I presumed that multi tracks meant working in the timeline.
With multiple clips in the timeline, if the properties of one clip are modified(speed and audio mute in my case) then from then on attempting to modify the properties of another clip caused it to crash. I did write a really in depth new issue and added the dump files from windows and shotcut but when it came to submit it was forbidden, probably due to the newbie status.

**Comment by OpusMcN** [comment]
@ddennedy , I'm dragging from the playlist onto the timeline.  I have had other crashes manipulating the timeline, but this dragging case is 100% repeatable for me.

**Comment by Gaffy2** [comment]
This morning after a full restart, reloading the saved mlt and modifying the individual clips is working correctly, apologies for wasting your time.

**Comment by OpusMcN** [comment]
@ddennedy 

   Here's a screen capture of the crash.   I'll try and get time to add rebuild the shot and see when it starts crashes.   It's rock stable with just the video, so I strongly suspect something to do with the filters or audio tracks.

https://mega.nz/#!OsMClIYS!TbfF6Srj5cdRlHqiG_Joy03aEfpROazka6GqXLySogc

Cheers,

**Comment by Gaffy2** [comment]
@ddennedy 
So this evening it is occurring again, would you like it started as a new issue?

**Comment by ddennedy** [comment]
@Gaffy2 yes, but do not bother attaching a dump file. Please include steps to reproduce.

**Comment by ddennedy** [comment]
There have been a number of crashes fixed over the past few releases related to dragging from playlist to timeline, moving clips between tracks, and changing timeline clip properties. The latest version is 16.06.08. I am not reproducing the it (original problem reported) per the description and screen capture. If this is still a problem on the latest version, you can reopen it.
