### ISSUE TITLE
Opening a .mlt file on a network location crashes the program when scrubbing

### ISSUE THREAD

**Issue by anzx42** [mltframework/shotcut#222]
Opening an mlt on another computer in a network crashes the program when the user starts scrubbing

**Comment by ddennedy** [comment]
Not enough information. No OS specified. "Network location" too ambiguous. Please do not spam us with bad bug reports, or I will be quick to just close them when I see how brief they are and who is is from.

**Comment by anzx42** [comment]
With a shared folder set up on another computer(both Windows machines) on the same network, opening an mlt in the shared folder will load video, but when the user starts scrubbing the program crashes.

**Comment by ddennedy** [comment]
Unable to reproduce.
