### ISSUE TITLE
Removing a clip from one track removes the equivenent on the rest of the tracks

### ISSUE THREAD

**Issue by Danfun64** [mltframework/shotcut#223]
In the last version, when I right clicked a clip and clicked on remove, it would only affect the one track. Now it affects all tracks, and this "feature" junked part of my work. Can you remove this "feature", or at the very least, tell me how to turn it off, if it can be turned off at all (which it should, at least)

**Comment by Danfun64** [comment]
Similarly, and even worse a "feature", is stuff going to the front when you add something in between.

**Comment by metellius** [comment]
Sounds like you accidentally enabled "ripple all tracks" which is that toggles this behavior. It is not a recent feature.

**Comment by Danfun64** [comment]
...oh.

silly me :P
