### ISSUE TITLE
Question: Desynchronization - separation of audio and video

### ISSUE THREAD

**Issue by myswiat** [mltframework/shotcut#224]
Is it possible to separate the audio from the video in the material, so that you can synchronize audio with video, and vice versa?
Does the program allows or has an option to separate video from audio to both can be edited independently?

**Comment by metellius** [comment]
There is no UI for this at the moment. I have found that always having an extra video track on top with audio muted covers most cases.

**Comment by ddennedy** [comment]
This area is for software defect tracking only. Use a forum for help and general Q&A.
