### ISSUE TITLE
Encoding stuck at 0% when using Overlay HTML Filter

### ISSUE THREAD

**Issue by cybercircuits** [mltframework/shotcut#225]
Version: 16.04.1
OS: CentOS 7.2

Job Log:
QXcbConnection: XCB error 146 (Unknown), sequence: 168, resource id:0, major code: 139 (Unknown), minor code: 20

The encoding stuck at 0% if I use any Overlay HTML filter. If I remove all Overlay HTML filters it works. I know that my HTML files are good since I am using the same HTML file in Windows and Mac.

**Comment by cybercircuits** [comment]
I have tried the same project with 16.03.01 and all works well. I have reverted back to this version. Another issue I found with Version 16.04.01 is when I add Overlay HTML > click open > select HTML file it automatically opens the HTML editor but if I add another Overlay HTML  and selected another HTML file it opens the HTML file again with the correct filename but the contents are wrong. The contents belong to the very first HTML file opened.

**Comment by ddennedy** [comment]
> I add another Overlay HTML and selected another HTML file it opens the HTML file again with the correct filename but the contents are wrong

Is that because the editor was automatically opened? I am not sure I understand this one.

**Comment by cybercircuits** [comment]
Basically the contents of the first file is displayed instead of the newly selected html file. Say you have added 3 overlay HTML each one is assigned to an existing html file. Even if you assign another html file to the other two the editor will display the correct filename but the contents belong to the first selected html file.

**Comment by ddennedy** [comment]
Can you please test this new build?
http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-debian7-x86_64-160419.tar.bz2

**Comment by cybercircuits** [comment]
"Is this part also a new problem with 16.04?"
Yes I can confirm the new problem was introduced with 16.04 but does not exist with 16.03.

I have tested build 160419 and I can confirm that the problem of not proceeding with encoding has been resolve. The progress is no longer stuck at 0%. I can also confirm that selecting a new html (using open button) no longer opens the html editor.

The only issue that I have found is the contents of the HTML editor is wrong but displays the correct filename at the title bar. The contents belongs to the first html file you have opened from the time you open a project or created a new project.

**Comment by cybercircuits** [comment]
Here is the video of this problem.
https://youtu.be/w-c27Ytu7jo

**Comment by ddennedy** [comment]
Thanks, as a workaround for the last issue point, switch tabs in the editor to toggle the source to be updated. This bug occurred when the editor was closed in View Source mode. Upon opening, it would only load the WYSIWYG mode and then loads source when switching tabs. Fixed now for next release.

**Comment by cybercircuits** [comment]
Thank you
