### ISSUE TITLE
Crazily jumping stripe when I try to trim it

### ISSUE THREAD

**Issue by PostPollux** [mltframework/shotcut#227]
The video stripe gets crazy when I try to trim it. Watch it yourself:
https://goo.gl/photos/JB9ijchUNg1oHFSG8

Btw. It has nothing to do with "snapping". When I toggle it off, it is the same.

**Expected Behavior:**
Trimming to the exact position of the cursor without jumping.
I also think, there should be NO SOUND UPDATE during trimming, as the sound won't change at that position at all. It's no scrubbing... Maybe even no video update as long as it doesn't change the image under the playhead.

**My System:**
Linux Manjaro
ShotCut 16.04.01

**Comment by ddennedy** [comment]
This was bugging me for a while too, especially the "crazy jumping." Glad I could finally fix it.

**Comment by metellius** [comment]
+1!
