### ISSUE TITLE
Crash when closing preset or timeline menu (AMD Catalyst)

### ISSUE THREAD

**Issue by procedural** [mltframework/shotcut#23]
Firstly I want to say that man, this is the best video editor I've ever used! Great job, keep it working :)

I have a few crashes, this is first one, it happens when Shotcut closes preset pop-down menu, see this video of me reproducing it: http://www.youtube.com/watch?v=4lY-KdouJxs

Here's the log from that video:
https://gist.github.com/procedural/61e1f7abe891d226e1de

I'm using Ubuntu 14.04 and shotcut-debian7-x86_64-140601 build version downloaded from the main site.

**Comment by ddennedy** [comment]
I recently found out about an environment variable that might help: LIBGL_ALWAYS_SOFTWARE=1
http://www.mesa3d.org/envvars.html

**Comment by ddennedy** [comment]
Needs to be retested on v15.09.

**Comment by procedural** [comment]
Ubuntu Mate 14.04, latest available AMD Catalyst 15.7 and Shotcut v15.09: it works! No crashes so far. Thanks, @ddennedy! I'll close it for now since it's currently solved for me.
