### ISSUE TITLE
Toggling effect causes timeline to jump

### ISSUE THREAD

**Issue by PostPollux** [mltframework/shotcut#230]
Disabling and enabling of an effect in the effects panel by toggling the checkbox causes the timeline to jump as long as you don't see the playhead.

https://goo.gl/photos/bcLwAn1CAvm7xArH9

I don't think it should do that, because it doesn't really make sense. Or does it? Maybe I'm missing something...

My System:
Linux Manjaro
Shotcut 16.04.01

**Comment by ddennedy** [comment]
Whenever you make a change to filters (and other situations), the video is refreshed to preview it. Whenever a video frame is displayed, the timeline updates the playhead position to reflect it - a normal part of moving the playhead while the video plays. Whenever the playhead moves, the timeline is scrolled - a normal part of scrolling the timeline while the video plays. It is debatable whether the timeline scrolling when previewing changes is much of a usability issue. What is not so debatable is the code changes required to prevent that behavior - the effort of the changes, the subsequent bugs that will surely arise, and the additional effort to work through those bugs.

**Comment by PostPollux** [comment]
Ok, I now understand it. Thanks for clarification! You are right, there is definetely more important stuff to do, than fixing some minor thing with a huge code rework coming with new bugs.

By the way. You are doing an awesome job with this Video Editor. I really like it! I even wanted to make a monthly subscription with more than 5$ (10 or 15) but I didn't find a way to do that...

cheers, Johannes
