### ISSUE TITLE
Unable to see/edit video/metadata properties for different clips.

### ISSUE THREAD

**Issue by AndKe** [mltframework/shotcut#231]
This video illustrates the problem:
https://youtu.be/ELuJ9QMmajo

Reproduce:  create or open an .mlt file with multiple clips.
while at position of one clip, enable "properties"  in menu: [view], [properties]
observe that video/audio/metadata tabs can be selected by clicking.
now select a different clip, and only audio is displayed.
Still a problem in 16.04.01  , but it has been a problem for half a year at least.  - It's a showstopper, because I need to change interlacing data of those clips.

**Comment by ddennedy** [comment]
Unable to reproduce. Are you using binary builds provided by the Shotcut project?

**Comment by AndKe** [comment]
Yes, downloaded for Ubuntu 64 today.

**Comment by ddennedy** [comment]
Nevermind, I reproduced it. This is a high priority for me to fix for next release.

**Comment by AndKe** [comment]
thank you. :)
