### ISSUE TITLE
"Fast forward" is much to fast

### ISSUE THREAD

**Issue by michael-heerdegen** [mltframework/shotcut#232]
Hello,

I'm using the prebuilt binary available from the Homepage.  Debian testing.  Downloaded again today.

For any clip, when I hit l (once), I get a playback that is ~ a hundred times faster than normal.  Which is, more or less, completely unusable.  This is the issue.

Every successive hit of l doubles the speed again (which is expected I think).

Oh, and thanks for writing this video editor!

Thanks,

Michael.

**Comment by ddennedy** [comment]
Unable to reproduce. It is working as intended and designed.

**Comment by michael-heerdegen** [comment]
No, obviously not for me.  Do you want a screencast as proof?

Maybe this depends on ffmpeg version or whatever, dunno.  I see it all the time.  AFAICT I have a sane system and use just the binary, unmodified, that is provided on the project's homepage.

Anything I could do to investigate?

Thanks.

**Comment by ddennedy** [comment]
You can submit a patch or wait until someone else who is a developer is affected by this. You could make a screencast as well as provide some media info about your clip. Does sound work on your system?

**Comment by michael-heerdegen** [comment]
Dan Dennedy <notifications@github.com> writes:

> You can submit a patch

I already failed at building the thing, so I guess I'm not qualified.  I
just guessed that it could be a problem with units that you pass to
ffmpeg when browsing the sources.

> or wait until someone else who is a developer is affected by this. You
> could make a screencast as well as provide some media info about your
> clip.  Does sound work on your system?

Yes, sound works.  Why do you ask?  The frequencies appear unshifted
AFAICT.

And the problem seems to be independent from the media type.

**Comment by ddennedy** [comment]
> The frequencies appear unshifted AFAICT.

That might be the problem. Playback speed is regulated by the sound device. When you fast forward, it simply skips every other frame. Shotcut is based on MLT, which is 13 years old and started on Linux. It has been used by other video apps Kdenlive, Flowblade, and OpenShot. So, it has been through much refinement. I do not know why it is a problem on your system, and the Shotcut binary is built on Debian stable. Interesting. We can re-open the bug, but that does not mean I volunteer to give this my attention. Basically, it will wait until someone who is affected decides to do something about it.

**Comment by ddennedy** [comment]
Another thing you can try to test is in a terminal window in a X session:
`$ melt your-file`
Don't have melt? apt-get install melt. How does that play? How does audio sound? You can press '6' to play fast-forward. Same problem?
If that is fine, next try
`$ path/to/Shotcut/Shotcut.app/melt your-file`
Same difference?

**Comment by michael-heerdegen** [comment]
Dan Dennedy <notifications@github.com> writes:

> Another thing you can try to test is in a terminal window in a X session:
> $ melt your-file
> Don't have melt? apt-get install melt.

It already had been installed.  I already tried to downgrade to the
Debian stable version, but it didn't make a difference for shotcut.

> How does that play? How does audio sound? You
> can press '6' to play fast-forward.

Seems I need '7'.  I tested with '7'.

> Same problem?
> If that is fine, next try
> $ path/to/Shotcut/Shotcut.app/melt your-file
> Same difference?

Both behave exactly the same: speed is moderately enlarged, the factor
could be 2, which seems correct.  But sound is turned off for both when
hitting '7'.  Before hitting '7', sound is normal.

**Comment by ddennedy** [comment]
>Seems I need '7'.

Correct, 5 is pause, 6 normal forward, 7 fast forward.

> Both behave exactly the same: speed is moderately enlarged, the factor could be 2, which seems correct.

Then, melt and MLT provided with Shotcut is working fine.

How are you starting Shotcut? Running Shotcut.app/bin/shotcut is not supported. You must run Shotcut.app/shotcut (or use the icon, which tries to do the same thing).

**Comment by michael-heerdegen** [comment]
Dan Dennedy <notifications@github.com> writes:

> How are you starting Shotcut? Running Shotcut.app/bin/shotcut is not
> supported. You must run Shotcut.app/shotcut (or use the icon, which
> tries to do the same thing).

I think I do it right: I have ~/bin in my PATH and there is a symlink

  shotcut -> ../software/Shotcut/Shotcut.app/shotcut

Also cd'ing into ~/software/Shotcut/Shotcut.app and calling

  ./shotcut file

doesn't help.

I use the fish shell normally, sometimes it does dumb things, but
switching to bash doesn't help.  Sourcing source-me doesn't help, too.

I also installed the Debian shotcut package (I didn't use it because it
was very buggy), and its shotcut has the issue.

**Comment by michael-heerdegen** [comment]
> I think I do it right: I have ~/bin in my PATH and there is a symlink
>
>   shotcut -> ../software/Shotcut/Shotcut.app/shotcut

Yip, trying to use Shotcut.app/bin/shotcut immediately crashs, so I
guess I have not been using it.

**Comment by michael-heerdegen** [comment]
Michael Heerdegen <michael_heerdegen@web.de> writes:

> Yip, trying to use Shotcut.app/bin/shotcut immediately crashs, so I
> guess I have not been using it.

But don't feel obligated to care about this now.  It's not the end of
the world, I can live without this working.  Thanks so far.
