### ISSUE TITLE
Picture duration > 10 minutes

### ISSUE THREAD

**Issue by Aurosspenjy** [mltframework/shotcut#234]
Hello guys !

For some reasons i would open a picture and extend it for 15 minutes (at least)
I don't know why, but there is a limitation at 10 minutes, i can't extend more...

Do you know why and do you know how can i resolve it ?

I really need this time for 1 picture. Why ?

I'm actually trying to make a timer. The only way i found was in Shotcut, with the timecode balise.
So i want to put timecode balise on green screen to import in another video project. (also i need only hours and minutes but with masking i can have it)

Thanks :)

**Comment by metellius** [comment]
As a workaround you can probably modify the duration of the picture source directly in the XML.

**Comment by Aurosspenjy** [comment]
Hi !

Thank you for your speed answer !!

Do you know where can i make such thing ? I never did that...

**Comment by metellius** [comment]
Open the MLT file in a text editor, find the **producer** tag that has a matching **resource** property that is your filename, then modify the **length** property. Then open it again in shotcut and you should be able to stretch it further.
Remember to backup the file in case you mess it up.

**Comment by Aurosspenjy** [comment]
Very nice, it works !!

Thank you Metellius :+1: 

Do you know if it is possible to modify the timecode balise ? 

At least with your help i can forward :)

**Comment by metellius** [comment]
balise?
I suggest just experimenting and see if you get the expected result.

**Comment by Aurosspenjy** [comment]
Sorry it was a french word,

this is : #timecode#
But I don't even know if its possible, i didn't find this in the mlt file (i think it's normal)

When you use the text filter #timecode# it is a format hh:mm:ss:ms
In the case some one know how to format it like : mm:ss

;)

**Comment by bmatherly** [comment]
There is no feature for custom timecode formatting.

There is a different keyword for localtime that supports an optional formatting string. For example, you can do: `#localtime %M:%S#`
But that will display the minute/seconds for the local computer time, not the video timecode.

The timecode related keywords are:
`#smpte_df#` - drop frame. Same as ndf for non-fractional frame rates
`#smpte_ndf#` - non drop frame
`#frame#` - just the frame number
`#timecode#` - same as smpte_df

**Comment by Aurosspenjy** [comment]
Ok thank you bmatherly. It is interesting. Btw with the length of my picture I can put a countdown as I wished, with some masking tool on Vegas or Natron it will be ok.

Thanks you all for your help :)

**Comment by ddennedy** [comment]
Another workaround is to simply include the picture in a playlist or timeline more than once.
