### ISSUE TITLE
Text filter: No text in text entry box breaks video

### ISSUE THREAD

**Issue by tin2tin** [mltframework/shotcut#236]
How to reproduce:
- Add a text filter.
- Resize the textbox so one line of text fits inside it and center the box.
- Remove all text in the text entry box.

Result:
A copy of the video image is pushed below the text box and flickers in green colors when played. 

OS:
Win 8

**Comment by ddennedy** [comment]
Reproduced on OS X as well.
Workaround: remove the filter or add some text.

**Comment by tin2tin** [comment]
The reason I came across this bug, was that I wanted to add texts throughout a longer clip. So first I added the text filter and the settings I needed and the added it to the clip. Then I used the split tool to split the clip into parts, so each part could have an individual text (like subtitles), but then I encountered the above mentioned bug.

**Comment by ddennedy** [comment]
Fixed in MLT git commit https://github.com/mltframework/mlt/commit/a2a11e6b0f77498be444d01ba1b07571a23863e0

**Comment by tin2tin** [comment]
That was quick, thank you!
