### ISSUE TITLE
The program crashes at startup at the "loading plugins" screen

### ISSUE THREAD

**Issue by personaevok88** [mltframework/shotcut#237]
Hi everyone. I've been using Shotcut for a few months now and I've really liked the program so far. However, when I tried to install the new update today, the program crashed as soon as the startup screen appeared. It was the screen that says "loading plugins". My graphics card is the Intel HD Graphics 4000 for Windows 10 64 bit on a Dell Inspiron 5520 laptop. I'm not sure if maybe I accidentally made a change in my registry or uninstalled another program that is contributing to the problem. 

My log shows:

[Info   ] <Application::Application(int&, char**)> Starting Shotcut version 16.05.01 
[Info   ] <Application::Application(int&, char**)> Windows version 192 
[Info   ] <Application::Application(int&, char**)> number of logical cores = 4 
[Info   ] <Application::Application(int&, char**)> locale = QLocale(English, Default, UnitedStates) 
[Info   ] <Application::Application(int&, char**)> install dir = "C:/Program Files/Shotcut" 
[Debug  ] <MainWindow::changeTheme> begin 
[Debug  ] <MainWindow::changeTheme> end 
[Debug  ] <MainWindow::MainWindow()> begin 
[Debug  ] <Mlt::Controller::Controller()> begin 

Thanks for your help!

**Comment by ddennedy** [comment]
The installer has an option that says something like "check this option if you experience a new crash at startup." Did you try that? If not, you should.

**Comment by personaevok88** [comment]
You mean the option to delete the registry? I tried that. I also tried manually deleting the registry item that was recommended in the FAQs before that and it still didn't help.

**Comment by ddennedy** [comment]
Does it work again if you install an older version (best if you can remember what it was - perhaps from download history).

**Comment by personaevok88** [comment]
I've tried some of the older versions. I even tried some of the older 32 bit versions from 2015 and experienced the same problem.

**Comment by ddennedy** [comment]
Sorry, but something changed on your, and Shotcut is no longer compatible. We are not acting upon or keeping open crash-on-launch system incompatibility bugs.

**Comment by personaevok88** [comment]
I went even farther back and version 14.05 worked for me without a problem. What made the later versions incompatible?

**Comment by alexnoma** [comment]
I had the same problem: "ShotCut crashes at statup (loading plugins)".
I reinstalled ShotCut with the option to "remove from registry" but the same problem occurred after I executed another program called "OBS Studio".
I updated OBS Studio to the latest version and the problem disappeared.
Therefore, it seems this problem can be caused by another program, other than ShotCut.
