### ISSUE TITLE
Tiny issue : Menus don't open on first click

### ISSUE THREAD

**Issue by MrHeadwar** [mltframework/shotcut#238]
Hi, 
A tiny, tiny bug here : the main menus don't respond to the first click, and have to be clicked twice to unfold. You can even click once on one (nothing happens) then click on another one and it unfolds. Looks like a focus problem. Hope it's a quick fix !
Thanks for Shotcut,
Regards,
Ed

Edit : Ubuntu 14.04 / Unity, language French

**Comment by ddennedy** [comment]
You did not specify an OS, but I do not see that problem, and it is the responsibility of Qt to open the menu (there is no Shotcut code that responds directly to open-menu events). So, I do not expect this to go anywhere. I believe it is quite specific to your environment.

**Comment by MrHeadwar** [comment]
Ok, then. Its strange, as my Ubuntu 14.04 is vanilla straight from Canonical. Though, I tested with Ms Win 7 and it works as expected. Plus, its a very minor annoyance. Sorry for the noise.
Regards,
Ed

**Comment by ddennedy** [comment]
Does not reproduce on my Kubuntu 14.04 system running on hardware or a fresh install of 14.04 of Unity running in VirtualBox.
