### ISSUE TITLE
Refresh Viewer after trimming

### ISSUE THREAD

**Issue by PostPollux** [mltframework/shotcut#239]
Thanks, the trimming works really nice now without jumping! Good job. One small thing which I think could be still improved, is to automatically refresh the view, when you let go the mouse button and stop trimming. Because sometimes the trimming changes the stripes under your playhead and thus it would be nice to see an updated image as soon as you are finished with trimming (but not while trimming).

Linux Manjaro
Shotcut 16.05

**Comment by ddennedy** [comment]
The player shall never reflect anything that is not the playhead position. The question is then whether to seek upon completing trimming, and I do not think it should.

This area is for defect tracking only and not enhancement requests or discussing refinements. Use the forum for that.

**Comment by ddennedy** [comment]
Oh, wait, I see it depends upon if the item under playhead changes, and yes that needs refresh.
