### ISSUE TITLE
Snapping clips broken after wrong trim

### ISSUE THREAD

**Issue by PostPollux** [mltframework/shotcut#240]
There seems to be a bug with snapping of clips. Sometimes it visually works, but as soon as you end your drag and drop, the clip just jumps back to its original position. It took me quite a while to reliably reproduce this issue, but now I found how to do it:
If you have a already trimmed clip and you snap it to another, then everything is fine in the first place. But when you now want to trim it again and first accidentally move in the direction of the other clip and then move the other way round or lets say you just want to make a transition and while draging you decide against it and want to undo it by moving the cursor back and going a bit to far, then the snapping will be broken if you move the clips. Ok, sounds complicated. Here a video so it's easier to see what I mean:
https://goo.gl/photos/bBX8v5v929MpqtyW6

Linux Manjaro
Shotcut 16.05

**Comment by ddennedy** [comment]
A workaround is to zoom way in on the timeline and delete the 1-frame transition that was created and not removed.

**Comment by BenMcLean** [comment]
I'm running into this as well and wow, this is a seriously nasty bug that heavily undermines the usefulness of the whole program. Please get this fixed as soon as possible!

**Comment by ddennedy** [comment]
I started working on this, but it is rather tricky and difficult especially with undo history integration. Might take a while.
