### ISSUE TITLE
【compile】 failure: shotcut16.05 on Ubuntu14.04

### ISSUE THREAD

**Issue by zhouhuirun2015** [mltframework/shotcut#244]
when build shotcut with ./shotcut.sh command on Ubuntu14.04, it fails in configure vid.stab,it warns me that compiler not work,but it seems not the compiler problem(all compile things get from official site), log list below:

LOG: Configuring vid.stab
LOG: About to run command: cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/dyh/shotcut20160530/shotcut/Shotcut/Shotcut.app
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /opt/mxe/gcc-5.1.0/usr/bin/x86_64-w64-mingw32.static-gcc
-- Check for working C compiler: /opt/mxe/gcc-5.1.0/usr/bin/x86_64-w64-mingw32.static-gcc -- broken
CMake Error at /usr/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "/opt/mxe/gcc-5.1.0/usr/bin/x86_64-w64-mingw32.static-gcc"
  is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /home/dyh/shotcut20160530/src/vid.stab/CMakeFiles/CMakeTmp

  

  Run Build Command:/usr/bin/make "cmTryCompileExec3910844002/fast"

  /usr/bin/make -f CMakeFiles/cmTryCompileExec3910844002.dir/build.make
  CMakeFiles/cmTryCompileExec3910844002.dir/build

  make[1]: Entering directory
  `/home/dyh/shotcut20160530/src/vid.stab/CMakeFiles/CMakeTmp'

  /usr/bin/cmake -E cmake_progress_report
  /home/dyh/shotcut20160530/src/vid.stab/CMakeFiles/CMakeTmp/CMakeFiles 1

  Building C object
  CMakeFiles/cmTryCompileExec3910844002.dir/testCCompiler.c.obj

  /opt/mxe/gcc-5.1.0/usr/bin/x86_64-w64-mingw32.static-gcc
  -DHAVE_STRUCT_TIMESPEC -I/home/dyh/shotcut20160530/shotcut/Shotcut/include
  -o CMakeFiles/cmTryCompileExec3910844002.dir/testCCompiler.c.obj -c
  /home/dyh/shotcut20160530/src/vid.stab/CMakeFiles/CMakeTmp/testCCompiler.c

  /opt/mxe/gcc-5.1.0/usr/bin/x86_64-w64-mingw32.static-gcc: 1:
  /opt/mxe/gcc-5.1.0/usr/bin/x86_64-w64-mingw32.static-gcc: Syntax error: ")"
  unexpected

  make[1]: Leaving directory
  `/home/dyh/shotcut20160530/src/vid.stab/CMakeFiles/CMakeTmp'

  make[1]: ***
  [CMakeFiles/cmTryCompileExec3910844002.dir/testCCompiler.c.obj] Error 2

  make: *** [cmTryCompileExec3910844002/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
See also "/home/dyh/shotcut20160530/src/vid.stab/CMakeFiles/CMakeOutput.log".
See also "/home/dyh/shotcut20160530/src/vid.stab/CMakeFiles/CMakeError.log".
ERROR: Unable to configure vid.stab
LOG: Process has finished. Reason: FAILURE Some kind of error occured: Unable to configure vid.stab
LOG: Process has finished. Reason: FAILURE Some kind of error occured: Unable to configure vid.stab
Build failed

How to solve this problem? Thank you.

**Comment by ddennedy** [comment]
We do not provide support for build problems. We have a few months that compile Shotcut nightly on a couple different OSes that serves our needs for producing monthly binary releases. Bugs against the build system are not accepted without a patch (i.e. pull request).

Why are you trying to cross-compile it yourself? If you have a good reason, I can give you a SDK that makes development on Windows easier.

**Comment by zhouhuirun2015** [comment]
Because there is no way to download windows version sdk.64bit is ok, but 32 is better.
