### ISSUE TITLE
Constrain proportions when encoding

### ISSUE THREAD

**Issue by vitorgalvao** [mltframework/shotcut#245]
When encoding a video, it’s frequent I’ll want to lower its dimensions (width and height). However, to do it proportionally, currently I need to manually calculate one of the values, as they do not change automatically in proportion.

The `Size and Position` Video Filter can resize proportionally (Size Mode: Fill), so why not the encoding panel? It’s a useful option to have.

**Comment by ddennedy** [comment]
We do not take feature or enhancement requests. This tracker is only for defects, and this is not a defect.

**Comment by vitorgalvao** [comment]
Apologies. I’ve looked for a CONTRIBUTING.md, but did not find one. I now see you have the “defects only, feature requests will be rejected” information [on the website](https://www.shotcut.org/discussionforum/).

Is the only way to make a feature request to pay and ask on the forums?
