### ISSUE TITLE
Changing clip on timeline speed crash

### ISSUE THREAD

**Issue by grizeldi** [mltframework/shotcut#251]
I dragged one clip on the time line, split it at the playhead and tried to change speed of one part (in properties panel). When I hit enter after changing the number, Shotcut crashes. Tried it several times and it happened every time. Not even changing the number with up and down buttons next to the speed tex area works.

OS: Windows 7, 64 bit
Shotcut: 16.06.01

EDIT: Dragging the clip at the end of the timeline, changing it's speed and then dragging it back works.

**Comment by ddennedy** [comment]
I can confirm this is a new bug with v16.06, but there is a really easy and simple workaround. Do not press Enter. Simply remove focus from the speed field by press Tab or clicking elsewhere.

**Comment by grizeldi** [comment]
Here it still crashes by clicking elsewhere...

**Comment by ddennedy** [comment]
Maybe clicking elsewhere depends much on where you click, and that is a lot
places to check and communicate about. How about tab for you?

**Comment by ddennedy** [comment]
Yeah, the more I test this, I see Tab and click elsewhere are not reliable workarounds. Also, changing any clip properties is having a problem.

**Comment by grizeldi** [comment]
Cool, thanks!

**Comment by ddennedy** [comment]
There is a new version 16.06.08 available for download that contains this fix and another crash fix.
