### ISSUE TITLE
melt starts in the middle of the playlist 

### ISSUE THREAD

**Issue by CarlFK** [mltframework/shotcut#252]
my python script generates a foo.mlt works fine 100's of times.
This one is tripping some bug.  It may be I am generating an invalid mlt, but I figured I would provide steps to repo it, maybe it is melt.   I worked around the problem by simplifying the data my python script uses (I consolidated a bunch of clips) so it isn't a blocker for me.  

```
wget -N --force-directories -i http://veyepar.ndv.cdn.nextdayvideo.com/veyepar/eric/write_docs_na_2016/mlt/Lightning_Talks_13.urls

http://veyepar.ndv.cdn.nextdayvideo.com/veyepar/eric/write_docs_na_2016/mlt/Lightning_Talks_13.mlt

http://veyepar.ndv.cdn.nextdayvideo.com/veyepar/eric/write_docs_na_2016/titles/Lightning_Talks_13.png
http://veyepar.ndv.cdn.nextdayvideo.com/veyepar/eric/write_docs_na_2016/assets/ndv-169.png

http://veyepar.ndv.cdn.nextdayvideo.com/veyepar/eric/write_docs_na_2016/dv/crystal_ballroom/2016-05-23/12_59_18.ts.webm
http://veyepar.ndv.cdn.nextdayvideo.com/veyepar/eric/write_docs_na_2016/dv/crystal_ballroom/2016-05-23/13_29_18.ts.webm

cd "veyepar.ndv.cdn.nextdayvideo.com/veyepar/eric/write_docs_na_2016/dv/crystal_ballroom/2016-05-23"
ln -s 12_59_18.ts.webm 12_59_18.ts
ln -s 13_29_18.ts.webm 13_29_18.ts
```
$ melt --version 
melt 6.3.0
$ cd veyepar.ndv.cdn.nextdayvideo.com/veyepar/eric/write_docs_na_2016
$ melt mlt/Lightning_Talks_13.mlt 

It should start with Lightning_Talks_13.png for 5 seconds, then fade into 12_59_18.ts
instead it starts with 13_29_18.ts

loading this into shotcut would normally show the clips on the time line, but for this one it just treats it as a single asset.

**Comment by ddennedy** [comment]
Do not use the Shotcut project for this kind of bug report. melt runs the last producer (not necessarily <producer>, more often a <tractor>, which is also a producer) in the composition. The last producer in your MLT XML is clearly "../dv/crystal_ballroom/2016-05-23/13_29_18.ts" and melt is doing what it was told.
