### ISSUE TITLE
HTML5 overlay filter exhibits inconsistent timing (fps) in exported render.

### ISSUE THREAD

**Issue by veganaize** [mltframework/shotcut#253]
**Windows** 8.1 (64-bit)
**Shotcut** 16.06.01

I'm creating some simple (information/instructional) videos that incorporate a .wav audio track (exported into aac, mp3, etc.) with a 1080 background image (in shotcut's timeline; on top of the audio track).  All of this gets exported to:
1920x1080
16:9
FPS: 16
Progressive
BFF
YADIF-temporal+spatial
Bilinear

libx264
Q-VBR
60%
GOP: 13
B frames: 2
Codec threads: 0

44100
aac
avg bitrate
384k

^ Those are my typical settings...  I've tried a handful of variations on them but the resulting output is, often times, varying the effective FPS. .

When I first created a short (~15 second) HTML5 animation and added it to the image track, it all seemed to play fine (pretty much in sync, as far as I could tell).  As the animation grew (30+ seconds; more assets; but only amounting to a few image and text slide-ins), **it began to exhibit a mind of its own, during export renders, for frame rate** (sometimes slower, sometimes faster).

I'd remembered reading about how most browsers "loose it" when the frame-rate of animated GIFs exceed 16 FPS.  So I set the framerate of my project (export settings) to 16 FPS.  That seemed to fix the issue for a short time.  I have since added another, separate HTML5 animation about 1 minute into the video.  Even if the first animation (during the first minute) runs too slow/fast, the second animation begins exactly when it should and seems to stay in sync so far.

**Comment by ddennedy** [comment]
CSS Animation does not work. Only Javascript animation using the WebVfx extensions preserves the animation speed and timing. There is no way around this.
See this: https://www.shotcut.org/howtos/tumult-hype/

**Comment by veganaize** [comment]
Thank you.  I'm using Google Web Designer (GWD) and it apparently has a similar Javascript timing library that controls the timings of the HTML/CSS/Javascript animations (at least when rendered through a web browser).  I don't have access to a Mac (and as far as purchasing software...  I currently have about 18$ to my name=).  Any chance at incorporating Google's P.O.S. Web Designer timing format?  It seems to render fairly consistently (automatically), in a web browser, after the image assets and such are loaded/buffered in.

**Comment by ddennedy** [comment]
No, it is not possible because Web Designer relies upon  CSS animation. You can play the animation in a web browser and make a screen capture of it.
