### ISSUE TITLE
FAQ: why is there no 32 bit windows version available?

### ISSUE THREAD

**Issue by exclusivejeremy** [mltframework/shotcut#254]
For the FAQ.
Why is there no 32 bit windows version available?

**Comment by ddennedy** [comment]
A 32-bit process on Windows is limited to 2GB memory, which is not enough for this multitrack video editor. Also, the last time I tried to make a 32-bit build after upgrading some heavily used libraries, compiler, and runtime; I could not get the app to launch.

**Comment by ddennedy** [comment]
Version 16.10 just released today includes a 32-bit version for Windows.
