### ISSUE TITLE
HTML overlay filter remains active after removal

### ISSUE THREAD

**Issue by veganaize** [mltframework/shotcut#255]
**Windows 8.1** (64-bit)
**Shotcut** 16.06.01

After adding two separate HTML overlay filters (non-WebVfx), saving, removing (all) filters with the minus button [-], saving & closing... **the animation still renders the HTML overlay**.  I've tried re-saving and restarting -- Doesn't help.  If I re-add the HTML overlay filters then it will render them _TWICE_.  I can tell because the timing between the two (identical) overlays is erratic.  So I can see the animation trailing itself slightly (a mouse-trail like effect).

_Thank you_

**Comment by ddennedy** [comment]
Unable to reproduce. Maybe you still have a HTML filter attached to something else like the track or the whole timeline. Pay attention to what is selected. Otherwise, I need exact steps to reproduce starting from a new project.

**Comment by veganaize** [comment]
You are correct.  Apparently it was attached to the whole track.  Clicking & un-clicking the checkbox next to Video->Overlay HTML (in filters) and _then_ clicking the minus sign removed all of it.

I didn't realize that I could apply an effect to an entire track like that.  Thank you.
