### ISSUE TITLE
Cant export to webm

### ISSUE THREAD

**Issue by julius1986** [mltframework/shotcut#256]
Im not sure, but i cant export in webm format. 
I use windows 8.1(russian).  Shotcut version 16.06.08.

**Comment by ddennedy** [comment]
It works for me. Do not the Format drop-down above the tabs of the Export panel (unless you REALLY know what you are doing). Use a preset from the choices along the left of the Export panel.
If you still have a problem, you must provide exact details of the encoding settings. To do that, click + button at bottom of list of export presets. A dialog opens with a text box with several lines of text. Copy that text and paste it here.

**Comment by julius1986** [comment]
You are right. If i chooce on the left panel webm(not in drop-down list) it is doing auto settings for this format and i can export. Thx a lot.
