### ISSUE TITLE
Track compositing setting unavailable after reopening file

### ISSUE THREAD

**Issue by marksolly** [mltframework/shotcut#257]
After reopening a saved file that has 2 or more video tracks, the composite "C" button no longer works and compositing does not occur. However, the history shows "Change track compositing" when it's clicked.

Version: 16.06.08
OS: Windows 7 64 Bit

Steps to reproduce:

1. Open shotcut
1. Add two video tracks with video
1. Note that compositing is enabled on track 2 (uppermost track)
1. Save the project
1. Close & reopen shotcut
1. Note that compositing is now disabled on track 2
1. Click the "C" button and note that nothing happens

**Comment by marksolly** [comment]
Example .mlt file

**Comment by marksolly** [comment]
[borked.zip](https://github.com/mltframework/shotcut/files/311640/borked.zip)
Example .mlt file attached

**Comment by marksolly** [comment]
Bug is also present in version 16.05.01

Application log shows this, but no compositing occurs:
[Debug  ] <Timeline::CompositeTrackCommand::redo> trackIndex 0 composite Qt::CheckState(Unchecked) 
[Debug  ] <Timeline::CompositeTrackCommand::redo> trackIndex 0 composite Qt::CheckState(Checked) 
[Debug  ] <Timeline::CompositeTrackCommand::redo> trackIndex 0 composite Qt::CheckState(Unchecked) 
[Debug  ] <autosaveTask> running 
[Debug  ] <Timeline::CompositeTrackCommand::redo> trackIndex 0 composite Qt::CheckState(Checked)

**Comment by marksolly** [comment]
I've discovered an (awkward) workaround that probably hints at the origin of the bug:

1. Open shotcut
2. Add videos to playlist
3. Add 2 video tracks
4. Add videos from playlist to both tracks
5. Toggle compositing on track 2 off then back on again
6. Save .mlt file
7. Close & reopen shotcut
8. Rejoice because compositing still works!

**Comment by ddennedy** [comment]
Unable to reproduce and bug reports about GPU processing are not being accepted without a patch.

**Comment by marksolly** [comment]
I think you misread my report. The bug occurs when GPU rendering is turned
OFF.

Turning GPU rendering on and manually editing the .mlt file worked around
the problem but left me in the undesirable state of using the unsupported
GPU rendering feature.

**Comment by ddennedy** [comment]
I understood what you wrote after I sent the reply and spent more time trying to reproduce and study the information you provided. I am still not able to reproduce it with GPU off, given the steps above, and adding the missing step to open the project. 
frei0r.cairoblend is for CPU processing and movit.overlay is for GPU processing. It makes no sense to replace that.

**Comment by marksolly** [comment]
I'll try to gather more information. Is their anything in particular that
would be useful?

**Comment by ddennedy** [comment]
Try to reproduce it again using the steps you originally provided to verify the steps.
Clarify these 2:
> 6. Note that compositing is now disabled on track 2

Do you mean the "C" button on V2 is off/not highlighted? That is what I interpret it as but do not reproduce.

> 7. Click the "C" button and note that nothing happens

Do you mean that the highlight state of the "C" button does not switch when you click it?

Or do you mean there is compositing effect in the video preview? If that is what you mean, then 2 videos with no alpha channel information are not going to show any net effect using the default blending mode (by design).

**Comment by marksolly** [comment]
I've recorded a screen cast showing steps to reproduce this bug and also https://github.com/mltframework/shotcut/issues/258
View here: https://www.dropbox.com/s/kcvstoowcv9mil8/Shotcut%20Issues%20257%20and%20258%20.avi?dl=0

To clarify questions above:
1. Yes, the "C" button on V2 is not highlighted.
2. Yes, the "C" button on V2 cannot be toggled to the on state.
3. Yes, the compositing does not work

**Comment by marksolly** [comment]
In this video I note that shotcut prompts to restore from autosave files despite no unexpected exit condition on the first run. This might be part of the problem?

**Comment by ddennedy** [comment]
Strongly related to #258 and will be tracked there.
