### ISSUE TITLE
Shotcut menu label display: offset copy

### ISSUE THREAD

**Issue by chrisave** [mltframework/shotcut#260]
Some menu labels have an offset duplicate on top of them.

Shotcut version 16.06.08
Linux Mint 17.3 Rosa 64-bit (with Mate)

![shotcut_html_editor_menu_text_display_issue_1](https://cloud.githubusercontent.com/assets/14296961/16080535/9650d4f2-3309-11e6-971f-ee7f272e48dc.png)
![shotcut_html_editor_menu_text_display_issue_2](https://cloud.githubusercontent.com/assets/14296961/16080536/965455c8-3309-11e6-9df8-6c8a117bf39a.png)
![shotcut_menu_text_display_issue_1](https://cloud.githubusercontent.com/assets/14296961/16080537/968de0b8-3309-11e6-856e-5cd484c84f12.png)
![shotcut_menu_text_display_issue_2](https://cloud.githubusercontent.com/assets/14296961/16080538/96a179ac-3309-11e6-8856-16ebf47b8378.png)

**Comment by ddennedy** [comment]
This is the way disabled items appear on the dark theme.
