### ISSUE TITLE
Filters menu appears outside the window / screen

### ISSUE THREAD

**Issue by RainStormDay** [mltframework/shotcut#264]
Shotcut 16.06

Windows 10 Home version 1511
Windows 7 Professional Version 6.1, build 7601: service pack 1

When I click "add" in the filters tab, the menu sometimes appears in the correct place, but most often it appears outside the Shotcut window.  If the window is already full screen or occupying most of it, you cannot see it. It's not a big problem now that I know about it, but because I couldn't see it I spent hours trying to figure out why I cannot add filters. It was only when a friend tested it on a big screen that we figured out what was happening.

**Comment by RainStormDay** [comment]
Windows 10 Home version 1511
Windows 7 Professional Version 6.1, build 7601: service pack 1

**Comment by ddennedy** [comment]
Hmm, in fuil-screen mode, most popups and additional windows seem to be a problem on Windows (at least Win 10). I am going to have to that feature on Windows. Outside of that, I am having trouble to reproduce on the X axis. I can easily add some checks to the code setting the coordinates, which I will do, but not easy for me to confirm a fix. I can reproduce the bottom of the menu running off the bottom edge of the screen; so, that is my way to confirm the fix. Also, I can give you an interim build to test tomorrow.

**Comment by ddennedy** [comment]
Oh, I was only looking at the screen edges. Menus and popups in GUI apps are allowed to run beyond the edge of the window, but their origin should start within the window.

**Comment by RainStormDay** [comment]
Great, thank you! :)
I will be happy to test the build to see it fixes the problem in my system. 
Only one caveat: I am not a programmer myself, so I would greatly appreciate if you can provide me with an already compiled version.

About your comment: unless this particular GUI popup has a partially invisible geometry, I would say that its origin is clearly outside the window, as there is no graphical continuity between them. I will include a screenshot in a minute to illustrate what I mean.

**Comment by ddennedy** [comment]
I got it and agree. Not screenshot needed.

**Comment by ddennedy** [comment]
Fixed in 2498712
