### ISSUE TITLE
Procedure Entry Point Not Located in Qt5Core.dll

### ISSUE THREAD

**Issue by BillsBayou** [mltframework/shotcut#268]
Start program, Click "Open File..." button, the following error message pops up immediately:

The procedure entry point ?absoluteDir@QFileInfo@@QEBA?AVQDir@@XZ could not be located in the dynamic link library Qt5Core.dll

Click the OK button and the message pops up one more time. 

Shotcut version 16.06.08

Windows 7 64-bit, Service Pack 1
Intel Core i7-5600U 2.60 GHz
8GB Ram

**Comment by ddennedy** [comment]
From where did you download Shotcut? It works for me and many others without this problem. Does it prevent you from using the app or crash thereafter?

**Comment by BillsBayou** [comment]
Downloaded from this page: https://shotcut.org/download/

There is a crash issue as well.

Once the two message boxes are closed, I get the dialog box to open my videos.  I open three MTS format files.  I'm okay dragging one file to the timeline.  When I drag a second file to the timeline, the program crashes.

I've only started using the program yesterday, so I haven't done much beyond watch it crash.

**Comment by ddennedy** [comment]
I think it is safe to say that Shotcut is not compatible with your system, but I do not know what the problem is or how to figure out what it is (perhaps outside of you sending the computer to me or setting up a remote session ala TeamViewer - neither of which I am volunteering to do).

**Comment by BillsBayou** [comment]
Maybe the Qt software hates me.  Oh well.  Good luck with the software.

**Comment by ddennedy** [comment]
This can happen if you are using a Windows shell extension that is using a different version of Qt than Shotcut and not using -qtnamespace in a custom build of Qt. Anything which hooks into the system like this should use -qtnamespace to avoid a problem like this. Some possible examples are Tortoise SVN (which I have installed but is not causing a problem for me) and Dell Backup and Restore.
See also this [Qt Forum post](https://forum.qt.io/topic/66447/qfiledialog-problem-entry-point-not-found/12).
