### ISSUE TITLE
shotcut not work on Ubuntu 16.10 

### ISSUE THREAD

**Issue by myswiat** [mltframework/shotcut#269]
Ubuntu 16.10 abandoned gstreamer 0.10 (not the repository), and shotcut needs to function gstreamer 0.10 (libgstapp-0.10.so.0), which makes the program does not work, because it does not like.

Info:
bin/shotcut: error while loading shared libraries: libgstapp-0.10.so.0: cannot open shared object file: No such file or directory

**Comment by ddennedy** [comment]
Closing because the next version 16.09 due Sept. 2 will be using a custom build of Qt 5.6.1 that does not depend on gstreamer.

**Comment by crysman** [comment]
This is not resolved yet, I am experiencing the same issue with Shotcut 16.12 on Xubuntu 16.10:

    ~/bin/Shotcut_16.12/Shotcut.app 12:19:08
    ❱ ./shotcut 
bin/shotcut: error while loading shared libraries: libgstapp-0.10.so.0: cannot open shared object file: No such file or directory

Shotcut 16.11 is working, though...
