### ISSUE TITLE
Crash when opening Filter properties

### ISSUE THREAD

**Issue by tin2tin** [mltframework/shotcut#270]
Unfortunately I had a crash when using the top menu to add a view of the filter properties. A pop up window opened above the user interface with a non qt theme looking frame, and when I tried to attached it to a tabbed window Shotcut crashed. 

Version 16.7.

Windows 8.

**Comment by ddennedy** [comment]
I have seen this too, but unfortunately I have not been able to fix it. A have found that a workaround is to double-click the filter window's title bar to return it to its original tabbed location. In general, double-click the title bar of any panel to make the panel float (separate window) or dock (embedded in main window).

**Comment by ddennedy** [comment]
Next release 16.09 will be using Qt 5.6.1, and we will see if this makes a difference. I could not find a reliable way to reproduce it on 16.08 or less in order to fully verify this.

**Comment by ddennedy** [comment]
Please re-test on v16.09. I did and was unable to reproduce it yet.

**Comment by tin2tin** [comment]
Yes, it seems to be solved.
