### ISSUE TITLE
Prores and mpeg export should not be listed as lossless

### ISSUE THREAD

**Issue by kieranjol** [mltframework/shotcut#272]
I'm using OSX 10.11.4 and Shotcut 16.07.01.

I'm not sure if this qualifies as a defect, but I don't think that prores should be listed as a lossless codec. Every implementation of it is lossy, and I'm not sure if any of the implementations could be regarded as visually lossless.

It seems that ALL-I implementations of mpeg2 and mpeg 4 are listed as lossless too. I think this could be misleading for users?

Thanks,

Kieran O'Leary - Irish Film Archive.

**Comment by ddennedy** [comment]
I do not disagree. Do you have a suggestion for the name of a new category for this class of presets? "intermediate" ?

**Comment by kieranjol** [comment]
I'm more familiar with preservation terms,so we'd call them 'mezzanine'
files. Might be too vague/obscure though.

Production ,or intermediate would be perfect I reckon?

**Comment by kieranjol** [comment]
:+1:
