### ISSUE TITLE
Fails on export with a specific JPG

### ISSUE THREAD

**Issue by lnx64** [mltframework/shotcut#277]
I have tried so many things, re-encoded the main video before putting it into the timeline, via handbrake, just to clean it up, downsized any of the graphics that were to be overlaid on the video, in case they were too large, but it just keeps failing.  If I try to view the line by right clicking on the exported failure, it's empty.  Most I can do is show you the XML and the application log itself.

Specs of the machine working on this:
Dual Quad Core Intel Xeon 2.8GHz
32GB RAM
2TB Hard Drives
Windows 10 64-bit

Please, is there anything you see wrong here that should be causing the video to fail like this, without even a log to give me a hint as to WHY it's failing on export?

I even tried on my laptop, which usually exports just fine, it's specs are as follows:
Intel i7 Quad Core 2.8GHz (Hyper Threading Enabled)
8GB RAM
480GB SSD
Windows 10 64-bit

It also fails, and the log and XML will be from that machine itself since it was the last I tried.  There was one failure opening the MLT file, but it's from the old video file that no longer exists, and the error was happening far before that file was deleted and should be ignored.
[faillog.txt](https://github.com/mltframework/shotcut/files/356561/faillog.txt)
[failxml.txt](https://github.com/mltframework/shotcut/files/356562/failxml.txt)

**Comment by lnx64** [comment]
Apparently this JPG may be the problem causing all my issues.  So far since removing it from the video track 2, the video has continued exporting so far.
![toy-story-3](https://cloud.githubusercontent.com/assets/2136976/16722079/54c51f1c-4712-11e6-91d5-6d3a4f91e8fc.jpg)

Seems like I'll need to convert it to a PNG or something, but a simple JPG shouldn't have stopped up the exporter like this when it viewed fine in the timeline.

I'll let you know if/when it finishes encoding without this JPG.

**Comment by lnx64** [comment]
It completed just fine without this JPG.  Hopefully the developer can have insight as to why a JPG caused problems, when no other problem seems to have an issue with it.

**Comment by bmatherly** [comment]
I am not able to reproduce your problem on my Windows system. But I am not able to use your xml file because I don't have any of the other media files. The provided JPG exports fine for me.

Some things you can do to help:
1) Reproduce the problem with the latest version of Shotcut (16.07.01)
2) Create a minimal project that reproduces the problem. Provide all the media and xml necessary to reproduce the problem, but make sure you pare it down to the bare minimum.

**Comment by lnx64** [comment]
Sorry for delay getting back to you, my father had a bad fall and needed to watch after him last night.

I have tried with the latest, same issue.

I just tried cutting it down, and it still didn't work..  If it's the image itself on it's own in video track 1, it will not fail.  However, if I make it on video track 2, to overlay on top of a video that is playing on track 1, it does fail, like it won't mix it with another source.  But when I take that JPG and convert it to a PNG, it exports without issue.

**Comment by lnx64** [comment]
Here's a zip file with the MLT and a source video and the JPG, that did fail on export, as it's my tested failure.

https://www.mediafire.com/?1d6p5kn11uv0ft1

**Comment by bmatherly** [comment]
Thanks for the test case. Using Shotcut 16.07.01, I can confirm that this problem exists on Windows, but not on Linux.

@ddennedy I don't have a Windows dev environment set up. Is this something you could take a quick look at?

**Comment by ddennedy** [comment]
I reproduced this on Windows. I can workaround it by either disabling parallel processing or disabling compositing on V2. If I change the mlt_service in the XML for the JPEG from pixbuf to qimage, it does not make a difference. For me, converting to PNG did not make a difference; it still fails. This suggests a problem with parallelism in the track compositor.

**Comment by ddennedy** [comment]
Wait, I overlooked that there are 2 image producers in this XML. So, yeah, using PNG did make it succeed.  Ok, odd.

**Comment by lnx64** [comment]
Thank you for looking at it and solving it so fast.  You guys are great!

**Comment by ve3** [comment]
I'm using Shotcut 18.05.08 but still can't export video with jpg image. The exported video showing "INVALID" instead of image.
