### ISSUE TITLE
Unable to open file with non-local and non-latin symbols in filenames [unicode]

### ISSUE THREAD

**Issue by regs01** [mltframework/shotcut#278]
Having Russian locale, trying to open a file with Chinese or Japanese symbols leads to error - unable to open file. Have to rename a file by cutting off non-Russian and non-Latin symbols/letters.

**Comment by ddennedy** [comment]
Which operating system are you using and version of Shotcut?

**Comment by regs01** [comment]
Windows 10 / Shotcut 16.07

**Comment by nsmarkop** [comment]
Same thing is happening for me with Korean on Windows 10 / Shotcut 16.07. If the file path / file name has Korean characters in it like "D:\Example\무한도전\example.mp4" then I get a message saying "Failed to open -file path-". If I move it out of that folder and make sure the file name is also not Korean then it loads the file fine.

**Comment by ddennedy** [comment]
@nsmarkop What is your Windows language setting?

**Comment by nsmarkop** [comment]
@ddennedy My Windows language setting is Korean as well.

**Comment by ddennedy** [comment]
In case a developer wants to work on this, take a look here:
https://github.com/mltframework/mlt/blob/master/src/win32/win32.c

MLT string properties standardize on UTF-8, and the app should be supplying the chosen filename to MLT as UTF-8. However, most libraries such as libavformat take the C string as given and pass it to fopen or similar. On Windows the string needs to be in [code page](https://msdn.microsoft.com/en-us/library/yeby3zcb.aspx) encoding. In win32.c the functions `mlt_properties_from_utf8()` and `iconv_from_utf8()` use the [libiconv](https://www.gnu.org/software/libiconv/) to convert UTF-8 to the appropriate code page. Even if MLT did not standardize on UTF-8 for string properties, the file name strings must still be able to pass through XML that is using UTF-8 encoding. So, if a file name is read from XML, it must be converted to code page before handing to most libraries or C runtime.

**Comment by Lmixa** [comment]
Good day!Windows 7 is my OS!tell me how to fix the startup,I want to open a MP4 file but it does not open.also, AVI, MKV,what you need to do to the files the program began to open?????Thanks in advance!!!
![7893](https://cloud.githubusercontent.com/assets/21083611/17740601/87c6ff58-6499-11e6-9a7f-c47f309a4804.jpg)

**Comment by ddennedy** [comment]
Fixed in MLT for next release due early May.
