### ISSUE TITLE
Video file opens with duration as "live," no ability to FF/scroll

### ISSUE THREAD

**Issue by erineldridge** [mltframework/shotcut#279]
Not too sure where to look for details of this problem but hopefully I can tell you enough.

OS: Win 10
Version: 16.07.01

A particular gameplay video I've made with OBS appears to open in a different mode than my other videos.  To the right of the "Current Position" (time index) control, the video duration is displayed as "/Live" and scanning/entering new times is disabled, as is fast forward and rewind.  The "properties" tab accurately shows that the playtime is around 2 and a half hours.  If the video itself is malformed in some way, it isn't showing in any of the VLC debug info I can find.

I've tried to workaround by just "adding" the video to the timeline, but this causes CPU usage and memory usage to go through the roof (task manager reports 6+GB of memory used before Shotcut is read as "stopped responding" by the OS and apparently halted).

**Comment by ddennedy** [comment]
This is by design because the clip does not pass the test for providing accurate seeking and cannot be used for editing. You have to convert it. Since you made this with OBS, it is important to use constant framerate in OBS encode settings; variable framerate is not accepted and might be the cause of this.

**Comment by ddennedy** [comment]
Since the Properties does show a duration, you might be able to use Shotcut to convert it. Open the clip, click Export and then Export File.

**Comment by erineldridge** [comment]
I think you might be right about the variable frame rate.  I was trying some different stuff with that video.  Not finding a way to verify that yet.

Oh well, thanks for the quick reply, and for the program itself.  It's been a fun intro to video editing, and mostly worked very well for my needs--specifically easily messing about with recordings that have multiple audio tracks.
