### ISSUE TITLE
Adjust opacity instead of fade with black

### ISSUE THREAD

**Issue by Nonononoki** [mltframework/shotcut#282]
Windows 10 Home, Shotcut 16.07.01

Hi there,

I am currently experiencing a bug with a certain feature of Shotcut, namely "Adjust opacity instead of fade with black".
Composite box is checked, but the video clip (V3) still fades with black and I'm unsure if I'm doing something wrong or if this is a technical problem.

![screenshot 30](https://cloud.githubusercontent.com/assets/11612388/17132902/200fa648-5324-11e6-9084-732d76ab90ea.png)

**Comment by ddennedy** [comment]
All video tracks blend/composite with track V1, which you have hidden. Underlying all of the video tracks is a black background. This is by design.

**Comment by schauder** [comment]
@ddennedy could you explain a little more how adjust opacity is supposed to work? Whenever I tried to use it, it was just the same as turning the fade in/out filters off.
