### ISSUE TITLE
Stabilize filter does not work after saving and reopening project file

### ISSUE THREAD

**Issue by bmatherly** [mltframework/shotcut#283]
OS: Windows 10 and Linux
Version: shotcut-win64-160727.exe and latest git head (Linux)
Steps to reproduce:
1) Open a clip, move it to the timeline
2) Apply stabilize filter to the clip and click "analyze". Save the .stab file in the same directory as the .mlt file.
Observe that the stabilize filter works
3) Save the project
4) Close the project
5) Open the project
Observe that the stabilize filter does not work. However the filter does say "Analysis Complete".

The problem only occurs if the .stab file is in the same directory as the project or in a lower folder. If I generate the .stab file outside of the project directory tree, then the path in the .mlt file is absolute and it will work when it is loaded.

**Comment by ddennedy** [comment]
producer_xml.c:on_end_filter() needs to call `qualify_property( context, properties, "results" )`, but that will screw up other filters using "results" that is not a filename.

**Comment by ddennedy** [comment]
It does qualify "filename" and filter vidstab also has filename; so, perhaps the vidstab filter should load from the filename property instead of results when filename ends with results.

**Comment by bmatherly** [comment]
I tested your changes. It works for me. Thanks Dan!

**Comment by chmorgan** [comment]
@bmatherly just got to looking at this and it looks like ddennedy found and fixed it but thank you for the heads up.

**Comment by bmatherly** [comment]
@chmorgan Sorry for the noise. When I saw the bug, I jumped to a conclusion because you had been working on it. Thanks again for your help.

**Comment by chmorgan** [comment]
@bmatherly it isn't an unreasonable assumption. I was thinking the same myself when I saw your msg.
