### ISSUE TITLE
Shotcut won't import video from Note 4 on Marshmallow

### ISSUE THREAD

**Issue by lnx64** [mltframework/shotcut#285]
Latest version of Shotcut, Windows.  16.07.01, Windows 10, 64-bit.

Importing the video results in an immediate crash.  Settings on the phone were 1080p60, using the stock camera app.  Video plays in other apps just fine without issue.

Here's a link to an example video file that won't import without crashing Shotcut.
https://www.mediafire.com/?y9jif4jogjvmlzf

I don't know if it has to do with it, but in VLC it plays normally, but in Media Player Classic, it's upside down (so I clearly recorded it with the phone flipped the wrong way I guess, and it's using meta data to rotate it in the players that support it, like VLC).

If I transcode the video in Handbrake, and import that one, it imports fine.

**Comment by lnx64** [comment]
So I think I found out what's causing it.  It's the rotation.  (I always hold landscape, never portrait).  If I have the phones bottom on the right, the videos, no matter what resolution, import just fine into Shotcut.  If the phone is held with it's bottom on the left, the videos fail to import and crash Shotcut.

I'm not sure why it's causing the crash, but I'm going to assume the meta data is causing it, that otherwise tell the player how to rotate the video.

**Comment by ddennedy** [comment]
I reproduce it on Windows, but interestingly not on Linux where I developed the solution to reorient the video. I also found a workaround. In Settings > Video Mode, choose something other that Automatic. That should provide me with a hint to fix it.

**Comment by ddennedy** [comment]
Fix will be in new release due Tuesday.
