### ISSUE TITLE
Unable to Disable GPU Rendering

### ISSUE THREAD

**Issue by MistahWrite** [mltframework/shotcut#286]
Unable to Disable GPU Rendering.  Enabled in the menu, but when shotcut starts it seems my laptop has no GPU so nothing is being rendered anymore.  Dang.  Uninstalled, reinstalled, same thing.   How do I manually change this setting in regedt32 or something??  Looks like I had a shot to use the program, but it got cut.... lol

Windows 10, latest version as of this writing.

Chad

**Comment by ddennedy** [comment]
I find it very difficult to believe you cannot disable GPU rendering. The first thing the code does in response to that menu option is to save the new setting. I can toggle GPU processing just fine on all of my systems.
The [FAQ](https://www.shotcut.org/FAQ/) explains where the registry settings are. This, in particular is:
HKEY_CURRENT_USER\SOFTWARE\Meltytech\Shotcut\player\gpu
Change or set it to "false"
Also, the Windows installer has an option to "Remove Shotcut Settings From Registry"!
