### ISSUE TITLE
v16.08 Crashes when cropping composited overlay tracks

### ISSUE THREAD

**Issue by SleekPanther** [mltframework/shotcut#287]
Windows 10, 64 Bit 
Recently updated to 16.08

I had existing projects involving split-screens (2 video tracks, the top one composited and using the **crop filter** so I could have 2 videos side by side). As soon as I hit play, Windows pops up with a  **Shotcut has stopped working** Error and the program exits.

Everything worked perfectly in 16.07 and I've had to downgrade back to that version since any way I try, 16.008 crashes when doing **cropped overlay tracks**

**Comment by ddennedy** [comment]
Thanks. I reproduced this. Also, I verified that using Size & Position filter alone does not.

**Comment by SleekPanther** [comment]
Yes, I usually also use the Size and Position filter in combination with the Crop filter (so I can move 1 video the the side), but Shotcut kept crashing before I could add Size and Position.

**Comment by ddennedy** [comment]
I uploaded a new version 16.08.04 to include this fix.
