### ISSUE TITLE
libx264 video encoding fails when switching to QVR from AVR with dual pass enabled

### ISSUE THREAD

**Issue by max-maag** [mltframework/shotcut#289]
**Steps to reproduce:**
 1. Create a clip.
 2. Select h.264 High Profile preset
 3. Select "Codec" tab.
 3. Switch "Rate Control" to "Average Bitrate".
 4. Enable "Dual pass".
 5. Switch "Rate Control" to "Quality-based VBR".
 6. Export file.

**Expected result:**
The video is exported properly.

**Actual result:**
The exported file contains no video information. It only displays a black screen, and no information about width, height, etc. are abailable. Audio works fine.

When observing the "Jobs" panel while exporting with "Dual pass" enabled you can see that two passes are perfomed. With "Dual pass" disable only one is performed. Since the "Dual pass" option is only visible with the "Average Bitrate" rate control I assume it should not apply when "Quality-based VBR" is selected.

**Other information**
The bug occured with Shotcut 16.08.04 on Windows 8.

**Comment by ldennedy** [comment]
Thanks for your detailed description. I've tried reproducing this on OSX and noticed the two job passes as well. The resulting file seems to match what you've described, so it seems like an issue with the application and dual pass as you said.

I'm going to tag this as reproduced, and see what can be done.

**Comment by ddennedy** [comment]
Thanks. It will be fixed in next version.
