### ISSUE TITLE
Timeline automatically scrolls to playhead after zoom, paste, move, filter activation etc.

### ISSUE THREAD

**Issue by raffi98** [mltframework/shotcut#290]
config : Shotcut version 16.08.04 on Win 7 64 bits

**steps to reproduce :**
- paste clip A in the timeline, a short one - say 4 frames
- append clip B, a long one
- place playhead far enough to loose sight of the first clip - let's say at 2 min
- scroll back horizontally (Alt+mousewheel)  at the start of the timeline to grab and move clip A
- zoom with Ctrl+mousewheel

**expected result :** 
you zoom here

**actual result :**
you have lost  your position and you find yourself at 2 min

Since you can scroll horizontally not only to place the playhead but also for grabbing a clip for instance, the playhead is not always at the place to be zoomed at. 
Wouldn't it be better to zoom, like in some drawing programs, on the center of the timeline  or even on the mouse position...

Regards

**Comment by ddennedy** [comment]
> Since you can scroll horizontally not only to place the playhead but also for grabbing a clip for instance, the playhead is not always at the place to be zoomed at.

This is by design. Timeline zoom in nearly all video editors including this one only adjusts the scale of the timeline and does not affect the play head position.

> Wouldn't it be better to zoom, like in some drawing programs, on the center of the timeline or even on the mouse position.

Currently the zooming action is affected by the play head position, which may unexpectedly cause the timeline to scroll, and it would be better to be able to zoom without that. So, I agree to this part - but without affecting the playhead position.

**Comment by raffi98** [comment]
Hi

I'm not sure whether i should open a new issue for this : I noticed same kind of behavior in an even simpler situation.
In the timeline panel :
- play head is at time= 0
- a clip is at t=100
- move the clip from 100 to 102
expected result : clip is moved and you see it
actual result : clip is moved but you can't see it, as timeline has been scrolled back to display the play head.

Regards
