### ISSUE TITLE
mouse scrolling in timeline

### ISSUE THREAD

**Issue by raffi98** [mltframework/shotcut#291]
config : Shotcut version 16.08.04 on Win 7 64 bits

**step to reproduce:**
- add 2 tracks
- populate them with clips and empty spaces
- place the mouse over an empty space in timeline
- Alt+mousewheel to scroll horizontally
- place mouse over a clip in timeline
- Alt+mousewheel to scroll horizontally

**expected result :**
there is no difference between the 2 ways

**actual result :**
the second scrolling action has no effect

the same thing also appears in vertical scroll (mousewheel only)

Regards

**Comment by ddennedy** [comment]
This is due to a limitation in the GUI toolkit and will not be addressed.
