### ISSUE TITLE
inconsistant decimal symbol representation in gui

### ISSUE THREAD

**Issue by raffi98** [mltframework/shotcut#292]
**config :**
Shotcut version 16.08.04 in french
on Win 7 64 bits in french with **french** decimal symbol which is the comma

**step to reproduce**
- paste a clip in the timeline
- add a gain filter
- modify gain by clicking once on the value and typing "9.5" on keypad

**expected result**
you enter 9.5

**actual result**
the value can't be entered, as the dot is refused as decimal symbol

Conforming to local or regional parameters - whatever it is called, makes the keypad useless, as one have to reach for the comma.
I searched the .mlt file for "gain" and saw that the value 9,5 is coded in another system/scale. This value uses a comma no matter the system decimal is a comma or a dot.
So is it possible to get rid of local parameters and hard code dot as decimal symbol in the gui?
Also note that this confusion doesn't exist for the second:frame separator for instance. So i would not consider as abusive if the decimal symbol is strictly defined too.

**what if.... changing the local parameter**
- i changed the local parameter for the decimal symbol to set the dot.
- i reopened the project

**results**
- the values are showed with dot decimal symbol
- but the values are changed : 9.5 became 6.0 and other filter values have been more or less randomly changed too
- opening  the mlt as a text shows that the gain value is coded consistently through the local parameter change (no dot or comma change, though the value itself changed)

Regards

**Comment by ddennedy** [comment]
> the value can't be entered, as the dot is refused as decimal symbol

This is working by design and will not be changed.

> I searched the .mlt file for "gain" and saw that the value 9,5 is coded in another system/scale. This value uses a comma no matter the system decimal is a comma or a dot.

See LC_NUMERIC on the root <mlt> element. That is what dictates the decimal separator for the file.

> So is it possible to get rid of local parameters and hard code dot as decimal symbol in the gui?

No

> Also note that this confusion doesn't exist for the second:frame separator for instance. 

That is not a decimal separator and does not apply here. Colon is used for non-drop-frame timecode, and semi-colon is used for drop-frame timecode.

**Comment by raffi98** [comment]
I changed one by one LC_NUMERIC, windows localization format value, and both of them :

- changing localization to English suffices to get the decimal point, 

- changing only LC_NUMERIC to English in a French localized OS doesn't set the point, but has an effect on absolute values in filters at least. (9.5 is reduced to 6.0, and some other weak values are reduced to 0). But this is observable only in the GUI, as the values in XML are left unchanged

- changing both of the values produces the combination of the two previous effects

**Comment by ddennedy** [comment]
This bug report is about "inconsistant decimal symbol representation in gui" and the steps to reproduce and results. If that is the case, attach a screen shot, preferably highlighting the inconsistency.

If you want to talk about editing the XML from one locale to another, please open another bug report and attach two small XML files that show your changes. Please be aware that, if you change LC_NUMERIC from a comma to period as the decimal point, that you must also change all of the non-integer numeric values as well to use the corresponding separator.
