### ISSUE TITLE
Starting by opening project from Explorer does not load project correctly.

### ISSUE THREAD

**Issue by XyllyX** [mltframework/shotcut#293]
Whenever I make a multi-video track with composite for transparency effects, saving it and loading the same .mlt file will results in my saturation filters being removed from all my video clips that use it, and the filter is also gone from the filters list. The composite feature also becomes unavailable (the "c" button on the track will not press.) on the auxiliary video tracks.

I am also noticing a lot of lag in the playback when, however my CPU and RAM usage are still only at 40-60% when rendering composite sections.

I can't get the filter or composite back until I reinstall, and when I reinstall, the filters and composite will not work until I remove and add a video track again, forcing me to recreate the track and re-adding the filters onto the clips which used to have the saturation filters. 

I'm using Windows 10 64-bit Home, using the current latest available version of shotcut at the time of writing (installed it on same day, and reinstalled it again)

i7 - 6700HQ
16GB DDR4
GTX 960m 2GB

**Comment by ddennedy** [comment]
It took me a while to reproduce this, but for me this only happens when I open Shotcut by double-clicking the project file in Explorer. The workaround is to start Shotcut and then use the recent view or File > Open to open the project. Can you please check if that works for you?

**Comment by XyllyX** [comment]
Ahh yes, this works, everything is where it should be now!

What could be causing this to happen? Although double-clicking the project file feels a little more convenient, I'm more than happy to continue working like this.

**Comment by XyllyX** [comment]
I've run into a new issue, after trying to add in a video track below my "base" track, removing it again (it had become a triple-video track timeline, then back to double), it set both my original video tracks to composite, and then after opening the project again (via open file), my video track was turned into an audio track but somehow the software still reads the audio clips as videos?


http://i.imgur.com/bufRrsM.png

**Comment by ddennedy** [comment]
> What could be causing this to happen?

A bug.

> I've run into a new issue

You have to create a new bug report for that. I am going to close this bug report when the original problem reported is resolved.

**Comment by ddennedy** [comment]
This is fixed for next release.

**Comment by littleraskol** [comment]
Just came here from my duplicate report, wanted to mention the workaround worked (excellent!), also that I am on Windows 7 64-bit in case this is useful info.
