### ISSUE TITLE
Error when activating sequence images

### ISSUE THREAD

**Issue by germanvallverdu** [mltframework/shotcut#299]
OS: Windows 8.1 Pro 64-bit - Intel Core i7 2600K - 16,0GB Doble-Canal DDR3 @ 668MHz - 232GB Samsung SSD 850 EVO 250GB (SSD)
Shotcut version 16.08.12
When I load an image and I want to activate the sequence of images the program stops working.
The images are in jpg format.
Are 2040 images in total
This began to happen from version 16.07 onwards

error message windows:

Firma con problemas:
  Nombre del evento de problema:	APPCRASH
  Nombre de la aplicación:	shotcut.exe
  Versión de la aplicación:	0.0.0.0
  Marca de tiempo de la aplicación:	57adbeda
  Nombre del módulo con errores:	libmlt++-3.dll
  Versión del módulo con errores:	0.0.0.0
  Marca de tiempo del módulo con errores:	57adbbd9
  Código de excepción:	c0000005
  Desplazamiento de excepción:	0000000000006904
  Versión del sistema operativo:	6.3.9600.2.0.0.256.48
  Id. de configuración regional:	3082
  Información adicional 1:	c68d
  Información adicional 2:	c68de55d732b40f2019150dff13c7fdd
  Información adicional 3:	2522
  Información adicional 4:	2522a15db22e8db8c2ff5a7f6684e40a

Lea nuestra declaración de privacidad en línea:
  http://go.microsoft.com/fwlink/?linkid=280262

Si la declaración de privacidad en línea no está disponible, lea la declaración de privacidad sin conexión:
  C:\Windows\system32\es-ES\erofflps.txt

**Comment by ldennedy** [comment]
Tried reproducing this on Windows 10 by exporting JPG stills of a video, then opened 2040 of them in a playlist and added them to the timeline. Although it takes an ungodly amount of time, I've experienced no crashes. For me, it froze when I tried to click anywhere else in the window but leaving it alone everything loaded eventually, around 10 minutes total. The stills would also play in the project timeline after a short delay. If there are any steps that you did that I haven't please tell me. Otherwise I would say just leave the application alone while it loads.

**Comment by ddennedy** [comment]
I am not reproducing it either. Tried a few times. It might be very intermittent. @ldennedy please test it again like 20 times.

**Comment by germanvallverdu** [comment]
The problem occurs as follows.
1- I open the program.
2- I go to the menu. Open File. I am seeking the first JPG image in the folder where are all images.
3- I click the Properties pane.
4- I click imagnes sequence.
5- The program stops working.

I can send them a picture of the screen if it's something any mail?

Sorry if nome explain well, but use a translator because I speak Spanish and I live in Argentina.

Thank you very much for the quick answer.

I will try to reproduce the problem on another computer I have, even if you only see dealgo happens to that computer and tell what happened is.

**Comment by ldennedy** [comment]
Yes, that is how we are testing it and the program does not crash. Sending a picture or a log won't help, it has to be reproducible by one of us.

Is this only happening with one specific sequence that you're trying? Or does it crash with any image sequence you load? If you export a new sequence using Shotcut > Export > stills/JPG and load that will it still crash?

**Comment by germanvallverdu** [comment]
Ordered images showing
        how the error happens
      
      
      
      El 19/08/2016 a las 16:09, Lauren Dennedy escribió:
    
    
      Yes, that is how we are testing it and the program does not
        crash. Sending a picture or a log won't help, it has to be
        reproducible by one of us.
      Is this only happening with one specific sequence that you're
        trying? Or does it crash with any image sequence you load? If
        you export a new sequence using Shotcut > Export >
        stills/JPG and load that will it still crash?
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mltframework/shotcut","title":"mltframework/shotcut","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mltframework/shotcut"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ldennedy in #299: Yes, that is how we are testing it and the program does not crash. Sending a picture or a log won't help, it has to be reproducible by one of us.\r\n\r\nIs this only happening with one specific sequence that you're trying? Or does it crash with any image sequence you load? If you export a new sequence using Shotcut \u003e Export \u003e stills/JPG and load that will it still crash?"}],"action":{"name":"View Issue","url":"https://github.com/mltframework/shotcut/issues/299#issuecomment-241108316"}}}

**Comment by ddennedy** [comment]
Recently, I added a crash handler for debug/development versions of Shotcut, and I ran into this crash while working on another bug. I was not able to determine exactly how to reproduce it, but the crash report did illustrate quite well a buggy part of code. So, I applied a fix for next release.

**Comment by germanvallverdu** [comment]
Hello, I continued testing
          the use of the program.
        I found that the error is generated when
          I want to load a sequence of
        images of more than 1000 files.
        If I create multiple folders with
        only 1000 files the program
        does not crash.
        Only then are able to save video
          segments and then merge them
        all into a single video.
        But it's a shame you
          have to do the whole process.
        
      Greetings, I
            hope the information will help them.
        
      
      El 19/08/2016 a las 16:09, Lauren Dennedy escribió:
    
    
      Yes, that is how we are testing it and the program does not
        crash. Sending a picture or a log won't help, it has to be
        reproducible by one of us.
      Is this only happening with one specific sequence that you're
        trying? Or does it crash with any image sequence you load? If
        you export a new sequence using Shotcut > Export >
        stills/JPG and load that will it still crash?
      —
        You are receiving this because you modified the open/close
        state.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mltframework/shotcut","title":"mltframework/shotcut","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mltframework/shotcut"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ldennedy in #299: Yes, that is how we are testing it and the program does not crash. Sending a picture or a log won't help, it has to be reproducible by one of us.\r\n\r\nIs this only happening with one specific sequence that you're trying? Or does it crash with any image sequence you load? If you export a new sequence using Shotcut \u003e Export \u003e stills/JPG and load that will it still crash?"}],"action":{"name":"View Issue","url":"https://github.com/mltframework/shotcut/issues/299#issuecomment-241108316"}}}

**Comment by germanvallverdu** [comment]
Hello, I continued testing the use of the program.
I found that the error is generated when I want to load a sequence of images of more than 1000 files.
If I create multiple folders with only 1000 files the program does not crash.
Only then are able to save video segments and then merge them all into a single video.
But it's a shame you have to do the whole process.

Greetings, I hope the information will help them.

**Comment by germanvallverdu** [comment]
Hello, I continued testing the use of the program.
I found that the error is generated when I want to load a sequence of images of more than 1000 files.
If I create multiple folders with only 1000 files the program does not crash.
Only then are able to save video segments and then merge them all into a single video.
But it's a shame you have to do the whole process.

Greetings, I hope the information will help them.
