### ISSUE TITLE
v14.07 on Windows 7 crashing on launch

### ISSUE THREAD

**Issue by elijah60** [mltframework/shotcut#30]

**Comment by ddennedy** [comment]
Needs to be retested on v15.09.

**Comment by ddennedy** [comment]
@elijah60 It would be great if you can retest this with v15.09. I have a system with Intel G45, which previously did not work but now does since this new version can use DirectX. Not saying it is totally crash free, but you should at least be able to start it and play a video. Thanks

**Comment by ddennedy** [comment]
Works for me now with a very similar GPU.
