### ISSUE TITLE
Crop filter removed or altered after splitting video

### ISSUE THREAD

**Issue by Catch33** [mltframework/shotcut#301]
OS Windows 10, Shotcut 16.08.12

1. Add video file to video track.
2. Add crop filter, for example crop 200 pix from bottom.
3. Split video into 2 clips.
4. Select a clip and look at the crop filter, the 200 pix crop is gone on both video clips.

**Comment by ddennedy** [comment]
Not able to reproduce. Consider making a screencast video showing the problem.

**Comment by Catch33** [comment]
OS Windows 10, Shotcut 16.08.12
I changed my display scaling from 125% to 150%, and now I can't reproduce the problem, however the following problem occurred:

1. Add video file to video track.
2. Add crop filter, for example crop 200 pix from bottom.
3. Split video into 3 clips.
4. Cross-fade the clips
5. Select a clip and look at the crop filter, on some clips (it randomly) the 200 pix crop is gone or changed.

**Comment by ddennedy** [comment]
> I changed my display scaling from 125% to 150%, and now I can't reproduce the problem

You really expect that to affect it?!

> however the following problem occurred

Nope; that does not reproduce either. Do not reopen unless you have a screencast demonstrating it.
