### ISSUE TITLE
can't export EDL on Windows 10 using Korean locale

### ISSUE THREAD

**Issue by secondroms** [mltframework/shotcut#302]
When i try export edl, i show message that "a javascript error occured during export".
Work correctly on Ubuntu(Kxstudio 14.04), but Windows didn't.

This is my mlt file.

`<?xml version="1.0" encoding="utf-8"?>
<mlt LC_NUMERIC="Korean_Korea.949" version="6.3.0" title="Shotcut version 16.08.12" producer="main bin">
  <profile description="HD 1080p 25 fps" width="1920" height="1080" progressive="1" sample_aspect_num="1" sample_aspect_den="1" display_aspect_num="16" display_aspect_den="9" frame_rate_num="30" frame_rate_den="1" colorspace="709"/>
  <producer id="producer0" title="Anonymous Submission" in="00:00:00.000" out="00:00:30.100">
    <property name="length">00:00:30.133</property>
    <property name="eof">pause</property>
    <property name="resource">E:/Source/1.mp4</property>
    <property name="audio_index">1</property>
    <property name="video_index">0</property>
    <property name="mute_on_pause">0</property>
    <property name="mlt_service">avformat-novalidate</property>
    <property name="seekable">1</property>
    <property name="aspect_ratio">1</property>
    <property name="shotcut:hash">57ace9a3b16288aa1629a0632beab3f0</property>
    <property name="ignore_points">0</property>
    <property name="shotcut:caption">1.mp4</property>
    <property name="shotcut:detail">E:/Source/1.mp4</property>
    <property name="shotcut:comment"></property>
    <property name="global_feed">1</property>
    <property name="xml">was here</property>
  </producer>
  <producer id="producer1" title="Anonymous Submission" in="00:00:00.000" out="00:00:30.000">
    <property name="length">00:00:30.033</property>
    <property name="eof">pause</property>
    <property name="resource">E:/Source/2.mp4</property>
    <property name="audio_index">1</property>
    <property name="video_index">0</property>
    <property name="mute_on_pause">0</property>
    <property name="mlt_service">avformat-novalidate</property>
    <property name="seekable">1</property>
    <property name="aspect_ratio">1</property>
    <property name="shotcut:hash">2381b64c2752ad72c47c7c1492025d4a</property>
    <property name="ignore_points">0</property>
    <property name="shotcut:caption">2.mp4</property>
    <property name="shotcut:detail">E:/Source/2.mp4</property>
    <property name="shotcut:comment"></property>
    <property name="global_feed">1</property>
    <property name="xml">was here</property>
  </producer>
  <playlist id="main bin" title="Shotcut version 16.08.12">
    <property name="xml_retain">1</property>
    <entry producer="producer0" in="00:00:00.000" out="00:00:30.100"/>
    <entry producer="producer1" in="00:00:00.000" out="00:00:30.000"/>
  </playlist>
  <producer id="black" in="00:00:00.000" out="00:00:13.267">
    <property name="length">00:00:13.300</property>
    <property name="eof">pause</property>
    <property name="resource">black</property>
    <property name="aspect_ratio">1</property>
    <property name="mlt_service">color</property>
    <property name="set.test_audio">0</property>
  </producer>
  <playlist id="background">
    <entry producer="black" in="00:00:00.000" out="00:00:13.267"/>
  </playlist>
  <producer id="producer2" title="Anonymous Submission" in="00:00:00.000" out="00:00:30.133">
    <property name="length">00:00:30.167</property>
    <property name="eof">pause</property>
    <property name="resource">E:/Source/1.mp4</property>
    <property name="audio_index">1</property>
    <property name="video_index">0</property>
    <property name="mute_on_pause">0</property>
    <property name="mlt_service">avformat-novalidate</property>
    <property name="seekable">1</property>
    <property name="aspect_ratio">1</property>
    <property name="shotcut:hash">57ace9a3b16288aa1629a0632beab3f0</property>
    <property name="ignore_points">0</property>
    <property name="shotcut:caption">1.mp4</property>
    <property name="shotcut:detail">E:/Source/1.mp4</property>
    <property name="shotcut:comment"></property>
    <property name="global_feed">1</property>
    <property name="xml">was here</property>
  </producer>
  <producer id="producer3" title="Anonymous Submission" in="00:00:00.000" out="00:00:30.033">
    <property name="length">00:00:30.067</property>
    <property name="eof">pause</property>
    <property name="resource">E:/Source/2.mp4</property>
    <property name="audio_index">1</property>
    <property name="video_index">0</property>
    <property name="mute_on_pause">0</property>
    <property name="mlt_service">avformat-novalidate</property>
    <property name="seekable">1</property>
    <property name="aspect_ratio">1</property>
    <property name="shotcut:hash">2381b64c2752ad72c47c7c1492025d4a</property>
    <property name="ignore_points">0</property>
    <property name="shotcut:caption">2.mp4</property>
    <property name="shotcut:detail">E:/Source/2.mp4</property>
    <property name="shotcut:comment"></property>
    <property name="global_feed">1</property>
    <property name="xml">was here</property>
  </producer>
  <playlist id="playlist0">
    <property name="shotcut:video">1</property>
    <property name="shotcut:name">V1</property>
    <entry producer="producer2" in="00:00:00.000" out="00:00:04.700"/>
    <entry producer="producer3" in="00:00:00.000" out="00:00:08.533"/>
  </playlist>
  <tractor id="tractor0" title="Shotcut version 16.08.12" global_feed="1" in="00:00:00.000" out="00:00:13.267">
    <property name="shotcut">1</property>
    <track producer="background"/>
    <track producer="playlist0"/>
    <transition id="transition0">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
      <property name="mlt_service">mix</property>
      <property name="always_active">1</property>
      <property name="combine">1</property>
    </transition>
    <transition id="transition1">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
      <property name="version">0.9</property>
      <property name="mlt_service">frei0r.cairoblend</property>
      <property name="disable">1</property>
    </transition>
  </tractor>
</mlt>
`

OS:Windows 10 64 bit
Version:16.08.12

**Comment by ddennedy** [comment]
It works for me. The JavaScript code is installed to "C:\Program Files\Shotcut\share\shotcut\qml\export-edl\export-edl.js" if you want to try to fix it and submit a patch. Would most likely be something in one of the functions near the end of the file beginning with "MltXmlParser." In order to really debug it, you need node.js and see "test-node.js" in the "export-edl" folder.

**Comment by ddennedy** [comment]
Your XML worked for me in my development environment:
`
$ cd src/qml/export-edl/
$ ls
export-edl.js  main.js  mlt2edl.js  package.json  rebuild.sh*  test-node.js
$ npm install
npm WARN package.json mlt2edl@0.0.1 No repository field.
npm WARN package.json mlt2edl@0.0.1 No README data
timecode@0.0.3 node_modules\timecode

xmldoc@0.5.1 node_modules\xmldoc
└── sax@1.1.6

$ node test-node.js /c/tmp/test.mlt

 === playlist0 ===

001  1_mp4    AA/V  C        00:00:00:00 00:00:04:21 00:00:00:00 00:00:04:21
* FROM CLIP NAME: 1.mp4
002  2_mp4    AA/V  C        00:00:00:00 00:00:08:16 00:00:04:21 00:00:13:07
* FROM CLIP NAME: 2.mp4
`

**Comment by secondroms** [comment]
I change system locale korean to english. and it works fine now.
I think that it didn't work on multilingual environment.
This is my application log on korean locale system:

> [Info   ] <Application::Application(int&, char**)> Starting Shotcut version 16.08.12 
[Info   ] <Application::Application(int&, char**)> Windows version 192 
[Info   ] <Application::Application(int&, char**)> number of logical cores = 4 
[Info   ] <Application::Application(int&, char**)> locale = QLocale(Korean, Default, SouthKorea) 
[Info   ] <Application::Application(int&, char**)> install dir = "C:/Program Files/Shotcut" 
[Debug  ] <ShotcutSettings::singleton> language "ko_KR" 
[Debug  ] <ShotcutSettings::singleton> deinterlacer "onefield" 
[Debug  ] <ShotcutSettings::singleton> external monitor "" 
[Debug  ] <ShotcutSettings::singleton> GPU processing false 
[Debug  ] <ShotcutSettings::singleton> interpolation "nearest" 
[Debug  ] <ShotcutSettings::singleton> video mode "atsc_1080p_30" 
[Debug  ] <ShotcutSettings::singleton> realtime true 
[Debug  ] <MainWindow::changeTheme> begin 
[Debug  ] <MainWindow::changeTheme> end 
[Debug  ] <MainWindow::MainWindow()> begin 
[Debug  ] <Mlt::Controller::Controller()> begin 
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error opening shared object file 'C:\Program Files\Shotcut\lib\ladspa/AUTHORS': "C:\Program Files\Shotcut\lib\ladspa\AUTHORS": ?????? ?????? a?? ?? ???????.
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error opening shared object file 'C:\Program Files\Shotcut\lib\ladspa/COPYING': "C:\Program Files\Shotcut\lib\ladspa\COPYING": ?????? ?????? a?? ?? ???????.
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error finding ladspa_descriptor symbol in object file 'C:\Program Files\Shotcut\lib\ladspa/libfftw3f-3.dll': "ladspa_descriptor": ?????? ???��????? a?? ?? ???????.
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error opening shared object file 'C:\Program Files\Shotcut\lib\ladspa/readme.txt': "C:\Program Files\Shotcut\lib\ladspa\readme.txt": 
[Debug  ] <Mlt::Controller::Controller()> end 
[Debug  ] <Mlt::GLWidget::GLWidget(QObject*)> begin 
[Debug  ] <Mlt::GLWidget::GLWidget(QObject*)> end 
[Debug  ] <MainWindow::setupSettingsMenu> begin 
[Error  ] <MLT> [ 0x70deea0] The DeckLink drivers not installed.
[Debug  ] <MainWindow::setupSettingsMenu> end 
[Debug  ] <MainWindow::readPlayerSettings> begin 
[Debug  ] <MainWindow::readPlayerSettings> end 
[Debug  ] <MainWindow::configureVideoWidget> begin 
[Debug  ] <MainWindow::setProfile> "atsc_1080p_30" 
[Debug  ] <Mlt::Controller::setProfile> setting to profile "atsc_1080p_30" 
[Debug  ] <MainWindow::configureVideoWidget> end 
[Debug  ] <ScopeController::ScopeController(QMainWindow*, QMenu*)> begin 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> begin true 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> end 
[Debug  ] <AudioLoudnessScopeWidget::AudioLoudnessScopeWidget()> begin 
[Debug  ] <AudioLoudnessScopeWidget::AudioLoudnessScopeWidget()> end 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> begin 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> end 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> begin true 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> end 
[Debug  ] <AudioPeakMeterScopeWidget::AudioPeakMeterScopeWidget()> begin 
[Debug  ] <AudioPeakMeterScopeWidget::AudioPeakMeterScopeWidget()> end 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> begin 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> end 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> begin true 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> end 
[Debug  ] <AudioSpectrumScopeWidget::AudioSpectrumScopeWidget()> begin 
[Debug  ] <AudioSpectrumScopeWidget::AudioSpectrumScopeWidget()> end 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> begin 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> end 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> begin true 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> end 
[Debug  ] <AudioWaveformScopeWidget::AudioWaveformScopeWidget()> begin 
[Debug  ] <AudioWaveformScopeWidget::AudioWaveformScopeWidget()> end 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> begin 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> end 
[Debug  ] <ScopeController::ScopeController(QMainWindow*, QMenu*)> end 
[Debug  ] <RecentDock::RecentDock(QWidget*)> begin 
[Debug  ] <RecentDock::RecentDock(QWidget*)> end 
[Debug  ] <PlaylistDock::PlaylistDock(QWidget*)> begin 
[Debug  ] <PlaylistDock::PlaylistDock(QWidget*)> end 
[Debug  ] <TimelineDock::TimelineDock(QWidget*)> begin 
[Debug  ] <TimelineDock::TimelineDock(QWidget*)> end 
[Debug  ] <FiltersDock::FiltersDock(MetadataModel*, AttachedFiltersModel*, QWidget*)> begin 
[Debug  ] <FiltersDock::FiltersDock(MetadataModel*, AttachedFiltersModel*, QWidget*)> end 
[Debug  ] <EncodeDock::EncodeDock(QWidget*)> begin 
[Debug  ] <EncodeDock::EncodeDock(QWidget*)> end 
[Debug  ] <JobsDock::JobsDock(QWidget*)> begin 
[Debug  ] <JobsDock::JobsDock(QWidget*)> end 
[Debug  ] <MainWindow::readWindowSettings> begin 
[Debug  ] <MainWindow::readWindowSettings> end 
[Debug  ] <LeapNetworkListener::start> begin 
[Debug  ] <MainWindow::MainWindow()> end 
[Debug  ] <Database::run> Database version is 1 
[Debug  ] <FiltersDock::resetQview> begin 
[Warning] <> libpng warning: iCCP: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG
[Debug  ] <MainWindow::open> "C:/Users/SLADE/AppData/Local/Meltytech/Shotcut/__untitled__.mlt" 
[Debug  ] <MltXmlChecker::MltXmlChecker()> decimal point '.' 
[Debug  ] <MltXmlChecker::check> begin 
[Debug  ] <MltXmlChecker::check> end 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "alpha_adjust" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Alpha Channel: Adjust" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "alpha_view" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Alpha Channel: View" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_balance" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Balance" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_bandpass" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Band Pass" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_basstreble" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Bass & Treble" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_channelcopy" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Copy Channel" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_compressor" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Compressor" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_delay" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Delay" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_expander" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Expander" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_fadein" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade In Audio" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_fadeout" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade Out Audio" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_gain" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Gain / Volume" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_highpass" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "High Pass" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_limiter" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Limiter" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_lowpass" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Low Pass" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_mono" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Downmix" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_mute" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Mute" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_normalize_1p" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Normalize: One Pass" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_normalize_2p" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Normalize: Two Pass" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_notch" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Notch" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_pan" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Pan" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_reverb" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Reverb" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_swapchannels" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Swap Channels" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "bluescreen0r" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Chroma Key: Simple" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "blur" "meta_boxblur.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Blur" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "blur" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Blur" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "brightness" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Brightness" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "brightness" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Brightness" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "color" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Color Grading" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "color" "meta_frei0r_coloradj.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Color Grading" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "color" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Color Grading" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "contrast" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Contrast" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "contrast" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Contrast" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "crop" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Crop" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "crop" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Crop" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "dust" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Old Film: Dust" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "dynamictext" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Text" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "fadein_brightness" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade In Video" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "fadein_movit" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade In Video" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "fadeout_brightness" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade Out Video" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "fadeout_movit" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade Out Video" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "glow" "meta_frei0r.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Glow" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "glow" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Glow" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "grain" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Old Film: Grain" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "invert" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Invert Colors" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "keyspillm0pup" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Key Spill: Advanced" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "lines" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Old Film: Scratches" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "mirror" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Mirror" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "mirror" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Mirror" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "movit_diffusion" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Diffusion" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "oldfilm" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Old Film: Projector" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "opacity" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Opacity" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "opacity" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Opacity" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "rotate" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Rotate" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "saturation" "meta_frei0r.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Saturation" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "saturation" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Saturation" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "select0r" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Chroma Key: Advanced" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "sepia" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Sepia Tone" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "sharpen" "meta_frei0r.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Sharpen" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "sharpen" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Sharpen" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "size_position" "meta_affine.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Size and Position" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "size_position" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Size and Position" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "smartblur" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Reduce Noise" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "spillsuppress" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Key Spill: Simple" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "stabilize" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Stabilize" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "tcolor" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Old Film: Technocolor" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "vignette" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Vignette" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "vignette" "meta_oldfilm.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Vignette" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "wave" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Wave" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "webvfx" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Overlay HTML" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "webvfx_circular_frame" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Circular Frame (HTML)" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "webvfx_ruttetraizer" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Rutt-Etra-Izer (HTML)" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "webvfx_threejs_text" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "3D Text (HTML)" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "white" "meta_frei0r.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "White Balance" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "white" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "White Balance" 
[Debug  ] <AudioLoudnessScopeWidget::resetQview> begin 
[Debug  ] <Mlt::GLWidget::initializeGL> begin 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL vendor "NVIDIA Corporation" 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL renderer "GeForce GTX 750 Ti/PCIe/SSE2" 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL threaded? true 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL ES? false 
[Debug  ] <Mlt::GLWidget::initializeGL> end 
[Debug  ] <LeapNetworkListener::onDisconnected> Disconnected from Leap Motion 
[Debug  ] <LeapNetworkListener::onError> Leap Motion WebSocket error: "\uC5F0\uACB0\uC774 \uAC70\uBD80\uB428" 
[Debug  ] <MainWindow::open> "E:/Source/test/test.mlt" 
[Debug  ] <MltXmlChecker::MltXmlChecker()> decimal point '.' 
[Debug  ] <MltXmlChecker::check> begin 
[Debug  ] <MltXmlChecker::check> end 
[Debug  ] <TimelineDock::setSelection> Changing selection to (0)  trackIndex -1 isMultitrack false 
[Info   ] <MainWindow::open> "E:/Source/test/test.mlt" 
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Error  ] <MainWindow::on_actionExportEDL_triggered> Uncaught exception at line 407 : "SyntaxError: Expected token `numeric literal'" 
[Info   ] <MainWindow::showStatusMessage> "A JavaScript error occurred during export."

**Comment by ddennedy** [comment]
Thank you. I was about to ask you for the application log. The important line is `[Error ] MainWindow::on_actionExportEDL_triggered Uncaught exception at line 407 : "SyntaxError: Expected token `numeric literal'"`.
That corresponds to this line in export-edl.js:
`finalVal = finalVal.substring(0,25).trim() + "…";`

This file is aggregated JavaScript, and that line of code comes from dependent project [xmdoc](https://github.com/nfarina/xmldoc). The line looks OK from a syntax perspective; however, when viewing it with a hex editor, the string "..." is not simply 3 periods. Rather, it is hexadecimal e2 80 a6, which is the [ellipsis character in UTF-8](http://www.fileformat.info/info/unicode/char/2026/index.htm). I am not certain if that is the problem, but it can be interesting if you change that string on that line to use 3 periods, and see if the problem goes away. I would appreciate if you can test that.

**Comment by secondroms** [comment]
I change … to 3 periods and it works correctly on korean locale system. Thank you!
