### ISSUE TITLE
Changing picture duration deletes filters

### ISSUE THREAD

**Issue by grizeldi** [mltframework/shotcut#303]
I added a picture to my timeline and added some filters to it. Then I added a video after the picture to the timeline. Then I changed duration of the picture from 4 sec to 5 sec. Filters were no longer there.

System info:
Windows 7, 64 bit
Shotcut 16.8.12

**Comment by ldennedy** [comment]
Duplicate of issue [#297](https://github.com/mltframework/shotcut/issues/297), which has already been fixed and will be included in the next release of Shotcut.

**Comment by grizeldi** [comment]
Okay, sorry.
