### ISSUE TITLE
Setting blend mode to anything different than "over" causes crash

### ISSUE THREAD

**Issue by AGI-THB** [mltframework/shotcut#304]
Shotcut version: 16.08.12
OS: Win7 64bit and Linux Mint 18 x64 Cinnamon

I'm new to video editing and played around with the programm today.
When having two timeline tracks  and setting "blend mode" of track v2 to "add" the programm crashes immediatly. 
Don't know if its just me. I reproduced the crash on two different machines (desktop and laptop) with windows 7 and linux mint 18. 

`http://fs5.directupload.net/images/160830/wn3akdti.png`

**Comment by ldennedy** [comment]
Also confirmed crashing on OSX. Thank you for reporting the crash, hopefully it can be fixed in the upcoming new release of Shotcut this month.

**Comment by AGI-THB** [comment]
Well, I created this issue a little too fast it seems. The other blend modes also crash.  Don't know if you noticed it too. Sorry for the inconvenience.

**Comment by ddennedy** [comment]
Fixed in MLT for next release.
