### ISSUE TITLE
With some transition types there is a warning of missing file in the project file

### ISSUE THREAD

**Issue by VosaXalo** [mltframework/shotcut#305]
Hi,
I have found out that if I set some type of video transition, when the project file (.mlt) is reopened, there is a warning that a file is missing. For example if I set the transition type "**Matrix Waterfall Horizontal**", when I reopen the project file, a dialog is displayed showing that the file "**%luma09.pgm**" is missing.
In the zip file that I have attached you can find an example of project that has this issue, and a screenshot of the dialog with the warning of the missing file.
[shotcut_missing_file_issue.zip](https://github.com/mltframework/shotcut/files/445547/shotcut_missing_file_issue.zip)

I have tried with different transitions type, and the issue is always present.
I have also noted that if you do nothing, and you close the dialog, then the project opens correctly. Maybe this warning is a "false positive".

I use Shotcut version 16.08.12 on Ubuntu 16.04 LTS 64bit

**Comment by sguilly** [comment]
Hi,

Same issue with a missing 'white' file at startup after create transition between two clips.

I use Shotcut version 16.08.12 on Ubuntu 16.04 LTS 64bit

**Comment by ldennedy** [comment]
Reproduced this issue on Windows 10, ver 16.08.12. The next release of Shotcut is coming up very soon, so a fix might be possible in that time.

I found it happens for every kind of transition besides cut or dissolve. My best guess would be that the issue has something to do with the [luma transition](https://www.mltframework.org/bin/view/MLT/TransitionLuma) and filter plugins in the MLT Framework, or at least how Shotcut receives information from them. Each of these filters uses that grayscale map processing described in the page, and each missing file message points to a luma file.

Not sure what exactly is causing the issue though.

**Comment by ddennedy** [comment]
@sguilly I do not reproduce that. You can file a separate bug if you provide either step-by-step directions or attach a project file (preferably a small one).

**Comment by pravynandas** [comment]
Hi @ddennedy here is quick video to reproduce the error in most recent version 19.12.31 [https://youtu.be/Hvz9TW7aGvE](SHOTCUT | Missing file error) and I have discussion a quick fix using xml cleanup. But it would be nice to have a more promising fix. Thanks for the great tool.

**Comment by Sjlver** [comment]
This did happen to me as well. One vote for the bug being re-opened. There seems to be a good way to reproduce thanks to @pravynandas 's work.

**Comment by ddennedy** [comment]
He posted about a version that is over a year old, and there have been 9 releases since then. Moreover, this bug was resolved over 4 years ago. I just repeated the steps in his video on the latest version 21.01. If someone has this problem on a recent version - 20.11 or 21.01 - and can provide the steps, they should open a **new** bug.
