### ISSUE TITLE
Multi-monitor support broken

### ISSUE THREAD

**Issue by lnx64** [mltframework/shotcut#309]
I made a video of this issue for you as it's a lot harder to explain than it is just seeing it do this.  This is the 16.09.01 version of Shotcut, latest drivers for my video card, and up to date Windows 10 64-bit.  The multiple video test on multiple screens at the end were 4k video files btw, and the test video I pushed through Shotcut was 1080p 24fps.

https://www.youtube.com/watch?v=VddsAyverf4

In a nut shell though, second display shows up blank, then when content is supposed to be playing, it's a small white square.  The only workaround is to goggle this option off and back on in the settings menu, and even then, sometimes the framerates are atrocious, and very choppy at best.

**Comment by ddennedy** [comment]
I am not able to improve the frame rate. It is gated by when the Qt is sending me signals (callback). You have to use a Blackmagic Design SDI/HDMI peripheral to get really smooth playout.

**Comment by lnx64** [comment]
How do you select DirectX as the option when you select an external screen?  Those options vanish when an external monitor is selected.

**Comment by ddennedy** [comment]
Settings > Display Method is only hidden when GPU Processing is enabled because GPU processing requires OpenGL.

**Comment by ddennedy** [comment]
Also, I have found that after switching to Direct X and restarting when prompted, it does not always switch properly. You may need to restart again manually. View > Application Log, and scroll down past most of the begin/end lines and look for:

    [Info   ] <Mlt::GLWidget::initializeGL> OpenGL vendor "Google Inc." 
    [Info   ] <Mlt::GLWidget::initializeGL> OpenGL renderer "ANGLE (

**Comment by lnx64** [comment]
Sadly using DirectX made things worse.  Timeline buttons went grey and are acting very funny.

![capture](https://cloud.githubusercontent.com/assets/2136976/18596255/3a242854-7c16-11e6-844e-9d82b97f8d1a.PNG)

**Comment by ddennedy** [comment]
Your mileage may vary. Both OpenGL and DirectX are high level APIs to big complicated things in the driver, firmware, and hardware. You can file a separate bug about the external monitor framerate issue if you want, but the problem reported here is resolved for next release, and I only track problem per issue report.

**Comment by lnx64** [comment]
That's fine, I'll deal with the frame rate issue, you already said you can't improve it, so there's no need to make another bug report.

**Comment by ddennedy** [comment]
What is your GPU BTW? I do not get a lot feedback about the DirectX method.

**Comment by lnx64** [comment]
It's a Radeon 7850, 1GB..

Besides the GUI artifacts, it was still slowish when any second video track is added with say, translucent PNG's (which I use for overlays).  Like it can go down to 1fps.  I know it's not real time and should drop the frames, but that's excessive in my opinion, because Adobe Premier works blazingly smooth on the same hardware.  But I prefer Shotcuts "flow" more, which is why I practically live off of it.

I may be switching back to Linux soon, so I may not be able to test DirectX much, but I'll hold off for now, and create the other ticket if you'd like me to?
