### ISSUE TITLE
External Monitor Performance Issues (Now affecting single monitor mode too)

### ISSUE THREAD

**Issue by lnx64** [mltframework/shotcut#311]
At the request of ddennedy.  "You can file a separate bug about the external monitor framerate issue if you want, but the problem reported here is resolved for next release, and I only track problem per issue report."

Performance on the external monitor seems to be a little more choppy than the primary monitor in single mode.  However, since messing with the DirectX mode, and putting it back to Automatic, the single monitor has some performance issues too.  In fact, I have found that turning OFF Realtime playback, actually speeds it up.  It's as if that realtime playback is taking more resources to drop the frames, which defeats the purpose of frame dropping.  For example, I get around 15fps in a 1080p 30fps video with realtime off, and with real time on, it's 1fps.  I can video tape how it reacts at request if you'd like.  I have tried GPU acceleration, but that seems to make things worse, and pixelated, and DirectX has glitches, so it's OpenGL mode only.

This is the 16.09.01 version of Shotcut, latest drivers for my video card, and up to date Windows 10 64-bit.

**Comment by ddennedy** [comment]
Non-realtime mode also enabled multi-core, frame-threaded image processing, which can explain the speed up. I do not know why you get 1fps simply playing a 1080p clip. There is definitely something wrong with Shotcut running on your Windows system with Automatic, but I do not know what that is.
