### ISSUE TITLE
[swscaler @ 0000000010779d20] Warning: data is not aligned! This can lead to a speedloss

### ISSUE THREAD

**Issue by HellScre4m** [mltframework/shotcut#312]
> [swscaler @ 0000000010779d20] Warning: data is not aligned! This can lead to a speedloss

This is 1st pass:
`<?xml version='1.0' encoding='utf-8'?>
<mlt root="F:\Program Files\Shotcut" parent="producer0" version="6.3.0" in="00:00:00.000" LC_NUMERIC="English_United States.1252" title="Shotcut version 16.07.01" out="00:00:07.930">
  <profile sample_aspect_den="1" display_aspect_den="292" height="292" frame_rate_num="6700" width="256" progressive="1" description="automatic" sample_aspect_num="1" display_aspect_num="250" colorspace="601" frame_rate_den="793"/>
  <consumer width="256" aspect="0.876712" preset="placebo" me_method="tesa" pass="1" f="mp4" mlt_service="avformat" minrate="0k" g="999" top_field_first="0" audio_off="1" an="1" vcodec="libx264" partitions="all" rc-lookahead="80" passlogfile="C:/Users/Sobhan/Downloads/Gifs/test.mp4_2pass.log" target="C:/Users/Sobhan/Downloads/Gifs/test.mp4" real_time="-4" r="8.449" vb="260k" height="292" rescale="hyper" progressive="1" keyint="infinite" direct="auto" trellis="2" no-fast-pskip="1" fastfirstpass="1" bf="0" deinterlace_method="yadif" slow-firstpass="1" subme="10" me_range="32" threads="1"/>
  <producer id="producer0" in="00:00:00.000" title="Shotcut version 16.07.01" out="00:00:07.930">
    <property name="length">00:00:07.930</property>
    <property name="eof">pause</property>
    <property name="resource">C:/Users/Sobhan/Downloads/Gifs/1152_1.mp4</property>
    <property name="seekable">1</property>
    <property name="aspect_ratio">1</property>
    <property name="audio_index">-1</property>
    <property name="video_index">0</property>
    <property name="mute_on_pause">0</property>
    <property name="mlt_service">avformat-novalidate</property>
    <property name="shotcut:hash">e1f84c56700d2e017066ee52a175c172</property>
    <property name="ignore_points">0</property>
    <property name="shotcut:caption">1152_1.mp4</property>
    <property name="shotcut:detail">C:/Users/Sobhan/Downloads/Gifs/1152_1.mp4</property>
    <property name="shotcut:comment"/>
    <property name="global_feed">1</property>
  </producer>
</mlt>
`
This is second pass:
`<?xml version='1.0' encoding='utf-8'?>
<mlt root="F:\Program Files\Shotcut" parent="producer0" version="6.3.0" in="00:00:00.000" LC_NUMERIC="English_United States.1252" title="Shotcut version 16.07.01" out="00:00:07.930">
  <profile sample_aspect_den="1" display_aspect_den="292" height="292" frame_rate_num="6700" width="256" progressive="1" description="automatic" sample_aspect_num="1" display_aspect_num="250" colorspace="601" frame_rate_den="793"/>
  <consumer width="256" aspect="0.876712" preset="placebo" me_method="tesa" pass="2" f="mp4" mlt_service="avformat" minrate="0k" g="999" top_field_first="0" audio_off="1" an="1" vcodec="libx264" partitions="all" rc-lookahead="80" passlogfile="C:/Users/Sobhan/Downloads/Gifs/test.mp4_2pass.log" target="C:/Users/Sobhan/Downloads/Gifs/test.mp4" real_time="-4" r="8.449" vb="260k" height="292" rescale="hyper" progressive="1" keyint="infinite" direct="auto" trellis="2" no-fast-pskip="1" bf="0" deinterlace_method="yadif" slow-firstpass="1" subme="10" me_range="32" threads="1"/>
  <producer id="producer0" in="00:00:00.000" title="Shotcut version 16.07.01" out="00:00:07.930">
    <property name="length">00:00:07.930</property>
    <property name="eof">pause</property>
    <property name="resource">C:/Users/Sobhan/Downloads/Gifs/1152_1.mp4</property>
    <property name="seekable">1</property>
    <property name="aspect_ratio">1</property>
    <property name="audio_index">-1</property>
    <property name="video_index">0</property>
    <property name="mute_on_pause">0</property>
    <property name="mlt_service">avformat-novalidate</property>
    <property name="shotcut:hash">e1f84c56700d2e017066ee52a175c172</property>
    <property name="ignore_points">0</property>
    <property name="shotcut:caption">1152_1.mp4</property>
    <property name="shotcut:detail">C:/Users/Sobhan/Downloads/Gifs/1152_1.mp4</property>
    <property name="shotcut:comment"/>
    <property name="global_feed">1</property>
  </producer>
</mlt>
`
I get this warning in almost all of my conversions (using video mode = auto, which I said in another issue is not completely accurate in terms of detecting correct width and fps). What is wrong?

**Comment by ddennedy** [comment]
The message comes from FFmpeg/libswscaler and the fact that rows of images in MLT do not necessarily begin on a 16 byte boundary. But this is legacy that cannot be changed now, or it will break too much existing code. The decision about way images are stored in memory in MLT preceeds the appearance of this warning message from libswscale. This is not something that will be addressed or fixed. A superficial fix could be to convert the image just before giving it to libswscale, but that has an obvious overhead as well. There is a huge amount of optimization work that can be done just as there is a huge amount of features that can be added. I do not consider lack of optimization to be a bug a bug or defect, which is what we use this tracking system for.
