### ISSUE TITLE
Undo increase of transition length removes clip from timeline

### ISSUE THREAD

**Issue by ltGuillaume** [mltframework/shotcut#313]
Whenever I try to **undo** a correction of a transition's start/end point by dragging it in the timeline, the undo action removes one of the clips entirely (the transition remains present). My guess is that the clip cannot be restored, because the transition's increase in length does not leave enough room to restore the clip. That would mean that the undo feature does not take into account that the undo action is twofold: restore the length of the transition AND restore the length of the clip. I have unfortunately been able to reproduce this on more than 10 occasions.

What usually causes my need to undo this correction is possibly another bug: changing the length of a transition oftentimes expands the entire left-side clip for no reason, which results in the entire set of clips to its right to be shifted along the timeline. Or, Shotcut removes the whole transition and the clips are linked together, even though I was _expanding_ the transition.

Windows 10 b10586; Shotcut x64 16.09.01

**Comment by ltGuillaume** [comment]
I feel I have to add that dragging clip and extending/contracting them on the timeline is extremely unresponsive: at times, my mouse cursor has already moved over 1/5 of the screen width before the clip actually starts to expand, and after it finally does acknowledge it needs to move, any response to mouse movement may take over two seconds.

**Comment by ddennedy** [comment]
@ltGuillaume There is nothing really can be done about the responsiveness of dragging without rewriting it completely, which I am not going to to do. I have noticed that it depends on speed of CPU and GPU of your system. On Windows, you can try to choose Settings > Display Mode > DirectX to see if it helps any. You may need to restart it again after it restarts the first time, to ensure it is really in DirectX mode.

**Comment by ltGuillaume** [comment]
Thanks for your response. I already did set it to DirectX, restarted and tried to drag and create some transitions. There still was a lag of 1-4 seconds, and after trying to undo a transition (the original issue) Shotcut crashed repeatedly.

**Comment by ddennedy** [comment]
Regarding the laggy reaction, there was actually a change for #294 that went into v16.10. It was to improve a specific case in Linux, but actually the change is not OS-specific and might help. Did you try the new version yet?

**Comment by ltGuillaume** [comment]
Just tried 16.10, such a huge difference that it can't be placebo or coincidence. Thanks!
