### ISSUE TITLE
Export missing from File Menu

### ISSUE THREAD

**Issue by tin2tin** [mltframework/shotcut#316]
Just a reminder from the forum. There is currently no Export(video) option in the File Menu.

**Comment by ddennedy** [comment]
I have not decided to add this. There is already View > Export and a corresponding toolbar button. So, what will File > Export do differently than View > Export? If it does the same thing, then I really doubt it will help people who cannot already figure out how to Export. It could, however, only export progressive H.264 MP4 with default settings, and use the Export panel for advanced or custom options. In any case, it is a suggestion and not a defect, and we only use this tracker for defects. So, I will close this, but you can still leave your reply with your opinion about the behavior of FIle > Export. Will it be confusing to some if it does something different than View > Export?

**Comment by tin2tin** [comment]
Ah, it's by design. I think most people would expect all file in/out operations to be accessible from the File Menu, especially now with the new Frame and EDL export options, you get the feeling that you also should be able to export video from this menu.  

Personally that was where I looked for it(I had the toolbar disabled), when that user kept asking about it. 

On the functionality I think File > Export should do the same as View > Export. It will be more confusing with a dumbed down function there.

Anyway, I fine with just keeping it as is now. I simply thought that it has disappeared by accident while implementing the frame/edl export and just wanted to remind you if that was the case.

**Comment by ddennedy** [comment]
I hear you about the expectations and symmetry. It is trivial to make it an alias for the Export panel.  I appreciate your feedback: "It will be more confusing with a dumbed down function there."

**Comment by tin2tin** [comment]
I noticed, when working in Avid today, that they use Input/output as first level in the Menu and them stream, file etc. as sub menus. This way you make the main file menu more simple if you like.
