### ISSUE TITLE
Add Scottish Gaelic (gd) locale

### ISSUE THREAD

**Issue by gunchleoc** [mltframework/shotcut#319]
Since my translation is almost finished, I looked up the QT locale for `gd`:

    QLocale::Gaelic

Getting everything to build just to add 1 line to the code takes too much time, so could you please do this for me?

Thanks :)

**Comment by ddennedy** [comment]
Thank you for your contribution. One week before end-of-month I lupdate the english .ts and git push it for Transifex to pull. This batches up the string changes into a once-a-month activity for translators. Then, day before planned release I pull down the latest translations. I check if there is a new translation that has exceeded 70% and automatically include it. This will be included in the next release.

**Comment by ddennedy** [comment]
See commit edb150f4b

**Comment by gunchleoc** [comment]
Thanks! :)
