### ISSUE TITLE
Pressing ENTER in playlist doesn't work

### ISSUE THREAD

**Issue by bjornfor** [mltframework/shotcut#321]
Reading about the keyboard shortcuts[1], it looks like pressing ENTER when a clip is selected in the playlist area should bring it to the player, similar to a double mouse click. But nothing happens when pressing ENTER.

Windows 10; Shotcut 16.10.

(It also happens on Linux, with unofficial package. The official package doesn't work on NixOS due to its non-standard directory layout -- for instance, there is no /lib64/ld-linux-x86-64.so.2.)

[1] https://www.shotcut.org/howtos/keyboard-shortcuts/ (look for "Open selected")

**Comment by ddennedy** [comment]
@metellius Can you take a look at this? It might be a regression with the recent playlist view changes.

**Comment by metellius** [comment]
```
    case Qt::Key_Enter: // Seek to current playlist item
    case Qt::Key_Return:
        if (isMultitrackValid()) {
            if (m_timelineDock->selection().size())
                m_timelineDock->seekInPoint(m_timelineDock->selection().first());
        } else if (m_playlistDock->position() >= 0) {
            if (event->modifiers() == Qt::ShiftModifier)
                seekPlaylist(m_playlistDock->position());
            else
                m_playlistDock->on_actionOpen_triggered();
        }
        break;
```

When you only have a playlist, ENTER will open the item, but when there is a timeline as well, it will instead seek to the start of the clip in the timeline.
The new views have not introduced or replaced any key handling, and I also tried with the commit right before and it had the same behavior.

@bjornfor I can't reproduce a scenario where nothing happens, please provide detailed steps starting with a blank project.

**Comment by ddennedy** [comment]
Thanks @metellius ! That is correct analysis. Also, currently, we do not have the notion of a panel focus and a way to indicate it. I have not decided whether to do that as it does make the user experience more complicated.

**Comment by bjornfor** [comment]
> When you only have a playlist, ENTER will open the item, but when there is a timeline as well, it will instead seek to the start of the clip in the timeline.

Right, that's what is happening. (I didn't know at the time of writing the issue, it was my first day of using shotcut.)

Note that the keyboard shortcut page[1] shows ENTER and double-click in the playlist as equivalent, so it's very confusing that the key changes behaviour like that (IMHO). Also, doesn't ENTER become very similar to Alt+Left now when the timeline is activated? Is it really necessary to re-purpose the ENTER key like that when Alt+Left exists?

I'd really like to be able to navigate the playlist with the keyboard.

[1] https://www.shotcut.org/howtos/keyboard-shortcuts/ (look for "Open selected").

**Comment by ddennedy** [comment]
I agree with your point. We'll change it for next release.

**Comment by metellius** [comment]
Are you aware of the Alt+Up/Alt+Down shortcuts (I see they are missing from that wiki page)? They will increment the playlist index _and_ open it in source view (AKA press enter). I find that Alt+Up/Down/Left/Right and Escape cover most timeline/playlist navigation.

**Comment by bjornfor** [comment]
@metellius: I didn't know that. Thanks!
