### ISSUE TITLE
Filters don't work on split clips

### ISSUE THREAD

**Issue by lnx64** [mltframework/shotcut#322]
Shotcut version 16.10.01
Linux Brandons-Laptop 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:11:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
I think it's an Intel HD4000, it's the GPU built into the Haswell.

For some odd reason, if I drag in a clip and immediately throw on a filter like contrast for example, I can adjust it just fine.  But if I add in a clip, and split it at the playhead with "S", no filter can be applied they have no affect on the preview image whatsoever.  The same is true for clips already added in as a whole, and then having a filter applied that worked.  If you split it, you can no longer change the filters applied to them.

**Comment by lnx64** [comment]
I would like to add a video showing the issue in case I didn't explain it well: https://www.youtube.com/watch?v=uEDcNCRygIY

I tried exporting the "split after filter" clip and yes, it looks **nothing** like the preview window, it has no filter in the exported version.

**Comment by ddennedy** [comment]
I reproduced this by closely watching the video to see that you removed the left hand clip. This seems to only be a problem if you add a filter when there is one clip on the Timeline. A workaround (for me) is to not remove the left clip or add another clip to the timeline.

**Comment by lnx64** [comment]
Thanks I will use that workaround for the time being.  It'll be easy to add a simple black frame clip to the right and no one will notice, until a proper fix is developed.

**Comment by ddennedy** [comment]
This issue no longer exists as tested in v19.01.27. It was probably fixed earlier, but I do not know exactly when.
