### ISSUE TITLE
UI Glitch: Update prompt is truncated.

### ISSUE THREAD

**Issue by lnx64** [mltframework/shotcut#327]
Sorry for the two bug reports in a row today, but I just noticed this one also after the last.

When starting Shotcut, the blue update prompt is truncated and only says "Click here to check..."..  To the average user, they may not know it should be saying updates at the end.  Not sure why it's truncated like that, the window is maximized on a 1920x1080p screen.

Ubuntu 16.04.01 64-bit, Shotcut 16.10.01..

![checkwhat](https://cloud.githubusercontent.com/assets/2136976/19571356/d8bacd4a-96cb-11e6-8c52-8b8afb913777.png)

**Comment by ddennedy** [comment]
I have seen this before as well as received reports about, but either thought I fixed it or have not found a reliable way to reproduce it to work on it. After it goes away and you choose Help > Upgrade... does it appear correctly?

**Comment by lnx64** [comment]
Yes, doing a Help / Upgrade does cause it to say the correct prompt afterwards.

**Comment by ddennedy** [comment]
This should be fixed as of v17.11 by commit 5957ded.
