### ISSUE TITLE
Fade In / Fade Out Glitch

### ISSUE THREAD

**Issue by lnx64** [mltframework/shotcut#328]
Ok after this bug report, I'm done for the day.  I'm not sure why I'm running into these issues with Shotcut 16.10.01, maybe this one you can replicate though, it happens on all of my Ubuntu 16.04.01 64-bit machines (I don't use any other distro to try).

When I import a 1-minute video, and set the fade in and fade out both to 1 frame 
(00:00:00:01), for some reason the final result is the entire video taking one whole minute to fade in.  Fade out doesn't seem to take place at all.

(The only reason I'm trying to do this is to get around that other bug with popping between clips, and I think you said to make a fade in and out 1-2 frame between clips to prevent the pop).

PS this happens when there is only one clip on the time line.  When I do this to a time line with more than one clip, this issue doesn't seem to happen.  At least those that aren't the first clip.

Sorry for the skipping video while trying to show what I mean if you can't replicate it for some reason.  My computer can't do shotcut and OBS at the same time, despite being an i7 Haswell at 3GHz with 8GB RAM.  I'll need to look into what's hogging the resources in that, it's probably OBS as it uses XSHM which is slow at best for screencapturing anything.

https://www.youtube.com/watch?v=wX8N0Sd3sLU

EDIT:  I have confirmed that it seems to happen when there's one clip, as the next clips to the right of the first do properly fade in on one frame.

**Comment by ldennedy** [comment]
Sorry for late reply. I've reproduced this on Windows, both the 16.10.01 and 16.11.02 64 bit versions.
Thank you for the report, I will start working on this.

**Comment by lnx64** [comment]
Thanks.  By the way, this bug report I made, might actually be related to this, I'm not sure: https://github.com/mltframework/shotcut/issues/333

If it is you can close the other one.  After making the second one I started to think it might be part of the same issue as this.

**Comment by ddennedy** [comment]
I found that sometimes it is possible to make Shotcut output MLT XML with a filter that is missing timing information. This is because the filter in and out are both set to 0, which makes MLT not output that information because in MLT a filter in or out value effectively means unset (applies to entire clip). It can be argued that a single frame video fade is nonsensical, and some parts of Shotcut does try to enforce a minimum 2 frame video fade. I have to think about whether to make a change deep in MLT that can be potentially regressive or change Shotcut to require minimum 2 frame fades throughout.

**Comment by lnx64** [comment]
Well I was doing the 1 frame fades because you were telling me that's how I can get rid of the pop between scenes, so that's why I had to do that.  It was to bandaid the other issue.

**Comment by ddennedy** [comment]
I know why, but I was just relaying some heresay, and obviously one frame does not work. Issue #314  has been significantly improved - if not 100% for lossy-compressed sources then probably less obnoxious than the bandaid approach.

**Comment by lnx64** [comment]
I'll check it out.  When it's released.  I'm very eager to see how it performs, even if not 100%.

**Comment by ddennedy** [comment]
@lnx64 It IS released. v16.11

**Comment by lnx64** [comment]
I'm sorry I misread it.  I got confused, I have 16.11 installed now so I will be trying it out on a project later tonight.

**Comment by lnx64** [comment]
Update from 16.11, I still seem to be exibiting some slight issues with faders, either video or audio.  Sometimes even though they are enabled on a clip, sometimes they just don't actually apply, and the fix so far as been to delete the filter, and re-add it, then it starts working.  It's very odd, but at this time I can't use faders reliably.  Cross fading though via transitions works, but faders regarding multiple tracks isn't working (like fading in another video on top of track 1).  Sometimes it just needs the filter re-added.

**Comment by lnx64** [comment]
Here's a few files to hopefully show you what is going on.  I have to MLT's, one is when in the Shotcut GUI, I have both faders for a 3rd video track to fade in and fade out, with text on it.  The GUI shows the fade out correctly, yet it does not apply.  The second MLT marked fixed, is when I simply deleted the fade out for that track, and re-added it in.

[Fadeoutfixed.txt](https://github.com/mltframework/shotcut/files/583646/Fadeoutfixed.txt)
[Nofadeoutonlayer.txt](https://github.com/mltframework/shotcut/files/583645/Nofadeoutonlayer.txt)

**Comment by lnx64** [comment]
I think I just figured out what is triggering the fade out to not always work where it's supposed to be, requiring me to re-apply the filter.  These clips are always stretched out, like a graphic.  At first it sometimes applies the filter where it was stretched from originally, not where it was stretched too, and when I re-apply it, it seems to apply to the proper end.
