### ISSUE TITLE
"3D Text (HTML)" causes freeze

### ISSUE THREAD

**Issue by meoso** [mltframework/shotcut#329]
v16.10.01

Selecting "3D Text (HTML)" causes Shotcut to freeze.  Unsure where to get logs or create verbose logging.

`Linux 4.7.0-0.bpo.1-amd64 #1 SMP Debian 4.7.5-1~bpo8+2 (2016-10-01) x86_64 GNU/Linux`

**Comment by ddennedy** [comment]
It works for me on Ubuntu 16.04 with nvidia gpu driver. It also works on my Windows 10 system and at least one macOS machine. I know it does not work on another OS X machine I have. This filter is quite complicated by using a Web view rendering WebGL to an offscreen buffer and integrated into the MLT engine. I know it does not work for some people, and at this time it is largely a matter of it may or may not work for you. So, we will leave the bug open, but at this time I do not know of a way to fix it as it goes deep into the guts of QtWebKit and OpenGL.

**Comment by meoso** [comment]
Thank you. Possibly, because i don't have a add-on GPU -- only the on-board HD4000 series CPU-Embedded graphics. `Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller`

Should I look for any Web[GL|Kit] / OpenGL / Qt packages to install -- Or is everything embedded into Shotcut? Thanks for the fantastic product!!

**Comment by ddennedy** [comment]
In my experience OpenGL interoperability is a little brittle/fragile. What do I mean by that? The app sends a bunch of OpenGL commands, which are very expressive, in the hopes that the driver+firmware+hardware does the expected thing. 

All the Qt and WebKit dependencies are included with Shotcut and system versions not used. I do not have any advice about OpenGL alternatives for your system. There is mesa+llvmpipe, which is  all CPU-based, but its really slow especially without many cores.

**Comment by lnx64** [comment]
meoso, I have an HD graphics 4600 on my laptop, and this filter works fine.  Ubuntu 16.04.01.

I'm not sure what it uses for OpenGL though.  My desktop I know but not my laptop.  It might be mesa.

**Comment by meoso** [comment]
Thank you both, I will look at my mesa drivers; otherwise, i'll stick with regular "text" for now...

**Comment by ddennedy** [comment]
I now have this problem on Windows 10 since v16.09 when Qt was upgraded to our own build of Qt 5.6.1 that includes QtWebKit.

**Comment by bill17** [comment]
I have new compupter and i have this bug too!
Computer:  Core-i7 -7700k Nvidia 1070
Fedora 25: 3D Text (HTML)" causes freeze
but Windows 10 work correctly.

**Comment by ddennedy** [comment]
HTML5 integration is discontinued. This has been announced in the past few release's notes, and in the next version now in beta it is completely removed.
