### ISSUE TITLE
Shotcut doesn't build/run correctly as described in the readme

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#334]
I'd love to contribute to shotcut but the description how to build and run it (at least from the command line under Linux) is inaccurate. The main problem I encountered was that it does not find the QML files when built using qmake and make. It looks for QML files in the source root due to QmlUtilities::qmlDir() trying to cd into a  hardcoded "share/shotcut" directory relative to the application root which does not exist when building this way.

Also, a nicer overview of which QT5 packages are required would be nice to have, but taking a close look at the warnings should also be enough.

Anyway, even though I managed to build it, I think it would be a pity if potential contributions are hindered by this. Should the qmlDir discovery be made more dynamic and/or should the building description be updated?

**Comment by ddennedy** [comment]
I hear you and agree in some ways, but we only use this issue tracker for software defects - not feature requests, shortcomings of the project, requests in general, differences of opinion with the leadership, etc. ;-) I will share more information on how to build and contribute soon.

**Comment by ddennedy** [comment]
See also our nightly build script: https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut.sh

It relies on various dependencies and our custom build of Qt 5.6.1 with QtWebKit enabled extracted to $HOME:
https://s3.amazonaws.com/misc.meltymedia/shotcut-build/qt-5.6.1-ubuntu14.04-x86_64.tar.bz2

There are some Dockerfiles in here that can help:
https://github.com/mltframework/mlt-scripts/tree/master/docker

The other things downloaded from S3 in the shotcut-build/Dockerfile are for the Windows builds.
