### ISSUE TITLE
Crashes so much-Stressful!

### ISSUE THREAD

**Issue by wolfgang7913** [mltframework/shotcut#335]
I have had a lot of problems with crashing, almost every 3 mins it crashes. I have CPU Rendering on and It happens whenever I try to add text, or any filter... seemingly random when it decides to crash. 
Are there any settings I can change to optimize it for my pc? 

Pc: 
Windows 10 - Version : 16.10.01-
Processor Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
 
Video Card NVIDIA GeForce GTX 965M
      Driver Version 21.21.13.6909
RAM 12 GB

**Comment by ddennedy** [comment]
Is Settings > GPU Processing enabled?

**Comment by wolfgang7913** [comment]
No, I have it on CPU, and I read somewhere you can change the type of rendering? (OpenGL or DirectX?) I don't have that under my settings.

**Comment by ddennedy** [comment]
There is only a "GPU Processing" setting that you can enable or disable, but you keep talking about "CPU" which can not be disabled - it is always on. When GPU Processing is enabled, then Settings  > Display Method is not available. Therefore, you seem to be using a feature marked experimental (GPU Processing) and known to be randomly crashy.

**Comment by ddennedy** [comment]
Turn off GPU Processing.
