### ISSUE TITLE
Encoding with GPU services fails with XML clip

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#337]
I am aware that using the GPU is considered experimental but I have to say that this is one of the features which really makes shotcut worth using since it gives a great performance boost.

Under certain circumstances, encoding fails with GPU-enabled services. Consider the following workflow which I like to use to cut and batch-encode a project:

- Make sure that GPU Processing is enabled.
- Make sure that thumbnail display is set to hidden in the Playlist beforehand, otherwise you will probably cause another (possibly related) crash later on. To disable thumbnails, you possibly need to have some items in the playlist first.
- Compose some timeline (e.g. open an image and pull it into a video track).
- Save this file as e.g. "timeline.mlt".
- Use "Open MLT XML As Clip..." to open "timeline.mlt" in Source tab.
- Cut your video using the Playlist (e.g. drag the whole source to the Playlist).
- Go to export dock, make sure to select "From: Playlist", do "Export File" and save e.g. as MP4.

Observed result: The export either fails or generates a video file with garbage in it. Also take a look at the export log, it should show lots of "Invalid format glsl" messages.

It might even be that the root cause is in MLT itself since running "melt" on the temporary MLT XML shows a similar result. I think the cause is that the MLT which is generated in this specific workflow has an XML producer but does not have e.g. "movit.*" services in it which seems to be the criterion for melt to enable qglsl. Therefore melt doesn't know that it needs to enable qglsl. Note that running melt with "xml:shotcut-XYZ.mlt?qglsl=1" seems to do the trick and encode the MLT correctly.

**Comment by ddennedy** [comment]
Closing because GPU Effects is unsupported without a patch/pull request. Next version 18.11 makes this more obvious.
