### ISSUE TITLE
Playlist thumbnail generation crashes with XML clip with GPU

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#338]
Even though GPU processing is currently experimental, this is a crash which could be avoided at least with a workaround (disable thumbnail generation under certain circumstances) but possibly it is also not that hard to fix if one has more insight into MLT which I'm still lacking.

This issue might be related to #337.

Repro:
- Enable GPU processing.
- Compose some timeline and save it e.g. as "timeline.mlt".
- Open "timeline.mlt" as clip using "Open MLT XML As Clip..."
- Drag the opened source clip into the Playlist and make sure thumbnails in Playlist are enabled.

Observed: shotcut crashes trying to generate the thumbnail. Backtrace points to UpdateThumbnailTask in playlistmodel.cpp which noticably uses a temporary Mlt::Producer whose service type is set manually to "xml-nogl" in case the original producer's service type starts with "xml". Is this similar to #337 where MLT needs to be told to use glsl if necessary? The "simple" workaround would be to disable thumbnail generation for the time being in that case.

**Comment by ddennedy** [comment]
Closing because GPU Effects is unsupported without a patch/pull request. Next version 18.11 makes this more obvious.
