### ISSUE TITLE
wrong frame order for exported videos

### ISSUE THREAD

**Issue by klevstul** [mltframework/shotcut#342]
# description of issue
very often, when exporting videos originating in the .mts format, to .mp4 format, i have noticed problems with the final result. seems like frames some times are outputted in the wrong order. the result being that the image jumps back back and forth. easy to see when there is movement in the image.

# examples
(sorry regarding the annoying sound. i could have muted the videos.)
1 : https://www.youtube.com/watch?v=CkaEXclePvk
2 : https://www.youtube.com/watch?v=hbXXdoh7Vvo

# export settings used
![image](https://cloud.githubusercontent.com/assets/216850/20040748/52d3714c-a45d-11e6-9202-e7cbe51122a0.png)

# shotcut version
16.11.02

# os
win 10 - 64bit
![image](https://cloud.githubusercontent.com/assets/216850/20040746/41ef3122-a45d-11e6-801a-51831c1c3041.png)

**Comment by ddennedy** [comment]
Does the problem go away if you disable "Parallel processing" in the Export panel?

I have quite a few AVCHD .mts files that do not exhibit this problem. It might be a problem specific to this particular camera. You can upload a sample file [here](https://shotcut.org/notes/support-upload/).

**Comment by klevstul** [comment]
done a few exports now, with "parallel processing" disabled. so far i have not run into the same problem, and the exported videos have been all good.

i have shot the footage with a sony a7 camera. uploaded a test file for you to mediafire.com. file name "20161031101421.MTS".

**Comment by lnx64** [comment]
I've run into this sometimes when I'm exporting video from an AVCHD camera, but it only does it when the clip changes.  I'll have to also try disabling Parallel Processing and see what it does.  When it happened to me, it only jumped for a split second as soon as the clip changed, but then worked fine throughout the rest of the clip.

https://youtu.be/gJJB4m-EvT4?t=9m39s

Watch when the clip changed, you can see the frames clearly in the wrong order at the start.  Perhaps the same issue as then?  I don't honestly know what Shotcut version I was using then when I did that video, it was up to date though.

**Comment by klevstul** [comment]
just an update. i have exported quite a few videos in the last days. with "parallel processing" disabled exporting works fine, every time. in other words, that is a valid workaround.

**Comment by ddennedy** [comment]
Closing as old, bugs have been fixed over the years, and the next version will have parallel processing disabled by default (but state is remembered if you change it).
