### ISSUE TITLE
Playhead magnetism may be too strong

### ISSUE THREAD

**Issue by raffi98** [mltframework/shotcut#343]
version  16.11.02
os windows 7 64bits

When moving a clip in the timeline, the magnetism of the playhead interferes with the magnetism of other clips' extremity.
It seems the moved clip snaps in priority to the playhead, but it also seems the playhead's magnetism is so strong that it cancels all other magnetism around. Overriding it would imply a mouse move so big the clip would be too far to be snapped to the right element.

an example with arbitrary values :
2 clips A and B, each of length 50
The play head is placed at 99
A is snapped at the beginning.
Now trying to snap B after A
But instead of snapping B's START to A's END, B's END will snap in priority to the play head.
The mouse move required to leave the magnetic influence of the play head is > 1.
So it's impossible to snap B to A, unless dropping B somewhere, moving the play head aside, and moving B back to the desired position.

Best regards

**Comment by ddennedy** [comment]
We took a look and decided not to change anything. You must move the playhead out of the way. Changing the magnetism level will make others complain that snapping strength is inconsistent.

**Comment by Kapsarovchess** [comment]
Maybe add a setting to change playhead magnetism?
