### ISSUE TITLE
mouse messes up in/out points in source viewer

### ISSUE THREAD

**Issue by raffi98** [mltframework/shotcut#345]
Hi

The mouse can set In and Out point by dragging and dropping them in the source viewer.
But when those are set, clicking in their neighborhood will slightly move them, which can cause a loss of work/time.
The behaviors in this bar are a bit confusing.

Maybe the use of combo key + mouse could conciliate all the purposes of the bar, which seem to be :
- place play head freely without moving anything else
- drag and drop I/O points
- set I/O points by single click
- assist user by placing play head right on I/O point when clicking in their neighborhood
without having one interfere with others.

Regards

**Comment by ddennedy** [comment]
Disagree; keeping it as it is.
