### ISSUE TITLE
Bass and Treble Missing

### ISSUE THREAD

**Issue by lnx64** [mltframework/shotcut#346]
Now call me crazy, but I thought we had a Bass and Treble audio filter?
![nobasstreble](https://cloud.githubusercontent.com/assets/2136976/20180835/0f35db30-a72a-11e6-892b-ae974736557c.png)

I can't seem to find it.

**Comment by ddennedy** [comment]
On Linux, you need to install the LADSPA SWH plugins. This is explained on the download page.

**Comment by lnx64** [comment]
You may want to update the download page to explain what the LADSPA SWH plugins are for, and what they help bring back.  It's explained sure, but it's very vague to the "general user".  In fact, simply Googling the package doesn't yield quite easily what it is or what it does, unless you're a programmer actually looking to research it.

Not complaining, I just would like to see the download page reflect why a package is required, rather than guesswork for the general user.  Not all video editing personnel are programmers.  ;)

**Comment by lnx64** [comment]
Ok.  Honestly didn't know what LADSPA SWH was.  I saw it was optional, but was clueless to the acronym.

Perhaps for the explanation, add (This is for extra sound filters), so we actually know.  ;)  The explanation, doesn't actually explain anything really.
