### ISSUE TITLE
open as clip doesn't stop playing at the end of the clip

### ISSUE THREAD

**Issue by raffi98** [mltframework/shotcut#347]
version 16.11.02
win 7 64

HI

When i open a clip from the playlist with "open as clip" the clip starts at the Input point, but doesn't end at the Output point.
How can one know whether the O point is well set, and when the clip ends ?

Regards

**Comment by metellius** [comment]
This works fine for me with the newest release. The "open as clip" feature was replaced with standard copy (Ctrl-c) some time in May; I recommend you upgrade and see if it still happens.

**Comment by metellius** [comment]
Sorry, was wrong about the feature being removed; I see it's still there in the playlist. Still couldn't reproduce it though, tried both in playlist mode and timeline mode. Could you point exact reproduction steps, starting from a blank project?

**Comment by metellius** [comment]
Ok, again I misunderstood, the O point is correctly set but you were talking about playback. The main developer (@ddennedy) will have to decide if this is the way forward.

**Comment by ddennedy** [comment]
This is a request that I agree with as I have thought about it myself previously when editing. Quite simply, when playing something in the Source player, stop at the out point; so, you can more easily observe the placement of the out point. Then, if you want to keep playing beyond the out point, press play again. However, it will be a little difficult to stop playback right at the out point if the playback speed is greater than normal. Probably need to issue an additional seek to out after the stop.
