### ISSUE TITLE
No longer able to change background color for Text Filter

### ISSUE THREAD

**Issue by DSkyline** [mltframework/shotcut#350]
In versions after 16.09 i can no longer set the background color for my Text filter. In version 16.09 i was able to change the background color for my Text filter (i had to select the same color 2 times but at least it changed the color eventually), and now that doesn't work any more. I can only change the color of text.

**Comment by ddennedy** [comment]
What is your OS? This is a known issue on Linux fixed for next release. d4f9e5eb5767c26844ed975fac86e9e133f7eee8

**Comment by DSkyline** [comment]
I tested it on Win 7 and Win 8. Actually just found out by accident on Win 8 that you can change the background color if you press the "Pick Screen Color" button and then select some color from the palette.

**Comment by ddennedy** [comment]
It is working, but the default level for the alpha channel is 0. Thus, even if you change the color using (without picking screen color), you have to increase the alpha channel level. 0 is transparent, 255 is opaque, and anything in between is a level of translucency proportional to the value. So, all you need to do after selecting a color, is remember to change the alpha. With that said, I am still going to make a change to help prevent falling into this trap/gotcha.
