### ISSUE TITLE
Font selection opens up in the background and doesn't apply right away.

### ISSUE THREAD

**Issue by lnx64** [mltframework/shotcut#351]
Ubuntu 16.04
Shotcut 16.11.02

When you are on the text filter properties, and click the button to change the font, the window opens up behind Shotcut, not on front.

Also, semi-related, once you have made your selection, the filter doesn't actually apply it, and I have to add a blank space in my text and back space it, to make it visible.  Minor stuff, doesn't really break anything though.

**Comment by ddennedy** [comment]
I know about this problem (first one), and I am unable to make it work due to bug in Qt for which I have not figured out a workaround.

**Comment by lnx64** [comment]
Would using KDE work better perhaps than a GTK based desktop?  Or does this effect all?

**Comment by ddennedy** [comment]
This is working since upgrading to Qt 5.9.7 many versions ago.
