### ISSUE TITLE
B-pasting (overwrite) makes selection shift to the track below

### ISSUE THREAD

**Issue by raffi98** [mltframework/shotcut#352]
version 16.11.02
win 7 64

Hi

Let's take two tracks : one audio, one video
import a short video clip to the timeline
copy it (C), and append it next to himself (Alt-Right and B)
paste it multiple time (expected hotkey : B B B...)
But doing so will paste the video clip onto the audio track, as after the paste is done selection shifts to the track below.

Regards

EDIT: actually it's a bit more complex than that. Selection is not always shifted to the track below. In case of 5 tracks for instance(4 video 1 audio), pasting on topmost, lowermost, or center tracks is ok but pasting on other tracks makes the selection shift to the topmost track.

**Comment by ddennedy** [comment]
This was fixed in 076557c8e50243e28675f1d313ed327e39a75857 for v19.04
