### ISSUE TITLE
Cannot grab video fade-in point of left-most clip on a track

### ISSUE THREAD

**Issue by lorenzosu** [mltframework/shotcut#353]
I have a clip (an image) at the beginning of a track. Hovering towards the top/left margin of the clip does not highlight the grey point/spot handle used for creating a fade-in. The right (out) one works fine. 
If one splits the clip, then all fade (in and out) handles won't work for the left side clip.

As a work-around, cutting and re-pasting the clip fade handles both work correctly.

v. 16.11.02 - Windows 7 - 64bit

**Comment by ddennedy** [comment]
I am not able to reproduce this, or it is explained poorly. Tested with v16.11 on Windows 10, macOS, and Linux. It might need specific steps or a screencast video to show.

**Comment by awesomeProgrammer** [comment]
I have the same problem, whenever I try moving the left-fade-in of the first video (starting at 00:00:00), the software have a hard crash. (have 2 saves, but it is only the old one that does it.)

I still have the save file that crashes ever time I do it, tell me what you need me to look for.

Windows 10 64bit, intel Xeon e5-2603 1.80GHz (16 gb ram)

**Comment by lorenzosu** [comment]
Hi,
As this happened again today using version 17.02.05 (on Windows 7 64bit) I took the opportunity to do a quick screengrab. Unfortunately, I cannot see a pattern for this happening. As you see in this case the problem is with the right edge of the big video clip on the left. Interestingly splitting the clip, while the new small clip on the right has fade handles which work correctly, the one on the left keeps ignoring the mouse hover.
Hope this helps.

https://youtu.be/ceoQ9i8LLK8

**Comment by ddennedy** [comment]
@lorenzosu Thank for you making the screen cast. In your case, it is not "fade-in point of left-most clip" but that is OK and probably more of the same bug.
