### ISSUE TITLE
Cannot drag file that has '?' in file name into Shotcut

### ISSUE THREAD

**Issue by rogererens** [mltframework/shotcut#354]
OS X 10.12.1; Shotcut 16.11.01 

When I use Open File and navigate to a file called 'Huh?.mp4' (without the quotes) the player starts;
When I drag that file from the Finder into Shotcut, I get an error message on the status line:
'Failed to open /Volumes/SSD2/Huh%3F.mp4'

**Comment by lnx64** [comment]
I can confirm on Linux, the same behavior is observed, though I don't see the error, it just doesn't go into the playlist.
