### ISSUE TITLE
filters - when copied, you can't past it after

### ISSUE THREAD

**Issue by awesomeProgrammer** [mltframework/shotcut#355]
am not sure if it's added yet, but the buttons are there, so i'm thinking it's a bug.

when I have made a filter that is just a 'text' type, I want to copy it by clicking it and there after go to the cut I want it on, and past it there. (the work around I have is to recreate the same text on every cut that I need it on.) 
(a better one is to add the 'text' filter to the whole video, then cut it up, because it stays on every cut. I like that 👍 )

but the button never turn on, just stays outlined.

V 16.11.02 (portable exe) , windows 10 64 bit,

**Comment by ddennedy** [comment]
It is added, and it works for me as described. To be clear, "copy it by clicking it" should be "copy the filter by clicking the copy button in the Filters panel" (not the Edit menu or Timeline toolbar). Likewise, paste requires that you use the past button in the Filters panel.

**Comment by awesomeProgrammer** [comment]
I don't know how you can get it to work, it have never worked for me, even when starting a new project.
- I have one filtre, it's selected by a blue line, then I click on 'copy the filters' button.
- then I go to an other cut, but the 'paper-clip-bord' button don't get clickable, every.

I have tried one from every group, none of them can be past into an other one (it can also not be past into it's own cut, but I'm not sure if that is an option)

 V 16.11.02 (portable exe) , windows 10 64 bit.
danish language.

**Comment by ddennedy** [comment]
OK, it works when copying filters on clip in Source player to a Timeline clip, but not from one Timeline clip to the next.
