### ISSUE TITLE
Missing frame(s) in combined video

### ISSUE THREAD

**Issue by rcmaniac25** [mltframework/shotcut#356]
OS: Windows 10 Pro x64
Shotcut 16.11.02

Background: I have an HDMI video recorder (typically for games) that records to a USB stick without the need for a computer. It automatically splits the videos into ~2GB files. I was hoping to combine all the clips into one full video using Shotcut.

Video format (according to VLC):
- V: H264 - MPEG-4 AVC (part 10) (avc1)
- V: 1920x1080
- V: Frame Rate: 29.555870
- V: Decoded format: Planar 4:2:0 YUV
- A: MPEG AAC Audio (mp4a)
- A: Channels: Stereo
- A: Sample rate: 48000 Hz

Setup: I drag and drop two or more video files that have been recorded together into the Playlist panel. I insert the first video to make the track. I drag the remaining videos onto the track in order, and move them till they snap to the prior clip.

Issue: Playing back the track, there is a momentary pause between video clips while the audio keeps playing seemlessly between the clips. Upon exporting the video the gap in video is still there. It seems like a frame or two is missing. I asked someone else to splice the two clips together in another editor (I believe they used iMovie) and the clips were seemlessly put together without any audio or video gaps.

Expectation: there is no gap between the videos.

Addendum: There is also an audio issue, but I will make a separate issue for that.

**Comment by rcmaniac25** [comment]
Forgot: I intended to compile the source and try it but the instructions for building the source code doesn't appear to be working for me. Just using Qt Creator is giving me errors I'm not understanding right now (I never really worked with Qt Creator)

**Comment by rcmaniac25** [comment]
Related to #357

**Comment by ddennedy** [comment]
What is the HDMI capture device specific make and model?
What is the file format, for example mp4 or transport stream, or its filename extension?
Can you make some short samples that demonstrate the problem and upload them to https://shotcut.org/notes/support-upload/?
Does the problem go away if you do not use the timeline? You can export a playlist using the From field at the top of the Export panel.
Does the problem go away if you disable Parallel processing in the Export panel?
The problem might be rather specific to some features in the file format or codecs that are challenging the interface between MLT and FFmpeg such that compiling the source of Shotcut alone will not help.

**Comment by rcmaniac25** [comment]
HDMI capture device is generally known as "EZCAP" (There are multiple OEMs, but they all look like this: http://www.newegg.com/Product/Product.aspx?Item=9SIA8K734F7543)
File format is mp4
...working on the other questions (currently testing with parallel processing disabled)

**Comment by rcmaniac25** [comment]
Disabling parallel processing didn't fix the gap. It's still there.

Working on the other questions.

**Comment by rcmaniac25** [comment]
Exporting from playlist didn't work.

I uploaded some sample files at the link specified. I expected it to give me a link but it didn't so the file names aren't exactly great.
t1-p1.mp4 is "test 1, part 1"
t1-p2.mp4 is "test 1, part 2"
t1.mp4 is t1-p1 + t1-p2

You can see the gap after 10 sec. Note: it flashes white... that isn't what I see when I do this. I only see the slight pause between the clips. They also didn't come out the same FPS as the original, even though I specified the same FPS. I don't know why.

Let me know if you have any questions. I can upload some files that aren't synthetically split, but they will be 2GB per clip. I don't know how much space may be available on the support site.

**Comment by ddennedy** [comment]
Your uploads were created/exported with Shotcut, which makes it hard to debug the problem reported. It would be better to provide a short sample (only one needed for now) made with the EZCAP device. Using the files provided I can see that the second-last frame of t1-p1.mp4 is repeated twice instead of showing the last frame (00:00:10:00 and 00:00:10:01 are the same). That may or may not be the same problem as what happens on the source videos.

As for FPS, they are all consistent in the samples provided, my own export made from them, and the reports from ffprobe, mediainfo, and Shotcut. That problem is masked as well by not having the original. Do you think the original files are variable framerate? If so, that is not supported. (I need to find a way to detect that and limit them.)

**Comment by ddennedy** [comment]
When I use mediainfo to get video duration and framerate and when I use ffmpeg to dump thumbnails from t1-p1.mp4, then I get 287 frames. However, `melt -consumer xml t1-p1.mp4` reports 288 frames. (melt is the command line tool for the MLT engine used by Shotcut.) However, if I use the total duration printed by mediainfo, then I get 287.7 frames which rounds up to 288 frames. This is because the audio track is slightly longer than the video track. MLT is doing the right thing here by preserving as much as data as possible. It has in the past not rounded or used the shorter track length and received bug reports about dropping data. Thus, if I edit t1-p1.mp4 in Shotcut by trimming out the last frame, then the problem goes away. This is an editor after all; you may be expected to edit and clean up cuts. It does not matter what another editor tool does. It can be argued that it is doing the wrong thing by discarding data.

You may ask why did Shotcut (MLT) export with the audio slightly longer? Well, that is another issue that will muddy the discussion around this bug, but it might be related to the fact that AAC frames (codec terminology for chunk of data) contain 1024 samples. 1024/48000 (sample rate of t1-p1.mp4) gives 21 ms, but the difference between audio and video track duration in the file is 25 ms. So, the AAC frame size is not a full explanation. I can also say as the MLT lead developer that MLT, like ffmpeg, must deal with AAC encoder delay and flush the encoder at the end of the file output. This means that it feeds the encoder with null data and as long as it gets data out it tells libavformat to add it to the file. So, there is not a lot of direct control over the process there. We have tests in MLT that work with uncompressed and discrete frame format (DV) to verify integrity of MLT operations and FFmpeg libavformat integration.

**Comment by ddennedy** [comment]
I opened t1-p1.mp4 in Shotcut, and exported it as test.mp4 using defaults. Then, I used ffmpeg command line to convert both of them to wav files. test.wav is 42 ms longer than t1-p1.wav. I opened both .wav files in Audacity one atop the other. It is clear as day that the audio signals are in synchronization and test.wav contains 42 ms of silence at the end.

Next, I ran `ffmpeg -i some.dv fftest1.mp4` followed by `mediainfo fftest1.mp4` and it shows the audio track is 32 ms longer than the video. Again, DV is a frame discrete format meaning there is no codec delays or temporal compression. Each DV frame contains one exactly video frame plus all of the audio for that video frame. This shows that H.264+AAC MP4 output from ffmpeg is adding audio data that MLT is preserving.

**Comment by rcmaniac25** [comment]
1. Since the EZCAP device is standalone and I have no control over where the files are split, the best I can do of the captured video I have is ~4GB of video. If this is fine, I will upload 2 clips.
2. I'm not sure if you mean the FPS changes mid-video (I don't know if that's a thing or not). I just checked with VLC and, while I don't know how VLC determines the framerate, most clips are constant (29.968648) but not all. In fact, I have a couple which are obviously playing at a higher FPS then what VLC states (5.698382). Is it that between clips it's not supported? Or the "can it change mid-video" is not supported?
3. But if the other editor has seamless audio and video, then what might it be cutting?
4. So what you're saying is that the audio is somehow longer then the video (with the extra audio being null data), and thus MLT is retaining the extra audio data and causing the video to be slightly longer. Giving it a delay between clips? I reiterate and expand on 3). Why is the other editor not encountering this issue? Does it just ignore the null data and end the clip when both audio is null and video is null?

This is all lead up to (along with an answer for 1) if you want original clips, but they'll total 4GB in size): what can I do then? I have only digitized a few recordings (this is me converting family VHS tapes to digital), but I have hundreds total. While another editor may give me the desired result, Shotcut offers more flexibility and the ability to assemble possibly tens of these conversions together while others are exporting or enqueued. As indicated in addendum to the original post: I'm not against doing some code work to try and fix it if it's something that needs fixing but low priority, but I don't know where to start on it right now. Though, that is if it's a bug.

**Comment by ddennedy** [comment]
1. Does the EZCAP make it difficult to stop and start to make a short sample? It looks like MediaFire will let you upload large files, but that might take a long time.
2. I do not know if VLC reports about variable frame rate, but MediaInfo and PotPlayer does.
3. and 4. These are all notes I made while investigating the files you provided, which may or may not apply to your actual files. It is not uncommon for temporally compressed files to have tracks where the lengths differ a little. Things for me to ponder about possible changes to make or not. It is difficult to balance different needs and perspectives.

**Comment by rcmaniac25** [comment]
1. EZCAP has a single button which is a toggle to start and stop recordings. If all you want is one file, I can do a short recording. If you want a recording that gets split into 2, I need to do the larger recordings.
2. I will try those programs out.

**Comment by ddennedy** [comment]
Yes, let's start with a single short recording and see what I can find.

**Comment by rcmaniac25** [comment]
Ok.

I also ran MediaInfo on some files. Do you have a preference on what format I post the results in? The only variable info I see is "OverallBitRate_Mode"

**Comment by rcmaniac25** [comment]
I uploaded issue356_Encode_1080P_21_15.mp4.

All EZCAP recordings are in the format of "Encode_<resolution>_<global counter>[_<specific recording clip index that isn't 0>].mp4

**Comment by ddennedy** [comment]
I downloaded the sample provided. MediaInfo says the frame rate is 30 fps, but ffprobe (part of FFmpeg) reports:
`Stream #0:1(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1920x1080, 102 kb/s, 0.19 fps, 30 tbr, 30 tbn, 60 tbc (default)`

Shotcut uses MLT, which uses FFmpeg libraries. It too can output some info (melt -consumer xml ...):
```
<mlt LC_NUMERIC="en_US.UTF-8" version="6.5.0" title="issue356_Encode_1080P_21_15.mp4">
  <profile description="automatic" width="1920" height="1080" progressive="1" sample_aspect_num="1" sample_aspect_den="1" display_aspect_num="1920" display_aspect_den="1080" frame_rate_num="60" frame_rate_den="2" colorspace="709"/>
...
    <property name="meta.media.1.stream.frame_rate">0.187757</property>
...
    <property name="meta.media.1.codec.frame_rate">30</property>
```

See also the duration reported by ffprobe: `Duration: 04:51:20.15` and Shotcut `04:51:20:04`, which is insane.
So, yeah, this file is written in a manner that makes FFmpeg unable to provide accurate seeking, which is needed by Shotcut even for the simple case of joining files. Feel free to report problems about detected frame rate and duration to the FFmpeg project, but you will also need to test with the latest version. I am doing that now... output of ffprobe:
```
ffprobe version N-82874-g6b517a1 Copyright (c) 2007-2016 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/home/ddennedy/opt --enable-libvorbis --enable-libtheora --enable-libx264 --enable-gpl --enable-postproc --enable-pthreads --enable-shared --enable-version3 --disable-stripping --enable-avfilter --disable-static --enable-x11grab --enable-librtmp --enable-debug --enable-libpulse --enable-libmp3lame --enable-libvpx --enable-libiec61883 --enable-libdc1394 --enable-vdpau --disable-doc --enable-libopus --enable-libx265
  libavutil      55. 43.100 / 55. 43.100
  libavcodec     57. 68.100 / 57. 68.100
  libavformat    57. 60.100 / 57. 60.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 68.100 /  6. 68.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'issue356_Encode_1080P_21_15.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: qt  
  Duration: 04:51:20.15, start: 0.000000, bitrate: 103 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 1 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:1(eng): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1920x1080, 102 kb/s, 0.19 fps, 30 tbr, 30 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
```
Shotcut 16.12 is using FFmpeg 3.0.4, which is several months older than this, but you can see FFmpeg still has a problem with it. So, I doubt upgrading Shotcut build to latest FFmpeg will make a difference either. As a result, I am not going to do anything to try to get these files working in Shotcut.

**Comment by rcmaniac25** [comment]
No problem. I'll have to look into ffmpeg then. To refer to the statement from earlier, "what is with the video that ffmpeg has issues with but other (at least iMovie) can handle just fine.

**Comment by rcmaniac25** [comment]
Hmm. Doing a ffmpeg concat (`ffmpeg.exe -f concat -i sources.txt -c copy output.mp4`) produces a seamless file. Now, that may not help for a non-linear editor such as Shotcut, but at least it produces the expected result. Though it does complain `Non-monotonous DTS in output stream 0:0; previous: 26504192, current: 26504192; changing to 26504193. This may result in incorrect timestamps in the output file.`
