### ISSUE TITLE
Audio is out-of-sync with video when clip is added to timeline and exported

### ISSUE THREAD

**Issue by rcmaniac25** [mltframework/shotcut#357]
OS: Windows 10 Pro x64
Shotcut 16.11.02

Related to #356

Background: I have an HDMI video recorder (typically for games) that records to a USB stick without the need for a computer. It automatically splits the videos into ~2GB files. I was hoping to combine all the clips into one full video using Shotcut.

Video format (according to VLC):
- V: H264 - MPEG-4 AVC (part 10) (avc1)
- V: 1920x1080
- V: Frame Rate: 29.555870
- V: Decoded format: Planar 4:2:0 YUV
- A: MPEG AAC Audio (mp4a)
- A: Channels: Stereo
- A: Sample rate: 48000 Hz

Setup: I drag and drop two or more video files that have been recorded together into the Playlist panel. I insert the first video to make the track. I drag the remaining videos onto the track in order, and move them till they snap to the prior clip.

Issue: When the clips are played in the playlist and timeline, they play properly. When I look at the audio visualization within the clip upon the timeline, the audio is offset from the video. After export, the audio is out of sync with the first clip. The instant it gets to the next clip, the audio is back in sync and remains in sync for the remainder of the clip. I have not tried more then two clips for testing the audio issue.

Expectation: audio is in-sync with video unless explicitly changed

Addendum: I intended to compile the source and try it but the instructions for building the source code doesn't appear to be working for me. Just using Qt Creator is giving me errors I'm not understanding right now (I never really worked with Qt Creator)

**Comment by lnx64** [comment]
I've had some weird issues with sync, and frame ordering when Parallel Processing is enabled.  Try exporting with Parallel Processing unchecked in the export tab, and see if that helps.

**Comment by rcmaniac25** [comment]
Trying it now

**Comment by rcmaniac25** [comment]
That didn't resolve the issue. The audio is still out-of-sync.

**Comment by ldennedy** [comment]
Hi, I don't know if it helps at all and this may not work for you, but since you've made these bug reports that have to do with out-of-sync exports, there is a forum post [here](https://forum.shotcut.org/t/audio-aligns-with-video-in-shotcut-but-goes-out-of-sync-after-export/535) that has a couple of solutions/workarounds for what sounds like a related issue. I hope this helps. At the very least it can provide a convenient link between topics on the forum and on github.

**Comment by rcmaniac25** [comment]
In #356, the theory that the video is vfr was also mentioned. I need to find a video that _is_ vfr as everyone's mentioning it and the tools that mention it, but I don't know what the tool says to indicate it's vfr. When I look at the videos referenced by this issue with MediaInfo, they are listed as having a framerate (again, not sure if it's going to say "vfr" or give a constant frame rate). I will need to read all responses other then OP and the first couple posts. But otherwise it is good to cross-link the forum and here.

**Comment by ddennedy** [comment]
MediaInfo reports something like `Frame rate mode : Variable` when it is variable frame rate. The sample provided in the related ticket #356 shows some incompatibilities with FFmpeg libs.
