### ISSUE TITLE
Shotcut shows "Nothing Selected" when opening MLT with one video in the timeline.

### ISSUE THREAD

**Issue by lnx64** [mltframework/shotcut#358]
16.12.03, 64-bit Linux.

When opening an MLT file that has one video in the timeline, I can't apply any effects to said one video in the timeline because it insists nothing is selected, despite the clip in the timeline being highlighted with the red border around it.  Only way out of this quirk is to add another blank clip, select it, and then click back to the clip I wanted to work with.  In this screenshot you can see here that a clip is highlighted but the effects tab indicates that nothing is actually highlighted.
![nothingselected](https://cloud.githubusercontent.com/assets/2136976/20934462/441a0874-bba9-11e6-9a37-8a6db5e16a81.png)

**Comment by ddennedy** [comment]
A better workaround is to select the timeline cornerstone or track head and then re-select the clp. Or, if you are not using multiple clips or tracks, do not even use the Timeline!

**Comment by lnx64** [comment]
I will ultimately be using the timeline in general to lay down audio tracks from the mayor's microphone directly, but I like to start with adding the video first, then applying filters and white balancing, etc, then I add other stuff to the timeline after I'm happy with the video.  I will try the cornerstone option.

I have a small feeling this bug however, is related to another bug I filed once, about how sometimes filters don't actually get applied to the selected clips.  (Namely, when you split a clip and see that one half of the split clip is already highlighted, but the effects don't actually get applied to either half sometimes.  (I finally am able to reproduce this if you want me to).

**Comment by tol182** [comment]
Almost a year and an issue still there.

**Comment by ddennedy** [comment]
Sorry, but my day job has been very busy and has left me with very little time to work on Shotcut. Meanwhile, there is a simple workaround for this.
