### ISSUE TITLE
Jack audio fails

### ISSUE THREAD

**Issue by mxa** [mltframework/shotcut#360]
On Linux Mint 18 Cinnamon 64bit running Shotcut 16.12.03 connecting to Jack fails.
Shotcut Message: Failed to connect to JACK. Please verify that JACK is installed and running.
It is running and it worked with the previous version of Shotcut on the same configuration.
Tried different soundcards and sampling rates too.

**Comment by ddennedy** [comment]
Upon user request/suggestion, version 16.12 now includes libjack.so.0 in the Linux app bundle. That is most likely the cause. Apparently, this is not as cross-distro safe as I expected. It looked safe according to the short list of library dependencies, but there very well could be some interface or protocol version mismatch. I can easily remove it from the next version.
From your Shotcut folder remove Shotcut.app/lib/libjack.so.0 and see if it works again.

**Comment by mxa** [comment]
I confirm this easy workaround does do the trick.
