### ISSUE TITLE
Jack connects to itself, no audio to system output.

### ISSUE THREAD

**Issue by mxa** [mltframework/shotcut#361]
I've brought this up on the g+ group some time ago, but since I still believe it's a bug, I'll post it here again. Shotcut is auto-connecting to itself in JACK. By default the audio is not going to the system out. It's different to any other app which either do no auto connection or connect to the system out.
![jack-shotcut](https://cloud.githubusercontent.com/assets/1220707/21030969/6598e71e-bda1-11e6-9154-e6294e8ea9aa.png)

@ddennedy answered back then:
This is by design. The JACK integration into MLT is designed as a filter, primarily for use with plugin hosts such as Jack-Rack. If it did not connect back itself, then it would not get back any audio for output including encoding. The JACK integration into Shotcut extends this to include transport sync but not for primary audio monitoring. If you are using JACK, Shotcut assumes you are running a system where PulseAudio or ALSA are redirected to JACK and continues to use those APIs for audio monitoring.  If that is not the case, then you need to manually connect to a system sink. Needless to say JACK is for power users who know how to operate a patchbay to route the audio for their particular needs.

However, I think it is still strange and if it's by design, it's a very strange design and contrary to how any other app is behaving.

**Comment by mxa** [comment]
Sorry, my intention for this issue was simply to help making Shotcut better by user feedback. IMHO your simple solution would reduce the versatility of Shotcut's audio capabilities.

**Comment by ddennedy** [comment]
Sometimes, if a feature is too problematic and not essential to me or the majority, then I will make it dark until possibly some time in the future it is either revisited or scrapped. That is what is going to happen here because it is not a high enough priority to address anytime soon.

**Comment by ddennedy** [comment]
I have decided to remove support for JACK in the next version.

**Comment by mxa** [comment]
Maybe someone with knowledge about jack could have a look at the code? If you would get a pull request with a fix, would you consider a merge?

**Comment by ddennedy** [comment]
No, I no longer want to maintain it.

**Comment by mxa** [comment]
Hey, thanks a million for fixing this without giving up on Jack support! Truly appreciated.
