### ISSUE TITLE
"Size and Position" filter values cannot be set correctly

### ISSUE THREAD

**Issue by CheeseDurger** [mltframework/shotcut#362]
version 16.12.03
win 10 64

Hi,
It's with the "Size and Position" filter : when the size and/or position values are changed, it impacts randomly the other values of it (see attachment).
[2016-12-11 19-01-52.zip](https://github.com/mltframework/shotcut/files/644646/2016-12-11.19-01-52.zip)

**Comment by ddennedy** [comment]
Related to #324. Some people are having a problem, but I (developer) do not. Still looking for one of my systems where this occurs to look into it.

**Comment by ldennedy** [comment]
I cannot reproduce on Win 10, newest 64 bit version as well.

**Comment by ddennedy** [comment]
As a workaround, use the Rotate filter without rotation because it offers "scale" and "offset" parameters that can be used to achieve the same result (but without a visual rectangle tool).

**Comment by ochilan** [comment]
What language and – in particular – number format settings are you using? I'm asking because I observed the following: I'm using German number format on Win 10. The usual decimal point symbol is then "," (comma). Everything works as expected. As soon as I change the decimal point symbol to e.g. "." (period) in the "Additional settings..." panel in the "Region" settings of Windows, shotcut goes crazy when I try to move the bounding rectangle of the Size and Position filter around.

**Comment by ddennedy** [comment]
@ochilan Did you start or restart Shotcut after you changed the decimal point in Additional settings?

**Comment by ochilan** [comment]
@ddennedy Restarting shotcut completely doesn't seem to be necessary, but just changing the decimal point doesn't seem to influence an _existing_ Size and Position filter either. It appears to be necessary to delete and re-add the Size and Position filter to apply the changed behavior to it. Maybe the changed setting is applied during filter initialization?

**Comment by ochilan** [comment]
@ddennedy That said, if the decimal point setting is set to the "not cool" version, restarting shotcut doesn't help to fix the issue. In my case, having the decimal point set to "," works, having it set to "." does not work, even after restarting.

**Comment by CheeseDurger** [comment]
Hi,
Actually, I already thought of that. Usually my computer is set as a mix of english language and french format (coma is used for decimal, usually). I already did some quick tests that didn't bring anything, but I should test it further.

On another note, I don't know how the size and position values are handled internally, but in the .mlt files it's :
`<property name="transition.geometry">100,00%/87,96%:200,00%x12,87%</property>`
So could there be some false string interpretations and calculations done internally ?

**Comment by mxa** [comment]
@ddennedy The described workaround is not solving the issue, changing the system locale to have points as decimal dividers is the workaround that does work though.

**Comment by IGTHORN** [comment]
Same issue here. I had to change the system locale to "English (US)" - as simply changing the decimal point to "," still resulted in some strange behaviour.
