### ISSUE TITLE
Notch effect forgets bandwidth and rolloff rate

### ISSUE THREAD

**Issue by raffi98** [mltframework/shotcut#364]
version 16.12.03 on win 7 64

Hi
these are the steps to reproduce the glitch :
- paste two video clips in the timeline, select the first one
- add a notch effect, and another one, say gain/volume (that can be disabled)
- modify the four parameters of the notch filter (frequency, bandwidth, rolloff rate and dryness)
- select the other effect OR select the other clip in the timeline
- respectively select notch effect back OR select the first clip back

expected result :
- notch filter parameters are left unchanged

actual result :
- only frequency and dryness are unchanged, bandwidth and rolloff rate values are set back to default

Kind Regards

ps :
- didn't try for a clip in the playlist
- didn't try for an audio clip

**Comment by ddennedy** [comment]
@ldennedy This problem also exists in the Bandpass filter.
