### ISSUE TITLE
Shotcut 16.12 not working on Xubuntu 16.10 (libgstapp-0.10.so.0 error)

### ISSUE THREAD

**Issue by crysman** [mltframework/shotcut#366]
This has been reported already here https://github.com/mltframework/shotcut/issues/269 but it is incorrectly marked as "RESOLVED", so I am opening it again.

I am experiencing this issue with Shotcut 16.12 on Xubuntu 16.10:

    ~/bin/Shotcut_16.12/Shotcut.app 12:19:08
    ❱ ./shotcut 
    bin/shotcut: error while loading shared libraries: libgstapp-0.10.so.0: cannot open shared object file: No such file or directory

Shotcut 16.11 is working, though...

**Comment by ddennedy** [comment]
I have not found any file in that links with libgstapp. From where did you download it? Is it possible you are trying v15.12 instead 16.12?

**Comment by ddennedy** [comment]
I just tested the binary bundle we provide in a fresh Ubuntu 16.10 virtual, and it works fine.
`find ~/Desktop/Shotcut/Shotcut.app -type f -exec ldd {} \; | grep gst` reveals no linkages to libgstapp or any gstreamer library for that mater.

**Comment by crysman** [comment]
Hmm, that is weird. Thank you for all the tests, though.
This is the file I got from the official site I believe: `shotcut-debian7-x86_64-150601.tar.bz2` which causes trouble.
If you wish, I may upload it somewhere for you to check what it is. I doubt getting it from somewhere else than `https://www.shotcut.org/download/`, because that's the place where I always go to get it...

What might had happened, though, is that I had accidentaly and incorrectly extracted some old archive instead the new one, because I remember me using back then other web browser than I normally use. If this is the case, I am very sorry for this fuss :/

**Comment by metellius** [comment]
"shotcut-debian7-x86_64-150601.tar.bz2" is the june 2015 release...

**Comment by crysman** [comment]
Yeah, I see, obviously I made a mistake and extracted some other archive due to browser issues. I am sorry.

Nevertheless, the problem is that only the archive contains the date information in its name. Once extracted, there is no convenient way to determine Shotcut version in case it's not possible to launch it. I propose including version information somewhere inside... There is already "versions" file, but it contains something else...
