### ISSUE TITLE
Can't drag and drop media files to playlist.

### ISSUE THREAD

**Issue by OskarW85** [mltframework/shotcut#369]
I just updated to version 17.01.02 (Windows x64 build).
When I try to drag and drop media files into playlist - nothing happens.
Possibly related to commit 2b3cabe135b9aba14421a38ab8e87c66d8d3ce4f?

**Comment by ddennedy** [comment]
I have not been able to reproduce it. Dragging from where? Please describe some steps.

**Comment by OskarW85** [comment]
I was drag'n'dropping PNG files (some slides) from explorer window into playlist pane in Shotcut window. In previous version Shotcut renders those slides one by one and they appear in playlist after short pause. In newest version I did the same but no slides appeared in playlist window.

**Comment by ddennedy** [comment]
I tried multiple scenarios on multiple computers on multiple OSes multiple times, and I still cannot reproduce it. I will wait a little while longer to see if someone else reports it perhaps with more information. Consider making a screencast video to show the problem.

**Comment by ddennedy** [comment]
Are you dragging from a drive other than C:? See [this forum post](https://forum.shotcut.org/t/fail-to-open-file-on-drives-other-than-c/702).
