### ISSUE TITLE
Compile FFMPEG with Support NVENC

### ISSUE THREAD

**Issue by jniltinho** [mltframework/shotcut#372]
Compile FFMPEG with Support NVENC
Export using -vcodec h264_nvenc like OBS

https://gist.github.com/jniltinho/9273dc133796062c13ca739d17862125

**Comment by ddennedy** [comment]
We only use this for tracking defects, and this is a feature request. Feel free to submit a pull request against our [build script](https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut.sh).

**Comment by ddennedy** [comment]
Also, is the NVIDIA SDK compatible with GPL3? If it requires using ffmpeg configure flag --enable-nonfree, then it is not compatible.

**Comment by ddennedy** [comment]
I verified that it is not compatible with GPL and requires --enable-nonfree. Shotcut is not simply a ffmpeg command line frontend such that you can drop in whatever build of ffmpeg that you want such as one that uses nvenc. Rather, it uses the FFmpeg library APIs, which means it must be compiled in a license-compatible manner, using a license that permits free distribution.
