### ISSUE TITLE
h264-lossless decoding problems in Windows release

### ISSUE THREAD

**Issue by viric** [mltframework/shotcut#378]
I have some h264-lossless videos (made with x264) that I wanted to manipulate in shotcut. In linux they work fine for me, but in the Windows shotcut release they have a weird horizontal noise. Like white rows over the image, somewhat transparent.

The VLC video player and ffplay for windows show the video without trouble. But shotcut on windows has the decoding problem.

Any idea what it can be? What is the code decoding the h264 in shotcut for windows?

**Comment by ddennedy** [comment]
FFmpeg v3.0.5

**Comment by viric** [comment]
ffmpeg 3.2.2 decodes it fine on Windows.

**Comment by ddennedy** [comment]
You can use the ffplay that comes with Shotcut if you want to see if it specific to that version or Shotcut.

**Comment by ddennedy** [comment]
I just used the new build 17.02 to encode a lossless H.264, 1280x720p23.98, on Windows, and playing it back looked fine.

**Comment by viric** [comment]
I can't reproduce the problem in 17.02. I guess this can be closed.

**Comment by ddennedy** [comment]
When we build, it pulls the latest/head of the FFmpeg 3.0 branch; so, it is possible that there was a fix pushed into that branch.
