### ISSUE TITLE
Shotcut crashes with transition and two video tracks

### ISSUE THREAD

**Issue by andydunkel** [mltframework/shotcut#380]
Hi,

I am using ShotCut 17.02.05 (64bit) on Windows 7 (64 bit).

My project consists of two video tracks. One with videos and one is just an image with text. The following shows the setup:

![shotcut1](https://cloud.githubusercontent.com/assets/355448/22650118/08c29fc4-ec7e-11e6-8e1e-5906b84a4870.png)

This example is working. Both preview and export are working fine. However if I move the image from the upper track over the transition, the application crashes, when playing the video. The export is also failing. Here is a screenshot of the failing scenario:

![shotcut2](https://cloud.githubusercontent.com/assets/355448/22650151/2fd16f1e-ec7e-11e6-9ef5-330b7c4fab7d.png)

![shotcut_crash](https://cloud.githubusercontent.com/assets/355448/22650152/3184ec1e-ec7e-11e6-8807-9564415e85cf.png)

Andy

**Comment by ddennedy** [comment]
Thank you for the good, detailed bug report. Unfortunately, I have not yet reproduced it. When you wrote "image with text" is the text a part of the image, or is this an image with the Shotcut Text filter applied? And for the Fade In/Out Video applied to the image on the upper track, I assume you checked "Adjust opacity"?

**Comment by andydunkel** [comment]
Thanks for the reply. Yes I am using "Adjust opacity". I tested it today with the newest version and it still happens. I put together a demo project: http://ekiwi.he-internet.de/www/temp/video.zip

Hope that helps.

Andy
