### ISSUE TITLE
No progress indication or feedback when refreshing timeline audio waveforms and thumbnails

### ISSUE THREAD

**Issue by EliasZ** [mltframework/shotcut#384]
For some reason the timeline started refreshing the audio waveforms and thumbnails. Shotcut is completely unusable at that point, probably when the timeline is of any significant size.

**Comment by ddennedy** [comment]
Waveform and thumbnail generation occurs in the background. It is not necessarily unusable depending on your machine's power. UI responsiveness does slow after generation and when the UI is updated, and there is no way around that. Progress for waveforms is already shown by incrementally growing the waveform horizontally left-to-right. Initially, it is blank and then fills in. Showing progress for thumbails would be distracting. Also, we have no way of getting progress; it goes from 0% (no thumbnail rendered yet) to 100% (thumbnail displayed). I am not exactly sure what else you expect, and you can elaborate, but I will probably close this as something I will not address.

**Comment by EliasZ** [comment]
Well, the application is unusable for me. I have no idea when this rebuilding is done. I have a project with a tenfold of clips and all of a sudden it decided the waveform, timeline and playlist thumbnails had to be refreshed - even though they worked fine before. It's taking more than 30 minutes and still going. This on a i5 (6300U, 2.5ghz) with 8 gb of ram idling except for shotcut.

I guess I will just leave it on, hoping it will finish. It doesn't seem to be making much progress. Scrolling through the timeline is nearly impossible due to the UI being unresponsive. Other than this issue, was really enjoying working with Shotcut. Any hints on when this refresh takes place so I can try to not have it happen? Even bringing the app to the foreground barely works.

**Comment by ddennedy** [comment]
The refresh takes place when the waveform/thumbnail data is missing. The data is stored in a database that has a limit to prevent growing big, and the oldest data is removed to make room for newer data. This is all automatic and not very deterministic. Really long clips can take a long time for the waveform generation. Maybe something else is wrong. Maybe Shotcut has used up most of your RAM and you are swapping. You can give up, stop Shotcut, and see what happens if you restart and reopen the project.

**Comment by EliasZ** [comment]
I have left it running for hours and after it did the audio waveforms (with some unfinished clips) it didn't do the video thumbnails. Have retried a few times and it starts over entirely and doesn't manage to finish. How to proceed? Is there some sort of cache (that database you speak of) I can wipe so it starts from scratch? I actually don't care that much for the audio waveforms, the thumbnails are much more important so I can visually see what's going on in the timeline. The track its context menu does have a hide waveforms option, but it doesn't seem to stop generating them just visually disables them.

Really bummed about this as I have a pretty decently sized project with lots of clips and redoing it probably won't be with Shotcut, if this issue cannot be dealt with.

**Comment by ddennedy** [comment]
Do you realize there is only 2 thumbnails - start and end - for each video clip?
See the [FAQ](https://www.shotcut.org/FAQ/) to figure out where the database is.

> redoing it probably won't be with Shotcut, if this issue cannot be dealt with

OK with me.

**Comment by EliasZ** [comment]
A day or so after this ocurred, I reopened the project and it regenerated everything in a minute or so without hiccups. Really strange. Glad either way I got it working again.
