### ISSUE TITLE
NDEBUG only activated for debug builds?

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#388]
In the build-shotcut.sh script it reads

```
if [ "$DEBUG_BUILD" = "1" ]; then
    export CFLAGS=-DNDEBUG
    export CXXFLAGS=-DNDEBUG
else
    export CFLAGS=
    export CXXFLAGS=
fi
```

Is there a specific reason why NDEBUG is activated for debug builds instead of release? I saw that this if was introduced in a commit having something to do with mingw, so maybe there is a reason which I don't understand.

**Comment by ddennedy** [comment]
Um, I think the logic is reversed?

**Comment by ddennedy** [comment]
This was the prior state:
https://github.com/mltframework/shotcut/commit/9346b426b4d1c997bdded52c74dbe4aa65565961

Regarding the commit message, for the Windows SDK build, I integrated DrMingw crash logging, but made this part of the change with reverse logic. Will fix this.
