### ISSUE TITLE
Slowdowns in shotcut/MLT due to leaks in movit

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#389]
Hello,

I've been tracking down bad leaks lately which ultimately lead to shotcut getting slower and slower within 10-20 minutes of playback when using GPU acceleration. I'm unsure where to post this issue since the main problem is actually in _movit_, but since a fork of movit is used in MLT I would like to have some advice where I should send my fixes to in order to get them into shotcut. Maybe we can use this issue to track the overall problem until it found its way into shotcut?

Without going into details here, the use of constructors and destructors in movit is at times inconsistent. One problem where this comes into play is the ResampleEffect of movit which is widely used when editing in shotcut. It creates plain pointers to two passes of effects which in turn reserve GL textures. But since the ResampleEffect class doesn't have a destructor at all, they never get deleted which leads to hundereds of textures to be generated per second which are not deleted either. Other classes have similar problems.

So, should I propose fixes against the fork of movit, or should I try to send them upstream? Would you pick them from there once they are available?

EDIT: Just as a heads-up, adding the destructor in ResampleEffect now crashes somewhere in the EffectsChain destructor when adding e.g. a Size and Position effect. Will investigate further. As long as I don't change anything in the effects of an existing project, the slowdowns when playing back disappeared though.

**Comment by ochilan** [comment]
Sorry for the spam -.- I didn't understand that the memory management of movit is just a little obscure through the effect chain graphs and the ResampleEffect doesn't need a destructor. In fact, this destroys the cleanup later on. The SingleResamplePassEffect destructor is called when the EffectChain is destroyed.

I think after all, it boils down the the same question I have in issue #390. Effects such as the ResampleEffect (as well as Inputs, etc.) are created all the time by MLT (e.g. every frame during playback) but are only very seldomly destroyed (e.g. if an effect is enabled/disabled in shotcut). The question I have is thus what change is necessary to clean up the movit EffectsChain (I suppose?) in time, or to reuse it in a suitable way without creating hundreds of objects each frame.

**Comment by ochilan** [comment]
My best guess is that it's special cases of movit filters that are problematic such as Resample and Blur which themselves create raw pointers to sub-filters (SingleResamplePassEffect in case of Resample) and register them in the movit effects graph. MLT tries to clean up the created effects (dispose_movit_effects in filter_movit_convert.cpp?) by calling delete on the effect instances. But in the aforementioned cases this will not delete the created sub-filters. They only seem to get deleted when movit cleans up the whole graph, deleting all nodes and attached effects.

**Comment by ddennedy** [comment]
> So, should I propose fixes against the fork of movit, or should I try to send them upstream? Would you pick them from there once they are available?

It is not my intention to maintain a fork of Movit. Late 2015, Movit started requiring a newer version of OpenGL, and that conflicted with Qt and Shotcut's requirements. In Shotcut I chose to have a QuickView for the video area to overlay controls and to share a GL context with Movit to facilitate fast, direct rendering. That put me into a corner with respect to the GL version Qt 5 uses for Quick. The reason I have a git repo instead of a specific git ref upstream was to also address some instability with nightly builds against the upstream git repo.

I have been meaning to experiment with a change where we do not take a GL texture from Movit, but make it always transfer to an RGBA buffer in CPU RAM. That would allow moving to a newer version of Movit by creating the GL context with the profile and version it needs. OTOH, that could reduce the compatibility and will certainly impact performance: GPU -> CPU -> GPU. I will try to make this experiment this weekend. What are your thoughts on this matter?

I am not in a position now with time to give the issues you raise any assistance.

**Comment by ochilan** [comment]
> It is not my intention to maintain a fork of Movit.

Understood. While I'm not sure now at all whether the trouble I'm seeing is really a fault in movit, I will direct any (real) fixes I may do at some point upstream and let you know if it's relevant for MLT or shotcut. I also experienced that the movit repos don't seem to be the most reliable when working with them the last few days.

> I have been meaning to experiment with a change where we do not take a GL texture from Movit, but make it always transfer to an RGBA buffer in CPU RAM.

Interesting – if you ask me I'm somebody who embraces using the newest stuff available, but I totally understand that this also means problems. In that regard, I don't know if compatibility will really be an issue. Even newer OpenGL versions should be available on almost all relevant machines (what OpenGL versions are we talking about btw?). The typical source of problems may be something like integrated GPUs, but first they got better as well, and second I don't know if you really want to do serious video editing on such a machine anyway (but that's only my opinion). 

Regarding the performance, it's a bit hard to tell. Certainly, GPU/CPU transfers are costly and should be avoided if possible. I'm often working with large point cloud data which may not fit in GPU memory for rendering, in such cases using CPU memory may be an option since the transfer overhead is negligible compared to the benefits (or necessities). But for a handful of small textures the overhead may hurt. (Btw, what is the special thing about the Qt version you are using, is updating not an option, or does Quick still not play nice with newer OpenGL?) But if this is the only feasible solution at the moment and it's quick to test, maybe you should give it a try. If you have a branch that you would like me to try, let me know.

At any rate, if you want to experiment in the direction of GPU-based rendering, I'm all for it. It's a good direction to go. I'm using shotcut for putting together videos with 3 to 4 H.264 video tracks and 3-4 audio tracks and using GPU mode makes a huge difference for me. In fact, I tried a very popular and widely used commercial video editor for a few days and in addition to not supporting the container format I use (MKV which I use for a good reason actually), the performance was very underwhelming (without creating proxy clips. Especially for the simple editing I do, I was glad to switch back to shotcut (together with a little hack that allows me to do simple multi camera editing – I really need to look into implementing such a feature at some point since I often need it).

> I am not in a position now with time to give the issues you raise any assistance.

No worries. If I'm really really stuck with something I will say so, otherwise I still need to learn more about how everything works together and then maybe I can also work out some fixes. For me personally I have a hack now that gives me good performance even if it's not exactly stable.

**Comment by ddennedy** [comment]
Here is the new branch that creates a distinct, non-shared OpenGL 3.2 core profile context for Movit. It asks Movit to render to a rgba buffer and uses a thread to upload this to a texture for the display code.

https://github.com/mltframework/shotcut/tree/non-shared-context-gpu

I have not done much performance comparison, but I do see reports of dropped frames while playing 1080p23.98 material. Other than that, it seems fair performance-wise - certainly not atrocious. And this was on a machine from 2008, which is definitely mediocre by today's standards.

**Comment by bmatherly** [comment]
Would this make it possible to write video scopes? I have been waiting two years to be able to enable the exiting video waveform scope and to start writing more video scopes:
https://github.com/mltframework/shotcut/blob/master/src/controllers/scopecontroller.cpp#L39

**Comment by ddennedy** [comment]
> Would this make it possible to write video scopes?

yes, it would make it much easier than trying to implement scopes in GLSL using a GL texture from a shared context.

**Comment by ochilan** [comment]
I tried the non-shared-context-gpu branch in direct comparison with the master branch. It does work, also with multiple video tracks in parallel, but I do get dropped frames much more often than with the regular branch. Not that it's unusable or anything, it's just not as smooth.

**Comment by ochilan** [comment]
Another thing I noticed with the branch is that the jumps I described in the [forum](https://forum.shotcut.org/t/hiccups-with-nvidia-378-13-gpu-mode-with-workaround/999) due to threaded optimizations in the nvidia driver doesn't happen to me with the new branch.

**Comment by ddennedy** [comment]
> the jumps I described in the forum due to threaded optimizations in the nvidia driver doesn't happen to me with the new branch

Is that because I added the workaround to the launch script in this commit: 2a7af2b66ebf02dd64c2aaba62f4eeca2192ca18

**Comment by ochilan** [comment]
At first I thought so too (and indeed, I missed the commit when I wrote the comment), but as it turns out I haven't even used the updated build script for building with the new branch at that time and as such the added line was not in there. I tried again and even when I explicitly try to enable to optimization, I cannot reproduce the jitter with the new branch. In the master branch, it still happens.

**Comment by ddennedy** [comment]
The texture leak in ResampleEffect was fixed in Shotcut's Movit branch:
https://github.com/ddennedy/movit/commit/3e8b4ebb796bcbe7e9727a2d7f2d0ba8f0170dfa

Upstream made a similar fix based on this:
https://git.sesse.net/?p=movit;a=commitdiff;h=11f2afecc201d7c4c845f5782059860ce3209a28

Also, the bug that required turning off threaded optimizations on Linux was fixed in Shotcut: 4d4dfbf4f4a572c5fdc6b164ade318b3be1e15dc

This might be enough to close this bug, or we can leave it open pending the switch to upstream.

**Comment by ochilan** [comment]
That's great news! I use this filter all the time. I will try this out soon.
I think the blur filter also uses a similar construct with hpass and vpass nodes. Is a similar change also applicable there? Haven't used this filter as much yet; this is something I only saw in the code. I don't know of other filters using a similar scheme.

**Comment by ddennedy** [comment]
When a Movit effect adds nodes it creates to a graph, the graph becomes the new owner and deletes. The ResampleEffect was special because it is what is known in MLT as an OptionalEffect, meaning it was constructed and potentially some parameters set but ultimately not included in the graph as it was not needed. This basically applies to all the Movit-based so-called normalization filters in MLT - the ones in src/modules/core/loader.ini. There are a couple of other OptionalEffects that should be checked for the same problem.

**Comment by ddennedy** [comment]
Closing because GPU Effects is unsupported without a patch/pull request. Next version 18.11 makes this more obvious.
