### ISSUE TITLE
Possible memory leak in MltInput/movit Input

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#390]
When playing back video with GPU acceleration enabled, memory requirements slowly increase. Valgrind pointed me to the inputs (YCbCrInput in this case) created in mlt_movit_input.cpp. As noted in comments in the code, the movit input is not owned by us there. However, while the MltInput gets constructed and destroyed all the time, a movit input is constructed each time useYCbCrInput is called but never seems to get deleted again. At that point I don't have enough insight yet where the movit input is supposed to get destroyed.

**Comment by ddennedy** [comment]
Closing because GPU Effects is unsupported without a patch/pull request. Next version 18.11 makes this more obvious.
