### ISSUE TITLE
There is no 'Overlay HTML' filter

### ISSUE THREAD

**Issue by music-fan** [mltframework/shotcut#392]
The 'Overlay HTML' filter is not available.
I use Arch Linux (32 bit, 'shotcut-git' package, updated now), but I tested on Manjaro Linux (64 bit, 'shotcut-git' package, updated few days ago).

**Comment by ddennedy** [comment]
It is available in the builds we provide. We do not make every build out there and can only support the ones we provide. You need to raise this issue with whoever made your build.
