### ISSUE TITLE
program cuts material

### ISSUE THREAD

**Issue by myswiat** [mltframework/shotcut#394]
Ubuntu 17.04 beta
shotcut 17.02.05

I have noticed for some time that the program cuts the material, or rather does not win all the material. This happens when you drag the video file manager program. Not always, but many times, the material that has 10 minutes in the program (for editing bar) is visible only 9:20, although in vlc material is 10 minutes.
If you need proof, so it can record to prove that the program cuts for a few seconds to several movies moved to the program.
When such an error utility program is practically zero, because there is never a certainty that this is what you are editing has been moved to the second.

**Comment by ddennedy** [comment]
This depends very much on the file format, tool used to create the file, and sometimes the specific file. Shotcut uses FFmpeg to get the length and to read the file. Shotcut v17.02.05 uses FFmpeg v3.0.6 and the next version will use v3.2.4. You need to confirm the problem by running ffprobe against it to see what length it reports. You can use the ffprobe that comes with Shotcut, or use another version to compare results. Ultimately, you may need [report the bug to the FFmpeg](https://ffmpeg.org/bugreports.html) project, but you will need to provide a sample file.
Also, you can try to override the duration in Shotcut using the Properties panel.

**Comment by myswiat** [comment]
The problem has not disappeared in the new version.
As for .flv files.
I reported the problem, because other editing programs do not have this problem.
Of course, the solution is to add the same material twice to the program, because the first program it "cuts", and only the second identifies and intepretuje properly.
