### ISSUE TITLE
Scrolling in Timeline does not work when mouse is over a clip

### ISSUE THREAD

**Issue by Schyrsivochter** [mltframework/shotcut#396]
Windows 10 x64, Shotcut 17.02.05

Scrolling the timeline either horizontally (by holding Alt) or vertically only works when the mouse is over a blank space in a track, or below the last track. When hovering over a clip or over the time scale, nothing happens.

Both timeline zoom functions are working as expected; Shift for vertical and Ctrl for horizontal zoom both work while hovering over the time scale or on a clip.

**Comment by ddennedy** [comment]
This is a known issue but out of our control with the GUI library we use. Sorry. Maybe it will work in the future on an upgrade to the library.
