### ISSUE TITLE
export gif crashing on mac

### ISSUE THREAD

**Issue by vgawen** [mltframework/shotcut#397]
Export gif crashing on mac (with Video Mode: Non-broadcast HD 720p 24fps)

OS X 10.10.5
Shotcut version: 17.03.02

Thread 8 Crashed:
0   libsystem_platform.dylib      	0x00007fff8ae90080 _platform_memmove$VARIANT$Unknown + 224
1   libavutil.55.dylib            	0x00000001143babbc av_image_copy + 156
2   libavutil.55.dylib            	0x00000001143b89e8 av_frame_copy + 216
3   libavutil.55.dylib            	0x00000001143b8348 av_frame_ref + 408
4   libavcodec.57.dylib           	0x000000011313f86d 0x112fc7000 + 1542253
5   libavcodec.57.dylib           	0x0000000113500208 avcodec_encode_video2 + 296
6   libmltavformat.dylib          	0x0000000112fb80ab consumer_thread + 10971
7   libsystem_pthread.dylib       	0x00007fff9071605a _pthread_body + 131
8   libsystem_pthread.dylib       	0x00007fff90715fd7 _pthread_start + 176
9   libsystem_pthread.dylib       	0x00007fff907133ed thread_start + 13

**Comment by ddennedy** [comment]
Did you use the "GIF Animation" preset? That works for me.
It is not enough to change only the Format field in the Export panel. There are many combinations that can be created in Export that will fail. You need to be more specific. Explain how you export to GIF.

**Comment by vgawen** [comment]
@ddennedy  I used the "GIF Animation" preset, and set the video mode to "Non-broadcast>HD 720p 24fps", shotcut crash. With the default 1080p output, it works well.

**Comment by ddennedy** [comment]
Shotcut UI crashed or the export job? I do not reproduce either, and I was using v17.03 on OS X 10.11 with the same video mode. Not sure what is wrong.

**Comment by vgawen** [comment]
@ddennedy The export job crashed, I have tried 720p + Gif Animation, 640x480 + Gif Animation, 768x576 + Gif Animation, 854x480 + Gif Animation, all crashed. But the 1920x1080 + Gif Animation works. 
Here is a screen video:
https://www.dropbox.com/s/kic5tsh38zw04km/shotcut-gif-crash.mov?dl=0

**Comment by ddennedy** [comment]
GIF Animation export is completely broken since v17.09 when upgrading FFmpeg and will be removed in v17.11
