### ISSUE TITLE
Switched from OpenGl to DirectX, and it won't start

### ISSUE THREAD

**Issue by Uzer1** [mltframework/shotcut#398]
Windows 8.1
Shotcut — latest as of 09.03.2017

Shotcut was starting fine in OpenGL mode. I switched it to DirectX in its settings. Ever since then it's become impossible to launch it. It shows me the window I had without Open GL 2.1 which I have just recently obtained to use this software. 
Once I obtained the opengl2.1 gpu and the program started fine. Now it doesn't. 

**How do I get it back to launch in OpenGL mode, not in DirectX?** 

I tried deleting its settings in appdata, registry and it still won't launch. A fresh install, both stationary and portable won't work. A Windows restart won't help. 

These pics show the error and that I have opengl 2.1. 

http://static2.keep4u.ru/2017/03/09/SKRINSOT0012017G03MES09D11C18MIN279d7.jpg
http://static1.keep4u.ru/2017/03/09/SKRINSOT0012017G03MES09D11C14MIN4148f.jpg

**Comment by ddennedy** [comment]
The latest version 17.03 starts up in DirectX mode by default unlike previous versions. This is an attempt to improve compatibility. I guess that will better for some and not for others. Get the previous version and start it. If it starts successfully, change Settings > Display Method to OpenGL. Then, try running 17.03. Does it work now?

**Comment by Uzer1** [comment]
Yes, this manipulation worked. Thank you for the idea.

**Comment by ddennedy** [comment]
I will be on the lookout for how worse it may be to default to directx, but the change was made to try to actually increase compatibility, based on problem reports from past year.
