### ISSUE TITLE
Crash adding cross-dissolve

### ISSUE THREAD

**Issue by petrica-celrau** [mltframework/shotcut#40]
This is not easy to reproduce but I was playing with multiple clips on timeline and cross-dissolve and occasionally I get a segmentation fault when dragging the handler or I can't drag the cross-dissolve handle to the left, only to the right and then I get the transition on the whole clip. I'm not sure but it seems to be related to having a gap (say I shorten the end of a clip and drag the adjacent one to close the gap I open another one further down) between clips further down from where I'm working. BTW this is the Linux version latest git built on Arch 64 bit.

**Comment by ddennedy** [comment]
Intermittent, non-reproducable crashes with no backtrace information are not actionable.
