### ISSUE TITLE
Clip Path not saved properly in mlt

### ISSUE THREAD

**Issue by spacemanspiff2007** [mltframework/shotcut#401]
Hi,

I open Shotcut 17.01.02 on Windows 7. I add one Video to the playlist. Save the file to "blabla.mlt".
Open the file -> "Error missing file".

When I check the file it seems that the '/' from linux is prefixed in the filename:
`<property name="resource">/C:/bla/bla/bla.MP4</property>`

**Comment by ddennedy** [comment]
This is already fixed in the latest version of Shotcut. That is an old version.
