### ISSUE TITLE
Hangs when cutting (S) and starting (Space) a timeline clip

### ISSUE THREAD

**Issue by cypress-speedycat** [mltframework/shotcut#402]
In the timeline, if I cut a clip (with S) and then starts to play (with Space or L), Shotcut hangs. It works better if i move the cursor between these two steps. It is reproducible on my computer. 

macOS 10.11.6 (El Capitan),  Shotcut 17.03.02

Maybe it will work better if upgrading the OS; I'm on a work computer for now.

**Comment by ddennedy** [comment]
I have not reproduced this; tried multiple times. I doubt the OS version makes a difference. I will also check it on other OSes.

**Comment by cypress-speedycat** [comment]
I have now upgraded to latest macOS Sierra. The problem still persists. It does not happen always, but pretty often. My shortcut was installed via homebrew: `brew install Caskroom/cask/shotcut`.

I tried to debug it via lldb, and found something interesting when it hung:  it is waiting for a thread to join. See [bug.txt](https://github.com/mltframework/shotcut/files/872442/bug.txt) 🐞
