### ISSUE TITLE
Crash on launch on macOS 10.12.4

### ISSUE THREAD

**Issue by AlexCarmel** [mltframework/shotcut#404]
After upgrade to MacOs 10.12.4 (16E195) shotcut start to crash both 17.02 and 17.03

/Applications/Shotcut.app/Contents/MacOS/Shotcut
[Debug  ] <static ShotcutSettings &ShotcutSettings::singleton()> language "en_CA"
[Debug  ] <static ShotcutSettings &ShotcutSettings::singleton()> deinterlacer "onefield"
[Debug  ] <static ShotcutSettings &ShotcutSettings::singleton()> external monitor ""
[Debug  ] <static ShotcutSettings &ShotcutSettings::singleton()> GPU processing false
[Debug  ] <static ShotcutSettings &ShotcutSettings::singleton()> interpolation "nearest"
[Debug  ] <static ShotcutSettings &ShotcutSettings::singleton()> video mode ""
[Debug  ] <static ShotcutSettings &ShotcutSettings::singleton()> realtime true
[Info   ] <Application::Application(int &, char **)> Starting Shotcut version 17.03.02
[Info   ] <Application::Application(int &, char **)> OS X version 14
[Info   ] <Application::Application(int &, char **)> number of logical cores = 8
[Info   ] <Application::Application(int &, char **)> locale = QLocale(English, Latin, Canada)
[Info   ] <Application::Application(int &, char **)> install dir = "/Applications/Shotcut.app/Contents/MacOS"
[Info   ] <Application::Application(int &, char **)> device pixel ratio = 2
[Debug  ] <MainWindow::changeTheme> begin
[Debug  ] <MainWindow::changeTheme> end
[Debug  ] <MainWindow::MainWindow()> begin
[Info   ] <GLTestWidget::GLTestWidget(QWidget *)> OpenGL context version 2 1
[Debug  ] <Mlt::Controller::Controller()> begin
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error opening shared object file '/Applications/Shotcut.app/Contents/MacOS/lib/ladspa/gong_1424.so': dlopen(/Applications/Shotcut.app/Contents/MacOS/lib/ladspa/gong_1424.so, 2): Symbol not found: _waveguide_nl_free  Referenced from: /Applications/Shotcut.app/Contents/MacOS/lib/ladspa/gong_1424.so  Expected in: flat namespace in /Applications/Shotcut.app/Contents/MacOS/lib/ladspa/gong_1424.so
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error opening shared object file '/Applications/Shotcut.app/Contents/MacOS/lib/ladspa/hermes_filter_1200.so': dlopen(/Applications/Shotcut.app/Contents/MacOS/lib/ladspa/hermes_filter_1200.so, 2): Symbol not found: _run_svf  Referenced from: /Applications/Shotcut.app/Contents/MacOS/lib/ladspa/hermes_filter_1200.so  Expected in: flat namespace in /Applications/Shotcut.app/Contents/MacOS/lib/ladspa/hermes_filter_1200.so
Illegal instruction: 4

**Comment by ddennedy** [comment]
Interesting, I only have 10.12.3 (16D32). When I get the next version, I will see what happens for me.

**Comment by ddennedy** [comment]
A workaround is to delete /Applications/Shotcut.app/Contents/MacOS/lib/ladspa/imp_1199.so

**Comment by ddennedy** [comment]
This is fixed in the v17.04 due in a couple of days.

**Comment by leoxxw** [comment]
I'm sorry to bother you, but I want to build the shocut on the MAC, but I haven't seen the relevant document, maybe I haven't found it. Can you tell me how to build it? Thank you very much.
