### ISSUE TITLE
Double frame at transition end

### ISSUE THREAD

**Issue by tin2tin** [mltframework/shotcut#407]
HOW TO REPRODUCE:
- Add a black clip to the time line.
- Add a text filter with a frame counter.
- Export that clip to ProRes.
- New project.
- Add the ProRes file to the time line.
- Split the clip at the middle.
- Pull the first edge of the latter clip to the left to create a dissolve.
- Place the playhead over the dissolve. 

RESULT:
Two different frames numbers are visible at the same time(mixed), but only one should be visible. Or in other words the dissolve should be invisible, because the frame numbers should be the same.

It is the outframe of the dissolve which is doubled. Ex. if I make a split cut at 01:00 and drag to the left to make a dissolve, then the frame: 01:00 is shown twice - at the last frame of the transition - and at the first frame of the following clip.

[This may be considered a minor thing, but if you use split cuts in the audiotrack to give different parts of a clip different volumes and then want to fade between the jumping volumes you're in trouble with the double frame.]

**Comment by ddennedy** [comment]
Fixed in MLT git commit https://github.com/mltframework/mlt/commit/3b049b75cd7ca8c0d75d1d4e603428066a82755f
