### ISSUE TITLE
Version 17.04.02 thinks 17.03.02 is the latest

### ISSUE THREAD

**Issue by vitorgalvao** [mltframework/shotcut#408]
Despite being on version `17.04.02`, Shotcut still thinks there’s a newer version available, pointing me to `17.03.02`.

Reporting since I’m not sure this is something that will be fixed on its own (outdated feed somewhere) or something more severe that might affect future checks for updates.

macOS `10.12.4`, Shotcut `17.04.02`.

**Comment by ddennedy** [comment]
Dude, I have not even updated the web site. All the little things for a new release are not perfectly synchronized.

**Comment by vitorgalvao** [comment]
> All the little things for a new release are not perfectly synchronized.

Agreed. But usually apps use an appcast feed and your release numbers are great for checking true later versions. They always increment in a logical order, so it’s sensible to assume your update-checking code could just see “does this version I think is newer actually have a newer version number?”.

I thought about waiting to see if it’d go away, but if something was broken with the update mechanism people could get stuck on an old version without being warned there’s a new one. Those types of errors are the ones we typically want to resolve as soon as possible, to affect the least amount of people.

Thank you for the fast reply. Have a nice day. And again thank you for all your work on Shotcut.
