### ISSUE TITLE
Toolbar doesn't allow hiding widgets

### ISSUE THREAD

**Issue by qubodup** [mltframework/shotcut#409]
1. Purge Shotcut settings.
2. Press "Export" in the toolbar. (widget appears)
3. Press "Export" in the toolbar. (nothing happens)

Expected:
Widget disappears

While useful, the toolbar seems to be broken, as it can only turn on but not remove widgets.

In addition: it doesn't show whether a widget is enabled or not through some kind of style change.

Windows 10

**Comment by ddennedy** [comment]
Currently, this is by design whether you like it or not. The toolbar buttons open a panel; the panel close button closes it. These are generally not toggles and making them appear like toggles makes them look ugly.
