### ISSUE TITLE
The snap package of shotcut 17.04 lacks the desktop-launcher

### ISSUE THREAD

**Issue by VosaXalo** [mltframework/shotcut#410]
I have tried to run the last shotcut version 17.04 on my system Ubuntu 16.04 LTS 64bit, but it doesn't start.
The error message is this one:

nicola@nicola-XPS-13-9360~> shotcut 
**/snap/shotcut/6/command-shotcut.wrapper: 2: exec: desktop-launch: not found**

If I search the app icon with the Unity Dash I can't find it anymore.
With the previous version all was fine and worked correctly.

**Comment by ddennedy** [comment]
This should be fixed now. Reopen if not.

**Comment by VosaXalo** [comment]
Perfect!
Thank you
