### ISSUE TITLE
Image clips longer than 10 minutes

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#415]
I sometimes need to add some kind of background image over the whole length of a project. The properties of an image clip don't seem to allow more than 10 minutes in length. Is there a specific reason for this limit? If not, maybe it could simply be increased.

**Comment by ddennedy** [comment]
I think the only real reason was to make it easier to see and work with the out point in the Source player. Showing out = 4 seconds (default) out of, say, 2 hours, makes it a little hard for noobs to notice the out point and to drag it as needed. However, likely these users are just as likely to not trim in the Source player and instead drop into timeline and drag right edge to adjust.

**Comment by ochilan** [comment]
Ah, I get your point. I haven't realized before that the "Duration" property of an image in the Source viewer (which is exposed to the user through the Properties dock) has a different meaning than the duration of a movie clip in the Source viewer: the duration of an image basically moves the out-point around while the duration of a movie clip makes it seem as if the whole clip actually has the duration set in the properties dock.

How about making the duration property consistent for image and video clips: An image clip could have some default duration (e.g. 10 minutes) and a shorter part of this clip could be extracted using the in- and out-points similarly to a movie clip (the out-point could be defaulted to a few seconds like before). Then the duration of the image could be modified in the properties dock if a longer image clip is desired. This would be more similar to how movie clips work in the Source viewer as well – the in- and out-points are independent of the clip duration.

By the way: The fact that the duration property sets the position of the out-point in case of an image clip has its flaws. If you open an image and set the in-point to e.g. 10 seconds and then set the duration in the properties dock to to something less than 10 seconds, the out-point will be left of the in-point (which can actually also be achieved by dragging the points). When adding the clip to the timeline the apparent length of the clip will be the difference of the in- and out-points but the duration of the clip will be the duration set in the properties in the source viewer.

By the way 2: If you want me to move some of the "issues" I added yesterday to the forum since they are rather feature requests, please let me know and I will do so, sorry about that.

**Comment by ddennedy** [comment]
This is fixed by duplicate #428
