### ISSUE TITLE
Stabilization fails to apply on some video files

### ISSUE THREAD

**Issue by einhander** [mltframework/shotcut#417]
Hi,
I use Shotcut version 17.04.02  on Debian Testing (amd64).
Stabilization filter fails to apply on most of my files.
I managed to successfully apply stabilize one video and checked .mlt file, to find difference.
Good one has 

  ```
...
<property name="vid.stab.version">v0.98 (2014-01-04)</property>
      <property name="mlt_service">vidstab</property>
      <property name="disable">0</property>
      <property name="results">VID_20161015_162357.stab</property>
    </filter>
```

Bad one has 

```
...
<property name="vid.stab.version">v0.98 (2014-01-04)</property>
      <property name="mlt_service">vidstab</property>
      <property name="shotcut:hash">d41d8cd98f00b204e9800998ecf8427e</property>
      <property name="disable">0</property>
      <property name="refresh">1</property>
    </filter>
```
If I replace these strings of bad file from good one and change stab file name I get stabilized video in Shotcut.

Still there is some Error messages in terminal:
`[Error  ] <MLT> [filter vidstab] Bad frame sequence`
But I prefer get stabilized video despite some errors.

Replace string is quite annoying, can we have skip error checking option   in Shotcut for this filter until this bug fixed?

**Comment by ddennedy** [comment]
For the bad one, you need to verify that the Analyze step completed successfully as it appears that did not run or complete successfully. Find a "bad one", click Analyze, and see if the message "Click Analyze to use this filter" goes away. If it does, save the .mlt, reload it, and let us know if it works now.

**Comment by einhander** [comment]
No, message "Click Analyze to use this filter" never goes away.

**Comment by ddennedy** [comment]
OK, thanks, that gives us a more tangible repro target. I will try several files and file types.

**Comment by einhander** [comment]
I've done some additional test. This issue occurs only if GPU processing enabled.
I removed all user settings from .config and .local and start new project with same files, stabilization filter work OK.
Then I switch to my previous project with GPU processing. Message "Click Analyze to use this filter" never goes away in that case.

**Comment by ochilan** [comment]
The stabilize filter has recently been marked incompatible with GPU mode, see commit 8de07dafef1d3685f902f6298d00bc5f746e12f6

**Comment by ddennedy** [comment]
Closing because GPU Effects is unsupported without a patch/pull request. Next version 18.11 makes this more obvious.
