### ISSUE TITLE
Jack Audio Sync Bugs

### ISSUE THREAD

**Issue by sonejostudios** [mltframework/shotcut#420]
Hello Shotcut and mlt devs!

First, thanks a million to have implemented Jack support. I'm a recording engineer and I'm making a lot of music videos. Until now it was a pain to work with music AND video on linux.. But thank to the Jack implementation in Shotcut now it's absolutely amazing. So creating complex mixes in Ardour with a lot of automations, routing, surround and this all synced with the video timeline of shotcut is now an really big step forward. Thank you!!!

Now, I was trying around with Ardour-Jack-Shotcut sync and I figured out 2 small bugs:

1) MLT is creating a stereo output and a stereo input in jack, which is fine, but it connects shotcut's output to shotcut's input automatically (which doesn't make sense), instead of connecting the output to the system playback (and input with system capture).

2) in Jack sync mode, the play button (Shotcut or Ardour or Jack, doesn't matter) sends "play" to Jack (and Shotcut), but the real timeline start occurs 4-5 sec later... so Shotcut starts but Ardour waits 4-5 sec to the start of the jack timeline. Shotcut and Ardour are synced, but with 4-5 sec delay. I don't think this is the wanted behaviour, since hitting play should start all Jack clients at the same time with the same timeline.

I hope I could help, just waiting for these bugfixes to start the new AV revolution on Linux :wink:

All the best and thanks a million for Shotcut!!

Vince

OS: LinuxMint 17, Shotcut 17.04, Ardour 5.8

original post: https://forum.shotcut.org/t/jack-audio-bugs/1409

**Comment by ddennedy** [comment]
See #361 for point 1, which is resolved for next release.
For point 2, I test primarily with Qtractor as I understand it better; however, I do not reproduce this delay with it. Some day I may get around to testing with Ardour. Just wanted to give an update.

**Comment by sonejostudios** [comment]
hey Dan!
Interesting, I will test it with Qtractor as well and again with Ardour.
It is absolutely amazing to have now a video editing software with jack sync, usable with any jack-software, and especially with ardour because it is so mighty :)  Thank you very much!
