### ISSUE TITLE
seek for 1080p's video is so slowly for mlt++ ,  

### ISSUE THREAD

**Issue by NickXhh** [mltframework/shotcut#421]
This tracker is for defects only! For feature requests, see [our patron forum](https://www.shotcut.org/discussionforum/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `OS X 10.11.5; Shotcut 16.05.01`).

**Comment by NickXhh** [comment]
set Properties ？  how ？

**Comment by ddennedy** [comment]
This is not a defect; it is an enhancement request. Also, it is unrelated to this specific resolution; rather, it depends on the format and compression. 1080p ProRes and DNxHD seek much quickly more than AVCHD. See the [FAQ](https://www.shotcut.org/FAQ/) for more information about seek speed. If you want to to try to improve it, see [producer_avformat.c](https://github.com/mltframework/mlt/blob/master/src/modules/avformat/producer_avformat.c) in MLT source code and possibly also FFmpeg/libavformat. However, be aware that seeking to the closest key frame will be faster but not accurate, and we require frame accuracy.

**Comment by NickXhh** [comment]
I know , but shotcut is better than mlt++ for 1080p's video .   so , i want to know What did you do when seeking of shutcut ,  thanks . 





At 2017-04-19 10:34:32, "Dan Dennedy" <notifications@github.com> wrote:


This is not a defect; it is an enhancement request. Also, it is unrelated to this specific resolution; rather, it depends on the format and compression. 1080p ProRes and DNxHD seek much quickly more than AVCHD. See the FAQ for more information about seek speed. If you want to to try to improve it, see producer_avformat.c in MLT source code and possibly also FFmpeg/libavformat. However, be aware that seeking to the closest key frame will be faster but not accurate, and we require frame accuracy.
