### ISSUE TITLE
Long delays when timeline duration changes

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#422]
When working with longer projects (say 1 or 2 hours), performing certain editing operations or changing the timeline zoom level causes long delays. This becomes even more pronounced at higher zoom levels of the timeline which makes it seem like the actual length of the timeline has a strong influence on the problem. However, performing other editing operations which do not change the total duration of the timeline are very quick even in large projects so it doesn't seem to be a general problem of rendering the timeline.

Example:
- Open some simple clip (even an image suffices) as Source.
- Add the clip to the timeline.
- Move it to the right to, say, 2 hours.
- One operation that now causes issues is to use the zoom slider. High zoom levels take much longer to refresh than low zoom levels for no really apparent reason.
- Another operation that shows the effect is deleting a part of the clip that changes the overall timeline duration: Zoom in onto the clip quite a bit. Split it in two pieces. Deleting the left part should work instantaneously. Deleting the right part will cause a delay which is proportional to the zoom level. This delay may seem small in this simple case but it becomes more pronounced and annoying in more complex projects.

As a workaround, I started adding a dummy track with some clip at the very end and locking it. Then I can edit things very quickly since the overall timeline length does not change due to the locked track. But this workaround is quite stupid.

I tried tracing the culprit, but I end up with calls in Qt5Gui which I can't easily debug or profile. Maybe you have better tools (and debug builds of the Qt version you're using) at hand to analyze the problem.

**Comment by ddennedy** [comment]
Closing this as old and won't fix. Since then, I have simplified the time strip/ruler, which makes it faster. Also, you can disable the audio waveforms to make it faster. Beyond those, I consider an enhancement request that requires a rewrite, and that is not planned.
