### ISSUE TITLE
32 bit vista "The procedure entry point GetActiveProcessorCount could not be located"

### ISSUE THREAD

**Issue by yardog1usa** [mltframework/shotcut#425]
32 bit vista " The procedure entry point GetActiveProcessorCount could not be located in the dynamic link library KERNEL32.dll Problem signature:   Problem Event Name:	APPCRASH   Application Name:	shotcut.exe   Application Version:	0.0.0.0   Application Timestamp:	5909c974   Fault Module Name:	KERNEL32.dll!GetActiveProcessorCount   Fault Module Version:	6.0.6001.18538   Fault Module Timestamp:	4cb733dc   Exception Code:	c0000139   Exception Offset:	00009cfc   OS Version:	6.0.6001.2.1.0.256.1   Locale ID:	1033

**Comment by ddennedy** [comment]
Shotcut does not support Vista:
https://www.shotcut.org/download/
https://www.shotcut.org/FAQ/#what-are-the-minimum-system-requirements
