### ISSUE TITLE
Failed to create OpenGL context on Linux - fatal

### ISSUE THREAD

**Issue by mxa** [mltframework/shotcut#427]
Shotcut 17.03.02-1 fails to launch with the line

```
[Fatal  ] <> Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior 2, swapInterval 1, profile  0) 
Aborted
```

On Linux Mint 18.1 Cinnamon 64bit with the NVIDIA 381.09 drivers.

**Comment by ddennedy** [comment]
I do not think there is anything we can do about that. And what is this strange -1 in the version? We do not provide support for other parties' builds.

**Comment by mxa** [comment]
Same problem with version 17.05 downloaded from the website.

**Comment by ddennedy** [comment]
And the same incompatible machine/environment. Shotcut is not intended to be compatible with all systems. The OpenGL requirement imposes that.

**Comment by mxa** [comment]
It used to work fine on this machine.

**Comment by ddennedy** [comment]
You should see if v16.08 still works as 16.09 upgraded Qt:
https://github.com/mltframework/shotcut/releases/tag/v16.08

Also, report the output of `glxinfo | grep OpenGL`

**Comment by mxa** [comment]
Tried glxgears and it failed too. Restart fixed it. Shotcut runs again. <3

**Comment by AlexisWilke** [comment]
I was just upgrading one of my computers as I installed Shotcut and when I tried to run it, it failed. One of the items in the list of packages ready for update was the CUDA library. Rebooting also resolved the issue for me.

**Comment by mxa** [comment]
There is a feature suggestion relating to this issue: https://forum.shotcut.org/t/fail-with-a-message-if-opengl-context-cant-be-found/1596

**Comment by matanster** [comment]
Same here. I'm lost on what needs to be done to solve it.
