### ISSUE TITLE
Unable to extend picture length past 10 minutes

### ISSUE THREAD

**Issue by gaining** [mltframework/shotcut#428]
Hello,

Great work on shotcut.
This could probably be because I'm not used it, but today I decided to try shotcut for the first time to edit a video which consists of 2 files. 1st file is an image jpg, 2nd file is an mp4 audio file. By default, I saw that the image lasts 4 seconds on the timeline, however, I wanted to extend its length to that of the audio file which is 57 minutes but I can only extend to 10 minutes. How can I achive this? Thanks.

System info
Linux mint 18.1 64bit
8GB RAM
Nvidia graphics

**Comment by ddennedy** [comment]
Right now you have to add the image multiple times to the track. Obviously, using the 10 min. stretched version is easier; use Timeline Copy and Paste to make that easier. I will change the max duration for the next version to 4 hours.
