### ISSUE TITLE
play 4k file [mlt_pool] out of memory on 32-bit Windows

### ISSUE THREAD

**Issue by zlmnjy** [mltframework/shotcut#429]
OS: window7  64bit
tools:
       1 qt-opensource-windows-x86-mingw492-5.5.1.exe(32bit)
       2  mingw(32bit)
shotcut version: 17.05
mlt version:6.4.1
video file : 
        1  format: h264     
        2  resolution: 3840x2160  
        3  fps: 23.976  
        4  bit rate: 50Mbps

I compile shotcut(32bit) by myself, it log [mlt_pool] out of memory when I play 4k file,  memory is 757M.

**Comment by ddennedy** [comment]
Use the 64 bit version on a 64 bit OS! 32 bit is very memory constrained. I doubt this will be addressed (not planned by me) unless you can fix it.

**Comment by ddennedy** [comment]
P.S. There was a period where I removed the 32-bit issues because I did not want to deal with the memory limitations and bug reports like this. I only brought it back because the nuisance level of people asking for 32-bit was so high.

**Comment by zlmnjy** [comment]
thank you  I will compile 64-bit

**Comment by ddennedy** [comment]
You can also download a ready binary build g github or the website.

**Comment by leoxxw** [comment]
I am currently compiling the shotcut of Windows 32-bit, but my environment is not successful. Can you help me?I seem to lack the 32-bit lib file, which results in compilation errors.Thank you very much
