### ISSUE TITLE
Apply text and watermark filter on original image

### ISSUE THREAD

**Issue by pc-zhang** [mltframework/shotcut#430]
How can I apply text and watermark filter on original image, before crop/rescale/resize? So that when changing profile, the text and watermark didn't change their location?

**Comment by ddennedy** [comment]
This is not available in Shotcut, and there is no "watermark" in Shotcut. Maybe you are asking about MLT and posted to the wrong bug tracker. In any case, this is also difficult to do in MLT and outside the normal usage scenarios. If you wish to continue down this route in MLT, then you need to become a MLT expert, and I am not available to help you. There is an undocumented MLT producer named "abnormal" that is a variation of the normally used "loader" producer. The loader producer attaches the so-called normalizing filters defined in loader.ini, but the "abnormal" producer does not.

**Comment by pc-zhang** [comment]
Thanks a lo t
