### ISSUE TITLE
Crashing with 3D Text

### ISSUE THREAD

**Issue by fullcontact68** [mltframework/shotcut#432]
[shotcut-log.txt](https://github.com/mltframework/shotcut/files/1095806/shotcut-log.txt)
New to Shotcut,

Getting crashing when trying to add 3D text.

Log attached.

Extract from the end....

[Debug  ] <autosaveTask> running 
[Error  ] <MLT> [filter webvfx] No 'resource' property found
[Error  ] <MLT> [filter webvfx] Failed to create WebVfx ServiceManager
[Error  ] <MLT> [filter webvfx] No 'resource' property found
[Error  ] <MLT> [filter webvfx] Failed to create WebVfx ServiceManager
[Error  ] <MLT> [filter webvfx] No 'resource' property found
[Error  ] <MLT> [filter webvfx] Failed to create WebVfx ServiceManager
[Error  ] <MLT> [filter webvfx] No 'resource' property found
[Error  ] <MLT> [filter webvfx] Failed to create WebVfx ServiceManager

**Comment by ddennedy** [comment]
3D Text filter is a rich feature that very much depends on your system. It works for me (on Windows 10) with Settings > Display Method = OpenGL or DirectX. By "rich" I mean that it is using WebGL in a HTML-based filter, and the web runtime for that will vary quite a bit in its ability to support WebGL based on your graphics card and driver. I see from your log that you are using Display Method > DirectX (or Automatic, which happened to select DirectX). You can change that to OpenGL to see if it makes a difference.

**Comment by ddennedy** [comment]
As an explanation for the errors you reported in your log, it is normal to see these messages after adding the filter. They appear after the filter is added but before the "resource" property is set, which is the HTML source for the filter. They are generally harmless errors.

**Comment by fullcontact68** [comment]
The problem is that the program stops responding when adding the 3D text filter. I have to ctrl+alt+delete to close it. The log file is after the freeze.

Initially I added a 3D text filter to the first item (picture) on the timeline. This is work. However, when I closed and reopened the same project later shotcut froze when trying to edit this item. I had to right click and remove the offending item. The project then worked.

However, when trying to add 3D text again the project just freezes.

(I've tried DirectX and OpenGL, both show the same result)


Any idea how to resolve this?

Cheers.

**Comment by ddennedy** [comment]
There is no way to resolve this. The only thing to do is realize this filter does not work well on your system and not use it. I can add something like "(unstable)" after the filter name if you think it will help others (except there is already "(HTML)" after the name and adding more adds clutter). One can argue to remove it, but others who are using it successfully will complain.

**Comment by fullcontact68** [comment]
I was thinking more along the lines of somehow preventing the software from freezing. If the code does get into this situation, then instead of being unresponsive, could the error be handled, the user is informed and the code exits from the filter section nicely, allowing the user to continue?

The weird thing here is that initially the 3d text did work, but for some strange reason, it's not anymore.

**Comment by ddennedy** [comment]
I agree it would be nice to be more graceful, but it is far from easy improvement to make. Hence, this bug remains open until such time I or someone can improve upon that.

**Comment by fullcontact68** [comment]
Many thanks.

If only I knew c++ and it could be debugged in VS
