### ISSUE TITLE
UI glitch for inactive menu entries on GNU/Linux Debian 9 with cinnamon; Shotcut 17.06.01

### ISSUE THREAD

**Issue by vv01f** [mltframework/shotcut#434]
These menu entries are drawn different (like font drawn twice) directly after first start of the portable program:

* Edit / *
* Settings / Project
* Settings / Player
* Settings / User Interface

Scrrenshot: 
![2017-06-30 16-18-03](https://user-images.githubusercontent.com/3034896/27739712-d5904a72-5daf-11e7-80f4-a376a36667fd.png)

**Comment by ddennedy** [comment]
This is a known issue with the dark theme with no plans to fix. If it bugs you enough; use a different theme.
