### ISSUE TITLE
Jquery animate performs perfectly in Shotcut but is ignored in the exported video

### ISSUE THREAD

**Issue by danielbanfield** [mltframework/shotcut#436]
Windows 10
Shotcut V1.13.1

I put together some nice overlays on my video that I animate in using jquery animate.
i.e.
$(document).ready(function () {
  $('div').css('margin-left', function (index, curValue) {
    return parseInt(curValue, 10) - 10 + 'px';
  });
  $('div').animate({
    opacity: 1,
    marginLeft: '+=10',
  }, 250, function () {
    // Animation complete.
  });
});

This performs **absolutely perfectly** when viewing the video within Shotcut.

As soon as I export ( using the YouTube preconfigured export settings) the resulting video doesn't show any of my transitions. In fact, since my overlays start off with opacity=0 and wait for jquery to animate in, all the overlays are stuck on zero opacity and don't show at all :(

Is there some kind of export setting I need to consider for heavy use of jquery functionality, or is this full-blown bug?

Thanks!

**Comment by metellius** [comment]
Unfortunately you cannot create html filters in this way because there is no connection between the jQuery keyframes and the webvfx renderer timestamp. Here's a page that touches on what javascript functions you need to implement to do this: https://www.shotcut.org/howtos/tumult-hype/

**Comment by danielbanfield** [comment]
Thanks for the pointer! I put together a simple equivalent using the renderRequested method

```
function Transition() {
}
Transition.prototype.render = function (progress) {
  document.getElementById("main").style.opacity =  progress * 1;
}

function onLoad() {
   var transition = new Transition();
    webvfx.renderRequested.connect(transition, Transition.prototype.render);
    webvfx.readyRender(true);
}
window.addEventListener("load", onLoad, false);
```

I was wondering if you had any guidance on a remaining issue though. I've looked through the documentation on https://www.mltframework.org/doxygen/webvfx/effects_authoring.html and can't find a way to extract an absolute time value. As in the above code the param passed to render is basically a percentage of **progress** through the current clip. So if I apply the above transition to a 5 second clip, the overlay takes 5 secs to fade in. A 2 second clip, 2 seconds to fade in.

However I want to make the animation apply to e.g. the first 500ms of any clip and have the div at full opacity for the rest of it's clip. I would need something like a value for the duration of the current clip to do the math. Does such a thing exist?

**Comment by metellius** [comment]
Here's some code from a transition I worked on way back. It uses Rekapi, a js thingy that let's me define keyframes and just plug in the timestamp from shotcut. In order to get the duration of the clip, I had to hard code the fps.
```
var rekapi = new Rekapi(document.getElementById("flag").getContext('2d'));
rekapi.renderer.width(boxwidth);
rekapi.renderer.height(boxheight);
var actor;
rekapi.addActor(actor = new Rekapi.Actor({
    render: function(ctx, state) {
        ctx.save();

        ctx.globalAlpha = state.globalAlpha;

        var flagImage = document.getElementById('flagImage');
        var titleImage = document.getElementById('titleImage');

        ctx.font = "80px Helvetica";
        var tw = ctx.measureText(mainText).width;

        ctx.save();

        var bannerOffset = tw - 1200 + 100 * state.sideOffset;

        ctx.drawImage(titleImage, bannerOffset,0);

        ctx.restore();

        ctx.shadowColor = "white";
        ctx.shadowBlur = 5;
        ctx.strokeStyle = "black";
        ctx.lineWidth = 3;
        ctx.fillStyle = "white";

        if (!mainText)
            mainText = "San Francisco test";

        ctx.save();
        ctx.globalAlpha *= state.mainTextAlpha;
        ctx.translate(1210 - tw - 20 + bannerOffset, 92);
        ctx.fillText(mainText, 0, 0);
        ctx.restore();


        ctx.restore();
    }
}));

actor
    .keyframe(500, { globalAlpha: 0 })
    .keyframe(800, { globalAlpha: 1 })

    .keyframe(800, { mainTextAlpha: 0 })
    .keyframe(1500, { mainTextAlpha: 1 })
    //.keyframe(200, { mainTextAlpha: 0 })
    //.keyframe(600, { mainTextAlpha: 1 })

    .keyframe(500, {
        sideOffset: 0
    })
    .keyframe(1100, {
        sideOffset: 1,
    }, {sideOffset: 'easeOutQuad'})

    .keyframe(3600, {
        sideOffset: 1
    })
    .keyframe(4300, {
        sideOffset: 0,
    }, {sideOffset: 'easeInQuad'})

    .keyframe(1300, {
        mainTextOffset: 1
    })
    .keyframe(1700, {
        mainTextOffset: 0
    }, {mainTextOffset: 'easeOutQuad'})
    .keyframe(1400, {
        subTextOffset: 1
    })
    .keyframe(4000, {
        globalAlpha: 1
    })
    .keyframe(4300, {
        globalAlpha: 0
    })
;

var assumedFps = 50;

function render(t) {
    var frameCount = webvfx.getNumberParameter("out") - webvfx.getNumberParameter("in");
    var duration = frameCount / assumedFps;
    mainText = webvfx.getStringParameter("text");
    if (!mainText)
        mainText = "Main title"
    subText = webvfx.getStringParameter("subText");
    if (!subText)
        subText = "Subtext"
    rekapi.update(1000 * duration * t);
}

function init() {
    webvfx.renderRequested.connect(render);
    webvfx.imageTypeMap = { "sourceImage" : webvfx.SourceImageType };
    webvfx.readyRender(true);
}

if (typeof webvfx !== 'undefined')
    window.addEventListener("load", init, false);
else {
    document.body.style.backgroundColor = "#ddd";
    rekapi.play()
}
```

**Comment by danielbanfield** [comment]
Brilliant! Thanks so much for your help. Hard coding the FPS is no biggie. Here's the code I ended up with in case it might help anyone else. It's for a small slide-in/fade-in card overlay:

```
var assumedFps = 30;
var transitionDuration = 0.5;

function Transition(el) {
   this.el = el;
   this.startMarginLeft = parseInt(el.style.marginLeft);
}

Transition.prototype.render = function (progress) {
  var frameCount = webvfx.getNumberParameter("out") - webvfx.getNumberParameter("in");
  var time = (frameCount / assumedFps) * progress;
  var transitionProgress = Math.min(time, transitionDuration) / transitionDuration;
  this.el.style.opacity =  transitionProgress * 1;
  this.el.style.marginLeft = this.startMarginLeft + (transitionProgress * 12) + 'px';
}

function onLoad() {
   var transition = new Transition(document.getElementById("main"));
    webvfx.renderRequested.connect(transition, Transition.prototype.render);
    webvfx.readyRender(true);
}
window.addEventListener("load", onLoad, false);
```
