### ISSUE TITLE
Typo in Italian translation

### ISSUE THREAD

**Issue by FirasH** [mltframework/shotcut#437]
There is a typo in the translation of a filter:
"Disssolvi video in entrata" -> "Dissolvi video in entrata"

Using Shotcut 17.06.01 for Windows.

**Comment by ddennedy** [comment]
We use transifex.com to get translations from volunteers. Is there any chance you can join the Italian team on there and make the change? If not, I can try it out relay this message.

**Comment by FirasH** [comment]
I sent a message to the current translator in transifex.

I'll close this issue as soon as the fix is confirmed.
Thanks!

**Comment by FirasH** [comment]
Fixed another small typo on transifex.
Should be fixed now!

Thanks!
