### ISSUE TITLE
Not receiving Forum Verification email

### ISSUE THREAD

**Issue by gconlon** [mltframework/shotcut#438]
Hi,
I'm trying to join your Shotcut forum, but I am not receiving the Verification emails.  They may be being discarded by spam filters somewhere, but I can't see them in my spam folder either.  Can you please tell me what mail address they would be sent from, so that they aren't being discarded by my email filters?

Cheers,
Greg Conlon

**Comment by ddennedy** [comment]
The from address is noreply@shotcut.org (forum is unable to receive e-mail).
The forum admin screen has an e-mail test function, which I just used to send e-mail to myself. I will use that with the e-mail address you registered. I do not see a general e-mail delivery problem, but I can manually activate you (I found your user account).

**Comment by gconlon** [comment]
Thanks Dan, Much appreciated.

 

Cheers,

 

Greg Conlon

0447 452 453

**Comment by ddennedy** [comment]
Let me know if you received any e-mails yet or need manual activation.

**Comment by gconlon** [comment]
Thanks Dan,

I tried setting up an account again with an alternative email address, greg@i2snap.com <mailto:greg@i2snap.com>  but I haven’t seen an email activation to this address either.  That said, it is hosted by the same provider and so is subject to the same filtering.  So maybe it would just be quicker if you can manually active me.

 

Cheers,

 

Greg Conlon

0447 452 453

**Comment by ddennedy** [comment]
I manually activated user gjc

**Comment by gconlon** [comment]
Thanks Dan

 

Cheers,

 

Greg Conlon

0447 452 453

**Comment by gconlon** [comment]
HI Dan,

I just tried and still get the following message:

"You can't log in yet. We previously sent an activation email to you at greg@theconlons.com. Please follow the instructions in that email to activate your account."



Cheers,

Greg Conlon
0447 452 453


________________________________

**Comment by gconlon** [comment]
Hi Dan,

I still can’t log in to the forum.  It still prompts me to resend the verification email.

 

Cheers,

 

Greg Conlon

0447 452 453

**Comment by ddennedy** [comment]
Now, I have activated i2snap as well. The forum software says you are active. There is nothing more I can do outside of debugging it, which I am not volunteering to do.

**Comment by gconlon** [comment]
Thanks Dan,

But that didn’t work either.

 

I also tried changing the email address on the gjc account when it asks for activation, but it then responds with, “You are not permitted to view the requested resource.” 

I’ll try to create yet another account, maybe with an outlook email address and see if that works.

 

 

Cheers,

 

Greg Conlon

0447 452 453
