### ISSUE TITLE
Filters not working (when root folder contains accented characters ?)

### ISSUE THREAD

**Issue by MrHeadwar** [mltframework/shotcut#44]
Hi,

Under certain cicumstances, I cannot get to have any filter listed. The filter placeholder in the UI is empty (shows the underlying window). I'm on Ubuntu 14.04 64 bits, and the error messages seem to tell me QtQuick is missing (which I know is not the case) : 

[Warning] <> file:///home/edouard/Téléchargements/Shotcut/Shotcut.app/share/shotcut/qml/views/filter/filterview.qml:21:1: module "QtQuick.Layouts" is not installed 

[... etc with other QtQuick modules ...]

[Warning] <static QMetaObject::Connection QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)> QObject::connect: Cannot connect (null)::currentFilterRequested(int) to FiltersDock::currentFilterRequested(int)

As you can see, I'm using a french Ubuntu, do "downloads" is named "Téléchargements", with accented "e"s. Having tried everything else (and the rest), I've tried changing the root folder : 
if I copy the whole shotcut on my desktop ("Bureau" in french, so no accents), it works without problems.

I'm not a developper, but there seems to be a string encoding issue here.

Thanks again for this excellent software !

**Comment by ddennedy** [comment]
This was fixed in the launch script as of 15.05.
