### ISSUE TITLE
List QT dependencies for end users

### ISSUE THREAD

**Issue by ageis** [mltframework/shotcut#441]
The following dynamic libraries seem to be dependencies on Debian Linux; running Shotcut without them results in either a warning or crash, yet they are not listed on the [Linux package dependencies page](https://www.shotcut.org/notes/linux-dependencies/):

* libqt5websockets5
* libqt5quicktemplates2-5
* libqt5quickcontrols2-5
* qml-module-qtquick-window2
* qml-module-qtquick2
* qml-module-qtquick-controls
* qml-module-qtquick-layouts
* qml-module-qtgraphicaleffects
* qml-module-qtquick-extras
* qml-module-qtqml-models2

I do note that some of these are present in `Shotcut.app/lib` and distributed with the program, but I'm not sure why my system wasn't able to use them or `bin/shotcut` didn't pick them up.

**Comment by bmatherly** [comment]
The reason it does not find the libraries in Shotcut.app/lib is because you are not supposed to run bin/shotcut.

See the instructions here:
https://shotcut.org/download/

Either use the Shotcut.desktop file or use the Shotcut.app/shotcut script. DO NOT RUN bin/shotcut
