### ISSUE TITLE
Image sequences are not found when loading a project

### ISSUE THREAD

**Issue by KoltesDigital** [mltframework/shotcut#442]
Hi,

I encounter a bug which prevents me to work efficiently. Repro steps:

1. make a project with an image sequence: drag & drop the first image then check Image sequence
2. save the project
3. load the project

Shotcut then tries to load imagename_%000d.png without replacing %00d by the producer's begin property. This file does not exist, of course.

In the code, in `void MltXmlChecker::checkUnlinkedFile(const QString& mlt_service)`, the file existence is checked with `if (!m_resource.info.exists())` which is incorrect for image sequences. However I don't know your code standards so I can't suggest a fix.

Thanks in advance for handling this bug

**Comment by ddennedy** [comment]
Thank for you for reporting this and good find. Since it is not simple to replace an image sequence with a new one, I am making a change to simply skip checking for a missing file if the resource property appears to be an image sequence.

**Comment by KoltesDigital** [comment]
Thanks. Can you estimate the date you'll release this version?

**Comment by ddennedy** [comment]
August 2 (see Milestone above and to the right)

**Comment by KoltesDigital** [comment]
I was not aware of this feature. Great! Thanks.
