### ISSUE TITLE
"Show in folder" doesn't highlight the file in Windows Explorer

### ISSUE THREAD

**Issue by Pikamander2** [mltframework/shotcut#444]
(Windows 7) (Shotcut 17.08.01)

In the Jobs panel, after you've exported a video to a file, you can right click the filename to bring up a context menu.

One of the options on the context menu is "Show in folder".

Clicking this option opens the containing folder in Windows Explorer, but it does not highlight the specific file.

This StackOverflow thread might be of use, even though it's about Java: https://stackoverflow.com/questions/7357969/how-to-use-java-code-to-open-windows-file-explorer-and-highlight-the-specified-f

**Comment by ddennedy** [comment]
There is no cross-platform way to do this, and it is not very important (nice to have). There is a [way using the cross-platform toolkit that Shotcut uses](https://stackoverflow.com/questions/3490336/how-to-reveal-in-finder-or-show-in-explorer-with-qt) that works on Windows and macOS only, but on Windows it assumes you are using explorer.exe, which is the clear majority but not everyone. Undecided.
