### ISSUE TITLE
Failed to create WebVfx ServiceManager

### ISSUE THREAD

**Issue by CarlFK** [mltframework/shotcut#445]
Not sure if what I am trying to do makes sense, but Error and segfault so here is a report.

```
fresh install of zesty Ubuntu 17.04
sudo apt install libsdl1.2debian git
juser@nk2:~$ /usr/local/Shotcut/Shotcut.app/shotcut --version 
Shotcut 17.08.01

git clone https://github.com/PyOhioJenkins/resources.git
juser@nk2:~$ /usr/local/Shotcut/Shotcut.app/shotcut resources/Building\ Delivery\ Pipelines\ with\ Jenkins\ Pipeline\ as\ Code\ -\ PyOhio\ 2017/index.html
```
doesn't crash, but display only shows a white box.  

Error lines and surrounding:

```
[Info   ] <MLT> WebVfx::Effects cannot be initialized on main UI thread.
[Error  ] <MLT> [producer webvfx] "plain:resources/Building Delivery Pipelines with Jenkins Pipeline as Code - PyOhio 2017/index.html" Failed to create WebVfx Effects for resource plain:resources/Building Delivery Pipelines with Jenkins Pipeline as Code - PyOhio 2017/index.html
[Error  ] <MLT> [producer webvfx] "plain:resources/Building Delivery Pipelines with Jenkins Pipeline as Code - PyOhio 2017/index.html" Failed to create WebVfx ServiceManager
```
Run again, this time using File Open and nav to index.html...
```
[Warning] <> libpng warning: iCCP: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG
[Debug  ] <AudioLoudnessScopeWidget::resetQview> begin 
[Debug  ] <FiltersDock::resetQview> begin 
[Debug  ] <MainWindow::open> "/home/juser/.local/share/Meltytech/Shotcut/__untitled__.mlt" 
[Debug  ] <MltXmlChecker::MltXmlChecker()> decimal point '.' 
[Debug  ] <MltXmlChecker::check> begin 
[Debug  ] <MltXmlChecker::check> end 
[Debug  ] <MainWindow::open> "/home/juser/resources/Building Delivery Pipelines with Jenkins Pipeline as Code - PyOhio 2017/index.html" 
[Debug  ] <MltXmlChecker::MltXmlChecker()> decimal point '.' 
[Debug  ] <MltXmlChecker::check> begin 
[Debug  ] <MltXmlChecker::check> end 
[Info   ] <MLT> WebVfx::Effects cannot be initialized on main UI thread.
[Error  ] <MLT> [producer webvfx] "plain:/home/juser/resources/Building Delivery Pipelines with Jenkins Pipeline as Code - PyOhio 2017/index.html" Failed to create WebVfx Effects for resource plain:/home/juser/resources/Building Delivery Pipelines with Jenkins Pipeline as Code - PyOhio 2017/index.html
[Error  ] <MLT> [producer webvfx] "plain:/home/juser/resources/Building Delivery Pipelines with Jenkins Pipeline as Code - PyOhio 2017/index.html" Failed to create WebVfx ServiceManager
[Info   ] <MainWindow::open> "/home/juser/resources/Building Delivery Pipelines with Jenkins Pipeline as Code - PyOhio 2017/index.html" 
Segmentation fault (core dumped)

bt coming up...

**Comment by CarlFK** [comment]
#0  0x00007ffff5f445eb in QWaitCondition::wakeAll() () from /usr/local/Shotcut/Shotcut.app/lib/libQt5Core.so.5
No symbol table info available.
#1  0x00007fffcaca7dbc in WebVfx::EffectsImpl::initializeComplete(bool) ()
   from /usr/local/Shotcut/Shotcut.app/lib/libwebvfx.so.1
No symbol table info available.
#2  0x00007ffff6140aa1 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/local/Shotcut/Shotcut.app/lib/libQt5Core.so.5
No symbol table info available.
#3  0x00007fffcacac392 in WebVfx::WebContent::contentPreLoadFinished(bool) ()
   from /usr/local/Shotcut/Shotcut.app/lib/libwebvfx.so.1
No symbol table info available.
#4  0x00007fffcacab17e in WebVfx::WebContent::webPageLoadFinished(bool) ()
   from /usr/local/Shotcut/Shotcut.app/lib/libwebvfx.so.1
No symbol table info available.
#5  0x00007ffff6140aa1 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/local/Shotcut/Shotcut.app/lib/libQt5Core.so.5
No symbol table info available.
#6  0x00007ffff7f78712 in QWebPage::loadFinished(bool) ()
   from /usr/local/Shotcut/Shotcut.app/lib/libQt5WebKitWidgets.so.5
No symbol table info available.
#7  0x00007ffff7f766f1 in ?? () from /usr/local/Shotcut/Shotcut.app/lib/libQt5WebKitWidgets.so.5
No symbol table info available.
#8  0x00007ffff2e91115 in ?? () from /usr/local/Shotcut/Shotcut.app/lib/libQt5WebKit.so.5
No symbol table info available.
#9  0x00007ffff31a7e66 in ?? () from /usr/local/Shotcut/Shotcut.app/lib/libQt5WebKit.so.5
No symbol table info available.
#10 0x00007ffff31a6e37 in ?? () from /usr/local/Shotcut/Shotcut.app/lib/libQt5WebKit.so.5
No symbol table info available.
#11 0x00007ffff3198bf7 in ?? () from /usr/local/Shotcut/Shotcut.app/lib/libQt5WebKit.so.5
No symbol table info available.
#12 0x00007ffff31d1b42 in ?? () from /usr/local/Shotcut/Shotcut.app/lib/libQt5WebKit.so.5
No symbol table info available.
#13 0x00007ffff33b7c72 in ?? () from /usr/local/Shotcut/Shotcut.app/lib/libQt5WebKit.so.5
No symbol table info available.
#14 0x00007ffff33b5902 in ?? () from /usr/local/Shotcut/Shotcut.app/lib/libQt5WebKit.so.5
No symbol table info available.
#15 0x00007ffff33b788b in ?? () from /usr/local/Shotcut/Shotcut.app/lib/libQt5WebKit.so.5
#16 0x00007ffff33b78eb in ?? () from /usr/local/Shotcut/Shotcut.app/lib/libQt5WebKit.so.5
No symbol table info available.
#17 0x00007ffff6140aa1 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/local/Shotcut/Shotcut.app/lib/libQt5Core.so.5
No symbol table info available.
#18 0x00007ffff64d6685 in ?? () from /usr/local/Shotcut/Shotcut.app/lib/libQt5Network.so.5
No symbol table info available.
#19 0x00007ffff6142056 in QObject::event(QEvent*) () from /usr/local/Shotcut/Shotcut.app/lib/libQt5Core.so.5
No symbol table info available.
#20 0x00007ffff74704ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/local/Shotcut/Shotcut.app/lib/libQt5Widgets.so.5
No symbol table info available.
#21 0x00007ffff7474b0a in QApplication::notify(QObject*, QEvent*) ()
   from /usr/local/Shotcut/Shotcut.app/lib/libQt5Widgets.so.5
No symbol table info available.
#22 0x00007ffff6116eb5 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /usr/local/Shotcut/Shotcut.app/lib/libQt5Core.so.5
No symbol table info available.
#23 0x00007ffff6118c9a in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/local/Shotcut/Shotcut.app/lib/libQt5Core.so.5
No symbol table info available.
#24 0x00007ffff6167ba3 in ?? () from /usr/local/Shotcut/Shotcut.app/lib/libQt5Core.so.5
No symbol table info available.
#25 0x00007ffff240b377 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#26 0x00007ffff240b5e0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#27 0x00007ffff240b68c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#28 0x00007ffff616722c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/local/Shotcut/Shotcut.app/lib/libQt5Core.so.5
No symbol table info available.
#29 0x00007ffff6114ecb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/local/Shotcut/Shotcut.app/lib/libQt5Core.so.5
No symbol table info available.
#30 0x00007ffff611cdb6 in QCoreApplication::exec() () from /usr/local/Shotcut/Shotcut.app/lib/libQt5Core.so.5
No symbol table info available.
#31 0x0000000000443db9 in main ()
No symbol table info available.
(gdb)

**Comment by ddennedy** [comment]
If you open a video and add the Circular Frame filter, does it work?

**Comment by CarlFK** [comment]
Yes, Circular Frame filter works.

on the Zesty box, opening index.html still segfaults

but oy my messy Xenial box,
carl@twist:~/src/tv/lca/ansible/scripts$ ~/local/Shotcut/Shotcut.app/shotcut --version 
Shotcut 17.08.01

Circular Frame filter works, exit shotcut, start shotcut
now index.html loads.

**Comment by ddennedy** [comment]
WebVfx as a producer in Shotcut is known to be a little unstable, which is how you are using it. It is more reliable as a filter. I am curious to know if on your Zesty system if the PyOhio index.html loads with the Overlay HTML filter.

**Comment by CarlFK** [comment]
Zesty, open video, add Overlay HTML filter, index.html, crash

Zesty, open video, add Overlay HTML filter, [x] Use WebVfx JavaScript extension,  index.html, no crash.  (and no render as expected)

**Comment by qubodup** [comment]
Win 10 18.03.06: If I enable [x] Use WebVfx Javascript extension and create a new HTML file and then try to play back the timeline, Shotcut freezes.
