### ISSUE TITLE
Not work with GPU processing under Windows

### ISSUE THREAD

**Issue by Tamila-2017** [mltframework/shotcut#447]
Not work with GPU processing under Windows!
There is no "GPU Processing" item in the application menu under Windows.
(but in Linux this works - see attachment).

OS: Windows 7/64
Shotcut 17.08 Version   64-bit Windows portable zip

![missing_gpu_processing](https://user-images.githubusercontent.com/27445399/29753336-1aa9c746-8b78-11e7-8593-f5d13fe1a3f1.png)

**Comment by ddennedy** [comment]
You must enable the OpenGL option under Settings > Display mode.

**Comment by Tamila-2017** [comment]
Well. But why is this parameter different in Windows and Linux? This confuses people.
Make it the equally same, please!

**Comment by Tamila-2017** [comment]
The result of testing. 
I checked the work of the GPU. This function does not work. Instead, the CPU is still running. Therefore, the speed of video processing has not increased. It remained the same, as slow as the CPU.

**Comment by ddennedy** [comment]
The GPU is not used for decoding or encoding at this time. It is currently only for select filters and transitions. This is not a defect; it is by design based on the current progress of development. Use the forum for further general discussion about what you want and expect.
