### ISSUE TITLE
Shotcut 17.08 does not work on Debian 8

### ISSUE THREAD

**Issue by Abdula-2015** [mltframework/shotcut#448]
Shotcut 17.08 does not work on Debian 8

I'm using Debian 8/64 Jessie.
I unpack the file shotcut-linux-x86_64-170801.tar.bz2 and try to start Shotcut.

Emerge first error:
`./shotcut: error while loading shared libraries: libmlt++.so.3: cannot open shared object file: No such file or directory
`

I installed the package libmlt++3. But emerge second error:
`./shotcut: error while loading shared libraries: libQt5QuickWidgets.so.5: cannot open shared object file: No such file or directory
`

I installed the package libQt5QuickWidgets. But emerge third error:
`./shotcut: error while loading shared libraries: libQt5Multimedia.so.5: cannot open shared object file: No such file or directory`

I installed the package libQt5Multimedia5. But emerge fourth error:
`./shotcut: error while loading shared libraries: libQt5WebSockets.so.5: cannot open shared object file: No such file or directory`

I installed the package libQt5WebSockets5. But emerge many  errors!!!
```./shotcut: /usr/lib/x86_64-linux-gnu/libQt5WebSockets.so.5: no version information available (required by ./shotcut)
./shotcut: /usr/lib/x86_64-linux-gnu/libQt5Multimedia.so.5: no version information available (required by ./shotcut)
./shotcut: /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5: no version information available (required by ./shotcut)
./shotcut: /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5: no version information available (required by ./shotcut)
./shotcut: /usr/lib/x86_64-linux-gnu/libQt5WebKitWidgets.so.5: no version information available (required by ./shotcut)
./shotcut: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: no version information available (required by ./shotcut)
./shotcut: /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5: no version information available (required by ./shotcut)
./shotcut: /usr/lib/x86_64-linux-gnu/libmlt++.so.3: version `MLTPP_0.9.8' not found (required by ./shotcut)
./shotcut: /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5: no version information available (required by ./shotcut)
./shotcut: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: no version information available (required by ./shotcut)
./shotcut: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: no version information available (required by ./shotcut)
./shotcut: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: no version information available (required by ./shotcut)
./shotcut: /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5: no version information available (required by ./shotcut)
./shotcut: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: no version information available (required by ./shotcut)
./shotcut: /usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5: no version information available (required by ./shotcut)
```
**shotcut-linux-x86_64-170801.tar.bz2 - this is a terrible build**. Shotcut does **not work**.

Build , please, the correct assembly. For Shotcut to run immediately, without installing additional packages. 
That Shotcut to run immediately, without installing additional packages.

**Comment by bmatherly** [comment]
Are you sure you followed the instructions on the download page?
[https://shotcut.org/download/](https://shotcut.org/download/)

> Linux Zip file Users: No install required, simply extract the archive and run it. You can drag the Shotcut folder to copy and move it wherever you want. If double-clicking the icon in your file manager does not launch Shotcut, open Shotcut.app, and try double-clicking the shotcut shell script. Do not try to run bin/shotcut directly. You may need to install the following dependencies from their distribution (the exact names may vary): SDL, libexif, and JACK. A number of the audio filters such as Band Pass, Bass & Treble, Compressor, Delay, Expander, High Pass, Limiter, Low Pass, Notch, and Reverb requires that you install the SWH LADSPA plugins package, which is commonly available in all distributions. Here is a page that lists some required packages for specific distributions.

**Comment by Abdula-2015** [comment]
No. Because it's long and tedious :) 
I want the Schotcut to start right after unpacking.

Or do make a Flatpak building, please - http://flatpak.org/

**Comment by bmatherly** [comment]
It does run immediately - you just need to run the correct script from the zip file.

Contributions are welcome - feel free to take your feature suggestions to the forum. We reserve this issue tracker for bugs.

**Comment by Abdula-2015** [comment]
> you just need to run the correct script from the zip file.

It is not right. All portable applications should run immediately, without any scripts.

shotcut-linux-x86_64-170601.tar.bz2 - I started immediately.
shotcut-linux-x86_64-170801.tar.bz2  - does not start at all, so it's poorly made.

**Comment by ddennedy** [comment]
I just double-checked the version 17.08.01 tarball, and the launcher is correct and working. Again, you must run Shotcut.app/shotcut (or use the icon if it works with your desktop file manager). Running Shotcut.app/**bin**/shotcut directly is not supported. Stubbornly repeating your agenda will go nowhere. If you are going to respond, you must clearly show what you are running.

**Comment by Abdula-2015** [comment]
1. You did not answer the question: why shotcut-linux-x86_64-170601 was started immediately, but shotcut-linux-x86_64-170801 - does not start at all ?

2. I get the opposite: if I started 170601 by using the icon, it will not even start.
But 170601 is instantly launched from the command line from the /Shotcut.app/ directory and works fine.

3. I'm using PCManFM in LXDE in Debian 9.
