### ISSUE TITLE
Big performance regression with ffmpeg > 3.0

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#449]
When building shotcut using ffmpeg 3.2 or 3.3 on Linux (for the latter I needed to remove "enable-x11grab" in the build script), video playback performance is horrible. Even with a single Full HD 60 fps h264 mkv, playback is very choppy. When building with ffmpeg 3.0, playback is smooth. Happens both with GPU and non-GPU mode.

It might be worth noting that when using ffmpeg 3.0, my CPU load is 200-300% depending on the number of tracks while with 3.2 or 3.3, it is barely above 100%. Is this possibly an issue with (missing) multithreading?

If you need an example file for which I'm experiencing the issue, please let me know.

**Comment by ochilan** [comment]
3.1 is also affected. Trying to find the revision where it started to get worse.

**Comment by ochilan** [comment]
That took some effort. I think I found the commit that is the culprit in the 3.1 branch. It should be noted that even the newest version of the 3.0 branch doesn't have the problem even though the latest commits in 3.0 are newer than said commit in the 3.1 branch.

The bad news is that it is a huge commit and it's not immediately clear to me what the problem is. It is this merge commit:

https://github.com/FFmpeg/FFmpeg/commit/6f69f7a8bf6a0d013985578df2ef42ee6b1c7994

Using the parent commit 60b7518 results in smooth playback. Checking out the commit above yields stuttering playback. I will let you know if I find out more, but if you want to take a look as well, feel free to do so.

**Comment by ochilan** [comment]
I can also reproduce the issue under Windows 10 64-bit when comparing the August and September shotcut packages. Exactly the same stuttering and reduced CPU usage in the recent version.

**Comment by ddennedy** [comment]
I noticed this too. I wonder if I updating the MLT module to the use the newer APIs will resolve it.

**Comment by ddennedy** [comment]
This is fixed in MLT git commit 0f8e807aa911c53e221e940556370ee983f49c64
I might make another 17.09 release. Haven't decided yet..
