### ISSUE TITLE
Shotcut constantly crashing when starting working - have no idea why (Win 10, Shotcut v.17.09.04)

### ISSUE THREAD

**Issue by GoranUser** [mltframework/shotcut#452]
Here is the log, if anyone know why please help ...

[Info   ] <Application::Application(int&, char**)> Starting Shotcut version 17.09.04 
[Info   ] <Application::Application(int&, char**)> Windows version 192 
[Info   ] <Application::Application(int&, char**)> number of logical cores = 4 
[Info   ] <Application::Application(int&, char**)> locale = QLocale(Slovenian, Latin, Slovenia) 
[Info   ] <Application::Application(int&, char**)> install dir = "C:/Program Files/Shotcut" 
[Info   ] <Application::Application(int&, char**)> device pixel ratio = 1 
[Debug  ] <MainWindow::changeTheme> begin 
[Debug  ] <MainWindow::changeTheme> end 
[Debug  ] <MainWindow::MainWindow()> begin 
[Debug  ] <Mlt::Controller::Controller()> begin 
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error opening shared object file 'C:\Program Files\Shotcut\lib\ladspa/AUTHORS': "C:\Program Files\Shotcut\lib\ladspa\AUTHORS": The specified module could not be found.
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error opening shared object file 'C:\Program Files\Shotcut\lib\ladspa/COPYING': "C:\Program Files\Shotcut\lib\ladspa\COPYING": The specified module could not be found.
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error finding ladspa_descriptor symbol in object file 'C:\Program Files\Shotcut\lib\ladspa/libfftw3f-3.dll': "ladspa_descriptor": The specified procedure could not be found.
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error opening shared object file 'C:\Program Files\Shotcut\lib\ladspa/readme.txt': "C:\Program Files\Shotcut\lib\ladspa\readme.txt": 
[Debug  ] <Mlt::Controller::Controller()> end 
[Debug  ] <Mlt::GLWidget::GLWidget(QObject*)> begin 
[Debug  ] <Mlt::GLWidget::GLWidget(QObject*)> end 
[Debug  ] <MainWindow::setupSettingsMenu> begin 
[Warning] <MLT> [ 0x6c46900] The DeckLink drivers not installed.
[Debug  ] <MainWindow::setupSettingsMenu> end 
[Debug  ] <MainWindow::readPlayerSettings> begin 
[Debug  ] <MainWindow::readPlayerSettings> end 
[Debug  ] <MainWindow::configureVideoWidget> begin 
[Debug  ] <MainWindow::setProfile> "" 
[Debug  ] <Mlt::Controller::setProfile> setting to profile "Automatic" 
[Debug  ] <MainWindow::configureVideoWidget> end 
[Debug  ] <ScopeController::ScopeController(QMainWindow*, QMenu*)> begin 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> begin true 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> end 
[Debug  ] <AudioLoudnessScopeWidget::AudioLoudnessScopeWidget()> begin 
[Debug  ] <AudioLoudnessScopeWidget::AudioLoudnessScopeWidget()> end 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> begin 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> end 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> begin true 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> end 
[Debug  ] <AudioPeakMeterScopeWidget::AudioPeakMeterScopeWidget()> begin 
[Debug  ] <AudioPeakMeterScopeWidget::AudioPeakMeterScopeWidget()> end 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> begin 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> end 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> begin true 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> end 
[Debug  ] <AudioSpectrumScopeWidget::AudioSpectrumScopeWidget()> begin 
[Debug  ] <AudioSpectrumScopeWidget::AudioSpectrumScopeWidget()> end 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> begin 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> end 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> begin true 
[Debug  ] <ScopeWidget::ScopeWidget(const QString&)> end 
[Debug  ] <AudioWaveformScopeWidget::AudioWaveformScopeWidget()> begin 
[Debug  ] <AudioWaveformScopeWidget::AudioWaveformScopeWidget()> end 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> begin 
[Debug  ] <ScopeDock::ScopeDock(ScopeController*, ScopeWidget*)> end 
[Debug  ] <ScopeController::ScopeController(QMainWindow*, QMenu*)> end 
[Debug  ] <RecentDock::RecentDock(QWidget*)> begin 
[Debug  ] <RecentDock::RecentDock(QWidget*)> end 
[Debug  ] <PlaylistDock::PlaylistDock(QWidget*)> begin 
[Debug  ] <PlaylistDock::PlaylistDock(QWidget*)> end 
[Debug  ] <TimelineDock::TimelineDock(QWidget*)> begin 
[Debug  ] <TimelineDock::TimelineDock(QWidget*)> end 
[Debug  ] <FiltersDock::FiltersDock(MetadataModel*, AttachedFiltersModel*, QWidget*)> begin 
[Debug  ] <FiltersDock::FiltersDock(MetadataModel*, AttachedFiltersModel*, QWidget*)> end 
[Debug  ] <EncodeDock::EncodeDock(QWidget*)> begin 
[Debug  ] <EncodeDock::EncodeDock(QWidget*)> end 
[Debug  ] <JobsDock::JobsDock(QWidget*)> begin 
[Debug  ] <JobsDock::JobsDock(QWidget*)> end 
[Debug  ] <MainWindow::readWindowSettings> begin 
[Debug  ] <MainWindow::readWindowSettings> end 
[Debug  ] <LeapNetworkListener::start> begin 
[Debug  ] <MainWindow::MainWindow()> end 
[Debug  ] <Database::run> Database version is 1 
[Debug  ] <FiltersDock::resetQview> begin 
[Debug  ] <Mlt::GLWidget::initializeGL> begin 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL vendor "NVIDIA Corporation" 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL renderer "GeForce GT 730/PCIe/SSE2" 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL threaded? true 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL ES? false 
[Debug  ] <Mlt::GLWidget::initializeGL> end 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "alpha_adjust" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Alpha Channel: Adjust" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "alpha_view" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Alpha Channel: View" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_balance" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Balance" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_bandpass" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Band Pass" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_basstreble" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Bass & Treble" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_channelcopy" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Copy Channel" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_compressor" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Compressor" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_delay" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Delay" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_expander" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Expander" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_fadein" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade In Audio" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_fadeout" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade Out Audio" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_gain" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Gain / Volume" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_highpass" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "High Pass" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_limiter" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Limiter" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_lowpass" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Low Pass" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_mono" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Downmix" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_mute" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Mute" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_normalize_1p" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Normalize: One Pass" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_normalize_2p" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Normalize: Two Pass" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_notch" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Notch" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_pan" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Pan" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_reverb" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Reverb" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_swapchannels" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Swap Channels" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "bluescreen0r" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Chroma Key: Simple" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "blur" "meta_boxblur.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Blur" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "blur" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Blur" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "brightness" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Brightness" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "brightness" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Brightness" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "color" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Color Grading" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "color" "meta_frei0r_coloradj.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Color Grading" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "color" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Color Grading" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "contrast" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Contrast" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "contrast" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Contrast" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "crop" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Crop" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "crop" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Crop" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "dust" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Old Film: Dust" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "dynamictext" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Text" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "fadein_brightness" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade In Video" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "fadein_movit" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade In Video" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "fadeout_brightness" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade Out Video" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "fadeout_movit" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade Out Video" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "glow" "meta_frei0r.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Glow" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "glow" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Glow" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "grain" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Old Film: Grain" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "invert" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Invert Colors" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "keyspillm0pup" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Key Spill: Advanced" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "lenscorrection" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Lens Correction" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "lines" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Old Film: Scratches" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "lut3d" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "LUT (3D)" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "mirror" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Mirror" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "mirror" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Mirror" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "movit_diffusion" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Diffusion" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "oldfilm" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Old Film: Projector" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "opacity" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Opacity" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "opacity" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Opacity" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "rotate" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Rotate" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "saturation" "meta_frei0r.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Saturation" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "saturation" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Saturation" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "select0r" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Chroma Key: Advanced" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "sepia" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Sepia Tone" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "sharpen" "meta_frei0r.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Sharpen" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "sharpen" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Sharpen" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "size_position" "meta_affine.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Size and Position" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "size_position" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Size and Position" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "smartblur" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Reduce Noise" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "spillsuppress" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Key Spill: Simple" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "stabilize" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Stabilize" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "tcolor" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Old Film: Technocolor" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "vignette" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Vignette" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "vignette" "meta_oldfilm.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Vignette" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "wave" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Wave" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "webvfx" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Overlay HTML" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "webvfx_circular_frame" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Circular Frame (HTML)" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "webvfx_ruttetraizer" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Rutt-Etra-Izer (HTML)" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "webvfx_threejs_text" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "3D Text (HTML)" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "white" "meta_frei0r.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "White Balance" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "white" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "White Balance" 
[Warning] <> libpng warning: iCCP: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG
[Debug  ] <MainWindow::open> "C:/Users/glorencin/AppData/Local/Meltytech/Shotcut/__untitled__.mlt" 
[Debug  ] <MltXmlChecker::MltXmlChecker()> decimal point ',' 
[Debug  ] <MltXmlChecker::check> begin 
[Debug  ] <MltXmlChecker::check> end 
[Debug  ] <AudioLoudnessScopeWidget::resetQview> begin 
[Debug  ] <LeapNetworkListener::onDisconnected> Disconnected from Leap Motion 
[Debug  ] <LeapNetworkListener::onError> Leap Motion WebSocket error: "Connection refused" 
[Debug  ] <MainWindow::open> "//sbs2011/RedirectedFolders/glorencin/My Documents/My Videos/Produkt_tovorni_program.mlt" 
[Debug  ] <MltXmlChecker::MltXmlChecker()> decimal point ',' 
[Debug  ] <MltXmlChecker::check> begin 
[Debug  ] <MltXmlChecker::check> end 
[Debug  ] <TimelineDock::setSelection> Changing selection to (0)  trackIndex -1 isMultitrack false 
[Info   ] <MainWindow::open> "//sbs2011/RedirectedFolders/glorencin/My Documents/My Videos/Produkt_tovorni_program.mlt" 
[Warning] <> libpng warning: iCCP: known incorrect sRGB profile
[Warning] <> libpng warning: iCCP: known incorrect sRGB profile
[Warning] <> libpng warning: iCCP: known incorrect sRGB profile
[Warning] <> libpng warning: iCCP: known incorrect sRGB profile
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[Debug  ] <MLT> [consumer sdl_audio] dropped video frame 1

... this for now.

**Comment by ddennedy** [comment]
Does it work to load something other than Produkt_tovorni_program.mlt?

**Comment by GoranUser** [comment]
Hmmm ... I thought I would have a good answer but I don`t ... I noticed that with that project there were some files that were supposed to be "bad" (.avi from youtube) but VLC played them ok ... but Premiere also did not want to import them ... but I opened another file and it crashed again and again ... will have to do more research when I`ll have time.

**Comment by ddennedy** [comment]
I do not know why it does not work for you. It works for me on all the systems in my house and hundreds of thousands of others based on the download counts. See the [FAQ](https://www.shotcut.org/FAQ/) for some possible reasons. It is known that Shotcut does not work on all systems as it has certain OpenGL or DirectX driver requirements. Also, some software installed on the system could be interfering, and nearly every system is different in that regard. Be sure to try all options under Settings > Display Method. With that said, I have generally had good compatibility experience with Nvidia hardware and drivers as I use them quite a bit myself.
