### ISSUE TITLE
Filters menu stutters when scrolling on macOS

### ISSUE THREAD

**Issue by vitorgalvao** [mltframework/shotcut#453]
The filters menu stutters when scrolling, on macOS. The stuttering is so prevalent it can completely prevent going down the list. This happens when scrolling *down* and slowly; scrolling faster can at least get further down the list.

![stutter gif](https://user-images.githubusercontent.com/1699443/31493070-86923650-af45-11e7-801b-0a1da02c94bb.gif)

[Stutter video](https://github.com/mltframework/shotcut/files/1379045/stutter.zip) (clearer than gif).

*Shotcut `17.10.02` and macOS `10.12.6`*.

**Comment by ddennedy** [comment]
I reproduce it but only on macOS. A workaround is to use more force/stronger gesture or to use the scroll bar.
