### ISSUE TITLE
shotcut 17.10 crashes when closed with a "core dumped" error.

### ISSUE THREAD

**Issue by martinkg** [mltframework/shotcut#456]
I use Fedora 26 with Shotcut 17.10

shotcut crashes when closed with a "core dumped" error.

```
Thread 1 "shotcut" received signal SIGSEGV, Segmentation fault.
0x00007ffff300f38a in QDateTime::QDateTime() () from /lib64/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff300f38a in QDateTime::QDateTime() () at /lib64/libQt5Core.so.5
#1  0x00007ffff30138fb in QDateTime::fromMSecsSinceEpoch(long long, Qt::TimeSpec, int) () at /lib64/libQt5Core.so.5
#2  0x00007ffff301445a in QDateTime::fromTime_t(unsigned int) () at /lib64/libQt5Core.so.5
#3  0x00007ffff30bba4c in QFileInfo::lastModified() const () at /lib64/libQt5Core.so.5
#4  0x00007ffff30fc01b in QConfFileSettingsPrivate::syncConfFile(int) () at /lib64/libQt5Core.so.5
#5  0x00007ffff30fc1ac in QConfFileSettingsPrivate::sync() () at /lib64/libQt5Core.so.5
#6  0x00007ffff30f3b76 in QSettings::~QSettings() () at /lib64/libQt5Core.so.5
#7  0x00005555556f95f0 in ShotcutSettings::~ShotcutSettings() (this=0x555555b593f0, __in_chrg=<optimized out>) at settings.h:27
#8  0x00005555556f95f0 in ShotcutSettings::~ShotcutSettings() (this=0x555555b593f0, __in_chrg=<optimized out>) at settings.h:27
#9  0x00007ffff1e36c68 in __run_exit_handlers (status=0, listp=0x7ffff21c75b8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:83
#10 0x00007ffff1e36cba in __GI_exit (status=<optimized out>) at exit.c:105
#11 0x00007ffff1e1c511 in __libc_start_main (main=
    0x5555555b8720 <main(int, char**)>, argc=1, argv=0x7fffffffdec8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdeb8) at ../csu/libc-start.c:329
#12 0x00005555555b8dca in _start () at main.cpp:261
```

**Comment by ddennedy** [comment]
Are you using a build provided by the Shotcut website or here on Github? It does not look like it since it is using system installed Qt 5. If you are, then you need to use the provided launch script instead of running bin/shotcut. We do not provide support for other people's builds, but we may accept a pull request from someone maintaining a build.

**Comment by martinkg** [comment]
I do not use a build provides by the Shotcut website or from github.
I use a rpm spec file https://martinkg.fedorapeople.org/Review/SPECS/shotcut.spec  for rpm based distributions like Fedora, Suse, Mageia, PClos etc.
[shotcut.spec](https://martinkg.fedorapeople.org/Review/SPECS/shotcut.spec)

> If you are, then you need to use the provided launch script instead of running bin/shotcut. 
where can i find such a launch script, or how looks it.

**Comment by ddennedy** [comment]
I appreciate your enthusiasm to maintain a RPM spec, but we are not available to debug other people's builds. I know how the Linux communities and distros tend to operate as I have been around it for a while, but I reject it for this app. This is the policy I have taken to prevent being dragged into debugging everyone's build problems, unique combinations of versions of dependencies, and all the different distros and their packaging systems. Those activities are a major time suck and demotivating work for volunteer developers. So, take my build if it works for you, or make and support your own. Again, if you have a change that you want to include to avoid maintaining your own patches or fork, I am open to that.

**Comment by martinkg** [comment]
only for information purposes:
with qt 5.7.1 wich is in stable Fedora branches, shotcut core dumpes.
with qt 5.9.2 which is in updates-testing, shutcut crashes any more.

**Comment by ddennedy** [comment]
Thanks, I am actually working on upgrading Qt to 5.9.2 for the next release of my builds.
