### ISSUE TITLE
 Where icon themes should be placed

### ISSUE THREAD

**Issue by martinkg** [mltframework/shotcut#457]
the sources of shotcut provide various icon themes.
Where should this icons be placed so that they can be found from shotcut.

icons/dark/32x32
icons/light/16x16
icons/light/32x32
icons/oxygen/32x32

Regards

('fedora 26; Shotcut 17.10`).

**Comment by ddennedy** [comment]
Icons are compiled as a Qt resource and bundled into the executable:
https://github.com/mltframework/shotcut/blob/master/src/src.pro#L269

QML files, however, are loaded from filesystem location relative to executable ../share/shotcut/qml
https://github.com/mltframework/shotcut/blob/master/src/qmltypes/qmlutilities.cpp#L64

Shotcut source is currently written primarily for relocatable app bundles and not system installation. Changes to make it more compatible with system installs requires contribution (pull requests).
