### ISSUE TITLE
Export Audio Sync Issue

### ISSUE THREAD

**Issue by m9115m** [mltframework/shotcut#459]
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

**Comment by m9115m** [comment]
A few years back, I reported an issue with audio video sync. It seems like the issue is still there. For some reason, I can't get audio and video to stay in sync when exporting. I suspect it has something to do with the source video and the export video being too different for the calculations to appropriately sync the audio and video. My workflow starts with an ATEM which captures at 720P 59.94 FPS. Recently, I needed to create a DVD from a 90-minute Sunday service, at the church. When I try to export, to what I think should be the appropriate format for a DVD, selecting the DVD template from the export options, I consistently get audio that is about 15 frames out of sync with the video. I've tried a number of different export settings, and I think I can get it a little bit better, but it feels like there's something not right. In the past, I've used Avid and never had issues like this. It's frustrating because when you're spending hours editing a show, and you export you expect the synk to be dead on.

**Comment by schauder** [comment]
Is this the same issue described here: https://forum.shotcut.org/t/audio-aligns-with-video-in-shotcut-but-goes-out-of-sync-after-export/535

I think I hit that and the workaround of converting everything before importing it to shotcut means a huge amount of work I have to redo :-(

**Comment by m9115m** [comment]
Yes, I believe the issue I'm experiencing is the same.

The work around I tried, which worked, was to change the project setting
from "Auto" to match the resolution and frame rate of the lion's share of
the material.  In my case, most of the material was fromn a Sunday church
service, recorded in 720p, 59.94, with intos and outros added that were
saved as mp4 @29.97.   After I changed the project settings to 720p@59.94,
I was able to export MP4 in sync.

The next test is to try exporting in other formats and frame rates to see
if I maintain sync.  I'm trying to get the material to VOB, so I can burn
it to DVD.

Hope that helps
Mike

Best Regards,

Mike Minadeo
mike.minadeo@gmail.com
971.207.2679

**Comment by ddennedy** [comment]
Probably related https://github.com/mltframework/mlt/issues/250
I will look into this soon.

**Comment by AleksMx** [comment]
Hello! I have the same issue. I use Shotcut 17.12.03 and have Ubuntu 16.04 LTS. I encounter a problem when I save and reopen the project. On one of audio track some points/entry moved to right on 2-3 s. The error grows closer to the end of the track. On the second track the same points does not move. 

All files I converted to mov extension with Convert to Edit-frendly function, so this is not problem with bitrate.

It looks like an error in the accuracy of counting the position of the track points.

Example of project file:
`<playlist id="playlist2">
    <property name="shotcut:audio">1</property>
    <property name="shotcut:name">Clicks</property>
    <property name="shotcut:lock">0</property>
    <blank length="00:00:01.933"/>
    <entry producer="producer40" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.533"/>
    <entry producer="producer41" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.333"/>
    <entry producer="producer42" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:08.333"/>
    <entry producer="producer43" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.733"/>
    <entry producer="producer44" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.533"/>
    <entry producer="producer45" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:07.333"/>
    <entry producer="producer46" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.133"/>
    <entry producer="producer47" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.533"/>
    <entry producer="producer48" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.733"/>
    <entry producer="producer49" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:06.400"/>
    <entry producer="producer50" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.133"/>
    <entry producer="producer51" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:00.800"/>
    <entry producer="producer52" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:00.933"/>
    <entry producer="producer53" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.400"/>
    <entry producer="producer54" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:05.733"/>
    <entry producer="producer55" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:09.933"/>
    <entry producer="producer56" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:07.800"/>
    <entry producer="producer57" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.333"/>
    <entry producer="producer58" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:02.600"/>
    <entry producer="producer59" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:02.200"/>
    <entry producer="producer60" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:09.333"/>
    <entry producer="producer61" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.400"/>
    <entry producer="producer62" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.333"/>
    <entry producer="producer63" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:03.000"/>
    <entry producer="producer64" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:09.133"/>
    <entry producer="producer65" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.600"/>
    <entry producer="producer66" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.333"/>
    <entry producer="producer67" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.333"/>
    <entry producer="producer68" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:00.933"/>
    <entry producer="producer69" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:02.333"/>
    <entry producer="producer70" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:00.533"/>
    <entry producer="producer71" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:00.200"/>
    <entry producer="producer72" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.400"/>
    <entry producer="producer73" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:00.333"/>
    <entry producer="producer74" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:00.333"/>
    <entry producer="producer75" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.333"/>
    <entry producer="producer76" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.333"/>
    <entry producer="producer77" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.933"/>
    <entry producer="producer78" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:01.200"/>
    <entry producer="producer79" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:09.533"/>
    <entry producer="producer80" in="00:00:00.000" out="00:00:00.133"/>
    <blank length="00:00:02.133"/>
    <entry producer="producer81" in="00:00:00.000" out="00:00:00.133"/>
  </playlist>`

**Comment by ddennedy** [comment]
I believe I finally reproduced this today through a methodical test using the same 23.976 fps clip with burned-in timecode on two video tracks, splitting and lifting pieces from V2, saving, and opening the project. Occasionally, some of the blanks that get inserted during the "lift" operation are one frame too long. I am still looking for the root bug.

**Comment by m9115m** [comment]
Thanks Dan.  Appreciate you coming back to this one.  Especially around the holidays.

Hope you have a Merry Christmas

And thanks again for this awesome editing tool.

**Comment by ddennedy** [comment]
This is at least partially fixed as far as what @AleksMx reported and the related issue #479, which is resolved. There might still be something wrong mixing with material with differing frame rates that I have not yet produced; so, leaving this open longer for more investigation.

**Comment by kratzbaumkordel** [comment]
Hi. I have a similar issue. I don't know if the cause is the same. The audio of the videos themselves remain in sync after export, but the audio track I add is out of sync after export. I.e. in Shotcut I align the cuts in the video track to the beat in the audio track, but in the exported mp4 the cuts are not aligned anymore. Sometimes it seems they gradually get more out of sync later in the video, sometimes it seems to jump back and forth. 

Is this related? I didn't find an issue describing exactly this problem.
