### ISSUE TITLE
Video Trimming off near the End after Inserting from Playlist into the Timeline

### ISSUE THREAD

**Issue by NightfallAlicorn** [mltframework/shotcut#461]
`Windows 10; Shotcut 17.11.07`

Steps to reproduce:
1. Click and drag a video into the Playlist.
2. The video is at the correct length of 00:01:22;01 when played from the Playlist.
3. Click and drag it into the Timeline.
4. The video ending is wrong since it is now at 00:01:08;13 when I play the Timeline video.

I've repeated this a few times and I don't know why from Playlist to Timeline it's cropping some seconds off the end. I've never had this issue before when performing  trimming videos. I hadn't even started to trim it yet. I've made sure the video is placed right at the start of the Timeline as well.

Here's a [screenshot](https://i.imgur.com/dgKFGWr.png) of the video information.

This video was originally recorded on the regular PS4 and uploaded to YouTube. Then downloaded from the Video Manager page since I am the owner of the content. I wanted to apply some editing to it and re-upload it.

I've already updated from the old Shotcut version to the new version and it still has this strange issue. The whole downloaded MP4 plays correctly in Windows' Film & TV app.

**Comment by NightfallAlicorn** [comment]
I've found the problem. Changing `Settings > Video Mode` from `Automatic` to `HD 1080 29.97 fps` solved it. It seems Automatic wasn't providing the correct output in the Timeline for some reason.

**Comment by ddennedy** [comment]
This occurs when the video clip is something other than 25 fps. The problem is seen event after the first step: the player shows accurate duration, but the playlist in details or tiles mode has incorrect duration.
