### ISSUE TITLE
Crash on opening some avi files

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mltframework/shotcut#464]
You can download this video here https://cloud.mail.ru/public/7Ucu/ByN13ZJKX

Shotcut 17.08.01
macOS 10.13.1

**Comment by ddennedy** [comment]
Unable to reproduce using Shotcut 17.08 or 17.11 on both macOS 10.12.6 and Windows 10 with both GPU Processing enabled or not. Is GPU Processing enabled?
Pending label means I may close this after a few weeks if no progress is made.

**Comment by vitaly-zdanevich** [comment]
Try to move this audio to the timeline.

GPU processing enabled - because Shotcut said me that I need enable this because I use some GPU effect - but I do not remember where - I already have so many files on the timeline.

**Comment by ddennedy** [comment]
GPU processing is an unsupported feature clearly marked "experimental." I will not be looking into this any further at this time.

**Comment by vitaly-zdanevich** [comment]
Yes, sorry - without GPU processing I **can** open this file and add to the timeline.
