### ISSUE TITLE
issuewith windows resize limitation  (< 1920x1080)

### ISSUE THREAD

**Issue by meoso** [mltframework/shotcut#466]
I use Shotcut on a laptop with max resolution 1920x1080.  The window vertical height will not reduce small enough to see more than 2 tracks, even if i (ctrl -) make tracks smaller.

I would like to have even smaller than the current smallest track size (ctrl -).  I would like most all of the visual modules to be reduce-able just slightly more than current limits.

`Linux 4.10.0-38-generic #42-Ubuntu SMP Tue Oct 10 13:24:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
`Shotcut 17.11.07`

**Comment by ddennedy** [comment]
It does already reduce very much; however, maybe it is being constrained by some panel and its default placement. Close all panels except the Timeline and let me know if that helps. Also, are you running any sort of HiDPI setup? That can be a factor. View > Application Log... shows the DPI the app is trying to use, for example:
[Info   ] <Application::Application> device pixel ratio = 2

**Comment by meoso** [comment]
Thank you; solution worked (`export QT_AUTO_SCREEN_SCALE_FACTOR=0`). Previously `=2`.
This laptop does not have "hiDPI".

**Comment by ddennedy** [comment]
OK, this is determined by some heuristic in Qt. We plan to upgrade to Qt 5.9.2 soon, and maybe it will be improved.
