### ISSUE TITLE
Preview is ok when playing but rare picture update on using left and right keyboard keys

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mltframework/shotcut#467]
[I recorded animated gif](http://www.giphy.com/gifs/3osBLbmiRgjrJ1r7kQ). Firstly I pushed spacebar - and you see the preview without problems. After that I pushed space again for pausing the video and pushed left-left-left-left-left... and after that right-right-right-right-right - such frame by frame preview is **important** for video editing but for some reason we have such sad defect. I found that it occurs only in the space between two clips, no problem when only one clip with arrow keys, [see](https://giphy.com/gifs/shotcut-video-editor-3ohs7ZIRPwVxrSV4B2).

Source video for reproducing:
https://cloud.mail.ru/public/Hnha/Km4RR36iM
https://cloud.mail.ru/public/5KSX/RbTG9U2uH

Push this Russian button for downloading of the source video from links.
<img width="215" alt="screen shot 2017-11-24 at 9 55 09 am" src="https://user-images.githubusercontent.com/3514015/33198727-d93b0290-d0fd-11e7-8963-f36ec830793e.png">

Shotcut 17.08.01
macOS 10.13.1

**Comment by ddennedy** [comment]
Read the FAQ topic
https://www.shotcut.org/FAQ/#why-is-stepping-frame-by-frame-repeating-the-same-frame
