### ISSUE TITLE
Update Movit?

### ISSUE THREAD

**Issue by tin2tin** [mltframework/shotcut#468]
Just a heads up. I've just noticed(because someone is working on adding OpenCL filters to blender: [https://developer.blender.org/T53374](https://developer.blender.org/T53374)) that Steinar has been very busy working on Movit recently: [https://git.sesse.net/?p=movit;a=summary](https://git.sesse.net/?p=movit;a=summary)

Maybe updating the Movit-lib will add some more stability to the OpenGL filters?

**Comment by ddennedy** [comment]
It is a work-in-progress for the past couple months, but I have a problem with it still (integration problem, not Movit itself) blocking it.

**Comment by tin2tin** [comment]
No worries. :-)
[I hope you check into the SC forum to have a look at the EDL export bug. An uploaded mlt file is needed for reproduction of the bug]
