### ISSUE TITLE
Shotcut 17.11 doesn't start on Windows 10 Fall Creators Update

### ISSUE THREAD

**Issue by alessandrofrancesconi** [mltframework/shotcut#470]
Shotcut worked fine on my (pretty old) PC, but right after the Windows 10 Fall Creators Update it doesn't show up anymore when launched. I can only see the top bar but nothing else,  see the screenshot: https://imgur.com/a/Oikv6

My config:
- Shotcut 17.11
- Windows 10 64bit, Fall Creators Update, build 16299
- Processor	Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz, 3003 Mhz, 2 Core(s), 2 Logical Processor(s)
- 8 GB RAM
- NVIDIA GeForce 7300 SE/7200 GS, updated drivers

**Comment by Schyrsivochter** [comment]
For me (Intel i5-7200U with 2 cores and 4 logical processors, no dedicated graphics, 8 GB RAM), Shotcut 17.11 continues to work after the Fall Creators Update (build 16299). Might be an issue with your graphics or even your CPU (if that is even possible).

**Comment by alessandrofrancesconi** [comment]
Is there a way so I can debug this, maybe an error log?


---- Schyrsivochter ha scritto ----


For me (Intel i5-7200U with 2 cores and 4 logical processors, no dedicated graphics, 8 GB RAM), Shotcut 17.11 continues to work after the Fall Creators Update (build 16299). Might be an issue with your graphics or even your CPU (if that is even possible).

**Comment by ddennedy** [comment]
It works for me (lead developer) on Fall Creators Update on a system with GeForce 970ti. Your problem is likely related to the display driver but not entirely sure. I tested all of the Display methods in Settings as well as [GPU](https://shotcut.org/FAQ/) Processing enabled and disabled. It is difficult to debug, and it is unlikely that the log will be helpful. The FAQ explains how to get the log - it also depends on whether you have set an alternate location using Settings > App Data Directory. I recommend that you run the installer to reinstall and when you get the step with a few check boxes, click the checkbox to Remove Shotcut Settings from the Registry. Alternatively, the FAQ explains the registry location if you want to manually remove them yourself. You can also try updating the graphics driver with an installer provided by Nvidia.

**Comment by alessandrofrancesconi** [comment]
Thank you. For now, I can paste here the log when it starts:

`[Info   ] <Application::Application> Starting Shotcut version 17.11.07 
[Info   ] <Application::Application> Windows version 192 
[Info   ] <Application::Application> number of logical cores = 2 
[Info   ] <Application::Application> locale = QLocale(Italian, Latin, Italy) 
[Info   ] <Application::Application> install dir = "C:/Program Files/Shotcut" 
[Info   ] <Application::Application> device pixel ratio = 1 
[Debug  ] <MainWindow::changeTheme> begin 
[Debug  ] <MainWindow::changeTheme> end 
[Debug  ] <MainWindow::MainWindow> begin 
[Debug  ] <Mlt::Controller::Controller> begin 
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error opening shared object file 'C:\Program Files\Shotcut\lib\ladspa/AUTHORS': "C:\Program Files\Shotcut\lib\ladspa\AUTHORS": The specified module could not be found.
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error opening shared object file 'C:\Program Files\Shotcut\lib\ladspa/COPYING': "C:\Program Files\Shotcut\lib\ladspa\COPYING": The specified module could not be found.
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error finding ladspa_descriptor symbol in object file 'C:\Program Files\Shotcut\lib\ladspa/libfftw3f-3.dll': "ladspa_descriptor": The specified procedure could not be found.
[Info   ] <MLT> plugin_mgr_get_object_file_plugins: error opening shared object file 'C:\Program Files\Shotcut\lib\ladspa/readme.txt': "C:\Program Files\Shotcut\lib\ladspa\readme.txt": 
[Debug  ] <Mlt::Controller::Controller> end 
[Debug  ] <Mlt::GLWidget::GLWidget> begin 
[Debug  ] <Mlt::GLWidget::GLWidget> end 
[Debug  ] <MainWindow::setupSettingsMenu> begin 
[Warning] <MLT> [ 0x8a80600] The DeckLink drivers not installed.
[Debug  ] <MainWindow::setupSettingsMenu> end 
[Debug  ] <MainWindow::readPlayerSettings> begin 
[Debug  ] <MainWindow::readPlayerSettings> end 
[Debug  ] <MainWindow::configureVideoWidget> begin 
[Debug  ] <MainWindow::setProfile> "" 
[Debug  ] <Mlt::Controller::setProfile> setting to profile "Automatic" 
[Debug  ] <MainWindow::configureVideoWidget> end 
[Debug  ] <ScopeController::ScopeController> begin 
[Debug  ] <ScopeWidget::ScopeWidget> begin true 
[Debug  ] <ScopeWidget::ScopeWidget> end 
[Debug  ] <AudioLoudnessScopeWidget::AudioLoudnessScopeWidget> begin 
[Debug  ] <AudioLoudnessScopeWidget::AudioLoudnessScopeWidget> end 
[Debug  ] <ScopeDock::ScopeDock> begin 
[Debug  ] <ScopeDock::ScopeDock> end 
[Debug  ] <ScopeWidget::ScopeWidget> begin true 
[Debug  ] <ScopeWidget::ScopeWidget> end 
[Debug  ] <AudioPeakMeterScopeWidget::AudioPeakMeterScopeWidget> begin 
[Debug  ] <AudioPeakMeterScopeWidget::AudioPeakMeterScopeWidget> end 
[Debug  ] <ScopeDock::ScopeDock> begin 
[Debug  ] <ScopeDock::ScopeDock> end 
[Debug  ] <ScopeWidget::ScopeWidget> begin true 
[Debug  ] <ScopeWidget::ScopeWidget> end 
[Debug  ] <AudioSpectrumScopeWidget::AudioSpectrumScopeWidget> begin 
[Debug  ] <AudioSpectrumScopeWidget::AudioSpectrumScopeWidget> end 
[Debug  ] <ScopeDock::ScopeDock> begin 
[Debug  ] <ScopeDock::ScopeDock> end 
[Debug  ] <ScopeWidget::ScopeWidget> begin true 
[Debug  ] <ScopeWidget::ScopeWidget> end 
[Debug  ] <AudioWaveformScopeWidget::AudioWaveformScopeWidget> begin 
[Debug  ] <AudioWaveformScopeWidget::AudioWaveformScopeWidget> end 
[Debug  ] <ScopeDock::ScopeDock> begin 
[Debug  ] <ScopeDock::ScopeDock> end 
[Debug  ] <ScopeController::ScopeController> end 
[Debug  ] <RecentDock::RecentDock> begin 
[Debug  ] <RecentDock::RecentDock> end 
[Debug  ] <PlaylistDock::PlaylistDock> begin 
[Debug  ] <PlaylistDock::PlaylistDock> end 
[Debug  ] <TimelineDock::TimelineDock> begin 
[Debug  ] <TimelineDock::TimelineDock> end 
[Debug  ] <FiltersDock::FiltersDock> begin 
[Debug  ] <FiltersDock::FiltersDock> end 
[Debug  ] <EncodeDock::EncodeDock> begin 
[Debug  ] <EncodeDock::EncodeDock> end 
[Debug  ] <JobsDock::JobsDock> begin 
[Debug  ] <JobsDock::JobsDock> end 
[Debug  ] <MainWindow::readWindowSettings> begin 
[Debug  ] <MainWindow::readWindowSettings> end 
[Debug  ] <LeapNetworkListener::start> begin 
[Debug  ] <MainWindow::MainWindow> end 
[Debug  ] <Database::run> Database version is 1 
[Debug  ] <Mlt::GLWidget::initializeGL> begin 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL vendor "NVIDIA Corporation" 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL renderer "GeForce 7300 SE/7200 GS/PCIe/SSE2" 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL threaded? true 
[Info   ] <Mlt::GLWidget::initializeGL> OpenGL ES? false 
[Debug  ] <Mlt::GLWidget::initializeGL> end 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "alpha_adjust" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Alpha Channel: Adjust" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "alpha_view" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Alpha Channel: View" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_balance" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Balance" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_bandpass" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Band Pass" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_basstreble" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Bass & Treble" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_channelcopy" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Copy Channel" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_compressor" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Compressor" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_delay" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Delay" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_expander" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Expander" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_fadein" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade In Audio" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_fadeout" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade Out Audio" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_gain" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Gain / Volume" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_highpass" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "High Pass" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_limiter" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Limiter" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_lowpass" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Low Pass" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_mono" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Downmix" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_mute" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Mute" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_normalize_1p" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Normalize: One Pass" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_normalize_2p" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Normalize: Two Pass" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_notch" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Notch" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_pan" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Pan" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_reverb" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Reverb" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "audio_swapchannels" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Swap Channels" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "bluescreen0r" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Chroma Key: Simple" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "blur" "meta_boxblur.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Blur" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "blur" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Blur" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "brightness" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Brightness" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "brightness" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Brightness" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "color" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Color Grading" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "color" "meta_frei0r_coloradj.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Color Grading" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "color" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Color Grading" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "contrast" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Contrast" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "contrast" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Contrast" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "crop" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Crop" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "crop" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Crop" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "dust" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Old Film: Dust" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "dynamictext" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Text" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "fadein_brightness" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade In Video" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "fadein_movit" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade In Video" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "fadeout_brightness" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade Out Video" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "fadeout_movit" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Fade Out Video" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "glow" "meta_frei0r.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Glow" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "glow" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Glow" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "grain" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Old Film: Grain" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "invert" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Invert Colors" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "keyspillm0pup" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Key Spill: Advanced" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "lenscorrection" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Lens Correction" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "lines" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Old Film: Scratches" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "lut3d" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "LUT (3D)" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "mirror" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Mirror" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "mirror" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Mirror" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "movit_diffusion" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Diffusion" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "oldfilm" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Old Film: Projector" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "opacity" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Opacity" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "opacity" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Opacity" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "rotate" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Rotate" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "saturation" "meta_frei0r.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Saturation" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "saturation" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Saturation" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "select0r" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Chroma Key: Advanced" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "sepia" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Sepia Tone" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "sharpen" "meta_frei0r.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Sharpen" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "sharpen" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Sharpen" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "size_position" "meta_affine.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Size and Position" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "size_position" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Size and Position" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "smartblur" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Reduce Noise" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "spillsuppress" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Key Spill: Simple" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "stabilize" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Stabilize" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "tcolor" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Old Film: Technocolor" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "vignette" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Vignette" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "vignette" "meta_oldfilm.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Vignette" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "wave" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Wave" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "webvfx" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Overlay HTML" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "webvfx_circular_frame" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Circular Frame (HTML)" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "webvfx_ruttetraizer" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "Rutt-Etra-Izer (HTML)" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "webvfx_threejs_text" "meta.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "3D Text (HTML)" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "white" "meta_frei0r.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "White Balance" 
[Debug  ] <FilterController::loadFilterMetadata> reading filter metadata "white" "meta_movit.qml" 
[Debug  ] <FilterController::loadFilterMetadata> added filter "White Balance" 
[Warning] <> libpng warning: iCCP: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG
[Debug  ] <MainWindow::open> "C:/Users/miste/AppData/Local/Meltytech/Shotcut/__untitled__.mlt" 
[Debug  ] <MltXmlChecker::MltXmlChecker> decimal point ',' 
[Debug  ] <MltXmlChecker::check> begin 
[Debug  ] <MltXmlChecker::check> end 
[Debug  ] <Mlt::GLWidget::~GLWidget> begin 
[Debug  ] <Mlt::FrameRenderer::cleanup> begin 
[Debug  ] <Application::~Application> exiting 
`

**Comment by ddennedy** [comment]
The last 3 lines of the log indicate that the app is exiting normally perhaps on its own.
After `[Debug  ] <MltXmlChecker::check> end ` there should be the line `[Debug  ] <LeapNetworkListener::onConnected> Disconnected from Leap Motion`, which you do not have. Did you grab this log after you closed the window?
I wonder if you have something else on your computer listening on port 6437, which is the port the Leap Motion driver uses to communicate with apps using its WebSocket API.
This link shows how to use Resource Monitor and other things to see if there is something else listening on 6437: https://stackoverflow.com/questions/48198/how-can-you-find-out-which-process-is-listening-on-a-port-on-windows

**Comment by ddennedy** [comment]
It looks like it might be having a problem with the Leap Motion controller integration. Use Windows Resource Monitor  > Network > Listening Ports to see if anything is listening on TCP port 6437, and if so what.
I might need to make a setting that requires you to turn it on instead of simply trying to connect to this driver's WebSocket port and hoping it errors out if there is a problem.

**Comment by alessandrofrancesconi** [comment]
Tested the new 18.01 version, removing old registry settings at startup, on Windows 10.0.16299 Build 16299... and it works 👍
