### ISSUE TITLE
Delete a Fade In/out filter needs a redraw of time line

### ISSUE THREAD

**Issue by tin2tin** [mltframework/shotcut#472]
If time line doesn't get a redraw after deleting Fade In/Out filter, then the dark fade in/out triangles will still show.

(Another thing: if the dark triangle is pulled vertical(zero'ed), the fade in filter should be deleted from the filter list.)

**Comment by ddennedy** [comment]
I worked on the "another thing," but it was not stable enough to include in the next release. It is something I have been meaning to do for a while. I parked the changes into a local branch to revisit.

**Comment by tin2tin** [comment]
No worries. I was hoping it was a low hanging fruit. Thanks for all the fixes.
