### ISSUE TITLE
Crop won't work

### ISSUE THREAD

**Issue by SuperOP535** [mltframework/shotcut#476]
I've added & enabled the crop filter but when I change the bottom px nothing changes. I need this because I have to remove my taskbar (accidentally recorded full screen)

shotcut 17.11
windows 10 fall creators update

**Comment by ddennedy** [comment]
It works for me. Is GPU processing enabled in Settings? Is the filter applied to a clip in Source player, clip in Playlist, clip in Timeline, track in Timeline, or the entire Timeline?

**Comment by SuperOP535** [comment]
Enabling GPU processing did the thing, tysm for helping me and I love your software :) Keep up the good work!
