### ISSUE TITLE
Shotcut 17.12 doesn't start GUI on Ubuntu 16.04

### ISSUE THREAD

**Issue by reimashi** [mltframework/shotcut#477]
Shotcut doesn't start the GUI when run on my Ubuntu over snap.

- **OS:** Ubuntu 16.04.3 x64 (Kernel 4.10)
- **GPU:** AMD RX 570 with amdgpu-pro 17.40 drivers
- **Snap:** 2.29.4.2

I tested other programs with Qt (5.9 for more indications) over snap and run correctly.

[shotcut_log.txt](https://github.com/mltframework/shotcut/files/1589006/shotcut_log.txt)

**Comment by ddennedy** [comment]
Your snap environment is unable to provide an adequate OpenGL context. From the log
```
[Warning] <> QQuickWidget: Failed to make context current
[Warning] <> QQuickWidget::resizeEvent() no OpenGL context
```
OpenGL under snap is problematic especially with nvidia driver. I do not know about "amdgpu-pro" but you can search about it. There is nothing I can do as I will not remove the OpenGL requirement.
