### ISSUE TITLE
Shotcut in the Windows 32-bit system static link library (lib file)

### ISSUE THREAD

**Issue by leoxxw** [mltframework/shotcut#478]
THello, shotcut team: I am currently compiling the Windows 32-bit shotcut, but I don't have a 32-bit static link library (lib file) where I can get these.Thank you very much!

**Comment by leoxxw** [comment]
I seem to have mistaken my question. What I am missing is the file in the lib directory of MLT. I did not compile it.

**Comment by ddennedy** [comment]
Help with building is not provided. You can use the 64-bit Windows SDK we provide to work on the code to make code contributions that will then show up in all other build flavors:
https://www.shotcut.org/notes/windowsdev/
