### ISSUE TITLE
Shotcut 17.12 Audio tracks are shifted out of sync after reopening projects 

### ISSUE THREAD

**Issue by SleekPanther** [mltframework/shotcut#479]
This is a repost of (a bug from the Shotcut Forum](https://forum.shotcut.org/t/audio-tracks-are-shifted-out-of-sync-after-reopening-projects/3657), I hadn't gotten any response so am posting as an official issue here. Sorry if it's redundant.

I'm in Shotcut 17.12 on Windows 10 and was editing a large project and so I restarted my computer and reopened the project file. To my dismay, all my carefully timed audio clips in the Audio Track were time shifted at least 1 frame forward on the timeline. 
<img src="https://forum.shotcut.org/uploads/default/original/2X/7/7ace9f9478accab1e40a115c36ed96583be9ffc7.png" width="609" height="265">

When I initially saved the project, I had a bunch of video clips with audio clips that lined up with the exact start of the video, but now they all got shifted forward in time.  
The biggest problem is that they didn't all shift by the same amount. They started off being off by 1 frame, but by the end of my 5 minute video, they were 5-10 frames farther on the timeline from where they started.  
If they were all shifted by the same amount, I could have just trimmed 1 frame off the the beginning on the 1st audio clip and all would have moved earlier, but I had to manually drag each one because they got more and more out of sync.

I've replicated the bug in new projects and it still shifts audio tracks forward after restarting Shotcut and reopening the project, sometimes by just 1 frame and sometimes more.

I tried locking all tracks before saving, but no difference

Others have verified that it also happens to video tracks

**Comment by AleksMx** [comment]
I already reported this bug in this thread:
https://github.com/mltframework/shotcut/issues/459

**Comment by ddennedy** [comment]
This is fixed for the next release in a day or two in MLT git commit https://github.com/mltframework/mlt/commit/9e9a86a1214585259868448ba8477655e93d993c
