### ISSUE TITLE
ERROR: Unknown module(s) in QT: webkitwidgets in windows 7, Qt 5.10.0 and mingw530_32

### ISSUE THREAD

**Issue by cdwijs** [mltframework/shotcut#481]
I get the following compile error in windows 7, Qt 5.10.0 and mingw530_32:

07:37:24: Running steps for project shotcut...
07:37:24: Starting: "C:\Qt\5.10.0\mingw53_32\bin\qmake.exe" "D:\memories\2017 github qt progs\shotcut\shotcut.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
Info: creating stash file D:\memories\2017 github qt progs\build-shotcut-Desktop_Qt_5_10_0_MinGW_32bit-Debug\.qmake.stash
Info: creating cache file D:\memories\2017 github qt progs\build-shotcut-Desktop_Qt_5_10_0_MinGW_32bit-Debug\.qmake.cache
07:37:24: The process "C:\Qt\5.10.0\mingw53_32\bin\qmake.exe" exited normally.
07:37:24: Starting: "C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe" qmake_all
cd CuteLogger\ && C:\Qt\5.10.0\mingw53_32\bin\qmake.exe -o Makefile "D:\memories\2017 github qt progs\shotcut\CuteLogger\CuteLogger.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
cd CuteLogger\ && C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile qmake_all
mingw32-make[1]: Entering directory 'D:/memories/2017 github qt progs/build-shotcut-Desktop_Qt_5_10_0_MinGW_32bit-Debug/CuteLogger'
mingw32-make[1]: Nothing to be done for 'qmake_all'.
mingw32-make[1]: Leaving directory 'D:/memories/2017 github qt progs/build-shotcut-Desktop_Qt_5_10_0_MinGW_32bit-Debug/CuteLogger'
cd mvcp\ && C:\Qt\5.10.0\mingw53_32\bin\qmake.exe -o Makefile "D:\memories\2017 github qt progs\shotcut\mvcp\mvcp.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
cd mvcp\ && C:/Qt/Tools/mingw530_32/bin/mingw32-make -f Makefile qmake_all
mingw32-make[1]: Entering directory 'D:/memories/2017 github qt progs/build-shotcut-Desktop_Qt_5_10_0_MinGW_32bit-Debug/mvcp'
mingw32-make[1]: Nothing to be done for 'qmake_all'.
mingw32-make[1]: Leaving directory 'D:/memories/2017 github qt progs/build-shotcut-Desktop_Qt_5_10_0_MinGW_32bit-Debug/mvcp'
cd src\ && C:\Qt\5.10.0\mingw53_32\bin\qmake.exe -o Makefile "D:\memories\2017 github qt progs\shotcut\src\src.pro" -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
Project MESSAGE: MLT_PATH not set; using ..\..\... You can change this with 'qmake MLT_PATH=...'
Project MESSAGE: Install PREFIX not set; using C:\Projects\Shotcut. You can change this with 'qmake PREFIX=...'
Project ERROR: Unknown module(s) in QT: webkitwidgets
Makefile:85: recipe for target 'sub-src-qmake_all' failed
mingw32-make: *** [sub-src-qmake_all] Error 3
07:37:27: The process "C:\Qt\Tools\mingw530_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project shotcut (kit: Desktop Qt 5.10.0 MinGW 32bit)
When executing step "qmake"
07:37:27: Elapsed time: 00:03.

**Comment by cdwijs** [comment]
Webkit has been removed from the official Qt download:
https://forum.qt.io/topic/76739/webkit-status-2017
It's available in source form here:
http://download.qt.io/community_releases/
And in compiled form here:
https://github.com/annulen/webkit/releases

i did not yet figure out howto use the above to add the webkitwidgets module into Qt

**Comment by ddennedy** [comment]
This is not a defect, and help with building is not provided. If you want to help contribute to the code, you should consider using the information here: https://www.shotcut.org/notes/windowsdev/
