### ISSUE TITLE
PNG Load Failure v18.01

### ISSUE THREAD

**Issue by CutestCreeperEver** [mltframework/shotcut#485]
As of the new version, I would import a .PNG image and preview it. And it would play around with the image and cause it to malfunction. Then I exported the video/project and I wasted about 1 Hour and 25 Minutes just when I saw the preview had the the same problem as the previewed image. To the developer, I must say to fix this problem and other than that you made a pretty good piece of software

**Comment by ddennedy** [comment]
Unable to reproduce with this very poor description. I have no idea what you are saying. Nothing changed recently with PNG.

**Comment by CutestCreeperEver** [comment]
In return to this poor description I am sorry to interrupt you.
