### ISSUE TITLE
SplitClip condition is off by one frame

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#487]
Hello,

in TimelineDock::splitClip(), the range of the clip under the playhead is checked and the split is performed if the playhead is inside of the clip:

`if (info && m_position >= info->start && m_position < info->start + info->frame_count - 1)`

However, I think it should be:

`if (info && m_position > info->start && m_position < info->start + info->frame_count)`

The problem with the first version can be seen at the start or towards the end of a clip.

Repro 1:
- Place the playhead exactly at the beginning of a clip.
- Split the clip.
- Result: A two-frame clip is cut from the clip and inserted at the beginning, shifting clips to the right.

Repro 2:
- Place the playhead one frame _before_ the end of a clip.
- Try to split the clip.
- Result: The last frame cannot be split from the clip.

Corollary:
- Place the playhead inside of a clip.
- Repeatedly split the clip.
- Result: A bunch of clips is inserted at the split position. Only the first split should succeed.

I think the proposed change fixes these issues.

**Comment by ddennedy** [comment]
thanks

**Comment by ochilan** [comment]
yw
