### ISSUE TITLE
Crashes on opening

### ISSUE THREAD

**Issue by iansoady** [mltframework/shotcut#492]
Windows 10 Pro 64 bit, Dell Optiplex 755, Intel(R) Core(TN)2Duo CPU E8400@3.00GHz, 8GB memory.

Program starts then gives error (Failed to create openGL context......)

Log file attached.
[shotcut-log.txt](https://github.com/mltframework/shotcut/files/1691822/shotcut-log.txt)

**Comment by ddennedy** [comment]
The relevant messages from your log are:
```
[Warning] <> create: Could not initialize EGL display: error 0x3001
[Warning] <> create: When using ANGLE, check if d3dcompiler_4x.dll is available
[Warning] <> create: Could not initialize EGL display: error 0x3001
[Warning] <> create: When using ANGLE, check if d3dcompiler_4x.dll is available
[Debug  ] <> failed to acquire GL context to resolve capabilities, using defaults..
```
Unfortunately, your system does not meet the minimum requirements as specified in the [FAQ](https://www.shotcut.org/FAQ/). Specifically, it needs to support OpenGL either directly or indirectly. Your system is simply incompatible and nothing will be done about this.
