### ISSUE TITLE
Shortcut keys don't work when windows are detached

### ISSUE THREAD

**Issue by rauhs** [mltframework/shotcut#495]
Hi,

thanks for Shotcut! I really enjoy it.

I noted that when i detach windows into their own windows (so they float and I can move them around) that the keyboard shortcuts don't work when unless the main window has focus. This makes it almost unusable to detach the timeline window since I can't cut unless I first click on the main window.

OS: Ubuntu 16.04.
Shotcut: 18.02.01

**Comment by ddennedy** [comment]
Thank you for reminder. Closing as duplicate of #344, which is still open.
