### ISSUE TITLE
MacBook Pro 2017, timeline scrolling: trackpad "turns off" after a few seconds

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mltframework/shotcut#497]
Just try to move the timeline with touch bar, because of that I forced to use horizontal scrollbar.

macOS 10.13.3
Shotcut 18.01.02

**Comment by ddennedy** [comment]
None of the developers have a mac with a touch bar. Is there another way to reproduce it? I doubt there is anything we can do anyway as we do make the code for scrolling; it is provided by Qt.

**Comment by vitaly-zdanevich** [comment]
Sorry sorry, not a touch bar - I mean usual trackpad!
