### ISSUE TITLE
Pauses in exported video, portion of second

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mltframework/shotcut#498]
https://youtu.be/JACfnH12EnA?t=51s
The next cam starts with a pause, portion of the second. In Shotcut preview this part is correct.

You can see the same defect [here](https://youtu.be/JACfnH12EnA?t=1m21s) and [here](https://youtu.be/JACfnH12EnA?t=2m3s) too.

I exported project second time - pauses at the same places.

Exported settings from YouTube preset:

> movflags=+faststart
> preset=fast
> f=mp4
> acodec=aac
> ar=96000
> ab=384k
> vcodec=libx264
> crf=21
> g=13
> bf=2
> width=1920
> height=1080
> aspect=1.77778
> progressive=1
> top_field_first=2
> deinterlace_method=yadif
> rescale=hyper
> r=25
> threads=0

macOS 10.13.3
Shotcut 18.01.02

**Comment by ddennedy** [comment]
Is GPU Processing enabled?
Please test if disabling Export > Parallel processing makes a difference.

Please provide some information about the format of the source clip. Another test that will take longer is to convert your source clips to an edit-friendly format using Properties > Convert to Edit-friendly as it appears to have difficulty to seek properly on your clips.

**Comment by vitaly-zdanevich** [comment]
GPU processing was disabled.

Tried to disable parallel processing: pauses at the same places.

Information about [first clip](https://cloud.mail.ru/public/E6Du/HSqBu3k1C):

> # ffprobe output
> 
> [programs.program.0]
> program_id=100
> program_num=100
> nb_streams=4
> pmt_pid=129
> pcr_pid=308
> start_pts=920000
> start_time=0:00:00.920000
> end_pts=112600000
> end_time=0:01:52.600000
> 
> [programs.program.0.streams.stream.0]
> index=0
> codec_name=mpeg2video
> codec_long_name=MPEG-2 video
> profile=Main
> codec_type=video
> codec_time_base=1/25
> codec_tag_string=[2][0][0][0]
> codec_tag=0x0002
> width=1440
> height=1080
> coded_width=0
> coded_height=0
> has_b_frames=1
> sample_aspect_ratio=4:3
> display_aspect_ratio=16:9
> pix_fmt=yuv420p
> level=6
> color_range=tv
> color_space=bt709
> color_transfer=bt709
> color_primaries=bt709
> chroma_location=left
> field_order=tt
> timecode=N/A
> refs=1
> id=0x810
> r_frame_rate=25/1
> avg_frame_rate=25/1
> time_base=1/90000
> start_pts=90000
> start_time=0:00:01.000000
> duration_ts=10044000
> duration=0:01:51.600000
> bit_rate=25 Mbit/s
> max_bit_rate=N/A
> bits_per_raw_sample=N/A
> nb_frames=N/A
> nb_read_frames=N/A
> nb_read_packets=N/A
> 
> [programs.program.0.streams.stream.0.disposition]
> default=0
> dub=0
> original=0
> comment=0
> lyrics=0
> karaoke=0
> forced=0
> hearing_impaired=0
> visual_impaired=0
> clean_effects=0
> attached_pic=0
> timed_thumbnails=0
> 
> [programs.program.0.streams.stream.1]
> index=1
> codec_name=mp2
> codec_long_name=MP2 (MPEG audio layer 2)
> profile=unknown
> codec_type=audio
> codec_time_base=1/48000
> codec_tag_string=[3][0][0][0]
> codec_tag=0x0003
> sample_fmt=s16p
> sample_rate=48 KHz
> channels=2
> channel_layout=stereo
> bits_per_sample=0
> id=0x814
> r_frame_rate=0/0
> avg_frame_rate=0/0
> time_base=1/90000
> start_pts=82800
> start_time=0:00:00.920000
> duration_ts=10033200
> duration=0:01:51.480000
> bit_rate=384 Kbit/s
> max_bit_rate=N/A
> bits_per_raw_sample=N/A
> nb_frames=N/A
> nb_read_frames=N/A
> nb_read_packets=N/A
> 
> [programs.program.0.streams.stream.1.disposition]
> default=0
> dub=0
> original=0
> comment=0
> lyrics=0
> karaoke=0
> forced=0
> hearing_impaired=0
> visual_impaired=0
> clean_effects=0
> attached_pic=0
> timed_thumbnails=0
> 
> [programs.program.0.streams.stream.2]
> index=2
> codec_name=unknown
> codec_long_name=unknown
> profile=unknown
> codec_type=unknown
> codec_tag_string=[160][0][0][0]
> codec_tag=0x00a0
> id=0x815
> r_frame_rate=0/0
> avg_frame_rate=0/0
> time_base=1/90000
> start_pts=82800
> start_time=0:00:00.920000
> duration_ts=10051200
> duration=0:01:51.680000
> bit_rate=N/A
> max_bit_rate=N/A
> bits_per_raw_sample=N/A
> nb_frames=N/A
> nb_read_frames=N/A
> nb_read_packets=N/A
> 
> [programs.program.0.streams.stream.2.disposition]
> default=0
> dub=0
> original=0
> comment=0
> lyrics=0
> karaoke=0
> forced=0
> hearing_impaired=0
> visual_impaired=0
> clean_effects=0
> attached_pic=0
> timed_thumbnails=0
> 
> [programs.program.0.streams.stream.3]
> index=3
> codec_name=unknown
> codec_long_name=unknown
> profile=unknown
> codec_type=unknown
> codec_tag_string=[161][0][0][0]
> codec_tag=0x00a1
> id=0x811
> r_frame_rate=0/0
> avg_frame_rate=0/0
> time_base=1/90000
> start_pts=82800
> start_time=0:00:00.920000
> duration_ts=10051200
> duration=0:01:51.680000
> bit_rate=N/A
> max_bit_rate=N/A
> bits_per_raw_sample=N/A
> nb_frames=N/A
> nb_read_frames=N/A
> nb_read_packets=N/A
> 
> [programs.program.0.streams.stream.3.disposition]
> default=0
> dub=0
> original=0
> comment=0
> lyrics=0
> karaoke=0
> forced=0
> hearing_impaired=0
> visual_impaired=0
> clean_effects=0
> attached_pic=0
> timed_thumbnails=0
> 
> [streams.stream.0]
> index=0
> codec_name=mpeg2video
> codec_long_name=MPEG-2 video
> profile=Main
> codec_type=video
> codec_time_base=1/25
> codec_tag_string=[2][0][0][0]
> codec_tag=0x0002
> width=1440
> height=1080
> coded_width=0
> coded_height=0
> has_b_frames=1
> sample_aspect_ratio=4:3
> display_aspect_ratio=16:9
> pix_fmt=yuv420p
> level=6
> color_range=tv
> color_space=bt709
> color_transfer=bt709
> color_primaries=bt709
> chroma_location=left
> field_order=tt
> timecode=N/A
> refs=1
> id=0x810
> r_frame_rate=25/1
> avg_frame_rate=25/1
> time_base=1/90000
> start_pts=90000
> start_time=0:00:01.000000
> duration_ts=10044000
> duration=0:01:51.600000
> bit_rate=25 Mbit/s
> max_bit_rate=N/A
> bits_per_raw_sample=N/A
> nb_frames=N/A
> nb_read_frames=N/A
> nb_read_packets=N/A
> 
> [streams.stream.0.disposition]
> default=0
> dub=0
> original=0
> comment=0
> lyrics=0
> karaoke=0
> forced=0
> hearing_impaired=0
> visual_impaired=0
> clean_effects=0
> attached_pic=0
> timed_thumbnails=0
> 
> [streams.stream.1]
> index=1
> codec_name=mp2
> codec_long_name=MP2 (MPEG audio layer 2)
> profile=unknown
> codec_type=audio
> codec_time_base=1/48000
> codec_tag_string=[3][0][0][0]
> codec_tag=0x0003
> sample_fmt=s16p
> sample_rate=48 KHz
> channels=2
> channel_layout=stereo
> bits_per_sample=0
> id=0x814
> r_frame_rate=0/0
> avg_frame_rate=0/0
> time_base=1/90000
> start_pts=82800
> start_time=0:00:00.920000
> duration_ts=10033200
> duration=0:01:51.480000
> bit_rate=384 Kbit/s
> max_bit_rate=N/A
> bits_per_raw_sample=N/A
> nb_frames=N/A
> nb_read_frames=N/A
> nb_read_packets=N/A
> 
> [streams.stream.1.disposition]
> default=0
> dub=0
> original=0
> comment=0
> lyrics=0
> karaoke=0
> forced=0
> hearing_impaired=0
> visual_impaired=0
> clean_effects=0
> attached_pic=0
> timed_thumbnails=0
> 
> [streams.stream.2]
> index=2
> codec_name=unknown
> codec_long_name=unknown
> profile=unknown
> codec_type=unknown
> codec_tag_string=[160][0][0][0]
> codec_tag=0x00a0
> id=0x815
> r_frame_rate=0/0
> avg_frame_rate=0/0
> time_base=1/90000
> start_pts=82800
> start_time=0:00:00.920000
> duration_ts=10051200
> duration=0:01:51.680000
> bit_rate=N/A
> max_bit_rate=N/A
> bits_per_raw_sample=N/A
> nb_frames=N/A
> nb_read_frames=N/A
> nb_read_packets=N/A
> 
> [streams.stream.2.disposition]
> default=0
> dub=0
> original=0
> comment=0
> lyrics=0
> karaoke=0
> forced=0
> hearing_impaired=0
> visual_impaired=0
> clean_effects=0
> attached_pic=0
> timed_thumbnails=0
> 
> [streams.stream.3]
> index=3
> codec_name=unknown
> codec_long_name=unknown
> profile=unknown
> codec_type=unknown
> codec_tag_string=[161][0][0][0]
> codec_tag=0x00a1
> id=0x811
> r_frame_rate=0/0
> avg_frame_rate=0/0
> time_base=1/90000
> start_pts=82800
> start_time=0:00:00.920000
> duration_ts=10051200
> duration=0:01:51.680000
> bit_rate=N/A
> max_bit_rate=N/A
> bits_per_raw_sample=N/A
> nb_frames=N/A
> nb_read_frames=N/A
> nb_read_packets=N/A
> 
> [streams.stream.3.disposition]
> default=0
> dub=0
> original=0
> comment=0
> lyrics=0
> karaoke=0
> forced=0
> hearing_impaired=0
> visual_impaired=0
> clean_effects=0
> attached_pic=0
> timed_thumbnails=0
> 
> [format]
> filename=/Users/vitaly/inzhest/dk-dance/source/video/vitaly-zdanevich/Untitled Clip 01 02.mpeg
> nb_streams=4
> nb_programs=1
> format_name=mpegts
> format_long_name=MPEG-TS (MPEG-2 Transport Stream)
> start_time=0:00:00.920000
> duration=0:01:51.680000
> size=359.588261 Mibyte
> bit_rate=27.009714 Mbit/s
> probe_score=50
> Completed successfully in 00:00:00
> 

[Second clip](https://cloud.mail.ru/public/Hnha/Km4RR36iM) after that that was with pause:

> # ffprobe output
> 
> [programs.program.0]
> program_id=1
> program_num=1
> nb_streams=3
> pmt_pid=256
> pcr_pid=4097
> start_pts=540489
> start_time=0:00:00.540489
> end_pts=2636200489
> end_time=0:43:56.200489
> 
> [programs.program.0.streams.stream.0]
> index=0
> codec_name=h264
> codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
> profile=High
> codec_type=video
> codec_time_base=1/50
> codec_tag_string=HDMV
> codec_tag=0x564d4448
> width=1920
> height=1080
> coded_width=1920
> coded_height=1080
> has_b_frames=1
> sample_aspect_ratio=1:1
> display_aspect_ratio=16:9
> pix_fmt=yuv420p
> level=40
> color_range=N/A
> color_space=unknown
> color_transfer=unknown
> color_primaries=unknown
> chroma_location=left
> field_order=tt
> timecode=N/A
> refs=1
> is_avc=false
> nal_length_size=0
> id=0x1011
> r_frame_rate=50/1
> avg_frame_rate=25/1
> time_base=1/90000
> start_pts=55844
> start_time=0:00:00.620489
> duration_ts=237202200
> duration=0:43:55.580000
> bit_rate=N/A
> max_bit_rate=N/A
> bits_per_raw_sample=8
> nb_frames=N/A
> nb_read_frames=N/A
> nb_read_packets=N/A
> 
> [programs.program.0.streams.stream.0.disposition]
> default=0
> dub=0
> original=0
> comment=0
> lyrics=0
> karaoke=0
> forced=0
> hearing_impaired=0
> visual_impaired=0
> clean_effects=0
> attached_pic=0
> timed_thumbnails=0
> 
> [programs.program.0.streams.stream.1]
> index=1
> codec_name=ac3
> codec_long_name=ATSC A/52A (AC-3)
> profile=unknown
> codec_type=audio
> codec_time_base=1/48000
> codec_tag_string=AC-3
> codec_tag=0x332d4341
> sample_fmt=fltp
> sample_rate=48 KHz
> channels=2
> channel_layout=stereo
> bits_per_sample=0
> dmix_mode=-1
> ltrt_cmixlev=-1.000000
> ltrt_surmixlev=-1.000000
> loro_cmixlev=-1.000000
> loro_surmixlev=-1.000000
> id=0x1100
> r_frame_rate=0/0
> avg_frame_rate=0/0
> time_base=1/90000
> start_pts=48644
> start_time=0:00:00.540489
> duration_ts=237188160
> duration=0:43:55.424000
> bit_rate=256 Kbit/s
> max_bit_rate=N/A
> bits_per_raw_sample=N/A
> nb_frames=N/A
> nb_read_frames=N/A
> nb_read_packets=N/A
> 
> [programs.program.0.streams.stream.1.disposition]
> default=0
> dub=0
> original=0
> comment=0
> lyrics=0
> karaoke=0
> forced=0
> hearing_impaired=0
> visual_impaired=0
> clean_effects=0
> attached_pic=0
> timed_thumbnails=0
> 
> [programs.program.0.streams.stream.2]
> index=2
> codec_name=hdmv_pgs_subtitle
> codec_long_name=HDMV Presentation Graphic Stream subtitles
> profile=unknown
> codec_type=subtitle
> codec_time_base=0/1
> codec_tag_string=[144][0][0][0]
> codec_tag=0x0090
> width=1920
> height=1080
> id=0x1200
> r_frame_rate=0/0
> avg_frame_rate=0/0
> time_base=1/90000
> start_pts=48644
> start_time=0:00:00.540489
> duration_ts=N/A
> duration=N/A
> bit_rate=N/A
> max_bit_rate=N/A
> bits_per_raw_sample=N/A
> nb_frames=N/A
> nb_read_frames=N/A
> nb_read_packets=N/A
> 
> [programs.program.0.streams.stream.2.disposition]
> default=0
> dub=0
> original=0
> comment=0
> lyrics=0
> karaoke=0
> forced=0
> hearing_impaired=0
> visual_impaired=0
> clean_effects=0
> attached_pic=0
> timed_thumbnails=0
> 
> [streams.stream.0]
> index=0
> codec_name=h264
> codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
> profile=High
> codec_type=video
> codec_time_base=1/50
> codec_tag_string=HDMV
> codec_tag=0x564d4448
> width=1920
> height=1080
> coded_width=1920
> coded_height=1080
> has_b_frames=1
> sample_aspect_ratio=1:1
> display_aspect_ratio=16:9
> pix_fmt=yuv420p
> level=40
> color_range=N/A
> color_space=unknown
> color_transfer=unknown
> color_primaries=unknown
> chroma_location=left
> field_order=tt
> timecode=N/A
> refs=1
> is_avc=false
> nal_length_size=0
> id=0x1011
> r_frame_rate=50/1
> avg_frame_rate=25/1
> time_base=1/90000
> start_pts=55844
> start_time=0:00:00.620489
> duration_ts=237202200
> duration=0:43:55.580000
> bit_rate=N/A
> max_bit_rate=N/A
> bits_per_raw_sample=8
> nb_frames=N/A
> nb_read_frames=N/A
> nb_read_packets=N/A
> 
> [streams.stream.0.disposition]
> default=0
> dub=0
> original=0
> comment=0
> lyrics=0
> karaoke=0
> forced=0
> hearing_impaired=0
> visual_impaired=0
> clean_effects=0
> attached_pic=0
> timed_thumbnails=0
> 
> [streams.stream.1]
> index=1
> codec_name=ac3
> codec_long_name=ATSC A/52A (AC-3)
> profile=unknown
> codec_type=audio
> codec_time_base=1/48000
> codec_tag_string=AC-3
> codec_tag=0x332d4341
> sample_fmt=fltp
> sample_rate=48 KHz
> channels=2
> channel_layout=stereo
> bits_per_sample=0
> dmix_mode=-1
> ltrt_cmixlev=-1.000000
> ltrt_surmixlev=-1.000000
> loro_cmixlev=-1.000000
> loro_surmixlev=-1.000000
> id=0x1100
> r_frame_rate=0/0
> avg_frame_rate=0/0
> time_base=1/90000
> start_pts=48644
> start_time=0:00:00.540489
> duration_ts=237188160
> duration=0:43:55.424000
> bit_rate=256 Kbit/s
> max_bit_rate=N/A
> bits_per_raw_sample=N/A
> nb_frames=N/A
> nb_read_frames=N/A
> nb_read_packets=N/A
> 
> [streams.stream.1.disposition]
> default=0
> dub=0
> original=0
> comment=0
> lyrics=0
> karaoke=0
> forced=0
> hearing_impaired=0
> visual_impaired=0
> clean_effects=0
> attached_pic=0
> timed_thumbnails=0
> 
> [streams.stream.2]
> index=2
> codec_name=hdmv_pgs_subtitle
> codec_long_name=HDMV Presentation Graphic Stream subtitles
> profile=unknown
> codec_type=subtitle
> codec_time_base=0/1
> codec_tag_string=[144][0][0][0]
> codec_tag=0x0090
> width=1920
> height=1080
> id=0x1200
> r_frame_rate=0/0
> avg_frame_rate=0/0
> time_base=1/90000
> start_pts=48644
> start_time=0:00:00.540489
> duration_ts=N/A
> duration=N/A
> bit_rate=N/A
> max_bit_rate=N/A
> bits_per_raw_sample=N/A
> nb_frames=N/A
> nb_read_frames=N/A
> nb_read_packets=N/A
> 
> [streams.stream.2.disposition]
> default=0
> dub=0
> original=0
> comment=0
> lyrics=0
> karaoke=0
> forced=0
> hearing_impaired=0
> visual_impaired=0
> clean_effects=0
> attached_pic=0
> timed_thumbnails=0
> 
> [format]
> filename=/Users/vitaly/inzhest/dk-dance/source/video/nelly-artemenko/00002.MTS
> nb_streams=3
> nb_programs=1
> format_name=mpegts
> format_long_name=MPEG-TS (MPEG-2 Transport Stream)
> start_time=0:00:00.540489
> duration=0:43:55.660000
> size=3.994337 Gibyte
> bit_rate=13.018027 Mbit/s
> probe_score=50
> Completed successfully in 00:00:00
> 

Oh, `convert to edit-friendly` sound interesting, maybe after that my preview will be smoother. Hm, for this file converting will take a couple of hours, I will write to this ticket as it finished.

**Comment by bmatherly** [comment]
Is that a transport stream file? TS files are known to have poor seeking. If you are editing a transport stream file and you need frame accuracy, I recommend using an intermediate format. DNxHD or FFV1 would work.

**Comment by vitaly-zdanevich** [comment]
> Another test that will take longer is to convert your source clips to an edit-friendly format using Properties > Convert to Edit-friendly as it appears to have difficulty to seek properly on your clips.

Now ok. This edit friendly format decrease quality or not?

**Comment by vitaly-zdanevich** [comment]
This edit-friendly files sooooo big, my hard drive will not enough for my current project :(

No other ways to render without pauses?

**Comment by ddennedy** [comment]
MPEG-2 (at least with B-frames) in Transport Stream aka HDV is particularly problematic since it is typically what is called open GOP. You can read more about that here:
https://documentation.apple.com/en/finalcutpro/professionalformatsandworkflows/index.html#chapter=2%26section=1

I have not been able to solve the issues with HDV and thankfully this format has largely faded in popularity. However, I think you said that second clip (AVCHD) giving more of the problem?

The edit-friendly formats generally do not lose much perceivable quality but only the "best" option is truly no quality loss. I am sorry, but yes, they are heavy. Another option to try - but not yet available in the Shotcut UI - is transmuxing. This simply takes the existing compressed audio and video out of the current container format and puts it into a new one that generally works better. Here is an example:
`ffmpeg -i 00002.MTS -codec copy -map 0 00002.mov`

You can use the ffmpeg that comes with Shotcut for this. I am curious to get your feedback if the transmuxing works, and if the problem is more with the HDV or the AVCHD clip.

**Comment by vitaly-zdanevich** [comment]
Thank you, I will try this transmuxing on Saturday. If I understand correctly quality and size of audio/video will remain the same? If this will fix the pauses on rendered video I can replace my source files with that transmuxed variants.

**Comment by vitaly-zdanevich** [comment]
Tried to transmuxe my MTS file:
```
$ ./ffmpeg -i ~/inzhest/dk-dance/source/video/nelly-artemenko/00002.MTS -codec copy -map 0 ~/inzhest/dk-dance/source/video/nelly-artemenko/00002.mov
ffmpeg version n3.2.9-1-g519a54cc19 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
  configuration: --prefix=/Users/ddennedy/BuildAgent/work/ef55b932ce3c3e94/shotcut/build --disable-static --disable-doc --disable-ffserver --enable-gpl --enable-version3 --enable-shared --enable-pthreads --enable-runtime-cpudetect --enable-libtheora --enable-libvorbis --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libvpx --enable-libopus
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[mpegts @ 0x7fb10e800000] PES packet size mismatch
Input #0, mpegts, from '/Users/vitaly/inzhest/dk-dance/source/video/nelly-artemenko/00002.MTS':
  Duration: 00:43:55.66, start: 0.540489, bitrate: 13018 kb/s
  Program 1 
    Stream #0:0[0x1011]: Video: h264 (High) (HDMV / 0x564D4448), yuv420p(top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 50 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x1100]: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, fltp, 256 kb/s
    Stream #0:2[0x1200]: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090), 1920x1080
[mov @ 0x7fb10e3e7600] track 1: codec frame size is not set
Output #0, mov, to '/Users/vitaly/inzhest/dk-dance/source/video/nelly-artemenko/00002.mov':
  Metadata:
    encoder         : Lavf57.56.101
    Stream #0:0: Video: h264 (High) (avc1 / 0x31637661), yuv420p(top first), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 50 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: ac3 (AC-3 / 0x332D4341), 48000 Hz, stereo, 256 kb/s
    Stream #0:2: Subtitle: hdmv_pgs_subtitle ([144][0][0][0] / 0x0090), 1920x1080
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
Press [q] to stop, [?] for help
[mpegts @ 0x7fb10e800000] PES packet size mismatch=00:43:52.28 bitrate=12348.4kbits/s speed= 219x    
frame=131784 fps=10936 q=-1.0 Lsize= 3976031kB time=00:43:55.62 bitrate=12358.2kbits/s speed= 219x    
video:3873631kB audio:83483kB subtitle:18293kB other streams:0kB global headers:1kB muxing overhead: 0.015693%
✔ /Applications/Shotcut.app/Contents/MacOS 
12:13 $ ls -lh ~/inzhest/dk-dance/source/video/nelly-artemenko/00002.mov
-rw-r--r--  1 vitaly  staff   3.8G Feb 17 12:13 /Users/vitaly/inzhest/dk-dance/source/video/nelly-artemenko/00002.mov
✔ /Applications/Shotcut.app/Contents/MacOS 
12:13 $ ls -lh ~/inzhest/dk-dance/source/video/nelly-artemenko/00002.MTS
-rw-r--r--@ 1 vitaly  staff   4.0G Nov  7 20:01 /Users/vitaly/inzhest/dk-dance/source/video/nelly-artemenko/00002.MTS
✔ /Applications/Shotcut.app/Contents/MacOS 
```

QuickTime cannot open this newly produced `mov` file, VLC show correct video without sound with error `Codec not supported. VLC could not decode the format "AC-3" (No description for this codec)`. Tried to open in Shotcut - I hear the sound and see the video. Opened Shortcut's xml in Vim and replaced links from `00002.MTS` to `00002.mov`, started export...

**Comment by vitaly-zdanevich** [comment]
No pauses in the exported video! And smaller filesize is also a plus.

**Comment by ddennedy** [comment]
A workaround is to use **Convert to Edit-friendly** or transmux procedure described here. The core issue is challenging and may require a risky change to either sensitive/critical MLT or FFmpeg code. I might add a transmux feature, but there are pitfalls to a simple approach and much work to a non-simple both of which can lead to numerous bugs and support issues.

**Comment by loretoparisi** [comment]
Question: the `disposition` fields:

```
"disposition": {
                                            "default": 0,
                                            "dub": 0,
                                            "original": 0,
                                            "comment": 0,
                                            "lyrics": 0,
                                            "karaoke": 0,
                                            "forced": 0,
                                            "hearing_impaired": 0,
                                            "visual_impaired": 0,
                                            "clean_effects": 0,
                                            "attached_pic": 0,
                                            "timed_thumbnails": 0
                                        }
```

are the default values in the stream?
