### ISSUE TITLE
logo 

### ISSUE THREAD

**Issue by faridosc** [mltframework/shotcut#50]
hi dan 

i saw that there is another attempt at making the logo that wasn't accepted. also that the concept had to contemplate this sign: ][ unfortunately i realised it after i had created this attempts. in case you like any i could try to develop them a bit more. 

my concept was focused on tracks of the timeline. one is more abstract and the other more figurative. in case you like any let me don't... maybe i could try a bit more in case you don't  :)

![proposal](https://cloud.githubusercontent.com/assets/373726/6448608/f286c426-c0f9-11e4-86f3-36fe282fa3fb.png)

**Comment by ddennedy** [comment]
no thanks
