### ISSUE TITLE
Shotcut on windows overwrites file if ".mp4" is not added manually

### ISSUE THREAD

**Issue by qubodup** [mltframework/shotcut#501]
18.03.08 Win10 minor security(?) issue

Conveniently, Shotcut adds the file extension to exported files - the lack of this feature caused many reports in the past for windows users.

However, if I have a test.mp4 file in my folder and I save a file called "test", it will not ask me whether I want to overwrite that file.

If I pick "test.mp4", then it will ask.

It should ask in both cases.

Related: the "save as type" field is empty. Perhaps if it is used probably, windows will automatically start asking for overwrite confirmation. There seems to be some info in https://msdn.microsoft.com/en-us/library/windows/desktop/ms646960(v=vs.85).aspx

**Comment by ddennedy** [comment]
We now use the Save as Type field, which prevents this issue.
