### ISSUE TITLE
If "GPU processing" is once set for a project, it cannot be unset

### ISSUE THREAD

**Issue by ivanatora** [mltframework/shotcut#504]
Ubuntu 17.10

Shotcut  shotcut-linux-x86_64-180102.tar.bz2

If you try to disable GPU processing for a project, Shotcut asks to restart. After the restart when you open the same project (File -> Open MLT as Clip), that option is still enabled.

I can't find where this setting is stored. It doesn't look it is in the MLT file. It doesn't look it is in ~/.local/share/Meltytech/ either. 

How can we disable "GPU processing" for a saved project?

**Comment by ddennedy** [comment]
This is by design. To workaround it, you need to remove all elements in the XML that reference "movit." but you will lose things in the process of that. There is no conversion feature.
