### ISSUE TITLE
Crashes with Google Maps in webvfx HTML.

### ISSUE THREAD

**Issue by coolwanglu** [mltframework/shotcut#505]
macOS 10.13.3
Shotcut 18.01.02

To reproduce:

1. Get a Google Map API Key if you don't have one:
  - Visit https://developers.google.com/maps/documentation/javascript/get-api-key to get a key
  - Download [crash1.html](https://gist.github.com/coolwanglu/bc6374578e599be5f42403d376e5504e) and put your key in there.
  - Load the html file in Chrome, and make sure that Google Map is loaded correctly.
2. Create a new project in Shotcut
3. Create a new video track and add any video file to the track
4. Add an Overlay HTML filter of the video, enable webvfx and load 
 [crash1.html](https://gist.github.com/coolwanglu/bc6374578e599be5f42403d376e5504e)  (with your API key), it should work
5. Reload the HTML file in the filter, Shotcut would crash: **Segmentation fault: 11**

There's another crash, which may or may not be related to the previous one. To reproduce, just repeat the steps above with [crash2.html](https://gist.github.com/coolwanglu/d48268820c45959ebd7f67a70999469d), and Shotcut should crash in step 4.
The log says:
```
[Fatal  ] <> ASSERT: "compatible(sourceImage)" in file image.cpp, line 28
Abort trap: 6
```
which probably points to [this file](https://github.com/mltframework/webvfx/blob/master/webvfx/image.cpp#L28).

**Comment by ddennedy** [comment]
What you are trying to do is not supported because current versions of Shotcut do not support SSL/TLS/HTTPS, and Google requires that. Also, this is not good use of the webvfx technology because the rendered HTML will not have a transparent background or be able to integration any sort of JavaScript animation. You might as well just make a screen shot and include that in your project instead of writing HTML. That is much easier and also a workaround for this bug, which I will leave open since it does crash.
I plan to upgrade the WebKit that Shotcut builds include and add support for OpenSSL at the same time. That might fix this. No ETA on that, but some effort was made, but it has been postponed to work on other things.

**Comment by coolwanglu** [comment]
Thanks for your reply.
A bit background: I'm build an video overlay for telemetry data with webvfx. [Demo](https://youtu.be/_MsNd2w-0O8).  I'd like a dynamic mini-map at the corner, like in many games. The easiest way should be to load Google Map and update the location for each frame.

I can also try to hack the https part, maybe with a proxy.

**Comment by ddennedy** [comment]
OK, that is a cool use case! I have a dev build that uses the new webkit and openssl bits, and I will test this to get expectation. The upgrades for release are planned after the keyframes feature development currently in progress, and I expect a couple of months from now.

**Comment by coolwanglu** [comment]
I tried to run Shotcut behind a http proxy, which forward the request to https. And Shotcut still crashes.

Anyway I was able to create a minimal test case: [crash3.html](https://gist.github.com/coolwanglu/4bb69424853d9cd05dc895f9ec4c502e).

It seems that Shotcut does not crash if:
- webvfx is not enabled, or
- I remove the `<img>` tag from the file.

Note that the tag is linking to an non-existing file, which might be the root cause.

**Comment by coolwanglu** [comment]
On a Linux machine, I built webvfx and ran `melt` with my mlt file, and it worked!

**Comment by coolwanglu** [comment]
It crashed again, and https://github.com/mltframework/webvfx/pull/5 fixed for me (maybe only partially).

**Comment by ddennedy** [comment]
FYI, I tested crash1.html in my Qt 5.9.2 with [WebKit 5.212](https://github.com/annulen/webkit) and OpenSSL libs, and it works.
