### ISSUE TITLE
Fade with opacity do nothing - works only black fade (from Filter tab)

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mltframework/shotcut#506]
[Recorded video about that defect](https://photos.google.com/share/AF1QipPhBC7EUBSjA0bsPlJdkrdq0tu2soZNe5dQghLhmGD7rD-ph1b8vd2Xk0j8-aSbBA/photo/AF1QipNNXA48aGV7f3n6kNl7jiDOT1bIhauvcj9oFcez?key=VFlBWUliNEZVNWszT2ZOV1hvcDNLX2lYMU0zdDdB).

MacOS: 10.13.3
Shotcut: 18.01.02

**Comment by ddennedy** [comment]
This is happening because you enabled compositing on the bottom-most video track. That should almost always be left disabled. No plans to change anything here (basically I cannot due to architecture design). I have thought about hiding the composite toggle on that track. It almost never makes sense to composite the the hidden black background track. Is there a particular reason why you enabled it?

**Comment by vitaly-zdanevich** [comment]
Oh, transparent fade works with disabled composition on bottom track... I had no particular reason to have this toggle (composition) enabled by default. Hm, strange UX, anyway thank you!

**Comment by ddennedy** [comment]
I need to do some research before choosing to hide Composite toggle on the lowest video track because I recall seeing some forum messages about people using that to achieve some outcome.

**Comment by ddennedy** [comment]
BTW, V1 composite is never enabled by default. However, added video tracks DO enable composite by default. Thus, if you remove the V1 track, then your bottom-most video track is most likely composite enabled. Yes, that is quirky, but I am not sure how to handle it. I am not comfortable changing someone's track setting as a side effect of it becoming the bottom-most video track. However, problems like yours causes more headache for users compared to the advantages of being able to enable composite on V1, then I will consider always forcing V1 to disable composite at the sacrifice of some corner case capabilities.

**Comment by ddennedy** [comment]
Fixed in 438eaaabec59a32da036fbb8b502a72a726ddccb
