### ISSUE TITLE
current 18.03 snap build uses different snapcraft.yaml?

### ISSUE THREAD

**Issue by walterav1984** [mltframework/shotcut#508]
The commands to the shipped binaries like melt/ffmpeg/ffprobe etc are missing from the current 18.03 snap although the changes were pulled:

https://github.com/mltframework/shotcut/commit/deb2413c8edd4879546e2c806284b046d1a89dbd

**Comment by ddennedy** [comment]
I had not yet pushed the changes to snapcraft.yaml. Your changes did not work and generates an error. I do not have time to improve the snap. Send something tested that works if you still want it.
