### ISSUE TITLE
Snapping is not always working

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mltframework/shotcut#509]
![shotcut--defect--magnet](https://user-images.githubusercontent.com/3514015/36944319-b62ef9a4-1faa-11e8-8076-de8a0702bc5f.gif)

And another case of incorrect snapping:
![shotcut--defect--combine](https://user-images.githubusercontent.com/3514015/36945031-bb0fc206-1fb8-11e8-9e63-80201abcfa5e.gif)

Shotcut 18.03

**Comment by qubodup** [comment]
The bottom one is probably because of the presence of the playhead.

was the clip's original location near the playhead in the top animation?
