### ISSUE TITLE
Crossfade is not always generated

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mltframework/shotcut#510]
![shotcut--defect--crossfade](https://user-images.githubusercontent.com/3514015/36945059-6cc98fea-1fb9-11e8-9ff1-7354c848a85c.gif)

Shotcut 18.03

**Comment by ddennedy** [comment]
The clips must be exactly next to each other with no space between them. This is currently by design and has always been this way. It is also explained in the tutorial video.
