### ISSUE TITLE
Import multiple files to playlist only works once

### ISSUE THREAD

**Issue by bag-man** [mltframework/shotcut#513]
Shotcut version: 18.03.04
OS: Arch Linux (kernel 4.9)

Once you have added multiple clips to the playlist, you can't then add another set of multiple clips. 

File > Open File... > Select two or more video files > See them added to the playlist. 

Repeat, see only the first video in the preview window, not added to the playlist. Just like you had only selected one file. 

Workaround: Drag and drop files into the playlist from your native file manager.

**Comment by ddennedy** [comment]
I do not reproduce this in our build of Shotcut against Qt 5.6.1. I see you are using a custom Arch (18.03.04 is not official). I do not fix bugs in on others' builds; however, I do accept patches that will not cause a regression in my build.

P.S. I have an unofficial build 17.11.27 against Qt 5.9.2 where I also do not reproduce it. In a couple of months, official Shotcut builds are moving to Qt 5.9.
