### ISSUE TITLE
x264 profile passing issues

### ISSUE THREAD

**Issue by 1stFalloutBoy** [mltframework/shotcut#514]
Windows 10 1709 Build 16299.248
Shotcut 18.03.02

Okay I have been doing some checking and checked the baseline,high and main profiles for x264 they all seem to have some problems resulting in pretty much them always exporting the exact same way.

Firstly the word entry:
vprofile= seems not to be recognizing any value and is complaining thus in the log.
“Undefined constant or missing ‘(’ in 'baseline”
“Undefined constant or missing ‘(’ in 'main”

Now of course there is no vprofile value in the High profile so therefore no complaint.

flags2=-wpred-dct8x8 ( this is in the baseline profile )
"Undefined constant or missing ‘(’ in ‘wpred’

Undefined constant or missing ‘(’ in ‘dct8x8’ ( in the main profile )
Unable to pass value
In all cases it shows "Unable to pass option value "

I will come back and add to this message any further details I can find.

**Comment by ddennedy** [comment]
There are some mysterious messages reported in the log, but if you set vprofile=baseline you do get baseline:
[libx264 @ 0x7f8db807e600] profile **Constrained Baseline**, level 4.2
[libx264 @ 0x7f8db807e600] 264 - core 152 r2854 e9a5903 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: **cabac=0** ref=3 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 **8x8dct=0** cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 **bframes=0** **weightp=0** keyint=13 keyint_min=1 scenecut=40 intra_refresh=0 rc_lookahead=13 rc=crf mbtree=1 crf=21.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00

vprofile=main give you this in the log:

[libx264 @ 0x7feeda870e00] profile **Main**, level 4.2
[libx264 @ 0x7feeda870e00] 264 - core 152 r2854 e9a5903 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: **cabac=1** ref=3 deblock=1:0:0 analyse=0x1:0x111 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 **8x8dct=0** cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 **bframes=2** b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 **weightp=2** keyint=13 keyint_min=1 scenecut=40 intra_refresh=0 rc_lookahead=13 rc=crf mbtree=1 crf=21.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00

MediaInfo reports the same on the output. You wrongly claim they are "the exact same." I think you are disturbed by messages you do not understand. I think these messages are from libavcodec might be trying to interpret these as an expression.

**Comment by 1stFalloutBoy** [comment]
I will do some more checking Dan because when I am looking at the XML and the log that are produced I didn't always seem to get the  http://www.videolan.org/x264.html part of the text is there somewhere where I can see the source code for the parser ?

**Comment by 1stFalloutBoy** [comment]
BTW I have just gone to 18.03.06
I have checked the logs running complete vanilla with no changes and yes I am seeing differences, the things I am noting that are screwing up I don't know if they are relevant or not to any encoding options and I am still trying to get my head around the whole conversion MLT>Codec situation but what I was seeing was:

[libx264 @ 000000000660dac0] [Eval @ 000000000e44eef0] Undefined constant or missing '(' in 'dct8x8'
[libx264 @ 000000000660dac0] Unable to parse option value "dct8x8"
[libx264 @ 000000000660dac0] [Eval @ 000000000e44eef0] Undefined constant or missing '(' in 'main'
[libx264 @ 000000000660dac0] Unable to parse option value "main"
[aac @ 000000000660d5e0] [Eval @ 000000000e44ee80] Undefined constant or missing '(' in 'dct8x8'
[aac @ 000000000660d5e0] Unable to parse option value "dct8x8"

I am trying to figure out how to pass information through to be able to get the desired encoding options I want - which I did have some minor success with this afternoon but with errors being thrown back in your face it becomes a bit of a crap shoot for the end user.

For reference I am trying to achieve AVC cabac=1 ref=4 High@L4.1

**Comment by ddennedy** [comment]
If you want to review the code, it is here https://github.com/mltframework/mlt/blob/master/src/modules/avformat/consumer_avformat.c

With respect to passing options, search for "apply_properties". It is the function that converts MLT properties to FFmpeg AVOptions.
In order to pass options to x264, see the output of `ffmpeg -h encoder=libx264` and convert its
`-option value` syntax to MLT's `option=value` syntax. In particular, notice that some x264 options are not directly exposed as AVOptions and you have to use "x264-params" (which you can put into the Other tab).

**Comment by ddennedy** [comment]
> [Eval @ 000000000e44eef0]

This suggests to me that libavcodec is attempting to evaluate the value supplied as an expression and then failing (because it is not an expression?).

> [aac @ 000000000660d5e0] Unable to parse option value "dct8x8"

This means that the aac AVCodecContext also accepts the "flags2" option, which in this case was intended for libx264. However, MLT does not know that because the property name was not prefaced with a 'v', which means (in MLT) to only target video objects. However, the aac object fails to understand the flags supplied (naturally, since they are x264 flags).

**Comment by 1stFalloutBoy** [comment]
Thanks I shall have a look at it, although things maybe functional end users will see stuff like that and do an instant WTF and if anything like me try to rip out what the log indicates as offensive. I don't know that I will have much to offer as I haven't programed in C or C++ for some 32 odd years and have largely forgotten it but I will try. It won't be today though as I have a concussion.

**Comment by ddennedy** [comment]
Sorry to hear about your concussion. I understand what you mean by confusing messages in the logs. There is so much to do, and this particular log cruft is one of those things that is not getting priority (or left for others).

**Comment by 1stFalloutBoy** [comment]
Thanks Dan
I've been looking through the code and as I said it's been a loooong time
since I've looked at C/C++ so I'm playing catch up a little bit can I ask
you to look at something and tell me if these two are equivalent.

( this is pulled from mlt and I found it very hard to read )
if ( ( out < 0 || out >= mlt_producer_get_length( self ) ) &&
!mlt_producer_is_blank( self ) )
        out = mlt_producer_get_length( self ) - 1;
    else if ( ( out < 0 || out >= mlt_producer_get_length( self ) ) &&
mlt_producer_is_blank( self ) )
        mlt_properties_set_position( MLT_PRODUCER_PROPERTIES( self ),
"length", out + 1 );
    else if ( out < 0 )
out = 0;


( without running through a compiler or debugger as I don't have either at
the moment - I would have written it this way - possibly wrongly )
if ( ( out < 0 || out >= mlt_producer_get_length( self ) )
{
    if( ( !mlt_producer_is_blank( self ) )
        out = mlt_producer_get_length( self ) - 1;
    else
        mlt_properties_set_position( MLT_PRODUCER_PROPERTIES( self ),
"length", out + 1 );

    if ( out < 0 )
        out =0;
}

**Comment by ddennedy** [comment]
Not quite. In fact, in the original the `else if ( out < 0 )` can never be reached. Also, there is a bug in the original at `else if ( ( out < 0 || out >= mlt_producer_get_length( self ) ) &&
mlt_producer_is_blank( self ) )`. It should not include the `out < 0 ||` part as it will result in setting the blank's length to 0 or less.
To fix the logic and make it easier to read, it should be:
```
	if ( mlt_producer_is_blank( self ) && out >= mlt_producer_get_length( self ) )
		// Extend the blank producer if needed.
		mlt_properties_set_position( MLT_PRODUCER_PROPERTIES( self ), "length", out + 1 );
	else if ( out < 0 )
		// Get the out point from the length.
		out = mlt_producer_get_length( self ) - 1;
```

**Comment by 1stFalloutBoy** [comment]
Yup that's why we use single step :) I had a look at some of the code and I
can follow what you are doing I am going to have a good look at Qt today
