### ISSUE TITLE
When you click “Remove Selected Filter” after clicking “Copy and Paste The Filters” the program crashes

### ISSUE THREAD

**Issue by emirfirlar** [mltframework/shotcut#518]
https://i.hizliresim.com/lOpYnJ.jpg

&emsp;

#### <h1>Expected behavior</h1>

&emsp;

<h3>Using Remove Selected Filter</h3>

&emsp;

#### <h1>Actual behavior</h1>

&emsp;

<h3>The program does not respond and then Shotcut.exe stops working</h3>

&emsp;

#### <h1>How to reproduce</h1>

&emsp;

“Remove Selected Filter” Bug 
&emsp;

&nbsp;&nbsp;&nbsp; I was using the “Video Filter” feature in the Shotcut. I decided to add a few filters. I copied and pasted the filters a few times. Then i clicked to “Remove Selected Filter” many times to delete the filters that I copied. I did this click swiftly. But the program didn’t respond and Shotcut.exe stopped working. It gives this “Remove Selected Filter” bug at many video filters. When i repeated this process again and again, it gave the same error at every try. 
I am following this process while making this error: 

&emsp;

* Open File – Filters – Add a Filter – Show Video Filters – Video Filter (3D Text, Audio Spectrum Vis., Brightness, Lut(3D) etc.) – Copy The Filters – Paste Filters – Copy The Filters – Paste Filters – Copy The Filters – Paste Filters –  Copy The Filters – Paste Filters – Remove Selected Filter – Remove Selected Filter – Remove Selected Filter – Shotcut.exe stopped working

&emsp;

&nbsp;&nbsp;&nbsp;I detected this error on my Windows 7 professional SP1 (32 bit) computer first. I thought there might be a hardware error at first. Thus i tried this process on another computer too. I detected the same error on this Windows 7 home basic SP1 (64bit) computer. By this way, i decided it was a bug. You can see the error in two computers in detail below.

&nbsp;&nbsp;&nbsp;This bug causes the program to stop working and shutdown itself, it should be fixed.

&emsp;

* Operating system 1: Windows 7 professional SP1 (32 bit)
İntel Core 2 Duo 2.13 Ghz , 4 gb RAM
* Program Version 1: Shotcut Version 18.03.06 (32bit)

&emsp;

* Operating system 2: Windows 7 home basic SP1 (64 bit)
İntel Pentium CPU B940 2.00 Ghz , 4 gb RAM
* Program Version 2: Shotcut Version 18.03.06 (64bit)

&emsp;

#### <h1>Recording Of The Bug</h1>

&emsp;

* Remove Selected Filters – Error Gif’s: 

&emsp;

<center>https://media.giphy.com/media/6bdkO41YY0w9TrSuSc/giphy.gif </center>

&emsp;

* You can see the error in the  Windows 7 professional (32 bit) computer video in detail below:

&emsp;

<iframe width="1263" height="519" src="https://www.youtube.com/embed/PPkl6sgRLg8" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

&emsp;

* You can see the error in the  Windows 7 home basic (64 bit) computer video in detail below:

&emsp;

<iframe width="1263" height="519" src="https://www.youtube.com/embed/yfp6Xu4k76I" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

&emsp;

### Useful Links:

&emsp;

[Shotcut Video Editor]( https://shotcut.org/)

[Github Repository]( https://github.com/mltframework/shotcut)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@emirfirlar/bug-hunting-shotcut-video-editor-when-you-click-to-remove-selected-filter-after-clicking-copy-and-paste-the-filters-the-program">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by wdtrap** [comment]
I have also experienced this using the brightness filter.

**Comment by ddennedy** [comment]
Very old now and did not reproduce.
