### ISSUE TITLE
Error when building shotcut through the Docker image

### ISSUE THREAD

**Issue by gntech** [mltframework/shotcut#521]
The discussion started [here](https://github.com/mltframework/shotcut/commit/bdaf45d8bba9d0a1ff51e5c6fa7021860b6509eb) about automating the shotcut build with travis. (and then extend that to automatically update the snap on every new release)

I have set up an initial .travis.yml on my fork of shotcut but the build fails with the following error:
This happens both when I build the docker image with Travis and when I pull the prebuilt docker image from docker hub.

``` bash
filter_swresample.c:146:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for( int i = 0; i < pdata->out_channels; i++ )
   ^
make[2]: *** [filter_swresample.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from ../../framework/mlt.h:57:0,
                 from common.h:24,
                 from producer_avformat.c:20:
producer_avformat.c: In function 'producer_get_image':
../../framework/mlt_log.h:88:58: warning: '_mlt_log_timings_begin' may be used uninitialized in this function [-Wmaybe-uninitialized]
 #define mlt_log_timings(service, format, args...) mlt_log((service), MLT_LOG_TIMINGS, (format), ## args)
                                                          ^
../../framework/mlt_log.h:98:10: note: '_mlt_log_timings_begin' was declared here
  int64_t _mlt_log_timings_begin = mlt_log_timings_now(), _mlt_log_timings_end;
          ^
producer_avformat.c:1611:2: note: in expansion of macro 'mlt_log_timings_begin'
  mlt_log_timings_begin();
  ^
make[2]: Leaving directory `/root/shotcut/src/mlt/src/modules/avformat'
make[1]: *** [all] Error 1
make[1]: Leaving directory `/root/shotcut/src/mlt/src/modules'
make: *** [all] Error 1
ERROR: Unable to build mlt
LOG: Process has finished. Reason: FAILURE Some kind of error occurred: Unable to build mlt
```

The entire log output from the build is [here](https://api.travis-ci.org/v3/job/353197418/log.txt)

**Comment by ddennedy** [comment]
There was a commit merged into MLT over the weekend that introduced this compile error that slipped through the [MLT Travis build on check-in](https://travis-ci.org/mltframework/mlt/builds/352540533?utm_source=github_status&utm_medium=notification) and then noticed our [nightly build server](http://build.mltframework.org/) is down for the Shotcut nightly full builds. We will fix it very soon.

**Comment by bmatherly** [comment]
Must be a difference in gcc version? I've literally been using for loop initial declarations since I first learned the C language ;)

**Comment by ddennedy** [comment]
Maybe you are mostly coding C++? None of the other code in MLT uses that feature. However, it might be nice to start allowing it since we say the codebase is C99 in a couple of files in mlt/docs/. 
This may require usage of `-std=c99`. However, that is somewhat gcc- specfic (and now clang). And then there is [this claim of a "Single-Unix-approved way"](https://stackoverflow.com/a/2193730), which will require setting CC variable.

**Comment by ddennedy** [comment]
Fixed in https://github.com/mltframework/mlt/commit/3021e900b5c60c059218e8e0400a77641f98929c
