### ISSUE TITLE
Switching workspace in Gnome resets position on timeline

### ISSUE THREAD

**Issue by verymilan** [mltframework/shotcut#524]
* Shutcut 18.03-1 (AUR/ArchLinux)
* Gnome 3.26.2 on Wayland

As soon as you switch to a different workspace and return back to Shotcut later, you will fall back to the first frame on the timeline(s) and need to navigate back to where you were before.

**Comment by ddennedy** [comment]
I do not reproduce it using our official build of 18.03.06 against Qt 5.6.1 but not using Arch or Wayland. Is your package using our binary? We do not provide support for other people's builds, but I will accept a patch if it does not cause a regression in our builds.
