### ISSUE TITLE
Audio bugs after exporting

### ISSUE THREAD

**Issue by vic797** [mltframework/shotcut#526]
I have been working on a project for the past three and today I tried to expor it to a MP4.
The audio of the final file is very quiet and the audio on the may project got damaged (I only hear static) and I have to start my project again

Also I experienced some bugs while adding a video or a picture to a track, also sometimes the program uses about 8Gb of RAM and 85% of the processor (I don't know what happened) and it usualy keeps running after closing the main window.

Also as a recomendation you should load the projetc files as an asyncronimous thread to prevent the "Not responding" message.

Working on Windows 10.

**Comment by ddennedy** [comment]
There should only be 1 issue reported per ticket. For the first issue with audio, we need steps to reproduce it as I do not reproduce it. Also, include program version.
The next release reduces the memory footprint especially when working with still images.
