### ISSUE TITLE
Crash on Windows10x64

### ISSUE THREAD

**Issue by MrShannonH** [mltframework/shotcut#528]
Is there any known fixes to shotcut vs 18.03.06 crashing on Windows 10 x 64. 
I have switched between the OpenGL and DirectX. When attempting to update onboard video Intel HD 4600, it says I already have a newer version than is available on Intel's site.

Log file is attached....Any help is greatly appreciated
[shotcut-log.txt](https://github.com/mltframework/shotcut/files/1864611/shotcut-log.txt)

**Comment by ddennedy** [comment]
It does not work on all systems. Are you able to do anything at all? If not, then we cannot fix this unless  you send me your computer. If you are able to do some things, but sometimes it crashes, then we need the steps to reproduce.

**Comment by ddennedy** [comment]
Possible duplicate of #271

**Comment by MrShannonH** [comment]
I am a former IT Tech, so could fix it if I had any known solutions.
I saw this issue was at least a former unfixed issue on your forums, but
wanted to check for updates.

The crashes seem to be more often, since I added text filters (regular and
3D).

I would almost need to do a screen capture to explain it ... But adding any
text filter with a fade in/out video filter. Does not seem to work the same
as i see online in tutorial vids.
I've gotten it to somewhat work, but am still learning the program.

But also can lock up until windows wants to close the program... At first
launch or when jumping from split to split.

Everything else seems to work fine, i could do several splits... Removing
sections, inserting extra video tracks etc.

I have not yet tried to export to a final .mp4

My cpu and ram are not maxed out, and I run SSD HD.

I might have to lose the text, unless you have any other ideas?

Idk if it means anything but I am working on a old (digitized) video from
1987...dinosaur days.

Fixed or not... Thank you for responding so quickly!


Thank you
Mr. Shannon Harris
shannonrharris08@gmail.com

**Comment by Schnellfahrer** [comment]
Hi,
Is there any progress on this issue? I'm experiencing the exact same thing and I also believe it might be related to a text filter with a fade in/out video filter. My cpu and ram are not maxed out either, and I too run the software from an SSD HD. I'm able to add audio and video tracks and start exporting files, but the program is very unstable and stops working (whiteout) or crashes after a short while almost every time. I have tried to export the small video clip maybe 20 times, but only succeeded three times.  Switching between the OpenGL and DirectX does not make any difference, neither does disabling "parallel processing" or adding an empty video track in the project (a tip I found on youtube).
Apart from ShotCut, my PC is working perfectly, so I'm suspecting it is related to this software.

Help is greatly appreciated!
Thanks,
H

**Comment by MrShannonH** [comment]
I was able to complete my video with EXTREME PATIENCE!
After every click or action (especially after a split)... I just had to wait. 
Key to look for is the audio waveform rebuilding after a split. 
I run windows 8 gadgets on win 10 and I just have to look for the cpu/ram to be low. 
We need to see the hourglass often with this program. 
Crashes are low if you have EXTREME PATIENCE!

**Comment by Schnellfahrer** [comment]
Thanks for your quick reply MrShannonH!
I'm running on my brand new PC built by myself, now with win 10 (initially I started with Ubuntu, but the program was crashing there as well, so therefore I tried windows instead. This seems to have improved stability somewhat)...I have 32 GB RAM, AMD RYZEN 7 CPU, a 500GB SSD HD and a Geforce 1050Ti graphics card, so my system should be well equipped to handle video editing even if I'm working in 4K i think....I'm a newbie in ShotCut, but apart from the very frequent crashes I really like the program so I hope this issue could be solved soon;-) I have several other video projects in the loop that I would like to edit in ShotCut with my new PC.....

**Comment by ddennedy** [comment]
@Schnellfahrer I do not have a machine on which it is unstable like you describe. Perhaps if I bought one with AMD Ryzen and GeForce 1050ti, but I am not certain if that will reproduce it. Also, I am not in a position to buy every user's machine. So, you might want to look elsewhere if you cannot contribute a patch yourself. (That is, unless you want to donate your machine to me.) Also, you have not specified if you are using GPU Processing. Obviously, that is a major factor as it is labeled experimental.
