### ISSUE TITLE
Could someone fix this typo?

### ISSUE THREAD

**Issue by Art-2** [mltframework/shotcut#529]
For `File`;`Archivo`
Just remove the **%**

![imagen](https://user-images.githubusercontent.com/12375357/38157581-917d2928-3445-11e8-92ff-3872b592af30.png)

https://github.com/mltframework/shotcut/blob/ae953f4b1d128dbb1c68467553705b6183c1e446/translations/shotcut_es.ts#L2682

`Xubuntu 17.10; Shotcut 18.03.06`

**Comment by ddennedy** [comment]
I just fixed it on [Transifex](https://www.transifex.com/ddennedy/shotcut/language/es/), which is used to update the .ts files.

**Comment by Art-2** [comment]
Thanks, I did not want to make a mess
