### ISSUE TITLE
Deleting fade in/out audio and video filters does not affect black indicators on timeline clip

### ISSUE THREAD

**Issue by zorbama** [mltframework/shotcut#53]
To reproduce:
1. Add a clip to the timeline.
2. Move to the top left/right corner of the clip until a black spot appears.
3. Click and drag the black spot to add a fade in/out audio and video filters.
4. Open the filters pane.
5. Delete Fade In/Out Audio and Fade In/Out Video.

Expected result:
The black indicator should be removed from the clip.

Actual result:
The black indicator remains in the clip, as though the filters are still in place.

Moving the black indicator back to the edge of the clip does not delete the filters from the list, as well.

**Comment by pez4brian** [comment]
Thanks for the excellent report. I wish every report was as well described as this one.

This is a known issue. I agree that it would be nice if the UI was always left in a consistent state. Unfortunately, the fix is not simple.

**Comment by zorbama** [comment]
I'm glad the report is good. :)

I figured this could be problematic. Fortunately, this isn't a very big issue, so a fix could wait.
