### ISSUE TITLE
Shotcut installation with snap

### ISSUE THREAD

**Issue by gaaooee** [mltframework/shotcut#530]
Hello i am using a tx2 running l4t (ubuntu16.04 xenial arm64) and i want to install shotcut using snap but when i run the command
              sudo snap install shotcut --classic
i get this
              error: snap "shotcut" not found

**Comment by ddennedy** [comment]
Shotcut builds provided by us, including snap, is not available for arm64, and there are no plans at the moment to provide one. You can try to request it as debian package from [deb-multimedia.org](https://www.deb-multimedia.org/dists/sid/main/binary-arm64/package/shotcut).
