### ISSUE TITLE
Crash on Shotcut playing video .mlt, newbie need help ...

### ISSUE THREAD

**Issue by LeaSnapes** [mltframework/shotcut#531]
Excuse me if my english is bad, i'm french and i need help (i'm new on GitHub too so excuse me if i'm rude, impolite or if i just do something that i shouldn't do)

I made a vidéo that night and i saved it and closed it cause i did severals things at once. At 3am when i reopened it in order to continue the montage, it just crash : anytime now i want to open this file, it crash ...

My OS is Windows 8.1 in 64b and the version of Shotcut i'm using is 18.03.06

There is the repport windows gave me of the crash : 

Signature du problème :
  Nom d’événement de problème:	APPCRASH
  Nom de l’application:	shotcut.exe
  Version de l’application:	0.0.0.0
  Horodatage de l’application:	5a9e7ccd
  Nom du module par défaut:	ntdll.dll
  Version du module par défaut:	6.3.9600.18946
  Horodateur du module par défaut:	5a9a3a38
  Code de l’exception:	c00000fd
  Décalage de l’exception:	0000000000030d62
  Version du système:	6.3.9600.2.0.0.768.101
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	8b23
  Information supplémentaire n° 2:	8b2365323f69607d740900642ef71c45
  Information supplémentaire n° 3:	c60b
  Information supplémentaire n° 4:	c60be0f791c7edf15feddff20be649d7

Lire notre déclaration de confidentialité en ligne :
  http://go.microsoft.com/fwlink/?linkid=280262

Si la déclaration de confidentialité en ligne n’est pas disponible, lisez la version hors connexion :
  C:\WINDOWS\system32\fr-FR\erofflps.txt

Any other videos (in .mlt or not) that i want to play with shotcut worded just perfectly fine !! It's just with this video i made last night ... I worked so hard on this, i don't want to start all over again T.T

And i want to understand why it crash most !!

Thanks for the help, and especially for the time you took to read my bad english too ^^

Léa

**Comment by ddennedy** [comment]
Please attach the log file, or if it has information that you want to keep private upload to https://shotcut.org/notes/support-upload/

**Comment by LeaSnapes** [comment]
Done, i just downloaded it on the link you gave me ?
Thanks

**Comment by ddennedy** [comment]
You are affected by this [MLT bug](https://github.com/mltframework/mlt/issues/276). Your project includes itself (MLT XML) in the Playlist. You may have done this by using File > Open MLT XML as Clip and then choosing the project you are editing. I need to prevent this, but it should be fairly obvious that this will cause a problem. 
I edited your XML to remove that self-reference, and I uploaded it to here. Let me know when you have downloaded it; so I can remove it.
[Acteurs de crise - Sandy Hook - Repaired.zip](https://github.com/mltframework/shotcut/files/1886678/Acteurs.de.crise.-.Sandy.Hook.-.Repaired.zip)

**Comment by LeaSnapes** [comment]
ok you can delete it ! Thank for your time ! I come back if i have any problems.

**Comment by alexistaf** [comment]
Excuse me i am not sure i understood the solution here :D Can you guys light me up? I would apprieciate it. !

**Comment by ddennedy** [comment]
@alexistaf Shotcut could crash after opening a project for many reasons. This bug was one reason that was solved after these users supplied their project file, but that will not always work. Sometimes, even when the project file is provided I do not find the reason because I do not have your media files and because I do not have your computer - every computer is different. The solution for these users was put into the code for a new version of Shotcut. Before you open a new bug for your crash, first make sure you are using the latest version, which is currently 18.10.08. After that, be prepared to supply your project file.

**Comment by martyca65** [comment]
An interesting bug has developed with Shotcut running the latest 19.01.27 version. Initially, Shotcut was working on Ubuntu 18.04 LTS but now Shotcut will launch but as soon as I open any video file it shuts down almost immediately. Now here is the curious bit if I double click on the file in my recent list it will bring the file in without Shotcut crashing. Running Nvidia Quadro 620 card on an HP Z420 with an E5-1650 CPU and 32 Gb of ram. The latest version of Shotcut does not have the option of using GPU. So I don't know whether some recent update to Ubuntu has caused an issue with this.

Below is an extract of all warnings from the Shotcut log:
[Warning] <MLT> [ 0x1208e30] The DeckLink drivers not installed.
[Warning] <> libpng warning: iCCP: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG
[Debug  ] <LeapNetworkListener::onDisconnected> Disconnected from Leap Motion 
[Debug  ] <LeapNetworkListener::onError> Leap Motion WebSocket error: "Connection refused" 
[Warning] <> libpng warning: iCCP: known incorrect sRGB profile
[Warning] <> libpng warning: iCCP: known incorrect sRGB profile

There is also a section of Debug talking about WILD TIMESTAMP
