### ISSUE TITLE
erratic size and position values in Text filter [Shotcut 18.03.06 macoOS 10.12.6]

### ISSUE THREAD

**Issue by houdini69** [mltframework/shotcut#532]
Since version 18.03.06 changing size and/or position values in Text filter gives erratic results.
Example. Before
![text_filter before](https://user-images.githubusercontent.com/24533104/38470897-c610f982-3b69-11e8-93d6-0b97acafafb7.png)
After modifying only one value (for example in first column size 1529 changed to 1528)
![text_filter after change](https://user-images.githubusercontent.com/24533104/38470934-4c1290ea-3b6a-11e8-8f1e-6bca6c0ac457.png)
Version 18.01 is Ok

**Comment by ddennedy** [comment]
This probably regressed in the fix for #362 for Windows and Linux. Does your locale use a comma for the decimal separator?

**Comment by houdini69** [comment]
Yes, I do use a comma for the decimal separator (french)!

**Comment by ddennedy** [comment]
As a result of this fix, the next version will offer to repair old MLT XML project files when opening them. That is unfortunate, but it brings the macOS version of Shotcut in line with the behaviour on Windows and Linux, and it removes some ugly hacks we previously made for macOS.
