### ISSUE TITLE
Qt Creator Build Error

### ISSUE THREAD

**Issue by jhson951** [mltframework/shotcut#533]
I am using Qt 5.5.1 (MSVC 2013) and Qt Creator version 3.5.1.
I am using Windows 10 OS.
I am getting errors when I run Build from Qt Creator.
The error is as follows.
"sys / time.h" No such file or directory
"pthread.h" No such file or directory
How can I solve it?

**Comment by ddennedy** [comment]
You cannot use whatever version of Qt that you want. You must use the version we provide as well as the SDK for the Shotcut dependencies here: https://www.shotcut.org/notes/windowsdev/
Further help with building is not available.
