### ISSUE TITLE
Is there a guide to correctly building the shotcut on a MAC?

### ISSUE THREAD

**Issue by leoxxw** [mltframework/shotcut#538]
I'm sorry to bother you, but I want to build the shocut on the MAC, but I haven't seen the relevant document, maybe I haven't found it. Do you have any such documentation? https://www.shotcut.org/notes/windowsdev/, thank you very much.

**Comment by bmatherly** [comment]
You just download and run the script:
https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut.sh
You might need to satisfy a few dependencies.
That's about all the help I can offer.

**Comment by ddennedy** [comment]
I use MacPorts to satisfy the dependencies. Basically, you can install mlt, which installs many of the dependencies. Also, get my build of Qt from here:
https://s3.amazonaws.com/misc.meltymedia/shotcut-build/qt-5.6.1-osx-x86_64.tar.bz2

and extract it into the home directory of the user doing the build.
