### ISSUE TITLE
can achieve partial Mosaic ?

### ISSUE THREAD

**Issue by leoxxw** [mltframework/shotcut#539]
Hello, developer. I know that the latest version of the shotcut increased the Mosaic filter, can achieve partial Mosaic ? Or need to modify the code to do? Thank you very much for your reply.

**Comment by ddennedy** [comment]
This is not a bug.

**Comment by bmatherly** [comment]
I would suggest starting a discussion on the forum:
https://forum.shotcut.org/

**Comment by ddennedy** [comment]
Or even better, search existing forum posts about using the Mask filter to affect other filters.
