### ISSUE TITLE
Undo operations can cause a crash.

### ISSUE THREAD

**Issue by leoxxw** [mltframework/shotcut#540]
![image](https://user-images.githubusercontent.com/33110699/39029402-2d282adc-448e-11e8-8cd8-11dbe8659cad.png)
In my operation, I found that the undo operation would cause an unexpected crash. Is this a bug or am I not correct to modify the code?

**Comment by ddennedy** [comment]
Can you provide steps to reproduce it?

**Comment by leoxxw** [comment]
My basic operation is to open the video file, add the time line, add the filter, cut the time line and so on, and then click the undo button quickly, which is likely to crash unexpectedly.

**Comment by vipseixas** [comment]
Same problem, just add a video, cut it twice and undo twice:

[Debug  ] <Timeline::SplitCommand::undo> trackIndex 0 clipIndex 0 position 471 
Segmentation fault (core dumped)

**Comment by ddennedy** [comment]
@vipseixas Thank you, but I was not able to reproduce it. I tried repeatedly with and without GPU Effects turned on. Maybe you can produce a gdb backtrace or debug it and submit a patch.
