### ISSUE TITLE
flatpak: Shotcut is now available on Flathub

### ISSUE THREAD

**Issue by eszlari** [mltframework/shotcut#544]
I want to inform you, that Shotcut is now available on Flathub:
https://flathub.org/apps/details/org.shotcut.Shotcut

build manifest:
https://github.com/flathub/org.shotcut.Shotcut

You will need at least flatpak version 0.11.4 to have it work correctly.

**Comment by ddennedy** [comment]
Thanks, and good job!

This is using an incompatible (run time, not compile time) version of Movit, and we have not yet fully tested with those versions of Qt and QtWebKit, although those are my targets for the June release; so, keep them there for now. Can you please switch Movit to https://github.com/ddennedy/movit until you see me mention a new release has upgraded to Movit master (that is a goal for this year)?

Also, why are you replacing usage of qmelt with melt? That is inadvisable especially for certain combinations such as Movit and WebVfx. I think instead, we should have webvfx install the qmelt it builds, and continue to use that.

Lastly, you have some bad MLT configure options because you probably think they do something other than actual. In order to use LADSPA and JACK, you must remove "--disable-jackrack". It provides more than Jack-Rack integration. It contains all LADSPA- and JACK-related code in MLT. Similarly, in order to do deinterlacing, which is rather important, you must remove "--disable-xine" as that contains deinterlace code from xine (plus new code for YADIF). It does not require or enable actual xine integration.

**Comment by ddennedy** [comment]
Note to myself and others. Here is the app page on Flathub:
https://flathub.org/apps/details/org.shotcut.Shotcut

**Comment by eszlari** [comment]
> we have not yet fully tested with those versions of Qt and QtWebKit

At the moment flatpak only provides 5.9 and 5.10 as pre-build runtimes. One could self-compile and bundle Qt, but I would like to avoid that for obvious reasons.

> Can you please switch Movit to https://github.com/ddennedy/movit until you see me mention a new release has upgraded to Movit master (that is a goal for this year)?

I guess the last commit of the "shotcut" branch?!

> Also, why are you replacing usage of qmelt with melt?

It was some time ago, but if I remember correctly, when building WebVfx, I couldn't make it find MLT's source tree (with MLT_SOURCE). Couldn't you use git's submodule feature in MLT for that?

>  You can remove all the --enable-{module} MLT configure options.

I wanted to be explicit, in case a MLT module gets removed.

**Comment by eszlari** [comment]
By the way, if you want to build and test this flatpak locally, that's pretty easy:

```
$ git clone https://github.com/flathub/org.shotcut.Shotcut
$ cd org.shotcut.Shotcut
$ flatpak-builder --install --ccache build_dir org.shotcut.Shotcut.json
$ flatpak run org.shotcut.Shotcut
```

**Comment by eszlari** [comment]
Of course you can have commit access to the repo, see:

https://github.com/flathub/flathub/wiki/App-Submission#someone-else-has-put-my-app-on-flathubwhat-do-i-do

**Comment by ddennedy** [comment]
> I guess the last commit of the "shotcut" branch?!

Yes

> I wanted to be explicit, in case a MLT module gets removed.

It does not hurt, but also these are not actually options recognized by the MLT configure script.

**Comment by eszlari** [comment]
When trying to compile movit from https://github.com/ddennedy/movit, I get the following error:
```
make: *** [Makefile:130: effect_chain_test.o] Error 1
In file included from gamma_expansion_effect_test.cpp:9:0:
test_util.h:31:116: error: ‘YCbCrOutputSplitting’ has not been declared
  void add_ycbcr_output(const ImageFormat &format, OutputAlphaFormat alpha_format, const YCbCrFormat &ycbcr_format, YCbCrOutputSplitting output_splitting = YCBCR_OUTPUT_INTERLEAVED);
                                                                                                                    ^~~~~~~~~~~~~~~~~~~~
test_util.h:31:156: error: ‘YCBCR_OUTPUT_INTERLEAVED’ was not declared in this scope
  void add_ycbcr_output(const ImageFormat &format, OutputAlphaFormat alpha_format, const YCbCrFormat &ycbcr_format, YCbCrOutputSplitting output_splitting = YCBCR_OUTPUT_INTERLEAVED);
                                                                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:130: gamma_expansion_effect_test.o] Error 1
```

**Comment by ddennedy** [comment]
Use target 'libmovit.la' to skip building the Movit demo app and unit tests:
https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut.sh#L1510

**Comment by ddennedy** [comment]
Also, I just pushed a fix for the compile error into my branch.

**Comment by eszlari** [comment]
MLT configure options simplified:
https://github.com/flathub/org.shotcut.Shotcut/commit/53c20223125457e4e46b77f8bec627f46c7d81d3

movit switched:
https://github.com/flathub/org.shotcut.Shotcut/commit/22441c81b012b6248f1f7551d4e492c15a65bb35

**Comment by eszlari** [comment]
Should I add gtk2?

**Comment by ddennedy** [comment]
I tested this out, and it basically works good. I would need to swap out my x11 driver again to test GPU; so, I skipped that for now. There will be a new release tomorrow hopefully. Then, I will list this option on the downloads page and close this.

**Comment by eszlari** [comment]
When you do the release, could you add a release entry to the appdata.xml file?

Maybe you could also incorporate the other post-install steps from the flatpak json file into the buildsystem.

**Comment by ddennedy** [comment]
>  When you do the release, could you add a release entry to the appdata.xml file?

I do not feel like maintaining that. 

> Maybe you could also incorporate the other post-install steps from the flatpak json file into the buildsystem.

Many of the additional installed things are flatpak-specific by requiring the "org.shotcut." prefix. The lrelease step is done as part of build-shotcut.sh and serves my needs.  If someone really wants these things, they should submit a patch and not ask me to do it for them.

**Comment by ddennedy** [comment]
This is listed on the downloads page now: https://www.shotcut.com/download/

**Comment by eszlari** [comment]
When I try to compile 18.05 I get:
```

/run/build/shotcut/src/widgets/avformatproducerwidget.cpp: In member function ‘void AvformatProducerWidget::onFrameDisplayed(const SharedFrame&)’:
/run/build/shotcut/src/widgets/avformatproducerwidget.cpp:261:97: error: ‘mlt_channel_layout_default’ was not declared in this scope
                 const char* layout = mlt_channel_layout_name(mlt_channel_layout_default(channels));
                                                                                                 ^
/run/build/shotcut/src/widgets/avformatproducerwidget.cpp:261:98: error: ‘mlt_channel_layout_name’ was not declared in this scope
                 const char* layout = mlt_channel_layout_name(mlt_channel_layout_default(channels));
                                                                                                  ^
make[1]: *** [Makefile:2654: avformatproducerwidget.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/run/build/shotcut/_flatpak_build/src'
make: *** [Makefile:98: sub-src-make_first] Error 2

```

**Comment by eszlari** [comment]
> This is listed on the downloads page now: https://www.shotcut.com/download/

@ddennedy Small correction - Flathub actually hosts binaries for:

- x86_32
- x86_64
- arm
- arm64

**Comment by eszlari** [comment]
Okay, I got it, it compile with MLT git.

**Comment by ericfont** [comment]
Just tried out the flatpak build and found jack doesn't work...so just bumping to second the request to build with jack enabled.

**Comment by ddennedy** [comment]
jack2

**Comment by ericfont** [comment]
I made issue on the flathub repo regarding jack: https://github.com/flathub/org.shotcut.Shotcut/issues/4

**Comment by frdbr** [comment]
> Can you please switch Movit to https://github.com/ddennedy/movit until you see me mention a new release has upgraded to Movit master (that is a goal for this year)?

Hi Dan, should we still use your build of Movit (1.2) or can we switch to latest release (1.6.3)?

**Comment by ddennedy** [comment]
Shotcut uses my fork of Movit for a very special reason: video display integrates with Qt Quick for on-screen controls, which limits the OpenGL version. I cannot comment on what Kdenlive should do.
