### ISSUE TITLE
Build date as version string in about dialog

### ISSUE THREAD

**Issue by eszlari** [mltframework/shotcut#546]
When building shotcut, the resulting binary displays under `Help > About Shotcut` the build date instead of the actual version from the tarball as a version string.

**Comment by ddennedy** [comment]
The versioning is based on the app bundle, which includes dependencies, and not just Shotcut source tree. IOW, the build identifier (date) is just as important as the Shotcut source tree when it comes to understanding the state of things. This also helps me to differentiate between official and unofficial builds. Lastly, my process is that there are nightly automated builds, whose version number goes into the About dialog, and I pick one to release when timing makes sense.
IOW, this is currently buy design, and I have no plans to change this at this time.
