### ISSUE TITLE
AppImage does not work in Fedora 17

### ISSUE THREAD

**Issue by stiratel** [mltframework/shotcut#552]
The program does not have enough libraries:

`$ ./Shotcut-18.05.glibc2.14-x86_64.AppImage
fuse: warning: library too old, some operations may not work
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, wayland-egl, wayland, xcb.

Reinstalling the application may fix this problem.
/tmp/.mount_ShotcuE5sY4d/usr/bin/shotcut: line 15: 22834 Аварийный останов         (core dumped) bin/shotcut "$@"
`

**Comment by ddennedy** [comment]
The AppImage is just a different format as the .zip, both of which require at least Fedora 21, as stated on the downloads page.

**Comment by ddennedy** [comment]
Fedora 17 is not supported.
See the minimum versions on the [downloads page](https://shotcut.com/download/). The FAQ about glibc version is wrong and will be updated.
