### ISSUE TITLE
Regression: Filters are not applied properly to tracks in 18.05

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#555]
Hello,

I could reproduce the following issue with the gain and brightness filters. It probably also affects other (keyframed?) filters.

Repro:
- Create a new project with one track.
- Open some media file with video and audio in source viewer.
- Append source media to track.
- Add some filters (e.g. gain, brightness) to the track (not the clip).
- Modify the parameters of the filters so that some change is audible and/or visible.
- Add the source media to the track again so you effectively have two copies of the media on the timeline.

Expected:
- The track filters should be applied on both clips over the whole timeline.

Observed:
- The filters are only applied to the first clip. The second clip is unchanged.
- The filter parameters can only be modified when the playhead is over the first clip.
- When the playhead is over the second clip, the filter parameters reset themselves on playing.

**Comment by ddennedy** [comment]
Thanks for finding, the filter duration is not being updated correctly.

**Comment by ddennedy** [comment]
Please be aware that filter trimming in and out points will not be preserved when the timeline duration changes. It is not clear whether the intention of these are relative or absolutely positioned.

Also, simple keyframes are not adjusted accordingly. I realized I need to figure out a way for filters to provide simple animation functions, which are unique to each filter, to the timeline manipulation class. Currently, only the fade in and out filters get adjusted automatically when changing things on the timeline.
