### ISSUE TITLE
Forward incompatibility of fade in/out filters

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#556]
Hello,

I'm not sure if forward compatibility is a priority. But I noticed a glitch when trying to open a project created using 18.05 in 18.03. Even if it's not expected to work, I want to make sure that there's not more to it than a glitch.

To reproduce, create a simple project with one clip on the timeline with 18.05. Add a fade out filter at the end (I used the handles on the clip for that). When opening this project with 18.03, the fade effect is shown in the timeline as being applied over the whole length of the clip even though the actual fade effect in the video seems to work correctly.

Indeed, there's a difference in the resulting XML:

18.03:
```
    <filter id="filter0" in="00:00:12.217" out="00:00:12.700">
      <property name="opacity">0~=1; 29=0</property>
      <property name="alpha">1</property>
      <property name="mlt_service">movit.opacity</property>
      <property name="shotcut:filter">fadeOutMovit</property>
    </filter>
    <filter id="filter1" in="00:00:12.217" out="00:00:12.700">
      <property name="window">75</property>
      <property name="max_gain">20dB</property>
      <property name="mlt_service">volume</property>
      <property name="shotcut:filter">fadeOutVolume</property>
      <property name="gain">1</property>
      <property name="end">0</property>
    </filter>
```

18.05:
```
    <filter id="filter0" out="00:00:12.700">
      <property name="opacity">733~=1;762=0</property>
      <property name="alpha">1</property>
      <property name="mlt_service">movit.opacity</property>
      <property name="shotcut:filter">fadeOutMovit</property>
      <property name="shotcut:animOut">30</property>
    </filter>
    <filter id="filter1" out="00:00:12.700">
      <property name="window">75</property>
      <property name="max_gain">20dB</property>
      <property name="level">733=0;762=-60</property>
      <property name="mlt_service">volume</property>
      <property name="shotcut:filter">fadeOutVolume</property>
      <property name="shotcut:animOut">30</property>
    </filter>
```

**Comment by ddennedy** [comment]
Backwards compatibility is not supported. There is no way for old versions to show keyframes, and fades had to change in order to be compatible with keyframes. I cannot change an old version to accomodate the changes in XML. What is important is being able to open a project in an older version and use it correctly in a newer version.
