### ISSUE TITLE
Video Export Failed (Windows 10 64bit; Shotcut 32bit 18.05.08).

### ISSUE THREAD

**Issue by HeartbreakSurvivor** [mltframework/shotcut#557]
Hello, I just installed the latest version of the Shotcut. And I just do some simple video editing and it's failed. Here is the xml and the log.

```xml
<?xml version='1.0' encoding='utf-8'?>
<mlt version="6.7.0" producer="main bin" LC_NUMERIC="en_US" title="Shotcut version 18.05.08" root="C:\Program Files\Shotcut">
  <profile width="1920" display_aspect_num="16" height="1080" colorspace="709" progressive="1" frame_rate_num="25" description="HD 1080p 25 fps" sample_aspect_den="1" display_aspect_den="9" sample_aspect_num="1" frame_rate_den="1"/>
  <consumer crf="21" movflags="+faststart" f="mp4" g="125" rescale="bilinear" progressive="1" channels="2" aspect="1.77778" bf="3" preset="fast" ab="384k" real_time="-4" deinterlace_method="yadif" r="25" vcodec="libx264" threads="0" mlt_service="avformat" target="D:/rrr.mp4" top_field_first="2" height="1080" ar="48000" width="1920" acodec="aac"/>
  <producer out="00:00:29.960" in="00:00:00.000" title="Anonymous Submission" id="producer0">
    <property name="length">00:00:30.000</property>
    <property name="eof">pause</property>
    <property name="resource">D:/后会无期.HD1024高清国语中字.mp4</property>
    <property name="audio_index">1</property>
    <property name="video_index">0</property>
    <property name="mute_on_pause">0</property>
    <property name="mlt_service">avformat-novalidate</property>
    <property name="seekable">1</property>
    <property name="aspect_ratio">1</property>
    <property name="shotcut:hash">8abfdb1910586f3d1dc055fb141334e2</property>
    <property name="ignore_points">0</property>
    <property name="shotcut:caption">后会无期.HD1024高清国语中字.mp4</property>
    <property name="shotcut:detail">D:/后会无期.HD1024高清国语中字.mp4</property>
    <property name="shotcut:comment"/>
    <property name="shotcut:skipConvert">1</property>
    <property name="global_feed">1</property>
    <property name="xml">was here</property>
  </producer>
  <producer out="03:59:59.960" in="00:00:00.000" title="Anonymous Submission" id="producer1">
    <property name="length">04:00:00.000</property>
    <property name="eof">pause</property>
    <property name="resource">D:/FFmpegKit/TestPic/14182277_xl.jpg</property>
    <property name="ttl">1</property>
    <property name="aspect_ratio">1</property>
    <property name="progressive">1</property>
    <property name="seekable">1</property>
    <property name="mlt_service">qimage</property>
    <property name="shotcut:hash">f4a264a5b72e41eb19eb31d59daeb87c</property>
    <property name="ignore_points">0</property>
    <property name="global_feed">1</property>
    <property name="xml">was here</property>
  </producer>
  <producer out="03:59:59.960" in="00:00:00.000" title="Anonymous Submission" id="producer2">
    <property name="length">04:00:00.000</property>
    <property name="eof">pause</property>
    <property name="resource">D:/FFmpegKit/TestPic/4a4768dfed35099ebde9084cf7ace2c6.jpg</property>
    <property name="ttl">1</property>
    <property name="aspect_ratio">1</property>
    <property name="progressive">1</property>
    <property name="seekable">1</property>
    <property name="loop">1</property>
    <property name="mlt_service">pixbuf</property>
    <property name="shotcut:hash">e43884519d360a789cd0bc583ad47104</property>
    <property name="ignore_points">0</property>
    <property name="global_feed">1</property>
    <property name="xml">was here</property>
  </producer>
  <playlist title="Shotcut version 18.05.08" id="main bin" autoclose="1">
    <property name="shotcut:projectAudioChannels">2</property>
    <property name="xml_retain">1</property>
    <entry out="00:00:29.960" in="00:00:00.000" producer="producer0"/>
    <entry out="00:00:05.240" in="00:00:00.000" producer="producer1"/>
    <entry out="00:00:05.240" in="00:00:00.000" producer="producer2"/>
  </playlist>
  <producer out="00:00:12.960" in="00:00:00.000" id="black">
    <property name="length">00:00:13.000</property>
    <property name="eof">pause</property>
    <property name="resource">black</property>
    <property name="aspect_ratio">1</property>
    <property name="mlt_service">color</property>
    <property name="set.test_audio">0</property>
  </producer>
  <playlist id="background" autoclose="1">
    <entry out="00:00:12.960" in="00:00:00.000" producer="black"/>
  </playlist>
  <producer out="00:00:29.960" in="00:00:00.000" title="Anonymous Submission" id="producer3">
    <property name="length">00:00:30.000</property>
    <property name="eof">pause</property>
    <property name="resource">D:/后会无期.HD1024高清国语中字.mp4</property>
    <property name="audio_index">1</property>
    <property name="video_index">0</property>
    <property name="mute_on_pause">0</property>
    <property name="mlt_service">avformat-novalidate</property>
    <property name="seekable">1</property>
    <property name="aspect_ratio">1</property>
    <property name="shotcut:hash">8abfdb1910586f3d1dc055fb141334e2</property>
    <property name="ignore_points">0</property>
    <property name="shotcut:caption">后会无期.HD1024高清国语中字.mp4</property>
    <property name="shotcut:detail">D:/后会无期.HD1024高清国语中字.mp4</property>
    <property name="shotcut:comment"/>
    <property name="shotcut:skipConvert">1</property>
    <property name="global_feed">1</property>
    <property name="xml">was here</property>
    <filter out="00:00:29.960" id="filter0">
      <property name="background">colour:0</property>
      <property name="mlt_service">affine</property>
      <property name="shotcut:filter">affineSizePosition</property>
      <property name="transition.fill">1</property>
      <property name="transition.distort">0</property>
      <property name="transition.rect">0 149 1920 756 1</property>
      <property name="transition.valign">middle</property>
      <property name="transition.halign">center</property>
      <property name="transition.threads">0</property>
    </filter>
  </producer>
  <playlist id="playlist0" autoclose="1">
    <property name="shotcut:video">1</property>
    <property name="shotcut:name">V1</property>
    <entry out="00:00:12.960" in="00:00:00.000" producer="producer3"/>
  </playlist>
  <producer out="00:00:05.240" in="00:00:00.000" title="Anonymous Submission" id="producer4">
    <property name="length">04:00:00.000</property>
    <property name="eof">pause</property>
    <property name="resource">D:/FFmpegKit/TestPic/4a4768dfed35099ebde9084cf7ace2c6.jpg</property>
    <property name="ttl">1</property>
    <property name="aspect_ratio">1</property>
    <property name="progressive">1</property>
    <property name="seekable">1</property>
    <property name="loop">1</property>
    <property name="mlt_service">pixbuf</property>
    <property name="shotcut:hash">e43884519d360a789cd0bc583ad47104</property>
    <property name="ignore_points">0</property>
    <property name="global_feed">1</property>
    <property name="xml">was here</property>
  </producer>
  <playlist id="playlist1" autoclose="1">
    <property name="shotcut:video">1</property>
    <property name="shotcut:name">V2</property>
    <blank length="00:00:02.840"/>
    <entry out="00:00:05.240" in="00:00:00.000" producer="producer4"/>
  </playlist>
  <tractor out="00:00:12.960" global_feed="1" in="00:00:00.000" title="Shotcut version 18.05.08" id="tractor0">
    <property name="shotcut">1</property>
    <property name="shotcut:projectAudioChannels">2</property>
    <track producer="background"/>
    <track producer="playlist0"/>
    <track producer="playlist1"/>
    <transition id="transition0">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
      <property name="mlt_service">mix</property>
      <property name="always_active">1</property>
      <property name="sum">1</property>
    </transition>
    <transition id="transition1">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
      <property name="version">0.9</property>
      <property name="mlt_service">frei0r.cairoblend</property>
      <property name="disable">1</property>
    </transition>
    <transition id="transition2">
      <property name="a_track">0</property>
      <property name="b_track">2</property>
      <property name="mlt_service">mix</property>
      <property name="always_active">1</property>
      <property name="sum">1</property>
    </transition>
    <transition id="transition3">
      <property name="a_track">1</property>
      <property name="b_track">2</property>
      <property name="version">0.9</property>
      <property name="mlt_service">frei0r.cairoblend</property>
      <property name="disable">0</property>
    </transition>
  </tractor>
</mlt>

```
`
[libx264 @ 08ad60e0] using SAR=1/1
[libx264 @ 08ad60e0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 08ad60e0] profile High, level 4.0
[libx264 @ 08ad60e0] 264 - core 152 r2854 e9a5903 - H.264/MPEG-4 AVC codec - Copyleft 2003-2017 - http://www.videolan.org/x264.html - options: cabac=1 ref=2 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=6 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=12 lookahead_threads=2 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=125 keyint_min=12 scenecut=40 intra_refresh=0 rc_lookahead=30 rc=crf mbtree=1 crf=21.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
[h264 @ 0e9a66e0] Reinit context to 1024x416, pix_fmt: yuv420p
[h264 @ 0e9a7980] Reinit context to 1024x416, pix_fmt: yuv420p
[h264 @ 245b8440] Reinit context to 1024x416, pix_fmt: yuv420p
[producer avformat] audio: total_streams 1 max_stream 1 total_channels 2 max_channels 2
[producer avformat-novalidate] D:/后会无期.HD1024高清国语中字.mp4
    checking VFR: pkt.duration 1000
[h264 @ 0e9d9080] Reinit context to 1024x416, pix_fmt: yuv420p
[h264 @ 0e9d9080] Reinit context to 1024x416, pix_fmt: yuv420p
[mp4 @ 08c434e0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mp4 @ 08c434e0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[h264 @ 0e9d9080] Reinit context to 1024x416, pix_fmt: yuv420p
[h264 @ 0e9d9080] Reinit context to 1024x416, pix_fmt: yuv420p
[h264 @ 0e9d9080] Reinit context to 1024x416, pix_fmt: yuv420p
Current Frame:         99, percentage:         30
Current Frame:        100, percentage:         30
Current Frame:        101, percentage:         31
[h264 @ 0e9d9080] Reinit context to 1024x416, pix_fmt: yuv420p
Current Frame:        102, percentage:         31
Current Frame:        104, percentage:         32
Current Frame:        105, percentage:         32
Current Frame:        106, percentage:         32
Current Frame:        107, percentage:         32
Current Frame:        108, percentage:         33
Current Frame:        109, percentage:         33
Current Frame:        110, percentage:         33
Current Frame:        112, percentage:         34
Current Frame:        114, percentage:         35
Current Frame:        115, percentage:         35
Current Frame:        116, percentage:         35
[h264 @ 0e9d9080] Reinit context to 1024x416, pix_fmt: yuv420p
Current Frame:        117, percentage:         36
Current Frame:        118, percentage:         36
Failed with exit code -1073741819

`

What's going wrong with this version of Shotcut? Cause I have done the same operation on the Shotcut(18.03.06) and everything goes well.

**Comment by HDSQmid** [comment]
@HeartbreakSurvivor 
You can find out what is happening when the error occurs by using the log and finding the current frame, dividing it by the framerate you have chosen and navigating to the relative time on the timeline. That could help with figuring out what is going wrong

**Comment by ddennedy** [comment]
One thing that is strange about the XML is that some JPEGs are being loaded with the MLT qimage (Qt5) producer and others are using pixbuf (GTK2). qimage is preferred now by MLT, but pixbuf will be used if qimage fails to load the image. There was a [recent crash fix in MLT qimage](https://github.com/mltframework/mlt/commit/f6f9d36e2bf09c72e41bdab68308dfc3a1badc5a#diff-146fe0ec2906190e9b58141da4483ecb) that might be at play here.

**Comment by HeartbreakSurvivor** [comment]
@HDSQmid Thanks, that will be a good way to find out the problem. And I found the crash happened when dealing with the high-resolution image.  This image "14182277_xl.jpg" is 3456x2304.

**Comment by HDSQmid** [comment]
@HeartbreakSurvivor I had a similar issue with an earlier video that I made. Have you tried substituting that image for a different image, or using software such as ms paint to change the format to PNG or something similar? that was the workaround I used

**Comment by ddennedy** [comment]
There have been some fixes recently for images and the Size and Position filter. Please try this nightly build:
http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-win64-180517.zip

**Comment by ddennedy** [comment]
Why are you using 32-bit Shotcut on 64-bit Windows?

**Comment by HeartbreakSurvivor** [comment]
@HDSQmid  Yes, I tried. After replacing the large image with another normal image, it works well. So I think  the problem is in the way MLT dealing with large images.

**Comment by HeartbreakSurvivor** [comment]
@ddennedy  Uhh... It's a little bit complicated, but I have to say It is  indeed a bug. And I will install the 64-bit Shotcut to test if it has the same problem.

**Comment by HDSQmid** [comment]
If it is a large image and you're using 32-bit shotcut, it may use too much RAM. Theoretically, 32-bit applications can use up to 4GB of RAM, but due to some weird historical thing, they only end up using 2GB, and you need to apply a 4GB patch in order for them to use the full 4GB (although 64-bit programs are always better)
But anyway, I'd say what is happening is that Qmelt is getting a BAD_ALLOC error, in other words, it can't get enough RAM because of this. Try it on 64-bit shotcut and see if it works...

**Comment by ddennedy** [comment]
> I don't know if the qmelt.exe, attached by this version of Shotcut(18.05.08), has that two patches or not.

Yes, Shotcut 18.05.08 includes those patches.
Oh, I just thought of something else. The Parallel processing option in Export uses quite a bit more memory. I should disable that on 32-bit. 
I am taking a look at the project you provided now, but I am not setup for building and debugging 32-bit at the workstation. That is mainly just a compile target. I do not even really test it. So, it might take a while if I ever get around to it.

**Comment by ddennedy** [comment]
One thing I noticed while working with your files is that Shotcut loads screenshot.jpg with pixbuf instead of qimage (preferred as of 18.03). When I looked at this file with Media Info, it told me it is PNG. So, I changed the filename extension to .png and now qimage loads it. It looks like Qt is sensitive to MIME type or filename extension. That answers some of that mystery I mentioned before.

**Comment by ddennedy** [comment]
I reproduced the export crash with the 64-bit build of v18.05.08. The export does not crash with my development version of 64-bit for Windows. So, I made last night's 32-bit build available for downoload:
http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-win32-180518.zip

Export crashed with it. Then, I turned off Parallel processing, and it succeeds.
It is quite possible that the change in 71167e65b4ac126546b7524e406bd81f991c2abf to reduce memory usage by turning off memory pooling exposes more pointer bugs because memory pool keeps more address space pinned within the process. I think some of these bugs have been fixed lately.

I ran the above 32-bit 18.05.18 build of qmelt.exe in a debugger against the project with parallel processing enabled (`-consumer avformat:test.mp4 real_time=`**-2**), and I got this in the log just before crash:
`x264 [error]: malloc of size 11453376 failed`
It should be noted as well that codec threads will also use more memory, and the automatic mode chooses by cpu count, and I have 16 logical CPUs.
Again, if I disable parallel processing (`-consumer avformat:test.mp4 real_time=`**-1**) it succeeds. Pointer problems are more likely to trigger in a debugger session, but not as good as address sanitizing or valgrind. Another easy experiment to make without having a debug build and development project setup for 32-bit: enable parallel processing but reduce x264 threads (`-consumer avformat:test.mp4 real_time=-2 threads=3`). That succeeds as well.

So, this is still looking like issues with memory constraints and consumption especially with multiple threads. It should be noted as well that many decoders in FFmpeg now use multiple threads, and there are new multi-threaded [slice-based image processing routines in MLT](https://www.mltframework.org/blog/v6.6.0_released/). The combination of all these multi-threaded processing improvements in FFmpeg and MLT also explains why an older version like 17.02 did not have as much problem. There is a MLT environment variable to control the max number of slices: [MLT_SLICES_COUNT](https://github.com/mltframework/mlt/blob/master/src/framework/mlt_slices.h#L29).
Unfortunately, I have not found anything like that for FFmpeg decoder threads yet. A property would need to be set on each MLT avformat producer object, which would be difficult to manage. Now, if I run with `MLT_SLICES_COUNT=1 qmelt ... -consumer avformat:test.mp4 real_time=0 threads=1` to reduce multi-threading without touching producers, qmelt does not use more than 670 MiB RAM. `real_time=0` tells MLT to not use a separate rendering thread; the rendering takes place on the encoding thread. Taking this to another level and adding `<property name="threads">1</property>` to each avformat-novalidate producer in the MLT XML file, and RAM usage does exceed 570 MiB. Here is another MLT environment variable MLT_AVFORMAT_SLICED_PIXFMT_DISABLE, and if I set that to 1. Oh, and another thing, MLT playlist can have "autoclose="1"' property which closes producers after they have ended strictly for sequential processing where you know random seeking will not occur. Shotcut already puts that into the XML for export. Adding those two things brings RAM usage down to 556 MiB! Not so bad now, eh?
To resolve this bug, I will make Shotcut limit thread usage on 32-bit.

**Comment by HeartbreakSurvivor** [comment]
> Oh, I just thought of something else. The Parallel processing option in Export uses quite a bit more memory. I should disable that on 32-bit.  

 As you know, disable the Parallel processing will lead a video export speedlose. Can we just disable the Parallel processing when dealing with large images or some cases that will use a lot of memory? 

> One thing I noticed while working with your files is that Shotcut loads screenshot.jpg with pixbuf instead of qimage (preferred as of 18.03).

Uhh... Actually I didn't use that screenshot.jpg, I just do a screenshot to show you my timeline layout. But I'm glad that you have sloved your problem. And I can infer from your conclusion that the qimage loads a image according to its file extension instead of its real foramt, which may be a potential bug.

**Comment by ddennedy** [comment]
>Can we just disable the Parallel processing when dealing with large images or some cases that will use a lot of memory?

No, that is too challenging to make a good heuristic and adds the overhead of an initial analysis pass, and cannot be done dynamiclly. 32-bit users must suffer the consequences of continuing to use 32-bits and living in the past.

> So will you still turn off memory pooling and fix bugs over successive versions

Yes

> Uhh... Actually I didn't use that screenshot.jpg

I know, but I did by chance, which is when I noticed that it loaded with pixbuf instead of qimage.

**Comment by HeartbreakSurvivor** [comment]
@ddennedy Okay, get it. Thank you once again for you reply.

**Comment by pipecleaner** [comment]
On my Win 7 32bit Intel with 4GB RAM using Shotcut 18.05 the by HeartbreakSurvivor ( you are not alone ) provided "shotcut-crash.mtl" file will open with a request from Shotcut for repair and autosave. The repaired file will not work immediately but if the "shotcut-crash Repaired.mlt" file is closed and reopened Shotcut will ask for alternative paths for the project files (the two images plus bunny.mp4).The now again repaired file ("shotcut-crash Repaired Repaired.mlt") will when opened playback and export as 1280x720 .mp4 without problems on this machine (with laggy playback). The standalone nightly may 18 build also behave OK as long as the .mtl file is valid.

**Comment by pipecleaner** [comment]
Addendum: I meant Shotcut export fine also as 1920x1080.With project files in c:/Temp the double repaired .mlt is as follows

`<?xml version="1.0" encoding="UTF-8"?>
<mlt LC_NUMERIC="da_DK" version="6.7.0" title="Shotcut version 18.05.08" producer="main bin">
  <profile description="HD 1080p 25 fps" width="1920" height="1080" progressive="1" sample_aspect_num="1" sample_aspect_den="1" display_aspect_num="16" display_aspect_den="9" frame_rate_num="25" frame_rate_den="1" colorspace="709"/>
  <producer id="producer1" title="Anonymous Submission" in="00:00:00,000" out="03:59:59,960">
    <property name="length">04:00:00,000</property>
    <property name="eof">pause</property>
    <property name="resource">C:/Temp/3a2ea1ea94b065fe78d8deb2a56aabbe.jpg</property>
    <property name="ttl">1</property>
    <property name="aspect_ratio">1</property>
    <property name="progressive">1</property>
    <property name="seekable">1</property>
    <property name="mlt_service">qimage</property>
    <property name="global_feed">1</property>
    <property name="xml">was here</property>
    <property name="shotcut:hash">61fa25637f9cd89eab27d30797ca272e</property>
  </producer>
  <producer id="producer2" title="Anonymous Submission" in="00:00:00,000" out="03:59:59,960">
    <property name="length">04:00:00,000</property>
    <property name="eof">pause</property>
    <property name="resource">C:/Temp/14182277_xl.jpg</property>
    <property name="ttl">1</property>
    <property name="aspect_ratio">1</property>
    <property name="progressive">1</property>
    <property name="seekable">1</property>
    <property name="mlt_service">qimage</property>
    <property name="global_feed">1</property>
    <property name="xml">was here</property>
    <property name="shotcut:hash">f4a264a5b72e41eb19eb31d59daeb87c</property>
  </producer>
  <producer id="producer3" title="Anonymous Submission" in="00:00:00,000" out="00:05:00,000">
    <property name="length">00:05:00,040</property>
    <property name="eof">pause</property>
    <property name="resource">C:/Temp/bunny.mp4</property>
    <property name="mute_on_pause">0</property>
    <property name="mlt_service">avformat-novalidate</property>
    <property name="seekable">1</property>
    <property name="aspect_ratio">1</property>
    <property name="global_feed">1</property>
    <property name="xml">was here</property>
    <property name="shotcut:hash">5c2831cf9f1f579a12cf24a911bf4829</property>
  </producer>
  <playlist id="main bin">
    <property name="xml_retain">1</property>
    <entry producer="producer1" in="00:00:00,000" out="00:00:05,240"/>
    <entry producer="producer2" in="00:00:00,000" out="00:00:05,240"/>
    <entry producer="producer3" in="00:00:00,000" out="00:05:00,000"/>
  </playlist>
  <producer id="black" in="00:00:00,000" out="00:00:18,400">
    <property name="length">00:00:18,440</property>
    <property name="eof">pause</property>
    <property name="resource">black</property>
    <property name="aspect_ratio">1</property>
    <property name="mlt_service">color</property>
    <property name="set.test_audio">0</property>
  </producer>
  <playlist id="background">
    <entry producer="black" in="00:00:00,000" out="00:00:18,400"/>
  </playlist>
  <producer id="producer5" title="Anonymous Submission" in="00:00:00,000" out="00:05:00,000">
    <property name="length">00:05:00,040</property>
    <property name="eof">pause</property>
    <property name="resource">C:/Temp/bunny.mp4</property>
    <property name="mute_on_pause">0</property>
    <property name="mlt_service">avformat-novalidate</property>
    <property name="seekable">1</property>
    <property name="aspect_ratio">1</property>
    <property name="global_feed">1</property>
    <property name="xml">was here</property>
    <property name="shotcut:hash">5c2831cf9f1f579a12cf24a911bf4829</property>
    <property name="shotcut:caption">bunny.mp4</property>
    <property name="shotcut:detail">C:/Temp/bunny.mp4</property>
    <filter id="filter0" out="00:00:18,400">
      <property name="start">1</property>
      <property name="level">1</property>
      <property name="mlt_service">brightness</property>
      <property name="shotcut:filter">fadeInBrightness</property>
      <property name="alpha">0=0;45=1</property>
      <property name="shotcut:animIn">46</property>
    </filter>
    <filter id="filter1" out="00:00:18,400">
      <property name="start">1</property>
      <property name="level">1</property>
      <property name="mlt_service">brightness</property>
      <property name="shotcut:filter">fadeOutBrightness</property>
      <property name="alpha">410=1;460=0</property>
      <property name="shotcut:animOut">51</property>
    </filter>
  </producer>
  <playlist id="playlist0">
    <property name="shotcut:video">1</property>
    <property name="shotcut:name">V1</property>
    <entry producer="producer5" in="00:00:00,000" out="00:00:18,400"/>
  </playlist>
  <producer id="producer6" title="Anonymous Submission" in="00:00:00,000" out="00:00:05,240">
    <property name="length">04:00:00,000</property>
    <property name="eof">pause</property>
    <property name="resource">C:/Temp/3a2ea1ea94b065fe78d8deb2a56aabbe.jpg</property>
    <property name="ttl">1</property>
    <property name="aspect_ratio">1</property>
    <property name="progressive">1</property>
    <property name="seekable">1</property>
    <property name="mlt_service">qimage</property>
    <property name="global_feed">1</property>
    <property name="xml">was here</property>
    <property name="shotcut:hash">61fa25637f9cd89eab27d30797ca272e</property>
    <filter id="filter2" out="00:00:05,240">
      <property name="start">1</property>
      <property name="level">1</property>
      <property name="mlt_service">brightness</property>
      <property name="shotcut:filter">fadeInBrightness</property>
      <property name="alpha">0=0; 45=1</property>
      <property name="shotcut:animIn">46</property>
    </filter>
    <filter id="filter3" out="00:00:05,240">
      <property name="start">1</property>
      <property name="level">1</property>
      <property name="mlt_service">brightness</property>
      <property name="shotcut:filter">fadeOutBrightness</property>
      <property name="alpha">81=1; 131=0</property>
      <property name="shotcut:animOut">51</property>
    </filter>
  </producer>
  <producer id="producer7" title="Anonymous Submission" in="00:00:00,000" out="00:00:05,240">
    <property name="length">04:00:00,000</property>
    <property name="eof">pause</property>
    <property name="resource">C:/Temp/14182277_xl.jpg</property>
    <property name="ttl">1</property>
    <property name="aspect_ratio">1</property>
    <property name="progressive">1</property>
    <property name="seekable">1</property>
    <property name="mlt_service">qimage</property>
    <property name="global_feed">1</property>
    <property name="xml">was here</property>
    <property name="shotcut:hash">f4a264a5b72e41eb19eb31d59daeb87c</property>
    <filter id="filter4" out="00:00:05,240">
      <property name="start">1</property>
      <property name="level">1</property>
      <property name="mlt_service">brightness</property>
      <property name="shotcut:filter">fadeInBrightness</property>
      <property name="alpha">0=0;45=1</property>
      <property name="shotcut:animIn">46</property>
    </filter>
    <filter id="filter5" out="00:00:05,240">
      <property name="start">1</property>
      <property name="level">1</property>
      <property name="mlt_service">brightness</property>
      <property name="shotcut:filter">fadeOutBrightness</property>
      <property name="alpha">81=1;131=0</property>
      <property name="shotcut:animOut">51</property>
    </filter>
  </producer>
  <playlist id="playlist1">
    <property name="shotcut:video">1</property>
    <property name="shotcut:name">V2</property>
    <blank length="00:00:01.280"/>
    <entry producer="producer6" in="00:00:00,000" out="00:00:05,240"/>
    <blank length="00:00:01.280"/>
    <entry producer="producer7" in="00:00:00,000" out="00:00:05,240"/>
  </playlist>
  <tractor id="tractor0" title="Shotcut version 18.05.08" global_feed="1">
    <property name="shotcut">1</property>
    <property name="shotcut:projectAudioChannels">2</property>
    <track producer="background"/>
    <track producer="playlist0"/>
    <track producer="playlist1"/>
    <transition id="transition0">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
      <property name="mlt_service">mix</property>
      <property name="always_active">1</property>
      <property name="sum">1</property>
    </transition>
    <transition id="transition1">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
      <property name="version">0.9</property>
      <property name="mlt_service">frei0r.cairoblend</property>
      <property name="disable">1</property>
    </transition>
    <transition id="transition2">
      <property name="a_track">0</property>
      <property name="b_track">2</property>
      <property name="mlt_service">mix</property>
      <property name="always_active">1</property>
      <property name="sum">1</property>
    </transition>
    <transition id="transition3">
      <property name="a_track">1</property>
      <property name="b_track">2</property>
      <property name="version">0.9</property>
      <property name="mlt_service">frei0r.cairoblend</property>
      <property name="disable">0</property>
    </transition>
  </tractor>
</mlt>`

**Comment by pipecleaner** [comment]
Addendum: I meant Shotcut exports the project also as 1920x1080. The double repaired project file with sources located in c:/Temp is attached as zip

[shotcut-crash - Repaired - Repaired.zip](https://github.com/mltframework/shotcut/files/2020296/shotcut-crash.-.Repaired.-.Repaired.zip)

**Comment by Wolferl1** [comment]
I had the exactly same problem, Windows 7 HP 64bit, 8GB of RAM. Crashed at different points when exporting a 15 minute video 1920x1080, 25p with several still images and effects. After disabling "parallel mode" it works nicely.
Used ShotCut version 19.08.16.
