### ISSUE TITLE
Opening the .mlt file crashes Shotcut

### ISSUE THREAD

**Issue by BrendanBlair64** [mltframework/shotcut#558]
I've been editing a video for around 20 hours, and now when I try opening the .mlt file, Shotcut crashes. It only crashes when I open that file, otherwise Shotcut works fine. Please help, I'd be devastated if I have to start over. I also want to get the video out really soon considering it's been almost a month since my last video.

**Comment by ddennedy** [comment]
Does it load OK if you use File > Open MLT XML As Clip...?
You can attach the project file to here or use https://shotcut.org/notes/support-upload/

**Comment by BrendanBlair64** [comment]
I just tried that, no, it still crashed. I just uploaded the mlt using your link, I don't know what that did. I'm pretty dumb with computers, so I apologize if I wasn't supposed to do that.

**Comment by BrendanBlair64** [comment]
I fixed it! I just turned on GPU processing! I guess maybe my project got a bit too ambitious for my CPU? Whatever! I'm so happy! Thanks for trying to help, I do appreciate it!

**Comment by Rayz12345** [comment]
Hi i have same problems please help me bro
