### ISSUE TITLE
saving Timeline settings

### ISSUE THREAD

**Issue by pixelr0** [mltframework/shotcut#56]
i have a low resolution screen so i have to Make Tracks Shorter. The problem is that the settings are not saved and i have to Make Tracks Shorter every time i start shotcut. It would be nice if shotcut can autosave the Tracks settings on exit

**Comment by ddennedy** [comment]
We do not accept enhancement requests. This tracker is for defects only.

**Comment by pixelr0** [comment]
what if i code the changes, will you accept upstream?

**Comment by ddennedy** [comment]
Yes! P.S. The track heights are saved with a project XML. It should be fairly easy to also save to/restore from settings for app session.

**Comment by pixelr0** [comment]
Thanks! i'm a bit rusty but let's see :>
