### ISSUE TITLE
Some high-DPI pop-ups broken

### ISSUE THREAD

**Issue by qubodup** [mltframework/shotcut#561]
Some windows don't scale when high DPI (150%) is enabled (win10 64bit)

Save changes warning popups
![image](https://user-images.githubusercontent.com/18312/39986757-f3aeeb32-5762-11e8-94ec-bd34a676b509.png)

Open Other (clicking corner fixes it)
![image](https://user-images.githubusercontent.com/18312/39986790-0d3b5a0e-5763-11e8-885e-d600f1ce789b.png)

Color picker in Open Other/Generator/Color
![image](https://user-images.githubusercontent.com/18312/39986812-22119aec-5763-11e8-97a1-96a7918e72d2.png)

Color picker in text filter (closing and re-opening fixes it)
![image](https://user-images.githubusercontent.com/18312/39986873-4a8c6646-5763-11e8-8450-5db4e702ff08.png)

Switch to GPU mode warning
![image](https://user-images.githubusercontent.com/18312/39986896-5d1ba92a-5763-11e8-80e5-75b578e59a4b.png)

Windows setting https://support.microsoft.com/en-us/help/4028566/windows-10-change-the-size-of-text

**Comment by bmatherly** [comment]
Could be a DPI issue. Try the suggestions here:
https://forum.shotcut.org/t/interface-fonts-way-to-small/312

Also of interest:
https://forum.shotcut.org/t/program-dont-fit-on-tv-screen/4403
https://forum.shotcut.org/t/shotcut-theming-gone-wrong/1107

**Comment by ddennedy** [comment]
It works fine for me in Windows 10 at 150 and 200%:
![image](https://user-images.githubusercontent.com/1146683/40010300-26db8934-5759-11e8-9d88-bb3c320a179d.png)

I also turned on "Fix scaling for apps" in Advanced scaling settings and that gives some funky results but nearly as unusable as yours. 

Do you have multiple monitors connected?

This is largely out of our control and controlled by Qt, and it may change with the next Qt upgrade, which I am hoping for next release.

**Comment by qubodup** [comment]
Thanks for all the info!

Yeah, I should have mentioned: I use two screens and only use 150% on screen1 (screen2 is 100%).

When I enable 150% scaling on both screens, it works fine.

So this is probably too much of a border case to care.
