### ISSUE TITLE
qmelt.exe hangs forever

### ISSUE THREAD

**Issue by HDSQmid** [mltframework/shotcut#562]
I am getting an issue where when I am rendering a video, qmelt.exe will hang with 0% CPU usage until it is force quit.
It does not produce an error
It does not say "Job Failed" in the main shotcut window
It just stops at about 60% seemingly forever (I force killed the application after 10 minutes of 0% CPU usage)

The project files can be found here (I included all of them. Its a big download)
*If any are missing, please let me know their filenames so I can add them to the archive
[Link](https://drive.google.com/open?id=1wYEc3yGZmHNEED3WzS__9aBL0LgbSQ47)
The main project file is named "nightfall.mlt"

I believe that it is an issue with the Audio Spectrum Visualisation filter.

I was able to produce this error on a machine with the following specs
i7 6500U
2 x 4 GB of DDR4 RAM
256GB SSD + 1TB HDD
Windows 10 Home Version 1709

**Comment by ddennedy** [comment]
> I believe that it is an issue with the Audio Spectrum Visualisation filter.

Did you remove or disable that filter to see if it works?

**Comment by ddennedy** [comment]
Please be aware that this was created with v18.05.03, which has been deleted from download and replaced by v18.05.08.
hqsq.mp4 was not provided, and I used nightfall 1.5.2.mp4 as a subtitute.
Then, using v18.05.08 (18.05.03 not tested), it exports completely for me.

**Comment by HDSQmid** [comment]
> Please be aware that this was created with v18.05.03

The MLT was created with 18.05.03, but when the export failed for a different reason, I updated shotcut to 18.05.08. Maybe this has something to do with it. (possible migration issues?)

> Did you remove or disable that filter to see if it works?

I made another video using the same source, but without the audio visualisation, and without some other filters near the end, and it worked fine. I made this version in 18.05.08

**Comment by ddennedy** [comment]
I found the problem in MLT. It is triggered by your complex project with multiple tracks containing multiple overlapping transitions. There is a workaround until the next release. You need to set the following environment variable and restart Shotcut: MLT_AVFORMAT_PRODUCER_CACHE = 10.

**Comment by HDSQmid** [comment]
Where do I set environment variables?

**Comment by ddennedy** [comment]
user is fine.

**Comment by ddennedy** [comment]
This did not completely resolve it for me. There was a different in my working copy masking an additional problem. As a result, qmelt would crash at ~85%. This corresponds to the point at which the last clip on V4 starts. This clip has several filters on it, and disabling Size and Position finally made it succeed. Now, I am trying to debug that, but I doubt 

Do you have a video on your channel that was made with Shotcut that I can add to a [playlist](https://www.youtube.com/watch?v=MES-varsnUo&list=PLy7k-GJ461uvTuwZPS0ISlDYu_AY4FFwp).

**Comment by ddennedy** [comment]
The partial fix to avoid needing to set the environment variable: https://github.com/mltframework/mlt/commit/49470a9d7fb02556bac307f8434ff5aae06a249e

**Comment by HDSQmid** [comment]
[Link](https://www.youtube.com/channel/UCPB_zkvsJKuIkCgEzoXtN3g/featured)
that's my channel. Everything there has been edited with shotcut.
I hope you're not epileptic ;D

**Comment by HDSQmid** [comment]
What is the name of the clip that made it fail?

**Comment by ddennedy** [comment]
250 end screen.png with the filters:
* Chroma Key: Simple
* Glow
* Fade Out Video
* Fade In Video
* Size and Position

**Comment by HDSQmid** [comment]
Maybe changing the order of filters could help.
Putting size and position earlier...
From my knowledge, it would work best before the glow filter. so that the glow doesn't get warped and stuff due to the keyframes

**Comment by HDSQmid** [comment]
Sounds good!

**Comment by ddennedy** [comment]
Here is the nightly build to try out:
http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-win64-180517.zip

**Comment by HDSQmid** [comment]
I'll be able to try it out in about 12 hours. On battery power at the moment.

**Comment by HDSQmid** [comment]
Trying it now... I'll leave it overnight. Let you know the results in the morning...

**Comment by HDSQmid** [comment]
It worked perfectly! thanks!
