### ISSUE TITLE
Adding blur effect with sharpen effect crashes shotcut.

### ISSUE THREAD

**Issue by Nukley** [mltframework/shotcut#567]
OS: Windows 7 Ultimate 64 Bit
GPU: GMA 45
CPU: Intel Pentium Dual Core
Shotcut: 18.05.08
Issue: Adding the blur effect makes shotcut crash, it's that simple.

**Comment by ddennedy** [comment]
Unable to reproduce on Windows 10 with or without GPU processing enabled. I doubt Windows version makes a difference? Do you have GPU processing enabled in Settings? That is experimental and not addressable because it is dependent on the particular machine's OpenGL.

**Comment by Nukley** [comment]
No i don't, and i forgot to mention its in combination of the sharpen effect.

**Comment by ddennedy** [comment]
ok, I reproduced it now.
