### ISSUE TITLE
Filters won't update until clicking around a few times

### ISSUE THREAD

**Issue by allanbreyes** [mltframework/shotcut#569]
Shotcut: 18.05.08
OS: Ubuntu 18.04 LTS
Installation method: tried on AppImage, flatpak, snap, and built from source

---

This is a particularly elusive one. I'm not exactly sure what the reproduction steps are, but it happens fairly often (at least 1-2 times in every MLT file I open). A typical example:

1. I'll add an "other source," usually a green screen
2. I'll add a size/position filter. It defaults to Fit. I can't change it to Distort or resize it in the window pane. Some of the values can be changed, but they won't "save."
3. I click away from the filter (sometimes to other filters or other objects), and then click back on the filter. Then, stuff can be updated and saved.

Occasionally, this is accompanied with a crash. I've observed this issue for about a month, now, and I've also seen it happen with opacity filters. Would like to see if others are seeing the same, or if there is any remediation for it. I'll try to grab a screencast during the next time it happens. Thanks!

**Comment by allanbreyes** [comment]
Here's a screencast: https://youtu.be/o9EDrOdYdik

![ezgif com-optimize](https://user-images.githubusercontent.com/7947900/40416443-21da9d6e-5e32-11e8-85a3-d1228686a8c0.gif)

**Comment by ddennedy** [comment]
This was already fixed. The bug is that filters with simple keyframes required the playhead to be between the first and last frame of the clip (not including them) even if the simple keyframes were not used. There are numerous other keyframes-related bugs fixed:
https://github.com/mltframework/shotcut/commits/master

**Comment by allanbreyes** [comment]
Ah perfect. Thanks for the resolution!
