### ISSUE TITLE
Copy/paste segment + resize duration

### ISSUE THREAD

**Issue by allanbreyes** [mltframework/shotcut#570]
Shotcut: 18.05.08
OS: Ubuntu 18.04 LTS

---

**Expected behavior**
When copying and pasting a segment (without ever touching or modifying the default keyframes), and then resizing said segment, the keyframes should retain the default behavior, e.g. resize with the total segment.

**Observed behavior**

![keyframes](https://user-images.githubusercontent.com/7947900/40454658-83fd40fc-5e9e-11e8-891b-67f336c097ad.gif)

> NOTE: this happens "behind the scenes" even when I haven't messed with keyframes at all. I'm not sure if it's intentional behavior, but I (personally) would have expected keyframes to remain "snapped" to the full duration, especially if I didn't touch anything w.r.t. keyframes.

**Comment by ddennedy** [comment]
This is already fixed as well. I tried to suggest in the other ticket that there are a lot of known bugs in the keyframes. I suggest holding off until the next version. If it is causing enough problems then use v18.03.

**Comment by allanbreyes** [comment]
Apologies for the noise! I'll hold off on posting issues.
