### ISSUE TITLE
Running as a Windows portable app

### ISSUE THREAD

**Issue by albertony** [mltframework/shotcut#572]
I'm running Shotcut with local data folder using command line argument: `shotcut.exe --appdata="data"`. If I do any changes to the user interface requiring restart (I know at least that Settings > Language does this), then a messagebox `You must restart Shotcut to switch to the new language. Do you want to restart now?` appears, and if I accept this then Shotcut will be restarted without the command line argument - leading to `%LocalAppData%\Meltytech\Shotcut` being used instead of my local data folder.

Another related thing: It seems that when using the --appdata argument all settings are stored in a `shotcut.ini` file in that folder, I really like that - so that it is completely self-contained ("portable app"). But it still creates the registry key `HKCU\Software\Meltytech\Shotcut`, so if that could be avoided then it would be (to my knowledge) be completely "stealth" (as portablefreeware.com calls it).

Tested on Windows 10 (1709) with Shotcut version 18.05.08.

**Comment by ddennedy** [comment]
I fixed the command line arguments on restart. I do not care about the lingering registry key. Someone will have to provide a patch if they want it.
