### ISSUE TITLE
The Fade is starting too late or too soon.

### ISSUE THREAD

**Issue by GetsGrassblock** [mltframework/shotcut#573]
Whenever I add a fade in or fade out filter and export the video, after it renders i play it and **it shows the fade ins and outs too soon or too fast**. Please respond **ASAP** because I am trying to make a youtube video and want to upload it fast. I am running on **Microsoft windows 8.1 Pro** and my shotcut version is **18.05.08.**

**Comment by ddennedy** [comment]
I believe you are affected by bugs in version 18.05 due to the introduction of new major features. This bug was already fixed. The only workaround is to remove the fades and re-add them. You have to do this every time you change the duration of a clip. The next version is due June 2.
