### ISSUE TITLE
Strange behaviour when using image

### ISSUE THREAD

**Issue by Kivattt** [mltframework/shotcut#575]
I tried inserting an image but this is what I see.
I can't apply any filters to the image.
I had the same issue with applying filters some time ago, but it fixed when I restarted
I'm using GNU/Linux Debian

![whatingodsnameisthis](https://user-images.githubusercontent.com/33596810/40623549-b5018a5c-62a7-11e8-8823-7ecde3c14fb7.png)
![ifucklecant](https://user-images.githubusercontent.com/33596810/40623553-b93b20ba-62a7-11e8-8cc0-678b3a53cbec.png)

**Comment by Kivattt** [comment]
It's worth noting I haven't updated in a while, so this might not be an issue still

**Comment by Kivattt** [comment]
Oh it just crashed because I tried to remove the last part of a timeline
nice good job I really love how I can't use DaVinci on loonix

**Comment by Kivattt** [comment]
I'm sorry that was rude I'd never leave shotcut xoxo

**Comment by Kivattt** [comment]
I just inserted another image
same problem, but moving it seems to do something
![screenshot from 2018-05-28 21-40-03](https://user-images.githubusercontent.com/33596810/40627513-c2bd4b8c-62bf-11e8-8590-82c7882ba817.png)

**Comment by Kivattt** [comment]
Now it won't let me insert another image bacuse why would you want to do such a thing, right?

**Comment by Kivattt** [comment]
I'd definitly change my video editor if I knew anything about editing

**Comment by Kivattt** [comment]
It let me insert another pic after i restarted the program

**Comment by Kivattt** [comment]
golly gee what is this editor anyway

**Comment by Kivattt** [comment]
I'd love to know what's going on, but I'm too autistic to find out

**Comment by Kivattt** [comment]
I found out how to recreate it (on my end, that is).
Open some image file, drag it before another image file (don't move "cursor" at this point)
 scale it (probably not necessary) then move it infront of the other image. Tada!

**Comment by ddennedy** [comment]
OK, thanks, I see it in your video. I do not have the project "run - Repaired.mlt" but I tried to create a similar track arrangement. However, I could not reproduce the problem in v18.05.  That is not surprising. Something as sufficiently complex as this software and your project is bound to have issues that are difficult to locate. Since you are working with PNGs that may have alpha channels, you still might be affected by the bug fix I mentioned above. Do you have GPU Processing enabled in Settings?

**Comment by Kivattt** [comment]
No, I don't have it enabled

**Comment by Kivattt** [comment]
The "smile.jpg" image has the fade in video, mask, and opacity filters btw
