### ISSUE TITLE
Logo For shotcut #1

### ISSUE THREAD

**Issue by hawk28** [mltframework/shotcut#578]
Hi , I am a graphic designer, I want to help you in graphic design.

After I review your project, you have no logo on this project yet. Therefore I want to contribute to this project by creating a new logo / icons. What do you think?

**Comment by ddennedy** [comment]
There is already a logo, and I am keeping it. Did you even install it and see the app icon? How about the About dialog?
![Shotcut logo](https://raw.githubusercontent.com/mltframework/shotcut/master/icons/shotcut-logo-64.png)

It is so simple many people think it is not an icon or logo, but it is; simple is the trend. I will be making a small change to the website design soon to better emphasize the logo.
