### ISSUE TITLE
Project with one clip only doesn't show filters at times

### ISSUE THREAD

**Issue by qubodup** [mltframework/shotcut#582]
1. Import 1 image (works with video too)
2. Add image to timeline
3. Apply 1 filter to clip in timeline
4. Save, restart, load project
5. Click clip

Expected:
Filters tab shows filters of clip

Actual:
Filters tab is empty even if filters are visibly active in the preview monitor

Video: https://youtu.be/ZCnRfXg9dtU

**Comment by ddennedy** [comment]
Duplicate of #358.
