### ISSUE TITLE
Shotcut won't start on Xubuntu 18.04 - `(process:26739): Gtk-WARNING **: 01:48:12.238: Locale not supported by C library.`

### ISSUE THREAD

**Issue by NightfallAlicorn** [mltframework/shotcut#583]
Shotcut: 18.03.06
Xubuntu: 18.04 (Bionic Beaver)

I've wiped my partitions and installed Xubuntu 18.04.

I've installed Shotcut by `snap install shotcut --classic`.

When Shotcut is run from terminal it produces this log with no program window. I think I saw something about this somewhere before where it involved changing a Shotcut config file but I can't find the link. Not sure if issue is related or not.

```
(process:26739): Gtk-WARNING **: 01:48:12.238: Locale not supported by C library.
	Using the fallback 'C' locale.
No appenders registered with logger
[Debug  ] <ShotcutSettings::singleton> language "en_GB" 
[Debug  ] <ShotcutSettings::singleton> deinterlacer "onefield" 
[Debug  ] <ShotcutSettings::singleton> external monitor "" 
[Debug  ] <ShotcutSettings::singleton> GPU processing false 
[Debug  ] <ShotcutSettings::singleton> interpolation "nearest" 
[Debug  ] <ShotcutSettings::singleton> video mode "" 
[Debug  ] <ShotcutSettings::singleton> realtime true 
[Info   ] <Application::Application> Starting Shotcut version 18.03.06 
[Info   ] <Application::Application> Linux version 
[Info   ] <Application::Application> number of logical cores = 4 
[Info   ] <Application::Application> locale = QLocale(English, Latin, UnitedKingdom) 
[Info   ] <Application::Application> install dir = "/snap/shotcut/21/Shotcut.app/bin" 
[Info   ] <Application::Application> device pixel ratio = 1 
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
[Debug  ] <MainWindow::changeTheme> begin 
[Debug  ] <MainWindow::changeTheme> end 
[Debug  ] <MainWindow::MainWindow> begin 
[Warning] <> Unrecognized OpenGL version
[Warning] <> Unrecognized OpenGL version
```

**Comment by ddennedy** [comment]
The real error is `libGL error: unable to load driver: radeonsi_dri.so`
This is an OpenGL problem or a OpenGL problem in snap. Shotcut requires a working and compatible OpenGL environment as stated in the [FAQ](https://shotcut.org/FAQ/).
Did you try the AppImage or portable zip? This is not really in our control.

**Comment by NightfallAlicorn** [comment]
The portable one seems to work. Hadn't tried the AppImage. I was trying to get an install version of the program to work and have it auto update with the rest of my applications without needing to unzip a new version later updates I know there's an apt version but I don't know the PPA host is trusted or not.

**Comment by ddennedy** [comment]
This PPA is maintained by a former Shotcut developer and is trustworthy:
https://launchpad.net/~haraldhv/+archive/ubuntu/shotcut/
