### ISSUE TITLE
Need to restart or reload timeline to fix audio waveform after split

### ISSUE THREAD

**Issue by houdini69** [mltframework/shotcut#585]
Contrary to Shotcut 18.05.08, in Shotcut 18.06.02 (macOS 10.13.04) when I split (S) video track in the timeline I'm unable to rebuild audio waveform. I need to restart Shotcut for that. I have tried to detach audio waveform but Shotcut crashs when selecting audio waveform rebuild.

**Comment by ddennedy** [comment]
> I'm unable to rebuild audio waveform

What does that mean? It sounds like the menu item is hidden or disabled, but I do not think that is what you mean.

> I have tried to detach audio waveform but Shotcut crashs when selecting audio waveform rebuild.

I think you are referring to the new "Detach Audio" menu item in a timeline clip's context menu. I do not reproduce that.

**Comment by houdini69** [comment]
> What does that mean? It sounds like the menu item is hidden or disabled, but I do not think that is what you mean.

That means that when I cut the track in the timeline the audio waveform doesn't match to what is listened ("same" audio waveform before the cut and after). So, I tried to rebuild the audio waveform by selecting the menu item to no avail (menu item isn't hidden or disabled). Restarting Shotcut allows to get it.

> I think you are referring to the new "Detach Audio" menu item in a timeline clip's context menu. I do not reproduce that.

Yes I do. Sorry for my inaccurate english (my Shotcut interface is in french).

**Comment by houdini69** [comment]
Duplicate audio waveform after cut with (s)
![duplicate audio](https://user-images.githubusercontent.com/24533104/40890543-22a41028-6778-11e8-8bb5-d6b6bca379e7.png)

Menu item used without effect
![menu item](https://user-images.githubusercontent.com/24533104/40890554-4a6cd270-6778-11e8-8e99-4191dbdef2ae.png)

**Comment by ddennedy** [comment]
> That means that when I cut the track in the timeline the audio waveform doesn't match to what is listened ("same" audio waveform before the cut and after). 

I reproduce that. The easier (less interruption) workaround is to choose Reload (F5) from the Timeline menu. I will make that the main bug for this ticket.

**Comment by Pierstoval** [comment]
Is there any plan to schedule a new release for this fix soon? I'm having this bug and I have to make hundreds of splits on my videos and it takes me twice the time to reload everytime, especially when I have heavy videos to update (sometimes, a F5 call takes a few seconds to process, so you can imagine the time I lose just because I must do F5 everytime I make a cut)

**Comment by ddennedy** [comment]
Yes, as usual, at the beginning of the next month. Also, the milestone that is tagged on this ticket has a target date.

**Comment by Pierstoval** [comment]
Thanks! I didn't know you had such release process, that's great! 👍
