### ISSUE TITLE
Setting default scan mode and deinterlacer for presets

### ISSUE THREAD

**Issue by albertony** [mltframework/shotcut#588]
When resetting options before loading presets, the `Deinterlacer` combo is being set to `YADIF - temporal + spatial (best)` but the combos `Scan mode` and `Field order` are not updated. This leads to some issues, probably minor but leads to some confusion (see below). And also, is the intention to set `Scan mode` to `Progressive` (and then `Field order` to grayed out `None`)?

Two observed issues related to this:

If you manually set `Scan mode` to `Interlaced`, then the `Field order` is automatically set to `Top Field First` and `Deinterlacer` is set to grayed out value `None`. Now if you click a preset (that does not explicitely set these options) then the `Deinterlacer` changes to value `YADIF - temporal + spatial (best)` but will still be grayed out.

If you click the `Reset` button and then select the preset `D10 (dv_pal)`, then the video setting `Deinterlacer` will show grayed out value `None`. But if you click the same preset once more the `Deinterlacer` changes to grayed out value `YADIF - temporal + spatial (best)`.

Tested on Windows 10 (1709) with Shotcut version 18.06.02.

**Comment by ddennedy** [comment]
> is the intention to set `Scan mode` to `Progressive` (and then `Field order` to grayed out `None`)?

Yes

> Now if you click a preset (that does not explicitely set these options) then the Deinterlacer changes to value `YADIF - temporal + spatial (best)`

This is by design. The preset system is not intended to be really smart about what you changed from defaults.

> but will still be grayed out

That is a bug. I reproduced it.

> select the preset D10 (dv_pal), then the video setting Deinterlacer will show grayed out value None

That is intentional. D10 is for interlaced output.

> if you click the same preset once more the `Deinterlacer` changes to grayed out value `YADIF - temporal + spatial (best)`

That is a bug I reproduce as well.
