### ISSUE TITLE
"failed to open" mlt file

### ISSUE THREAD

**Issue by dynamuso** [mltframework/shotcut#589]
last night i saved my shotcut video, and went to bed, when i came back i tried and pasting the mlt file into shotcut to load mhy footage but an error pops up saying "failed to open" (and the file path). i need help with this, tones of other people have this problem to.

**Comment by ddennedy** [comment]
> pasting the mlt file into shotcut

How do you paste a mlt file into Shotcut? 
If you mean File Open or choosing it from the Recent panel, then I do not reproduce it. 
You must specify your OS and Shotcut version.

> tones of other people have this problem to

No, they don't. There are plenty of people that have some problem loading a past project but not the "failed to open" error you report.

**Comment by ddennedy** [comment]
Add a .txt extension to your .mlt file and upload it here, or for a little more confidentiality you can upload it here: https://shotcut.org/notes/support-upload/
