### ISSUE TITLE
Incorrect audio waveforms on split

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#592]
Hello,

I'm seeing the following behavior in shotcut 18.06.02:
- Create a new audio track (or video track, seems to have the same problem).
- Insert some file with audio into the track.
- Split the track somewhere.
- Problem: The right side of the split has an incorrect waveform (it appears that the beginning of the waveform is moved to the split point).

I tried to reproduce this with a current git version (as of 2018-06-09), however the git version crashes when trying to split the track.

Best regards
Ochi

**Comment by ddennedy** [comment]
Delicate of #585
