### ISSUE TITLE
Crash when adding video to timeline in GPU mode after commit 90164dd

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#599]
Hello,

I noticed that the current git version segfaults when adding a video to the timeline when adding a clip (in my case a h264 mkv) to the timeline while GPU processing is enabled. Bisecting shows that d9b7f73c05f3b2674c9898a5505c9c85eadb895e works while 90164dd57b2738a49f5da6ff34ca9fc1c1223557 ("Fix AvformatProducerWidget inaccurate with timeline clips.") fails. In case you cannot reproduce this issue I'll have to check if my mlt and movit versions also play a role.

Best regards
Ochi

**Comment by ddennedy** [comment]
I reproduced it when I add a GPU filter to the clip in Source before trying to add it to Timeline.
