### ISSUE TITLE
export does not work, ASSERT failure in QXcbIntegration

### ISSUE THREAD

**Issue by dim-geo** [mltframework/shotcut#602]
Hi,

For sure reason shotcut does not allow me to export my video.
I have export the video a few times without adding credits and it worked.
I added credits like this:
https://forum.shotcut.org/t/movie-style-scrolling-credits/2863/6

It fails with this:
```
WARNING: QApplication was not created in the main() thread.
QSettings::value: Empty key passed
QSettings::value: Empty key passed
ASSERT failure in QXcbIntegration: "Initializing accessibility without event-dispatcher!", file qxcbintegration.cpp, line 357
Failed with exit code 6
```

I have installed through flatpak as a user, Gentoo in my main OS
all flatpak packages are updated.
```
flatpak list
Ref                                                  Options       
com.ozmartians.VidCutter/x86_64/stable               system,current
org.shotcut.Shotcut/x86_64/stable                    system,current
org.freedesktop.Platform.GL.nvidia-396-24/x86_64/1.4 system,runtime
org.freedesktop.Platform.ffmpeg/x86_64/1.6           system,runtime
org.kde.KStyle.Adwaita/x86_64/5.10                   system,runtime
org.kde.KStyle.Adwaita/x86_64/5.9                    system,runtime
org.kde.Platform/x86_64/5.10                         system,runtime
org.kde.Platform/x86_64/5.9                          system,runtime

```
```
Shotcut: 18.06.02
```

Any idea for a workaround?

**Comment by ddennedy** [comment]
@eszlari This is because the flatpak is using melt instead of qmelt ro run export child process.
https://github.com/flathub/org.shotcut.Shotcut/blob/master/org.shotcut.Shotcut.yaml#L204

Why? qmelt should be installed by WebVfx. It will if MLT_SOURCE is provided to qmake:
https://github.com/mltframework/webvfx/blob/master/mlt/qmelt/qmelt.pro

Is the source path location difficult to provide between flatpak modules?

**Comment by eszlari** [comment]
Should be fixed: https://github.com/flathub/org.shotcut.Shotcut/commit/337eecbbf2d853d643e4cf9bf9671c5f373aa1a4

@dim-geo Could you update and try again?

**Comment by ddennedy** [comment]
Thank you @eszlari !

**Comment by dim-geo** [comment]
It works! Feel free to close the issue!
