### ISSUE TITLE
Wrong keyboard shortcuts in HTML Editor

### ISSUE THREAD

**Issue by mrleemon** [mltframework/shotcut#605]
Many menu items in the HTML Editor have a letter underlined indicating a keyboard shortcut that either doesn't exist (e.g: &Strikethrough) or is wrong (e.g: &Paste). It may be a good idea to remove the ampersands from the menu item strings where they don't make any sense. Or remove all the ampersands altogether because most of them don't have an exact equivalent in other languages (&Bold in English, Negrita in Spanish doesn't have any B)

**Comment by ddennedy** [comment]
They work for me on Windows (including Strikethrough and Paste), and translators can choose to have an ampersand in front of a chosen letter. Menu keyboard shortcuts are a very common thing. You need to be more convincing.

**Comment by mrleemon** [comment]
Sorry, you are right. I was doing it wrong.
