### ISSUE TITLE
Audio issues when playing timeline

### ISSUE THREAD

**Issue by lhimo** [mltframework/shotcut#608]
Adding a .MOV video to the timeline, by playing a chunk of it he audio turns out to be sloppy, as in the attached file. Video: 1920x1080 11870 kbps (12381 kbps overall) with 30 fps. Audio: 511 kbps, mono, 32000 kHz. Running Shotcut 18.07.02 on Windows 10 1803 with SSD and 8GB of RAM.

EDIT: Disabling GPU effects fixes it sometimes.

[record.zip](https://github.com/mltframework/shotcut/files/2167849/record.zip)

**Comment by ddennedy** [comment]
This was a regression in v18.07 with the fix for audio scrubbing. It only affects preview and not export.
