### ISSUE TITLE
Problem with non-Arabic numbers (0-9).

### ISSUE THREAD

**Issue by ve3** [mltframework/shotcut#610]
My Windows use Thai as main format (date/time/number).
Thai number is **๐** = 0, **๑** = 1, **๒** = 2 and so on...

Shotcut have problem with these numbers. It is not working if I'm trying to set video speed to... for example, **9x**. It will be **๙x** and then video did not speed up at all.

Changed language to English still not working.

I'm sure that the other functional that must use the number will not work too.

Please do not use the system numbers but use Arabic numbers (0-9) by default.

**Comment by ve3** [comment]
Sorry, I know nothing about the programming you are using.

**Comment by ddennedy** [comment]
I will ask for help from a friend (non-developer) who knows Farsi to see if that language is affected similarly.

**Comment by ddennedy** [comment]
I have a Thai friend who made the new Thai translation (please consider helping her on the [Transifex web site](https://www.transifex.com/ddennedy/shotcut/language/th/)). We tested this with the latest version on macOS and Windows 10, and it (changing speed) is working fine using Thai numbers on Windows. You can also change Windows keyboard input to English and type in arabic numbers, and it works too even though it converts them back to Thai.

**Comment by ddennedy** [comment]
More than likely this fixed itself in version 19.02 when we last upgraded Qt:
https://shotcut.org/blog/new-release-190228/
