### ISSUE TITLE
Video fading in/ out don't work

### ISSUE THREAD

**Issue by ALetsPlayYT** [mltframework/shotcut#611]
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

Hey,

I'm using the Shotcut version 18.07 for Windows. Today I tried to use "video fading in/ out" for the first time. The effect should have a period of time of 1 second each.
But nothing happens. In the timeline I see the triangle that shows that everything worked, but when I watch the video there isn't any effect.

I hope you can fix this issue.

Best regards,

ALetsPlay

**Comment by ALetsPlayYT** [comment]
Settings > GPU Effects is already turned off
I recorded everything during I reproduced the problem, so it should be easier to reproduce it on other devices.
Link to the video: https://youtu.be/xJx6R6azMZQ

**Comment by ddennedy** [comment]
I reproduced it. It occurs mainly when you add fade out to an image file with a transition at the start. I am not certain it is limited to that exact combination and sequence yet, but that is how I can reproduce it. It does not seem to reproduce with a video file, and it does not seem to reproduce without that transition, however. (I am making notes here for myself and other developers.)

**Comment by ddennedy** [comment]
A inconvenient workaround is to remove the image clip after the transition, re**open** the image file (do not use copy from Edit menu or Timeline, but OK if it comes from Playlist or Recent), and add the filters.

**Comment by ALetsPlayYT** [comment]
Thank you for this bypass as long as it isn't fixed. Now everything works.

Thank you for the fast help.
