### ISSUE TITLE
Custom build crashes on Add Video Track

### ISSUE THREAD

**Issue by kodekid9** [mltframework/shotcut#612]
Shotcut consistently crashes when simply clicking "Add Video Track."  Program was built from shotcut180702 source on a Slackware 64-current  laptop.  Very disappointing because not only was it a pain to compile but the visuals upon startup look very promising.

**Comment by ddennedy** [comment]
Shotcut builds can be tricky to get working correctly, and custom builds are not supportable. What you describe is not reproduced on our official builds for macOS, Linux, and Windows. Are you working on a package for Slackware? I am only willing to support you if you are working on a package for the distro.
