### ISSUE TITLE
Shotcut v18.08 snap export failing

### ISSUE THREAD

**Issue by edwardabraham** [mltframework/shotcut#615]
I installed Shotcut using Snap and am getting the following error (in the log) when exporting a video:

```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, wayland-egl, wayland, xcb.

Reinstalling the application may fix this problem.
Failed with exit code 6
```
When the export first failed, I installed `libxkbcommon-x11-0` and `libqt5gui5` following advice to a similar sounding problem elsewhere. For good measure, I removed and reinstalled, again using the snap. When I run `ldd /snap/shotcut/28/Shotcut.app/lib/qt5/platforms/libqxcb.so`, it seems that everything is linked to lib files.

However, I am still unable to export (using the default Youtube settings). 

Ubuntu 18.04, Shotcut 18.08.01

**Comment by chrissxYT** [comment]
I have got exactly the same problem with exactly the same Ubuntu (18.04.1 LTS) and exactly the same Shotcut (18.08.01), I'm currently researching it a bit (downloading it from the website instead of the Ubuntu Store and I'll maybe look at the code later), if i'll find something, I'll post.

**Comment by ddennedy** [comment]
I reproduce this as well. Some dependency changed in the Snap container base image between last version and this. As a workaround, you can run the snap the same as a portable at the command line: `/snap/shotcut/current/Shotcut.app/shotcut`.

**Comment by chrissxYT** [comment]
I tried the portable and had something like "libmtl++.so.3"(not guaranteed to be the right name) missing. I'm rebuilding right now, my bad internet connection makes it take a while.

**Comment by ddennedy** [comment]
@chrissxYT You are probably running it incorrectly. Running bin/shotcut is not correct.

**Comment by chrissxYT** [comment]
First I need to say I saved the project when exporting didn't work, here some facts:
Funfact 1: When I open the proj.¹ I get a warning that it's damaged.
Funfact 2: I have a Color Grading on my clip, when I open the project and tell it to repair the file, it sets the black-white bar of the Midtones to black.
Funfact 3: When I try to render in portable 18.08.1 with the repaired, it seems to work (it finished while writing this).
Funfact 4: 3 applies to 18.07.2, too (it finished while writing this too).
Funfact 5: The differences seem to be:
damaged: "<mlt LC_NUMERIC="C""
repaired: "<mlt LC_NUMERIC="en_US""
(C -> en_US)
damaged: "<producer id="black" in="00:00:00.000" out="00:01:20.117">", "<entry producer="black" in="00:00:00.000" out="00:01:20.117"/>", "<producer id="producer0" title="Anonymous Submission" in="00:00:00.000" out="00:01:25.900">"
repaired: "<producer id="black" in="00:00:00,000" out="00:01:20,117">", "<entry producer="black" in="00:00:00,000" out="00:01:20,117"/>", "<producer id="producer0" title="Anonymous Submission" in="00:00:00,000" out="00:01:25,900">"
(dot -> comma)
Funfact 6: When I open the proj.¹ without repairing, 2 doesn't happen.
Funfact 7: I successfully started rendering the proj.² without repairing and it seems to work so far. (both done)
Summary: Something in either saving of 18.08.1 or loading² seems to be completely broken, my recommendation is saving the proj., reloading it without repairing and then trying to render again.
This should be all you need to know, I'd call this solved at this point.

¹in either 18.08.1 or 18.07.2
²in both 18.08.1 and 18.07.2 (portable)

**Comment by ddennedy** [comment]
There is a new v18.08 on the candidate, beta, and edge channels where the export does work (as well as locale handling). However, it changes the execution mode to work exactly like the portable tar bypassing the snap desktop-launcher script that changes numerous environment variables. It was never the intent that Shotcut uses the snap's Qt libs but rather its own. This change ensures that even further.
```
ddennedy@MS-7593:~/src/shotcut/packaging/linux$ snapcraft release shotcut 29 candidate,beta,edge
Track    Arch    Channel    Version    Revision
latest   amd64   stable     18.07      27
                 candidate  18.08      29
                 beta       18.08      29
                 edge       18.08      29
```
