### ISSUE TITLE
Shotcut saved mtl file keep on crashing when I play it or do anything to it.

### ISSUE THREAD

**Issue by Zealthy** [mltframework/shotcut#618]
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

**Comment by Rayz12345** [comment]
Same bro have you found a fix > please

**Comment by JazzTp** [comment]
Probably not related: you might try enabling (or disabling) GPU effects, _then_ loading the project (actually I had crashes minutes ago when _loading_ with GPU effects disabled a project that had been saved with GPU effects enabled... in analogue circumstances, ShotCut had _warned_ about the discrepancy without crashing).
