### ISSUE TITLE
No way to resize the screen??

### ISSUE THREAD

**Issue by emcampinline** [mltframework/shotcut#620]
I have two videos which i would like to play simultaneously on a shared screen (positioned one above another). 
To do this i need to resize the screen so that it's size can hold the two videos. But i find no way to do this in the app. 
So the only way to achieve it is by scaling the two videos?

**Comment by ddennedy** [comment]
This is not a bug. You can resize the window (it is not a "screen") just like resizing any window. If you need to go smaller, and you are limited then close the panels or choose View > Layout > Player from the menu. However, that is probably not what you want and have not explained it well. If that is the case, then Shotcut probably does not provide what you are looking for, and I do not take feature requests.
