### ISSUE TITLE
(Windows) Shotcut Crashes After 3 Seconds of Playback

### ISSUE THREAD

**Issue by CallMeHydra** [mltframework/shotcut#622]
Windows 10.0.17 Shotcut 18.08.14
[shotcut-log.txt](https://github.com/mltframework/shotcut/files/2312749/shotcut-log.txt)

**### Attempting to edit an about 50 minute video**
      It has always been crashing for me, but i was able to get around it by saving frequently.  #Now it is just not possible to get work done. I can open Shotcut fine, and open the file i want to edit, but 3-5 seconds after i hit play shotcut freezes and crashes. This really puts a damper on my video schedule, as this video was supposed to be out in 5 hours :(

**Comment by ddennedy** [comment]
Is the problem specific to this project? There is probably very little I can do to help you. Something got into the project that upset it. Does it depend on where you start play from? If so, that is a clue about something to remove. Are you able to export it? If it fails, it reports the time code *near* the point of failure, and that can be used to locate a problem and something to try to remove.

**Comment by CallMeHydra** [comment]
I seem to have fixed whatever it was. 

I set the display method to "Automatic" (after already trying both options) and i skipped a rather large chunk of the unneeded beginning and it seems to be running fine now. I don't know which did it, but hopefully anyone else having similar problems finds help in either :)
