### ISSUE TITLE
Corrupt edited file.

### ISSUE THREAD

**Issue by tabascorez2302** [mltframework/shotcut#623]
Hello,

I am using Windows 10 Home 64 bits.

18.08.14 SHOTCUT. I edited this video using the previous version before this one. 

I am unable to watch the video or edit it. None of the clips is playable.

I have try to perform the steps of <property name="shotcut:comment"></property> and it seems everything is fine and there is no additional words / or icon there. 

This is my first work using SHOTCUT.

Can you please help - thanks

[FIRST.zip](https://github.com/mltframework/shotcut/files/2318665/FIRST.zip)

This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

**Comment by ddennedy** [comment]
This file does not suffer the corruption problem mentioned in the blog post about v18.08.14. I do not see anything wrong with it.

When you try open it in Shotcut do you get a window similar to this?
![image](https://user-images.githubusercontent.com/1146683/44599524-76c95980-a78b-11e8-8161-286d82699532.png)

What is drive E: ? Is that a removable USB device? It looks the folder structure from a camera. If so, you need to use Windows Explorer to copy those files to a hard drive somewhere and then use this dialog to tell Shotcut where the new file location is.
