### ISSUE TITLE
Shotcut contains proprietary fonts

### ISSUE THREAD

**Issue by plater** [mltframework/shotcut#626]
The openSUSE legal team have informed me that these proprietary non free fonts must be removed from shotcut.
shotcut-18.08.14/src/qml/filters/webvfx_threejs_text/fonts/droid_sans_bold.typeface.js
shotcut-18.08.14/src/qml/filters/webvfx_threejs_text/fonts/droid_sans_regular.typeface.js
shotcut-18.08.14/src/qml/filters/webvfx_threejs_text/fonts/droid_serif_bold.typeface.js
shotcut-18.08.14/src/qml/filters/webvfx_threejs_text/fonts/droid_serif_regular.typeface.js
See:https://build.opensuse.org/request/show/629915

**Comment by ddennedy** [comment]
It looks like I can replace them with Liberation and/or Noto using [Facetype.js](https://gero3.github.io/facetype.js/) Then, provide a mapping for older projects.

**Comment by ddennedy** [comment]
see also 01849373
