### ISSUE TITLE
Better new version notification handling

### ISSUE THREAD

**Issue by FFY00** [mltframework/shotcut#627]
Right now when a custom version string is used (via `SHOTCUT_VERSION=`) the new version notification still shows up. The problem is that shotcut checks if the application version and the last version is exactly the same. That results in the new version notification being triggered even if it's already in the last version (Ex. `18.08.14-ARCH` != `18.08.14`). IMO we have two ways to fix this, the first would be disabling this feature when a custom version string is used, this option is almost only used by distributions so that would actually be a good thing, or change the check to see if the custom string contains the last version string, this might not work depending on the custom string model.

Thank you,
Filipe :)

**Comment by ddennedy** [comment]
Add `DEFINES+=SHOTCUT_NOUPGRADE` to the qmake call to disable the upgrade prompts and Help > Upgrade... menu item.

**Comment by FFY00** [comment]
Can you reopen? Adding `DEFINES+=SHOTCUT_NOUPGRADE` to qmake didn't work, even though `-DSHOTCUT_NOUPGRADE` was passed to the compiler.

Here's the build log: http://ix.io/1lRp

Screenshot:
![Issue Preview][https://i.imgur.com/i5pvRlK.png]

**Comment by ddennedy** [comment]
This requires git master head, which I do not think your build is using. See the milestone tagged to this issue for the next release that will include this commit.

**Comment by FFY00** [comment]
Thank you, that explains it :smile:.
