### ISSUE TITLE
chocolaty link on website

### ISSUE THREAD

**Issue by crener** [mltframework/shotcut#628]
This appears to be available to download [on Chocolaty](https://chocolatey.org/packages/Shotcut) but there is no mention of it on the website on the downloads page. Some people might like to know they can get it that way... Is there any chance that it is going to be added to the windows section of the downloads?

I'm assuming that it's on there in an unofficial capacity?

**Comment by ddennedy** [comment]
That is an unofficial source, and I do not want to be subject to their approval process or clutter the already complicated download page.
