### ISSUE TITLE
Black screen after white balance [macOS 10.13.6 Shotcut 18.08.15]

### ISSUE THREAD

**Issue by houdini69** [mltframework/shotcut#632]
Black screen is on the video display and after export when applying white balance on a whole track (whole track becomes black) or on a selected clip (only the selected clip becomes black). In my workflow I export into Intermediate -> ProRes from AVCHD mts files. I noticed this bug with the previous version.

**Comment by ddennedy** [comment]
This is due to a bug in color selection that was already fixed in the code base. This bug also afflicts the Chroma Key filters. You can use v18.08.14 in the meantime, or I can give you a link to last night's build that really only contains the fix for this (and only this).

**Comment by ddennedy** [comment]
http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-macos-x86_64-180916.dmg

**Comment by ddennedy** [comment]
FIxed in https://github.com/mltframework/mlt/commit/ac8d1f3485c58139429e4503a7fcc2daf0d72659

**Comment by ddennedy** [comment]
I updated the downloads page on the web site to include this version: 18.09.16
