### ISSUE TITLE
Overlay Video Clips No Longer Available?

### ISSUE THREAD

**Issue by TMacFPV** [mltframework/shotcut#640]
Windows 10
Shotcut Version 18.09.16
Compositing or Overlay or "Stack" lines button no longer appears at left in video tracks in latest version, consequently we are not able to "overlay" one video from one track onto another video on the track below it.  Where did they go?  Is this overlay option still available in this latest version, and if so, how do we go about accomplishing it.  Stuck on project because of this.  Thank you.

**Comment by ddennedy** [comment]
From the [release announcement](https://shotcut.org/blog/new-release-180913/), under Changes:

Removed the **Compositing** toggle icon from the **Timeline** track head. Now, it is located in the track **Properties** as **Blend mode** with a **None** option.

**Comment by TMacFPV** [comment]
Thanks!
