### ISSUE TITLE
Removing empty space does not move keyframes applied to track filters

### ISSUE THREAD

**Issue by arximboldi** [mltframework/shotcut#641]
Removing empty space moves all the clips forward. However, it does not move the keyframes. As such, keyframes are out of sync. Since I don't know a way to move multiple keyframes at once, there is no workaround I could find now... Now I have a lot of crazy manual editing to do... :(

**Comment by ddennedy** [comment]
Keyframes are relative to the start of a clip. Are you referring to a track filter (filter attached to a track or Master instead of a filter attached to a clip?
What is your version?

**Comment by arximboldi** [comment]
I am using the latest version, `18.09.15`. I refer to track filters, which I use extensively.

**Comment by arximboldi** [comment]
Is there a workaround to relatively quickly fix the issue? (Eg. move all breakpoints in a track by an offset?)

**Comment by ddennedy** [comment]
OK. Yeah, timeline edits do not affect keyframes on track filters. That is simply not implemented today, and we need to add that. There is no workaround. I recommend only using keyframes on clip filters in the meantime and only use keyframes on track filters for simple things. You live and learn just like us.

**Comment by arximboldi** [comment]
Ok. Thanks a lot anyways for this great software! Sorry for the negativity of my initial comment. Have a good one!

**Comment by ddennedy** [comment]
I have no plans to add this. Another user would just as surprised that removing clips moves keyframes on track filters. Also, this behavior would imply that the keyframes move when inserting footage and moving clips around - all of which can get messy and surprise many.
