### ISSUE TITLE
Weird behavior when using keyframes on "scale" in "Scale and Rotate" effect

### ISSUE THREAD

**Issue by arximboldi** [mltframework/shotcut#642]
Not sure how to describe this exactly, but automating both the "Scale" and "Rotate" parameters often yields very strange results... the image disapears, or scaling only in one of the dimensions. It is very hard to explain, but easy to reproduce. I think in particular what is broken is the Scale parameter, not rotate, which seems to be working fine.

**Comment by ddennedy** [comment]
This was already fixed for the next version due in October. a394b590

**Comment by ddennedy** [comment]
BTW, this problem does not affect simple keyframes on this filter.

**Comment by arximboldi** [comment]
What do you mean by "simple keyframes"? Thank you!

**Comment by arximboldi** [comment]
Also, I am not sure how is that related, since it seems like that commit is only about loading presets?

**Comment by ddennedy** [comment]
The problem occurs when you drag the keyframes. Please provide steps in the future.
[This release announcement](https://shotcut.org/blog/new-release-1805/) contains info about simple keyframes.

**Comment by arximboldi** [comment]
Aha!!! That makes a lot of sense. Sorry I would have put steps to reproduce, but I just could not figure out exactly how it was happening. Thank you very much for the fast responsiveness to the issues!
