### ISSUE TITLE
Video lags behind intended position with keyframed size & position filter applied to track with GPU acceleration enabled

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#647]
Observed in at least Shotcut 18.10.08 and 18.09.15.

This short video shows the issue in action:

[bug.zip](https://github.com/mltframework/shotcut/files/2470063/bug.zip)

Repro:
- Use GPU mode.
- Add clip to track.
- Move it a bit to the right so it doesn't start at 00:00:00:00.
- Add Size & Position filter to the track (not the clip).
- Activate keyframes for the filter and animate the clip (e.g. have it move around).

Observed:
- The actual position/size of the clip lags behind the intended position/size of the clip.

I wasn't able to reproduce this problem with the non-GPU-version of the filter.

**Comment by AGI-THB** [comment]
[GPU-Mode](https://github.com/mltframework/shotcut/issues/633#issuecomment-423266807)

**Comment by ochilan** [comment]
Note that the lag does not seem to be due to performance issues, but due to incorrectly positioned keyframes (they seem to have an offset from the correct start position of the clip, see above attached video).

**Comment by ddennedy** [comment]
Closing because GPU Effects is unsupported without a patch/pull request. Next version 18.11 makes this more obvious.
