### ISSUE TITLE
Shotcut does not start due to missing libwrap.so.0

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#648]
Shotcut 18.10.08 does not start on one of my Arch Linux boxes due to missing libwrap.so.0. On my main box, this library is installed as a dependency of steam-native-runtime, but only by chance.

The culprit is the (newly?) bundled libpulsecommon-4.0.so which requires libwrap.so.0.

**Comment by ddennedy** [comment]
More library dependencies are bundled now to resolve this bug #634.
However, the bundle_libs function filters out libs from /lib as opposed to /usr/lib by default as most of them fall in the [excludelist](https://github.com/AppImage/AppImages/blob/master/excludelist) but not all including libwrap in this case.

**Comment by ochilan** [comment]
Ah, that's interesting – on Arch there's not even a distinction between lib and usr/lib anymore (lib is simply symlinked to usr/lib for quite some time now). Anyway, maybe an includelist could then explicitly whitelist libraries that should be included in any case. Doesn't really make it more overseeable, but resolving library dependencies are not the nicest problem to have in the first place. :)
