### ISSUE TITLE
Unknown module(s) in QT: webkitwidgets

### ISSUE THREAD

**Issue by jalomic** [mltframework/shotcut#649]
Can't build
Windows Qt 5.11

**Comment by ddennedy** [comment]
This is not a bug. Your Qt build is missing the QtWebKit module, which is no longer supported by Qt. We have a SDK that includes the version of Qt that we use with the QtWebKit module plus other dependencies: https://shotcut.org/notes/windowsdev/

I hope you are planning to contribute to Shotcut and not just make an illegitimate fork to sell under your own name.
