### ISSUE TITLE
More libraries missing in distribution

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#652]
Hello,

I'm just installing a new system and thus have a pretty clean Arch Linux installation. There it shows that more library dependencies are missing from the shotcut distribution.

First, shotcut does not start because libxslt is missing. If I install it on my system, this issue is resolved.

Second, shotcut shows a dialog that SDL 2 is missing. As it turns out, the bundled SDL 2 library fails to load because it depends on libXss. If I install libxss on the system, shotcut is able to start.

By the way, some libraries are not set executable in the lib directory. Although it doesn't seem to make a technical difference on Linux, it is inconsistent with the rest of the libraries, and e.g. "ldd" also warns about this when inspecting libraries without execution permission.

**Comment by ddennedy** [comment]
This was already fixed by 4da128ab2 and #684. The fix was comprehensive, not minimal. 
Here is a nightly build you can try: http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-linux-x86_64-181026.tar.bz2
