### ISSUE TITLE
Non-Transparent Transparent Images 

### ISSUE THREAD

**Issue by Kolano** [mltframework/shotcut#655]
Transparent PNG images are not consistently handled as such, instead sometimes using solid black background and obscuring underlying layers.

I may have a sample project for this later. I had tried to work around it by using Mask filters rather than transparent images to mask things out, but that  was buggy too and resulting in crashes/an unrenderable project.

Shotcut v18.10.08 Windows x64 portable

**Comment by ddennedy** [comment]
Unable to reproduce. Provide a file.

**Comment by ddennedy** [comment]
Closing because GPU Effects is unsupported without a patch/pull request. Next version 18.11 makes this more obvious.
