### ISSUE TITLE
Drag and drop multiple mp4 in playlist crash

### ISSUE THREAD

**Issue by NightfallAlicorn** [mltframework/shotcut#661]
`Linux Xubuntu 18.04, shotcut-linux-x86_64-181008.tar.bz2`

I use CTRL + A to select all the videos in a folder and then use CTRL + Left-Click videos to exclude. This is the odd thing. When I click and drag them to the playlist, the first video sound only starts to play and then increasing hangs till it crashes. But if I exclude the files from the folder and just drag the folder containing the mp4 I want, it works perfectly and the first video plays including the video without any crashes.

Just to note I'm dragging 55 files at 328.6 mb. My RAM is way over 3 GB. I believe it's an issue how Shotcut sees multiple files and a folder containing the files being dragged into the playlist. I've tested 2 times both files only and the folder containing them. Files only crashes.

**Comment by NightfallAlicorn** [comment]
Update. It actually crashes with the folder too. Just restarted project. Seems sometimes it crashes and sometimes doesn't.

**Comment by ddennedy** [comment]
Do you have GPU Effects on?

**Comment by NightfallAlicorn** [comment]
I always have it off since it's experimental.

**Comment by ddennedy** [comment]
old, expired, and needs retest
