### ISSUE TITLE
Remove all pending jobs after exporting 70-80 items playlist

### ISSUE THREAD

**Issue by hkskoglund** [mltframework/shotcut#664]
I sometimes find myself in a situation where I have forgot to do some editing when I have started exporting 70-80 items. I press the "pause" to pause, but its cumbersome to remove all pending jobs manually. (Its easier to quit shotcut). It would be easier to have a "remove all pending jobs" option. in the jobs pane.

Pressing Pause says nothing about the changed status of jobs. Maybe the button text could be "resume" after pressing pause, or some other kind of indicator.

**Comment by ddennedy** [comment]
Feature requests are not accepted without a patch.
