### ISSUE TITLE
Incorrect leading zero when batch exporting 10^i-1, i=1,... items

### ISSUE THREAD

**Issue by ochilan** [mltframework/shotcut#677]
Hello,

when exporting 9 items in batch using "Each Playlist Item" in the Export Panel, I noticed that the files were numbered 01..09 instead of 1..9.

I think the culprit is src/docks/encodedock.cpp:997:
`int digits = QString::number(n + 1).size();`
The "+ 1" is superfluous since "n" already is the total count of playlist items (MAIN.playlist()->count()).

**Comment by ddennedy** [comment]
Thank you for finding the bug in the code.
