### ISSUE TITLE
Unable to play timeline in Project pane when opening a saved project

### ISSUE THREAD

**Issue by jwflory** [mltframework/shotcut#678]
## Summary

When I open a saved project and try to play the video in the timeline, the play/pause button changes state, but the cursor does not move and the Project pane appears to be frozen.

## Actual behavior

1. Open saved project (either from file or after opening Shotcut)
2. Click somewhere in timeline (Project pane updates)
3. Click play or hit space bar
4. No visible change
5. Seeking / moving cursor on timeline does not change view in Project pane – it freezes on where I first clicked before pressing play

## Expected behavior

1. Open saved project (either from file or after opening Shotcut)
2. Click somewhere in timeline (Project pane updates)
3. Click play or hit space bar
4. Video plays in Project pane

## How to reproduce

This happens to me every time I open a saved project (see the project file [here](https://pastebin.com/MLubH01V)).

## Environment

* **OS**: Fedora 28
* **Shotcut**: 18.11.18.02

**Comment by ddennedy** [comment]
This is not a build made by us and is unsupported. As the people who made your build to debug it.
