### ISSUE TITLE
15.04.01 - Video Filters Reset after Changing them

### ISSUE THREAD

**Issue by laughterislost** [mltframework/shotcut#68]
This includes not being able to remove said video filters from clip after adding them.

**EDIT**

I have this issue while trying to change the Video Fade Out Filter.

**Comment by ddennedy** [comment]
I do not reproduce this. Please provide more details including OS, where you got Shotcut, whether GPU processing is enabled, and some steps.

**Comment by ddennedy** [comment]
If you double-click a filter or click its checkbox in the filter list, then it toggles whether the filter is enabled. But I am closing this so no further information is provided and not clear how to reproduce.
