### ISSUE TITLE
No composite button on any of timeline tracks

### ISSUE THREAD

**Issue by mabakay** [mltframework/shotcut#685]
Where is the "composite" button?

![composite button not found](https://user-images.githubusercontent.com/1766645/50530395-5163a800-0afd-11e9-923a-913e7f173f44.PNG)

windows: 18.12.23

**Comment by ddennedy** [comment]
This is not a bug. Things change. Click the track header and view properties to disable blending aka compositing.

**Comment by mabakay** [comment]
Thanks
