### ISSUE TITLE
No audio on Ubuntu 18.04 snap: MLT cannot find audio device

### ISSUE THREAD

**Issue by malteneuss** [mltframework/shotcut#688]
When i run shotcut (latest  18.12.23 version) on my Ubuntu 18.04 machine, i can't hear anything.
I get the following logs:
```
[Info   ] <MLT> Failed to open audio device: ALSA: Couldn't open audio device: No such file or directory
[Info   ] <MLT> [sdl2] Try alternative driver: alsa
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
[Info   ] <MLT> [sdl2] Open failed: ALSA: Couldn't open audio device: No such file or directory
[Info   ] <MLT> [sdl2] Try alternative driver: sndio
couldn't open play stream: No such file or directory
[Info   ] <MLT> [sdl2] Open failed: sio_open() failed
[Info   ] <MLT> [sdl2] Try alternative driver: dsp
[Info   ] <MLT> [sdl2] Open failed: No such audio device
[Error  ] <MLT> [consumer sdl2_audio] SDL failed to open audio
```
It seems that i don't have the right dependencies installed (i cannot find any instructions which dependencies to install on shotcut.org), but i have tried `libsdl2-dev` to no avail.
Do you have any suggestions?

**Comment by ddennedy** [comment]
It works for me assuming you are using a snap provided by this project through the snap store and not some alternative. Can you confirm that ALSA audio works on your system and user?
Did you have a previous version that worked?

**Comment by malteneuss** [comment]
Thanks for your quick reply.

I can control the system's audio with `alsamixer` (terminal app) so ALSA should work. This is my first install of shotcut (switching from openshot due to way to many crashes), so no previous working version.

What dependencies do i have to install manually? "Nearly all" is not "all.
```
Since this snap is using classic confinement based on the portable zip above, not all dependencies are bundled, and it has the same run-time requirements as the portable tar.
```
I can't find a list of dependencies for the portable version as well.

**Comment by ddennedy** [comment]
Here is all we have on the dependencies, and this page is linked to from the Downloads page very near to the paragraph you quoted:
https://shotcut.org/notes/linux-dependencies/

Using alsamixer is not a good enough test. Consider using `aplay`. If you have jackd running then it could have the alsa device locked. Shotcut does not directly ALSA; it uses SDL which has different audio providers that it tries except it does not support JACK. If you use JACK, then you should setup PulseAudio because many apps including SDL include a provider for it, and it can cooperate with JACK.

**Comment by malteneuss** [comment]
Oh thanks, i missed that. Maybe you could move that info to the installation page. However, i seem to have all the dependencies installed, even JACK
```
libjack-jackd2-0/bionic,now 1.9.12~dfsg-2 amd64 [installed]
```
although i can't remember having installed it manually.
As you mentioned to have Ubuntu 18.04 yourself, could you tell me what dependencies you manually installed on your machine with `apt`?

Also `aplay music.mp3` plays some sound, so it seems that SDL just doesn't find Alsa. I don't know what could be wrong, since i didn't change any sound configuration from the default Ubuntu settings (i especially didn't setup JACK or anything).
Did you setup anything?

**Comment by ddennedy** [comment]
It is a problem specific to your system that I am not going to troubleshoot for you.

**Comment by ed6767** [comment]
Had the same issue on 19.04, maybe dependances should be added in the snap package?

**Comment by ddennedy** [comment]
Most dependencies are included now but not libasound (ALSA) and JACK since [they are on the AppImage excludelist](https://github.com/AppImage/pkg2appimage/blob/master/excludelist#L78) (our snap, portable archive, and AppImage all use the same build and bundled dependencies).

**Comment by volodalexey** [comment]
> It is a problem specific to your system that I am not going to troubleshoot for you.

I have this problem too.
```
$ lsb_release -a && printf 'Desktop: %s\nSession: %s\n' "$XDG_CURRENT_DESKTOP" "$GDMSESSION"

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
Desktop: i3
Session: i3
```
I have Ubuntu 18.04 with [i3wm](https://i3wm.org/).

Previously I had `Ubuntu 16.04` with `Gnome` on the same laptop and all `Shotcut` versions worked for me (sound worked).
A couple of month ago I upgraded my distro to Ubuntu 18.04 and today I tried `Shotcut` installed by `snap` (v19.06.15).
I do not hear any sound from `Shotcut` (peak meter jumps, I am sure - no muted tracks or volume control) - all other programms work (sound).
I do not see any errors in console.
I also tried `SDL_AUDIODRIVER=pulseaudio shotcut` I see following:
`[Error  ] <MLT> [consumer sdl2_audio] Failed to initialize SDL: Could not setup connection to PulseAudio`

My audio device:
```
$ sudo aplay -l

card 1: PCH [HDA Intel PCH], device 0: ALC668 Analog [ALC668 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

$ lspci -v | grep -A7 -i "audio"

00:03.0 Audio device: Intel Corporation Crystal Well HD Audio Controller (rev 08)
	Subsystem: Intel Corporation Crystal Well HD Audio Controller

00:1b.0 Audio device: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller (rev 05)

$ pacmd list-sinks

1 sink(s) available.
  * index: 0
	name: <alsa_output.pci-0000_00_1b.0.analog-stereo>
	driver: <module-alsa-card.c>
        flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
	state: SUSPENDED
	suspend cause: IDLE 
```

Can you help me?

**Comment by ddennedy** [comment]
I am not sure what is wrong @volodalexey as that info looks pretty good.
I can tell you that the error message comes from a PulseAudio connection failure in SDL:
https://github.com/SDL-mirror/SDL/blob/master/src/audio/pulseaudio/SDL_pulseaudio.c#L305

You can do a web search on "pa_context_connect failed" and get many results that might help you.
My `pacmd list-sinks` output is much more verbose than what you showed in case you did not truncate it.

**Comment by volodalexey** [comment]
Yes. I truncated each of the outputs. If you need full output I can attach it.

**Comment by volodalexey** [comment]
I still do not have audio in i3wm with the recent version of shotcut `19.09.14`. The problem in not in the system (Ubuntu) - however in desktop manager and/or shotcut.
When I start `gnome`WM + `shotcut` - audio works
When I start `i3`WM + `shotcut` - audio fails to work (only in shotcut)
```
[h264 @ 0x47acbc0] Reinit context to 1920x1088, pix_fmt: yuv420p
[Info   ] <MLT> [filter swresample] 2(stereo) s16 44100Hz -> 2(stereo) s16 48000Hz
[Info   ] <MainWindow::open> "/mnt/disk/Documents/eatLinux/Linux/gog_games_id_software/03.mkv" 
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
[Info   ] <MLT> Failed to open audio device: ALSA: Couldn't open audio device: No such file or directory
[Info   ] <MLT> [sdl2] Try alternative driver: alsa
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
[Info   ] <MLT> [sdl2] Open failed: ALSA: Couldn't open audio device: No such file or directory
[Info   ] <MLT> [sdl2] Try alternative driver: sndio
couldn't open play stream: No such file or directory
[Info   ] <MLT> [sdl2] Open failed: sio_open() failed
[Info   ] <MLT> [sdl2] Try alternative driver: dsp
[Info   ] <MLT> [sdl2] Open failed: No such audio device
[Error  ] <MLT> [consumer sdl2_audio] SDL failed to open audio
```

**Comment by volodalexey** [comment]
When I run `driver=pulseaudio shotcut` on i3wm - audio works!

**Comment by akshaysubr** [comment]
I have the same issue. Audio works in gdm but not in i3. Any pointers to why this might be the case?
