### ISSUE TITLE
Linux: project creation from start screen broken

### ISSUE THREAD

**Issue by eszlari** [mltframework/shotcut#689]
https://forum.shotcut.org/t/error-when-creating-project/8992

For some reason, `&` gets added to the path:
```
[Debug  ] <Mlt::Controller::setProjectFolder> project folder "/ho&me/user/test"
```

**Comment by eszlari** [comment]
Maybe @grulja has an idea.

**Comment by ddennedy** [comment]
I suspect there might be something going wrong with temporary QString objects returned from calls to QFileInfo methods.

**Comment by grulja** [comment]
I cannot reproduce that, can you give me better description how to reproduce it? I have never used this app before.

**Comment by eszlari** [comment]
1. Start Shotcut.
2. On the start screen under `New Project > Project name` type in e.g. `"xxx"`.
3. Click the `Start` button below.
4. Observer how a directory named `"xxx"` and a file named `"xxx/xxx.mlt"` should have been created under `/home/<user>/Videos`.

**Comment by grulja** [comment]
Ok, I managed to reproduce. It fails on QDir::mkpath() from some reason, but I have no idea why, because I see you have access to whole filesystem when using "--filesystem=host".

**Comment by eszlari** [comment]
I tried this again, and the file is now successfully created under `/home/user/&Videos/xxx/xxx.mlt`.

The adding of the `&` could be related to: https://bugs.kde.org/show_bug.cgi?id=337491

**Comment by ddennedy** [comment]
According to a user on the forum, the workaround in the KDE bug report worked for him, and he is not using the flatpak.
