### ISSUE TITLE
Transition issue between different sized photos

### ISSUE THREAD

**Issue by poldon** [mltframework/shotcut#692]
O.S.: Linux Mint 19 (Ubuntu 18.04)
Shotcut v19.01.19 BETA

I have 2 photos in a slideshow that each zoom a little bit.  One photo is wider than the other, so its edges show up solid even during the transition as shown below:
![transitionbug](https://user-images.githubusercontent.com/12818275/51634179-3710c480-1f19-11e9-987f-df9946d2c5a0.png)

If both photos take up the complete frame, it looks fine.  This is true both with photos and videos during the transition.  I'm using the Size and Position filter on both of them as well.

What I would prefer to see was the edges would simply fade to black (or whatever background track may be behind it).

**Comment by ddennedy** [comment]
Of course, the edges will be noticeable; they have different sizes and their pixel values are different along the edges. However, I think I see the problem you are experiencing. If the first clip has a Size and Position filter on it; then, in the transition, it does not properly fade out. Unfortunately, I have not found a fix this that will not also break some compositing behavior with multiple tracks. A workaround is to add a Crop with the Center option to the second image to make it fill the screen.

Note: This is issue is not new to this beta.

**Comment by ddennedy** [comment]
A workaround by editing the MLT XML is to locate the `<filter>` with `<property name="shotcut:filter">affineSizePosition</property>` that is a child of the first clip's `<producer>` element. Then, change

    <property name="background">colour:0</property>

to

    <property name="background">colour:0x000000ff</property>

**Comment by poldon** [comment]
Thanks for the workaround, it works well!

**Comment by ddennedy** [comment]
Another workaround: Add an **Alpha Channel: Adjust** filter to the clips before adding the transition.

**Comment by poldon** [comment]
I tried the **Alpha Channel: Adjust** filter on the clips, and I still get the same result with the Size and Position filter on the clips.  The XML workaround above still works though.  Is there a way to at least get an option added to make the transparent background applied through the UI?

**Comment by ddennedy** [comment]
I started working on this tonight (adding Background color to the filter UI), but it is not something I can get done for the next release tomorrow as it requires a change in the engine's component to handle a color change after the filter is created.

**Comment by ddennedy** [comment]
Here is some detail that missing on the **Alpha Channel: Adjust** workaround:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/1146683/79062697-4e88ba00-7c51-11ea-883f-945a2286b640.png">

It goes on an image that does not fill the frame after the Size and Position filter.
Mode = Threshold
Amount = 100
Invert = yes

**Comment by poldon** [comment]
Thanks for the info and getting on it so quickly!  I really don't run into this that often, but I did yesterday again.  Keep up the great work!  Shotcut is progressing quite nicely.

**Comment by ddennedy** [comment]
Fixed in bc12de7c by adding **Background color** parameters to the **Size and Position** and **Rotate and Scale** video filters.
