### ISSUE TITLE
Compile error in util.cpp v19.01.27

### ISSUE THREAD

**Issue by TemporarilyOffline** [mltframework/shotcut#696]
Error Message:

util.cpp: In static member function ‘static uint Util::versionStringToUInt(const QString&)’:
util.cpp:199:5: error: ‘const_reverse_iterator’ is not a member of ‘QList<QString>’
     QList<QString>::const_reverse_iterator i;
     ^
util.cpp:201:10: error: ‘i’ was not declared in this scope
     for (i = list.crbegin(); i != list.crend(); ++i, factor *= 1000)
          ^
util.cpp:201:19: error: ‘class QStringList’ has no member named ‘crbegin’
     for (i = list.crbegin(); i != list.crend(); ++i, factor *= 1000)
                   ^
util.cpp:201:40: error: ‘class QStringList’ has no member named ‘crend’
     for (i = list.crbegin(); i != list.crend(); ++i, factor *= 1000)
                                        ^
Makefile:2527: recipe for target 'util.o' failed
make[1]: *** [util.o] Error 1
make[1]: Leaving directory '/home/steve/Desktop/workspace/shotcut-19.01.27/src'
Makefile:69: recipe for target 'sub-src-make_first' failed
make: *** [sub-src-make_first] Error 2

OS:  Ubuntu 16.04 LTS

Shotcut Version: 19.01.27

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/powerpc-linux-gnu/5/lto-wrapper
Target: powerpc-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.11' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-powerpc/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-powerpc --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-powerpc --with-arch-directory=ppc --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-secureplt --disable-softfloat --with-cpu=default32 --disable-softfloat --enable-targets=powerpc-linux,powerpc64-linux --enable-multiarch --disable-werror --with-long-double-128 --enable-multilib --enable-checking=release --build=powerpc-linux-gnu --host=powerpc-linux-gnu --target=powerpc-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)

**Comment by ddennedy** [comment]
QList::const_reverse_iterator was added in Qt v5.6. No older version is supported by Shotcut or Qt. Qt 5.6 is an old LTS release that is [losing support in March](https://blog.qt.io/blog/2018/11/29/support-qt-5-6-lts-ends-march-2019/). There are 5.9 and 5.12 LTS releases since then. The next version of Shotcut builds are using 5.9.7. We are not going to make changes to our code to support older versions. Patch it yourself.
