### ISSUE TITLE
Segfault on adding audio track

### ISSUE THREAD

**Issue by wundrweapon** [mltframework/shotcut#697]
After installing Shotcut on Void Linux via `xbps-install shotcut` and opening it, the timeline was entirely empty – neither tracks nor buttons were there. I figured I could still work via keyboard shortcuts, so I pressed Ctrl+I to add an audio track. Shotcut immediately crashed. Upon running via terminal, Shotcut printed "Segmentation fault" before closing after repeating the previous steps.

Installing from source yielded no difference in results. All dependencies appear to be installed and at latest version.

**Comment by ddennedy** [comment]
We do not provide support for third party builds (Void Linux xbps). Use one of our builds, debug it yourself, or ask a Void Linux developer to debug it.

**Comment by ddennedy** [comment]
With that said, it sounds like Qt Quick's, which we use, usage of OpenGL is incompatible with your system's OpenGL. There is nothing we will do about removing the dependence on OpenGL, which is stated as requirement in the FAQ.

**Comment by wundrweapon** [comment]
Didn't even see the AppImage first time I came across this; it works just fine. No clue what was wrong with the distro build. C'est la vie
