### ISSUE TITLE
Questen about MediaInfo incostistens (pssible is cosmenic, but...)

### ISSUE THREAD

**Issue by VictorVG** [mltframework/shotcut#702]
OS Win7 SP1 x64m Shotcut all latest versions include v19.01.27 and v19.02 BETA x64, used codec libh264 , h264_nvenc, NVIDIA  GPU GTX 650, GTX 1060.

Source is MPEG4/AVC 640x360 family video (owners object to any publication) full duration 1 h 54 min 46,517 sec factory have variable frame rate (filmed amateur DV/MPEG 4 part 10 camcorder, model is unknown) used preset "Constant frame rate FILM" (manufacturer defined as 23.976 FPS, but device firmware have only one variable frame rate 23,4 FPS - 25.7 FPS mode - is the entry level class for low level  price device manufactured by "Made is noname" :) ) and start part  (~23 min) is highest damaged and end part is not needed.

Common task - cut damaged and end part, zoom up to 720p, set constant frame rate 23,976 FPS and set Russian as default language for audio track. 

Result possible is cosmetics, but I see unexpected oddities (I think their source is libmediainfo) like this:

source is MP4 /AVC have:

Duration                                 : 1 h 31 min
Bit rate                                 : 234 kb/s
Width                                    : 640 pixels
Height                                   : 360 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 23.976 (24000/1001) FPS
Minimum frame rate                       : 23.974 FPS
Maximum frame rate                       : 23.987 FPS

output for constant frame rate 23,976000 FPS and bitrate 1800 Kbit/sec mode is MP4 have:

Duration                                 : 1 h 31 min
Source duration                          : 1 min 54 s
Bit rate mode                            : Variable
Bit rate                                 : 1 749 kb/s
Maximum bit rate                         : 5 400 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (23976/1000) FPS
Original frame rate                      : 23.976 (24000/1001) FPS

I cut out the excess in Avidemux (ADM) - I know it, and I just started Shotcut to learn, then recode for set constant frame rate (ADM can recode output use variable frame rate then I set mode CFR 2 past  average bitrate, ReFrame = 8, frame rate is "constant") in such cases, Shotcut allows you to recalculate the video in the desired format for the hardware player (it does not support variable frame rates).

For information please, see media info output: 
[original_MI.txt](https://github.com/mltframework/shotcut/files/2899369/original_MI.txt)

[final_MI.txt](https://github.com/mltframework/shotcut/files/2899370/final_MI.txt)

exported MediaInfo v18.12 also this field on report show libmediainfo v0.7.97 (used for Media info plugin for Far 3.0 v3.12.797.4400).

Possible is cosmetic bug libmediainfo, but not needed. :)

**Comment by VictorVG** [comment]
Additional - some MI out can see if use as source any MKV, but I still do not understand what causes this behavior of the program. For example, in ADM I did not see such a phenomenon, but in XviD4PSP v7 it is also sometimes found, but extremely rare.

As a test example, you can take the "corrected" videos from YouTube (I don’t know why they do it, but the guys uploaded family videos as 1080p, and a spoiled demo in 240p or 360p was downloaded and a message was displayed that the full version of the video was paid (here overdone :)).

**Comment by ddennedy** [comment]
What is the problem or question? I do not see a problem in final_MI.txt.

If you are changing Export > Advanced > Frames/sec, then do not do that. Instead, choose or create a Video Mode in either Settings or New Project at the beginning and then export as-is.

**Comment by VictorVG** [comment]
Ok! I don't know it.:(
