### ISSUE TITLE
Text filter is missing but GPU processing is disabled

### ISSUE THREAD

**Issue by Barracuda72** [mltframework/shotcut#705]
OS: Gentoo Linux
Shotcut version 19.01.24

Just as title says, text filter is missing from filters menu despite the fact that GPU processing is disabled in config file ~/.config/Meltytech/Shotcut.conf (and I don't even see the option for it anywhere on the interface). 3D text filter is also missing. 

(Can't directly upload images for some reason)
https://i.ibb.co/zhXJhms/2019-03-03-21-24-45.png
https://i.ibb.co/sQwTg7S/2019-03-03-21-25-11.png

**Comment by Barracuda72** [comment]
Actually, I can't find many filters mentioned in tutorials, forum posts and https://shotcut.org/features/ - Blur, Mask, Size and Position, Rotate, Timer, etc. There are no errors in console except the warning about missing some third-party library. What may be wrong with my installation of Shotcut?

**Comment by bmatherly** [comment]
Where did you get your Shotcut Package?

Let us know if you can recreate the problem using the official package downloaded from here:
https://shotcut.org/download/

Also, in your screenshot, you have typed "te" into the search text box. So the filter list is only returning results that contain "te" in the name of the filter. Clear the filter search box and you will see more results.

**Comment by ddennedy** [comment]
This is a [known issue](https://forum.shotcut.org/t/text-filter-missing-on-gentoo-linux/9478/2), but we do not make or support the gentoo package nor do any of the developers run gentoo in order to help troubleshoot it. Talk to gentoo.

**Comment by Barracuda72** [comment]
> Where did you get your Shotcut Package?
Gentoo Portage, of course.
> Let us know if you can recreate the problem using the official package
Sorry, installing software from third-party resources is off limits.
> Also, in your screenshot, you have typed "te" into the search text box. So the filter list is only returning results that contain "te" in the name of the filter. Clear the filter search box and you will see more results.
Come on, guys, I'm not THAT stupid =D
> This is a known issue, but we do not make or support the gentoo package nor do any of the developers run gentoo in order to help troubleshoot it. Talk to gentoo.
Well, no, it's something that causing malfunction in _you_ software, so it should be handled gracefully by it. It wouldn't hurt if at startup (at first startup?) Shotcut would display a warning message about the plugins that it couldn't load and the cause for that. It's not some-kind-of-tricky-hacking, it's just informing the user about the thing that already happened and has known cause. E.g. "The following filters couldn't be loaded because you MLT installation lacks required features:" then list of the Shotcut filters and corresponding MLT filters that they rely on. Or "The following filters is incompatible with GPU rendering and were disabled:" and so on. It's very simple thing, but it would save so much time for the people. Be a little graceful to the user, it won't kill any kittens.
P.S.: To one who will also stumble upon issue - media-libs/mlt should be compiled with "fftw" USE flag.

**Comment by Barracuda72** [comment]
And also for some obscure reason Shotcut expects melt binary to be named as "qmelt". It's neither so in Ubuntu/Debian/Gentoo (it's just "melt") nor in RPM-based (it's "mlt-melt"). Please a;so give it a thought. This is very small thing, so I don't want to create separare issue for it.

**Comment by bmatherly** [comment]
> Shotcut would display a warning message about the plugins that it couldn't load and the cause for that. It's not some-kind-of-tricky-hacking, it's just informing the user about the thing that already happened and has known cause. E.g. "The following filters couldn't be loaded because you MLT installation lacks required features:" then list of the Shotcut filters and corresponding MLT filters that they rely on. Or "The following filters is incompatible with GPU rendering and were disabled:" and so on. It's very simple thing, but it would save so much time for the people.

Those ideas are not bad. But no one here volunteers to implement them. Patch welcome :)

> Be a little graceful to the user, it won't kill any kittens.

We are graceful to the user by supplying a fully supported package that works on most platforms. We provide monthly releases with the latest features. People who use the provided package generally have a good experience.

> Shotcut expects melt binary to be named as "qmelt"

Have you inspected the official build script?
https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut.sh
Search for qmelt and you will quickly understand.

**Comment by Barracuda72** [comment]
> Those ideas are not bad. But no one here volunteers to implement them. Patch welcome :)

Oh, if only we all had the time and will... I've already resolved my problem (thanks to ddennedy, BTW, for pointing out in right direction).

> We are graceful to the user by supplying a fully supported package that works on most platforms. We provide monthly releases with the latest features. People who use the provided package generally have a good experience.

OK, you are developers, it's your choice (and as a dev I understand you quite well).

> Have you inspected the official build script?

Only now and only a quick glance. It's some different binary from melt, it seems (Qt wrapper?), but I just symlinked /usr/bin/qmelt to /usr/bin/melt and everything works. (BTW, MLT on my machine is also compiled with Qt5, but there is no qmelt anythere).

**Comment by ddennedy** [comment]
> Shotcut would display a warning message about the plugins that it couldn't load and the cause for that.

Not a bad idea, but the problem is that our binary releases often depend on newer versions of FFmpeg, frei0r, and MLT than appears in most distros. In that case, distro users would be nagged, which would get annoying. Of course, we could add an ignore checkbox to that dialog.

> for some obscure reason Shotcut expects melt binary to be named as "qmelt"

qmelt is not so obscure. It is a wrapper provided by WebVfx that makes Qt and GPU effects (i.e. Movit, probably another thing missing in your package) work reliably. WebVfx is a separate project that Shotcut makes fairly heavy use of.  This gentoo package is very poor quality, and I resent that it is called Shotcut. It would be great if you can improve it. The [flatpak config](https://github.com/flathub/org.shotcut.Shotcut/blob/master/org.shotcut.Shotcut.yaml) represents a rather concise and comprehensive definition of a valid build (much cleaner than the 2500 line bash script we use to make all builds). Please note, however, that Shotcut does not depend on KDE, the flatpak developer chose that as a base for some reason (probably more bundled dependencies).
