### ISSUE TITLE
How to add video or audio

### ISSUE THREAD

**Issue by mrkaban** [mltframework/shotcut#708]
Hello. Thank you very much for the program with such a license. I apologize for the stupid question, but how to add audio or video to a track? I understood how to add to the library, and I also understood how to add an audio or video track, but I didn’t understand how to add music or video to a track at all.

I used to use the program and there were no such problems a few years ago. Earlier, as it seems to me, I just transferred the materials to the track.

Windows 10 x64.

**Comment by ddennedy** [comment]
This is not a bug. There is plenty of beginner info on the web site, YouTube, and in the forum. Use those resources or purchase this course:
https://betterbusiness.zenler.com/courses/video-editing-made-easy-with-shotcut-video-editor&affiliate=1367
