### ISSUE TITLE
Text pixelation with large resolution backgrounds

### ISSUE THREAD

**Issue by DaveJarvis** [mltframework/shotcut#711]
**Replicate**
Reproducible 100% of the time:
1. Create a new video.
1. Create a background SVG file ([bg-svg.txt](https://github.com/mltframework/shotcut/files/2967827/bg-svg.txt)).
1. Drop the background image onto the video timeline, extended a few seconds.
1. Add text to the image.
1. Change the text colour from white to bright orange.
1. Render as YouTube settings (1080p video at 60fps).
1. Play the video at 2560x1600.

**Expected Results**
The resulting text appears smooth.

**Actual Results**
The text has jagged little edges (preview at 2560x1600 or greater to see the pixelation):

![pixelated](https://user-images.githubusercontent.com/2131950/54382375-175e6880-464d-11e9-87d3-6df5d26c54e6.png)

**Related**
Looks like this issue may have been encountered by a few others:
* https://forum.shotcut.org/t/unexpected-pixelation/5746/5
* https://www.reddit.com/r/shotcut/comments/79cgyu/shotcut_text_is_pixelated_fixes/

**Work Around**
Edit the background SVG to be 1920 x 1080 pixels.

**Version**
19.02.28 on Linux.

**Comment by ddennedy** [comment]
I think the problem is that the image gets rendered to full resolution, text composited, and then scaled to project resolution. Then, export interpolation setting probably has a bearing. Is it less of a problem when using Bicubic and Hyper/Lanczos?
@bmatherly can you please take a look at this?

**Comment by ddennedy** [comment]
I think another workaround is to use a text clip (Open Other > Text) on a video track above the background image on a lower video track.

**Comment by DaveJarvis** [comment]
> full resolution, text composited, and then scaled to project resolution

No interpolation settings improved the result. The only way to resolve the issue was specifically setting the background image resolution to match the video export format resolution. (Note that the issue probably isn't as visible when using white text because the pixelation itself seems to appear white regardless of text colour.)

**Comment by bmatherly** [comment]
I did some testing. I do not think the image size is the problem. I think the problem is that the image is 100% transparent. I can recreate the same problem by putting text on a transparent color clip. 

1) New shotcut project with mode set to 1080
2) Open color clip (set color to transparent)
3) Add text filter
4) Observe text pixelation
5) In the properties panel, change the text color to black
6) Observe the text is not pixelated

Can someone else confirm my test?

For another work-around, try using the same size image that is black instead of transparent.

**Comment by bmatherly** [comment]
Another workaround is to give the text a background color that is non-transparent.

**Comment by bmatherly** [comment]
Some more information/explanation:

The "outline" in Shotcut maps to the width of the QPen. I learned that a QPen width of zero is a special indication that it is a cosmetic pen:

> A line width of zero indicates a cosmetic pen. This means that the pen width is always drawn one pixel wide, independent of the transformation set on the painter.

So a width of "0" isn't actually possible. And a cosmetic pen will not give the user the results they expect. Also, the pen (outline) is used to anti-alias the shape. Here is the issue: if the outline has an alpha of zero and the background has an alpha of zero, then the antialias pixels won't be drawn - which causes the jagged edges.

As a result of this, I suggest that we change the outline option to have a minimum of 1. It would still be possible for someone to break the anti-aliasing by setting the outline color to be transparent. But it would only be a problem if the background of the frame is also transparent.

**Comment by bmatherly** [comment]
Thinking about this some more... I think that just setting the default thickness to 1 would resolve this.

**Comment by ddennedy** [comment]
Thanks, @bmatherly, but I found it is also easy to get into this situation when you have Text with thickness 0 on transparent clip (text clip) on a video track higher than V1 with nothing on V1. It would be nice to remove this sharp edge entirely. Why not set the minimum thickness to 1, and change the default Outline color to transparent? When you change the outline color, it defaults to change to opaque (at least on Windows). That would also solve the minor usability issue that today if you simply change the outline color, you do not see a change until you increase thickness.

**Comment by bmatherly** [comment]
Did you test setting thickness to 1 with a transparent outline color? Did it work around the problem for you? As I recall, it didn't fix the problem in my test scenario. Maybe I need to try again.

Changing the outline color to opaque might be an idea. We would want to make sure we don't surprise the user if they click the button and then decide to not change anything.

**Comment by ddennedy** [comment]
> Did you test setting thickness to 1 with a transparent outline color?

I thought it worked when I wrote that but not so upon retesting.

> Changing the outline color to opaque might be an idea.

I meant to only change the default outline color to transparent. It already switches to opaque when the current color is transparent and the user picks a new color. I do not want to change anything there.

I see that in Open Other > Text, I chose to default the outline to translucent black with thickness 3. Could switch to that for consistency and dull this sharp edge.

Another idea is that when thickness is 0, set the MLT filter's outline=1 and olcolour=fgcolour.

**Comment by bmatherly** [comment]
I had tried that, too, by fiddling with the code here:
https://github.com/mltframework/mlt/blob/master/src/modules/qt/filter_qtext.cpp#L138

I was really rooting for that solution, but it didn't smooth the edges in my test case, but maybe it would work for some cases. 

My theory is that it is antialiasing by trying to blend text color with outline color. But if the colors are the same, the blend ends up being 100% text color and therefore no antialiasing.
