### ISSUE TITLE
Cannot export video (shotcut 64 19.02.28/Windows 10)

### ISSUE THREAD

**Issue by GF47** [mltframework/shotcut#714]
I chose the YouTube preset and made some code rate changes. When I specified the output location, the job was completed in an instant, but the correct file was not output.

The following is the contents of the job log:

----------------------------------------------------------------
```bat
mlt_repository_init: failed to dlopen D:\Program Files\Shotcut\lib\mlt/libmltgtk2.dll
  ("D:\Program Files\Shotcut\lib\mlt\libmltgtk2.dll": �Ҳ���ָ���ĳ�����)
mlt_repository_init: failed to dlopen D:\Program Files\Shotcut\lib\mlt/libmltjackrack.dll
  ("D:\Program Files\Shotcut\lib\mlt\libmltjackrack.dll": �Ҳ���ָ���ĳ�����)
mlt_repository_init: failed to dlopen D:\Program Files\Shotcut\lib\mlt/libmltxml.dll
  ("D:\Program Files\Shotcut\lib\mlt\libmltxml.dll": �Ҳ���ָ���ĳ�����)
[AVIOContext @ 00000000048fa840] Statistics: 8479 bytes read, 0 seeks
[AVIOContext @ 00000000048fa840] Statistics: 8479 bytes read, 0 seeks
Failed to load "C:/Users/GF47/AppData/Local/Temp/shotcut-L15316.mlt"
[AVIOContext @ 00000000049bbfc0] Statistics: 8479 bytes read, 0 seeks
[AVIOContext @ 00000000049bbfc0] Statistics: 8479 bytes read, 0 seeks
Failed to load "C:/Users/GF47/AppData/Local/Temp/shotcut-L15316.mlt"
Completed successfully in 00:00:00
````
----------------------------------------------------------------

Then the contents of the application log:

----------------------------------------------------------------
```
[Debug  ] <Mlt::Controller::setProjectFolder> project folder "E:/Work/Video_Projects/233" 
[Debug  ] <MainWindow::setAudioChannels> 2 
[Debug  ] <Mlt::Controller::setAudioChannels> 2 
[Debug  ] <MLT> [mlt_producer avformat-novalidate] "E:/Work/blender/Animation/0020-0092.mkv" checking VFR: pkt.duration %I64d
[Debug  ] <TimelineDock::setSelection> Changing selection to ()  trackIndex -1 isMultitrack true 
[Info   ] <MainWindow::open> "E:/Work/Video_Projects/233/233.mlt" 
[Warning] <> libpng warning: iCCP: known incorrect sRGB profile
[Warning] <> libpng warning: iCCP: known incorrect sRGB profile
[Info   ] <MLT> Failed to open audio device: XAudio2: XAudio2Create() failed at open.
[Info   ] <MLT> [sdl2] Try alternative driver: xaudio2
[Info   ] <MLT> [consumer sdl2_audio] Audio Opened: driver=xaudio2 channels=2 frequency=48000
[Debug  ] <LeapNetworkListener::onDisconnected> Disconnected from Leap Motion 
[Debug  ] <LeapNetworkListener::onError> Leap Motion WebSocket error: "Connection refused" 
[Debug  ] <MLT> [consumer sdl2_audio] dropped video frame 1
[Debug  ] <MLT> [consumer sdl2_audio] dropped video frame 2
[Debug  ] <MLT> [consumer sdl2_audio] dropped video frame 3

...

[Debug  ] <MLT> [consumer sdl2_audio] dropped video frame 80
[Debug  ] <MLT> [consumer sdl2_audio] dropped video frame 81
[Debug  ] <MLT> [consumer sdl2_audio] dropped video frame 82
[Debug  ] <MLT> [mlt_producer avformat-novalidate] "E:/Work/blender/Animation/0020-0092.mkv" checking VFR: pkt.duration %I64d
[Debug  ] <MLT> [consumer sdl2_audio] dropped video frame 83
[Debug  ] <EncodeDock::on_encodeButton_clicked> 168301297664 bytes available on "C:/" 
[Debug  ] <MeltJob::start> "D:/Program Files/Shotcut/qmelt.exe" ("-verbose", "-progress2", "-abort", "C:/Users/GF47/AppData/Local/Temp/shotcut-L15316.mlt") 
[Info   ] <AbstractJob::onFinished> job succeeeded 
```
----------------------------------------------------------------

![SharedScreenshot](https://user-images.githubusercontent.com/16915758/54608276-5cd6c780-4a8b-11e9-9583-333bd36b22f8.jpg)

**Comment by ddennedy** [comment]
The XML DLL (libmltxml.dll) is failing to load, which is required to process the export job XML. I do not know why; no one else has reported this problem, and the error in your log contains garbage characters. What is interesting is that Shotcut GUI depends on this DLL as well, and that must be working. The export job is executed using a different, console program called qmelt, and that is the program failing to load the DLL.
Did a previous version of Shotcut work for you, or is this your first version to try?

Something to try: In D:\Program Files\Shotcut, create an empty file named `qmelt.exe.local`. There is a `shotcut.exe.local` that is empty if you want to simply copy it. Does it work after that?

**Comment by GF47** [comment]
These characters are caused by East Asian characters. Don't mind them, LOL.
And I use you way to creat the empty local file,it works.Then I tried to delete the file, emmm, it still works fine.
Maybe because I did something and made the exe not have enough permissions,or just a little joke from Microsoft.
Thank you for solving my problem,the shotcut works well now.Many thanks.
