### ISSUE TITLE
First clip does not start at Time Zero

### ISSUE THREAD

**Issue by andrewk8** [mltframework/shotcut#715]
Windows 10 x64 1810 and Shotcut 19.02.28

If you finish a project and start a new one, when you add the first clip to the timeline, it does not start at time zero.

Note in the attached video.  In the new project, the playhead is way to the right.  When I drag a new clip onto the playlist, then drag that onto the timeline, there is a lot of empty space between time zero and the start of the first clip.

It's like it remembers the playhead position from the previous project and uses it as the insertion point.

When you add the first clip to the timeline, it should start at time zero.
[Drop Video to Timeline.zip](https://github.com/mltframework/shotcut/files/3000866/Drop.Video.to.Timeline.zip)

**Comment by ddennedy** [comment]
Thanks, fixed for the next release.
