### ISSUE TITLE
Ошибка в экспорте

### ISSUE THREAD

**Issue by SUREFAN** [mltframework/shotcut#717]
У меня проблема файл который я делал (проект)
НЕ может экспортироваться, я уже сбрасывал настройки,
но переустанавливать я не собираюсь!

![Screenshot_2](https://user-images.githubusercontent.com/48901755/54897815-f44c7800-4eda-11e9-93a2-0d3d2f6a341f.png)

**Comment by ddennedy** [comment]
We only accept English for a big report.

**Comment by SUREFAN** [comment]
I had a problem.
I can not be exported
but I'm not going to reinstall!
![image](https://user-images.githubusercontent.com/48901755/54918021-36db7800-4f0e-11e9-85f7-b340f5417caf.png)

**Comment by ddennedy** [comment]
There is not enough information and unable to reproduce. You need to provide the error message or job log by right-clicking the failed job and choosing the the log item. You might also need to provide the job XML. Before doing so, I see you have hardware encoding turned on. You should try by turning that off. Hardware encoding does not work with every combination of export setting including resolution and frame rate, and that is not the fault of Shotcut.
