### ISSUE TITLE
Cannot add a new video

### ISSUE THREAD

**Issue by Stalker-Elric** [mltframework/shotcut#723]
Hi.

I cannot add new videos to the track. If I open a new file, it read it very fast or maybe just the begining (like 1.08s) If I add it to the track it's still short. I have already added several videos to the track without problems and now it wont add new ones. It does it with any video now.

I'm on windows 7, Shotcut 19.02.28

**Comment by ddennedy** [comment]
There are multiple ways to add clips to the timeline. Did you try all of them or only drag-n-drop. If drop stops working you need to restart the app. Otherwise, I need the exact steps that breaks drop as I do not know them. Until then i cannot reproduce this bug and fix it.
