### ISSUE TITLE
error: 'class Mlt::Producer' has no member named 'get_creation_time'

### ISSUE THREAD

**Issue by martinkg** [mltframework/shotcut#728]
Hi,
I' am trying to compile shotcut-19.04.21 on Fedora Linux 30, but this fails with the following
error message:

`g++ -c -pipe -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wall -W -D_REENTRANT -fPIC -DSHOTCUT_VERSION=\"19.04.21.02\" -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WEBKITWIDGETS_LIB -DQT_QUICKWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_WEBKIT_LIB -DQT_MULTIMEDIA_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -I../CuteLogger/include -isystem /usr/include/mlt++ -isystem /usr/include/mlt -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtOpenGL -isystem /usr/include/qt5/QtPrintSupport -isystem /usr/include/qt5/QtWebKitWidgets -isystem /usr/include/qt5/QtQuickWidgets -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtQuick/5.12.1 -isystem /usr/include/qt5/QtQuick/5.12.1/QtQuick -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtWebKit -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtGui/5.12.1 -isystem /usr/include/qt5/QtGui/5.12.1/QtGui -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtQml/5.12.1 -isystem /usr/include/qt5/QtQml/5.12.1/QtQml -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtWebSockets -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtCore/5.12.1 -isystem /usr/include/qt5/QtCore/5.12.1/QtCore -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o mltcontroller.o mltcontroller.cpp
mltcontroller.cpp: In member function 'void Mlt::Controller::lockCreationTime(Mlt::Producer*) const':
mltcontroller.cpp:929:43: error: 'class Mlt::Producer' has no member named 'get_creation_time'
  929 |         int64_t creation_time = producer->get_creation_time();
      |                                           ^~~~~~~~~~~~~~~~~
mltcontroller.cpp:931:23: error: 'class Mlt::Producer' has no member named 'set_creation_time'
  931 |             producer->set_creation_time(creation_time);
      |                       ^~~~~~~~~~~~~~~~~
mltcontroller.cpp: In member function 'bool Mlt::Controller::enableJack(bool)':
mltcontroller.cpp:306:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
  306 |                 m_jackFilter->set("out_8", "system:playback_8");
      |                 ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mltcontroller.cpp:307:13: note: here
  307 |             case 7:
      |             ^~~~
mltcontroller.cpp:309:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
  309 |                 m_jackFilter->set("out_7", "system:playback_7");
      |                 ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mltcontroller.cpp:310:13: note: here
  310 |             case 6:
      |             ^~~~
mltcontroller.cpp:312:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
  312 |                 m_jackFilter->set("out_6", "system:playback_6");
      |                 ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mltcontroller.cpp:313:13: note: here
  313 |             case 5:
      |             ^~~~
mltcontroller.cpp:315:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
  315 |                 m_jackFilter->set("out_5", "system:playback_5");
      |                 ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mltcontroller.cpp:316:13: note: here
  316 |             case 4:
      |             ^~~~
mltcontroller.cpp:318:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
  318 |                 m_jackFilter->set("out_4", "system:playback_4");
      |                 ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mltcontroller.cpp:319:13: note: here
  319 |             case 3:
      |             ^~~~
mltcontroller.cpp:321:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
  321 |                 m_jackFilter->set("out_3", "system:playback_3");
      |                 ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mltcontroller.cpp:322:13: note: here
  322 |             case 2:
      |             ^~~~
mltcontroller.cpp:324:34: warning: this statement may fall through [-Wimplicit-fallthrough=]
  324 |                 m_jackFilter->set("out_2", "system:playback_2");
      |                 ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mltcontroller.cpp:325:13: note: here
  325 |             case 1:
      |             ^~~~
make[1]: *** [Makefile:2408: mltcontroller.o] Error 1
make[1]: Leaving directory '/home/martin/rpmbuild/BUILD/shotcut-19.04.21/src'
`

**Comment by bmatherly** [comment]
Your version of MLT is too old for the version of Shotcut you are trying to compile. You would need to build against MLT master or choose an older Shotcut version to build.

**Comment by martinkg** [comment]
hmm, on my system, the following mlt version is installed:

python3-mlt-6.14.0-1.fc30.x86_64
mlt-6.14.0-1.fc30.x86_64
mlt-devel-6.14.0-1.fc30.x86_64

**Comment by bmatherly** [comment]
shotcut-19.04.21 does not build against MLT-6.14.0. I understand that is the latest MLT release - but shotcut-19.04.21 requires MLT master to build.

**Comment by martinkg** [comment]
ok, that's true, shotcut19.04.21 requires MLT master version, i have tested.

**Comment by marillat** [comment]
> shotcut-19.04.21 does not build against MLT-6.14.0. I understand that is the latest MLT release - but shotcut-19.04.21 requires MLT master to build.

A new MLT release isn't scheduled ?

It's better to work with release than master. What's happen if the API is changed in master and break shotcut ?

**Comment by ddennedy** [comment]
@marillat  see #736 about new MLT v6.16.0

**Comment by marillat** [comment]
> @marillat see #736 about new MLT v6.16.0

Thank you very much @ddennedy  for the new 6.16.0 release
