### ISSUE TITLE
Crash changing Color Range to Full (JPEG)

### ISSUE THREAD

**Issue by andrewk8** [mltframework/shotcut#729]
Windows 10 x64 October 2018 and Shotcut Windows portable zips 19.02 and 19.04.23 beta.

Trying to re-master some poorly-converted videos.  Some sources have Full color range, but are not imported that way. Sometimes when you change the Color Range Property, Shotcut crashes.  Crashes don't happen 100% of the time.  The below sequence and attached sample seems to reliably reproduce the crash in 19.04.23 beta. Not reporting it as a new issue in the beta because I've had this issue in 19.02 and previous versions, so submitting as a stand-alone bug.

1. After running shotcut for a while ... close or new.
2. Drag video to playlist.
3. Drag video from playlist to timeline.
4. Pick clip properties.
5. Change color range to full.

[Color Range Full Crash.zip](https://github.com/mltframework/shotcut/files/3114837/Color.Range.Full.Crash.zip)

**Comment by ddennedy** [comment]
I have not reproduced this.

> 1. After running shotcut for a while ... close or new.

There was a bug fix recently to fix a crash upon File > New or Close. That could be related, but I see you also tried the 19.04 beta. Do you think this step is required? For now, I am not doing "a while" but simply loading a fairly complex project, playing a little of it, and then closing it.

**Comment by ddennedy** [comment]
Also, I just made a different fix when changing speed that could be related:
https://forum.shotcut.org/t/v19-04-beta-now-available/10709/10?u=shotcut
