### ISSUE TITLE
Sound goes out of synch with video with MKV from guvcview. (variable framerate)

### ISSUE THREAD

**Issue by DanielKrawisz** [mltframework/shotcut#73]
Every time I try to edit a video the sound goes out of synch. This happens when I change my position in the video, when I try to move a clip around, or when I try to split the video at some point. This happens over and over and it's too serious for me to finish my project.

**Comment by pez4brian** [comment]
What version are you using? 15.05.02 fixed a similar sounding issue.
http://shotcutapp.blogspot.com/2015/05/version-1505-re-released.html
If you are using 15.05 and you upgrade to 15.05.02, you will have to start your project over since the bug in 15.05 was in the project file itself.

**Comment by DanielKrawisz** [comment]
Hey, sorry I should have given more information like that. I had just downloaded the latest version available that I could find, which was 15.05.06 and I was using it on Ubuntu 14.04.

**Comment by ddennedy** [comment]
15.05.02 was the buggy version. It is 15.05.06 that is the re-release version number. If that is not the problem, if it is a more subtle drift, then please provide some information on the source file formats you are using and how you obtained them (e.g. camera model, created by software X). Also, please let us know how you encoded it and what player you used to check the result.

**Comment by DanielKrawisz** [comment]
The file was an mkv file recorded in GTK UVC video viewer and I viewed the encoded file later in Videos, which is a program that comes with linux. I also uploaded it to youtube because I wasn't paying close enough attention, so you can see it here. https://www.youtube.com/watch?v=CEn29v1ScGY I've tried to re-do the editing, but every time I try to load the project and move the video over to make room for the title screen, the audio goes way off by about 5 seconds.

**Comment by ddennedy** [comment]
OK, yeah, that is really bad. It would be great if you can zip up a small project exhibiting the problem including the source mkvs, .mlt project file, and your encoded output; and upload it to http://www.shotcut.org/bin/view/Shotcut/SupportUpload

**Comment by DanielKrawisz** [comment]
Well I tried to reproduce the problem with a short video that I recorded just now, but I wasn't able to. Maybe the problem has to do with working with giant files? The file I originally recorded to produce the youtube link up there was around 1.2 gb long and almost half an hour of video. Is it ok if I upload something that big?

**Comment by ddennedy** [comment]
No, you cannot upload something that big. There might be something funky happening with the muxed (combined) audio/video parsing. To workaround the problem, you might try to separate the source audio as a WAV file and muting the video track. To help try to reproduce the bug, it would be nice if you can send the output of 'mediainfo your.mkv' or 'ffprobe your.mkv' or 'melt your.mkv -consumer xml' Thanks

**Comment by ddennedy** [comment]
Also, do the long source files stay in sync when simply played in Shotcut? Try seeking halfway into the file, let it play for 15 minutes, and then assess the sync. Then, do the same in the Videos app.

**Comment by DanielKrawisz** [comment]
The long videos usually stay in sync when I click around in the middle of the file, but not always. Sometimes they do start playing out of sync, but it is back in synch if I click somewhere else in the video. Thanks for the tip. I'll try what you suggest with the wav sound output. I'll try to find the output you mentioned and upload it.

**Comment by DanielKrawisz** [comment]
Hey, I have an update on this problem. I tried doing what you suggested and I exported the audio separately and I muted the audio in the video track. I experienced a very similar problem than before, only now I can see what's happening a lot more clearly. I added a title screen (png image), and then I moved the video track right next to it and the video track snapped in place. However, when I moved the separate audio track, it snapped into place at the wrong time. It was about 1/3 of a second too early or so. This amounts to the same problem I had before. 

Can you tell me more about exporting the output of 'mediainfo your.mkv' or 'ffprobe your.mkv' or 'melt your.mkv -consumer xml' ? When and where would I find these files?

**Comment by ddennedy** [comment]
If the a/v sync is out immediately after seeking, then the file is not suitable for editing. Video editing requires frame accuracy. I installed guvcview to see how the file is created, and I see from mediainfo that it created a variable framerate file, which is not supported by Shotcut or most video editors for that matter. I hate it when tools like this or screen capture programs record in odd ways (sometimes just by default) that only really works well in a video player and not a video editor. Therefore, you must convert the file to something else to use it for editing. What to convert it to and what tool? There are so many options. I tried using Shotcut for my test, but my webcam only provides 5 fps video making it difficult to judge. In any case you can try this:
1. Start Shotcut without a project or clip loaded.
2. Change Settings > Video mode to Automatic if not already.
3. Open the MKV file.
4. Click Encode on the main toolbar.
5. Choose the preset lossless/ProRes
6. Click Encode File.
7. Give it a name and click OK.
8. Wait for the job to finish.
9. Double-click the finished job to open in the Shotcut player.
10. See if it works better.

Also, for working with a separate audio file on an audio track, you can turn off snapping using the button on the timeline toolbar to allow for more fine adjustment.
