### ISSUE TITLE
Whenever I export a video on shotcut editing software it goes right to 100% and does not show up anywhere I dowload it to.

### ISSUE THREAD

**Issue by exoticallytoxicyt** [mltframework/shotcut#732]
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

**Comment by ddennedy** [comment]
Unable to reproduce. Not enough information and you did not follow the instructions to report bug.
