### ISSUE TITLE
Cannot export video with chroma key filter retaining alpha transparency

### ISSUE THREAD

**Issue by samoshkin** [mltframework/shotcut#734]
I have a footage with a green screen on the background. I'm going to use Chroma Key to remove it and use transparent fill color in place of it. I'm not going to compose it with another video track like background image or another video in the Shotcut. I just want to export it to a new video file with alpha transparency in place of green color. Why? - because then I want to import it into another tool where I'm creating my screencast.

MacOS 10.11.5 El Capitan.
Shotcut 19.02.28

So I've read these posts, but none of the solutions explained here work for me.
https://forum.shotcut.org/t/webm-vp9-clip-not-showing-alpha/5359/6
https://forum.shotcut.org/t/how-can-i-create-a-video-clip-with-a-transparent-background/7797/3

What I've tried so far.

**Solution 1. Using Timeline** 
- "Green screen video + chroma key filter" as Video Track 2 on a timeline
- Video track 1 is beneath with the transparent #FF000000 color of same duration (Open Other -> Color(transparent), then drag to the timeline)
- Preview window shows that chroma keying is correctly applied
https://monosnap.com/file/z0kxFYatzRzSR3Stx2W5q9pv5Uru1i.png

- Now export the "Timeline" with one of the presets with alpha transparency, in our case it's Quicktime Animation (mov). I also have tried other options.
http://take.ms/SQTFM

Then when I try to import it back into the Shotcut or to another tool like ActivePresenter, solid black background is shown and there's no transparency. Although mediainfo shows that RGBA is used for color space.
https://monosnap.com/file/7tTFzP1Sy3r508m4IRHSuGywsf8P48.png

```
$ mediainfo result.mov
Frame rate mode                          : Constant
Frame rate                               : 30.000 FPS
Color space                              : RGBA
Bit depth                                : 8 bits
```

So seems it works in the Shotcut when composing several video tracks, but then alpha transparency is lost during export.

**Solution 2. Using Source video. No Timeline**
Next I decide to test it without chroma key filter at all. I've just created created a single clip with transparent fill color, like Open Other -> Color(transparent). It shows it in a Source preview. This time I don't drag it to the Timeline, just mark some range and repeat the export steps but pick the source clip in the From dropdown, not the "Timeline" option. So I expect the simple transparent video only at the output. Then I import it into ActivePresenter, and it works - transparency is there.
http://take.ms/2yZhf

**Solution 3. Using Source Video. No Timeline. Plus ChromaKey effect.**
As soon as solution 2 ends up with transparency in the output video, I just pick up my footage with green background, import it as a file, but don't drag to the Timeline. Then I've added the Chroma Key filter, and finally export it. Everything is  similar to solution 2, except that the real footage is used instead of full transparent clip.

Unfortunately it does not work. It's strange, but now the output is semi transparent. Green background is still there, but not fully removed. I don't understand why it's semi transparent and why green background is still there, as I use the very same settings for Chroma key filter as in the Solution 1, where it worked and perfectly removed all green background.
http://take.ms/zSt1Z

I'm almost out of ideas. Please, help.

**Comment by ddennedy** [comment]
Solution 1 works if you simply remove V1 after you are done using the background to adjust the key.

Solution 3 works for me. After doing solution 1, I simply used Copy to copy the timeline clip with its filter to the Source player and exported it from there. I see your screenshot, but I have no explanation other than something in filter parameters was wrong. If you are using the eye dropper to pick your color, you may have picked a stray color not consistent with what you staged in #1. You can use Copy/Paste in Filters, or you can Copy the timeline clip to Source as I have done.

**Comment by samoshkin** [comment]
Thank you, @ddennedy.

What codec are you using, except that Quicktime MOV container + qtrle codec. Maybe I have to try some other export configuration?

BTW, "Webm VP8, VP9" does not work. Even when I export it with RGBA conf, "mediainfo <file>" shows only RGB color space is used. Moreover, when I import it back into the Shotcut just generated file, it reports RGB as well.

For now, I take a following workaround. Instead of trying to export my footage with transparent background as MOV (btw, which is ~600MB for 15 seconds) and feeding it into ActivePresenter, I turn things the other way round - export my screencast from ActivePresenter and then combine it with my footage in a Shotcut, probably applying more effects that just a Chroma Key. Eventually, Shotcut exports MP4 file without any transparency, which is further uploaded to the YouTube. Maybe it's even better solution, as I can utilize the full power of Shotcut effects.

**Comment by ddennedy** [comment]
Quicktime Animation. For WebM use the presets in alpha. These output yuv420p with alpha, not RGB. I just tested them, and they work for me.

**Comment by ddennedy** [comment]
Maybe a problem you have is because you are not using one of the export presets. Usually it is not enough to change only the format and codec. After choosing a preset look in the other tab to see other parameters are required to make things work.

**Comment by samoshkin** [comment]
Nope, I'm using presets, as I'm not pretty savvy with all those codecs and theirs respective params. 

But maybe I have some other unknown factors affecting it on my local machine, who knows. Nevertheless, I've found a workaround. 

Thank you for your response and such a great tool.
