### ISSUE TITLE
Can no longer convert gif to mkv

### ISSUE THREAD

**Issue by gnu-lorien** [mltframework/shotcut#739]
Windows 10 x64; Shotcut 19.04.30;

Can no longer convert a gif to an mkv. This worked in 19.02.28 with the same gif. I switched versions to test it.

Actual in 19.04.30:

ffmpeg version n4.1.3-4-g7c2dd1f Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 5.5.0 (GCC)
  configuration: --prefix=/root/shotcut/shotcut/Shotcut --disable-static --disable-doc --enable-gpl --enable-version3 --enable-shared --enable-runtime-cpudetect --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libvpx --enable-libopus --enable-libmfx --cross-prefix=x86_64-w64-mingw32.shared- --arch=x86_64 --target-os=mingw32 --pkg-config=pkg-config
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, gif, from 'C:/tmp/1.gif':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: gif, 1 reference frame, bgra, 450x253, 12.50 fps, 12.50 tbr, 100 tbn, 100 tbc
Stream map '0:a' matches no streams.
To ignore this, add a trailing '?' to the map.
[AVIOContext @ 0000000000ea9340] Statistics: 2312786 bytes read, 20 seeks
Failed with exit code 1

Expected from 19.02.28:

ffmpeg version n4.1.1-3-g53f3f52 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 5.5.0 (GCC)
  configuration: --prefix=/root/shotcut/shotcut/Shotcut --disable-static --disable-doc --enable-gpl --enable-version3 --enable-shared --enable-runtime-cpudetect --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libvpx --enable-libopus --enable-libmfx --cross-prefix=x86_64-w64-mingw32.shared- --arch=x86_64 --target-os=mingw32 --pkg-config=pkg-config
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, gif, from 'C:\tmp\1.gif':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: gif, 1 reference frame, bgra, 450x253, 12.50 fps, 12.50 tbr, 100 tbn, 100 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (gif (native) -> ffv1 (native))
Press [q] to stop, [?] for help
[graph 0 input from stream 0:0 @ 0000000002744ac0] w:450 h:253 pixfmt:bgra tb:1/100 fr:25/2 sar:0/1 sws_param:flags=2
Output #0, matroska, to 'C:/tmp/1.mkv':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0: Video: ffv1, 1 reference frame (FFV1 / 0x31564646), bgra, 450x253, q=2-31, 200 kb/s, 12.50 fps, 1k tbn, 12.50 tbc
    Metadata:
      encoder         : Lavc58.35.100 ffv1
No more output streams to write to, finishing.
frame=   20 fps=0.0 q=-0.0 Lsize=    3385kB time=00:00:01.52 bitrate=18231.9kbits/s speed=3.71x    
video:3383kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.049240%
Input file #0 (C:\tmp\1.gif):
  Input stream #0:0 (video): 20 packets read (1016440 bytes); 20 frames decoded; 
  Total: 20 packets (1016440 bytes) demuxed
Output file #0 (C:/tmp/1.mkv):
  Output stream #0:0 (video): 20 frames encoded; 20 packets muxed (3464628 bytes); 
  Total: 20 packets (3464628 bytes) muxed
[AVIOContext @ 00000000026d1040] Statistics: 14 seeks, 29 writeouts
[AVIOContext @ 0000000000da9300] Statistics: 2312786 bytes read, 20 seeks
Completed successfully in 00:00:00

**Comment by ddennedy** [comment]
OK, thanks. This will be a very easy fix for the next version.
