### ISSUE TITLE
Running Shortcut on Ubuntu/Mint 18.04 missing libQt5OpenGL.so.5

### ISSUE THREAD

**Issue by ApertureSecurity** [mltframework/shotcut#741]
Good day All,

**In case if anyone has trouble running Shortcut on Ubuntu Mint 18.04 --**
This is related to 
https://github.com/mltframework/shotcut/issues/683

I looked and I released that I have it installed but was missing a few other libs as well .

```
 sudo apt-get install qtmultimedia5-dev
 sudo apt-get install libqt5quickwidgets5
sudo apt-get install libqt5websockets5
```

Also I kept getting a seg fault from running shortcut. Turns out I needed NVIDIA drivers installed 3.90 I believe (at the time of writing this).

**Comment by ddennedy** [comment]
The builds we provide come with that library:
`ddennedy@MS-7593:~/Desktop/Shotcut$ ls -l Shotcut.app/lib/libQt5OpenGL.so.5 
-rwxr-xr-x 1 ddennedy ddennedy 362864 Feb 14 01:10 Shotcut.app/lib/libQt5OpenGL.so.5`
And Shotcut will use it as long as you use the provided launcher script per the instructions on the download page (or snap, or AppImage, or Flatpak). In the portable tar, the script is at Shotcut.app/shotcut, and you should not run Shotcut.app/bin/shotcut directly (unless you first sourced Shotcut.app/source-me). The provided desktop file in the portable tar works with most desktop environments but not all.
