### ISSUE TITLE
Any way to change the size of the Timeline tracks

### ISSUE THREAD

**Issue by ApertureSecurity** [mltframework/shotcut#742]
Os . Ubuntu Mint 18.04 

Is there any way to resize the timeline tracks? They are HUGE! 

I might compile my own version , but I want to see if there is a solution for this. The rest of the application seems to do this fine and isn't so large. I tried the Windows version and it was much much smaller and more sane. I will show a picture of what I have. 

![Screenshot from 2019-05-22 07-05-37](https://user-images.githubusercontent.com/4926248/58146740-0a1eb500-7c60-11e9-82a4-3eb8dd2a0538.png)

My Screenshot might not put things into perspective..

![Screenshot from 2019-05-22 07-10-07](https://user-images.githubusercontent.com/4926248/58146868-b791c880-7c60-11e9-8d47-7106e534ac25.png)

**Comment by ddennedy** [comment]
You might be experiencing a problem with Qt HiDPI on Linux under some window managers/desktop environments. We do not have a fix for that and do not think it is our bug. You might also be experiencing a problem based on how you launched it, or what package you are running. Thanks to Linux fragmentation, Shotcut can be received and run in a variety of ways: how did you get Shotcut and how are you running it?

**Comment by ddennedy** [comment]
You can workaround some high DPI problems but using a [command line argument](https://shotcut.org/notes/command-line-options/). In particular, try with `--QT_SCALE_FACTOR 1`

**Comment by ApertureSecurity** [comment]
Oh That is much better!
Much cleaner!

Thank you!

![Screenshot from 2019-05-22 08-29-29](https://user-images.githubusercontent.com/4926248/58149498-e6616c00-7c6b-11e9-9678-a35ceb2ae722.png)
