### ISSUE TITLE
INVALID message on PHotos appear inside video WHY?  How Do I Fix this?

### ISSUE THREAD

**Issue by DesignerDavid** [mltframework/shotcut#743]
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

**Comment by ddennedy** [comment]
I don't know. You did not provide enough information. Read the instructions.

**Comment by DesignerDavid** [comment]
I need HELP ASAP, here's what I've tried:
1.  exported a Shotcut video to YouTube
2.  Played video inside YouTube, Every thing played fine EXC

**Comment by ddennedy** [comment]
Maybe you moved the files. Close Shotcut, restart it, and reopen the project.

**Comment by DesignerDavid** [comment]
Thank you ddennedy, I need your help,  let me be specific:
1. exported a video to YouTube, played it, everything played great EXCEPT the photos in my video did not appear instead the word INVALID appeared.  I've done several things to try to fix this

**Comment by DesignerDavid** [comment]
1.  I took 3 photos into Canva, created an image with each photo and black back ground
2.  changed from PGN to JPEG
3.  Then I rezied each of these to 1280 x 720 because I thought INVALID appeared because my images were 2560x 1440
4.  After resizing, I put one picture back into my Shotcut video and INVALID appeared inside my ttrack

**Comment by DesignerDavid** [comment]
I did as you requested, sorry I'm so new at this, I"m slow.

**Comment by ddennedy-gpsw** [comment]
You cannot change things outside of Shotcut and expect Shotcut to know what you did. Everything you are trying to do makes things worse. You need to provide your operating system and version info.  I have another job to do now and unable to help you further today.

**Comment by ddennedy** [comment]
If you are trying to include images that are in your browser's temporary files folder, that is a problem. You can rename your project file to have name ending with .txt and upload it here, and I can try to take a look.

**Comment by DesignerDavid** [comment]
I was able to fix the problem,  i realized the images and it worked thank you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by alex-gru** [comment]
fyi, in case anyone is still struggling with this problem. I had this INVALID screens with .png files in my video project. I tried to use .jpg files instead, which fixed the problem and the INVALID screens disappeared, instead showing the images as expected.
