### ISSUE TITLE
i accidentally change to MESA

### ISSUE THREAD

**Issue by JEMAR21** [mltframework/shotcut#744]
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

Hi i accidentally change the format of the program is there any possible way that i can it back without opening the program the format is  Open GL2.0 Mesa format

**Comment by ddennedy** [comment]
Yes, see this issue comment that explains how:
https://github.com/mltframework/shotcut/issues/722#issuecomment-489494315

Also, a beta comes out tomorrow that includes a fix for the problem that software method fails to initialize on some machines. 

Closing this as duplicate and already fixed.
