### ISSUE TITLE
No Repo For Linux 

### ISSUE THREAD

**Issue by sudopluto** [mltframework/shotcut#75]
I feel that the Linux version of Shotcut should have a repo for the various Linux distros. 
I could try to make one for Ubuntu, openSuSE, and Fedora via OBS, but the devs behind Shotcut should be the ones pushing out the updates, not me.

**Comment by ddennedy** [comment]
This bug tracker is for defect tracking only, and this is an enhancement request that I disagree with. I don't want Linux users to suffer with software that is a year or more old. As the developer, I don't want to deal with users reporting problems with software that is a year old and have little hope of getting a fix in the near term. As the developer, I don't want to deal with a hundred different configurations of the software for all the different distributions - not to mention the packages people have installed from alternative repos. I don't want to make users have to suffer as a result of the developers having to deal with that. I want developers and users to easily have multiple versions of Shotcut to make it easier to compare behaviors and track regressions.

So, the answer is no. Don't even bother to counter-argue. I've already made up my mind after dealing with that kind of bullshit for a decade in the 2000s. That is the way it is for now and the foreseeable future. Don't like it? Then go use some other video editor in your package repo.
