### ISSUE TITLE
Project preset 1080p50 missing

### ISSUE THREAD

**Issue by walterav1984** [mltframework/shotcut#751]
The shotcut new project "Video mode" button, misses the broadcast video option "HD 1080p 50 fps". However adding this as a "Custom" 1080p50 preset did work fine for Decklink duo 2 SDI monitor output.

Tried snap package on ubuntu 18.04 and 19.10 amd64:
shotcut  19.06.15   47    stable    meltytech✓  classic

**Comment by ddennedy** [comment]
Thanks for reporting it.
