### ISSUE TITLE
Queued stabilize jobs write into the same .stab file

### ISSUE THREAD

**Issue by Gizemquea** [mltframework/shotcut#753]
Shotcut Vesion 19,06.15 (broken on older versions too), OS Windows 10

Steps to reproduce the error from scratch:

1.) Create new project (with new/empty project folder)
2.) Add 3 video clips into project
3.) Add Stablilze filter to all three videos, DO NOT cick Analyze yet
4.) Click Analyze for clip 1
5.) WHILE the analyze job for clip 1 is STILL RUNNING, click Analyze for 2 AND 3

Result: 
Once all jobs are finished, there are only 2 .stab files in the project folder.
1.stab representing clip 1, and .2 stab representing clip 3.
The results from clip 2 are OVERWRITTEN (i.e. the file 2.stab is created for clip 2 but replaced as soon as job for clip 3 starts)
This means:
Clip 1 stabilize is working
Clip 3 stabilize is working
Clip 2 stabilize THINKS it has valid results, i.e. you cannot click Analyze again unless you change filter settings - but of course stabilization for clip 2 doesn't work at all. .xml output for job 2 shows 2.stab as output filename (as it does for job 3).

It seems that shotcut determines new .stab file names based on what is actually present in the project folder right at the time the job is created (i.e. in getNextProjectFile), but actually it needs to do that when the job is started. A very cheap workaround would be to just create an empty .stab destination file on job creation.

This might well be the true reason for various "Stabilze is not working" reports in the past.

**Comment by ddennedy** [comment]
Thanks for reporting it.

**Comment by Gizemquea** [comment]
You're very welcome. Thanks for fixing it so fast. Keep up the good work. Overall Shotcut is a really great product.

This issue actually cost me many days in my projects, since stabilize never worked reliably for me (rather slow computer, rather long clips).
