### ISSUE TITLE
Audio waveform not in sync with real audio after speed-change

### ISSUE THREAD

**Issue by RickOrchard** [mltframework/shotcut#755]
I guess this appears to be the same bug as reported in #185:

After changing the audio speed (on a separate track) the waveform is totally off (permanently).

![shotcut-version](https://user-images.githubusercontent.com/20968832/60889867-5185f280-a25a-11e9-8b5b-006005ee2907.png)

----
                               OS: Manjaro Linux x86_64 
                               Kernel: 4.19.56-1-MANJARO 
                               DE: KDE 
                               WM: KWin 
                               WM Theme: SteampunK 
                               Theme: Breeze Dark [KDE], Adwaita [GTK2], Breath [GTK3] 
                               CPU: Intel Xeon E31270 (8) @ 3.800GHz 
                               GPU: NVIDIA Quadro 2000 
                               Memory: 5998MiB / 15997MiB

**Comment by ddennedy** [comment]
What do you mean by "on a separate track"?

**Comment by RickOrchard** [comment]
I mean it wasn't a video track where this happened on but i had a music track of which i set the speed to 0.95, after which the waveform wasn't even close to the real audio anymore. 
--
Verstuurd via de myMail-app voor Android dinsdag, 09 juli 2019, 09:38p.m. +02:00 van Dan Dennedy  notifications@github.com :

**Comment by ddennedy** [comment]
OK, sorry, but I do not seem to be able to reproduce it. I need more steps. Also, we only really support our own builds and not those from another distributor. However, I would be surprised if that makes a difference in this case.

**Comment by RickOrchard** [comment]
I see.
It happened when i had an audio track (with music) under 2 videotracks, with clips and effects. The music track fell just too short so i changed the speed  in the properties tab to 0,95x.
Saving the file, reloading Shotcut and reopening the file didnt help, it persisted (and still does).
I had to allign the audio by listening since the waveform doesn't make sense anymore.
Hope this helps.
Oh also maybe helpfull, i have the video setting on OpenGL instead of MESA.
Thanks for your work on open source.
--
Verstuurd via de myMail-app voor Android dinsdag, 09 juli 2019, 10:01p.m. +02:00 van Dan Dennedy  notifications@github.com :

**Comment by RickOrchard** [comment]
I can send you a short screencast showing the issue if it helps

---

-------------------------

Dan Dennedy schreef op 2019-07-09 22:01:

> OK, sorry, but I do not seem to be able to reproduce it. I need more steps. Also, we only really support our own builds and not those from another distributor. However, I would be surprised if that makes a difference in this case. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/mltframework/shotcut/issues/755?email_source=notifications&amp;email_token=AE77LAAW24TLOGHJQJR67EDP6TVBJA5CNFSM4H7FIYD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZRLQVY#issuecomment-509786199
[2]

**Comment by ddennedy** [comment]
If you can show the steps leading to the problem using a new music file whose waveform had not been generated, then it will help. 
Did you try to right click the audio clip and choose to rebuild the waveform?

**Comment by RickOrchard** [comment]
Yes i did, didn't help.
I did notice some other strange things though, for example the HTML and 3D text filters are missing. Maybe there's something off with this build. I'm going to try another distro soon, I'll let you know...
--
Verstuurd via de myMail-app voor Android woensdag, 10 juli 2019, 10:42a.m. +02:00 van Dan Dennedy  notifications@github.com :

**Comment by RickOrchard** [comment]
I just tried to reproduce the issue using the AppImage from your website
(190615): it happens when i fiddle around with the audio clip order on
the track or when i adjust the speed -> one way goes well but when you
<ctrl-z> (undo) the clip changes are reverted but the waveform is
'messed up' permanently. 

So somewhere in the code the algorithm performing the undo logic makes
mistakes.

---

-------------------------

Dan Dennedy schreef op 2019-07-10 10:42:

> If you can show the steps leading to the problem using a new music file whose waveform had not been generated, then it will help.
> Did you try to right click the audio clip and choose to rebuild the waveform? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/mltframework/shotcut/issues/755?email_source=notifications&amp;email_token=AE77LABMB7FGKVEL4ERMZ53P6WOFVA5CNFSM4H7FIYD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZSYHEY#issuecomment-509969299
[2]

**Comment by ddennedy** [comment]
This is at least partially fixed in 16a240e65eeb23b972b338c3b39be1574bde07b2 for the next release 19.07.

I have not reproduced it in v19.06.15 with:
1. start shotcut
1. open a clip with obvious volume changes
1. add a portion of it to the timeline
1. select the clip on the timeline
1. find a time region of interest where you correlate audio with the waveform change
1. change speed to 0.8
1. compare the waveform to the audio
1. undo
1. compare the waveform to the audio
1. select the clip on the timeline
1. change speed to 1.5
1. compare  the waveform to the audio
1. undo
1. compare  the waveform to the audio

The fix above mentioned applies to more use cases than in the description. You can test the beta here:
https://github.com/mltframework/shotcut/releases/tag/v19.07.07

This will most likely be released July 15.

**Comment by RickOrchard** [comment]
Ok I'll try it, thanks
--
Verstuurd via de myMail-app voor Android donderdag, 11 juli 2019, 11:32p.m. +02:00 van Dan Dennedy  notifications@github.com :
