### ISSUE TITLE
Switching external monitors results in wrong position, crash etc.

### ISSUE THREAD

**Issue by Gizemquea** [mltframework/shotcut#757]
Shotcut 19.07.15 Windows 10 (broken on older versions too)

In a setup with multiple monitors, switching between external monitors doesn't work reliably. My display setup is:
[2][3]
  [1]
were display 3 uses a separate graphics card. Resolutions are 1920x1080 on the external displays and 2736x1824 on internal display.

When selecting an external monitor for the first time (or when restarting the application with an arbitrary external monitor set), the positioning "kind of" works as intended BUT

1.) screen nunbers are inconsistent between shotcut and windows: 
    windows screen 1 -> shotcut screen 0
    windows screen 2 -> shotcut screen 2
    windows screen 3 -> shotcut screen 1

2.) switching from external monitor 1 to external monitor 2 will position video on screen 0 instead, trying to switch back to none in this state will KEEP a working full screen video display on screen 0

3.) switching from external monitor 1 to none will often result in monochrome video overlaying the whole shotcut window, rendering the UI useless (tool tips will still work)

4.) switching from external monitor 2 to external monitor 1 will always result in wrongly positioned video overlaying part of shotcut screen 0 (the x-coordinate seems right, but y-coordinate is at top of screen 0.

5.) switching back from external monitor 1 to external monitor 2 will result in wrongly positioned video INSIDE a black box overlaying the left side of screen 0 (right border of the black box seems right, but video size is wrong)

6.) switching back to external monitor 1 will SHRINK the video (no black box), top left corner of video overly is the same as in 4. x/y size of video is exactly 1/2 of desired display size (960x540)

7.) switching external monitor back and forth repeatedly while video is playing will always result in a crash (application closes)

8.) running shotcut on the display using the external graphics card and switching external monitors betwen displays of the internal graphics doesn't behave much better - I'll spare you the details...

9.) now for the good news: you don't need an external graphics card to reproduce a crash. Removing windows screen 3 (including the whole hardware) completely from my setup and positioning screens of the internal graphics card side-by-side will still crash shotcut when trying to switch from etxternal monitor 1 to none while playing video. If video is not playing, it will produce the same result as in 3.

I observed similar behaviour on three other systems with completely different hardware, including a configuration where the integrated graphics can handle three monitors simultaneously.

**Comment by ddennedy** [comment]
> 1.) screen nunbers are inconsistent between shotcut and windows:

The GUI library we use (Qt) does not support getting screen numbers from the OS. It has its own order. I would like to add a description and [Qt v5.9 added a model()](https://doc.qt.io/qt-5/qscreen.html#model-prop), but that is not working and returns only empty string. I can display resolution, and that may help. I am not particularly interested to add Windows-specific code but will consider a pull request from someone else.

> 2.) switching from external monitor 1 to external monitor 2

Not observed, but I have a different result with no video anywhere.

> 3.) switching from external monitor 1 to none

not reproduced here

4, 5, & 6 are variations on 2 with different results here

> 7.) switching external monitor back and forth repeatedly while video is playing will always result in a crash 

not reproduced here with multiple tests while testing above scenarios

For now, sometimes you need to restart the app. And Shotcut does not yet respond to screen-added or screen-removed events. 

I did all my testing with only external graphics card. I have another system where I can test 2 monitors on internal graphics only. I do not have anything where I can test internal and external.

**Comment by ddennedy** [comment]
I made a few changes to support this including fixing switching between external monitors that works for me plus one that might improve stability by stopping the engine sooner than later when a restart is issued - before apply changes.

**Comment by Gizemquea** [comment]
> I made a few changes to support this including fixing switching between external monitors that works for me plus one that might improve stability by stopping the engine sooner than later when a restart is issued - before apply changes.

Thanks for looking into this. If there is a way to access a shotcut build with your recent commits I could try this out on my setup(s).

**Comment by ddennedy** [comment]
You can get a nightly build here:
http://build.mltframework.org/viewLog.html?buildId=63010&tab=artifacts&buildTypeId=bt43

**Comment by Gizemquea** [comment]
It is an improvement, but there is still a problem. If I set an external montior and switch back to none, I get a strange kind of video overlay on part of the UI (which is actually moving if I play)

![image](https://user-images.githubusercontent.com/34210374/61926585-6c9e7500-af71-11e9-82b1-77d9688cecfe.png)

**Comment by ddennedy** [comment]
I have seen something like that before, and it is related to OpenGL and a race condition around texture IDs. For your technical curiosity, the player, Filters, Keyframes, and Timeline panels use technologies called Qt QML and Qt Quick. Quick draws and composes using OpenGL into a texture. The Shotcut player code also uses OpenGL using an under-painting API in Quick. Something is done in a non-thread-safe manner, and some drivers have better protection against the bad practice than others. I was not getting this problem on my main system, but I do get some temporary green glitches. I made a small change that improves things. Then, I found a system that has a similar problem (but it covers the entire window), and this small change did not fix it. I also found that I had Settings > Display Method = DirectX, and changing it to OpenGL makes it work. Going back to my main system, and I was using OpenGL. Changing it to DirectX did not make a difference (still works). Software mode works for me on either. You can try again after tonight's nightly build, but I do not yet have a foolproof fix for all systems.

**Comment by Gizemquea** [comment]
Sorry no luck with 20190726 either. The result when switching from an external monitor back to none is still the same. Shotcut's own screen doesn't matter i.e. this happens to me on any screen setup wether main and external screen are rendered on the same GPU or not and it also makes no difference if shotcut's main screen is on an external graphics adapter or not.

Shotcut will still crash if I switch external monitors during playback **but only if external monitors are on different graphics adapters** (tried this several times). If shotcut's main window is on the external graphics adapter and I switch back and forth between external monitors rendered on the internal graphics adapter then everything works fine.

**Comment by ddennedy** [comment]
System external monitor no longer included.
