### ISSUE TITLE
No progress bar displayed when exporting video

### ISSUE THREAD

**Issue by presdk** [mltframework/shotcut#759]
Bug type: Usability
Priority: Trivial

When exporting a video, there is no progress bar displayed, leaving the user uncertain when the export has finished.

Windows 10; Shotcut 19.07.15

**Comment by ddennedy** [comment]
Yes there is already one in the jobs panel, but it must be wide enough to show as a bar.

**Comment by presdk** [comment]
So sorry, I didn't see that! Loving the application by the way.
