### ISSUE TITLE
Shotcut 19.08.05 and greater fails to build with release mlt

### ISSUE THREAD

**Issue by plater** [mltframework/shotcut#763]
New features only available in mlt git appear to have been added to shotcut prior to version 19.08.05. These are conditional on LIBMLT_VERSION_INT >= MLT_VERSION_CPP_UPDATED not sure if I've done the right thing but QString m_serviceName; appears to be missing from qmltypes/qmlfilter.h in the section for libmlt < 6.17.0. Only mlt=6.16.0 is released.

**Comment by ddennedy** [comment]
Thanks for finding and reporting it. Please be aware that 19.08.05 is beta/pre-release, and 19.08 release is coming in several days. I just updated the release name on GitHub to clarify that.
