### ISSUE TITLE
Mute and other sound effects causes crash

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#767]
[Радужный водопад 2019.zip](https://github.com/mltframework/shotcut/files/3543049/2019.zip)
When I'm trying to add Mute and other sound effects to part of GH017404 video with 5x speed, it causes crash of Shotcut 19.08.16 for Windows x64 Portable.
![Shotcut Mute bug](https://user-images.githubusercontent.com/27248144/63722382-c25d8a00-c85b-11e9-8f21-cc1994b1b12f.png)

**Comment by LedAlex** [comment]
When I'm copying the clip in current project, it does not copy to the Source player. How can I do that? Or should I start new Project?
Workaround will definitely work, but I can't understand why this happens.
I've finished this project on another laptop with Win7. Bug on Win10.
Where cache for shortcut is stored at? I think trouble is out there...

**Comment by ddennedy** [comment]
Version 19.09.14 has a fix for some audio filters when Settings > Audio Channels is not 2. Please check how your Win10 installation is set. Regarding the cache, on Windows, if you did not set an app data dir in Settings > App Data Directory > Set... it is using the registry:
https://shotcut.org/FAQ/#where-are-the-log-presets-database-and-settings-stored

**Comment by LedAlex** [comment]
That bug reproduces only on one PC. I've kept that project. But I've finished it on another PC a lot of time ago. Is there some log where I can diagnose the cause of problem?

**Comment by ddennedy** [comment]
The app log will not help with this sort of problem. The SDK is a debug build with symbols that is usable in gdb debugger only on Windows and Linux (lldb on Mac). The  downloadable SDK runs via shotcut.exe even if you have trouble to make a build. This debug build for Windows also has an integrated crash logger. After a crash it writes to a text file named shotcut.rpt in the same dir as the exe.
