### ISSUE TITLE
playlist additional menu unaccessible after export(s)

### ISSUE THREAD

**Issue by cdevelc** [mltframework/shotcut#768]
On Win10/64bit version 19.09.02 (and also on 19.08)
using a 30 minute mpeg4 1280x720 H.264 video with AC-3 audio
open mpeg4 video, select a 5 minute chunk, push + to playlist, export to mp4
remove all from playlist
re-open mpeg4 video, select a 5 minute chunk, push + to playlist, export to mp4
remove all from playlist
re-open mpeg4 ...
UNable to remove all from playlist, playlist additional menu options button does not respond.

This problem does not exist in 19.07.15.  I am able to open, add to playlist, export, remove-all over and over and over.

**Comment by ddennedy** [comment]
thanks. Now the playlist menu button is never disabled.

**Comment by cdevelc** [comment]
Terrific, thanks for the quick response.
