### ISSUE TITLE
Build its broken (melt 6.5.0)

### ISSUE THREAD

**Issue by HotelBellaMuerte** [mltframework/shotcut#769]
OS: manjaro

Melt 6.5

Versions 19.08.16 + 19.09.02 

Glibc 2.29

Clang 8.0.1 / GCC 9 

FFmpeg 4.2

[Buildlog](https://gist.github.com/HotelBellaMuerte/a122b4b95b7b52ca29f16cfd8db03e61)

**Comment by ddennedy** [comment]
Build support is not provided unless you are a distro packager.
Your version of MLT is too old. Shotcut only works with the latest release (currently v6.16.0) or git master.
