### ISSUE TITLE
Non-fadein/out filter in/out points are not updated

### ISSUE THREAD

**Issue by metellius** [mltframework/shotcut#77]
Trying to use the time argument in webvfx I noticed that the in/out points were not updated when the clip was resized. I eventually tracked it down to MultitrackModel::trimClipIn (among others)
```
        // Adjust all filters that have an explicit duration.
        int n = info->producer->filter_count();
        for (int j = 0; j < n; j++) {
            Mlt::Filter* filter = info->producer->filter(j);
            if (filter && filter->is_valid() && filter->get_length() > 0) {
                if (QString(filter->get(kShotcutFilterProperty)).startsWith("fadeIn"))
                    filter->set_in_and_out(in, in + filter->get_length() - 1);
            }
            delete filter;
        }
```
This startsWith test was added in 1456ff84
So in webvfx's case, the filter in/out is only set once, in Component.onCompleted in the filter ui, and never again.

I have not yet had time to look at possible solutions, but my initial impression is that QString(filter->get(kShotcutFilterProperty)).startsWith("fadeIn") looks hackish.

**Comment by ddennedy** [comment]
This is largely because property animation is not yet in Shotcut. However, we do claim to support the notion of time in webvfx (see howto). Until animation is properly integrated and this gets rewritten, we can add a test here for mlt_service=webvfx.
