### ISSUE TITLE
Audio/Video device stopped working in v19.09.14

### ISSUE THREAD

**Issue by chovanj** [mltframework/shotcut#775]
Hello,

There is an issue with Audio/Video recording in version v19.09.14, it stopped working and it doesn't record anything. I had to migrate back to the version v19.08.16 in which it works properly.

Anyway, I like your tool and if you have time would be great to simplify voice over functionality because now it requires too many clicks to record. For example put it into Audio track. 

Thank you!

**Comment by ddennedy** [comment]
This is a known bug that has already been fixed for the next version.
