### ISSUE TITLE
Separate video window

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#776]
I have spent a lot of time, but I can't figure out how to detach video window and move it to separate monitor. Is it possible?

**Comment by ddennedy** [comment]
This is not available. You float all other panels or use Settings > External Monitor.

**Comment by LedAlex** [comment]
This does not help. I can't free workspace that way. I want to make time line bigger, but it's stucked...
It'll be great to detach everything in red box and move it away. Can this be implemented in future release? 
![2019-09-30](https://user-images.githubusercontent.com/27248144/65900188-19f09780-e3be-11e9-82c8-dbcdc674ab92.png)

**Comment by LedAlex** [comment]
I have figured out the problem. It's in filters window. If I turn it off, I can enlarge time line in direction of red arrow. If I turn it on, it takes half of screen and everything stucks. I think it has minimum height.

**Comment by ddennedy** [comment]
Until more flexibility is added, turn on View > Show Title Bars. Now, you can temporarily float the Timeline panel by double-clicking its title bar. Then, increase its size or move it to another screen. Double-click its title bar again to return it to docked in the main window. Or, you can do something similar with the other panels such as Filters.

**Comment by LedAlex** [comment]
That's great. Each docked window is separate. Is there some way to join two windows in tabs for example timeline and keyframes like in main window?
