### ISSUE TITLE
Timeline time discards

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#777]
If I resize main Shotcut window, timeline time discards to zero. It will be recalculated only if scroll is dragged to the left or right.
![2019-10-04 0000](https://user-images.githubusercontent.com/27248144/66166022-cb9dfb80-e63e-11e9-9afc-6afa181f5b96.png)
![2019-10-04 0001](https://user-images.githubusercontent.com/27248144/66166030-cf318280-e63e-11e9-86f1-96945094bfdf.png)

**Comment by ddennedy** [comment]
This happened when resizing the panel or window horizontally - not only when maximizing or un-maximize. Thanks for reporting it.
