### ISSUE TITLE
cannot preview video after move the any clip in timeline.

### ISSUE THREAD

**Issue by gcrisis** [mltframework/shotcut#779]
OS:win10 64bit home ,4g, i5 
shotcut: 19.09.14
details: I add third audio track,Then I find that the preview window have nothing but dark ,no sound too. But After I play a material from playlist,then preview window will be ok.But once I move something in the timeline,the problem back again.
My shotcut  crashed a lot.Always happened when I close the project or I open more then two files.
[shotcut问题log.txt](https://github.com/mltframework/shotcut/files/3711056/shotcut.log.txt)

**Comment by ddennedy** [comment]
Is this only a problem in one project? Does it happen in a new project? If so, then provide more steps please.
It sounds like something is wrong in your timeline like a video track is hidden or a filter was added accidentally somewhere. You can upload the project here after renaming it to have a .txt filename.

**Comment by gcrisis** [comment]
Sorry for late reply.
It is OK for new one.There are so many videos and will be so large,Should I upload these or just .mlt file？

**Comment by ddennedy** [comment]
Only upload the .mlt

**Comment by gcrisis** [comment]
I'm sorry .I cannot find the origin one ,maybe I delete it when I make a new one.If it happens again, I will upload it.
Thank you for your reply.
