### ISSUE TITLE
Linear scale keyframes are exponential

### ISSUE THREAD

**Issue by muesliflyer** [mltframework/shotcut#782]
In the Rotate and Scale filter I set linear keyframes at 1% at the beginning and at 100% at the end of a clip.

Expected result: during playback, the object is scaled linearly between 1% and 100%

Observed result: the object scales exponentially, i.e., very slowly in the beginning and towards the end catches up to 100% very rapidly.

This was observed with Shotcut 19.09.14 on Windows 10.1903

See this project file:
https://drive.google.com/open?id=1n-HVBqfrcx078Y20-nNy2s4_4EGOKDuV

**Comment by ddennedy** [comment]
This is fixed in MLT git master and 811273326d1ebd212c6129f7a6ab4990624f7bba for the next release.
