### ISSUE TITLE
Image sequence export playlist shows INVALID

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#784]
Shotcut 19.09.14
Shotcut 19.10.10
Shotcut 19.10.20
Export timelapse sequence from playlist causes "INVALID" video with strange total time.
If I change export from source it works fine for one current timelapse.
In log I can see some strange path to images "C:\[Program Files]\Shotcut 19.10.20 for Windows x64 Portable/qimage:C:/Users/...".

![2019-10-22 0003+](https://user-images.githubusercontent.com/27248144/67321934-eadec900-f518-11e9-9087-8b2864b2f16e.png)
![2019-10-22 0004+](https://user-images.githubusercontent.com/27248144/67321941-ee725000-f518-11e9-8044-2aff11b119e8.png)
![2019-10-22 0005+](https://user-images.githubusercontent.com/27248144/67321951-f205d700-f518-11e9-9e41-171eea1b1e94.png)
![2019-10-22 0006+](https://user-images.githubusercontent.com/27248144/67321964-f631f480-f518-11e9-9858-f57370371bb2.png)
[Export log.txt](https://github.com/mltframework/shotcut/files/3757942/Export.log.txt)

**Comment by ddennedy** [comment]
From the export log, I can see that it thinks your image file path is a relative path and prepends a path (`C:\[Program Files]\Shotcut 19.10.20 for Windows x64 Portable/`) to it. I was to reproduce this by first dragging the image file from Explorer to Playlist. If you instead do any of the following you should not have this problem: 
- drag it to the Source player
- choose it from Recent
- use File > Open
