### ISSUE TITLE
change how delete button works in keyframes screen

### ISSUE THREAD

**Issue by Joshuaalbert** [mltframework/shotcut#785]
When in the keyframe screen and I click a keyframe point, I'd expect that pushing the delete button deletes that point but instead it deletes the track. This is on 19.10.20

**Comment by ddennedy** [comment]
Most people use the word button for something on screen, but I think  you mean key as in keyboard button. I do not plan to ever implement this as it overloads the delete keyboard shortcut and requires panel focus to do effectively and not be confusing. The Keyframes and Timeline panels can both be showing at the same time (not tabbed) and both showing something selected such that Delete is ambiguous. This would require panel focus, showing panel focus, and changing panel focus. I do not believe it is good for usability for many users. So, essentially, this becomes a feature request to add keyboard shortcuts for full/advanced keyframes. This is planned, but we do use this for tracking feature requests.
