### ISSUE TITLE
playlist thumbnails do not update after editing in external editor

### ISSUE THREAD

**Issue by ipatch** [mltframework/shotcut#786]
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

**OS** macOS High Sierra 10.13.6
**Shotcut** 19.10.20

When working with a project that uses a series of images, ie. PNG or JPEG and I import a list of images into my current project, sometimes the images require being rotated for whatever reason (mostly due to my bad photography skills).  That said, I can use quicklook on macOS to preview the image, and then open with _Preview.app_ and _rotate_ and _save_ the image to the orientation I would prefer.

Then I go back to Shotcut and try clicking the _update_ icon <kbd>✔️</kbd> to the right of the <kbd>+</kbd> <kbd>-</kbd> in the playlist panel, but the thumbnail does not update with the orientation that I applied using _Preview.app_.  I tried changing the _view mode_ of the thumbnails, but it seems the _Shotcut GUI_ from what i can tell does not expose a way to update the playlist thumbnail cache when viewing the thumbnails in the Playlist panel.

**Comment by LedAlex** [comment]
Shotcut 19.09.14
Shotcut 19.10.20
On Windows update button is disabled and not pressable at all.

**Comment by ipatch** [comment]
@LedAlex **yup**

I poked around the source yesterday and noticed the same thing.

[see](https://github.com/ipatch/shotcut/blob/master/src/docks/playlistdock.ui#L176)

👆 is that what you are referring to?

And have you tried to build shotcut from master yet?

I'm using shotcut on macOS, and there a some hoops jump through before I can even build a local copy to experiment with settings.

I ask because if you can build locally and change the line referenced in the link, I'm curious as to what your results would be.

Also on a completely different tangent, I opened a thread on the shot forums about the possibility of setting up some docker images to help streamline the whole process of getting a development env setup ...hopefully less painful.

**Comment by LedAlex** [comment]
I've only setup QT a couple weeks ago, but I totally don't have time even to compile it :( Sorry, maybe some time later.

**Comment by ddennedy** [comment]
The update button is not primarily about updating the thumbnail, but it may update it based on a change. The update button is only enabled when you have made some change to the playlist clip. I could enhance it to be enabled something is selected and force update the thumbnail even if no change is detected.

There are SDKs and instructions on the web site for each supported major OS. Look in the sure map.

**Comment by LedAlex** [comment]
That would be great, because I have template project in which some typical clips and images are to be changed before editing project. Therefore thumbnails never corresponds to real content.

**Comment by ipatch** [comment]
@ddennedy

or how about a completely separate button to update selected thumbnails?

I mean you already created the _create_ action to generate the thumbnails when importing an image, why not create a separate button that reuses the same method but instead updates the thumbnail if the item in the playlist is selected.

**Comment by ddennedy** [comment]
I added **Update Thumbnails** to the Playlist menu (menu button and context menu) for the next release. This should also be added to the clip context menu in Timeline but that is not done yet.
