### ISSUE TITLE
Ctrl+A bug

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#787]
Shotcut 19.09.14
Shotcut 19.10.20
When I select a clip in playlist and press Ctrl+A everything is selected even in timeline.
![2019-10-25 0000](https://user-images.githubusercontent.com/27248144/67590597-23261780-f764-11e9-81fa-6e9c17954879.png)
![2019-10-25 0001+](https://user-images.githubusercontent.com/27248144/67590601-26b99e80-f764-11e9-9913-e3832abeb6c3.png)

**Comment by ddennedy** [comment]
It is only supposed to select all in the timeline. It looks like the list widget is responding to it by default, and I need to try to tap and prevent it.

**Comment by LedAlex** [comment]
Maybe ti will be better to bind some new keyboard shortcut for example Shift+Ctrl+A or something...

**Comment by ddennedy** [comment]
Playlist select all already has keyboard shortcut Shift+Ctrl+A
