### ISSUE TITLE
Copy feature

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#789]
Shotcut 19.10.20
Feature request.
It will be awesome to copy selected part from timeline to another instance of Shotcut.
It's not good to trying to edit xml of project in melee fight.
Also when I select several clips in timeline I can't even move them together not to mention splitting several clips at a time and so on...

**Comment by ddennedy** [comment]
Feature requests are not accepted here.

**Comment by LedAlex** [comment]
Where should be they accepted?

**Comment by ddennedy** [comment]
In a pull request as a code contribution
