### ISSUE TITLE
crash when clicking add video track

### ISSUE THREAD

**Issue by arda2012** [mltframework/shotcut#79]
Hi,

I am trying shotcut on gentoo 64bit. I use gentoo packages for ffmpeg, qt5 and all other dependencies except mlt and shotcut which are compiled from source package from 1 june 2015.

As soon as a select add video clip, I receive a sgmentation fault.

Here is the output from gdb:

Program received signal SIGSEGV, Segmentation fault.
mlt_service_connect_producer (self=self@entry=0x0, 
    producer=producer@entry=0x1efa3c0, index=index@entry=0)
    at mlt_service.c:202
202             mlt_service_base *base = self->local;

If there is anything I can do to help you debugging this crash, please let me know.

Thanks in advance.

**Comment by ddennedy** [comment]
You are on your own if not using our supplied binaries.

**Comment by arda2012** [comment]
Just to complete this report in case another one will have this problem:

After some debugging I found that this bug occurred due to a too old version of frei0r-plugins.
