### ISSUE TITLE
Windows window resizing after save

### ISSUE THREAD

**Issue by vgXhc** [mltframework/shotcut#791]
### Platform
Windows 10 Pro 10.0.18362 Build 18362
Shotcut 19.10.20

### Issue
When saving a project, the Shotcut window rescales and the horizontal scroll bar for the timeline disappears. Un- and re-maxiziming the window brings back the scroll bar.

![image](https://user-images.githubusercontent.com/11335221/68302106-f8429a00-0066-11ea-9c1f-89a0d3e7dff6.png)
Before: Maximized window, with scroll bar visible

![image](https://user-images.githubusercontent.com/11335221/68302178-1a3c1c80-0067-11ea-849d-b4aef2451917.png)
After saving project: Maximized window, with "Saved ...." message and scroll bar gone

### Steps to reproduce
1. Open or create project, with window maximized
1. Add clip to timeline that is long enough to make a horizontal scroll bar appear
1. Save project (via File>Save or Ctrl-S)

**Comment by ddennedy** [comment]
I am not reproducing this. It might depend on Settings > Display Method on your system (I tried all the different options on my system when trying to reproduce). It looks like you are using a high density display. I also tried using 200% on my 3840x2160 display but still did not reproduce. You can also try to see if resizing the timeline panel or changing timeline zoom level restores the scroll bar.

**Comment by vgXhc** [comment]
Huh, interesting. Display is 1920x1080, with Windows scaling set to 150%. 

I changed the Display Method (was: "DirectX (ANGLE)") to "Auto," which didn't change the behavior (and resizing the timeline panel or its zoom level didn't restore the scroll bar). Changed Display Method again to "OpenGL," which did fix the problem. And now I can choose _any_ Display Method without the problem returning.
