### ISSUE TITLE
GIF File not working on ShotCut?

### ISSUE THREAD

**Issue by ZakiYT** [mltframework/shotcut#793]
I occasoianlly need to use GIF files for my projects. But they don't seem to work on shotcut as they can't be dragged into a timeline.

**Comment by ddennedy** [comment]
Yes, it works. You did not specify if yours is animated. Neither did you specify your version of Shotcut or Operating System as instructed, Here you can see an animated GIF dragged to Timeline in Shotcut v19.10.20 on Windows:

![image](https://user-images.githubusercontent.com/1146683/69012584-3c1d8500-092c-11ea-8250-4634fd59b2b3.png)

I supposed sometimes the GIF might load as an looping animation and thus without a specific duration. In that case, you can try two things:
1. With the GIF opened, use Properties > menu > Convert to Edit-friendly.
2. First drag the GIF to Playlist; it will prompt for a duration. Now, you can drag it from Playlist to Timeline.

**Comment by ZakiYT** [comment]
Then How do I check what shotcut version I'm running?

I can insert any GIF file in to the pogram and it instantly crashes.
![Screenshot (67)](https://user-images.githubusercontent.com/51287940/69072903-ac133480-0a2c-11ea-9cd9-17cd91f0ae1a.png)

**Comment by ZakiYT** [comment]
I'm on Windows 10 btw.

**Comment by ddennedy** [comment]
Help > About in the menu. Nearly all programs report their version there. I see from your screenshot it is an older version than latest. Near the middle of your screen shot you can see a message that says “Click here to check for a new version.”
