### ISSUE TITLE
Crashing when adding Vertigo filter

### ISSUE THREAD

**Issue by vasiliysmirnov** [mltframework/shotcut#797]
macOS 10.14.6; Shotcut 19.10.20
When I add vertigo filter, and starting a playback, shotcut is just closing. 
When I trying to export video, there is errors. 
Here you can see log file: 
[log.txt](https://github.com/mltframework/shotcut/files/3898780/log.txt)

**Comment by ddennedy** [comment]
Sorry to hear that, but I am not reproducing the problem using same Shotcut version on macOS, and the log does not have enough information. I tried a few times. Please try it on a different source video or test another filter on this same source to help determine if it depends on something about the source. Another test to make is convert the source using Properties > menu > Convert to Edit-friendly, open that result, and try it.
