### ISSUE TITLE
Shotcut 19.12.02 playlist issue.

### ISSUE THREAD

**Issue by Sauron0** [mltframework/shotcut#800]
OS Windows 10 1909
Shotcut 19.12.02

Moving a playlist item up or down causes Shotcut crash.

Sorting playlist items by name or date causes Shotcut crash.

Drag and drop video or audio from recent panel to playlist panel causes Shotcut crash.

Windows details.

Problem signature
Problem Event Name:	APPCRASH
Application Name:	shotcut.exe
Application Version:	0.0.0.0
Application Timestamp:	5de4e07b
Fault Module Name:	libwinpthread-1.dll
Fault Module Version:	1.0.0.0
Fault Module Timestamp:	00000000
Exception Code:	c0000005
Exception Offset:	0000000000002ab8
OS Version:	10.0.18363.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	5806
Additional Information 2:	58062408735a93dcdb55723aa770c315
Additional Information 3:	b8b0
Additional Information 4:	b8b063c388b55a4cc2ffcf9f2e7c8731

Extra information about the problem
Bucket ID:	8358b037873e16ac3d2d2b8c389bf524 (2102384482297050404)

**Comment by ddennedy** [comment]
Please do not file bugs here against unreleased versions.
