### ISSUE TITLE
Shotcut 19.12.08 playing video preview with 2-3fps frame rate update

### ISSUE THREAD

**Issue by newillusion** [mltframework/shotcut#804]
In previos version (19.10.20) playback going with normal frame update (30fps on the same videos).

Display method: OpenGL (the same on both new and previous ShotCut version)
Used video: 4K (and 2.7K), H264, HEVC, .mp4
OS: Windows 7 64bit

**Comment by ddennedy** [comment]
Thanks. I have a couple of ideas of the reason for this and will revert the change that caused it for the 19.12 release.
