### ISSUE TITLE
Shortcut is dead with long file

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#805]
Shotcut 19.10.20

Shortcut becomes unresponsive after second move in timeline with only one long file. It consumes all CPU and there is a memory leak.
![2019-12-12 0000](https://user-images.githubusercontent.com/27248144/70688868-c48d0c80-1cc3-11ea-8046-7b9e06fc6940.png)

**Comment by ddennedy** [comment]
Are you running two instances of Shotcut?

**Comment by LedAlex** [comment]
Yes. In one there is main project. Other used for creation of small sub-scenes to simplify main project.

**Comment by ddennedy** [comment]
Yeah there is some weird performance issue with multiple instances and not just on Windows. I have seen it on macOS too.
