### ISSUE TITLE
Can't change video speed

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#806]
Shotcut 19.10.20

Can't change video speed for long video. For example I need speed around 168x, but there is some limit hardcoded in (50x).
![2019-12-12 0002](https://user-images.githubusercontent.com/27248144/70689026-31a0a200-1cc4-11ea-9213-ec4899da556c.png)

**Comment by ddennedy** [comment]
Yes, there is a limit. Not accepting this as a bug

**Comment by LedAlex** [comment]
And how do you suppose to use it normally then? Can you remove limit?
