### ISSUE TITLE
Compatibility of .mlt files across versions

### ISSUE THREAD

**Issue by michael-heerdegen** [mltframework/shotcut#807]
Hi,
I often experienced the following issue: after I wanted to resume working on a project, after opening the .mlt file, the preview only showed graphical garbage, and encoding showed the same.  I never got such a source file to work again from within the program.

I typically used to start the project from scratch.  Not good (lost work).  That happened in the past and up to now.  I'm using shoutcut from Debian testing - the current version there is named "1:19.10.20-dmo2", the program itself says "Shotcut version 19.10.23".

I always believed that it had something to do with incompatibilities after upgrading shotcut.  Now I succeeded the first time to repair such a broken .mlt: I needed to do this (near the end of the file):

```
*** 74,80 ****
      <transition id="transition1">
        <property name="a_track">0</property>
        <property name="b_track">1</property>
!       <property name="mlt_service">movit.overlay</property>
        <property name="disable">1</property>
      </transition>
    </tractor>
--- 74,80 ----
      <transition id="transition1">
        <property name="a_track">0</property>
        <property name="b_track">1</property>
!       <property name="mlt_service">frei0r.cairoblend</property>
        <property name="disable">1</property>
      </transition>
    </tractor>
```

I don't understand the background, so sorry if I'm ignorant, but the feature request is: please try to make shotcut more smarter in this regard: could it autodetect such a situation and suggest to "repair" mlt files created with older versions in such a way automatically?

TIA, Michael.

**Comment by ddennedy** [comment]
Shotcut is already very good in this area, but there are two problems you are facing, which are not supported: using a build not provided by us where we can control the dependencies, and using GPU effects (as seen by “movit“ in the XML.  It does not provide a conversion between GPU projects and those not using it because the effects’ parameters and behaviors are different. Shotcut should detect that you are loading an incompatible project and warn you.

**Comment by michael-heerdegen** [comment]
Dan Dennedy <notifications@github.com> writes:

> It does not provide a conversion between GPU projects and those not
> using it because the effects’ parameters and behaviors are different.

Does that mean that how I edited the mlt file does not always work?
AFAIK I didn't use any effects in that project, only cutting.

> Shotcut should detect that you are loading an incompatible project and
> warn you.

Yeah, that would be good.

Anyway, thanks for your work - Michael.

**Comment by ddennedy** [comment]
If you use the timeline it adds a transition on each track that has the implementation of the compositor or audio mixer named. In your case it looks like one that is disabled by default on V1. I suppose we could detect that case and exclude it or convert it. The CPU compositor has a blend mode parameter that would not convert with full fidelity. Also, we would have to expand the warning dialog I mentioned to include a convert option (addition to the current option to switch mode). These are enhancement requests to something that was always labeled experimental or unsupported and eventually hidden from the UI. Now you know how easy it is to manually convert the basic case.

**Comment by michael-heerdegen** [comment]
Dan Dennedy <notifications@github.com> writes:

> These are enhancement requests to something that was always labeled
> experimental or unsupported and eventually hidden from the UI. Now you
> know how easy it is to manually convert the basic case.

Yes, doesn't sound like a good investment of time.  I think a simple
warning would be good, though, to prevent the user from thinking that
there is a problem with his current settings or system or hard disk.

Now he can also find this discussion, which is also good.

Thanks, Michael.
