### ISSUE TITLE
Incorrect Scaling (adds padding)

### ISSUE THREAD

**Issue by andrewk8** [mltframework/shotcut#809]
I have a source file with unknown history with an odd size: 720x406 resolution, 16:9 DAR, so non-square pixels (406:405 PAR).  Shotcut 19.10.20 portable on Windows 10 1909.  "Automatic" video mode.  SC detects the source at the correct DAR.

Export to H.264 lossless without changing the video settings.  The resulting file has the correct resolution and PAR, but it also has padding, where the original didn't.  I haven't done a pixel-by-pixel comparison, but either SC scaled the x-resolution and padded the difference, or it cropped the x-dimension (or a combination).

SC output of the original file resulted in 2px padding on the left and right sides.  I'm not going to share it.  I made a different sample at the same resolution/DAR to demonstrate the issue.  SC output of this sample results in 2px padding on the right side.  Not the same result, but it does demonstrate the issue.

Expected result: no scaling / no padding because the source, project, and output have the same resolution and DAR.
[scaling bug.zip](https://github.com/mltframework/shotcut/files/3963408/scaling.bug.zip)

**Comment by ddennedy** [comment]
This was fixed in [v21.05.01](https://www.shotcut.org/blog/new-release-210501/)
https://forum.shotcut.org/t/wrong-aspect-ratio-export-adds-padding-update/26974
