### ISSUE TITLE
Can't deselect

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#812]
Shotcut version 19.12.16

Ctrl+A to select all in timeline.
After that I can't select only one part in timeline.
Only workaround is to move something.
![2019-12-17 0000](https://user-images.githubusercontent.com/27248144/70952121-63c05400-2076-11ea-9db0-44e8aec3236c.png)
![2019-12-17 0001](https://user-images.githubusercontent.com/27248144/70952179-8ce0e480-2076-11ea-818e-ef8445c27743.png)

**Comment by ddennedy** [comment]
Use Select None (Ctrl+D or in Timeline menu)

**Comment by LedAlex** [comment]
In previous version that worked fine for mouse click.

**Comment by ddennedy** [comment]
fixed in version 24.06
