### ISSUE TITLE
Update thumbnails does not work with selection

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#813]
Shotcut version 19.12.16

If you select all items in playlist and try to update thumbnails, only one is updated on which sub-menu was invoked.

![2019-12-17 0002](https://user-images.githubusercontent.com/27248144/70952387-227c7400-2077-11ea-834b-ee8532bf619f.png)
![2019-12-17 0003](https://user-images.githubusercontent.com/27248144/70952390-24463780-2077-11ea-8a36-ea8acbd1bd32.png)

**Comment by ddennedy** [comment]
This action only exists for one item with no immediate plans to address this unless someone else volunteers to make the change.

**Comment by LedAlex** [comment]
Maybe it worth to move that feature to buttons under list and update all. In project with couple of hundreds of clips in list it's useless, 'cause you'l keep updating them for some hours.

**Comment by ddennedy** [comment]
Why do you need to do update so many of them? Someone will probably get around to handling multi-select for that someday, but no I am not going to add buttons because this is rarely needed. It is needed basically if you edit an image and need to update.

**Comment by LedAlex** [comment]
Because I'm using template project. Other I think too. You'll never create common things like intro and titles from scratch each time for each video. The simplicity of process is to update some files (pictures and videos) in project folder and load project. And you ready to create content part. In an ideal it'll be awesome if Shotcut will update them while loading project.
