### ISSUE TITLE
Wrong ripple drop mode editing

### ISSUE THREAD

**Issue by newillusion** [mltframework/shotcut#814]
Sometimes, in "ripple drop mode on", when a clip reallocating from right to left (over several clips ), the clip becomes wrong.
It becomes freeze (with one frame) and/or contains shifted source time.

![Clipboard03](https://user-images.githubusercontent.com/13040758/71144316-2c0d0400-2250-11ea-97c1-4ef9565276dd.png)

In next example you can see such clip at 25:29 (second on timeline)

![Clipboard04](https://user-images.githubusercontent.com/13040758/71144362-58288500-2250-11ea-9a3b-99b15bcedb32.png)

If I move the clip with "ripple drop mode" off, it "repaired". 
if the wrong clip saved with a project, after loading the project clip still wrong.

In next example you can see, what in project this clip described with wrong time:

![Clipboard05](https://user-images.githubusercontent.com/13040758/71144549-ffa5b780-2250-11ea-8aaf-5e712b137032.png)

The project (contains wrong clip):
[Project.zip](https://github.com/mltframework/shotcut/files/3981705/Project.zip)
(source file is very large, you can replace it any width duration more then 9:45:00)

OS: Windows 7 64bit
Shotcut ver. 19.12.16
Source file: mp4, variable fps (~30), 3840x2160, H.264

**Comment by ddennedy** [comment]
I have not been able to reproduce it after trying several times. I do see a problem in your project file. 

`  <producer id="producer1" title="Anonymous Submission" in="00:00:44.133" out="00:00:46.900">`

should be 

`  <producer id="producer1" title="Anonymous Submission" in="00:00:00.000" out="00:09:44.500">`

But I do not how it happened, and I am trying to figure out the steps. Maybe some step before moving is required. You wrote "sometimes." Any more information you discover will be helpful.

**Comment by ddennedy** [comment]
I finally reproduced this in ripple mode when moving left-to-right or moving a clip within a blank. Those conditions directly correspond to the bug I see in the code. Perhaps you did one of these before moving a clip right-to-left and did not notice it until then.

**Comment by newillusion** [comment]
"... Perhaps you did one of these before moving ..."
It is possible.
