### ISSUE TITLE
clips get weird after I split,move or speed up

### ISSUE THREAD

**Issue by gcrisis** [mltframework/shotcut#815]
Win10; Shotcut 版本 19.12.16

I split a clip and move the right one then the clip play an unexpect video.
I speed up video only but audio in audio line speed up too.
Sometimes the audio get no sound unexpectly.
The version 19.10.20 didn't have these problems I used before.
[ttt.txt](https://github.com/mltframework/shotcut/files/3992148/ttt.txt)

**Comment by ddennedy** [comment]
Duplicate of #814 which is fixed.
This is a major new bug. As a result, There will be a new beta version tomorrow.
