### ISSUE TITLE
Copy a filter from one video to the other does not copy the keyframs of the filters

### ISSUE THREAD

**Issue by orena1** [mltframework/shotcut#816]
Windows 10,  Shotcut 19.12.16.
As the title states, when I copy the filters from one video to another, I assumed that the keyframes would also be copied, but they are not copied.

**Comment by ddennedy** [comment]
Unable to reproduce. Provide exact steps.

**Comment by orena1** [comment]
I created a video to show the steps:
https://www.youtube.com/watch?v=5-Ftk9zpIvw

**Comment by ddennedy** [comment]
Ok those are not really considered key frames but rather filter trim points even though you use Keyframes panel to adjust them. I can confirm those are not applied on paste. I have yet to decide whether I agree to change behavior. For example, one may expect them belonging to the clip, another may expect them to be relative to the beginning and end, while yet another expects they are absolute (both relative to the beginning of the clip).

**Comment by orena1** [comment]
> one may expect them belonging to the clip, another may expect them to be relative to the beginning and end, while yet another expects they are absolute (both relative to the beginning of the clip).

Indeed a problem, I would suggest having all three options :). But I assume it might be hard. 

Thank you for the support.
