### ISSUE TITLE
Timelapse sequence total time calculation is wrong

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#818]
Shotcut 19.12.23
Timelapse sequence total time calculation is wrong.
It's usually equals to four seconds.
When you click "Image sequence", time is calculated right.
After you switch to playlist it becomes wrong.
If you add timelapse to timeline or open it in source, you can that it's cropped to 4 seconds.
Workaround is to manually change end time in source and add video to time line from there, but it's time consuming with a lot of timelapses.
![2019-12-28 0001](https://user-images.githubusercontent.com/27248144/71536951-5e8cc000-2926-11ea-8e76-4c0194436326.png)
![2019-12-28 0002](https://user-images.githubusercontent.com/27248144/71536952-5e8cc000-2926-11ea-8aed-0d997cbfbd6c.png)
![2019-12-28 0003](https://user-images.githubusercontent.com/27248144/71536953-5e8cc000-2926-11ea-8e65-26ff6974ee6e.png)

**Comment by ddennedy** [comment]
I have not figured out the sequence of steps to reproduce this. How did the image get into the Playlist? When did you click the Image sequence checkbox?
Surely as a workaround, you can open the image directly in the source player and click the image sequence checkbox before adding it to the playlist or timeline.

**Comment by LedAlex** [comment]
I have added image to playlist first. After I selected it in playlist and switched to properties tab. And now you'll be on first screenshot.

**Comment by LedAlex** [comment]
I have added image to playlist by D&D.
