### ISSUE TITLE
Impossible to add the @

### ISSUE THREAD

**Issue by Ang8r2** [mltframework/shotcut#822]
When you try to add the @ sign to the plain text filter, 0 is displayed instead of @ . For example, if you try to add the text **@my_shannel**, you will see **0me_shannel**.
v19. 12. 31

**Comment by ddennedy** [comment]
The filter engine treats a parameter value beginning with `@` as [special to interpret the value as a simple math expression](https://www.mltframework.org/doxygen/structmlt__properties__s.html#a045d36e89f83de4c747de465a8c9aa75). A simple workaround for now is to put anything else as the first character. For example, it could be some leading text like "twitter:" or if you really want or need @ first then put a space character before it.
