### ISSUE TITLE
Merge export processing with phone and other devices, by splitting video

### ISSUE THREAD

**Issue by DaniellMesquita** [mltframework/shotcut#823]

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/OpenShot/openshot-qt/issues/3162

**Comment by ddennedy** [comment]
Shotcut is not related to OpenShot. You can probably already do this. Is there a problem?

**Comment by DaniellMesquita** [comment]
Is this feature already available?

**Comment by ddennedy** [comment]
Maybe, but your request is not clearly defined. Besides, feature requests are not accepted here as already mentioned in our issue template. You can submit a feature request by making a pull request with the accompanying code.

**Comment by ddennedy** [comment]
See also https://shotcut.org/features/ and other pages to lean more.
