### ISSUE TITLE
V20.02 beta: Size & Position video filter: scaling issues - changing size mode only changes 'video-overlay rectangle' but not the content

### ISSUE THREAD

**Issue by M0RT1M4R** [mltframework/shotcut#827]
hi there,

just testing the V20.02 beta and have not seen the bug reported so far.
Please check Size & Position video filter.

- adding 1080p video
- adding s&p filter (does not matter if for the track or only a video snippet within the track)
- reducing size frpm 1080 to 740 for example
- changing size mode to distort

**Expectation**
As in V19.12 that the content stays at 1920 but is distorted to 740.
**What happens:**
Only the 'video-overlay rectangle' changes by the different size modes but not the content.

**What did I do else?**
Thought might have to do with the "Settings > Preview Scaling" I was trying but after turning that off and restarted Shotcut still the same.

Also did an export to check the final result. Export is exactly as in the preview.

Thanks for reading and many thanks for that great piece of Software!

bye morT

This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

**Comment by ddennedy** [comment]
This is already fixed for the next version.
