### ISSUE TITLE
Shotcut hangs on low memory

### ISSUE THREAD

**Issue by user2155** [mltframework/shotcut#829]
I had running FireFox along with Shotcut. I opened a new tab in FireFox, it took lots of memory, and Shotcut hanged. I quit FireFox, to free memory back, but Shotcut still hanging and not responding.

This is the second time for today.

Screenshot of Task manager when it happened:
https://filebin.net/rnl2op1vgfx75m5o/task_manager.jpg?t=00art3e2

Shotcut version 20.02.17

Windows 10 Pro Version    2004 (OS Build 19041.84)
BuildLab   19041.vb_release.191206-1406
BuildLab   19041.1.amd64fre.vb_release.191206-1406

P.S.
In the log file there is an error:

**[Error ] [mlt_pool] out of memory**

**Comment by ddennedy** [comment]
I guess we need to monitor free memory (or this error message), and prevent the user from doing anything more until more memory is made available (or offer to save and exit).

**Comment by ddennedy** [comment]
A low memory monitor and warning dialog was added for the next version 20.11 in  74543d97e5
