### ISSUE TITLE
Attempting to add transition by dnd on non-adjacent clips is allowed

### ISSUE THREAD

**Issue by metellius** [mltframework/shotcut#83]
Either this should work, or the action should be blocked completely until the clips are adjacent.
After this action, pressing ctrl-z gives a different timeline than what I had before the action. Pressing once more crashes shotcut.
![](http://i.imgur.com/iMy1ctL.gif)

**Comment by metellius** [comment]
You're sure this only happens when dragging right? (I don't have shotcut available to test atm)

**Comment by ddennedy** [comment]
It was already prevented when dragging left. There was an unchecked condition for dragging right.
