### ISSUE TITLE
200217: Glitch affects other parts than the filtered one in the export compared to 191231

### ISSUE THREAD

**Issue by M0RT1M4R** [mltframework/shotcut#831]
Hello, I could not find the following issue so I added it including examples.

Recorgnized in verion 200217 that the glitch effect is affecting other parts of my video not using the filter. Interesting for me, the additional glitches are different dependong on the export with constant bitrate or quality based VBR (please see videos listed below)

I thought it might have to do with the export codec because I switched from contant bitrate to quality based VBR but still the end result was affected - a lil different but not nice.
I export using the HEVC preset but also a test with H.264 had the issue.
I can not see the "extra" glitches in the preview window (I use unchanged preview window in 200217)

In version 191231 everything is as expected.

For my intro I use 3 video tracks each only with pictures and filters and 2 audio tracks.
![00 Shotcut Intro Setup](https://user-images.githubusercontent.com/25716937/75636353-46833680-5c1e-11ea-932c-8c9df7e2e864.png)

Please find the videos for comparison at Youtube:
**Issue in 200217**
- [00 SHOTCUT TEMPLATE Test Constant Bitrate CLOCK shaking V200217 HEVC preset](https://youtu.be/sZ2eaGArp8I)
- [00 SHOTCUT TEMPLATE Test Variable Bitrate CLOCK shaking V200217 HEVC preset](https://youtu.be/j92vL6rHk3E)
- [00 SHOTCUT TEMPLATE Test Variable Bitrate CLOCK shaking V200217 h 264 MAIN preset](https://youtu.be/Wpr0rU4OH8Q)

**as expected in 191231**
I only upload the VBR version to safe some space since I have not seen any unwanted glitches in the other exports.
- [00 SHOTCUT TEMPLATE Test Variable Bitrate CLOCK shaking V191231 HEVC preset](https://youtu.be/ZUSNuJkRnwE)

Thanks for reading.

Win10 64-bit w/ Shotcut 64-bit

**Comment by ddennedy** [comment]
Try disabling Export > Video > Parallel Processing when exporting.

**Comment by M0RT1M4R** [comment]
Thanks, now it is as expected!
Just curious, is this a workaround or do I have to keep that setting off from now on?

Thank you very much!

**Comment by ddennedy** [comment]
This is a workaround for certain combinations of filters and tracks. I am not entirely sure it was the Glitch filter. Basically, you can decide to always turn that off or keep this workaround in mind in case you notice unexpected image artifacts upon reviewing an export. To help me debug, can you please upload a copy of your project file after copying it as .txt? Also, it will be very helpful to provide the subscribe and bell images. For the other files, I can substitute my own media easily enough.

**Comment by M0RT1M4R** [comment]
Please find below the requested files.
I realized that the project file contains more data than just the little INTRO sequence I uploaded for review even if I deleted this from the project and saved it.
Does Shotcut not clear out the elements in the project file which are no longer used in the timeline?
Or do I misread this and it just lists the elements in my playlist?

Hope it helps. If you need something else please let me know.

![00 My YT Bell_transparent - grey](https://user-images.githubusercontent.com/25716937/75834725-2ccc2580-5dbd-11ea-862a-d15cd55a2982.png)
![00 My YT Subscribe button](https://user-images.githubusercontent.com/25716937/75834746-3b1a4180-5dbd-11ea-87dc-6c28b4ffa4b0.png)
[2020 03 01 HCR2 RoadRunner - INTRO saved by 200217 - Copy.txt](https://github.com/mltframework/shotcut/files/4284507/2020.03.01.HCR2.RoadRunner.-.INTRO.saved.by.200217.-.Copy.txt)

**Comment by ddennedy** [comment]
Notes: I reproduce the problem in older versions as far back as v19.09, and the problem goes away when I replace the still image on V1 with a video.

**Comment by ddennedy** [comment]
fixed in https://github.com/mltframework/mlt/commit/178dc0f43eef071c525bd9b99630c82842395354
