### ISSUE TITLE
Failed to export video, exit code 25

### ISSUE THREAD

**Issue by Hadron67** [mltframework/shotcut#835]
Hi, I'm using Shotcut 20.02.17 and have problem exporting video. It was always successful before but today it just failed. Switching off parallel support also didn't work. The job log looks like this
```
[producer avformat-novalidate] /media/cfy/fb8bd7ec-eef4-466c-9087-b679ef87710f/we-surface-layers.mp4
    checking VFR: pkt.duration 256
[h264 @ 0x7f14fcb2ff00] Reinit context to 1920x1088, pix_fmt: yuv420p
Failed with exit code 25
Failed with exit code 25
```
. It seems it has problem with `we-surface-layers.mp4`, so I split the timeline right at the 
 begining of the corresponding clip into to parts, pasting them into two seperate projects and export the videos seperately, the error didn't appear. However, when I try to concatenate the two videos the error appears again...

I also wonder what exit code 25 indicates since I couldn't find the same error in the forum.

I'm using Ubuntu 16.04 x86_64, kernel: 4.4.0-89-generic.

**Comment by ddennedy** [comment]
I am not aware of any error code 25 in the MLT code, which executes the export. It could be something in a dependency, but more likely it was a kill signal from the kernel. On Linux, signal 25 is SIGXFSZ, which is a problem related to file size. Is your volume nearly full? Have you turned on disk quota? You can check the video file for errors by opening it in Shotcut and choosing Properties > menu > Start Integrity Check Job.

**Comment by Hadron67** [comment]
Thanks for replying, and yes, my home directory was mounted on a seperate partition from root directory and only has 2GB of free space, but I was exporting the video to another partition that has 16GB left, so this may not be a problem with disk space? Also I've never used disk quota.

The exporting profile I choose was H.264 high, and my video lasts for 8:23. I've deleted the corrupted video file exported yesterday, I'll try exporting it again and do the integrity check, reply later.

**Comment by Hadron67** [comment]
That's strange, I can't reproduce it now, I have successfully exported 4 videos from the same project that has failed to export before. So it's very likely a problem with my system, not Shotcut itself. I'll close this issue for now, may reopen it when the error reappears. btw, thanks a lot for making this wonderful software.

**Comment by Hadron67** [comment]
That's strange, I can't reproduce it now, I have successfully exported 4 videos from the same project that has failed to export before. So it's very likely a problem with my system, not Shotcut itself. I'll close this issue for now, may reopen it when the error reappears. btw, thanks a lot for making this wonderful software.
