### ISSUE TITLE
I am using Version: 20.02.17 with Windows 10. I had many crashes editing my DJI OSMO Action videos.

### ISSUE THREAD

**Issue by rokozeit** [mltframework/shotcut#836]
H.264 / AVC; 1920x1080; Framerate 29,97... . I read about starting the program from command line and it actually helped. Since then no crashes anymore.

**Comment by ddennedy** [comment]
This is an invalid report and do not dump everything in the subject line. It needs to be more specific and actionable. You should try the different options in Settings > Display Method. Starting from the command line should not make a difference.

**Comment by rokozeit** [comment]
Hi, sorry, but the userinterface would only let me make the comment in the header. I was not able to write the text.

However, I tried all the options from Automatic, OpenGL, DirectX, Software (Mesa). It always crashed. Starting from command line solved the issue.
