### ISSUE TITLE
Enqueuing a job doesn't create the file immediately

### ISSUE THREAD

**Issue by Ekleog** [mltframework/shotcut#839]
Hello,

I've started using shotcut today, and it looks great! First time I'm using video editing software, though, so I'm lucky there was already an answer to my question on the discussion forum :)

That said, there is one issue I've met with, which is the following.

Steps to reproduce:
- Start a job that creates file `a.mp4`
- Before it is over, start another job that creates the file `a.mp4`
- Observe that no error message is ever given, yet the first job's file is erased by the second job

Suggested solution: `touch` the file as soon as the job is enqueued, which should be enough to “officially” reserve the right to this file

Does that idea make sense?

Cheers and thank you!
  Leo

**Comment by ddennedy** [comment]
I do not consider this a defect but rather an enhancement request to protect the stupid or careless user from doing something stupid. I will include if you submit a patch or pull request that works cross-platform (i.e. not literally `touch`).

**Comment by Ekleog** [comment]
I'm sorry, but being called “stupid or careless” kind of removed any will to try to help.

For the record, my usage included creating exporting lots of clips from a single video, named `foo-1.mp4`, `foo-2.mp4`, etc. at some split times, and I relied on the file list in the export dialog to know which name to give the next clip, only to find after the fact that some clips were missing because they had been overwritten by jobs after them.
