### ISSUE TITLE
Version 15.06.01 crashes on Mac OS X 10.6

### ISSUE THREAD

**Issue by cybercircuits** [mltframework/shotcut#84]
The program only crashes after successful encode. After encoding the Shotcut window freezes and consumes around 1GB RAM after encoding 200MB video. Forcing the program to Quit is the only option. After the force quit, you try to run the program is again stuck at Shotcut splash screen and loading plugins. The program will not fully load to display the window.

I need to delete the com.meltytech.Shotcut.plist file in order to load normally.

**Comment by ddennedy** [comment]
I do not reproduce this on my OS X 10.6, 10.8, or 10.10 machines. In a couple months - when we upgrade the version of Qt we use - we are dropping support for 10.6 and 10.7: https://blog.qt.io/blog/2015/05/15/qt-5-5-beta-released/
