### ISSUE TITLE
Ripple edits button triple state

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#843]
Shotcut 20.02.17

Ripple edits button has three states. Unpressed, something like half-pressed (button is slighter darker), pressed.
Ripple edits function works fine, in two states half-pressed and pressed.
But user expects that button should have only two states.
For example function disabled, you are pressing Ctrl+Alt+R, function is on now.
Then you want to disable function and click button by mouse, but it's enabled again.
![2020-03-29 0001](https://user-images.githubusercontent.com/27248144/77857991-7ae01780-7209-11ea-9bca-40555056ea59.png)
![2020-03-29 0000](https://user-images.githubusercontent.com/27248144/77857976-6734b100-7209-11ea-98e7-727724086af1.png)
![2020-03-29 0002+](https://user-images.githubusercontent.com/27248144/77857996-7fa4cb80-7209-11ea-809e-d650673b3dd8.png)
![2020-03-29 0003](https://user-images.githubusercontent.com/27248144/77858015-96e3b900-7209-11ea-9233-47dcad4b0447.png)
![2020-03-29 0004+](https://user-images.githubusercontent.com/27248144/77858020-9ba86d00-7209-11ea-899f-24d3d13aa22c.png)
![2020-03-29 0005](https://user-images.githubusercontent.com/27248144/77858022-9ea35d80-7209-11ea-9365-5d73db258a4f.png)

**Comment by ddennedy** [comment]
This also affected the snap and ripple-all-tracks buttons. This also changes the appearance to make the active state/color more clear:

![image](https://user-images.githubusercontent.com/1146683/80770872-752a6a00-8b06-11ea-8ac2-4c33759e5129.png)
