### ISSUE TITLE
20.02.17 release missing Settings->Preview scaling menu on linux 

### ISSUE THREAD

**Issue by fenugrec** [mltframework/shotcut#845]
Hi,
The package provided by my distro (Arch) is built with this script:
https://git.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/shotcut

and the resulting build lacks the `Settings->Preview scale` option described on the blog ( https://shotcut.org/blog/new-release-200217/ ). Here's what I see:

![settings](https://user-images.githubusercontent.com/10098613/77967556-5771a700-72b3-11ea-9193-2a78c4d1e43a.png)

I also posted an issue in my distro (Arch)'s bugtracker : https://bugs.archlinux.org/task/66033#comment187911 

Thoughts?

**Comment by ddennedy** [comment]
We are not responsible for builds not provided by us. This option will not appear unless it is built against the latest version of MLT.

**Comment by fenugrec** [comment]
Thanks, it's probably as you said: outdated mlt. Should be repackaged soon on our side.

**Comment by ddennedy** [comment]
Here is the code that shows the version detection used to remove the menu item
https://github.com/mltframework/shotcut/blob/master/src/mainwindow.cpp#L545

Here is the code that defines MLT_VERSION_PREVIEW_SCALE
https://github.com/mltframework/shotcut/blob/0a5fcfe2e03e3946d088059a8f26abe8443968f6/src/mltcontroller.h#L40
