### ISSUE TITLE
Preview scaling affects "rotate and scale" filter

### ISSUE THREAD

**Issue by fenugrec** [mltframework/shotcut#846]
Hi,
on 20.02.17, it appears that enabling "preview scaling" messes up clips with a "rotate and scale" filter. If I adjust parameters while preview scaling is enabled, then when I revert to "None" (or export in full resolution),  the rotation is ok, scale is correct but the offset shifts the clip partly outside the frame. Are the offsets applied in scaled-pixels somehow ?

**Comment by ddennedy** [comment]
That is already fixed in MLT for next release.
