### ISSUE TITLE
filters not applied to transition if transition already exists

### ISSUE THREAD

**Issue by lbesnard** [mltframework/shotcut#847]
Shotcut version 20.02.17

Not sure if it's a bug or a feature request. So feel free to close.

Let's say I have two clips next to each other in the timeline and I decide to create a transition between the two. Then I add a filter on both clips, such as a stabilization filter. Unfortunately, the filter won't be applied to the transition. I've tried editing the mlt file as well without success. So the workaround is to re-create the transition. Quite painful when most of the edit is done already on a movie.

Am I doing something wrong?

**Comment by ddennedy** [comment]
Normally,. this works (I just tested it), but there may be some sequences of actions, possibly including undo-redo, that breaks a strong relationship of the transition with a neighboring clip that leads to your problem. However, we need to figure out the steps to reproduce it from scratch (new project).

**Comment by lbesnard** [comment]
I'm trying again. In the preview window, the filters were definitely not taken into account within the transition. More specifically the smooth option of the stabilizer. I could see the video suddenly zooming out on the transition part, while it was zoomed in in the main clip (because of the smoothing). Even reloading the mlt didn't change anything. But maybe this is a cache issue?
I didn't tried exporting the video yet since I assumed that what I see in the preview window should be what I'll get. I'm doing an export now to check.

thanks for looking into it!

**Comment by lbesnard** [comment]
Yeah I can confirm that the rendered file still has this issue on the transitions. I manually rebuild them all and it's good. Let me know if you would like the mlt file to debug? cheers

**Comment by ddennedy** [comment]
An existing project with the problem does not really help since the real problem is some steps leading to the problematic result. But thanks. It is easy to recreate the problem within the project file by deleting the clip on one side of the transition, undo, and add a filter. That is probably the easiest way to reproduce it but possibly not the only.

**Comment by lbesnard** [comment]
awesome! always great to be able to re-create the bug! thanks for your time,it's a great tool

**Comment by ddennedy** [comment]
sorry, I closed the wrong one
