### ISSUE TITLE
opening a playlist item breaks master track filters if master is selected

### ISSUE THREAD

**Issue by lbesnard** [mltframework/shotcut#848]
Hi, 
I've been working on the same video project for a few weeks now (by project I mean the mlt file). 

In the last week, I have had to deal with a weird bug with ALL sound disappearing from the timeline project, preview and output file.

Here are my steps
1. open shotcut + MLT file
2. play preview -> works fine , sound is here
3. do any sort of modification on the timeline, like adding a track, shortening it.... something minimal
4. no more sound accross the whole project (peak meter doesn't show any sound)
5. save the (corrupted) file  and open shotcut with the same project
6. -> no more sound
7. open ANY file from the playlist, a mp3 file or video, the sound plays for this playlist object
8. play the timeline preview -> ALL the sound is now back on.
...

I can let you imagine that it gets tricky to do any modification. And it has only happened with this particular MLT file.

So I tried saving the project into 2 separated MLT files, one with a sound, one without any
[debug.zip](https://github.com/mltframework/shotcut/files/4413122/debug.zip)

Here is the diff of the two files
```
1366c1366
<       <property name="7[0]">-24.9755</property>
---
>       <property name="7[0]">-21.4247</property>
6266c6266
<   <tractor id="tractor21" title="Shotcut version 20.02.17" global_feed="1" in="00:00:00.000" out="00:05:02.302">
---
>   <tractor id="tractor21" title="Shotcut version 20.02.17" global_feed="1">
6325c6325
<     <filter id="filter247" out="00:05:02.302">
---
>     <filter id="filter247" in="00:00:-0.033" out="00:00:-0.033">
6339c6339
<     <filter id="filter248" out="00:05:02.302">
---
>     <filter id="filter248" in="00:00:-0.033" out="00:00:-0.033">
```

Not much difference ...  but I can open the 2 different projects in shotcut. One will have the sound, the other won't

**Comment by ddennedy** [comment]
That is very weird how opening a playlist item corrects the issue. 
In your NOSOUND.mlt you have a mute filter on the Master track. Inadvertently adding filters to the Master track is a common user mistake. When you do this, a funnel icon appears on the track header to show the presence of filters.

![Screenshot from 2020-04-01 17-29-34](https://user-images.githubusercontent.com/1146683/78198767-87998100-743e-11ea-9a33-6d39e9bd7bc8.png)

Pay attention to what is selected. A red border shows selection, and the Filters and Properties panels indicate at the top which timeline object they are affecting.

**Comment by ddennedy** [comment]
I will keep this as a bug that opening a playlist item is breaking all filters on the Master track!
