### ISSUE TITLE
Grouping/Link/Lock multiple Clip

### ISSUE THREAD

**Issue by mandhaniya** [mltframework/shotcut#849]
I have some questions… if any one can solve my problem
**1.** is there any option for _**Grouping/Link/Lock multiple Clip**_… so we can easily move these clips in timeline…???
every time i have to select all clips with **_Ctrl_** then able to move around the timeline.
**2.** There is no sequence creation in shortcut, is it possible to create a single clip/strip of  timeline/project with exporting video. so we can add the timeline clips to playlist in single strip like as we do in sequence method. 

like as....

![sequence creation](https://user-images.githubusercontent.com/11611920/78470571-4360f600-7748-11ea-99a9-5fc35993cff1.gif)

**Comment by ddennedy** [comment]
1. No and feature requests are not accepted here
2. You can load a project as a clip using File > Open MLT XML as Clip...

**Comment by mandhaniya** [comment]
thanks a lot, sir
The option I was really looking for.
you saved my life.
