### ISSUE TITLE
Sound issues on Mac OS X 10.6

### ISSUE THREAD

**Issue by cybercircuits** [mltframework/shotcut#85]
Disables the system sound when a video is open/played on Shotcut. The system sound restores only when Shotcut window is closed.

Steps to reproduce:
1. Test the system sound if working by playing any video or adjusting the volume level.
2. Open Shotcut and then open any video
3. Stop the playback video in Shotcut
4. Test the system sound. This time no sound can be heard.
5. Close Shotcut. Test the system sound again and everything is back to normal.

I also found out that plugging and unplugging the earphone will restore the sound.

**Comment by ddennedy** [comment]
I know about this problem, and I have experienced it before. We use SDL for audio output, and it might be something weird in SDL and OS X versions. I do not reproduce this on my OS X 10.8 or 10.10 machines. In a couple months - when we upgrade the version of Qt we use - we are dropping support for 10.6 and 10.7: https://blog.qt.io/blog/2015/05/15/qt-5-5-beta-released/
