### ISSUE TITLE
This is the only place I know to get help for issues w/ shotcut so sorry if I'm stupid and in the wrong place. 

### ISSUE THREAD

**Issue by user82775** [mltframework/shotcut#850]
But the other day I installed shotcut to my mac(its an old mac but I just need something to edit youtube with), and I was messing with the software trying to figure my way around the program and accidentally removed the toolbar and timeline and I cannot pull anything up. Is there any way to reset shotcut and restore its defaults on mac? Asking for a friend here. Thanks!

**Comment by bmatherly** [comment]
The right place to request support is on the forum.

Your question has already been answered:
https://forum.shotcut.org/t/shotcut-layout-is-wrong/10045
