### ISSUE TITLE
merge with next clip

### ISSUE THREAD

**Issue by Jogala** [mltframework/shotcut#851]
Hi,

sometimes I click the "split at play head (s)" button but actually it was at the wrong place. Now I would like to merge the thereby erroneously created clips, hence undo the "split at play head (s)" action. Of course I could press ctrl + z, but sometimes I realize it way to late... 

I googled and found screenshots of a "merge with next clip" option that appears when right-clicking the left clip, of the two clips that are supposed to be merged. 

merge with next clip option is missing...
![bug_shotcut](https://user-images.githubusercontent.com/5442389/78595997-4e507f00-784b-11ea-9f48-ed56ad9605e8.jpg)

How it should be (found via google images) ...
![shot_cut_how_ot_should_be](https://user-images.githubusercontent.com/5442389/78596055-6aecb700-784b-11ea-86b1-e65dd3b4e535.jpeg)

But in my version (20.02.17 running on Ubuntu) that option is not available!

Best

Jogala

**Comment by ddennedy** [comment]
This function has not been available for a long time. To workaround is easy: Lift (delete) one of the two clips and drag the end of the other to occupy the empty space.

**Comment by Jogala** [comment]
Like you say, it is a work around. Why isn't this feature available anymore? 
It is very contra intuitive and I don't understand why it got removed then.

**Comment by ddennedy** [comment]
It was removed due to some bugs, and then nobody has taken an interest to fix them. It is not a big leap to understand that these two are the same clip and go from frame N to frame N+1, so I can simply remove one of them and extend the other. It is a very basic edit operation. This is probably why no one bothered to fix it.

**Comment by Jogala** [comment]
@ddennedy  could you then relabel it as a feature request please?

**Comment by GLLM** [comment]
Just my 2 cents : I would use such a feature, because once it's split (even worse when one has detached audio), if you need to move them, you need to select all parts to do it ... and cut/paste does not work ;)
