### ISSUE TITLE
Segmentation fault on 4K monitor (bugs.debian.org/952901)

### ISSUE THREAD

**Issue by alexmyczko** [mltframework/shotcut#853]
Please see the debian bug report against shotcut at:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=952901

**Comment by ddennedy** [comment]
I use Shotcut/Linux on a 4K monitor without a problem. Of course, our portable/snap/appimage builds use Qt 5.9.7, but even the flatpak, which uses Qt 5.13.2 works.

**Comment by eszlari** [comment]
> but even the flatpak, which uses Qt 5.13.2 works.

5.14.1
