### ISSUE TITLE
Failed to create OpenGL context for format QSurfaceFormat

### ISSUE THREAD

**Issue by fu-hsi** [mltframework/shotcut#859]
Version: shotcut-win64-200412.exe
OS: Windows 10

After changing video mode to software (as far as I remember, becouse I checked all modes to restore GPU acceleration - without success!) we can't launch application anymore.
Re-installation not helped.

> Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(DoubleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) .
> This is most likely caused by not having the necessary graphics drivers installed.
> 
> Install a driver providing OpenGL 2.0 or higher, or, if this is not possible, make sure the ANGLE Open GL ES 2.0 emulation libraries (libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in the application executable's directory or in a location listed in PATH.

**Comment by ddennedy** [comment]
You can change the opengl key in registry or run the installer and choose the option to remove all settings from the registry.
https://shotcut.com/notes/configuration/

**Comment by ddennedy** [comment]
See also #722

**Comment by fu-hsi** [comment]
After trying to remove settings we have another exception from Installer:

Error opening file for writing:
C:\Program Files\Shotcut\Qt5Core.dll

This operation takes more time that I expected :)
And why GPU acceleration option is not available anywhere?
I disabled once this option, because stabilization filter can't work with that, I can't understand, why?

**Comment by ddennedy** [comment]
The file is locked because a shotcut.exe (or qmelt.exe) is still running possibly hidden. You can try to kill them or reboot.

**Comment by fu-hsi** [comment]
Yes, I restarted PC and removed Shotcut successfully, that's why I deleted my previous post.
You can clean this conversation too.
Thanks.

**Comment by ddennedy** [comment]
GPU Effects was removed from the settings menu because it is unstable and too many people reporting problems. You can enable it in the configuration/registry using documentation linked above.
