### ISSUE TITLE
Crash when copying filters from one clip to another

### ISSUE THREAD

**Issue by IgelRM** [mltframework/shotcut#861]
Win 10 x64
Shotcut 20.04.12

It appears I found a reproducible crash when copy filters from one video clip to another. Filters I used are "Text: Simple", Fade In/Out Video/Audio and "Scale and Rotate".

[shotcut-log.txt](https://github.com/mltframework/shotcut/files/4536096/shotcut-log.txt)

**Comment by ddennedy** [comment]
Sorry, I was not able to reproduce it after trying multiple times and with the filters  in different orders. Maybe it depends on something else in particular. You can upload a small .mlt file here that reproduces it for you, and that might help.

**Comment by IgelRM** [comment]
I later noticed I had accidentally copied some filters into the Master track. Here's the MLT file with everything removed except those clips I tried to copy the filters to.

[CS Hidden3-crash.zip](https://github.com/mltframework/shotcut/files/4541040/CS.Hidden3-crash.zip)

**Comment by ddennedy** [comment]
I reproduced the crash in the reported version 20.04 and 20.07 but not latest 20.09 or 20.10 versions. So, this was resolved through some other means.
