### ISSUE TITLE
html text - crashed on close

### ISSUE THREAD

**Issue by seema84** [mltframework/shotcut#864]
Version: 20.04.12

shotcut crashed every time when closing the program, if there are several html text in the project

**Comment by seema84** [comment]
**Deprecated the following video filters. These will be removed in the next version.
    Text: 3D
    Text: HTML**

but not other alternative? there is no other way to create and format text

**Comment by ddennedy** [comment]
> but not other alternative?

The alternatives are Text: Simple and the new **Text: Rich**. HTML5 integration is completely removed in the next version.
