### ISSUE TITLE
Inconsistencies on UI when re-using a playlist clip with new in-position after old out-position.

### ISSUE THREAD

**Issue by Gizemquea** [mltframework/shotcut#868]
Windows 10 64-bit, any recent version of shotcut.

Steps to reproduce:

1.) Open empty project,
2.) Create video track,
3.) Drag a single clip into the playlist
4.) Select clip
5.) Set arbitrary in- and out-postion somewhere in the first half of the clip
6.) Drag clip to video track
7.) Double-click clip in playlist (optionally pause clip replay if you're not fast enough with the mouse)
8.) Use mouse (single click) to set a NEW position quite some time after the original out-position -> position in clip jumps back to original out-position.

This alone is a real nuisance and can be reproduced indefinitely by repeating steps 7+8), but it gets "better":

9.) Click exact spot from step 8 again to "really" set the new position, marker finally stays at the desired position
10.) Hit "i" to make this the new in-position
11 .) Use any means to set a new out position a few seconds later (mouse or keyboard) -> new range in clip is indicated
12.) Drag clip to video track and place immediately after first clip -> observe that the clip length is not consistent to what has been indicated in step 12 while dragging over video track
13.) Play the project timeline and observe that the In-position for the second segment has in fact moved back to the original out-position of the first segment
14.) Select clip in playlist and observe that the in-postion is indeed not where you manually set it in step 10 but has jumped back to the original out-position of segement 1 once again.

This is driving me nuts whenever I need to use multiple segments from one clip, which happens quite a lot.

**Comment by ddennedy** [comment]
> 8.) Use mouse (single click) to set a NEW position quite some time after the original out-position -> position in clip jumps back to original out-position.
>
> This alone is a real nuisance and can be reproduced indefinitely by repeating steps 7+8), but it gets "better":

I agree and reproduce it. A behavior of the player that will not change is that during normal forward playback, it stops at the out point. That is what is being triggered here, and I will try to make a change to avoid it.

> 6.) Drag clip to video track
> 12.) Drag clip to video track and place immediately after first clip 

From where? Source player or Playlist?

> 12.) Drag clip to video track and place immediately after first clip -> observe that the clip length is not consistent to what has been indicated in step 12 while dragging over video track

I have not reproduced this yet. I suspect some step is disconnecting the Source player from the playlist item, and you are dragging from the playlist. The Source player is not always showing a playlist item by design. It could be showing something else if you use Open File, drag a clip from file manager to player, double-click a media file in Recent, use Copy or Cut on the timeline, use Open Other. If the shot you wish to add is in Source player, I suggest you drag from the Source player.

**Comment by ddennedy** [comment]
> position in clip jumps back to original out-position

fixed

**Comment by Gizemquea** [comment]
Thanks for looking into this and responding and fixing things so fast. I really appreciate your support, after all you're doing this for free!

The source player stopping at the current out point is actually a very good thing and I'm using this quite a lot since I do need frame-exact audio cuts for some of my clips

I am usually dragging from the external monitor which should be the same as "from the source player" - almost never from the playlist itself.

"observe that the clip length is not consistent to what has been indicated in step 12 while dragging over video track" meant the following: 

Let's say I originally
1.) had in-position at 00:02:00 and out-position at 00:03:00
2.)  dragged this 1-second clip into the video track and 
3.) then I set the new in-position to 00:05:00 and the new out-position at 00:06:00 and
4.) drag the new segment to the video track (without releasing it yet)
then I can already see that the new segment is going to 3 times longer than the first one, even though the indication of in- and out-position in the source player suggests that it is a 1-second segment.

Of course, the second segment is indeed 3 seconds long once I release it on the video track and it extends from 00:03:00 to 00:06:00.

If I select the clip in the playlist again, the in- and out-position are displayed consistently to what has been added to the track - so the inconsistency is in the display of the new in-position (for the second segment) **before** and **while** I drag the second segment of the clip i.e. the "real" in-position is not where I set it and how it was displayed in the first place 

I think that the two issues are somehow related, so maybe your fix has already improved this as well.

**Comment by ddennedy** [comment]
Sorry but I still could not reproduce it with the added information. I believe I understand your steps and explanation. Maybe it is a timing issue such as steps 7 - 8 or 8 - 9 must be performed quickly.  Is it intermittent or reliable problem for you?

**Comment by Gizemquea** [comment]
This is reliable as far as I can tell i.e. the issue is already there when I start shotcut with a new project from scratch and it seems to behave the same all the time. I am really using this a lot (sometimes more than 100 times within one project), so I might have missed it if it "accidentially" works in a few percent of the cases, but I doubt that.

It seems to be important that I actually just set the "player position" by mouse click (as opposed to dragging the position marker) and then press "i" in order to make this the new in-position (as I was trying to describe with step 9 and 10 of my original report). 

**If I really do drag the in-position marker by mouse, then it works as expected.**

Maybe that's what you're missing when trying to reproduce the second part of my report?

I'm using the keyboard a lot since it improves the workflow quite a bit (if would improve it even more so if keyboard commands would actually queue independently instead of waiting for operations to complete before a new command is accepted i.e. three presses of page down would **always** result in 3 seconds forward, regardless of whether I can type faster than the hard drive seeks), so I avoid dragging the in- and out-position markers whenever if I can.

**Comment by ddennedy** [comment]
I was single clicking the mouse to seek followed by I key and not dragging the in point marker.

**Comment by Gizemquea** [comment]
> I was single clicking the mouse to seek followed by I key and not dragging the in point marker.

Did you use an external monitor for video display?

I just tried the latest build (20.05.19) and I can confirm that the issue you were able to reproduce and fix is really gone in my setup too.

I decided to investigate the other phenomenon from step 9 onwards a little bit further and to my suprprise it does seem make a difference if I use an external monitor for video display (which I always do).

Using an external monitor I can **always** reproduce the behavior I described from step 9 onwards, but you don't need external monitor display to get odd behavior, and it is most probably related:

If I only use the regular shotcut window, and I always drag from the video player (NOT the playlist), then I can do the following
a.) choose a clip from the playlist, set in- and out-position and drag it to a video track
b.) choose same clip from the playlist again, stop replay before it reaches the out-position
c.) advance to old out-position by alt+right
d.) advance 2 seconds by shift+pg down
e.) set new in-position by i
f.) advance 1 second by pg down
g.) set new out-position by o
h.) drag from video player and HOVER above video track
i.) do NOT add to track but drag back to video player area and release there
j.) observe that the in-position changes to the old out-position, in- and out-position are now 3 seconds apart

In case I'd just add to track in step i.) I'll get the right lenght in the video track (1 second), but once I select the clip again in the playlist, I have just the same 3 second segment i.e. the in-position has magically moved yet again.

**Comment by ddennedy** [comment]
I finally reproduced the problem by following the latest steps and then I noticed - without even dragging and dropping - how sometimes the playlist details view would not update when setting an in point > current out point. I found a problem updating the playlist item when setting an out point < in point. I fixed these, and I hope it is closely related to the original problem dragging source to timeline. Please test and confirm.

**Comment by Gizemquea** [comment]
> I finally reproduced the problem by following the latest steps and then I noticed - without even dragging and dropping - how sometimes the playlist details view would not update when setting an in point > current out point. I found a problem updating the playlist item when setting an out point < in point. I fixed these, and I hope it is closely related to the original problem dragging source to timeline. Please test and confirm.

Will do as soon as the new build is available. Once again thanks a lot for all the effort you're putting into this!
