### ISSUE TITLE
Incorrect duration displayed in webm file

### ISSUE THREAD

**Issue by h8h** [mltframework/shotcut#875]
Affected Systems and Versions:
* `macOS 10.11.6` with `Shotcut 20.04.12`
* `Linux 5.4.43-1-MANJARO #1 SMP PREEMPT Wed May 27 20:25:12 UTC 2020 x86_64 GNU/Linux` with `Shotcut version ARCH-20.04.12`

Steps to reproduce:
1. Make a webm video [webrtc screen capture demo](https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/)
2. Download webm video
2. Open shotcut
3. Create a new project
4. Open the webm video
5. Take a look at the duration or see picture attached below
6. Move the webm to the timeline 
7. shotcut freezes

![Video Length of webm video](https://i.imgur.com/Bga1Gxl.png)

It seems that `ffmpeg` has the same problem with the file:
```
ffmpeg version n4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from 'Downloads/screen-recording.webm':
  Metadata:
    encoder         : QTmuxingAppLibWebM-0.0.1
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp8, yuv420p(progressive), 939x1030, SAR 1:1 DAR 939:1030, 24.42 tbr, 1k tbn, 1k tbc (default)
At least one output file must be specified
```
The bug is already reported and seems to be fixed, see [Ticket 1444](https://trac.ffmpeg.org/ticket/1444)

Hope you can fix it.

Thanks a million.

**Comment by ddennedy** [comment]
We use FFmpeg libraries from their latest release, which is currently 4.2.3, and that reports duration not available in ffprobe on my screen recording:
```
ddennedy@Gamerbox-9400:~/src/shotcut$ ~/Desktop/Shotcut/Shotcut.app/ffprobe '/home/ddennedy/Downloads/screen-recording.webm' 
ffprobe version n4.2.3-5-g221e490 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
  configuration: --prefix=/root/shotcut/shotcut/Shotcut/Shotcut.app --disable-static --disable-doc --enable-gpl --enable-version3 --enable-shared --enable-runtime-cpudetect --enable-libtheora --enable-libvorbis --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libvpx --enable-libopus --enable-libjack --enable-libxcb --enable-libpulse
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from '/home/ddennedy/Downloads/screen-recording.webm':
  Metadata:
    encoder         : QTmuxingAppLibWebM-0.0.1
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp8, yuv420p(progressive), 675x429, SAR 1:1 DAR 225:143, 1k tbr, 1k tbn, 1k tbc (default)
```
This is not a general problem with WebM: for example, WebM files generated with Shotcut.
MediaInfo also fails to report a duration:
```
ddennedy@Gamerbox-9400:~/src/shotcut$ mediainfo '/home/ddennedy/Downloads/screen-recording.webm' 
General
Complete name                            : /home/ddennedy/Downloads/screen-recording.webm
Format                                   : WebM
Format version                           : Version 2
File size                                : 4.77 MiB
Writing application                      : QTwritingAppLibWebM-0.0.1
Writing library                          : QTmuxingAppLibWebM-0.0.1
IsTruncated                              : Yes

Video
ID                                       : 1
Format                                   : VP8
Codec ID                                 : V_VP8
Width                                    : 675 pixels
Height                                   : 429 pixels
Display aspect ratio                     : 16:10
Frame rate mode                          : Variable
Compression mode                         : Lossy
Language                                 : English
Default                                  : Yes
Forced                                   : No
```
Notice it also says it is truncated. I do see that VLC and GNOME Videos (gstreamer) are able to understand a duration. There is a change FFmpeg master has a fix for the duration (your link is out of date and not applicable here), but it will still not be supported for editing in Shotcut because it is variable frame rate (see Media Info and Shotcut Properties reports Frame rate 1000 fps (typical for VFR). You can still try to use it, however, and I have by overriding the duration while the clip is in the Source player before adding it to the Timeline (workaround):

![image](https://user-images.githubusercontent.com/1146683/84097325-18e62000-a9b9-11ea-9663-97979f8ed423.png)

**Comment by ddennedy** [comment]
BTW, Shotcut is not deadlocked when you drag it to the timeline. It is just taking a *very* long to draw a 32860 hour video. We do not artificially limit your video duration, but I strongly encourage the user to limit the duration (using Properties or trimming in Source) before adding more than a couple of hours to the timeline. We are starting to add more progress bars and spinners (next version), but a spinner that goes on for very long is ultimately the same user experience as showing nothing at all (going nowhere).

**Comment by h8h** [comment]
Thank you.

Thanks for the workaround.
