### ISSUE TITLE
error al exportar

### ISSUE THREAD

**Issue by MaicolFA** [mltframework/shotcut#876]
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

al exportar vota un error, dice fallo al exportar y queda 25% depende del proyecto y de hay no pasa, version: windows 10. shotcut 20.04.12, 32 bits

**Comment by ddennedy** [comment]
English only accepted here. Google Translation is not good:

> When exporting, vote an error, say failure when exporting and there is 25% depends on the project and there is no pass

There is clearly not enough information to do anything here. I can only guess from some things your in your description and 32-bit that you may be running out of memory, and you need to significantly limit your project (SD) to keep from running out of memory.
