### ISSUE TITLE
Transition bugs

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#879]
Shotcut version 20.06.14.

I don't really know there is one bug or two. First crops right video while you're creating transition by DnD. And second when you try to reverse it all back by Ctrl+Z.

I don't know how to show this by text and screens so watch this [video](https://youtu.be/Boo4XZDQ7y0) please.

**Comment by luzpaz** [comment]
@LedAlex can you still recreate this ?

**Comment by LedAlex** [comment]
I'm not using Shotcut newer versions than 22.12.21.
It has similar bug, but it increase size of first clip up to 4 hours on Ctrl+Z.
https://youtu.be/aECzVF2e6pA

**Comment by ddennedy** [comment]
No longer reproduces, based on too old version, and newest versions do not let you keep going back and forth to create and remove the transition repeatedly in one dragging operation.

**Comment by LedAlex** [comment]
Just will leave it here... dead end happened several years ago...
https://youtu.be/tdO3rGfSipk
