### ISSUE TITLE
Crash when dragging on empty track

### ISSUE THREAD

**Issue by metellius** [mltframework/shotcut#88]
1. Start shotcut
2. Add a video track
3. Do a drag (anywhere starting on 1 px distance) within this region:
![](http://i.imgur.com/vSznrV7.png)

**Comment by ddennedy** [comment]
I can reproduce this on 15.06, but not git master HEAD as of today. Maybe it was fixed with the fix for #86?

**Comment by metellius** [comment]
Not unlikely, I'll try and see

**Comment by metellius** [comment]
Confirmed, the #86 fix covered this.
