### ISSUE TITLE
Segfault when creating a new solid color

### ISSUE THREAD

**Issue by mxa** [mltframework/shotcut#881]
This happens on `Shotcut-20.04.12` and the `Shotcut-200614.glibc2.14-x86_64.AppImage`, tested on Linux Kubuntu 20.04.
When adding a new solid color Shotcut ends with a segfault.
![shotcut_segfault](https://user-images.githubusercontent.com/1220707/85230074-ed6a2900-b3ed-11ea-8e8d-42b4209aaddc.gif)

**Comment by ddennedy** [comment]
I reproduced this only when using JACK and the exact steps shown. There are a few different ways to avoid it as workaround:
- use Open Other from the main toolbar
- do not use JACK
- do not first open an existing project
- use Properties to change an existing color instead of Open Other

**Comment by mxa** [comment]
Thanks @ddennedy for resolving this so quickly, I really enjoy working with shotcut!
