### ISSUE TITLE
"Show In Folder" not working in Appimage (Linux)

### ISSUE THREAD

**Issue by mxa** [mltframework/shotcut#882]
On Linux Kubuntu 20.04 the context menu option to show the rendered output is failing for Shotcut 20.06.14

```
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by kde-open5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5KIOWidgets.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5KIOCore.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5I18n.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5CoreAddons.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5JobWidgets.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5Service.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5Completion.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5IconThemes.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5ConfigWidgets.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5WindowSystem.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5WidgetsAddons.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5ConfigGui.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5ConfigCore.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5Crash.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5DBusAddons.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5AuthCore.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5Archive.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5ItemViews.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5Codecs.so.5)
kde-open5: /tmp/.mount_Shotcu0fwgtZ/usr/bin/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /usr/lib/x86_64-linux-gnu/libKF5GuiAddons.so.5)

```

**Comment by ddennedy** [comment]
Sorry, but I guess this cannot be fixed in a portable binary build due to differing Qt library versions. We are looking to upgrade our Qt libraries, and then it will likely work in your version and build of KDE but some others.

**Comment by eszlari** [comment]
This works with the flatpak version.

**Comment by mxa** [comment]
> This works with the flatpak version.

Is there a flatpak for the BETA?

**Comment by eszlari** [comment]
```
flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta org.shotcut.Shotcut
flatpak run org.shotcut.Shotcut//beta
```

**Comment by ddennedy** [comment]
Or wait for release tomorrow

**Comment by alexmyczko** [comment]
There's also an official package in Ubuntu, what about that? https://packages.ubuntu.com/focal/shotcut

**Comment by mxa** [comment]
> There's also an official package in Ubuntu, what about that? https://packages.ubuntu.com/focal/shotcut

It's very much behind the current version and @ddennedy multiple times declared that he doesn't support this package which makes it inofficial.

**Comment by alexmyczko** [comment]
> It's very much behind the current version and @ddennedy multiple times declared that he doesn't support this package which makes it inofficial.

Ah sorry for being outdated, of course I'm updating the package, but it needs some time to enter debian, and ubuntu gets its copy from there. (currently ubuntu is in freeze for 20.10 release) and packages in a stable release don't get updates.
http://phd-sid.ethz.ch/debian/shotcut/1/

That's fine, Ubuntu users usually create bugs in launchpad (ubuntu bug tracker), Debian users in Debian BTS. Users are free to use direct upstream bug tracking of course.

**Comment by mxa** [comment]
Sorry, didn't realize you are the maintainer of the package and didn't want to offend. I'm aware of how packages from debian make their way into ubuntu. Certainly having a debian package for Shotcut is very useful and a great contribution. It makes it easy for users of debian and debian based distributions to get their hands on a stable Shotcut version.

**Comment by ddennedy** [comment]
There is a new beta coming in a day or two based on a newer Qt. You can try [last night's AppImage](http://builds.us.meltytech.s3.amazonaws.com/shotcut/Shotcut-20.10.16.glibc2.14-x86_64.AppImage) of it.
"Show in Folder" is working for me in it on Ubuntu 20.04.

**Comment by ddennedy** [comment]
This is working for me in the new beta you can find here in GitHub releases.

**Comment by mxa** [comment]
Maybe a regression? It isn't working in 64-201128.AppImage any more.
