### ISSUE TITLE
CPU encoding with default export settings is significantly slower with 20.06.28

### ISSUE THREAD

**Issue by serebit** [mltframework/shotcut#883]
On Solus (a Linux distrubution that ships Shotcut), the build of Shotcut 20.04.12 exports default MP4 files significantly faster than the build of Shotcut 20.06.28. I'm the maintainer of the package, and I can personally verify that no buildscript changes were made. I also don't believe it to be a package outside of Shotcut that's causing this behavior, as I've reinstalled both versions of Shotcut to verify that the issue persists only in the new version.

In essence, when exporting the same project with default settings using the CPU encoder, 20.06.28 is *significantly* slower. It seems to slow down as it's encoding, as well, getting stuck at 8% on my two test projects for about a minute. Hardware encoding with VAAPI on my RX 480 is unaffected.

**Comment by ddennedy** [comment]
Is parallel processing turned on in export > video? That default changed from version 20.02. That is a likely source of difference. Almost every release someone reports something like this, and I do not reproduce it. Maybe I will give a comparison at some point. Are you using our binary builds?

**Comment by serebit** [comment]
Nope, built from source. I actually tried with parallel processing enabled and disabled on both versions and saw the same result. Exact same encoding settings on both test projects as well.

**Comment by serebit** [comment]
Plus, like I mentioned in the issue body, this is a difference between 20.04 and 20.06, so it couldn't be the default change to parallel processing in 20.02 anyway.

**Comment by serebit** [comment]
Also like I said in the issue, I'm the one who built it from source, so the buildscripts for the two versions are exactly the same. I can try to reproduce it with binary builds, though. For the sake of clarity, the buildscript is just
```
qmake
make
make install
```
with some CXX flags and packaging-specific environment variables.

**Comment by ddennedy** [comment]
What you are describing (not reproducing it with hardware encoder) depends heavily the mlt, ffmpeg, and libx264 dependencies. I just ran a test and I got 2:23 with both versions without hardware encoder or parallel processing on. We use versions of dependencies listed in  [scripts/build-shotcut.sh](https://github.com/mltframework/shotcut/blob/master/scripts/build-shotcut.sh). I am not aware of anything that changed in MLT that would make a difference. Sorry, but I not available to debug other people's builds.

**Comment by serebit** [comment]
Mm. Alright.

Just for the record, I'm not stumbling in here with no idea what I'm doing. I know the dependency versions matter and that regressions can happen if using newer versions.

But that aside, I mentioned already that the versions of everything else on the system stayed the same between tests, which includes the three dependencies that you mentioned. Additionally, the projects I used for testing and the encoding settings did not change between tests. The only thing that changed is the version of Shotcut I used to run the export.

I'm more than willing to test this more if you can't reproduce the problem. That said, I don't appreciate being dismissed solely based on the fact that you've had other people report similar things with prior versions. I don't file issues on projects for help debugging my own builds, I can do that myself (and I already do it myself).

**Comment by ddennedy** [comment]
> The only thing that changed is the version of Shotcut I used to run the export.

Shotcut does not actually do the export. It runs qmelt (or melt), which is a MLT command line tool. I am not dismissing you or your experience. I am dismissing that it is a valid bug, does not reproduce in our builds (which you failed to test and compare), and choose not to help distro packages and discourage users from using them.

**Comment by serebit** [comment]
Asking me to test with the binary version instead of closing the issue and disrespecting me would have been preferable. I ran a test with the prebuilt tarball and it ran fine, so it's likely a dependency issue and I'll see about resolving it myself. 

I wanted to file an issue in good faith that I might be helping out a piece of software that I find useful, but clearly issues from users that you don't feel like supporting aren't welcome, so I'll refrain from doing so in the future.

**Comment by bmatherly** [comment]
I just did a test on Windows with the official builds:
20.14.12:  5:18
20.6.28: 4:51

So I guess the newer version is faster on my computer.

It is very time consuming to try to reproduce bug reports in all the various environments that people can use. For people who refuse the use the official builds, the burden of proof falls on the the submitter to show that the problem exists in the code, and not the build.

You did not describe the project you are using for comparison. It can be useful to bisect the problem. Start with opening and exporting a single file. Try different export formats. That can help narrow if the slowness is in the encoding. If encoding is consistent with a single source file, then add individual filters or transitions to try to deduce which filter might be running slower than expected. This process of elimination can be time consuming. But often one hint about where the problem is occurring can unlock a focused attack on the problem.

**Comment by serebit** [comment]
Thanks for the explanation @bmatherly. I was planning on investigating this already, so I'll give your suggestions a try and see if they lead anywhere. It didn't *seem* to be related to effects or transitions, as I initially saw the issue with a project with only two clips and no effects before seeing the issue again in a project with multiple effects and transitions, but I certainly could be wrong.

My apologies for being rude with that last comment, @ddennedy. Regardless of my personal frustration, there was no need for me to get snarky with you for what admittedly did seem to be an issue that's out of scope for the project.
