### ISSUE TITLE
Audio: a crackle on the audio track in version v20.06

### ISSUE THREAD

**Issue by VictorVG** [mltframework/shotcut#885]
In to forum.ru-board.com question (Russian to English translation):

> **VDVolkov**
> 
> Dear forum users!
> 
> Please clarify (who knows) the following in the Shotcut version above 20.02.17.
> I use it for quick and easy slicing. I use E *** s for work (not an advertisement for this wonderful video editor).
> Actually a question. Cut the Soviet cartoon "Robbery ...". In the extreme version of Shotcut. There is a crackle on the audio track. I thought I was going to run it with a declicker or a decorator in RX3 (not advertising) and that’s it. Drove away. Checked in AU and Foobar2000: no clicks. I upload the file in Shotcut extremely version >> there are clicks. I tried to upload the file to Shotcut 20.02.17 and the original file and processed: no clicks.
> Question: is it a glitch of new versions of Shotcut or hands are crooked (it is doubtful, I work a lot and for a long time, though .... Live for a century ...). I enclose a fragment of the file (beginning 133 kB).
> 
> https://transfiles.ru/0mlcc

I don't know ansver - me needed oscilloscope screenshot and audio specter diagram for analyses process - possible is can be local hardware problem... (&)

**Comment by ddennedy** [comment]
If you copy SDL2.dll from the older version into the folder containing shotcut.exe for the new version 29.06 does the problem go away?

**Comment by VictorVG** [comment]
Idea! Me try it.

**Comment by VDVolkov** [comment]
ddennedy wrote:
If you copy SDL2.dll from the older version into the folder containing shotcut.exe for the new version 29.06 does the problem go away?

Yes. It work.

**Comment by VictorVG** [comment]
If replace sdl2.dll v2.12 to sdl2.dll v2.05 test result is success and problem is resolved:

>**VDVolkov**
>
>sended: 05:42 06-07-2020 
>
> Copied. The problem has disappeared. Maybe in the next version Shotcut correct.

**Comment by ddennedy** [comment]
Another use on our forum confirmed the same problem and solution. There will be a new version 20.07 with this fix soon.

**Comment by VictorVG** [comment]
Big thanks! I also messed up my project - I put 64-bit modules in a 32-bit program. Well, that at startup displays an error message. Hastened - made fun of people. :)

**Comment by ddennedy** [comment]
It would be great if someone can test this new build: http://builds.us.meltytech.s3.amazonaws.com/shotcut/shotcut-win64-200707.zip

**Comment by VDVolkov** [comment]
Version 20.07.07. There is no problem. Thanks
