### ISSUE TITLE
Noise when silence is played back

### ISSUE THREAD

**Issue by ryze42** [mltframework/shotcut#886]
I installed the new Version (20.06.28) on Windows 10 Pro (1909 Build: 18363.900).
I've encountered the problem as I was editing a file. As I started the playback, some clicking noice was in the background. Even if I'm playing pack complete silence (for example by playing back a white color) there is some noise. I've recorded the loopback and attached it as a zip file.

I've tried:
- Switching Audio Devices
- Updating Audio Drivers
- Reinstalling

Thanks in advance for your help!

[shotcutnoise.zip](https://github.com/mltframework/shotcut/files/4904942/shotcutnoise.zip)

**Comment by ddennedy** [comment]
I believe this is a duplicate of #885. It has a nightly build with a fix you can test.

**Comment by ryze42** [comment]
Sorry for producing a duplicate. I'll test the new version and get in touch if the problem persists.
Anyways, thanks for your help! :)
