### ISSUE TITLE
Blank white bar blocking top of window

### ISSUE THREAD

**Issue by isawilson** [mltframework/shotcut#889]
Issue started today. Opened Shotcut and the entire top of the window (toolbars etc) was blanked out white (see image)
![shotcut issue 20200717](https://user-images.githubusercontent.com/68424192/87775578-3f03a900-c81e-11ea-8055-22cc9fe4d598.png)

The window can't be closed or minimised from the buttons at the top, although clicking them does make the computer think it has been as I was able to accidentally open programmes on the desktop behind. I'm using the most up to date version but can't click the "about" tab to get the exact code. OS is windows10 home version 1909 64 bit 18363.959

**Comment by ddennedy** [comment]
Sorry, but I do not know what is wrong, and it does not happen to me. It might be a bad interaction between the GUI library we use and your graphics driver. Here are some things to try to recover from this:
- Press F11 once or twice - this toggles maximize and might jiggle something into working.
- Reboot the computer - this resets the graphics hardware and driver.
- Remove the Shotcut registry settings to restore default layout. This will clear your recent entries, but you can still get to the projects through the file system. There are 2 ways :
  - Run the Shotcut installer and check the checkbox that says to remove the registry settings
  - Delete the registry settings manually using the Windows Registry Editor and the [information here](https://shotcut.org/notes/configuration/).
