### ISSUE TITLE
Translation proccees.

### ISSUE THREAD

**Issue by firew4lker** [mltframework/shotcut#89]
Hello.

I am interesting in participating to the translation (Greek language) for ShotCut. Is there a particular method I must follow?

**Comment by ddennedy** [comment]
We use transifex to coordinate translations. Please create an account there and request to make a Greek translation for the project: https://www.transifex.com/projects/p/shotcut/

When you have translated at least 80% of the strings, I will add it to the next monthly release. Thank you
