### ISSUE TITLE
GUI font too small when running Shotcut-200711.glibc2.14-x86_64.AppImage on Linux Mint 20

### ISSUE THREAD

**Issue by catscarlet** [mltframework/shotcut#895]
OS: Linux Mint 20
Shotcut versions: Shotcut-200711.glibc2.14-x86_64.AppImage
Display Resolution: 1920x1080

Here is the screenshot:
![Screenshot from 2020-07-28 16-26-00](https://user-images.githubusercontent.com/10594035/88639190-136ea180-d0ef-11ea-9a01-51ea1ed09149.png)

I was using Mint 19.3 with Shotcut-200412.glibc2.14-x86_64.AppImage and it's good. After I reinstall Mint to 20, Shotcut GUI shows like this.
I looks like the font size is too small. It looks like only 3 or 4 px.I don't know how to change Shotcut's font size.

**Comment by ddennedy** [comment]
This is due a combination of our Qt version (5.9), your OS/desktop environment and its resolution and density/scaling. You need to use a command line option to override it https://shotcut.org/notes/command-line-options/
Try with `--QT_SCALE_FACTOR 2`

**Comment by catscarlet** [comment]
> This is due to a combination of our Qt version (5.9), your OS/desktop environment and its resolution and density/scaling. You need to use a command line option to override it https://shotcut.org/notes/command-line-options/
> Try with `--QT_SCALE_FACTOR 2`

Thanks.

I tried `--QT_SCALE_FACTOR 2` but it worked too far,

![Screenshot from 2020-07-29 09-58-07](https://user-images.githubusercontent.com/10594035/88747856-38602480-d182-11ea-8bd2-1c02e2d05d24.png)

Then I guessed I may try `--QT_SCALE_FACTOR 1` and it worked.

![Screenshot from 2020-07-29 09-57-39](https://user-images.githubusercontent.com/10594035/88747864-3e560580-d182-11ea-9c75-bed86c3788f5.png)

Wish this could be fixed soon.

**Comment by Asherathe** [comment]
The portable version and the snap are the same as the AppImage for me, on Peppermint 10 at 1920x1080. The flatpak is the only one that looks reasonably sized without tweaking.

**Comment by ddennedy** [comment]
The next version of Shotcut portable, snap, and AppImage are using Qt 5.15.1, the same as the latest Flatpak where Qt has massively improved support for high DPI and font sizes on Linux. There is a beta in github releases for you to give it a try.
