### ISSUE TITLE
Items on the timeline randomly selected and moved around while scrolling

### ISSUE THREAD

**Issue by DoctorOctagonapus** [mltframework/shotcut#899]
Running on MacOS 10.15.6, have observed this issue in Shotcut versions 20.6.28 and 20.7.11. I insert an item onto the timeline, but when scrolling using the two-finger gesture on the touchpad, it will select and drag the item under the cursor and move it around, either forwards and backwards or to another track. It doesn't do it every time, it appears random as to when it does or doesn't. v20.04.12 does not exhibit this behaviour.

**Comment by ddennedy** [comment]
This behavior did not change between versions. A touchpad also supports click to select. It is very possible for a trackpad to perceive some swipes as a click. We have no control over that sensitivity. The only way to totally prevent this us to disable selection at all times, and that is simply impossible.

**Comment by ddennedy** [comment]
I did reproduce a difference. It is not just subtle difference in user behavior as I suspected. Related to this, I notice the playhead moves more easily or frequently now. Normally, a click in empty area moves the playhead. So, this extra clicks detected can either move playhead, select, or move.
