### ISSUE TITLE
While exporting the video to Youtube video format then it's showing undefined pa_json_parse error

### ISSUE THREAD

**Issue by venkatesh-m-aiknow** [mltframework/shotcut#901]
Ubuntu 16.04 LTS; Shotcut 20.07.11.

While exporting the video to Youtube video format then it's showing undefined pa_json_parse error. What is the solution for this?

mlt_repository_init: failed to dlopen /home/sabari/Downloads/Shotcut/Shotcut.app/lib/mlt/libmltavformat.so
  (/home/sabari/Downloads/Shotcut/Shotcut.app/lib/libpulse.so.0: undefined symbol: pa_json_parse)
Failed with exit code 11
Failed with exit code 11

![error](https://user-images.githubusercontent.com/67941244/90443801-75bd2f80-e0fa-11ea-8831-380c1312b1c7.png)

**Comment by ddennedy** [comment]
This is a known issue from the forum:
https://forum.shotcut.org/search?q=pa_json_parse

Your version of Ubuntu is no longer supported. I will not be fixing this. The latest version that does work is 20.04. I will update the downloads page to reflect this.

**Comment by venkatesh-m-aiknow** [comment]
Thank you
