### ISSUE TITLE
Fine timeline adjustments cause segfaults

### ISSUE THREAD

**Issue by nrnrnr** [mltframework/shotcut#906]
I'm running Shotcut 200711 on Debian Linux 10 (buster), on an amd64 platform.

I've got two tracks in my timeline: one audio-only pulled from an AAC-encoded phone, and one with both audio and video. I'm trying to get the audio to sync up exactly, but when I make very fine adjustments to the tracks, it segfaults consistently.  I'm working at high zoom level and the adjustments are small.

The segfault occurs after I have slid the audio, at the moment I release the mouse.

I've confirmed it also happens with the .mp4 directly (not just audio-only)

Attached stdout and stderr.

[shotcut.stdout.txt](https://github.com/mltframework/shotcut/files/5163568/shotcut.stdout.txt)
[shotcut.stderr.txt](https://github.com/mltframework/shotcut/files/5163570/shotcut.stderr.txt)

**Comment by ddennedy** [comment]
I found a few different triggers when trying to reproduce this and fixed them. I hope this fixes the problem you had.
