### ISSUE TITLE
 [producer_xml] failed to load transition "frei0r.cairoblend"

### ISSUE THREAD

**Issue by hjjety1234** [mltframework/shotcut#907]
I use Ubuntu 16.04.6 LTS run melt

the command line : 
          xvfb-run -a /root/Shotcut/Shotcut.app/melt 1.mlt -consumer avformat:demo.mp4

show can not load transition 
         [producer_xml] failed to load transition "frei0r.cairoblend"

has no idea what make this happen.

**Comment by ddennedy** [comment]
Maybe a dependency problem
```
cd /root/Shotcut/Shotcut.app/
source source-me
ldd lib/frei0r-1/cairoblend.so
```
Look for missing in the output of ldd.

**Comment by hjjety1234** [comment]
> cd /root/Shotcut/Shotcut.app/
> source source-me
> ldd lib/frei0r-1/cairoblend.so

thanks , miss  libcairo.so.2 , i fix by apt-get install libcairo2.
