### ISSUE TITLE
Dosnt render proxy from new video material

### ISSUE THREAD

**Issue by survivor303** [mltframework/shotcut#908]
**Ubuntu 20.04.1 LTS; Shotcut 20.07.11 from Flatpak.**

Shotcut dosnt render proxy files, the ui says that it uses those:
![image](https://user-images.githubusercontent.com/3097696/92293885-890c2f80-ef2f-11ea-9671-4cbcf160e560.png)

But the proxy directory (in project directory) not getting filled with those and nothing isnt happen while importing new video files to shotcut.

**Comment by ddennedy** [comment]
I just tested the Flatpak, and it is working. But it is probably not working exactly like you expect it to work. Looking for files in a folder that you browse to and not seeing them is not a good way to determine it. Please understand that "project folder" is something special and specific in Shotcut and not simply where the project file is saved. The best way to look for the files is with the project open and choose Settings > Proxy > Storage > Show....
Here is the documentation: https://forum.shotcut.org/t/proxy-editing/18517
If you still have a problem, then provide evidence and steps.

**Comment by survivor303** [comment]
Now i try newest (20.09.01) **beta appimage**.
That version is trying to make those proxies but failed, because of hardware encording fails:

ffmpeg version n4.3.1-6-g0a012a5 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
  configuration: --prefix=/root/shotcut/shotcut/Shotcut/Shotcut.app --disable-static --disable-doc --enable-gpl --enable-version3 --enable-shared --enable-runtime-cpudetect --enable-libtheora --enable-libvorbis --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libvpx --enable-libopus --enable-libjack --enable-libxcb --enable-libpulse
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[AVHWDeviceContext @ 0xa4b900] Opened VA display via X11 display :0.
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /tmp/.mount_ShotcuzP5MBR/usr/bin/lib/va/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_0_39
pci id for fd 6: 1002:731f, driver (null)
pci id for fd 6: 1002:731f, driver (null)
libva error: /tmp/.mount_ShotcuzP5MBR/usr/bin/lib/va/radeonsi_drv_video.so init failed
libva info: va_openDriver() returns 2
[AVHWDeviceContext @ 0xa4b900] Failed to initialise VAAPI connection: 2 (resource allocation failed).
Device creation failed: -5.
Failed to set value 'vaapi=vaapi0:,connection_type=x11' for option 'init_hw_device': Input/output error
Error parsing global options: Input/output error
Failed with exit code 1
---------------------------------

It working fine without hardware encoding but it is slow as expected.

**Comment by ddennedy** [comment]
VA API compatibility with tar, AppImage, and snap builds is a separate issue tracked here in a separate ticket. VA API is very version sensitive with 3 versions that must agree.
