### ISSUE TITLE
I tried to use shotcut on windows 7 

### ISSUE THREAD

**Issue by Reaper10** [mltframework/shotcut#91]
I tried tp use shotcut on windows 7 I got this when I tried to start shotcut  how do I fix this

Error:
This program requires OpenGL version 2.0
with the framebuffer object extension.
<img width="427" alt="capture" src="https://cloud.githubusercontent.com/assets/8137561/8490888/20ed2542-20f6-11e5-88c8-0144448f3c79.PNG">

**Comment by ddennedy** [comment]
Shotcut is incompatible with your system. You need to upgrade your video card, GPU, and/or its driver. More info here:
http://www.shotcut.org/bin/view/Shotcut/FrequentlyAskedQuestions#Why_does_it_crash_on_Windows_upo

This is a bug-tracker - not a help or support system - and this is not a bug and will not be fixing it. However, that might change in a few months when we try to make a version less dependent upon OpenGL, and you can try again in a few months.

**Comment by Reaper10** [comment]
how meny is few months.

**Comment by Reaper10** [comment]
I tried in my windows 8.1 laptop it works just fine.
