### ISSUE TITLE
Shotcut's "Edit Friendly" files are too large 

### ISSUE THREAD

**Issue by durgaswaroop** [mltframework/shotcut#911]
On Windows 10 with the latest version of Shotcut, I am seeing that the converted files are huge. 

For example, I've a HD clip of about 1.5GB. When I imported that in, shotcut wanted to convert it to edit friendly file. I have allowed it with intermediate setting. 

The converted file is almost 40 GB!!
That's just too much. Is there a way to do this without making the files too big? If I pick the lower setting, would it affect the output video quality? 

Also, what should be done with the converted files after the project is done? Is there a way to have the project usable but without having to backup/keep the converted files around?

**Comment by ddennedy** [comment]
This is not a defect, and this area is just for defects. If you just want someone to talk to and get help use a forum.
