### ISSUE TITLE
Position Path dont export

### ISSUE THREAD

**Issue by seema84** [mltframework/shotcut#914]
Version 20.09.13
Filter: size and position

after export the position path changes are not in the video
but in shotcut it is shown

**Comment by ddennedy** [comment]
I do not reproduce this, and there is not enough information. Did you change the resolution in Export?

**Comment by seema84** [comment]
> 
> 
> I do not reproduce this, and there is not enough information. Did you change the resolution in Export?

No i dont change the resolution in Export.

**Comment by seema84** [comment]
what information do you need?

**Comment by ddennedy** [comment]
Exact steps from an empty project or a small project file that demonstrates the problem.
Also, specify whether proxy or preview scaling is turned on.

**Comment by seema84** [comment]
1. create a new projekt
2. add a picture in timeline
3. add size and position filter
4. set presetting for example the first "slowly zoom out"
5. export the project

**Comment by seema84** [comment]
proxy or preview scaling is not active

**Comment by ddennedy** [comment]
Unable to reproduce.

**Comment by seema84** [comment]
mh :(

**Comment by seema84** [comment]
https://i.imgur.com/IFWttQS.png

https://i.imgur.com/IonAnG5.png

**Comment by ddennedy** [comment]
I even switched my system numeric format to German (comma for decimal):

![image](https://user-images.githubusercontent.com/1146683/94741360-e1fd9680-0328-11eb-9fb9-673160a4ea8a.png)

**Comment by seema84** [comment]
i have found the cause. my filter is only called "size and position" (without rotating). i think this is an old filter?
after some crashed and deactivation of hardware gpu (unstable) he now shows me the right filter like yours. so it works

**Comment by seema84** [comment]
but now i cant open all my old projects

**Comment by ddennedy** [comment]
You were very well informed that GPU Processing is experimental, unstable, and unsupported.

**Comment by seema84** [comment]
I have a possibility to fix my old projects?

**Comment by seema84** [comment]
I can disable GPU processing in the project file?

**Comment by ddennedy** [comment]
No. You can edit the XML to remove things and convert them, but it is not documented, and there are no formulas to convert the parameters of GPU effects to similar parameters of related CPU effects. It is probably better if you simply turn back on GPU if you really need to.

**Comment by seema84** [comment]
that sounds not good, mh
