### ISSUE TITLE
Rich Text Filter Cursor

### ISSUE THREAD

**Issue by seema84** [mltframework/shotcut#916]
Version 20.09.27

with the new text filter i cannot see the text cursor
this looks like a bug

**Comment by ddennedy** [comment]
This depends on the scale of the preview (size relative to the Video Mode). In other words, the scaling of the full size text down to the preview resolution makes the very thin cursor sometimes disappear between letters. You can see this by switching to the Player view/workspace layout while the filter is selected. Unfortunately, it is out of control with the version of the GUI library we use, and it will be revisited after an upgrade but there is no guarantee.

**Comment by ddennedy** [comment]
This is fixed for the next version 20.11 in dbcf354998
