### ISSUE TITLE
Aliasing issue when using Size and Position filter.

### ISSUE THREAD

**Issue by firew4lker** [mltframework/shotcut#92]
When using the Size and Position filter, the shrinked video has aliasing issues. Is it a common thing when shrinking down videos?

http://i.imgur.com/0PK9Ft8.png

Tested on GNU/Linux 15.07.02

**Comment by ddennedy** [comment]
You are probably basing this observation on the UI preview. The UI preview runs uses Settings > Interpolation, which defaults to nearest neighbor (no interpolation) for speed. When you encode, it defaults to bilinear, and you have to enter something special in the Other tab of the encode settings to change it. I just ran a test with debug logging to verify it is still working correctly.

**Comment by firew4lker** [comment]
For the record. The screenshot was from the exported video. Not the preview window.

**Comment by ddennedy** [comment]
same issue as https://github.com/mltframework/mlt/issues/590

**Comment by ddennedy** [comment]
This is fixed in https://github.com/mltframework/mlt/issues/590
