### ISSUE TITLE
Irreversible Audio Muting

### ISSUE THREAD

**Issue by eppolito** [mltframework/shotcut#922]
**OS:** Pop!_OS 20.04 (close enough: Ubuntu 20.04)
**Shotcut:** 20.09.27 (via Flatpak)

**Effect:** Audio muted on all tracks with no obvious way to unmute (and no mute filters applied to clip)

**Steps to produce effect:**
(1) drag clip to timeline.
(2) apply mute filter to clip.
(3) copy filters.
(4) split clip at some point (move playhead to center of clip and press "s").
(5) select resulting left clip and cut (click clip and press "x").
(6) apply mute filter while no clips selected.

At this point audio is universally muted, and there is no way I can find within the GUI to restore audio.

**Additional notes:** Problem persists after restarting shotcut.  I think something awkward happens in the .mlt, but I haven't run a diff to check the effect.

**Comment by bmatherly** [comment]
I would guess that it pasted on the output
https://forum.shotcut.org/t/how-do-i-remove-output-filters/20960

**Comment by ddennedy** [comment]
After step 5 nothing is selected, and there is a recently reported bug I reproduced that lets you paste filters when nothing is selected. When that happens the filters are applied to **Timeline > Output**. This should be easy to fix for the next version.

https://forum.shotcut.org/t/if-you-paste-a-filter-after-removing-the-file-you-chose-for-said-filter-it-will-affect-all-files/21530

**Comment by bmatherly** [comment]
I would suggest to forbid pasting to Output and Track filters since I think that is an uncommon use case and a common source of confusion.

**Comment by ddennedy** [comment]
> I would suggest to forbid pasting to Output and Track filters since I think that is an uncommon use case and a common source of confusion.

People will complain about that change.

**Comment by bmatherly** [comment]
>>I would suggest to forbid pasting to Output and Track filters since I think that is an uncommon use case and a common source of confusion.

>People will complain about that change.

Correct. However, I predict the complaining will create less noise than the questions causes by accidental pasting. Maybe it would be possible to only allow pasting from similar producers: clip->clip, track->track

**Comment by eppolito** [comment]
Thanks for the swift reply to an ultimately silly question!  I wasn't aware of output filters.
