### ISSUE TITLE
why some filters are missing

### ISSUE THREAD

**Issue by asartori86** [mltframework/shotcut#927]
Hi,
I see that some filters are missing in my installation (e.g., HTML, text). What am I missing?

I am using the master branch on a linux machine

**Comment by ddennedy** [comment]
This expected due to change. Read the news on our website for more info.

**Comment by TomaszGasior** [comment]
Is there any plan to restore ability to use HTML overlay?

**Comment by ddennedy** [comment]
There are no plans to bring back the HTML overlay. You can learn in this forum post how some people [use OBS](https://forum.shotcut.org/t/what-to-do-if-when-webvfx-disappears/18132) to record a video of HTML5 to then bring into Shotcut. However, I suggest that you simply learn to use a proper animation tool as there are not many good UIs for HTML animation. Free, cross-platform, open source examples are Blender, Synfig, Krita, and enve.
