### ISSUE TITLE
Snapping feels inconsistent

### ISSUE THREAD

**Issue by ingobecker** [mltframework/shotcut#929]
In shotcut 20.09.27 installed via flathub, snapping doesn't work consistently. Often times i have the playhead very close to the position where i want to snap a clip to. In this example, the clip only snaps to the playhead, not the end of the clip i want to snap it to:
![Clip only snaps to nearby playhead](https://gist.github.com/ingobecker/0257c69a7c129ccf29746c0595f3fb26/raw/6b70616b2c04a33806e91935c61bb57d461fad2f/shotcut_snap_playhead.gif)

This is very annoying, because i have to first drop the clip back somewhere on the timeline, move the playhead so it's not near to the clips end anymore, grab the clip i want to position again and snap it to its final location.

If if move the playhead 2 frames further away from the clips end, it's impossible to snap the clip to the playhead at all. It only snaps to the clips end:
![Clip only snaps toe nearby clip end](https://gist.github.com/ingobecker/0257c69a7c129ccf29746c0595f3fb26/raw/6b70616b2c04a33806e91935c61bb57d461fad2f/shotcut_snap_clipend.gif)

Snapping should work for the clips end as well as the playheads position. Might be related to #509

**Comment by ddennedy** [comment]
I do not experience this much, and I do not volunteer to change it. You can workaround it by zooming in on the timeline. You can also suspend snapping temporarily by holding <kbd>Alt</kbd> while you are dragging.

**Comment by ingobecker** [comment]
Temporarily disabling snapping by holding <kbd>Alt</kbd> is very helpful in a lot of those snapping situations. Didn't know about that feature. Thanks.
