### ISSUE TITLE
Removing clip cause split to the clip under it.

### ISSUE THREAD

**Issue by firew4lker** [mltframework/shotcut#93]
When I remove a clip from the time line (right click -> remove) it will create a split (at the starting point of the removed clip) to the underlying clip. If the underlying clip is locket it doesn't happen. 

Is it a feature?

http://i.imgur.com/NO7dkEz.png
http://i.imgur.com/5Xguoea.png

Tested on GNU/Linux with 15.07.02.

**Comment by metellius** [comment]
This is ripple delete in action, not a bug.
