### ISSUE TITLE
How do you install plugins?

### ISSUE THREAD

**Issue by jcc10** [mltframework/shotcut#939]
I am trying to install [this plugin](https://forum.shotcut.org/t/plugins-for-360-video/12396) for use with my 360 footage. I was wondering how to install it with a flatpak install.

BTW: the [bitbucket repo](https://bitbucket.org/leo_sutic/bigsh0t/src/master/) has more info on how to set it up.

**Comment by ddennedy** [comment]
Already answered in the forum. There is no way to install plugins for Flatpak. More information about making plugins for Shotcut are on the web site: https://shotcut.org/notes/make-plugins/

**Comment by jcc10** [comment]
Apologies, I thought this was the flatpak repo since it is where the issues link on flathub goes to.
