### ISSUE TITLE
run last version that includes html overlay video filter

### ISSUE THREAD

**Issue by albfan** [mltframework/shotcut#940]
now we have flatpak

https://flathub.org/apps/details/org.shotcut.Shotcut

is it possible to install the latest flatpak version that includes that?

I think this was related to Qt and webvfx, isn't it?

https://forum.shotcut.org/t/what-to-do-if-when-webvfx-disappears/18132

What's the latest version of shotcut that depends on Qt 5.9 LTS?

relates #927

**Comment by ddennedy** [comment]
> This tracker is for defects only!

# Read the Shotcut [News](https://shotcut.org/blog/).
# Learn you want version 20.07.11.
# Get the commit sha1 you want from the [flatpak repo](https://github.com/flathub/org.shotcut.Shotcut/commits/master)
`4d320d80d96d57417f216387be682e8194c36622`
# Learn how to install a [specific flatpak version](https://docs.flatpak.org/en/latest/tips-and-tricks.html#downgrading).

**Comment by albfan** [comment]
Thanks a lot. Sorry for the noise. Just for the record, flatpak has its own commits

```
$ sudo  flatpak remote-info --log flathub org.shotcut.Shotcut | grep -B 1 20\\.07\\.11
      Commit: 3147de8abd8fdc6c29b73ca85bf27fbf93800317f76b44457d0b90b92b4b4b44
     Subject: shotcut 20.07.11 (4d320d80)
```

so FTR final command line is:

    sudo flatpak update   --commit=3147de8abd8fdc6c29b73ca85bf27fbf93800317f76b44457d0b90b92b4b4b44  org.shotcut.Shotcut

![html filter from flatpak](https://user-images.githubusercontent.com/220968/98287007-0d694600-1fa5-11eb-890a-2c36cfefd1bf.png)
