### ISSUE TITLE
Shotcut very laggy

### ISSUE THREAD

**Issue by Kapsarovchess** [mltframework/shotcut#941]
This tracker is for defects only! For feature requests, see [our discussion forum](https://forum.shotcut.org/).

If you’re reporting a defect, make it as detailed as possible, and include both your OS and Shotcut versions (e.g. `macOS 10.11.5; Shotcut 16.05.01`).

Shotcut seems to run slow at times while editing. Restarting your computer fixes it, so it is presumably a RAM problem.

**Comment by ddennedy** [comment]
Search the forum for "laggy" issues. Yes, it uses memory and can get slower, but this bug report is not specific enough.
