### ISSUE TITLE
Shotcut version 20.10.31 stucks and crashes

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#943]
New Shotcut 20.10.31 stucks and crashes.

In first case video stops to update and becomes black.
Second case then application totally crashes.
![2020-11-06 0001](https://user-images.githubusercontent.com/27248144/98361624-eeb68e00-203c-11eb-93cd-53e4f5a35072.png)
![2020-11-06 0000](https://user-images.githubusercontent.com/27248144/98361631-f1b17e80-203c-11eb-8dea-35001cc0148a.png)

**Comment by ddennedy** [comment]
Unable to reproduce. It works for a lot of others as well. What are the steps?

Try clearing your configuration and try again. The way to do that requires editing the registry.

I hope you understand I may not be able to do anything about this.

**Comment by ddennedy** [comment]
Check if you are running low on memory. There have been some changes to reduce memory usage as well as monitor the available memory after this version.

**Comment by LedAlex** [comment]
I'm now on Shotcut 20.11.28. It runs pretty well except deadlock freezes sometimes happens on very large projects (as on second screenshot). Can't really say how to reproduce it. I think Shotcut can't work with lot of data in one project, it becomes unresponsive and makes everything very slow.
