### ISSUE TITLE
Menu bug

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#944]
Shotcut version 20.10.31 Windows

With two monitors which have different DPI and scale some menus have monster size of elements.
![2020-11-06 0002+](https://user-images.githubusercontent.com/27248144/98397520-88e3f980-2070-11eb-945c-02b04b000880.png)

**Comment by ddennedy** [comment]
OK, this seems related to what is being reported on the forum:
https://forum.shotcut.org/t/ver-20-10-31-right-click-mouse-menu-not-working/22275/21

https://forum.shotcut.org/t/display-a-menu-of-additional-actions-doesnt-open/22314

**Comment by LedAlex** [comment]
I know that I can move application on other monitor and everything will be fine. (See attached screen)
The problem is that one monitor 2K and the other 1280x1024.
I can't make same scale (or change) on them, that leads to unreadable fonts on one of them. Too small on one or too big on other.
In previous versions of Shotcut everything was fine on any monitor at any scale.
![2020-11-06 0003](https://user-images.githubusercontent.com/27248144/98403542-2db70480-207a-11eb-8be0-52e826e5391f.png)

**Comment by LedAlex** [comment]
Shotcut version 20.09.27.
I can drag it from one monitor to other as I want.
![2020-11-06 0007](https://user-images.githubusercontent.com/27248144/98404516-c8fca980-207b-11eb-8a07-d6fd2662f29c.png)

**Comment by ddennedy** [comment]
This is related to a change in Qt, which we are required to upgrade. I think it may be due to `QT_SCALE_FACTOR_ROUNDING_POLICY` added recently as [documented here](https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt). I will do some experiments with multiple monitors and this option. Qt does not very well support fractional scaling (125, 150, or 175) on Windows, and its default is `Round`.

**Comment by LedAlex** [comment]
I thought so, about QT. Now in my situation it definitely takes scale 200% for menu from 2K monitor, which is primary.

**Comment by ddennedy** [comment]
The menus were rewritten in b755e9ec8246377679ca5ca3a4ab8f7480c13f7c to use a new API as they were using old, deprecated API to fix the menu opening bug in forum links above. It fixes this issue too (but not when using 150% with RoundPreferFloor policy, which is not fixable).
