### ISSUE TITLE
Size filter bug

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#946]
Shotcut version 20.10.31

If one side of sizable element is zero, than position stucks somewhere in outer space.
![0001](https://user-images.githubusercontent.com/27248144/98406913-d5830100-207f-11eb-898e-6fdfc38a0a86.png)
![0002](https://user-images.githubusercontent.com/27248144/98406916-d6b42e00-207f-11eb-96d1-c69916d9802f.png)
![0003](https://user-images.githubusercontent.com/27248144/98406917-d6b42e00-207f-11eb-948c-37655e1063de.png)
![0004](https://user-images.githubusercontent.com/27248144/98406918-d74cc480-207f-11eb-807c-63eb4f65be8d.png)
![0005](https://user-images.githubusercontent.com/27248144/98406919-d7e55b00-207f-11eb-9a5d-a7429f03f0dd.png)

**Comment by ddennedy** [comment]
FYI, the Horizontal and Vertical fit parameters now control an anchor point with respect to the scaling and rotation. So, when the centers options are on as they are for you and by default, when you change the size, it also changes the position to keep the center in the center. When you change scale by using zoom, mouse wheel, or increment/decrement a size numeric spinner this works very natural. When you change a size to 0 things go bad as you experienced. I reproduced your problem, and we need to add some corner case and error handling. In the meantime if you prefer to enter values numerically, you might want to change the fit parameters to Top and Left. However, 0 size values can still cause a problem. To workaround, change to 1 or press undo button next to size parameter to recover.

**Comment by LedAlex** [comment]
I don't use corners in that project, because there are 3 screenshots from mobile phone at the same frame. I need to align them. Shotcut can't handle this. By corners it's difficult to make them one size. So the only way is to enter manually calculated values.
