### ISSUE TITLE
Time flicker bug

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#948]
Shotcut version 20.10.31

First bug.
When you add new content in fresh project, current time can be set randomly to any value.
Even there can be no current time marker in timeline at all.

Second bug.
When you drag time marker to the end of timeline and further, current time becomes some random value.

See video: [Shotcut time flicker bug](https://youtu.be/DyeB5bzLdvA)

**Comment by ddennedy** [comment]
1. When you drag-n-drop media into the timeline we do not do any seeking unlike other actions from toolbar or keyboard shortcut. I am not going to change that even for a special case of dropping to empty timeline. What is really the problem? Not important in my opinion, change is risky, and change will only be done if important.

1. I know but again not important and the risk of change is not worth it.

**Comment by LedAlex** [comment]
The problem is that current time does not corresponds to time marker in timeline.
That's only one case of problem. It exists in older versions too, but I don't know how exactly reproduce it.
Usually then you edit project suddenly marker goes to randomly time at the project and the action you are performing executes in wrong place. Usually deletes or inserts somewhere you are not expecting.
