### ISSUE TITLE
AAC audio plays out of sync

### ISSUE THREAD

**Issue by tseeling** [mltframework/shotcut#951]
Version: Latest Shotcut from Fedora 33 repository.

Scenario: separate video mp4 and audio aac tracks (audio record from Android phone).

Play from timeline works the first time.
Stop video, change marker in timeline, press play, video starts, but audio is out of sync, continues to play from old position, not from the position of the marker.
Works with audio track imported from wav file, does not work for aac format.

**Comment by ddennedy** [comment]
We do not support builds not provided us based on our download page. Not all format or files can properly support seeking. Obviously, it tries very hard and has very good coverage, and it depends heavily on FFmpeg, which is no slouch. If it does not work, then you need to convert it as you have done. Also, I do not have this file or Android phone for that matter. You can provide a sample, and I will let you know if I think it should be seeking properly.
