### ISSUE TITLE
Last frame bug

### ISSUE THREAD

**Issue by LedAlex** [mltframework/shotcut#952]
Shotcut version 20.10.31

You can go further than the end of timeline by pressing play button.

[Shotcut last frame bug](https://youtu.be/Dx6MAH-sAwc)

**Comment by megabugman** [comment]
I guess this is the same issue, after deleting a video the play head can be moved too far left. 
also I noticed the program got sluggish for a few seconds , as shown in the video.
![bug2](https://user-images.githubusercontent.com/17204819/100558072-07693b00-32ad-11eb-9552-60ba306f9140.gif)
