### ISSUE TITLE
Shotcut on MacOs Big Sur not starting

### ISSUE THREAD

**Issue by piotrnikov** [mltframework/shotcut#957]
Hello,

Just in case you didn't know, Shotcut is not working/starting on le latest MacOs system (11.0.1).
It just says Application not responding and I have to force quit it.
Have a great day,

Piotr

**Comment by ddennedy** [comment]
related https://bugreports.qt.io/browse/QTBUG-87014

Please try in a terminal
`QT_MAC_WANTS_LAYER=1 /Applications/Shotcut.app/Contents/MacOS/Shotcut`

**Comment by piotrnikov** [comment]
Oh that command works!
Thanks so much!

**Comment by ddennedy** [comment]
awesome!
Next, I will try to make the app set that on itself so you do not need to do it. Then, I will update this ticket with a nightly build you can test.

**Comment by piotrnikov** [comment]
Thanks again!

**Comment by ddennedy** [comment]
Please test the updated beta without using terminal and the environment variable.
https://github.com/mltframework/shotcut/releases/download/v20.11.14/shotcut-macos-signed-201115.dmg

Anyone and all reading this are invited to test it, but please only comment about the basic ability to start and run Shotcut on macOS Big Sur and not other bugs you may experience that are quite likely unrelated to macOS Big Sue.

**Comment by piotrnikov** [comment]
Hello!
This seems to work here.
Thanks!

**Comment by only-cliches** [comment]
The newest pre release also works on Apple Silicon Macs through Rosetta 2.
