### ISSUE TITLE
backward incompatibility: position and size filter produces different result than before in version 201031

### ISSUE THREAD

**Issue by dougkdev** [mltframework/shotcut#958]
shotcut 20.10.31 on ubuntu 18.04
.mlt files created a few versions ago that use size/position filter to zoom into a specific part of a large image produced the same result in every version up to and including 20.09.27. Suddenly version 20.10.31 produces a different result.

The image can be downloaded from https://eoimages.gsfc.nasa.gov/images/imagerecords/74000/74042/world.200405.3x21600x10800.png

A small .mlt that reproduces the bug is attached.

Images of result of loading the .mlt in version 200927 and differing result loading the .mlt in version 201031 also attached
[size_position_bug.mlt.txt](https://github.com/mltframework/shotcut/files/5543416/size_position_bug.mlt.txt)
![size_position_200927](https://user-images.githubusercontent.com/13754318/99201228-3d63d680-2767-11eb-8491-4607ff568b5b.png)
![size_position_201031](https://user-images.githubusercontent.com/13754318/99201234-448ae480-2767-11eb-8e0f-44dfb95a4cad.png)

**Comment by ddennedy** [comment]
This occurs when the image width > height and height > 16000 due to new clamping that broke aspect ratio.
