### ISSUE TITLE
"insert track" command bug

### ISSUE THREAD

**Issue by gutko** [mltframework/shotcut#961]
when track is created with "insert track" it doesnt seem to respect layerig of its content in relation to other tracks and its content always comes on top of  scene. bug in v20.11.14 beta
v20.10.31 works as intended
win64

**Comment by ddennedy** [comment]
No, it works fine. Pay attention to what it is the current track.

**Comment by gutko** [comment]
this is from Shotcut version 20.11.25
https://youtu.be/ix6edUS1dJ0
v20.11.14 beta works the same way
last version working properly is v20.10.31
