### ISSUE TITLE
"insert track" command bug #2

### ISSUE THREAD

**Issue by gutko** [mltframework/shotcut#963]
reposting this to make sure you will see it

this is from Shotcut version 20.11.25
https://youtu.be/ix6edUS1dJ0
v20.11.14 beta works the same way
last version working properly is v20.10.31

_Originally posted by @gutko in https://github.com/mltframework/shotcut/issues/961#issuecomment-734176377_

**Comment by ddennedy** [comment]
OK, I see it now. Before I did not understand the description. I found the problem change.

**Comment by ddennedy** [comment]
fixed in release 20.11.28
