### ISSUE TITLE
when i click start to start a project the program closes

### ISSUE THREAD

**Issue by nesrox** [mltframework/shotcut#965]
windows and on latest version
i don't know if this bug is for one of the reasons said in the faq page

**Comment by ddennedy** [comment]
Did you use the installer?

**Comment by nesrox** [comment]
i installed it in a different location and now works
this problem is because of installing in a different location

**Comment by nesrox** [comment]
> 
> 
> I just re-tested, and it is working fine for me. You might have a bad install. You can reboot, uninstall, and reinstall.
i installed it in the main location and it works looks like this happens because of installing the program in a custom location
