### ISSUE TITLE
audioloudnessscope.qml: No such file or directory

### ISSUE THREAD

**Issue by eszlari** [mltframework/shotcut#966]
When trying to compile on Linux (Kubuntu 20.10) from git (both on the command line and in Qt Creator), the app crashes at startup with:

```
[Debug  ] <AudioLoudnessScopeWidget::resetQview> begin 
[Warning] <> file:///home/user/src/shotcut/build-shotcut-Desktop-Debug/share/shotcut/audioloudnessscope.qml: No such file or directory
```

**Comment by ddennedy** [comment]
You must make install it. Shotcut locates its QML files relative to the executable.

**Comment by eszlari** [comment]
Maybe this should be added to the README.

**Comment by eszlari** [comment]
btw: Is this the standard way to do it? Or should these be an a `*.qrc` file?

**Comment by ddennedy** [comment]
It is my preference.

**Comment by eszlari** [comment]
I guess you use a scripts for to create symlinks or else it would be cumbersome to debug in Creator?!

**Comment by ddennedy** [comment]
You only need to create the link once per qt version. Not a nuisance to me.
