### ISSUE TITLE
Playlist: after pressing rightmouse button selection is lost 

### ISSUE THREAD

**Issue by megabugman** [mltframework/shotcut#969]
to reproduce select multiple files in playlist, then RMB, select remove.
-> selection is lost, only one item is removed. using the shortcut shift+x works as expected:
![bug](https://user-images.githubusercontent.com/17204819/100553789-3f15ba00-3290-11eb-8e93-b9b9b35d8470.gif)

Win10 20H2; Shotcut 20.11.28

**Comment by ddennedy** [comment]
This only happens on Windows in the Icons view mode.
