### ISSUE TITLE
"Quality-based VBR" WEBM VP8 export broken

### ISSUE THREAD

**Issue by gutko** [mltframework/shotcut#970]
WEBM VP8 export with "Quality-based VBR" produces broken file with no video.
20.11.28 win64

**Comment by ddennedy** [comment]
Reports in log `[libvpx @ 0x7f598c002480] Rate control parameters set without a bitrate`
This is due to
```
maxrate=24M
minrate=100k
```
in Other tab inherited from the underlying preset. As a workaround, you can remove those lines.
