### ISSUE TITLE
VP9 1st pass of 2pass export takes too long

### ISSUE THREAD

**Issue by gutko** [mltframework/shotcut#972]
1st pass of VP9 takes same amount of time as 2nd pass. It seems a file defining 1st pass of vp9 is missing in 
C:\Program Files\Shotcut\share\mlt\presets\consumer\avformat
In case of VP8 there is a file "webm-pass1" for this purpose if im correct. no such file for vp9

**Comment by ddennedy** [comment]
I verified the first pass creates a file named something like `test.webm_2pass.log` that it used in the second pass. Also, for me the first is much, much shorter 0:05 compared to 1:07 for my quick test. There is no such thing as "webm-pass1" in the code, presets, or generated XML.
