### ISSUE TITLE
Free memory keeps diminishing while rendering, released only when the job ends or is stopped

### ISSUE THREAD

**Issue by JazzTp** [mltframework/shotcut#977]
shotcut-linux-x86_64-201128.AppImage
Linux Ubuntu 18.04.5

**Free memory keeps diminishing while rendering.
Memory is released only when the jobs ends or is stopped.**

I can only think that maybe Shotcut is _not releasing_ resources (objects created in memory? some imaging data?) allocated to render clips that have _already_ been rendered.

(I don't know if it's actually the case, I'm only **speculating** by the symptoms, I admit that I haven't looked into the source code.
When doing C++ programming, I usually adopted the smart pointers suggested by Bjarne Stroustrup in his C++ book, which limit the existence of a dynamically allocated resource to the scope of existence of the smart pointer, which is actually a template class with the appropriate conversion operators and a destructor which takes care of the dynamically allocated resource.)

-----

Alas, one of four RAM bars died recently in this old PC, I'm not ready to buy a new one right now because before I should investigate what hardware to buy (but I'm in the middle of a relocation, before which I'd really like to finish a long video I'm making *ad honorem*, which I have already split in parts, which I used to be able to render before making them a little bit more complex with material, and now being able to just render again would be _really great_).

**Comment by ddennedy** [comment]
Shotcut (actually MLT when it comes to export), already releases memory as it proceeds whether it looks like that to you or not. The fact of the matter is there are many factors and video is heavy. I do not accept bugs that say it needs to use less memory or go faster.

**Comment by JazzTp** [comment]
> I do not accept bugs that say it needs to use less memory or go faster.

Of course not, and actually **I did not say that it needs to use less memory nor that it has to go faster**, I wouldn't have considered that a possible bug (and BTW I'm the same person who was writing that it is a *great* editor in some place you read some time ago, IDK 1-2 years ago). **I said I need to buy a new computer ASAP after relocating.**

> Shotcut (actually MLT when it comes to export), already releases memory as it proceeds whether it looks like that to you or not. 

You have detailed knowledge of how melt works so it's certainly as you say.

Let me just mention why I opened the issue (I've already solved this rendering problem BTW):

- A loop running the bash command `free` every 10 seconds shows progressively less free memory.
- At most, I've seen the number go back up 1 MByte, and very rarely.
- Each time I added material to the timeline, the number went to a lower minimum value.
- When the number goes down below a certain limit, the current version of Shotcut warns about free memory running low.
- When the process ends or is stopped, free memory goes back **all at once** to what it was at the beginning of the render.

**That doesn't *look like* a progressive release of memory**.  
**I'm not saying that it isn't happening, only that I had strong elements to think "it's possibly not happening".**

This boils down to: **melt *is* taking up more and more memory as the render is progressing, maybe it also releases what's *possible* to release or it would be taking up *more* memory otherwise, and it's *certainly* so if you say so** and have closed this issue.

Best regards

**Comment by bmatherly** [comment]
MLT uses a caching memory management system so that it can reuse memory that it has previously allocated. This technique improves speed performance. A side effect is that from the operating system perspective, it looks like MLT never frees memory - because MLT is holding it to reuse it. This is by design to achieve a performance benefit. The behavior you are describing is expected.

I hope you can find a good deal on some RAM to get you PC back in working order.

**Comment by JazzTp** [comment]
> MLT uses a caching memory management system so that it can reuse memory that it has previously allocated. This technique improves speed performance. A side effect is that from the operating system perspective, it looks like MLT never frees memory - because MLT is holding it to reuse it. This is by design to achieve a performance benefit. The behavior you are describing is expected.

Thank you for taking the time to explain.  
Great! That certainly implies a benefit for other processes running on the OS as well.


> I hope you can find a good deal on some RAM to get you PC back in working order.

Thanks, LOL, I *really* need to buy a faster one for plenty of things I need to do, I'll keep this one for lower requirements tasks.

Best regards.
