### ISSUE TITLE
NSIS installer not using /D correctly

### ISSUE THREAD

**Issue by jjurkus** [mltframework/shotcut#98]
If I install Shotcut silently, via /S /D it installs into the wrong directory:
shotcut-win64-150702.exe /S /D=c:\test
The expected behaviour is to install into c:\test, but Shotcut gets installed into c:\test\shotcut

This is not very urgent, as Shotcut installs into the correct directory without using /D.

**Comment by ddennedy** [comment]
I don't care too much about it. So, if you want it fixed send a pull request or patch or clearly show the changes.

**Comment by jjurkus** [comment]
Not a problem.
However, it will take some time before I can send in a patch. Github is like a smartphone to me, I could not even find out how to add a label :-(
And NSIS isn't my strong point. But I might get to it eventually.
