### ISSUE TITLE
Crash after selecting audio filter

### ISSUE THREAD

**Issue by langfeld** [mltframework/shotcut#980]
First of all, I would like to say how grateful I am for this great program. It has allowed me to do a hobby that I would not have been able to do easily with the expensive programs.

However, I do have one problem:
The following error occurs regularly and I can reproduce it at any time:

1. open video file
2. separate audio and video
3. add another audio track (copy of the previous track)
4. put a filter (NoiseGate) on one of the two tracks
5. select another audio track
6. crash to desktop

I use the version 20.11.28 (AppImage)
on Linux Mint 20 Cinnamon

**Comment by ddennedy** [comment]
Thank you for the compliment and bug report, but I have not reproduced it yet.
What is "(copy of the previous track)"? I assume you mean to copy the audio clip to second audio track A2?
I assume between 1. and 2. you added the video clip to the timeline. I also assume when you say you put a filter on the track, that you literally mean the track and not the clip on the audio track (click the track header to select the track and add filter to the whole track). But I tried both the track and the clip on 20.11.28 AppImage on Ubuntu 20.04. Can you please repeat the steps yourself and see if there is more detail you can add (or make a screen recording)?

**Comment by langfeld** [comment]
Hi ddennedy,
I have now tested it again extensively. The problem always occurs when I call up a previously saved entry in NoiseGate.

I have created a screen recording of this:
![output](https://user-images.githubusercontent.com/48012778/102530368-74e4dc00-40a1-11eb-9525-63a900411c35.gif)

**Comment by ddennedy** [comment]
Thanks. I still could not reproduce it. Maybe it is a problem specific to your custom preset. You can share it. Can you reproduce it a simpler way by simply opening a clip, not adding it to the timeline and skipping all those extra steps in the timeline, and simply add the filter with the clip in source player and choose preset?

**Comment by langfeld** [comment]
In fact, applying the filter to a clip and then selecting one of my presets is also enough. As soon as I drag the clip into the timeline, Shotcut crashes. How can I export the preset?

**Comment by ddennedy** [comment]
Settings > App Data Directory > Show > presets > ladspa.1410

**Comment by langfeld** [comment]
Thanks. Here we go:
[ladspa.1410.zip](https://github.com/mltframework/shotcut/files/5712175/ladspa.1410.zip)
However, I can also reproduce it with the default preset.

**Comment by langfeld** [comment]
I have now started the AppImage via the terminal. Maybe this helps?

[Debug  ] <TimelineDock::setSelection> Changing selection to (QPoint(0,0))  trackIndex -1 isMultitrack false 
[Info   ] <Util::isMemoryLow> available RAM =  58771092 KB 
[Debug  ] <autosaveTask> Function autosaveTask finished in 3 ms.
[Debug  ] <Timeline::DetachAudioCommand::redo> trackIndex 0 clipIndex 0 position 0 
[Debug  ] <TimelineDock::setSelection> Changing selection to ()  trackIndex -1 isMultitrack false 
Segmentation fault (core dumped)

**Comment by luzpaz** [comment]
@langfeld can you still reproduce this on latest stable ?

**Comment by langfeld** [comment]
No, it now works fine, Thank you very much :+1:
