### ISSUE TITLE
Audio balance filter has no effect

### ISSUE THREAD

**Issue by mxa** [mltframework/shotcut#983]
Kubuntu 20.10, Shotcut 20.11.28

The balance audio filter has no effect, applied to the whole track or an element on that track. Tried it with or without Jack.
There is no effect in the shotcut itself and also not in the exported file. The audio stays centered. Looking at the meters in Shotcut it looks right, but the PulseAudio or Jack output everything is centered again.

**Comment by ddennedy** [comment]
I am not reproducing a problem using a stereo source with stereo output.

**Comment by mxa** [comment]
Uhm, sorry for that. Works as expected with another soundcard. Seems to be something here in my setup.
