### ISSUE TITLE
Bug: time when dragging jumps from 0:30 sec to 1:00 sec (cannot drag and scroll from 0:31 sec to 0:59 sec).

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [mltframework/shotcut#985]
Ubuntu 20.04   
Shotcut 20.11.28

Add anything. Try to drag its right edge in or out. It is impossible to drag to any numerical value from 0:31 to 0:59. As you drag right, it will go from 0:30 (half second) directly to 1:00 (full second).

In the image below, drag this to 2:30, and then one more tiny increment right goes straight to 3:00.

![image](https://user-images.githubusercontent.com/6842199/102682991-70442480-4182-11eb-8057-49ae40fd662c.png)

**Comment by ddennedy** [comment]
This is normal and by design. The last part of the time is frames, not seconds. Hours:minutes:seconds:frames

**Comment by ElectricRCAircraftGuy** [comment]
> This is normal and by design. The last part of the time is frames, not seconds. Hours:minutes:seconds:frames
Or possibly you misunderstand Settings > Video Mode

I see. This makes sense now. I found more info. about Video Mode here: https://forum.shotcut.org/t/video-mode/12790.

To make it obvious that it is Hours:minutes:seconds:frames, I suggest you add that information here, either always, or just when hovering over the time:

```
00:11:20:24
H:M:S:frames
```

![Uploading image.png…]()

**Comment by ElectricRCAircraftGuy** [comment]
It should also have an `hours:minutes:seconds:frames` tip popup when hovering over the Duration value and setting duration in filters:

![image](https://user-images.githubusercontent.com/6842199/102698937-f2216580-41f5-11eb-9a9e-e5c0996a68e7.png)

**Comment by ddennedy** [comment]
OK, I will add to tooltips but not always shown because often that space is too cramped and not going to reorganize this area yet.
