### ISSUE TITLE
Nearly one second is frozen after a cut

### ISSUE THREAD

**Issue by PontiacCZ** [mltframework/shotcut#987]
Steps to reproduce:

1. Download this 18-second video - https://uloz.to/file/DRkfa60ecVdz/aircraft-mts . Play the video on your computer, it should play smooth.
2. Open a new project in Shotcut, leave video mode on automatic, no proxy.
3. Import the aircraft.mts into the Playlist
4. In the Source player set the IN point to 15:10 and leave the OUT point at 18:10 (that makes a 3 sec clip)
5. Put this 3-sec clip TWO times on the timeline so that we have one cut (that will be enough for our need)
Your Shotcut should look like this now:

![image](https://user-images.githubusercontent.com/9153595/102723695-0ce4fe80-430a-11eb-9084-dcc2cfd03d29.png)

6. Now play the video on the Timeline and focus on the cut between these two clips - **right after the cut the video is frozen for about one second**.
7. Export the video to MJPEG - the same is in the exported file.

---
Windows 10 Pro, version 2004
Shotcut 20.11.28

**Comment by ddennedy** [comment]
Not everything seeks well. mts file is notorious. You can use Properties > Convert

**Comment by PontiacCZ** [comment]
Oh, so you mean it is fault of the MTS file? OK. I'll try the Convert function, thank you. :-)
