### ISSUE TITLE
converting a clip with detached audio makes the clip black on the timeline

### ISSUE THREAD

**Issue by PontiacCZ** [mltframework/shotcut#988]
Steps to reproduce:

1. Download this 18-second video - https://uloz.to/file/DRkfa60ecVdz/aircraft-mts . 
2. Open a new project in Shotcut, leave video mode on automatic, no proxy.
3. Drag the downloaded `aircraft.MTS` directly to the timeline.
4. Right click the clip on the Timeline -> click `More` -> `Detach audio`. Shotcut creates an A1 audio track and puts the detached audio in it.
5. In the Properties tab, click `Convert` button to get the "Convert to Edit-friendly" dialogue, leave the "Better" option and save the converted clip. Shotcut creates `aircraft - Converted.mov` and replaces the original clip on the timeline with the new one.
6. Play the timeline. The video is black now.
7. The same behavior occurs with an MP4 from different camera brand.

![image](https://user-images.githubusercontent.com/9153595/102775740-b91bf900-438d-11eb-87eb-1f98e9b16d6b.png)

---
Windows 10 Pro, version 2004
Shotcut 20.11.28

**Comment by ddennedy** [comment]
To reproduce it, between steps 4 & 5 you need to select the video clip. Detach selects the new audio clip, and if you leave the audio clip selected it works. To workaround this problem select the replaced video clip and change Properties > Video > Track. The video is there, it was simply not selected correctly upon replacement.

**Comment by PontiacCZ** [comment]
I see. What is this "Track" setting in "Video" tab good for? Do you have any idea why Shotcut sets this to "None" when creating the converted clip?

**Comment by ddennedy** [comment]
Most video container files support multiple audio and video tracks (also known as streams) in them. As you can see,  it is a way to disable the embedded track for the clip object. For example, when you detach the audio, it sets the audio track on the video clip to None. The reason it was changed to None is a bug.

**Comment by PontiacCZ** [comment]
Aha. I thought the "Track 1" in the "Video" tab was actually V1 track on the timeline! That confused me. :-) So it indicates which video track within the source file is used, now I get it. 

OK, so we have a bug here but I guess this is one of the easy ones to fix. :-)
