### ISSUE TITLE
15.07 Crop Filter doesn't keep size or position of clip

### ISSUE THREAD

**Issue by jessedubord** [mltframework/shotcut#99]
See video for example: https://www.youtube.com/watch?v=-x3nDFYl2ps

I'm not sure what the "Center" check box is supposed to do on the Crop filter, but when I try to crop a clip in the timeline, it doesn't keep the clip centered.

(Running Shotcut 15.07 on Ubuntu 15.04 x64 w/ Cinnamon 2.6 desktop environment)

**Comment by ddennedy** [comment]
This is by design. You are asking for a different type of crop, and I don't take feature requests.
