### ISSUE TITLE
Feature request: let Shotcut automatically find moved files when the name hasn't been changed

### ISSUE THREAD

**Issue by brunetton** [mltframework/shotcut#991]
- I've a bunch of videos (almost 50) that have hexadecimal names like `3853231b-8679-45a1-937d-cbd21cf399e6.mov`.
- I moved this directory to another location 
- when I reopened the project, I have the sources not found error message (absolutely intended)

![image](https://user-images.githubusercontent.com/86322/103140416-9fa8e300-46e6-11eb-89f3-7c77d496968d.png)

- but I thought I could precise a folder where to search for source files (like in every audio or video editing software I've used)

Proposal: let the replace file browser be able to select files or folders. If the user select a folder, auto-detect files with the same name in this selected folder.

Shotcut v20.11.28 - Ubuntu

**Comment by ddennedy** [comment]
You can already do that.

**Comment by brunetton** [comment]
Indeed ! I checked again just before your answer and I definitively missed something ! Sorry for the noise

Note to myself: never write a feature request with 4 children screaming around me ;)
