### ISSUE TITLE
Bezier curves keyframe types are almost unusable

### ISSUE THREAD

**Issue by brunetton** [mltframework/shotcut#993]
I'm trying to make a fine-controlled effect (video levels => gamma) with Bezier curves but it seems very buggy

![image](https://user-images.githubusercontent.com/86322/103161551-cac52c80-47e3-11eb-865e-95deb79b44ae.png)
![image](https://user-images.githubusercontent.com/86322/103161559-ef210900-47e3-11eb-9dee-31de860bf889.png)

Shotcut v20.11.28

**Comment by ddennedy** [comment]
I believe these pictures show this report is related to a few cases in the forum about moving keyframes by dragging, and I will track this problem as the same:
https://forum.shotcut.org/t/erratic-audio-volume-keyframe-editing/23738
https://forum.shotcut.org/t/holding-alt-to-lock-value-in-keyframes-is-not-working/22496

**Comment by ddennedy** [comment]
This is fixed for the next version in 1e3e29eb4a733e4f2f151c3fdf7d0813faecdc54
