### ISSUE TITLE
Cancel action when editing an effect curve doesn't cancel last curve edition

### ISSUE THREAD

**Issue by brunetton** [mltframework/shotcut#994]
Another way of saying it: make effects curves (keyframes) edition an undo/redo event

Shotcut v20.11.28

**Comment by ddennedy** [comment]
This is the first item on the [road map](https://shotcut.org/roadmap/), which is an enhancement request and not a hard defect. We only use this space for tracking defects.

**Comment by brunetton** [comment]
> This is the first item on the road map,

I had a look on the roadmap but I didn't got that it was included on "undo/redo support for filters". So, good news ! Thanks

> We only use this space for tracking defects.

Indeed, I've seen your answer on another issue. Sorry for that !

Thanks again
