### ISSUE TITLE
FR: Keyframes edit - allow multiple selection for group edition

### ISSUE THREAD

**Issue by brunetton** [mltframework/shotcut#995]
Sorry if this is a duplicate, I didn't found any similar issue.

I'm using keyframe edition and I wanted to move / delete multiple keyframes at once. Anything like this is mentioned in the [keyboard shortcuts](https://shotcut.org/howtos/keyboard-shortcuts/). 
Is is possible to select more than one keyframe ?

Thanks

Shotcut v20.11.28

**Comment by ddennedy** [comment]
"This tracker is for defects only! For feature requests..."

**Comment by brunetton** [comment]
Sorry! I was in a hurry to finish the film I'm working on and wanted to drop this.
